README.md
Point to Github hosted documentation for easy access to our main documents.
=> Update README with links to docs

filament/src/Froxel.cpp, filament/src/PrecompiledMaterials.h, filament/src/RenderPass.cpp, filament/src/RenderPass.h, filament/src/Renderer.cpp, filament/src/Scene.cpp, filament/src/ShadowMap.cpp, filament/src/View.cpp, filament/src/details/Froxel.h, filament/src/details/Renderer.h, filament/src/details/Scene.h, filament/src/details/ShadowMap.h, filament/src/details/View.h, filament/test/filament_test.cpp
Code maintenance, fix comments, reorder class methods in usage order, remove unused methods and rename some methods for more consistency.
Try to break some dependencies between classes.
Remove unneeded includes.
Fix implementation of  Scene::{getRenderableCount|getLightCount}(), it
was completely busted.
=> Break RenderPass dependency on FView & cleanup

CMakeLists.txt, third_party/libsdl2/tnt/CMakeLists.txt
=> Output libs and binaries to consistent locations across platforms

README.md
This folder is meant to host configuration files that can be imported
in various IDEs. We currently use only CLion
=> Document new ide folder

filament/CMakeLists.txt, filament/src/Froxelizer.cpp, filament/src/View.cpp, filament/src/details/Froxelizer.h, filament/src/details/View.h, filament/test/filament_test.cpp
Also match the file name to the class name.
=> Rename FroxelData to Froxelizer

filament/CMakeLists.txt, filament/src/Froxelizer.cpp, filament/src/Intersections.h, filament/src/details/Froxelizer.h
since the code is generic enough, move
sphere-plane and sphere-cone intersection tests
to their own header.
=> move intersection tests to their own headers

third_party/spirv-tools/CMakeLists.txt
=> Don't require Python to build

CMakeLists.txt
=> Detect GCC before attempting a build

docs/Filament.md.html
I changed
> We will provided
to 
> We will provide
=> Fix typo in overview.

libs/utils/include/utils/RangeSet.h
=> MSVC's STL doesn't let iterators go before begin()

tools/cmgen/tests/test_cmgen.cpp
We use a white furnace to test that spherical harmonics are properly computed.
=> Add spherical harmonics extraction test

libs/math/include/math/vec3.h, libs/math/include/math/vec4.h
=> add more pseudo vector swizzle to lib math

filament/src/driver/opengl/ContextManagerWGL.cpp, libs/bluegl/tests/OpenGLSupport.cpp, libs/bluegl/tests/test_bluegl.cpp
We need to make the context current and request a core profile.
=> Fix test_bluegl on macOS and Windows

filament/src/Froxelizer.cpp, filament/src/Scene.cpp, filament/src/View.cpp, filament/src/details/Froxelizer.h, filament/src/details/Scene.h, libs/utils/CMakeLists.txt, libs/utils/include/utils/BinaryTreeArray.h, libs/utils/include/utils/algorithm.h, libs/utils/test/test_BinaryTreeArray.cpp, samples/lightbulb.cpp
[DO NOT SQUASH when merging -- thanks]
=> ground work for calculating binary light trees

tools/tungsten/core/src/com/google/android/filament/tungsten/model/Graph.kt
=> Tungsten: use single-line functions where possible

docs/Filament.md.html
Thank you for the wonderful documentation of Filament! I've learned so much from it already 👍 
I noticed three small spelling mistakes in it which I address in this pull request.
Kind regards,
Tim
=> Fixed three small spelling mistakes in the documentation

filament/include/filament/Engine.h, filament/src/Engine.cpp, filament/src/Fence.cpp, filament/src/Renderer.cpp, filament/src/details/Engine.h, filament/src/driver/CommandBufferQueue.cpp, filament/src/driver/CommandBufferQueue.h, libs/utils/include/utils/compiler.h, libs/utils/src/JobSystem.cpp, samples/app/FilamentApp.cpp
This reverts commit e3457aa0a79f5345e5b847a523f91c2259fec4f5.
It causes a crash for Romain.  I haven't been able to repro yet.
=> Revert "Add single-threaded config to Filament. (#130)"

filament/CMakeLists.txt, filament/README.md, libs/bluegl/CMakeLists.txt, libs/bluevk/CMakeLists.txt, libs/filaflat/CMakeLists.txt, libs/filamat/CMakeLists.txt, tools/filamesh/CMakeLists.txt, tools/matinfo/CMakeLists.txt, tools/normal-blending/CMakeLists.txt, tools/roughness-prefilter/CMakeLists.txt, tools/skygen/CMakeLists.txt, tools/specular-color/CMakeLists.txt
Includes various other cleanups:
- Add READMEs for installed binaries
- Don't install includes that are not useful to 3p apps
This closes #147
=> Install BlueGL

filament/include/filament/Engine.h, filament/src/Engine.cpp, filament/src/Fence.cpp, filament/src/Renderer.cpp, filament/src/details/Engine.h, filament/src/driver/CommandBufferQueue.cpp, filament/src/driver/CommandBufferQueue.h, libs/utils/include/utils/compiler.h, libs/utils/src/JobSystem.cpp, samples/app/FilamentApp.cpp
=> Revert the revert, and proper fix.

libs/imageio/src/ImageDecoder.cpp, third_party/tinyexr/tinyexr.h, third_party/tinyexr/tnt/README.md
See also #176.
This closes #166.
=> Minor improvements to EXR decoding.

tools/tungsten/core/src/com/google/android/filament/tungsten/model/Properties.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/model/serialization/Graph.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/model/serialization/GraphSerializer.kt, tools/tungsten/core/test/com/google/android/filament/tungsten/model/serialization/GraphSerializerTest.kt
Property values are now serialized.
=> Tungsten: Introduce property serialization

android/filament-android/src/main/cpp/Engine.cpp, android/filament-android/src/main/cpp/EntityManager.cpp, android/filament-android/src/main/java/com/google/android/filament/Engine.java, android/filament-android/src/main/java/com/google/android/filament/EntityManager.java, android/samples/hello-triangle/app/src/main/java/com/google/android/filament/hellotriangle/MainActivity.kt
=> Add Engine.destroyEntity/cleanup JNI

java/CMakeLists.txt
=> Compile Java APIs against Java 1.8

tools/cmgen/src/CubemapUtils.cpp
=> Fix cubemap mirroring

samples/web/suzanne.cpp
This was causing an assert with debug builds.
=> Suzanne fixup: create entities for point lights.

tools/cmgen/src/CubemapIBL.cpp
We were doing a divide-by-zero in a case where
the result wasn’t used.
=> fix divide-by-zero in cmgen (#201)

filament/src/Scene.cpp
SIMD code is accessing uninitialized elements,
so make sure they are initialized enough to avoid
divide-by-zero.
We were also processing the directional light in
computeLightRanges(), which always has a zero
radius.
=> fix #201 Division by zero in FScene::computeLightRanges

samples/web/filaweb.js, samples/web/suzanne.html, samples/web/triangle.html
You need a really small finger or stylus, but at least it works.  :)
=> WebGL: support touch screens.

samples/material_sandbox.h, samples/web/filaweb.cpp, samples/web/filaweb.h, samples/web/sandbox.cpp, samples/web/suzanne.cpp, samples/web/triangle.cpp
This also moves some implementation from `filaweb.h` to `filaweb.cpp`
=> High-to-Low includes, per our style guidelines.

libs/filabridge/include/private/filament/Variant.h
Update comment so the labels match the description.
=> Update comment in Variant.h

tools/tungsten/core/src/com/google/android/filament/tungsten/ui/MaterialGraphComponent.kt
Fixes a few bugs that occur when dragging nodes around the material graph.
=> Tungsten: fix a couple view-related bugs

docs/Filament.md.html
=> better explication of the “split-sum”

tools/mipgen/src/main.cpp
The libimage API does not include the original image in the returned mip
array, which might make sense when generating individual files, but for
a KTX bundle, we want to include level 0.
=> Fix mipgen issue where mip 0 was missing from KTX.

samples/lightbulb.cpp, samples/material_sandbox.cpp
=> fix normals of the shadow plane.

tools/tungsten/core/src/com/google/android/filament/tungsten/model/Properties.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/properties/PropertyEditors.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/texture/TextureCache.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/texture/TextureUtils.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/ui/GraphPresenter.java
=> Tungsten: add color space option to texture chooser

tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/Expression.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/GraphCompiler.java, tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/GraphFormatter.java, tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/NodeRegistry.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/model/Graph.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/model/MathNodes.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/model/Nodes.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/model/Properties.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/properties/PropertyEditors.kt, tools/tungsten/core/test/com/google/android/filament/tungsten/model/NodeTest.kt
* Added normal input to shader node
* Added constant float node
* Add multiply, subtract, and divide math nodes,
=> Tungsten: normal mapping capabilities

tools/cmgen/src/cmgen.cpp
For each envmap/skybox pair, this will reduce the number of downloads from 61 files to 3 files.
Note that we are still using sh.txt for coefficients, I'll see if it would be easy to embed that in the KTX metadata.
Also, I will add KTX support to roughness-prefilter soon.
=> The cmgen tool can now generate KTX files.

libs/image/src/KtxBundle.cpp
This will make uploading KTX cubemaps to the GPU easier and more efficient.
=> KtxBundle now uses contiguous memory for blobs.

tools/cmgen/src/CubemapUtils.cpp
We use a better calculation of the number of
samples needed for a given texel.
=> improve equirectangular conversion

docs/Materials.md.html
The word 'from' was repeated twice unnecessarily.
=> Removed typo

filament/include/filament/RenderableManager.h, filament/src/components/RenderableManager.cpp, libs/filabridge/src/UibGenerator.cpp, shaders/src/common_math.fs, shaders/src/getters.vs
A full 3x3 + translate matrix is supported.
=> Skinning now supports non-rigid transforms

tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/Expression.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/NodeRegistry.kt, tools/tungsten/core/src/com/google/android/filament/tungsten/model/Nodes.kt
Add three new nodes
- A Time node to return `getTime()`
- A Tex Coord node to return `getUV0()`
- A Texture Panner node which automatically offsets texture coordinates.
Also:
- Use separate float sliders for Float2 and Float3 constant nodes so we can input negative values
=> Add a few new nodes to Tungsten

android/filament-android/build.gradle, android/samples/hello-triangle/build.gradle, android/samples/image-based-lighting/app/src/main/java/com/google/android/filament/ibl/IblLoader.kt, android/samples/image-based-lighting/build.gradle, android/samples/lit-cube/app/src/main/java/com/google/android/filament/litcube/MainActivity.kt, android/samples/lit-cube/build.gradle
Also update Kotlin and Gradle plugin versions
=> Clean up Kotlin samples

libs/filamentjs/CMakeLists.txt, libs/filamentjs/jsbindings.cpp, libs/filamentjs/jsenums.cpp, libs/filamentjs/tests/test.py, libs/filamentjs/tests/testwasm.html, libs/filamentjs/tests/testwasm.js, libs/filamentjs/wasmloader.js
This pull request is composed of several commits, some of which are individual bug fixes. Do not squash.
=> Add more JavaScript bindings.

shaders/src/main.vs
This avoids breaking bitangents when a scale value is set in the
transform matrix
=> Normalize normals and tangents in the vertex shader

libs/filamentjs/CMakeLists.txt, libs/filamentjs/jsbindings.cpp, libs/filamentjs/jsenums.cpp, libs/filamentjs/tests/testwasm.html, libs/filamentjs/tests/testwasm.js, libs/filamentjs/utilities.js, libs/filamentjs/wasmloader.js
The testwasm web page now looks like this:
=> jsbindings: add JS utilities, enhance testwasm.

libs/filamentjs/docs/tutorial_triangle.md, libs/filamentjs/jsbindings.cpp, libs/filamentjs/tests/test.py, libs/filamentjs/tests/testwasm.js
=> jsbindings: add IBL and cubemap support.

libs/filamentjs/docs/build.py, libs/filamentjs/docs/demo_template.html, libs/filamentjs/docs/main.css, libs/filamentjs/docs/tutorial_redball.md, libs/filamentjs/docs/tutorial_triangle.md, libs/filamentjs/jsbindings.cpp
Unlike the triangle tutorial, this is more focused on materials and 3D rendering. While much of the verbiage is still TBD, the code snippets already produce a functional demo after being glued together by the tangler script.
=> Start another literate tutorial / demo for JavaScript.

libs/filamentjs/docs/build.py, libs/filamentjs/docs/plastic.mat, libs/filamentjs/docs/triangle.mat, libs/filamentjs/docs/tutorial_redball.md, libs/filamentjs/docs/tutorial_triangle.md
This commit also adds a help option to `build.py` and allows
customization of the output folder.
=> The redball tutorial now describes matc and cmgen.

libs/utils/include/utils/RangeSet.h
=> Fix typo in RangeSet

filament/CMakeLists.txt, filament/test/CMakeLists.txt
Will merge after Kokoro succeeds.
=> Fix broken iOS build

libs/filamentjs/tests/test_parquet.js, libs/filamentjs/utilities.js
=> JavaScript PNG utility now has SRGB flag.

libs/utils/include/utils/Allocator.h
Align atomic HeadPtr to 64-bits.
=> Attempt to fix windows build

site/content/webgl/index.md, web/docs/CMakeLists.txt, web/docs/build.py, web/docs/demo_template.html, web/docs/textured.mat, web/docs/tutorial_redball.md, web/docs/tutorial_suzanne.md, web/docs/tutorial_triangle.md, web/docs/tutorials.txt, web/samples/CMakeLists.txt
This adds the markdown source but does not update the web site, that will be in a subsequent PR.
=> Add tutorial that describes compression and async loading.

samples/CMakeLists.txt, samples/app/MeshAssimp.cpp, samples/app/MeshAssimp.h, samples/gltf_viewer.cpp, samples/vk_hellopbr.cpp
=> Re-enable glTF support

CODE_STYLE.md, tools/resgen/src/main.cpp
This also adds the std:: qualifier to resgen (see also PR #356)
=> Add style guidelines for strings.

docs/Filament.md.html
Forgot the parenthesis when I corrected it, I'm sorry...
=> EV100 formula typo

samples/app/MeshAssimp.cpp
Changed property and texture names and indices to constants defined in pbrmaterial.h from Assimp.
=> Changed MeshAssimp.cpp to use constants defined in Assimp

samples/app/MeshAssimp.cpp
We started to write our own implementation of mikktspace, but it required an unindexed mesh for input. This was awkward because assimp is already applying a pipeline of operations that includes tangent generation and indexing. It felt redundant to add our own pipeline on top of that (unindexing => tangentgen => reindexing).
Since assimp's CalcTangentsProcess method is already producing tangents that follow the orientation implied by texture coordinates, this simply needs to be tweaked to match glTF. (flip the bitangent)
Flipping the bitangent seems to have no apparent effect on anisotropic lighting; for example see the attached before/after screenshots with the material_sphere. I confirmed with a printf that this *does* trigger the affected code path.
Also fixed a bug for the case where …
=> Fix up tangents in MeshAssimp to help with #528.

tools/resgen/src/main.cpp
This adds a couple optional features:
1) Preserve file extensions when generating symbols.
This is useful to distinguish `foo.vs` from `foo.fs`
2) Append null characters to data blobs.
Useful when treating `FOO_DATA` as a C string.
=> Minor resgen improvements.

filament/include/filament/Texture.h, libs/filabridge/include/filament/driver/DriverEnums.h, libs/image/include/image/KtxUtility.h, tools/mipgen/src/main.cpp, web/filament-js/jsbindings.cpp, web/filament-js/utilities.js
This makes it easier for C++ clients to use KTX files and simplifies the JavaScript bindings.
=> Introduce high-level KTX utility function.

README.md
Removed the extra slash from the URL
=> Removed extra slash

README.md, android/filament-android/build.gradle, build.sh, libs/bluevk/include/bluevk/BlueVK.h
=> Require API level 21, not 24

filament/src/RenderPass.cpp, filament/src/Renderer.cpp, filament/src/details/Renderer.h
We can start the froxelization earlier so it happens during the
shadow pass.
=> Run Froxelization during shadow pass

filament/src/View.cpp, filament/src/details/View.h
the code was structured so light culling and renderable culling could
be done in parallel, but this wasn't implemented.
Clean-up some methods to turn them to static and run light culling
in parallel with renderable culling.
=> parallelize light and renderable culling

docs/Materials.md.html, shaders/src/common_getters.fs
This calculates the modulo of the user time by a given value, using
the high precision user time. This is useful for animations without
having to worry about resetting the time.
=> Add getUserTimeModulo() to materials

filament/src/Engine.cpp, libs/utils/include/utils/JobSystem.h, libs/utils/src/JobSystem.cpp
this is to try to prevent threads from bouncing
between cores
=> set cpu affinity of JobSystem's threads

filament/src/driver/opengl/OpenGLDriver.cpp
there was a very small race, where we would dereference a pointer
that might not be set yet.
=> fix a potential crasher when copying the camera stream

README.md
=> Update README for VS 2017

filament/include/filament/Frustum.h, libs/filabridge/include/filament/driver/DriverEnums.h, libs/utils/CMakeLists.txt
=> Include unwindows in Frustum and DriverEnums

filament/include/filament/LightManager.h
Fixes #661 by removing the doc comments.
=> Removed outdated documentation about static lights

filament/src/Scene.cpp
=> Consider the extra entry for the directional light when rounding up the capacity

filament/src/Engine.cpp
=> Destroy engine's default material

libs/filameshio/include/filameshio/MeshReader.h, libs/filameshio/src/MeshReader.cpp, web/filament-js/extensions.js, web/filament-js/jsbindings.cpp
=> JS API: loadFilamesh can now return material names.

tools/filamesh/src/main.cpp
filamesh requires UV's but some glTF test models, like CesiumMilkTruck,
do not provide UV's on nonlit parts (e.g. the truck windows). This makes
it so that these assets can be converted to filamesh somewhat more
gracefully.
=> filamesh tool now generates dummy UV's if necessary.

filament/src/View.cpp, libs/filabridge/include/private/filament/UibGenerator.h, libs/filabridge/src/UibGenerator.cpp, shaders/src/common_getters.fs
=> Add missing getWorldFromClip() API

ios/samples/hello-triangle/hello-triangle.xcodeproj/project.pbxproj
iOS sample needs smol-v dependency
=> Fix iOS hello-triangle sample

android/samples/image-based-lighting/app/src/main/java/com/google/android/filament/ibl/IblLoader.kt, android/samples/textured-object/app/src/main/java/com/google/android/filament/textured/IblLoader.kt
=> Peek the right dimensions for the IBL in Android samples

samples/CMakeLists.txt, samples/app/FilamentApp.cpp, samples/app/NativeWindowHelper.h, samples/app/NativeWindowHelperCocoa.mm
When we resize the window, we should update the Metal layer's `drawableSize`.
=> Update Metal layer upon window resize 

filament/src/driver/vulkan/VulkanDriverImpl.cpp
These changes are sufficient to resurrect Vulkan-on-macOS, at least for
the vk_hellopbr sample.
=> Update MoltenVK and tweak queue selection strategy.

shaders/src/fxaa.fs
=> Work around FXAA issue with Vulkan Adreno drivers.

libs/imageio/src/ImageEncoder.cpp
=> Property write small .hdr files

filament/include/filament/Texture.h, filament/src/Texture.cpp, filament/src/driver/DriverAPI.inc, filament/src/driver/metal/MetalDriver.mm, filament/src/driver/opengl/OpenGLDriver.cpp, filament/src/driver/opengl/OpenGLDriver.h, filament/src/driver/vulkan/VulkanDriver.cpp, samples/CMakeLists.txt, samples/suzanne.cpp
This is carefully composed of 4 commits, please do not squash.  Partial fix for #749.
=>  Replace glGenMipmap with our own implementation.

filament/include/filament/RenderableManager.h, filament/src/components/RenderableManager.cpp
=> Skinning: fix buffer overrun for non-zero bone offsets.

filament/src/components/RenderableManager.cpp
This fixes an INVALID_OPERATION at draw call time with skinned
renderables. We do not see this error with Adreno drivers, but we saw it
with WebGL, and technically our usage was not spec compliant.
Motivated by #764
=> Fix GL error seen with skinning due to UBO size.

web/filament-js/jsbindings.cpp, web/samples/CMakeLists.txt, web/samples/skinning.html, web/samples/triangle.html
This demo does not use glTF, but it is heavily inspired by `gltfTutorial_019_SimpleSkin`.
Fixes #764.
=> Add skinning demo.

filament/src/driver/metal/MetalEnums.h
Add a bunch of enum conversions from Filament types to Metal.
=> Add Metal enums

filament/CMakeLists.txt, filament/src/driver/metal/MetalHandles.h, filament/src/driver/metal/MetalHandles.mm
Add Metal-specific handle subclasses. These will be alloc-ed and used by `MetalDriver`.
=> Add Metal handle classes

filament/src/driver/vulkan/PlatformVkCocoa.mm, samples/app/FilamentApp.cpp, samples/app/NativeWindowHelper.h, samples/app/NativeWindowHelperCocoa.mm
Metal's swapchain is a `CAMetalLayer`, while Vulkan's is an `NSView`.
=> Handle swapchain creation for Metal in FilamentApp

android/filament-android/src/main/cpp/VertexBuffer.cpp, android/filament-android/src/main/java/com/google/android/filament/VertexBuffer.java, filament/include/filament/VertexBuffer.h, filament/src/VertexBuffer.cpp
I did not test this but the JNI binding seem fairly straightforward.
#695
=> Expose tangent utility to Java / Kotlin.

CMakeLists.txt, build.sh, web/docs/build.py
=> Build web docs only when opting in.

filament/src/PostProcessManager.cpp, filament/src/Renderer.cpp, filament/src/fg/FrameGraph.cpp, filament/src/fg/FrameGraph.h, filament/src/fg/FrameGraphPass.h, filament/src/fg/FrameGraphPassResources.h, filament/src/fg/FrameGraphResource.h, filament/test/filament_framegraph_test.cpp
At this point, I'm happy with the API and implementation. there are still a few todos and we need more tests. But it should be close to the final thing.
=> more work on framegraph

filament/src/driver/metal/MetalDriver.mm
Merging immediately to fix broken master
=> Fix build errors in Metal driver

libs/filamat/tests/test_filamat.cpp
=> Fix wrong init method being called

tools/cmgen/src/CubemapIBL.cpp
also added uniform hemisphere sampling function for reference.
=> minor code and comments cleanups in dfg computations

filament/src/driver/vulkan/PlatformVkWindows.cpp
=> Fix Vulkan swapchain size on Windows

android/filamat-android/src/main/cpp/MaterialBuilder.cpp, android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java
This exposes the rest of the MaterialBuilder API to JNI.
=> Complete the MaterialBuilder JNI

ios/samples/README.md
Update README with Metal and new sample.
=> Update iOS samples README

android/filament-android/src/main/java/com/google/android/filament/android/UiHelper.java
=> Add missing call to surfaceChanged()

filament/src/driver/opengl/OpenGLDriver.cpp, filament/src/driver/opengl/OpenGLDriver.h, libs/filabridge/include/filament/driver/DriverEnums.h
Very much untested, but it should work!
=> more support for 2D texture arrays in the driver

filament/src/driver/metal/MetalContext.h, filament/src/driver/metal/MetalDriver.mm, filament/src/driver/metal/MetalHandles.h, filament/src/driver/metal/MetalHandles.mm, filament/src/driver/metal/MetalState.h, filament/src/driver/metal/MetalState.mm
=> Implement MSAA for Metal

libs/gltfio/src/Animator.cpp, libs/gltfio/src/math.h
- Add support for CUBICSPLINE and STEP interpolation methods.
- Use cgltf_accessor_read_float() instead of manually unpacking values.
- Fix potential NaN in decomposeMatrix.
- Reduce malloc churn by stashing the vector of bone matrices.
=> Finalize the Animator implementation.

filament/src/fg/FrameGraph.cpp, filament/src/fg/FrameGraph.h
We make sure it invalidate the 'from' handle.
=> improve moveResource()

libs/gltfio/include/gltfio/FilamentAsset.h, libs/gltfio/src/Animator.cpp, libs/gltfio/src/AssetLoader.cpp, libs/gltfio/src/FFilamentAsset.h, libs/gltfio/src/ResourceLoader.cpp
=> Add support for glb files.

tools/cmgen/src/CubemapIBL.cpp
As discussed offline with @romainguy, this is a proposition of importance sampling based on the Charlie distribution.
Comparing the values of the generated textures in both cases, it looks all good but this might require more in engine testing.
The sampling method as not been put by default to ease the testing without impact: https://github.com/google/filament/compare/google:master...sebavan:master#diff-a4a7927a3d47229762f1933aac649674R993
Do not hesitate to close/modify if not relevant.
=> Add Charlie importance sampling to cmgen.exe

libs/gltfio/src/AssetLoader.cpp
This model looks okay now I think, except that the bus momentarily has bad geometry during the animation, which I will look into next.
=> gltfio: fix UV set issue seen in littlest_tokyo

site/content/webgl/index.md, web/filament-js/jsbindings.cpp, web/samples/helmet.html
Add shadows to the FlightHelmet demo, add a link to it on the site,
and add recently-introduced entry points to the JS bindings.
=> Various JavaScript updates.

libs/gltfio/include/gltfio/SimpleViewer.h, samples/app/FilamentApp.cpp, samples/app/FilamentApp.h, samples/gltf_viewer.cpp
We might soon be migrating from SDL to GLFW, which thankfully also has support for drag-and-drop.
=> gltf_viewer: add support for drag-and-drop.

android/samples/image-based-lighting/app/build.gradle, android/samples/material-builder/app/build.gradle, android/samples/textured-object/app/build.gradle
=> Fix Android samples

libs/utils/include/utils/compiler.h
=> Use proper "restrict" syntax on visual studio

libs/ibl/CMakeLists.txt, libs/ibl/include/ibl/CubemapUtils.h, libs/ibl/src/CubemapIBL.cpp, libs/ibl/src/CubemapSH.cpp, libs/ibl/src/CubemapUtils.cpp, libs/ibl/src/CubemapUtilsImpl.h
=> remove dependency on JobSystem.h in public header

libs/ibl/src/CubemapUtilsImpl.h
remove dependency on JobSystem.h in public header
this should fix #995
=> oops fix build, missed file.

android/samples/README.md, android/samples/material-builder/README.md
=> Add additional documentation on filamat flag for material builder sample

filament/src/driver/vulkan/VulkanDriver.cpp, filament/src/driver/vulkan/VulkanDriverImpl.cpp, filament/src/driver/vulkan/VulkanDriverImpl.h, filament/src/driver/vulkan/VulkanHandles.cpp
Remove unnecessary depth attachment on the swap chain, introduce a "work" command buffer, etc.  This does not change anything major, it is just prep work.
=> Miscellaneous Vulkan refactoring.

filament/backend/src/metal/MetalDriver.mm
This fixes the rendering issues with gltf_viewer and the Bistro scene.
=> Implement mipmap generation for Metal backends

filament/backend/include/private/backend/DriverAPI.inc, filament/backend/src/metal/MetalDriver.mm, filament/backend/src/opengl/OpenGLDriver.cpp, filament/backend/src/vulkan/VulkanDriver.cpp, filament/src/MaterialInstance.cpp, filament/src/PostProcessManager.cpp, filament/src/Scene.cpp, filament/src/View.cpp, filament/src/components/RenderableManager.cpp
This is to make it more evident that uploading a buffer
partially, doesn't keep its content and the back of the buffer
becomes undefined.
=> rename updateUniformBuffer to loadUniformBuffer

web/filament-js/jsbindings.cpp
=> Fix setCustomProjection JS binding.

samples/CMakeLists.txt, samples/material_sandbox.cpp, samples/material_sandbox.h, samples/materials/sandboxSpecGloss.mat
=> Add specular-glossiness to material_sandbox.

CMakeLists.txt, libs/filamat/README.md
- Build filamat for iOS
- Add README / walkthrough for linking against Filamat
=> Add Filamat documentation

filament/src/ShadowMap.cpp, filament/src/details/ShadowMap.h
Use a better and simpler algorithm that has less error.
=> Switch back triangle/segment intersection to float

filament/src/RenderPass.cpp, filament/src/RenderPass.h, filament/src/Renderer.cpp
We were not committing the frozen data UBOs. This broke recently.
Fixes: #1119
=> Fix dynamic lighting

filament/backend/include/backend/DriverEnums.h, filament/backend/src/opengl/GLUtils.h, filament/backend/src/opengl/OpenGLDriver.cpp, filament/src/ShadowMap.cpp, filament/src/fg/FrameGraph.cpp, filament/src/fg/FrameGraph.h
We need to load the content of the resolved texture at
beginRenderPass time.
=> Emulate better EXT_multisampled_render_to_texture

filament/backend/src/vulkan/VulkanBinder.h, libs/utils/include/utils/compiler.h
=> support compilers that don't have attribute(packed)

filament/backend/src/opengl/OpenGLDriver.cpp
- use the clear flags to skip the clear code earlier
- better detection of the msaa RenderTarger with non msaa attachments
=> fix minor issues

RELEASE_NOTES.md
this is intended to help creating releases. this
file should be updated each time a commit is significant enough that it should be mentioned in
release notes.
when doing code reviews, reviewers should take this into account for approval.
=> release notes file.

filament/src/fg/FrameGraph.cpp, filament/src/fg/FrameGraph.h, filament/src/fg/FrameGraphPassResources.h
- can now return the name of a pass in setup or execute
- can easily retrieve a rsrc descriptor in setup
=> framegraph improvements

RELEASE_NOTES.md, filament/backend/src/metal/MetalContext.h, filament/backend/src/metal/MetalDefines.h, filament/backend/src/metal/MetalDriver.mm, filament/backend/src/metal/MetalHandles.h, filament/backend/src/metal/MetalHandles.mm
Add hard fence support to Metal backend.
=> Implement Metal fences

filament/CMakeLists.txt, filament/src/Engine.cpp, filament/src/MaterialInstance.cpp, filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/RenderPass.cpp, filament/src/RenderPass.h, filament/src/Renderer.cpp, filament/src/ShadowMap.cpp, filament/src/View.cpp, filament/src/details/Engine.h, filament/src/details/MaterialInstance.h, filament/src/details/Renderer.h, filament/src/details/View.h, filament/src/materials/ssao.mat, filament/tools/CMakeLists.txt, filament/tools/ssaogen.cpp, libs/filabridge/include/private/filament/SibGenerator.h, libs/filabridge/src/SibGenerator.cpp, samples/material_sandbox.cpp, shaders/src/light_indirect.fs
This adds basic support for SSAO. Currently performance doesn't scale very well, and the result is noisy.  This is still work in progress, but good enough for testing on various targets and backends.
No SSAO:
With SSAO:
=> Implement basic SSAO

libs/gltfio/src/AssetPipeline.cpp
This feature consumes a flattened glTF asset and produces a glTF asset with new topology and an additional set of UV coordinates suitable for baking light maps.
I verified with a couple glTF models that the generated assets are visually equivalent to the source assets, even though the topology and scene hierarchy is different.
The actual light baking is not yet implemented, but this is a major step towards that goal.
Below is a visualization of the atlas generated when running FlightHelmet through this tool.  This was generated using `XA_DEBUG_EXPORT_ATLAS_IMAGES`.
=> Implement AssetPipeline::parameterize() using xatlas.

.gitignore, libs/filagui/include/filagui/ImGuiHelper.h, libs/gltfio/include/gltfio/SimpleViewer.h, libs/gltfio/src/PathTracer.cpp, libs/gltfio/src/PathTracer.h, libs/image/include/image/LinearImage.h, samples/CMakeLists.txt, samples/app/FilamentApp.cpp, samples/app/FilamentApp.h, samples/gltf_baker.cpp, samples/materials/aoPreview.mat
For now this uses the geometric normals provided by embree rather than the smooth normals that ship with the model, I will fix this next.
=> Add gltf_baker tool and AO computation.

libs/gltfio/include/gltfio/AssetPipeline.h, libs/gltfio/include/gltfio/FilamentAsset.h, libs/gltfio/src/AssetPipeline.cpp, libs/gltfio/src/FFilamentAsset.h, libs/gltfio/src/FilamentAsset.cpp, samples/gltf_baker.cpp
This allows users to load models that have already been flattened & parameterized.
=> gltf_baker: fix needless reload for rendering.

filament/src/Scene.cpp
=>  Remember the highest intensity for directional lights

third_party/cgltf/cgltf_write.h, third_party/xatlas/xatlas.cpp
I'm working on submitting both of these to their upstream projects.
=> Fix memory bugs in third_party.

third_party/xatlas/xatlas.cpp
One of these fixes is already upstreamed, the other is pending.
=> Misc xatlas fixes

filament/backend/src/metal/MetalDriver.mm
=> Fix Metal error when sampler has not been bound

libs/rays/src/PathTracer.cpp
This uses the recently introduced distance field / voronoi functionality to dilate the charts and fill in the blank areas, which successfully fixes cracks in light-baked models. See below for before / after.
=> Light maps are now dilated to remove seams.

filament/src/fg/FrameGraph.cpp
An easy way to do this is to prepend a "+" to the variable.
=> promote uint8_t (i.e. uchar) to printable ints

docs/Filament.md.html
The Jacobian formula display was broken in the cloth IBL section.
=> Corrected minor LaTeX typo

filament/CMakeLists.txt, filament/src/Engine.cpp, filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/fg/FrameGraph.cpp, filament/src/materials/mipmapDepth.mat, filament/src/materials/sao.mat, filament/src/materials/ssao.mat
- we generate LODs for the depth map using the framegraph
- these LODs are used in the SAO shader to improve data access locality
=> SAO now uses a hierarchical depth to improve performance

libs/gltfio/CMakeLists.txt, libs/gltfio/include/gltfio/AssetLoader.h, libs/gltfio/include/gltfio/ResourceLoader.h, libs/gltfio/src/AssetLoader.cpp, libs/gltfio/src/ResourceLoader.cpp, samples/CMakeLists.txt, third_party/stb/stb.c, third_party/stb/tnt/CMakeLists.txt, web/filament-js/jsbindings.cpp
=> Expose gltfio library so it can be used by third_parties

libs/gltfio/include/gltfio/AssetLoader.h, libs/gltfio/include/gltfio/FilamentAsset.h, libs/gltfio/include/gltfio/MaterialProvider.h, libs/gltfio/src/AssetLoader.cpp, libs/gltfio/src/FFilamentAsset.h, libs/gltfio/src/FilamentAsset.cpp, libs/gltfio/src/MaterialGenerator.cpp
=> gltfio: add optional diagnostic shading.

filament/README.md
=> Update README with CoreVideo flag

android/samples/image-based-lighting/app/src/main/AndroidManifest.xml
this allows us to use snapdragon profiler
=> give internet permission to ibl sample

filament/backend/src/metal/MetalResourceTracker.h, tools/filamesh/src/MeshWriter.cpp
=> Use a 32 bit index buffer when necessary

RELEASE_NOTES.md, android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/CMakeLists.txt, filament/include/filament/View.h, filament/src/Engine.cpp, filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/materials/blur.mat, filament/src/materials/mipmapDepth.mat, filament/src/materials/sao.mat, filament/src/materials/ssao.mat, filament/tools/ssaogen.cpp
The biggest improvement is the addition of a blur pass
=> Lots of SSAO improvements

android/filament-android/CMakeLists.txt, android/filament-android/src/main/cpp/Engine.cpp, android/filament-android/src/main/cpp/RenderTarget.cpp, android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/Engine.java, android/filament-android/src/main/java/com/google/android/filament/RenderTarget.java, android/filament-android/src/main/java/com/google/android/filament/View.java, java/filament/CMakeLists.txt
New Kotlin sample app is forthcoming.
=> Add JNI bindings for RenderTarget.

RELEASE_NOTES.md, libs/geometry/src/SurfaceOrientation.cpp
=> geometry: tweak provided tangents to enforce orthonormality.

android/filament-android/src/main/cpp/IndirectLight.cpp, android/filament-android/src/main/java/com/google/android/filament/IndirectLight.java, docs/Filament.md.html, filament/include/filament/IndirectLight.h, filament/src/IndirectLight.cpp
Also Add IndirectLight::radiance()
=>  improve IndirectLight::irradiance() documentation

shaders/src/depth_main.vs, shaders/src/main.vs, shaders/src/material_inputs.vs
=> Workaround for a Mali driver bug

android/filament-android/src/main/java/com/google/android/filament/android/UiHelper.java
I used the comments as a skeleton and found a couple of typos as I did so
=> Comment fixes for UiHelper

android/filament-android/.idea/codeStyles/codeStyleConfig.xml, android/filament-android/CMakeLists.txt, android/filament-android/src/main/cpp/IndirectLight.cpp, android/filament-android/src/main/cpp/Texture.cpp, android/filament-android/src/main/java/com/google/android/filament/IndirectLight.java, android/filament-android/src/main/java/com/google/android/filament/Texture.java, filament/CMakeLists.txt, filament/backend/include/backend/DriverEnums.h, filament/backend/include/backend/PixelBufferDescriptor.h, filament/include/filament/IndirectLight.h, filament/include/filament/Texture.h, filament/src/IndirectLight.cpp, filament/src/Texture.cpp, filament/src/details/IndirectLight.h, filament/src/details/Texture.h, libs/ibl/CMakeLists.txt, libs/ibl/include/ibl/Cubemap.h, libs/ibl/include/ibl/CubemapIBL.h, libs/ibl/include/ibl/CubemapSH.h, libs/ibl/include/ibl/CubemapUtils.h, libs/ibl/include/ibl/Image.h, libs/ibl/include/ibl/utilities.h, libs/ibl/src/Cubemap.cpp, libs/ibl/src/CubemapIBL.cpp, libs/ibl/src/CubemapSH.cpp, libs/ibl/src/CubemapUtils.cpp, libs/ibl/src/CubemapUtilsImpl.h, samples/app/IBL.cpp, samples/app/IBL.h, tools/cmgen/src/cmgen.cpp
=> Utility to prefilter an environment at runtime 

RELEASE_NOTES.md, web/filament-js/extensions.js, web/filament-js/filament.d.ts, web/filament-js/jsbindings.cpp, web/filament-js/jsenums.cpp
Not yet tested but stay tuned.
=> Add JavaScript / TypeScript support for RenderTarget.

filament/include/filament/Engine.h, filament/src/Engine.cpp
=> Add Engine::destroy(Engine*) to match other APIs

build/toolchain-aarch64-linux-android.cmake, build/toolchain-arm7-linux-android.cmake, build/toolchain-x86-linux-android.cmake, build/toolchain-x86_64-linux-android.cmake
=> Fix Android Toolchain issue on Windows

samples/CMakeLists.txt, samples/materials/pointSprites.mat, samples/point_sprites.cpp
=> Add demo for point sprites and custom attribs.

RELEASE_NOTES.md, web/filament-js/extensions.js
=> gltfio JavaScript: add basePath argument to loadResources.

libs/gltfio/src/ResourceLoader.cpp
Thanks @iamjinge for the fix.
Fixes #1405.
=> gltfio: Fix skinning offset.

libs/ibl/include/ibl/CubemapSH.h, libs/ibl/src/CubemapSH.cpp, libs/ibl/src/CubemapUtils.cpp, tools/cmgen/src/cmgen.cpp
=> Improving cmgen SH with HDR images

libs/utils/src/JobSystem.cpp
if hw thread count was 1, we'd end-up with 32 threads
=> fix thread count initialization

filament/backend/src/metal/MetalState.h
Some structs used as hash keys had hidden padding, which is left in an indeterminate form upon initialization. This changes makes padding bytes explicit so we can zero them.
=> Ensure structs used as Metal state keys have no compiler padding

ios/samples/hello-ar/hello-ar.xcodeproj/xcshareddata/xcschemes/hello-ar OpenGL.xcscheme, ios/samples/hello-ar/hello-ar/FilamentArView/FilamentApp.cpp, ios/samples/hello-ar/hello-ar/FilamentArView/FilamentArViewController.mm, ios/samples/hello-ar/hello-ar/FilamentArView/FilamentView.m, ios/samples/hello-ar/project.yml
The sample now supports both Metal and OpenGL :)
=> Add OpenGL scheme to hello-ar sample app

shaders/src/dithering.fs
=> Add workaround for Adreno Vulkan shader bug.

libs/gltfio/include/gltfio/Animator.h, libs/gltfio/include/gltfio/FilamentAsset.h, libs/gltfio/src/Animator.cpp, libs/gltfio/src/AssetLoader.cpp, libs/gltfio/src/ResourceLoader.cpp
=> Add morphing support to gltfio.

android/filament-android/src/main/cpp/IndirectLight.cpp, android/filament-android/src/main/java/com/google/android/filament/IndirectLight.java, filament/include/filament/IndirectLight.h, filament/src/IndirectLight.cpp, filament/src/details/IndirectLight.h, libs/gltfio/include/gltfio/SimpleViewer.h, samples/material_sandbox.cpp
Initialized the directional light direction to the
IBL direction in material_sandbox and gltf_viewer.
=> API to query the direction of the IBL

android/gltfio-android/src/main/cpp/FilamentAsset.cpp, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java, libs/gltfio/include/gltfio/FilamentAsset.h, libs/gltfio/include/gltfio/SimpleViewer.h, libs/gltfio/src/AssetLoader.cpp, libs/gltfio/src/FFilamentAsset.h, libs/gltfio/src/FilamentAsset.cpp, samples/gltf_baker.cpp, samples/gltf_viewer.cpp, web/filament-js/filament.d.ts, web/filament-js/jsbindings.cpp
=> gltfio: allow names to be queried.

filament/backend/include/private/backend/DriverAPI.inc, filament/backend/src/metal/MetalDriver.mm, filament/backend/src/opengl/OpenGLDriver.cpp, filament/backend/src/vulkan/VulkanDriver.cpp, filament/src/Texture.cpp
=> Add isTextureFormatMipmappable driver query

libs/filamat/src/GLSLPostProcessor.cpp, libs/filamat/src/eiff/DictionarySpirvChunk.cpp, tools/matinfo/src/main.cpp
These features help with diagnosing SPIR-V related issues.
=> filamat and matinfo: add more diagnostics.

filament/src/Texture.cpp
This logic was moved to the drivers.
=> Remove unusued function

android/filament-android/src/main/java/com/google/android/filament/Camera.java, android/filament-android/src/main/java/com/google/android/filament/Engine.java, android/filament-android/src/main/java/com/google/android/filament/EntityManager.java, android/filament-android/src/main/java/com/google/android/filament/Fence.java, android/filament-android/src/main/java/com/google/android/filament/IndexBuffer.java, android/filament-android/src/main/java/com/google/android/filament/IndirectLight.java, android/filament-android/src/main/java/com/google/android/filament/LightManager.java, android/filament-android/src/main/java/com/google/android/filament/Material.java, android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java, android/filament-android/src/main/java/com/google/android/filament/RenderTarget.java, android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java, android/filament-android/src/main/java/com/google/android/filament/Renderer.java, android/filament-android/src/main/java/com/google/android/filament/Scene.java, android/filament-android/src/main/java/com/google/android/filament/Skybox.java, android/filament-android/src/main/java/com/google/android/filament/Stream.java, android/filament-android/src/main/java/com/google/android/filament/SwapChain.java, android/filament-android/src/main/java/com/google/android/filament/Texture.java, android/filament-android/src/main/java/com/google/android/filament/TransformManager.java, android/filament-android/src/main/java/com/google/android/filament/VertexBuffer.java, android/filament-android/src/main/java/com/google/android/filament/View.java
this allows mixed java/native apps to use filament objects on both
sides more easily
=> make getNativeObject() public

CMakeLists.txt, libs/matdbg/CMakeLists.txt, libs/matdbg/include/matdbg/JsonWriter.h, libs/matdbg/include/matdbg/ShaderExtractor.h, libs/matdbg/include/matdbg/ShaderInfo.h, libs/matdbg/include/matdbg/TextWriter.h, libs/matdbg/src/CommonWriter.h, libs/matdbg/src/JsonWriter.cpp, libs/matdbg/src/ShaderExtractor.cpp, libs/matdbg/src/ShaderInfo.cpp, libs/matdbg/src/TextWriter.cpp, tools/matinfo/CMakeLists.txt, tools/matinfo/src/main.cpp
This moves some of the matinfo functionality into a library which will soon have an embedded web server.
=> Introduce matdbg library, simplify matinfo.

tools/tungsten/core/src/com/google/android/filament/tungsten/ui/preview/Ibl.kt
=> Fix Tungsten build

libs/matdbg/src/JsonWriter.cpp, libs/matdbg/web/index.html, libs/matdbg/web/script.js, libs/matdbg/web/style.css
This fixes the unable-to-scroll issue and adds more info to the details panel.
=> matdbg improvements

README.md, RELEASE_NOTES.md, filament/README.md, libs/matdbg/CMakeLists.txt
=> matdbg: add "install" directive.

android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java, android/filament-android/src/main/java/com/google/android/filament/VertexBuffer.java
=> Java bindings now define CUSTOM / MORPH attribs.

filament/backend/include/backend/DriverEnums.h, filament/backend/include/private/backend/CommandStream.h, filament/backend/include/private/backend/Driver.h, filament/backend/src/CommandStream.cpp, libs/utils/include/utils/Profiler.h
=> Fix compilation error when DEBUG_COMMAND_STREAM is true

filament/backend/include/private/backend/DriverAPI.inc
we now handle zero argument declaration in some cases.
=> simplify DriverAPI.inc macros a bit further

filament/src/materials/blur.mat, filament/src/materials/sao.mat
This fixes SSAO rendering in Metal.
=> Convert SSAO shaders to post-process material domain

libs/filagui/CMakeLists.txt, libs/filagui/src/ImGuiHelper.cpp
This makes building samples faster when combined with PR #1613.
=> filagui: use resgen for the UI material.

filament/src/PostProcessManager.cpp
My fault, I did not catch this while reviewing #1621.
=> PostProcessManager: another Vulkan-related re-ordering.

libs/imageio/src/ImageEncoder.cpp
=> Encode sRGB images as sRGB, not linear

filament/backend/src/vulkan/VulkanHandles.cpp
To prevent an excess of variants, sometimes our vertex shaders declare
inputs that they never read from. For example, our skin-and-morph
variant might never read from the skinning attribute, but still declares
the input.
This PR is a sister to #1663, which is a fix for #1525.
See also #1279.
=> Vulkan: use a dummy buffer for missing attributes.

android/filament-android/src/main/cpp/Engine.cpp, android/filament-android/src/main/java/com/google/android/filament/Engine.java, android/filament-android/src/main/java/com/google/android/filament/Fence.java, filament/include/filament/Engine.h, filament/include/filament/Fence.h, filament/src/Engine.cpp, filament/src/FrameInfo.cpp, filament/src/FrameInfo.h, filament/src/FrameSkipper.cpp, filament/src/Renderer.cpp, filament/src/Stream.cpp, filament/src/details/Engine.h, filament/src/details/Fence.h
This API will be hard to implement on all backends (e.g. Vulkan) and
isn't that useful other than for timing.
=> Remove HARD Fence public API

CMakeLists.txt
=> Build OpenImageDenoise only in host builds.

filament/backend/include/private/backend/DriverAPI.inc
@greg7mdp hopefully this works! could you try this change?
=> Make DriverAPI.inc work with MSVC19

libs/math/include/math/TVecHelpers.h
@greg7mdp hopefully this should fix all the cast and parameters inversions you had to do.
Would you be able to revert all these changes and try this? Thanks!
=> handle scalar op vector directly to help some compilers

android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
Noticed this while working on javadoc stuff.
=> Add Java annotations to setMorphWeights.

android/filament-android/src/main/java/com/google/android/filament/Camera.java, android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java, android/filament-android/src/main/java/com/google/android/filament/proguard/UsedByNative.java, android/filament-android/src/main/java/com/google/android/filament/proguard/UsedByReflection.java
Note that GitHub does not show large diffs by default.
=> Add javadoc for RenderableManager, fix javadoc warnings.

android/filament-android/src/main/java/com/google/android/filament/IndirectLight.java, android/filament-android/src/main/java/com/google/android/filament/View.java, android/filament-android/src/main/java/com/google/android/filament/Viewport.java, filament/include/filament/View.h, filament/src/View.cpp
Note that `View.java` is a large diff and therefore hidden by github.
This CL also fixes warnings in IndirectLight and adds a new C++ getter to View for consistency with Java.
=> Add javadoc for View and Viewport.

android/filament-android/src/main/java/com/google/android/filament/Renderer.java
also made resetUserTime and getUserTime public
=> javadoc for Renderer

libs/gltfio/include/gltfio/ResourceLoader.h, libs/gltfio/src/Animator.cpp, libs/gltfio/src/AssetLoader.cpp, libs/gltfio/src/FFilamentAsset.h, libs/gltfio/src/ResourceLoader.cpp, third_party/cgltf/cgltf.h
Draft PR as this involves a tentative contribution to a third-party library.
=> Add support for sparse accessors.

filament/README.md, libs/matdbg/CMakeLists.txt
=> Combine matdbg dependencies into single shared library

libs/math/include/math/TQuatHelpers.h, libs/utils/test/test_StructureOfArrays.cpp, samples/CMakeLists.txt, samples/app/FilamentApp.cpp, samples/app/FilamentApp.h, samples/gltf_baker.cpp, samples/gltf_viewer.cpp, samples/lucy_bloom.cpp, samples/suzanne.cpp, samples/vk_hellopbr.cpp, samples/vk_shadowtest.cpp, samples/vk_texturedquad.cpp
A handful of additional changes to support MSVC.
=> Additional fixes for MSVC

third_party/meshoptimizer/CMakeLists.txt, third_party/meshoptimizer/tnt/README
=> Remove BUILD_DEMO CMake option

filament/src/Camera.cpp
We were not checking Camera's preconditions properly -- we assumed that
near < 1/1024 meant "near == 0".
Now we check preconditions properly and revert to the same hardcoded
default if they're not met -- doesn't matter what the default is,
it's there only to avoid NaNs and Infs elsewhere -- rendering will
be bogus eitherway.
Fixes #1766
=> don't limit the near plane to ~1mm

android/filament-android/src/main/java/com/google/android/filament/android/TextureHelper.java, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/KtxLoader.java, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/MaterialProvider.java, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/ResourceLoader.java
=> Remove the use of reflection where it's not necessary

libs/math/include/math/TMatHelpers.h, libs/math/include/math/mat2.h, libs/math/include/math/mat3.h, libs/math/include/math/mat4.h, libs/math/include/math/vec2.h, libs/math/include/math/vec3.h, libs/math/include/math/vec4.h
this requires using 'auto' as the return type.
=> implement diag() in TMatSquareFunctions

RELEASE_NOTES.md, android/gltfio-android/CMakeLists.txt, android/gltfio-android/src/main/cpp/Animator.cpp, android/gltfio-android/src/main/cpp/FilamentAsset.cpp, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/Animator.java, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java, android/samples/gltf-bloom/app/src/main/java/com/google/android/filament/gltf/MainActivity.kt
=> gltfio: Add Java / Kotlin bindings for Animator.

filament/include/filament/Box.h, filament/src/Box.cpp, filament/test/filament_test.cpp, libs/gltfio/src/AssetLoader.cpp, libs/gltfio/src/ResourceLoader.cpp
This is from the 1990 Graphics Gems article.
=> Use a faster method for transforming AABB's.

README.md, RELEASE_NOTES.md, build.sh, build/web/ci-common.sh, web/filament-js/jsbindings.cpp
This uses clang's wasm backend rather than fastcomp.
=> Upgrade emsdk for improved wasm generation.

filament/backend/CMakeLists.txt, filament/backend/include/private/backend/Driver.h, filament/backend/src/CommandStream.cpp, filament/backend/src/Driver.cpp, filament/backend/src/metal/MetalBlitter.mm, filament/backend/src/metal/MetalBufferPool.mm, filament/backend/src/metal/MetalContext.h, filament/backend/src/metal/MetalContext.mm, filament/backend/src/metal/MetalDriver.h, filament/backend/src/metal/MetalDriver.mm, filament/backend/src/metal/MetalExternalImage.mm, filament/backend/src/metal/MetalHandles.h, filament/backend/src/metal/MetalHandles.mm, filament/backend/src/metal/MetalState.h, filament/backend/src/metal/MetalState.mm, filament/backend/src/opengl/PlatformCocoaGL.mm, filament/backend/src/opengl/PlatformCocoaTouchGL.mm, filament/backend/src/vulkan/PlatformVkCocoa.mm
Automatic Reference Counting (ARC) is a Clang feature that simplifies memory management in Objective-C and Objective-C++ code. This PR turns on ARC for the Metal backend and Cocoa platform files (like PlatformCocoaGL.mm).
=> Use ARC for Metal backend

android/gltfio-android/src/main/cpp/Animator.cpp, android/gltfio-android/src/main/cpp/AssetLoader.cpp, android/gltfio-android/src/main/cpp/FilamentAsset.cpp, android/gltfio-android/src/main/cpp/ResourceLoader.cpp, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
=> Add support for GLTF files in the android gltfio bindings

web/filament-js/wasmloader.js
=> JavaScript: allow pre-population of asset data.

filament/src/VertexBuffer.cpp, libs/filabridge/include/filament/MaterialEnums.h, libs/gltfio/src/AssetLoader.cpp
=> Emit warning for too many morph targets.

shaders/src/shading_parameters.fs
Fixes #1872 by flipping tangents and bitangents on backfaces
=> Flip Tangents and Bitangents on backfaces.

.github/workflows/android-continuous.yml, .github/workflows/ios-continuous.yml, .github/workflows/linux-continuous.yml, .github/workflows/mac-continuous.yml, .github/workflows/presubmit.yml, .github/workflows/web-continuous.yml, .github/workflows/windows-continuous.yml
We can use third-party Actions again :)
=> Use checkout action for GitHub Actions

libs/gltfio/src/ResourceLoader.cpp
Reduces texture loading time from 290 ms to 110 ms for the lantern glb from the Khronos suite.
Stay tuned for another feature: notification callbacks.
Related to #1876.
=> gltfio: Use JobSystem to decode PNG / JPEG.

.github/workflows/presubmit.yml, .github/workflows/windows-continuous.yml, filament/backend/include/private/backend/DriverAPI.inc
Windows was reporting false positives. Fix this by specifying the correct shell to use.
Also fix a Windows build error in `DriverApi.inc`.
=> Fix Windows CI failures by specifying shell

samples/CMakeLists.txt, samples/gltf_baker.cpp, samples/gltf_viewer.cpp, samples/lucy_utils.h
Windows CI sometimes fails compiling `gltf.c`:
```
fatal error C1060: compiler is out of heap space
```
Hopefully splitting up the resources helps.
=> Separate resource packages for gltf_viewer and lucy demo

libs/imageio/src/ImageDecoder.cpp
The new conditional is cribbed from STB, which checks the first three
bytes.
Fixes #1937.
=> cmgen: add support for non-RLE HDR images.

RELEASE_NOTES.md, filament/backend/src/metal/MetalContext.mm
=> Add depth32 fallback for GPUs without packed depth support

third_party/astcenc/Source/astc_toplevel.cpp, third_party/astcenc/tnt/README, tools/cmgen/tests/test_cmgen.cpp, tools/mipgen/src/main.cpp
=> Make builds less verbose.

libs/ibl/src/CubemapUtilsImpl.h
the state wasn't initialized from the user given prototype
=> fix CubemapUtils::processSingleThreaded()

filament/backend/src/opengl/PlatformCocoaGL.mm
Previous to this change, we suffered from a flash-of-red followed by a
flash-with-wrong-projection every time we resized an OpenGL window.
SDL throttles the window resize events, so FilamentApp updates the View
only on the final low-level resize event. However we were calling
Cocoa's update method on every low-level resize event. Thus we were
showing uninitialized content during the resize.
FilamentApp recreates the SwapChain after the final resize event; one
reason for this is the fact that Vulkan swap chains must be recreated.
The fix is to defer the Cocoa update until the swap chain gets
recreated. This is the perfect time because FilamentApp has already set
the new Viewport at this point.
=> macOS: fix flash of red upon resize.

filament/backend/src/vulkan/VulkanContext.cpp
compile error when vulkan by vs 2019 16.4.2
=> fix compile error when vulkan

shaders/src/light_indirect.fs
This makes it easier to add new shapes and experiment.
Added a "sold box" shape that is not used yet.
=> Simplify refraction code

android/samples/gltf-bloom/app/build.gradle, web/samples/CMakeLists.txt
I broke this when I changed the cmgen KTX behavior.
=> Repair gradle IBL path for gltf_bloom.

libs/ibl/src/CubemapIBL.cpp
Rotate the sample pattern at every light direction, which trades
aliasing for noise (which is arguably more pleasant) for IBLs with
very high frequency (i.e. high level of HDR-ness).
Before:
After:
=> improve cmgen prefiltered cubemaps

filament/src/fg/FrameGraph.cpp, filament/src/fg/fg/PassNode.h
The main purpose of this change is to fix a problem where a resource
marked as sampleable by a *culled* pass would stay sampleable.
This happened because the sampleable state was tracked on the resource
itself.
We fix this by treating sample() just like read(), such resources are
added to an array living in the pass, which ensures the state is correct
when passes are culled.
Also fixed:
- simplified read() code a bit (minor)
- simplified resource aliasing code
- don't resolve() renderTargets of culled passes
=> More fixes to sampled textures in the framegraph

filament/CMakeLists.txt, filament/src/fg/Blackboard.cpp, filament/src/fg/Blackboard.h, filament/src/fg/FrameGraph.cpp, filament/src/fg/FrameGraph.h, filament/src/fg/FrameGraphHandle.cpp, filament/src/fg/FrameGraphHandle.h, filament/src/fg/fg/RenderTargetResource.cpp, filament/src/fg/fg/RenderTargetResource.h
- implement a blackboard
- minor refactoring, comment fixes and way to deep-compare handles
=> FrameGraph improvements 

android/filament-android/src/main/java/com/google/android/filament/android/UiHelper.java
When UiHelper is set to translucent with setOpaque(false), the
target SurfaceView's surface is set to be composited on top of
the activity's window. There are situations however where one
may want to render regular Views on top of the SurfaceView.
The new setMediaOverlay() API allows exactly that: when this
property is enabled, rendering to a translucent target will
cause the SurfaceView's surface to be composited above other
surfaces, but below the activity's surface.
Fixes #2037
=> Add more control to surface ordering

.github/workflows/android-continuous.yml, .github/workflows/release.yml, README.md, android/filament-utils-android/.gitignore, android/filament-utils-android/CMakeLists.txt, android/filament-utils-android/build.gradle, android/filament-utils-android/gradle.properties, android/filament-utils-android/libfilament-utils-jni.map, android/filament-utils-android/libfilament-utils-jni.symbols, android/filament-utils-android/src/main/AndroidManifest.xml, android/filament-utils-android/src/main/cpp/Bookmark.cpp, android/filament-utils-android/src/main/cpp/Manipulator.cpp, android/filament-utils-android/src/main/cpp/Utils.cpp, android/filament-utils-android/src/main/java/com/google/android/filament/utils/Bookmark.java, android/filament-utils-android/src/main/java/com/google/android/filament/utils/GestureDetector.kt, android/filament-utils-android/src/main/java/com/google/android/filament/utils/KtxLoader.java, android/filament-utils-android/src/main/java/com/google/android/filament/utils/Manipulator.java, android/filament-utils-android/src/main/java/com/google/android/filament/utils/Matrix.kt, android/filament-utils-android/src/main/java/com/google/android/filament/utils/Ray.kt, android/filament-utils-android/src/main/java/com/google/android/filament/utils/Scalar.kt, android/filament-utils-android/src/main/java/com/google/android/filament/utils/Utils.java, android/filament-utils-android/src/main/java/com/google/android/filament/utils/Vector.kt, android/samples/sample-gltf-bloom/build.gradle, android/samples/sample-gltf-bloom/src/main/java/com/google/android/filament/bloom/MainActivity.kt, android/settings.gradle, build.sh
This library houses the KTX loader, camutils bindings, and a Kotlin math library.
More will come later, such as a model viewer widget.
Sample app is forthcoming.
=> Introduce filament-utils and Java bindings for camutils.

android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
Remove ~30 LOC without losing any functionality.
=> Android: simplify gltf-viewer as much as possible.

RELEASE_NOTES.md, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/include/filament/View.h, filament/src/Renderer.cpp, libs/filamat/src/shaders/CodeGenerator.cpp
Fixes #737 and #1472. See also #475 and #1295.
=> Disable depth prepass everywhere.

BUILDING.md
=> Fix typo in documentation

ios/samples/hello-ar/hello-ar/FilamentArView/FilamentApp.cpp, ios/samples/hello-ar/hello-ar/FilamentArView/FilamentApp.h, ios/samples/hello-ar/hello-ar/FilamentArView/FullScreenTriangle.cpp, ios/samples/hello-gltf/hello-gltf/FilamentView/App.cpp, ios/samples/hello-gltf/hello-gltf/FilamentView/App.h, ios/samples/hello-pbr/hello-pbr/FilamentApp.cpp, ios/samples/hello-pbr/hello-pbr/FilamentApp.h, ios/samples/hello-triangle/hello-triangle/FilamentView.mm, ios/samples/transparent-rendering/transparent-rendering/FilamentView.mm
Fixing iOS headers due to the change in 3105a8330ea88946eaba4d156ba8bd4f687d8203.
=> Fix headers in iOS samples

libs/gltfio/include/gltfio/Image.h, libs/gltfio/src/ResourceLoader.cpp
=> Repair iOS error due to STBI_NO_STDIO.

filament/src/Engine.cpp, filament/src/details/Engine.h
=> Fix event pumping with non-owned platforms.

libs/gltfio/include/gltfio/ResourceLoader.h, libs/gltfio/include/gltfio/SimpleViewer.h, libs/gltfio/src/ResourceLoader.cpp, web/filament-js/jsbindings.cpp
This adds most of the asynchronous functionality but does not expose it.
=> gltfio: refactor to prep for async API.

filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/Renderer.cpp, filament/src/View.cpp, filament/src/fg/FrameGraph.cpp, shaders/src/light_indirect.fs
This will help reducing bandwidth requirements while not affecting
quality significantly.
=> Process SSR buffer in 11.11.10 format

filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/Renderer.cpp, filament/src/View.cpp, filament/src/fg/FrameGraph.cpp, shaders/src/light_indirect.fs
This reverts commit 79a83e8c467ba85fbfc8308d79cd35bf7eca1d1a.
=> Revert "wip: rework filtering"

filament/src/PostProcessManager.h, filament/src/Renderer.cpp
Chose a filter width that preserve the "gaussianness" of the 
blur filter.
=> improve SSRefr roughness with very strong highlight

RELEASE_NOTES.md, android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/CMakeLists.txt, filament/include/filament/View.h, filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/Renderer.cpp, filament/src/View.cpp, filament/src/details/View.h, filament/src/materials/bloomDownsample.mat, filament/src/materials/bloomUpsample.mat, filament/src/materials/tonemapping.mat, libs/gltfio/include/gltfio/SimpleViewer.h, samples/material_sandbox.cpp, samples/material_sandbox.h, shaders/src/bloom.fs
=> Implement a Bloom post-process effect

samples/app/FilamentApp.cpp
To trigger an exception users could either shrink the window or enlarge
the sidebar. Constraining both of these is somewhat tricky so let's
just clamp the viewport width at a low level.
=> Clamp viewport width to prevent floating point exception.

filament/include/filament/TextureSampler.h, filament/src/PostProcessManager.cpp, filament/src/Renderer.cpp, filament/src/Texture.cpp, filament/src/details/Texture.h, filament/src/details/View.h, filament/src/fg/FrameGraphHandle.cpp
- Minor cleanup. Add FTexture::maxLevelCount()
- Split downsample and upsample passes
- Improve bloom performance on mobile
=> A few improvements of performance and code 

android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/include/filament/View.h, filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/Renderer.cpp, filament/src/details/View.h, filament/src/materials/tonemapping.mat, libs/gltfio/include/gltfio/SimpleViewer.h, samples/app/Config.h, samples/app/FilamentApp.cpp, samples/app/FilamentApp.h, samples/material_sandbox.cpp, shaders/src/bloom.fs
=> Bloom can now have a dirt texture applied

android/filament-android/src/main/java/com/google/android/filament/View.java, filament/include/filament/View.h, filament/src/materials/bloomDownsample.mat
- also use step() to implement the threshold
- improve bloomOptions documentation
=> fix a typo when thresholding for bloom

android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/include/filament/View.h, filament/src/PostProcessManager.cpp, filament/src/materials/sao.mat
- Use a smoother falloff function.
- Added a quality level parameter for SSAO
=> Quality and API improvements to SSAO

android/filament-android/src/main/cpp/RenderTarget.cpp, android/filament-android/src/main/java/com/google/android/filament/RenderTarget.java
=> Fix JNI signature for RenderTarget API.

filament/src/PostProcessManager.cpp, filament/src/materials/bilateralBlur.mat, filament/src/materials/sao.mat, filament/tools/ssaogen.cpp, shaders/src/ambient_occlusion.fs
- minor uniform optimizations (saves ~0.1ms)
- fix some missing highp precision qualifers
- make it easier to tweak the blur filter
- make sure samples's radius goes from 0 to 1
- update comments
=> Minor changes to SAO

android/filamat-android/build.gradle, android/filament-android/build.gradle, android/filament-utils-android/build.gradle, android/gltfio-android/build.gradle
=> Fix library loading issue on API level 22 and below

android/build.gradle, android/filamat-android/CMakeLists.txt, android/filamat-android/build.gradle, android/filament-android/CMakeLists.txt, android/filament-android/build.gradle, android/filament-utils-android/CMakeLists.txt, android/filament-utils-android/build.gradle, android/gltfio-android/CMakeLists.txt, android/gltfio-android/build.gradle
We now share all the C++/CMake flags from the root project.
=> Refactor Gradle files

android/build.gradle, android/buildSrc/src/main/groovy/FilamentPlugin.groovy
=> Properly fetch project properties

android/filament-android/src/main/cpp/Camera.cpp, android/filament-android/src/main/java/com/google/android/filament/Camera.java, filament/include/filament/Camera.h, filament/src/Camera.cpp, filament/src/details/Camera.h, libs/gltfio/include/gltfio/SimpleViewer.h, samples/app/FilamentApp.cpp, samples/app/FilamentApp.h, samples/gltf_viewer.cpp, samples/lightbulb.cpp, samples/material_sandbox.cpp, samples/materials/groundShadow.mat, samples/vk_shadowtest.cpp
Exposure: shutter speed, aperture and ISO
Focal length
The shadow plane can now be toggled  at runtime.
=> Add camera controls to gltf_viewer

filament/backend/src/metal/MetalBuffer.mm, filament/src/Material.cpp, filament/src/View.cpp, filament/src/details/View.h, libs/filabridge/include/private/filament/EngineEnums.h, libs/filabridge/include/private/filament/UibGenerator.h, libs/filabridge/src/UibGenerator.cpp, libs/filamat/src/shaders/ShaderGenerator.cpp
This new uniform buffer stores additional information needed for spot light shadows.
=> Add new Shadows uniform buffer

web/filament-js/extensions.js, web/filament-js/filament.d.ts, web/filament-js/jsbindings.cpp, web/filament-js/jsenums.cpp
=> JavaScript: Expose bloom and SSAO options.

libs/math/include/math/mathfwd.h
=> Fix, mathfwd does not work correctly with MSVC

filament/src/Renderer.cpp
We make sure to only (and always) clear newly allocated buffers,
but only clear existing buffers based on the user request. This
should allow to share the depth buffer between drawing two
Views (if post-process is disabled). This should also fix 
a bug where the intermediate buffer wasn't cleared when blending
a view on to of another.
This should fix #2138
=> Fix framebuffer clears

filament/src/UniformBuffer.h
this actually makes it possible to set mat3s from java.
=> fix setting an array mat3 as a parameter of material instance

CMakeLists.txt, filament/CMakeLists.txt, filament/backend/CMakeLists.txt, libs/camutils/CMakeLists.txt, libs/filagui/CMakeLists.txt, libs/filamat/CMakeLists.txt, libs/geometry/CMakeLists.txt, libs/gltfio/CMakeLists.txt, libs/ibl/CMakeLists.txt, libs/image/CMakeLists.txt, libs/imageio/CMakeLists.txt, libs/matdbg/CMakeLists.txt, libs/math/CMakeLists.txt, libs/mathio/CMakeLists.txt, libs/rays/CMakeLists.txt, samples/CMakeLists.txt, third_party/meshoptimizer/CMakeLists.txt, third_party/meshoptimizer/tnt/README, third_party/tinyexr/tnt/CMakeLists.txt, tools/cmgen/CMakeLists.txt
Should have put this up awhile ago.
=> Deprecating Clang on Windows in CMakeLists

shaders/src/shadowing.fs
=> Fix contact shadows GLSL compilation error

filament/src/MaterialParser.cpp, libs/filabridge/include/filament/MaterialChunkType.h, libs/filaflat/src/DictionaryReader.cpp, libs/filamat/src/MaterialBuilder.cpp, libs/matdbg/src/ShaderExtractor.cpp, libs/matdbg/src/ShaderReplacer.cpp
⚠️ This breaks materials ⚠️
Part 1 of #2231.
=> Share material dictionaries between GLSL / MSL

RELEASE_NOTES.md, android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/include/filament/View.h, filament/src/RenderPass.cpp, filament/src/RenderPass.h, filament/src/Renderer.cpp, filament/src/View.cpp, filament/src/details/View.h, libs/filabridge/include/private/filament/UibGenerator.h, libs/filabridge/include/private/filament/Variant.h, libs/filabridge/src/UibGenerator.cpp, libs/filamat/src/shaders/CodeGenerator.cpp, libs/filamat/src/shaders/ShaderGenerator.cpp, libs/filamat/src/shaders/ShaderGenerator.h, libs/gltfio/include/gltfio/SimpleViewer.h, samples/app/FilamentApp.cpp, samples/material_sandbox.cpp, samples/material_sandbox.h, shaders/CMakeLists.txt, shaders/src/fog.fs, shaders/src/main.fs
=> Add support for basic fog

filament/src/ShadowMap.cpp
In some situations the shadow map would be too aggressively clipped.
This was due to a bug in the box-frustum intersection algorithm, which
could fail when some vertices of the frustum were inside the box, and
some vertices of the box inside the frustum and the total number
of vertices such classified was 8.
=> fix a shadow clipping bug

filament/src/IndirectLight.cpp, filament/src/View.cpp, filament/src/details/IndirectLight.h, libs/filabridge/include/private/filament/UibGenerator.h, libs/filabridge/src/UibGenerator.cpp, shaders/src/light_indirect.fs
The max mip (i.e. mip at roughness 1) was off by one.
=> Fix IBL mip calculation

samples/app/MeshAssimp.cpp, samples/lightbulb.cpp
spotlight/contact shadows, ssao, fog, bloom.
=> enable some more features in lightbulb

libs/utils/CMakeLists.txt, third_party/robin-map/tnt/CMakeLists.txt
=> Export missing headers for NameComponentManager

android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/include/filament/View.h, filament/src/View.cpp, filament/src/details/View.h, filament/src/materials/sao.mat, libs/filabridge/include/private/filament/UibGenerator.h, libs/filabridge/src/UibGenerator.cpp, libs/gltfio/include/gltfio/SimpleViewer.h, samples/material_sandbox.cpp, shaders/src/fog.fs, shaders/src/getters.vs, shaders/src/main.fs
- optimized the fog computations
- fixed issues with the skybox
- added the option of getting the fog color from the IBL envmap
=> Fog improvements

filament/include/filament/RenderableManager.h, filament/src/components/RenderableManager.cpp
Expose RenderableManager::getLayerMask() to public API
=> Expose Renderable::getLayerMask()

CMakeLists.txt, RELEASE_NOTES.md, android/gltfio-android/CMakeLists.txt, libs/gltfio/CMakeLists.txt, libs/gltfio/src/AssetLoader.cpp, libs/gltfio/src/DracoCache.cpp, libs/gltfio/src/DracoCache.h, libs/gltfio/src/FFilamentAsset.h, libs/gltfio/src/ResourceLoader.cpp, third_party/draco/CMakeLists.txt, third_party/draco/tnt/CMakeLists.txt
This needs a bit more testing before merging, but I wanted to put up the
PR for review. I will look into supporting Android after we land this.
Fixes #1932.
=> gltfio: add support for Draco (desktop only)

libs/utils/CMakeLists.txt
* Add dependency of Allocator.h
* Fix Android build error
=> Fix NameComponentManager dependency and Android build

CMakeLists.txt, libs/rays/src/PathTracer.cpp, samples/gltf_baker.cpp, third_party/spirv-tools/CMakeLists.txt
- Fix gltf_baker crash
- Fix Python3 discovery on macOS
- Fix TBB CMake warning
- Fix bent normals baking
=> Fixes various issues

android/build.gradle, android/filament-android/src/main/cpp/Renderer.cpp, android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/Renderer.java, android/filament-android/src/main/java/com/google/android/filament/View.java, android/filament-android/src/main/java/com/google/android/filament/android/DisplayHelper.java, android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt, android/samples/sample-gltf-viewer/build.gradle, android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt, android/samples/sample-hello-camera/src/main/java/com/google/android/filament/hellocam/MainActivity.kt, android/samples/sample-hello-triangle/src/main/java/com/google/android/filament/hellotriangle/MainActivity.kt, android/samples/sample-image-based-lighting/src/main/java/com/google/android/filament/ibl/MainActivity.kt, android/samples/sample-lit-cube/src/main/java/com/google/android/filament/litcube/MainActivity.kt, android/samples/sample-material-builder/src/main/java/com/google/android/filament/material_builder/MainActivity.kt, android/samples/sample-stream-test/src/main/java/com/google/android/filament/streamtest/MainActivity.kt, android/samples/sample-texture-view/src/main/java/com/google/android/filament/textureview/MainActivity.kt, android/samples/sample-textured-object/src/main/java/com/google/android/filament/textured/MainActivity.kt, android/samples/sample-transparent-view/src/main/java/com/google/android/filament/transparentrendering/MainActivity.kt, filament/include/filament/Renderer.h, filament/include/filament/View.h, filament/src/FrameInfo.cpp, filament/src/FrameInfo.h, filament/src/Renderer.cpp, filament/src/View.cpp, filament/src/details/Renderer.h, filament/src/details/View.h, java/filament/src/java/com/google/android/filament/FilamentCanvas.java, java/filament/src/java/com/google/android/filament/FilamentPanel.java
- add vsync tiemstamps to beginFrame()
- add a way to query ans set Display information
- rework how dynamic resolution works
=> plumbing for vsync timestamps and displayinfo

android/gltfio-android/src/main/java/com/google/android/filament/gltfio/Gltfio.java
=> Fix Gltfio.init(): call Filament.init() as well

libs/gltfio/src/AssetLoader.cpp, libs/gltfio/src/ResourceLoader.cpp
Moved all the skinning processing into one place, there is no longer a need to split it up.
=> gltfio: code cleanup for skinning.

libs/bluevk/src/BlueVKDarwin.cpp
=> Do not clobber VK_ICD_FILENAMES.

filament/include/filament/Renderer.h, filament/src/FrameInfo.cpp, filament/src/FrameInfo.h, filament/src/PostProcessManager.cpp, filament/src/Renderer.cpp, filament/src/View.cpp
This new code is better able to reach the desired target as it 
continuously evaluates the best scale factor based on the current
known state.
=> Improve dynamic resolution tracking

android/samples/sample-multi-view/src/main/java/com/google/android/filament/multiview/MainActivity.kt, filament/src/Renderer.cpp
there were cleared with the view's clear color instead of 0
=> newly created color buffers were not cleared properly

libs/filamentapp/CMakeLists.txt, samples/CMakeLists.txt
`FilamentApp.cpp` is now part of the filamentapp lib.
=> Fix getRootAssetsPath on Windows

filament/backend/src/opengl/PlatformWGL.cpp
=> Implement headless swapchains on Windows

tools/cso-lut/src/main.cpp
The ground truth is computed using a Monte Carlo simulation.
=> Add ground-truth option to cso-lut

build.sh
Fix a ton of warnings, mostly around escaping values to avoid
splitting.
=> Safer build script

filament/backend/include/private/backend/DriverAPI.inc, filament/backend/src/metal/MetalDriver.mm, filament/backend/src/noop/NoopDriver.cpp, filament/backend/src/opengl/OpenGLDriver.cpp, filament/backend/src/vulkan/VulkanDriver.cpp, filament/src/Texture.cpp
texture swizzling is now set at creation time to accommodate 
vulkan/metal texture immutability
=> texture swizzling is immutable

libs/image/include/image/ColorTransform.h, libs/image/src/ImageSampler.cpp, libs/imageio/src/ImageDecoder.cpp, libs/imageio/src/ImageEncoder.cpp, tools/mipgen/src/main.cpp
=> Fix support of paletted images and alpha channel in imageio

libs/filamentapp/include/filamentapp/Config.h, libs/filamentapp/src/FilamentApp.cpp, samples/gltf_viewer.cpp, samples/material_sandbox.cpp
Pass `--camera flight` to enable free flight mode.
=> Add camera flag to gltf_viewer and material_sandbox

filament/src/Froxelizer.cpp
we can calculate each plane directly from its clip-space equation
(which is trivial), instead of back-projecting 2 points and computing
the cross-product
=> improve code that generates froxel planes

filament/src/materials/skybox.mat
=> some old adreno drivers don't support bool in UBOs

filament/src/Renderer.cpp
=> Always bind the structure sampler

RELEASE_NOTES.md, android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/CMakeLists.txt, filament/include/filament/View.h, filament/src/Camera.cpp, filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/Renderer.cpp, filament/src/ShadowMap.cpp, filament/src/View.cpp, filament/src/details/Camera.h, filament/src/details/View.h, filament/src/materials/dof.mat, filament/src/materials/dofBlur.mat, filament/src/materials/dofUtils.fs, filament/src/materials/sao.mat, samples/gltf_viewer.cpp
=> A new depth of field (DoF) post-process effect

shaders/src/inputs.fs, shaders/src/inputs.vs, shaders/src/main.vs, shaders/src/shading_parameters.fs
This saves 4 varying components.
Fixes #2092
=> compute bitangeant in fragment shader

filament/src/materials/dofUtils.fs
We keep the same (or very close) quality by exploiting h/w
filtering. On the flip side, this is not compatible with dithering,
which is removed here.
=> Reduce DoF sample count from 25 to 11

filament/src/Engine.cpp
it's causing some unrelated problem on the iOS simulator, and we're
looking for an Android bug anyways.
=> only implement flushAndWait() debugging on android

RELEASE_NOTES.md, android/filament-android/src/main/cpp/Material.cpp, android/filament-android/src/main/cpp/MaterialInstance.cpp, android/filament-android/src/main/java/com/google/android/filament/Material.java, android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java, filament/include/filament/Material.h, filament/include/filament/MaterialInstance.h, filament/src/Engine.cpp, filament/src/Material.cpp, filament/src/MaterialInstance.cpp, filament/src/Skybox.cpp, filament/src/details/Engine.h, filament/src/details/Material.h, filament/src/details/MaterialInstance.h, web/filament-js/filament.d.ts, web/filament-js/jsbindings.cpp
In a subsequent PR, this feature will be exercised and tested via the
gltfio AssetLoader.
Fixes #2485.
=> MaterialInstance now has an optional name.

BUILDING.md, build/web/ci-common.sh, web/filament-js/CMakeLists.txt, web/filament-js/createContext.js, web/filament-js/extensions.js, web/filament-js/jsbindings.cpp, web/filament-js/utilities.js, web/filament-js/wasmloader.js
=> WebGL: upgrade and accommodate EMSDK.

libs/filabridge/src/UibGenerator.cpp
It wouldn't really cause any issues, because still.
=> PerViewUib header and .cpp padding didn't match

filament/backend/src/metal/MetalContext.h, filament/backend/src/metal/MetalContext.mm, filament/backend/src/metal/MetalDriver.mm, filament/backend/src/metal/MetalHandles.h, filament/backend/src/metal/MetalHandles.mm, libs/filamentapp/src/NativeWindowHelperCocoa.mm
This fixes the Metal issue with #2529.
=> Metal: allow swapchain size to change

libs/gltfio/include/gltfio/SimpleViewer.h
Added this for debugging earlier, meant to remove it.
=> Cast shadows by default in gltf_viewer

filament/backend/src/metal/MetalTimerQuery.mm
=> Fix Metal memory leak inside MetalTimerQuery

libs/filagui/include/filagui/ImGuiHelper.h, libs/filagui/src/ImGuiHelper.cpp
=> filagui: Fix "1 leaked FScene" warning.

filament/backend/include/backend/DriverEnums.h, filament/backend/include/private/backend/DriverAPI.inc, filament/backend/src/metal/MetalDriver.mm, filament/backend/src/noop/NoopDriver.cpp, filament/backend/src/opengl/OpenGLContext.h, filament/backend/src/opengl/OpenGLDriver.cpp, filament/backend/src/vulkan/VulkanDriver.cpp, libs/filamat/src/Enums.cpp, libs/filamat/src/shaders/CodeGenerator.cpp, libs/matdbg/src/CommonWriter.h
=> add support for 3D textures

android/build.gradle, android/buildSrc/src/main/groovy/FilamentPlugin.groovy
I forgot to update this in 0b1fa7f.
=> Gradle: update old property name.

filament/src/PostProcessManager.cpp
This avoids error spew on some platforms such as Chrome + WebGL 2.0
=> Add "if" when compiling subpass material.

filament/backend/src/vulkan/VulkanHandles.cpp
OpenGL allows vertex shaders to consume attributes that are never
assigned values from a vertex buffer. When this occurs, GL provides a
default zeroed-out value, or a value from the most recent call to
`glVertexAttrib*v`.
Vulkan does not allow this, so our Vulkan backend provides dummy data by
re-using the position buffer, which we know exists. This was an existing
hack, but it did not always assign a compatible type, which resulted in
validation spew with gltf_viewer + BusterDrone.
This fixes one of the two bugs reported in #2573.
=> Vulkan: fix dummy type for disabled attribs.

RELEASE_NOTES.md, filament/backend/CMakeLists.txt, filament/backend/src/metal/MetalBlitter.h, filament/backend/src/metal/MetalBlitter.mm, filament/backend/src/metal/MetalContext.h, filament/backend/src/metal/MetalDriver.mm, filament/backend/src/metal/MetalHandles.h, filament/backend/src/metal/MetalHandles.mm, filament/backend/src/metal/MetalState.h, filament/backend/src/metal/MetalState.mm, filament/backend/test/test_MRT.cpp
This enables DOF for the Metal backend.
=> Implement MRT for Metal

filament/backend/src/metal/MetalDriver.mm, filament/backend/src/metal/MetalHandles.h, filament/backend/src/metal/MetalHandles.mm
Adds 3D texture support, tested with #2561.
=> Add 3D texture support to Metal

filament/include/filament/ColorGrading.h, filament/include/filament/View.h, filament/src/ColorGrading.cpp, filament/src/ColorSpace.h, filament/src/ToneMapping.h, samples/material_sandbox.cpp, samples/material_sandbox.h
Example using channel mixer to create a sepia tone effect:
=> Add channel mixer and docs to ColorGrading

android/gltfio-android/src/main/cpp/FilamentAsset.cpp, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
Tested in Android Studio by starting sample-gltf-viewer and typing the
following into the debugger:
modelViewer.asset!!.getFirstEntityByName("Drone_Body")
modelViewer.asset!!.getEntitiesByName("Drone_Body")
modelViewer.asset!!.getEntitiesByPrefix("Drone")
=> gltfio: JNI bindings for get-by-name.

filament/backend/src/vulkan/VulkanDriver.cpp
Note that pushGroup / popGroup are already supported.
=> Vulkan: implement insertEventMarker.

README.md, RELEASE_NOTES.md, filament/include/filament/ColorGrading.h, filament/src/ColorGrading.cpp, libs/math/include/math/TVecHelpers.h, samples/material_sandbox.cpp, samples/material_sandbox.h
A CDL is made of slope/offset/power, and is roughly equivalent
to lift/gamma/gain.
=> Add ASC CDL (Color decision list) to color grading

filament/backend/src/metal/MetalDriver.mm, libs/filamat/src/GLSLPostProcessor.cpp
=> Implement framebuffer fetch for Metal backend

libs/utils/src/linux/futex.h
this fixes a problem where our implementation of Condition would not
handle timeouts properly
=> syscall (futex) errors are returned in errno

libs/imageio/src/ImageDecoder.cpp
See https://cbloomrants.blogspot.com/2020/06/widespread-error-in-radiance-hdr-rgbe.html
=> Fix libimageio's HDR format decoder

libs/gltfio/src/AssetLoader.cpp
Reproduced the issue by hacking the TexturedCube glTF file.
Verified the fix by viewing TexturedCube in ubershader mode, then
hacking the shader with matdbg in order to visualize texture
coordinates.
Fixes #2659
=> gltfio: enable unused UV attributes when possible.

RELEASE_NOTES.md, filament/include/filament/Camera.h, filament/src/Camera.cpp, filament/src/details/Camera.h, libs/filamentapp/include/filamentapp/FilamentApp.h, libs/filamentapp/src/FilamentApp.cpp, libs/gltfio/include/gltfio/FilamentAsset.h, libs/gltfio/src/AssetLoader.cpp, libs/gltfio/src/FFilamentAsset.h, libs/gltfio/src/FilamentAsset.cpp, samples/gltf_viewer.cpp
=> Add support to gltfio for glTF cameras

filament/backend/src/metal/MetalHandles.mm
=> Fix Metal bug not creating default depth attachment

CMakeLists.txt, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/ResourceLoader.java, java/gltfio/CMakeLists.txt, third_party/draco/tnt/CMakeLists.txt
This is completely untested but at least it builds.
Fixes #2670.
=> gltfio: Add Java bindings for desktop.

CMakeLists.txt, build/ios/build.sh, build/toolchain-mac-ios.filament.cmake, filament/backend/src/metal/MetalDriver.mm, filament/backend/src/metal/MetalState.mm, ios/samples/README.md, ios/samples/hello-ar/hello-ar/FilamentArView/FilamentView.m, ios/samples/hello-gltf/hello-gltf/FilamentView/FilamentView.m, ios/samples/hello-gltf/hello-gltf/FilamentView/FilamentViewController.mm, ios/samples/hello-pbr/hello-pbr/FilamentView.mm, ios/samples/hello-triangle/hello-triangle/FilamentView.mm, ios/samples/transparent-rendering/transparent-rendering/FilamentView.mm
Also add simulator support to release and continuous builds.
Fixes #2144
=> Support Metal in the iOS simulator

android/filamat-android/src/main/cpp/MaterialBuilder.cpp, android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java
=> Use an int, not byte, for variantFilter

filament/include/filament/Material.h, filament/src/Material.cpp, filament/src/details/Material.h
New function which returns false/true wether an existing parameter is a sampler. This can be used to dynamically set a texture when a parameter is a sampler or otherwise a vec4 color.
=> Check if an existing material parameter is a sampler

RELEASE_NOTES.md, libs/gltfio/materials/ubershader.mat.in, libs/gltfio/src/MaterialGenerator.cpp
=> gltfio: use highp for UV coords.

web/filament-js/filament.d.ts
Got the right target branch :)
=> Update TypeScipt declarations

android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/CMakeLists.txt, filament/include/filament/View.h, filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/Renderer.cpp, filament/src/View.cpp, filament/src/details/View.h, filament/src/materials/colorGrading.mat, filament/src/materials/colorGradingAsSubpass.mat, samples/gltf_viewer.cpp, shaders/CMakeLists.txt, shaders/src/common_graphics.fs, shaders/src/post_process_inputs.fs, shaders/src/vignette.fs
=> Add vignette post-processing effect

build/windows/build-github.bat, filament/backend/src/vulkan/VulkanContext.h
=> Fix VS 2019 build failure with Vulkan

filament/backend/src/vulkan/VulkanContext.cpp, filament/backend/src/vulkan/VulkanContext.h, filament/backend/src/vulkan/VulkanDriver.cpp, filament/backend/src/vulkan/VulkanHandles.cpp
=> Vulkan: add diagnostics to check if format is sampleable.

libs/filamat/include/filamat/MaterialBuilder.h, libs/filamat/src/MaterialBuilder.cpp, libs/filamat/src/shaders/ShaderGenerator.cpp, libs/filamat/src/shaders/ShaderGenerator.h, tools/matc/src/matc/CommandlineConfig.cpp, tools/matc/src/matc/Config.h, tools/matc/src/matc/MaterialCompiler.cpp
=> Add matc support for command-line preprocessor defines

filament/backend/include/backend/TargetBufferInfo.h, filament/backend/src/metal/MetalHandles.h, filament/backend/src/metal/MetalHandles.mm, filament/backend/src/vulkan/VulkanBinder.cpp, filament/backend/src/vulkan/VulkanBinder.h, filament/backend/src/vulkan/VulkanContext.h, filament/backend/src/vulkan/VulkanDriver.cpp, filament/backend/src/vulkan/VulkanFboCache.cpp, filament/backend/src/vulkan/VulkanFboCache.h, filament/backend/src/vulkan/VulkanHandles.cpp, filament/backend/src/vulkan/VulkanHandles.h
Tested by enabling depth of field.
=> Vulkan: add support for MRT.

filament/src/Texture.cpp
=> Swizzle textures when swizzle is enabled, not the other way around

filament/src/materials/dof.mat
This is still work in progress and disabled.
=> Some infrastructure to support arbitrary shaped diaphragm

filament/README.md
=> Add bluevk.lib to Windows README

filament/include/filament/Camera.h, libs/gltfio/include/gltfio/FilamentAsset.h, libs/gltfio/src/AssetLoader.cpp, samples/gltf_viewer.cpp
Fixes aspect ratio issue mentioned in #1988
=> Fix glTF camera aspect ratio

android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java, android/filament-android/src/main/java/com/google/android/filament/Material.java
=> Fix material parameters enum

web/filament-js/filament.d.ts
Not really sure if Vector&lt;T&gt; should be an interface or a type alias, probably doesn't matter.
https://github.com/google/filament/blob/c6d9d4a9aec0ebbdd17c28eca3dc6c587d4a64c1/web/filament-js/extensions.js#L29-L35
https://github.com/google/filament/blob/c6d9d4a9aec0ebbdd17c28eca3dc6c587d4a64c1/web/filament-js/jsbindings.cpp#L1537-L1544
=> Filament.d.ts: add Vector<T> interface, vectorToArray<T> fn, fix getResourceUris() return vec

libs/gltfio/include/gltfio/AssetLoader.h, web/filament-js/filament.d.ts, web/filament-js/jsbindings.cpp, web/samples/helmet.html
=> gltfio for web: add and use destroyAsset.

android/filament-android/src/main/cpp/Camera.cpp, android/filament-android/src/main/java/com/google/android/filament/Camera.java, filament/include/filament/Camera.h
=> Add getCullingProjectionMatrix JNI method

android/filament-android/src/main/cpp/SurfaceOrientation.cpp
Fix the non-implement exception by correcting the JNI method name
=> Fix typo in SurfaceOrientation jni wrapper

android/filament-android/src/main/cpp/ColorGrading.cpp, android/filament-android/src/main/java/com/google/android/filament/ColorGrading.java, filament/include/filament/ColorGrading.h, filament/src/ColorGrading.cpp, samples/gltf_viewer.cpp
Low: 16x16x16 LUT in 10 bit
Medium: 32x32x32 LUT in 10 bit
High: 32x32x32 LUT in 16 bit
Ultra: 64x64x64 LUT in 16 bit
=> Add quality option to ColorGrading

third_party/glslang/glslang/Include/intermediate.h, third_party/glslang/glslang/MachineIndependent/Intermediate.cpp, third_party/glslang/glslang/MachineIndependent/ParseHelper.cpp, third_party/glslang/tnt/README.md
glslang repo SHA: f3cb1896971f449706bb1df5053d0e8fad6b0675
This fixes another highp bug.
=> update glslang to latest

libs/filamat/src/MaterialBuilder.cpp, libs/filamat/src/sca/GLSLToolsLite.cpp, libs/filamat/src/sca/GLSLToolsLite.h, libs/filamat/tests/test_filamat_lite.cpp
=> Remove Google-style line directives in filamat lite

filament/backend/src/opengl/OpenGLDriver.cpp
So...we use integers for bone indices, and that makes them special. :)
On May 26, the emsdk WebGL 2.0 wrapper for the integer variant of
VertexAttribPointer was broken due to an incomplete renaming operation
from an emscripten contributor.
My upstream fix to the emscripten repo ([#11742](https://github.com/emscripten-core/emscripten/pull/11742)) has been merged but this won't percolate to the emsdk for a while, so let's work around this with a simple monkeypatch.
Fixes #2856.
=> WebGL: Add workaround for skinning with Emscripten.

web/filament-js/extensions.js, web/filament-js/filament.d.ts, web/filament-js/jsbindings.cpp, web/filament-js/jsenums.cpp
This is not tested but seems fairly straightforward.
=> ColorGrading: add JavaScript and TypeScript bindings.

filament/src/ColorGrading.cpp
we just move the conversion code into the already existing jobs.
=> multithread the conversion to RGB10_A2

libs/gltfio/CMakeLists.txt, libs/gltfio/materials/transmission.mat.in, libs/gltfio/src/MaterialGenerator.cpp, libs/gltfio/src/UbershaderLoader.cpp
=> Transmission should use FADE.

RELEASE_NOTES.md, android/filament-android/src/main/cpp/IndirectLight.cpp, android/filament-android/src/main/cpp/SkyBox.cpp, android/filament-android/src/main/java/com/google/android/filament/IndirectLight.java, android/filament-android/src/main/java/com/google/android/filament/Skybox.java, filament/include/filament/IndirectLight.h, filament/include/filament/Skybox.h, filament/src/IndirectLight.cpp, filament/src/Skybox.cpp, filament/src/View.cpp, filament/src/details/IndirectLight.h, filament/src/details/Skybox.h, web/filament-js/extensions.js, web/filament-js/filament.d.ts, web/filament-js/jsbindings.cpp
=> Add Texture getters to IndirectLight and Skybox.

filament/CMakeLists.txt, filament/include/filament/View.h, filament/src/FrameHistory.h, filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/Renderer.cpp, filament/src/View.cpp, filament/src/details/View.h, filament/src/fg/FrameGraphHandle.h, filament/src/materials/antiAliasing/taa.mat, libs/gltfio/include/gltfio/SimpleViewer.h
while this started as a sample to demonstrate how to use the new
frame history feature, this is now solid enough to become a feature.
this version of TAA doesn't use motion vectors, so it is prone to
various artifacts (e.g. ghosting). It also has the typical issues
TAA has (e.g. transparents).
with that said, performance is good and quality is overall superior
to FXAA or MSAAx4.
=> Implement basic temporal antialiasing (TAA)

android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/src/Renderer.cpp, filament/src/materials/antiAliasing/taa.mat
variance clamping further shrinks the min/max AABB
=> Implement variance clamping

filament/src/materials/blitHigh.mat, filament/src/materials/bloom/bloomDownsample.mat, filament/src/materials/bloom/bloomUpsample.mat, filament/src/materials/dof/dofDownsample.mat, filament/src/materials/dof/dofMedian.mat, filament/src/materials/dof/dofMipmap.mat, filament/src/materials/dof/dofTiles.mat
this really makes the code easier to read and has a chance to be
more efficient
=> make use of textureLodOffet where appropriate

filament/backend/src/opengl/OpenGLDriver.cpp
=> fix incorrect assert in GL backend

filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/Renderer.cpp, filament/src/details/Renderer.h
while support for this is added, this is disabled because
it is actually ~0.5ms slower on qualcomm devices.
=> Allow color-gradding-as-subpass with TAA

filament/src/ShadowMap.cpp
This is in preparation for VSM, which needs to access the light's position in the shaders.
=> Set the model matrix and projection separately for shadow cameras

filament/test/depth_test.cpp
we just make the output more readable
=> slightly improve the depth_test

filament/backend/src/vulkan/VulkanContext.cpp
This is useful to see which version of MoltenVK is actually being used.
=> Vulkan: log driver version info.

web/filament-js/filament.d.ts
been bugging you guys a lot 😬 so here's my tiny little contribution
thanks for sharing your great work. hopefully will be able to help out more once I get more familiar with filament
=> typescript defs for Texture &   RenderTarget APIs

filament/backend/src/metal/MetalBlitter.h, filament/backend/src/metal/MetalBlitter.mm, filament/backend/src/metal/MetalDriver.mm
=> Handle blitting only depth in Metal backend

filament/src/Renderer.cpp
the depth buffer wasn't resolved in this case. We fix this by always
creating a depth buffer resolve pass -- which is a lot more robust.
this pass automatically culled if the depth is not used (i.e. TAA or 
DoF are off). The pass is a no-op if resolving is not needed.
=> fix refraction + MSAA + TAA (depth resolve)

filament/src/Renderer.cpp
This just move the "finish color passes" pass before TAA and 
depth-resolve, where it belongs.
=> minor refactor + comments in the main render pass

filament/src/ShadowMap.cpp, shaders/src/shadowing.fs
it can be done more easily on the cpu side
=> don't do the "reverse-z" in the shader for shadows

filament/backend/include/private/backend/BackendUtils.h, filament/backend/src/BackendUtils.cpp, filament/backend/src/opengl/OpenGLProgram.cpp, filament/test/filament_test.cpp
=> Remove Google-style line directives driver-side

filament/src/fg/FrameGraph.cpp
this is needed now that shadows are using the framegraph
=> increase framegraph vector heap

filament/src/PostProcessManager.cpp, filament/src/PostProcessManager.h, filament/src/details/Engine.h
This way it can be used elsewhere.
=> Random engine should be owned by Engine

android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/include/filament/View.h, filament/src/Renderer.cpp, filament/src/View.cpp, filament/src/details/View.h, libs/filagui/src/ImGuiHelper.cpp, libs/filamentapp/src/FilamentApp.cpp
Just like with shadows, this is a toggle to entirely disable
screen space refraction.
Added missing getters, and minor refactoring.
=> APIs to enable/disable screen space refraction

filament/src/Material.cpp, libs/matdbg/web/script.js
This change also makes it so that matdbg shows a numeric suffix to help
with duplicated names, and fixes a bug with names that start with
non-alpha characters.
=> matdbg: do not hide anonymous materials

libs/gltfio/src/Animator.cpp
Tested with the model in #3124 as well as Fox, BusterDrone, CesiumMan, InterpolationTest, and VC.
Fixes #3124.
=> gltfio: Fix animation by clamping the per-channel interpolant.

libs/filamentapp/src/FilamentApp.cpp, libs/viewer/include/viewer/AutomationEngine.h, libs/viewer/src/AutomationEngine.cpp, samples/gltf_viewer.cpp
This should only be used in combination with --batch. Users are
admonished if they try using it on its own.
=> gltf_viewer: add --headless option.

filament/src/IndirectLight.cpp, filament/src/details/IndirectLight.h
=> Fix null pointer dereference in FIndirectLight

RELEASE_NOTES.md, filament/src/PostProcessManager.cpp
=> Destroy dummyOneTextureArray in PostProcessManager

libs/viewer/schemas/README.md, libs/viewer/schemas/automation.json, libs/viewer/tests/basic.json
This can help when authoring a spec using your favorite text editor.
=> Add JSON schema for automation specs.

filament/backend/src/metal/MetalDriver.mm, filament/docs/Debugging.md, filament/src/Renderer.cpp, filament/src/details/Engine.h, samples/gltf_viewer.cpp
Xcode frame capture is buggy. This makes debugging Metal issues 100x easier.
=> Add capture frame button to gltf_viewer

filament/backend/src/vulkan/VulkanContext.cpp
Fixes #3037, #2872
Not 100% confident this is the right fix, @prideout can advise.
=> Fix Vulkan black screen on Windows with NVIDIA hardware

filament/backend/src/vulkan/VulkanDriver.cpp, filament/backend/src/vulkan/VulkanHandles.cpp
=> Vulkan + Android: fix build break.

.gitignore, BUILDING.md, build/swiftshader/Dockerfile, build/swiftshader/gallery.py, build/swiftshader/patch_00.diff, build/swiftshader/test.sh, libs/viewer/src/AutomationEngine.cpp, libs/viewer/src/AutomationSpec.cpp
This adds a Dockerfile and a new bash script that makes it
east to invoke the appopriate Docker commands.
This does not yet enable a GitHub Action because of intermittent
issues that we have not yet ironed out.
=> Add Dockerfile and test script for SwiftShader.

filament/backend/src/vulkan/VulkanDriver.cpp
This makes it so that the PixelBufferDescriptor callback triggers at a
time consistent with other backends.
ReadPixels is still asynchronous in the sense that the callback is
triggered on the main thread. However, it is now guaranteed to trigger
during (or before) flushAndWait(), which is less surprising behavior.
=> Vulkan: make ReadPixels synchronous.

libs/gltfio/src/Animator.cpp
Release builds do not call cgltf_validate() so it was possible to
read out-of-bounds animation data when encountering a badly formed glTF
file with mismatched counts between sampler inputs and outputs.
=> gltfio: fix ASAN issue when consuming invalid animation.

libs/gltfio/src/Animator.cpp
=> gltfio: Fix animator crash for orphaned nodes.

filament/include/filament/SwapChain.h
=> Update native window documentation

filament/backend/src/metal/MetalHandles.mm
=> Fix Metal assertion when loading into texture arrays

tools/resgen/src/main.cpp
This option embeds a small JSON string inside the resgen blob that lists
all materials and their respective sizes. This is useful when analyzing
the footprint of the binary executable.
=> resgen: add --json option.

tools/zbloat/Dockerfile, tools/zbloat/README.md, tools/zbloat/evmar_bloat.py, tools/zbloat/template.html, tools/zbloat/zbloat.py, tools/zbloat/zbloat.sh
This tool makes it easy to analyze the composition of Android applications that use Filament.  It generates treemaps that include materials if resgen was invoked with the JSON flag.
See [README.md](https://github.com/google/filament/blob/6ec897f4f79cdb88fa6aa89d7a57953318483504/tools/zbloat/README.md) for usage instructions.  Go [here](https://prideout.net/webtreemap/demo.html) for a demo.
=> Add zbloat tool.

android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java, filament/include/filament/RenderableManager.h
I also double-checked the backends, they indeed treat it as an index
count.
Fixes #3351
=> Fix RenderableManager docs for "index"

libs/filamat/CMakeLists.txt, libs/filamat/src/GLSLPostProcessor.cpp, libs/filamat/src/GLSLPostProcessor.h, libs/filamat/src/ShaderMinifier.cpp, libs/filamat/src/ShaderMinifier.h
This shrinks the arm64 so file by 24 KiB.  Tested on Android.
=> filamat: minify struct fields.

libs/gltfio/CMakeLists.txt
=> Install gltfio_resources and gltfio_resources_lite for desktop builds

libs/gltfio/src/ResourceLoader.cpp
Faulty or missing texture files would cause the background decoder thread to never finish and would generate textures with 0x0 dimensions, which eventually triggers `GL_INVALID_VALUE`.
To recap, gltfio texture loading has two phases: the first phase is synchronous and uses `stbi_info` to gather texture info. The second phase is asynchronous and uses `stbi_load` to do the actual decoding.
During the first phase, we now check the return code from `stbi_info` rather than assuming that it worked.  :)
Fixes #3344
=> gltfio: Improve robustness when decoding textures.

filament/src/PostProcessManager.cpp
This line of code appears to affect Android phones on Qualcomm's platform，This line of code will not work without it
=> fix material use

samples/rendertarget.cpp
By default, the demo now reflects the camera instead of the renderable.
However this can be changed via the command line. Users can now change
the backend too.
=> Add options to planar reflection demo.

filament/backend/src/metal/MetalContext.h, filament/backend/src/metal/MetalDriver.mm, filament/backend/src/metal/MetalState.h
=> Metal: honor inverseFrontFaces RasterState.

build/linux/combine-static-libs.sh
=> Update combine-static-libs.sh script to work with universal binaries

filament/backend/CMakeLists.txt, filament/backend/test/test_FeedbackLoops.cpp
This test passes on my Radeon GPU MacBook but fails with an Intel GPU.
=> Add unit test for feedback loops.

libs/gltfio/src/ResourceLoader.cpp
Recall that we now use shared_ptr to simplify lifetime management of
cgltf source data (#3413).
Before this commit, we were only using shared_ptr to retain the source
data during buffer uploads. After this commit, we are using it to retain
source data during texture decoding.
Fixes #3428.
=> gltfio: fix crash during async texture decode.

android/gltfio-android/src/main/cpp/MaterialProvider.cpp, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java, android/gltfio-android/src/main/java/com/google/android/filament/gltfio/MaterialProvider.java, libs/gltfio/include/gltfio/MaterialProvider.h
=> gltfio on Java: free material cache in AssetLoader.destroy

filament/backend/test/test_FeedbackLoops.cpp
Previously this test was actually finding a ReadPixels failure on Intel GPU's, rather than a failure of feedback loop behavior. This was due to the fact that it was calling ReadPixels on a non-zero miplevel, which seems to be unsupported on Intel GPU's.
The test now follows the downsample phase with an upsample phase, just like the real bloom effect. This allows us to issue ReadPixels on the base level, thus making the test more targetted to rendering feedback loops.
In a subsequent PR, I will add `setMinMaxLevels` to the driver API and modify the test accordingly.  Good (Radeon) and Bad (Intel) screenshots are below.
=> Rewrite and enhance test_FeedbackLoops.

filament/backend/CMakeLists.txt, filament/backend/src/vulkan/VulkanBlitter.cpp, filament/backend/src/vulkan/VulkanBlitter.h, filament/backend/src/vulkan/VulkanContext.cpp, filament/backend/src/vulkan/VulkanContext.h, filament/backend/src/vulkan/VulkanDriver.cpp, filament/backend/src/vulkan/VulkanDriver.h
This is a prep step to fix #3485.
=> Refactoring: Add VulkanBlitter, inspired by MetalBlitter.

filament/backend/CMakeLists.txt, filament/backend/src/vulkan/BlitColor.fs, filament/backend/src/vulkan/BlitColor.vs, tools/matc/src/matc/CommandlineConfig.cpp, tools/matc/src/matc/Config.h, tools/matc/src/matc/MaterialCompiler.cpp, tools/matc/src/matc/MaterialCompiler.h
This feature can generate SPIRV blobs and will be used by VulkanBlitter.
(#3485)
=> matc: add --raw argument for internal use.

samples/materials/mirror.mat, samples/rendertarget.cpp
The colors now match up perfectly.  Woops.
(#3402)
=> RenderTarget demo now disables post-processing in offscreen view.

filament/backend/include/backend/PixelBufferDescriptor.h
=> Fix, computeDataSize returns incorrect value for USHORT_565

filament/backend/CMakeLists.txt, filament/backend/test/test_Blit.cpp
This is fairly simple for now, only does color.
Will enhance in a future PR.
=> Add backend unit test for blit.

filament/backend/test/test_Blit.cpp
Since we cannot upload a depth buffer, this test works by first drawing
a triangle into COLOR + DEPTH, copying them both to a new render target,
then drawing a slightly larger triangle just underneath the first one.
=> Add a depth blit to the backend test suite.

android/filament-utils-android/src/main/java/com/google/android/filament/utils/Manipulator.java
=> Correctly name JNI methods so they can be found

filament/backend/CMakeLists.txt, filament/backend/src/vulkan/VulkanContext.cpp, filament/backend/src/vulkan/VulkanMemory.cpp
This will improve parity between the GitHub repo and its sister codebase
within Google.
=> Move vk_mem_alloc to its own cpp.

android/filament-android/src/main/java/com/google/android/filament/Stream.java, filament/include/filament/Stream.h
Mathias noticed that the `setAcquiredImage` method was not well
documented on the C++ side. While fixing this I figured I'd try to write
up a docstring for the class itself.
=> Provide a docstring for the Stream class.

libs/utils/include/utils/Panic.h, libs/utils/src/Panic.cpp, libs/utils/src/debug.cpp
rename logAndPanic to panicLog, since it doesn't actually panics.
=> assert_invariant() now terminates the program in failure

filament/src/PostProcessManager.cpp
- generously document the CoC computation
- rewrite the code so that the computation will work for any
perspective projection matrix, instead of assuming
an "infinite-far" projection.
=> Improve circle-of-confusion computation

libs/filamentapp/src/FilamentApp.cpp, samples/gltf_viewer.cpp
useful for debugging shadows problems
=> add the --split-view option to gltf_viewer

filament/src/RenderTarget.cpp, filament/src/Renderer.cpp, filament/src/details/RenderTarget.h, filament/src/details/Renderer.h, filament/src/details/View.h
We were not declaring the attachments it was using.
Fixes #3628
=> Fixes some issues with imported rendertargets

libs/gltfio/src/ResourceLoader.cpp
The vertex data for glTF morph targets are deltas rather than final
values, so we were passing incorrect data into the SurfaceOrientation
helper.
This has been a long-standing bug that affected models with morphing,
including Buster Drone. However in practice we have observed visual
issues only with AnimatedMorphCube.
Tested against AnimatedMorphCube, Buster Drone, Cesium Man, Fox, and
Littlest Tokyo.
Fixes #1609
=> gltfio: Fix tangents when morphing is enabled.

filament/backend/src/DriverBase.h, filament/backend/src/opengl/GLUtils.h, filament/src/PostProcessManager.cpp, filament/src/components/LightManager.cpp, libs/filamentapp/src/IBL.cpp, libs/gltfio/include/gltfio/MaterialProvider.h, libs/ibl/src/CubemapUtils.cpp, libs/matdbg/src/ShaderReplacer.cpp, libs/math/include/math/half.h, libs/utils/include/utils/Allocator.h, libs/utils/include/utils/NameComponentManager.h, libs/utils/include/utils/StructureOfArrays.h, libs/utils/src/Allocator.cpp, libs/viewer/src/AutomationSpec.cpp, libs/viewer/src/Settings.cpp, tools/cmgen/src/cmgen.cpp, tools/cso-lut/src/main.cpp, tools/matc/src/matc/JsonishLexer.cpp, tools/matc/src/matc/JsonishParser.cpp, tools/resgen/src/main.cpp
=> add missing includes

android/gltfio-android/CMakeLists.txt, libs/gltfio/CMakeLists.txt, libs/gltfio/src/ResourceLoader.cpp, libs/gltfio/src/TangentsJob.cpp, libs/gltfio/src/TangentsJob.h
This cleans up the glTF tangents generator and allows it to be used in other parts of the library.  Also removed un-necessary usage of std vector.
=> gltfio: Refactor the tangents job.

libs/gltfio/src/Animator.cpp, libs/gltfio/src/FFilamentAsset.h
This does not change any behavior, it just prepares for the new MorphHelper class that will arrive in the next PR.
=> gltfio: Refactor Animator.

filament/include/filament/View.h
=> attempt to improve doxygen formatting

filament/backend/src/metal/MetalHandles.mm
=> Fix Metal bug when setGeometryAt is called multiple times

filament/src/materials/dof/dof.mat
=> DoF: code refactoring and foreground opacity improvement

samples/CMakeLists.txt, samples/suzanne.cpp
=> Add Metal and Vulkan backend support to Suzanne sample

android/filament-android/src/main/cpp/View.cpp, android/filament-android/src/main/java/com/google/android/filament/View.java, filament/CMakeLists.txt, filament/include/filament/View.h, filament/src/PostProcessManager.cpp, filament/src/materials/dof/dof.mat, filament/src/materials/dof/dofCoc.mat, filament/src/materials/dof/dofDownsample.mat, libs/viewer/src/Settings.cpp, libs/viewer/src/SimpleViewer.cpp, web/filament-js/jsbindings.cpp
- native/half resolution
- gather kernel ring counts
- circle-of-confusion radius clamps
=> DoF: add many user settings

shaders/src/ambient_occlusion.fs
=> SSAO: fix high-quality upsampling

web/filament-js/CMakeLists.txt, web/filament-js/filament-viewer.js, web/filament-js/package.json, web/samples/CMakeLists.txt, web/samples/test-filament-viewer.html
Just for fun, this is an example of a web component that allows you
to embed a Filament viewer with a single HTML element. It does not have
many features, but is much easier to use than our raw JavaScript API.
=> Add web component demo.

android/filament-android/libfilament-jni.map, libs/gltfio/src/Animator.cpp, libs/gltfio/src/AssetLoader.cpp, libs/gltfio/src/FFilamentAsset.h, libs/gltfio/src/FilamentAsset.cpp, libs/gltfio/src/MorphHelper.cpp, libs/gltfio/src/MorphHelper.h, libs/gltfio/src/ResourceLoader.cpp
149 additions and 305 deletions.
=> gltfio: Use BufferObject API, simplify MorphHelper.

filament/backend/src/metal/MetalDriver.mm
This aids in debugging Metal issues with Intel integrated GPUs on Macbook Pros. Yeah, gfxCardStatus can do this too, but it's a bit finicky and won't work if you're connected to an external monitor.
=> Check environment variable to force integrated Metal device

filament/backend/src/opengl/OpenGLContext.cpp, filament/backend/src/opengl/OpenGLContext.h, filament/backend/src/opengl/OpenGLDriver.cpp
- be more consistant with extension naming
- sort extension queries alphabetically
=> gl backend minor code cleanup

build/web/ci-common.sh
This now matches what is already specified in BUILDING.md
=> Update emscripten in Google Actions.

filament/backend/src/opengl/GLUtils.cpp, filament/backend/src/opengl/GLUtils.h, filament/backend/src/opengl/OpenGLDriver.cpp, libs/utils/src/ostream.cpp
no functionality changes, just easier to use when debugging.
=> improve a bit GLES error logging code.

filament/src/materials/dof/dof.mat, filament/src/materials/ssao/bilateralBlur.mat, filament/src/materials/ssao/sao.mat, filament/src/materials/ssao/ssaoUtils.fs, filament/src/materials/ssao/ssct.fs, shaders/src/common_getters.fs, shaders/src/getters.fs, shaders/src/shadowing.fs
- DoF: don't convert gl_FragCoord to mediump when generating noise
- SSAO: add a bunch of missing highp qualifiers
- all matrices and UV should be highp
- Also fix some typo in comments.
=> Fix some mediump related issues

BUILDING.md, build/web/ci-common.sh
The latest version of emscripten includes major updates to LLVM and
Binaryen.
=> Update emscripten to 2.0.17

docs/index.html, docs/viewer/filament-viewer.js, docs/viewer/index.html, site/themes/hyde/layouts/index.html
This will allow folks to drop a GLB into the following page to get a WebGL
preview. It always uses the latest version of Filament via unpkg.
https://google.github.io/filament/viewer
After the next release we can also use the `<filament-viewer>` component
itself from unpkg and remove the local copy.
=> Add glTF viewer to public website.

libs/geometry/src/SurfaceOrientation.cpp, libs/gltfio/src/DracoCache.cpp, libs/gltfio/src/DracoCache.h, libs/gltfio/src/ResourceLoader.cpp
These changes are motivated by #3815.
See also:
https://github.com/KhronosGroup/glTF-Blender-IO/issues/1326
https://github.com/KhronosGroup/glTF-Blender-IO/issues/1345
=> gltfio: robustness improvements for Draco meshes.

build/common/test_list.txt, filament/include/filament/VertexBuffer.h, libs/geometry/CMakeLists.txt, libs/geometry/include/geometry/Transcoder.h, libs/geometry/src/Transcoder.cpp, libs/geometry/tests/test_transcoder.cpp
We will add JavaScript and Java support in a later PR.
=> Add Transcoder API for C++ clients.

filament/include/filament/RenderTarget.h, filament/src/RenderTarget.cpp, filament/src/details/RenderTarget.h
=> fix a memory corruption introduced recently

shaders/src/light_indirect.fs
- fix a lod selection bug
- add interleaved gradient noise when sampling the brdf
- compute the diffuse using importance sampling too
=> improve the importance sampling code

docs/Materials.md.html, shaders/src/getters.fs
=> Fix documentation for getNormalizedViewportCoord

filament/src/PostProcessManager.cpp, filament/src/materials/ssao/sao.mat, filament/src/materials/ssao/ssaoUtils.fs, shaders/src/ambient_occlusion.fs
- implemented accurate normal reconstruction (enabled on desktop only for now)
- tweaked parameters to improve noise pattern at `LOW` and `HIGH` quality levels
=> SSAO quality improvements

samples/lightbulb.cpp
=> lightbulb: clear background

filament/src/PostProcessManager.cpp, filament/src/materials/ssao/sao.mat
- high quality upsampling didn't work when low pass was disabled
- fix a typo in the accurate normal reconstruction
=> Improvements to SSAO

filament/backend/src/vulkan/VulkanDriver.cpp
Fixes the flashing bloom issue on Mali devices.
=> Vulkan: add a barrier after each render pass.

filament/backend/src/vulkan/VulkanDriver.cpp, filament/backend/src/vulkan/VulkanPipelineCache.cpp, filament/backend/src/vulkan/VulkanPipelineCache.h
The API of the pipeline cache is now easier to use. Internally, it now
maintains separate pipeline and descriptor bindings for each command
buffer, since that's how Vulkan works.
=> VulkanPipelineCache: refactor and simplify.
