google/filament

filament/include/filament/RenderableManager.h
filament/src/Material.cpp
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Scene.cpp
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
filament/src/details/Scene.h

- We were not setting the bones ubo staging buffer size correctly
- The bones UBO was never bound to the shader
- The default values for the bones ubo wasn’t identity

Fix skinning bugs

---

libs/image/src/ImageDecoder.cpp

When compiling with clang on Linux, the following warning is generated:
```
../../libs/image/src/ImageDecoder.cpp:487:13: warning: unterminated '#pragma pack (push, ...)' at end of file [-Wpragma-pack]
#pragma pack(push, 1)
^
```
According to [1], the correct pragma to pop the packing state from the internal stack is "#pragma pack(pop)" rather than "#pragma pop()" which is used currently. This PR replaces "#pragma pop()" with "#pragma pack(pop)".
[1] http://gcc.gnu.org/onlinedocs/gcc-4.2.3/gcc/Structure_002dPacking-Pragmas.html

libs/image: fix structure-packing pragma warning

---

README.md

Windows: Clang 7 crashes, Clang 6 is required instead.

---

filament/src/Froxel.cpp
filament/src/RenderPass.cpp
filament/src/RenderPrimitive.cpp
filament/src/Renderer.cpp
filament/src/View.cpp
filament/src/components/RenderableManager.cpp
filament/src/details/Froxel.h
filament/src/details/RenderPrimitive.h
filament/src/details/View.h
filament/test/filament_test.cpp

Because DriverAPI is not thread-safe, it’s better
to make its usage more explicit — so it’s now
passed as argument of all methods that need it.
also pass Engine as parameter in internal classes
that made little use of it (i.e. no point in
storing it if we can just pass it a sa parameter).
Change-Id: I9142959437ed3d8c8ecb7bcd030ea55d9c8ef352

Refactor code a bit to make usage of DriverAPI more explicit

---

libs/utils/include/utils/StructureOfArrays.h

The compiler cannot infer the type of the constructed object when
using the shorthand syntax.
Fixes #30

Prevent compilation error on Windows

---

README.md
filament/CMakeLists.txt
libs/filamat/CMakeLists.txt
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/filamat/src/shaders/Shaders.h
shaders/CMakeLists.txt

Each shader string is now part of a separate .o file, which should make recompiling `filamat`/`matc` a tad more enjoyable.

Compile shaders in a separate static library

---

shaders/CMakeLists.txt

For passing arguments to a CMake `COMMAND` like echo, each word must not include spaces and be surrounded by double quotes. Unfortunately this is the only way I've found to get consistent behavior across platforms.
```
add_custom_command(
OUTPUT ${output_path}
COMMAND del ${output_path}
COMMAND echo "hello" >> ${output_path}
COMMAND echo "hello world" >> ${output_path}
COMMAND echo "hello ${DQUOTE}world${DQUOTE}" >> ${output_path}
COMMAND echo "hello" " " "world" >> ${output_path}
COMMAND echo "hello" "a" "world" >> ${output_path}
)
```

Fix shader compilation on Windows

---

libs/filaflat/include/filaflat/MaterialParser.h
libs/filamat/include/filamat/MaterialBuilder.h

`MaterialParserDetails` and `MaterialInfo` are structs.

Fix forward declaration type. 

---

third_party/spirv-tools/CMakeLists.txt

We don't need the pkg-config step of spirv-tools' build configuration. Let's turn this off to keep the build quiet when nothing has changed.

Make spirv-tools more quiet

---

libs/utils/CMakeLists.txt
libs/utils/include/utils/Path.h
libs/utils/src/Path.cpp
libs/utils/src/win32/Path.cpp
libs/utils/test/test_WinPath.cpp

Fix `Path::split`, `Path::isAbsolute`, `Path::getParent`, and `getCanonicalPath` on Windows.
Fixes #13 
Fixes #14
Some edge-case windows pathing may still not work:
- "drive relative" paths: "C:tmp.txt"
- UNC paths (network paths): "\\foo\\bar" (will be collapsed to \foo\bar, which may resolve to a different location than expected)
- "absolute paths": "\foo\bar" (may or may not resolve to drive root)

Fix pathing issues on Windows

---

libs/imageio/src/ImageDecoder.cpp
tools/cmgen/src/CubemapUtils.cpp
tools/cmgen/src/CubemapUtils.h
tools/cmgen/src/cmgen.cpp

Fixes bug #45 
cmgen always expects the backing store of cubmaps to have an extra line and column, which wasn't the case when the input was not equirectangular.

Fix cmgen cross cubmap input

---

filament/src/details/Froxelizer.h
libs/filabridge/include/filament/EngineEnums.h

This always was the intention because internally 
it uses 8-bits buffers instead of 16-bits. One of
our temporary buffer goes from 4 MiB to 2 MiB.
This got mistakenly changed to 256 recently.

Set max number of lights to 255 instead of 256

---

filament/src/Froxelizer.cpp
filament/src/Scene.cpp
filament/src/View.cpp
filament/src/details/Froxelizer.h
filament/src/details/Scene.h
libs/filabridge/include/filament/EngineEnums.h

- fix froxelization with more than 255 lights
- fix stack corruption when the scene has more than 255 lights

froxelization fixes

---

filament/src/driver/vulkan/VulkanDriverImpl.cpp

Some Intel drivers report a max image count of 0, which is legit.
Fixes #71.

Fix the surfaceCapabilities check.

---

CMakeLists.txt
filament/CMakeLists.txt

Remove more unsupported compiler flags when clang-cl.exe is being used.
Introduced new var "CLANG_CL" to indicate that clang-cl.exe is being used and guard compiler switches appropriately.

More clang-cl.exe warning fixes

---

libs/utils/include/utils/RangeSet.h

some STL implementations assert when iterators are
out of range (even without dereferencing).
Fixes #94

use pointers instead of std::array<>::iterator

---

CMakeLists.txt

Somehow I missed the specified compiler version in the docs. Maybe I forgot about it by the time I got to the platform-specific requirements. Maybe I just can't read. Not sure what the problem was, but it would be nice for CMake to catch that sort of mistake.
This commit adds a warning for compilers that don't meet the project's minimum requirements. There is already an explicit check for GNU, but this will catch Clang versions that are too low as well as any non-GNU, non-Clang compilers.
The check is Linux-only as I have only built Filament on Linux and I'm not sure if this check would apply to Windows or OSX. The message is warning rather than an error to minimize the impact of false-positives caused by differing compiler names or version numbers. In particular, forks of clang may be …

Enhance CMake compiler check on Linux

---

filament/src/Froxelizer.cpp

apparently off-by-one’s hard. The first row of
our *source* froxel data must be skipped because
it contains a bit mask representing wether a light
is point or spot.

really fix the previous froxelization bug

---

filament/src/Froxelizer.cpp
filament/src/details/Engine.h
filament/src/details/Froxelizer.h
libs/filabridge/src/UibGenerator.cpp

This changes the layout of the froxels data
structure in the GPU so that the major axis
is the Z axis instead of X. The idea is that
within a given screen-space tile, we have a high
probability to access froxels at the same x/y
but different z.
This is turned off right now, as it requires
a change that breaks existing compiled materials.

option to reorder the froxel info for better cpu cache utilization

---

libs/utils/include/utils/algorithm.h
libs/utils/include/utils/bitset.h
libs/utils/test/test_algorithm.cpp

Use CTZ in bitset.forEachBitSet() so we can
efficiently go through them in order instead of
reverse order.

Add ctz to utils::algorithm

---

CMakeLists.txt
filament/CMakeLists.txt
filament/src/driver/ExternalContext.cpp
filament/src/driver/opengl/gl_headers.cpp
filament/src/driver/opengl/gl_headers.h

Causes gl_headers to use GLES, even on desktop.
Causes all ContextManagers to be elided;
users are expected to provide their own.

Add option USE_EXTERNAL_GLES3

---

libs/filagui/include/filagui/ImGuiHelper.h
libs/filagui/src/ImGuiHelper.cpp
libs/utils/include/utils/Path.h
libs/utils/src/Path.cpp
samples/CMakeLists.txt
samples/app/FilamentApp.cpp
samples/app/FilamentApp.h
samples/vk_hellopbr.cpp
samples/vk_shadowtest.cpp
samples/vk_texturedquad.cpp

This removes the build step where we copy a subset of assets, and makes
it so that FilamentApp hands out a "root path" for assets. For now this
is determined based on the location of the executable. This allows
developers to launch samples from any CWD.
Closes #11

Try to clean up asset folders for sample apps.

---

filament/src/driver/CircularBuffer.cpp
filament/src/driver/ExternalContext.cpp
filament/src/driver/opengl/ContextManagerWebGL.cpp
filament/src/driver/opengl/ContextManagerWebGL.h
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/opengl/gl_headers.h
libs/utils/include/utils/compiler.h
libs/utils/src/CallStack.cpp

This does not add any build stuff or new sample code yet, it just does some prep to our C++ codebase.
- Similar to Android, WebAssembly will not be using BlueGL. We were using a mixture of `#if` and `#ifdef` when checking for the existence of certain GL prototypes, but the latter is what we want to build robustly with any GL headers. (We still perform run-time checks for extensions, this doesn't change that.)
- Add a trivial ContextManager, does a bit more than Dummy since it   needs to create an actual driver. 
This doesn't get compiled yet, it   just adds files to the tree.
- WebAssembly does not support mmap, execinfo, or asm volatile.

Make code friendly to WebAssembly.

---

tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/CompiledGraph.kt
tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/GraphCompiler.java
tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/GraphFormatter.java
tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/Parameter.kt
tools/tungsten/core/src/com/google/android/filament/tungsten/model/Graph.kt
tools/tungsten/core/src/com/google/android/filament/tungsten/properties/IPropertiesPresenter.java
tools/tungsten/core/src/com/google/android/filament/tungsten/properties/PropertiesPanel.kt
tools/tungsten/core/src/com/google/android/filament/tungsten/ui/GraphPresenter.java
tools/tungsten/core/test/com/google/android/filament/tungsten/compiler/GraphCompilerTest.kt

- `GraphCompiler.compile` now returns an instance of `CompiledGraph` that contains the material definition along with a mapping from node properties to material parameters.
- Introduce PropertyHandles- a way to uniquely reference a single property in a graph. This simplifies logic for handling property updates, and in a future CL, with material parameter updating.

Tungsten: prep for material parameters editing

---

libs/math/include/math/mat3.h

`CHAR_BIT` is defined in `limits.h`

Add missing include to math/mat3.h

---

tools/tungsten/core/src/com/google/android/filament/tungsten/Filament.java
tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/NodeRegistry.kt
tools/tungsten/core/src/com/google/android/filament/tungsten/model/Nodes.kt
tools/tungsten/core/src/com/google/android/filament/tungsten/model/Properties.kt
tools/tungsten/core/src/com/google/android/filament/tungsten/properties/PropertiesPanel.kt
tools/tungsten/core/src/com/google/android/filament/tungsten/ui/GraphPresenter.java
tools/tungsten/core/src/com/google/android/filament/tungsten/ui/TungstenPanel.java

Node property can now influence a material parameter. Model is now stored in `GraphPresenter` as an `AtomicReference<Graph>` because it is read from the `Filament` thread and written to from the `UI` thread.

Tungsten: add material parameters editing

---

filament/src/driver/opengl/ContextManagerWGL.cpp
filament/src/driver/opengl/ContextManagerWGL.h

`wglMakeCurrent` requires the pixel format match between the HGLRC and HDC. Previously, the pixel format of the HDC wasn't explicitly set, and on most implementations, this leads to a failure.
I decided to stash off the PFD, and use that re-query the pixel format index from the WGL layer. The PFD and pixel format index are both required in order to call `SetPixelFormat`.
Alternative solutions:
* Stash off the pixel format index. This saves a call to `ChoosePixelFormat` in `ContextManagerWGL::createSwapChain`. _Technically_, the index is dependent on the HDC as well, and the HDC does change between calls to `ChoosePixelFormat`. However, I can't imagine any implementation deciding to change their pixel format indices across HDCs sourced from similar windows (dangerous assumption)
* Make the …

WGL: Match pixel formats across HDC and HGLRC

---

filament/include/filament/VertexBuffer.h
filament/src/VertexBuffer.cpp
filament/src/driver/Driver.h
filament/src/driver/DriverBase.h
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/vulkan/VulkanHandles.cpp
libs/filabridge/include/filament/EngineEnums.h
libs/filabridge/include/filament/driver/DriverEnums.h

According to the spec, an attribute declared as an integer (ivec* or uvec* in the shaders) but be bound using `glVertexAttribIPointer` instead of `glVertexAttribPointer`. This means we were not binding bone indices correctly for GPU skinning. This issue was hidden by lenient drivers, particularly on Android.

Fix binding of integer attributes

---

samples/web/CMakeLists.txt

This uses `foreach` in order to create proper dependencies for each cubemap face and miplevel.
It also adds a custom command for the mesh and envmap assets, similar to how we already handle materials. This seems to work properly and rebuilds the assets only when upstream dependencies have been dirtied, or when downstream dependencies have been deleted.

CMake improvements for samples/web.

---

filament/src/driver/vulkan/VulkanBinder.cpp

Previously, the contents of mDescriptorKey were not being initialized during VulkanBinder construction. This could leads to bugs, such as getOrCreateDescriptor finding false entries inside the DescriptorKey::uniformBuffers or DescriptorKey::samplers arrays.
I found the issue on Win10 Vulkan.  Both the AMD ICD and VK_LAYER_LUNARG_standard_validation layer complained about issues that manifested in vkUpdateDescriptorSets.

Properly initialize VulkanBinder::mDescriptorKey

---

tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/Expression.kt
tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/GraphCompiler.java
tools/tungsten/core/src/com/google/android/filament/tungsten/compiler/NodeRegistry.kt
tools/tungsten/core/src/com/google/android/filament/tungsten/model/Nodes.kt
tools/tungsten/core/test/com/google/android/filament/tungsten/compiler/ExpressionTest.kt

The Adder node can now add `float` vectors of different lengths by trimming them to the same dimensionality. We can change this behavior in the future, or introduce different nodes (like a "mix" node) that address differing vector lengths in different ways.

Tungsten: introduce handling for varying dimensionality

---

tools/matc/src/matc/JsonishLexeme.h
tools/matc/src/matc/Lexer.h
tools/matc/src/matc/MaterialCompiler.cpp
tools/matc/src/matc/MaterialCompiler.h
tools/matc/src/matc/MaterialLexeme.h
tools/matc/src/matc/MaterialLexer.cpp
tools/matc/tests/test_lexersAndParsers.cpp

If a comment contained an opening brace { but not the matching
closing one, matc would not count braces properly and not find
the proper end of a vertex/fragment block.
This change also cleans up the code a bit.
Fixes #159

Exclude comments from brace parsing in vertex/fragment blocks

---

tools/cmgen/src/Cubemap.cpp

Fixes a minor error in the spelling of `stitch`, it was spelled as `stich`, in `cmgen`.

Fixes minor error in spelling of stitch

---

CMakeLists.txt
samples/web/CMakeLists.txt
samples/web/filaweb.cpp
samples/web/filaweb.js

This removes the trick of drawing to a 2D canvas. It corrupted the alpha in RGBM images, which caused subtle banding in the Suzanne reflection. Moreover it added complexity to the demo code.
This commit will increase the pre-zipped WASM size by 17k, but I think it's worth it.
This also removes one of the cmgen passes in the WebGL build; we were using PNG instead of RGBM for the skybox to work around the banding issue that this fixes.

WebGL demos now decode PNG in C.

---

build.sh
build/web/build.sh
build/web/ci-common.sh
build/web/common.cfg
build/web/continuous.cfg
build/web/presubmit.cfg
build/web/release.cfg

This is identical to the mac build except that it uses the `/web/` path and it installs the emscripten SDK in `ci-common.sh`

Prep for WebGL on Kokoro.

---

build/web/build.sh

We do not build unit tests for the web build, so we should skip them.

Fix continuous web builds by skipping unit tests.

---

samples/web/filaweb.cpp

In a previous CL today, I changed the skybox to RGBM but forgot to
change the format. Thanks Romain for catching this.

Fix bad skybox color in web demo.

---

CMakeLists.txt
build.sh
filament/CMakeLists.txt
libs/filagui/CMakeLists.txt
samples/CMakeLists.txt
samples/web/CMakeLists.txt

The WebGL build invokes cmgen for samples, which takes several minutes
in debug configuration. Let's use a release build for the host tools,
regardless of the build configuration for the target architecture.

Huge speed up for WebGL debug builds.

---

libs/filagui/src/ImGuiHelper.cpp
samples/web/filaweb.cpp

Unfortunately the trick of passing the address to stdlib "free" causes
a crash in WebGL, so we need to wrap these in lambda.

WebGL samples should pass free callback to BufferDescriptor.

---

filament/src/IndirectLight.cpp
shaders/src/light_indirect.fs

This will be useful for testing and can be
enabled at compile time by setting
IBL_INTEGRATION to IBL_INTEGRATION_IMPORTANCE_SAMPLING
in *both* indirectLight.cpp and light_indirect.fs
BUGS: clearcoat and subsurface won’t
work well when this is enabled since the prefiltered
cubemap is not available and, we don’t evaluate
those lobes with importance sampling (yet).
Additionally, anisotropy can’t work with our
prefiltered importance sampling, so it still uses
the emulation by bending the normal.

importance sampling option for IBL

---

tools/tungsten/core/src/com/google/android/filament/tungsten/texture/TextureUtils.kt

`img.data` returns a copy of the data, so use `raster` instead.

Tungsten: fix, flip components not working

---

CMakeLists.txt
libs/bluevk/src/BlueVKDarwin.cpp
samples/CMakeLists.txt

This looks for VULKAN_SDK at build time, and if present it tells
Filament to use the `libvulkan.1.dylib` that's located there. Otherwise
it falls back to our old loading strategy, which uses a bundled version
of MoltenVK that allows us to avoid requiring installation of the
LunarG SDK.
I tried this out an it works for me...
Closes issue #238.

Allow macOS developers to optionally use an SDK version of Vulkan.

---

docs/Filament.md.html
shaders/src/brdf.fs

mediump computations are not enough for certain roughness values.
This change fixes #241

Fix anisotropy BRDF on mobile

---

tools/cmgen/src/CubemapIBL.cpp

f90=0, which is nonsensical.
We now assume f0=f90=1, meaning the fresnel term
always evaluates to 1.
Thankfully this didn’t impact the prefilter too much.
IBLs MUST BE REGENERATED

When prefiltering the IBL we were wrongly assuming

---

libs/imageio/include/imageio/ImageDecoder.h
libs/imageio/include/imageio/ImageEncoder.h
libs/imageio/src/ImageEncoder.cpp
tools/cmgen/src/cmgen.cpp
tools/mipgen/src/main.cpp

These tools can be used in an asset pipeline; build scripts should not
be required to parse stdout in order to determine success.

cmgen and mipgen should return an error code upon failure.

---

tools/mipgen/src/main.cpp

Sometimes the source image might have a useless 1-bit alpha channel
which our image-processing pipeline expands into a proper alpha channel.
This consumes memory and breaks an assertion in our encoder.
I ran into this while testing mipgen with the Suzanne textures.

Add "strip alpha" feature to mipgen.

---

tools/cmgen/src/CubemapIBL.cpp

It looks like assuming V=1 during prefiltering
yields to better results. This is quite subtle.

Assume V=1 when prefiltering the environement

---

samples/web/CMakeLists.txt
tools/mipgen/src/main.cpp

By using single-component images instead of RGB, we are greatly reducing
the size of KTX files for roughness, metallic, and ambient occlusion.

Add --grayscale option to mipgen.

---

samples/web/filaweb.cpp
samples/web/filaweb.h
samples/web/filaweb.js
samples/web/suzanne.cpp

To determine PNG vs KTX, we were looking at the file extension of the asset name rather than the actual file path (which is a URL).
Also, le singe était trop sombre, so I added a call to setIntensity.

Fix filaweb bug with detecting PNG vs KTX.

---

samples/web/CMakeLists.txt
samples/web/suzanne.cpp
tools/mipgen/src/main.cpp

(1) Suzanne's normal map is actually linear but we were telling GL that it is SRGB, so the shader was not reading (0.5,0.5,1.0) from a perfectly flat normal map.
(2) --linear in mipgen was not honored when consuming PNG files.
(3) The build was not passing --linear to mipgen for the normal map.

Fix three bugs that caused bad normals with Suzanne.

---

samples/web/CMakeLists.txt
samples/web/filaweb.cpp
samples/web/filaweb.h
samples/web/filaweb.js
samples/web/sandbox.cpp
samples/web/sandbox.html
samples/web/suzanne.cpp
samples/web/suzanne.html

Now that cmgen supports KTX without any known bugs, we can finally turn this on. For each envmap/skybox pair, this reduces the number of downloads from 61 files to 3 files. This could go down to 2 if we use KTX metadata, which I'll look into next.

Finally, use KTX for envmaps in WebGL demos.

---

samples/web/sandbox.cpp
samples/web/suzanne.cpp

This is being done simply to maintain the rough alignment between
the light source and the env map. See 09830cd for more information.

Rotate WebGL samples IBL by 180.

---

samples/web/filaweb.cpp
samples/web/filaweb.js
samples/web/sandbox.html
samples/web/suzanne.html

Sometimes you want your KTX file to end in an extension other than
".ktx".  For example, GitHub Pages applies gzip encoding to bmp files
but not to ktx files (which I think is consistent with nginx defaults).
This change makes it so that a deploy script can rename the files and
apply a simple string transformation to the HTML.

Web: allow arbitrary file extensions for KTX files.

---

tools/matc/src/matc/sca/GLSLPostProcessor.cpp

Fixes https://github.com/baldurk/renderdoc/issues/1097
`matc` outputs shaders with invalid SPIR-V instructions (see linked Renderdoc issue):
```
%_runtimearr_float = OpTypeRuntimeArray %float
%_runtimearr_float_0 = OpTypeRuntimeArray %float
%gl_PerVertex = OpTypeStruct %v4float %float %_runtimearr_float %_runtimearr_float_0
```
Not sure if this is just a bug with glslang, incorrect usage on our side, or potentially both. According to [glslang documentation](https://github.com/KhronosGroup/glslang/blob/8751c13ce2cea72974586bf4005737903a7ed539/glslang/Public/ShaderLang.h#L668-L670) when compiling shader programs, we need to be adding them to a `TProgram` and calling `link`. This fixes the issue.

Fix incorrect SPIR-V instructions

---

libs/image/include/image/KtxBundle.h
libs/image/src/KtxBundle.cpp
libs/image/tests/test_image.cpp

The KTX spec allows for arbitrary key-value pairs, we are interested in using this to stash spherical harmonics coefficients.

Add metadata support to KtxBundle.

---

libs/bluevk/CMakeLists.txt
samples/vk_animation.cpp
samples/vk_depthtesting.cpp
samples/vk_hellotriangle.cpp
samples/vk_imgui.cpp
samples/vk_strobecolor.cpp
samples/vk_texturedquad.cpp
samples/vk_vbotest.cpp
samples/vk_viewtest.cpp

* The full `main` signature with `argc` and `argv` arguments must be declared in order for SDL to compile.
* test_bluevk does not compile on Windows

Fix, Vulkan samples not compiling on Windows

---

tools/roughness-prefilter/src/main.cpp

This tool was producing bad output for the monkey roughness map because the monkey roughness map has an (unnecessary) alpha channel, and the tool was assuming that the source image has 3 channels.
This commit fixes that particular case, and changes the tool so that it operates on single-channel data instead of 3-channel data.

Fix / simplify roughness-prefilter.

---

tools/cmgen/src/Cubemap.cpp
tools/cmgen/src/Cubemap.h
tools/cmgen/src/CubemapUtils.cpp
tools/cmgen/src/CubemapUtils.h
tools/cmgen/src/cmgen.cpp

- internal cross storage is now always horizontal
and seamless.
- source cross images are now always converted to
internal format, conversion includes rescaling
and sampling if scaling down.
- vertical cross is supported again
- fixes #283

better cross conversion. Fix #283.

---

shaders/src/shadowing.fs

because the shadow map can be “focused”, its
texture coordinates can end-up very large, which
in turn can cause overflows in the calculation of
the PCF positions. Unfortunately some GPUs
abort in that situation, which causes artifacts.
Fix Bug 111455153

clamp .st when reading shadow map to avoid overflow

---

tools/cmgen/src/Cubemap.cpp
tools/cmgen/src/CubemapUtils.cpp

We now handle all face corners correctly and
follow the OpenGL recommandation of averaging the
corners of all 3 adjacent faces.

improve cubemap bilinear sampling

---

tools/cmgen/src/Cubemap.cpp
tools/cmgen/src/CubemapUtils.cpp
tools/cmgen/src/CubemapUtils.h
tools/cmgen/src/cmgen.cpp

this adds a new --type (-t) parameter that is
used to specify cmgen’s output.
faces: outputs cube maps separate faces (default
and current behavior)
equirect: outputs an equirectangular image
ktx: outputs a ktx file
--format=ktx now implies —type=ktx

Equirectangular export support

---

libs/imageio/include/imageio/BlockCompression.h
libs/imageio/src/BlockCompression.cpp
third_party/astcenc/Source/astc_image_load_store.cpp
third_party/astcenc/tnt/CMakeLists.txt
third_party/astcenc/tnt/README
tools/mipgen/CMakeLists.txt
tools/mipgen/src/main.cpp

The compression API now takes block size instead of bit rate. Otherwise it is quite possible for the encoder to generate a block size that is not one of the valid block sizes that graphics API's can actually consume.

Add compression to mipgen and change bitrate to block size.

---

tools/cmgen/src/CubemapUtils.cpp
tools/cmgen/src/CubemapUtils.h
tools/cmgen/src/cmgen.cpp

Octahedron output support for cmgen. use —type=octahedron.
This is still fairly experimental.

experimental: add octahedron output support

---

filament/src/driver/opengl/OpenGLDriver.cpp
libs/image/include/image/KtxBundle.h
libs/imageio/CMakeLists.txt
libs/imageio/include/imageio/BlockCompression.h
libs/imageio/src/BlockCompression.cpp
samples/web/CMakeLists.txt
samples/web/filaweb.cpp
samples/web/filaweb.h
samples/web/filaweb.js
samples/web/suzanne.cpp
samples/web/suzanne.html
tools/mipgen/CMakeLists.txt
tools/mipgen/src/main.cpp

At build time, mipgen now creates several compressed and non-compressed variants for albedo.
For ASTC we use the ARM encoder, for S3TC we use the STB encoder. These are somewhat limited so we may wish to investigate other libraries in the future (e.g., AMD Compressenator).
At run time, we detect which of these variants to download, based on available WebGL extensions. In practice, this means that desktop browsers will use the S3TC variant and mobile browsers will use the ASTC variant.
The before/after screenshots below show Suzanne with all textures removed except albedo.  The developer pane shows that unzipped albedo went from ~4 MB to 682 KB using S3TC.
Mobile support (ASTC and ETC2) is coming in a future PR, stay tuned.

Add S3TC support to imageio and Suzanne.

---

filament/src/driver/opengl/GLUtils.h
libs/filabridge/include/filament/driver/DriverEnums.h
libs/image/include/image/KtxBundle.h
samples/web/filaweb.cpp
samples/web/filaweb.js
samples/web/suzanne.html

This reduces the unzipped albedo from 4 MB to 1.3 MB as seen in the attached before / after shots.

Add ASTC support to Suzanne.

---

filament/include/filament/driver/PixelBufferDescriptor.h
filament/src/driver/opengl/GLUtils.h
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/opengl/OpenGLDriver.h
filament/src/driver/opengl/gl_headers.cpp
filament/src/driver/opengl/gl_headers.h
libs/filabridge/include/filament/driver/DriverEnums.h

Fixes #309
- remove some currently unused code that requires
GLES 3.1 headers. It’s not technically a problem,
but it makes the code less confusing. We can
put that back, when we need it.
- Turn off multi-sampling on GLES 3.0
- Add support for EXT_multisampled_render_to_texture

Don’t use GLES 3.1 features on GLES 3.0 contextes

---

libs/image/include/image/KtxBundle.h
libs/imageio/include/imageio/BlockCompression.h
libs/imageio/src/BlockCompression.cpp
samples/web/CMakeLists.txt
samples/web/filaweb.cpp
samples/web/filaweb.js
samples/web/suzanne.cpp
samples/web/suzanne.html
tools/mipgen/src/main.cpp

This shrinks file size as follows, although it seems to darken the rendered result.
```
1398209 Oct  2 16:22 ao.ktx
699172 Oct  2 16:20 ao_etc.ktx
1398209 Oct  2 16:22 metallic.ktx
699172 Oct  2 16:19 metallic_etc.ktx
1398209 Oct  2 16:22 roughness.ktx
699172 Oct  2 16:20 roughness_etc.ktx
```

Add ETC support to mipgen / imageio / suzanne.

---

libs/imageio/src/BlockCompression.cpp
samples/web/CMakeLists.txt
samples/web/suzanne.html
tools/mipgen/src/main.cpp

Due to an assertion in etc2comp, this unfortunately uses RGB8 instead of RG11 but it still helps quite a bit (3.3 MB savings in the unzipped KTX size).
Before / After screenshots below.

Enable ETC for Suzanne normal map.

---

libs/utils/src/Path.cpp

Concating with an empty path should not prepend a slash since doing so implies that the user wants to access the system's root folder.
Fixes #332

Fix utils::Path concat for relative paths.

---

libs/image/include/image/ImageOps.h
libs/image/src/ImageOps.cpp
tools/mipgen/src/main.cpp

When using GAUSSIAN_NORMALS, image::resampleImage automatically unitizes
its output. This means that clients (e.g. mipgen) need to ensure that
the source image is in [-1,+1] rather than [0,+1].

mipgen: fix dark miplevels in normal maps.

---

android/filament-android/src/main/cpp/Texture.cpp
android/filament-android/src/main/java/com/google/android/filament/Texture.java
android/samples/image-based-lighting/app/src/main/java/com/google/android/filament/ibl/IblLoader.kt
filament/include/filament/Texture.h
filament/src/Engine.cpp
filament/src/IndirectLight.cpp
filament/src/Skybox.cpp
filament/src/Texture.cpp
filament/src/details/Engine.h
filament/src/details/Skybox.h
filament/src/details/Texture.h
libs/filabridge/include/filament/driver/DriverEnums.h
samples/app/IBL.cpp
samples/web/filaweb.cpp
tools/tungsten/core/src/com/google/android/filament/tungsten/ui/preview/Ibl.kt

This change will allow the skybox use a compressed texture format.
For now, the old internal format "RGBM" is still honored, but in a forthcoming change we will replace the enum with UNUSED.

NEW API: add RGBM flag to Texture.

---

tools/cmgen/src/cmgen.cpp

Okay I think I fixed the history problems - sorry about the hassle.

remove another instance of `using namespace std`

---

android/filament-android/src/main/java/com/google/android/filament/Renderer.java
filament/include/filament/Renderer.h
filament/src/Renderer.cpp

Adds a clear flag to the mirror frame call which clears the entire surface to black before mirroring in the current view.  Also exposes maxViewportDimensions through the driver API so that the full viewport dimensions can be used for the clear.

Add CLEAR flag to mirrorFrame

---

shaders/src/shading_lit.fs

When the clear coat layer uses a high roughness, the base layer should not be perceived as glossy. The screenshot below shows the problem (no dynamic light, only an IBL):
In this screenshot, the base layer is a glossy black dielectric and the clear coat layer uses the max roughness. You can see how glossy reflections appear at grazing angle. With a rough clear coat layer, light should be diffuse and it shouldn't be possible to see glossy reflections from the base layer.
We simulate the diffusion effect by making sure the base layer is never glossier than the clear coat layer. It's incorrect but better than nothing. Here is the same scene with the fix:

Ensure the base layer is never glossier than the clear coat layer

---

libs/imageio/src/BlockCompression.cpp

also a redundant 'using namespace image'

Remove 'using std::string' from BlockCompression

---

android/filament-android/src/main/java/com/google/android/filament/Texture.java
filament/src/IndirectLight.cpp
filament/src/Skybox.cpp
filament/src/Texture.cpp
filament/src/driver/CommandStream.cpp
filament/src/driver/Driver.cpp
filament/src/driver/opengl/GLUtils.h
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/vulkan/VulkanDriverImpl.cpp
libs/filabridge/include/filament/driver/DriverEnums.h

Clients should use the new `rgbm` builder flag instead, which allows the skybox and IBL to use compressed textures.
Sceneform needs to be updated, and we have a tentative CL for that.

API CHANGE: remove deprecated RGBM enum.

---

samples/web/CMakeLists.txt
samples/web/filaweb.cpp
samples/web/filaweb.js

The web build now invokes cmgen three times for each IBL: uncompressed, S3TC (desktop), and ETC (mobile). Alternatively, we could enhance cmgen to accept multiple compression strings, but per discussion with Mathias we decided to keep it simple.
I decided not to use compression for the skybox in our web demos because the quality is too poor (see PR image). I did not try playing with compression settings, might be worth revisiting in the future.

Filaweb now uses compression for the IBL.

---

filament/src/driver/opengl/OpenGLDriver.cpp

Recent changes to UBO management introduce the possibility of calling glBufferSubData on zero-length regions, which cause a cascade of `GL_INVALID_OPERATION` with the Suzanne WebGL demo. Note that the WebGL variant of BufferSubData has special behavior when length = 0.
This also seems like a potentially useful optimization for non-web platforms, since a CPU branch is likely cheaper than a GL entry point.

OpenGL Backend fix for INVALID_OPERATION regression.

---

samples/web/CMakeLists.txt
samples/web/filaweb.cpp

Every texture now uses KTX, so there is no need to fatten the WASM with
a PNG decoder.

Remove STB from web samples.

---

CMakeLists.txt
libs/filamentjs/CMakeLists.txt
libs/filamentjs/jsbindings.cpp
libs/filamentjs/wasmloader.js

This adds filamentjs to libs, which builds a Filament-only WASM file. Unlike our existing web demos, this WASM file contains no application code.
These bindings are by no means complete, but they are sufficient for a "hello triangle" demo that I have working locally. Sneak peak of the Triangle JS app code is available in a [gist](https://gist.github.com/prideout/e9d6dd0e312146c8a287d2d109affa4d).
This commit merely adds the bindings to the build. Demos and docs are forthcoming.

Introduce JavaScript API using embind.

---

build.sh

The web archive now has two subfolders: public and filamentjs.
- public contains the three C++ based web demos.
- jsbindings contains the new JS bindings and Filament-only WASM module.

Add filamentjs to web release archive.

---

libs/filamentjs/docs/Pipfile
libs/filamentjs/docs/build.py
libs/filamentjs/docs/tutorial_template.html
libs/filamentjs/docs/tutorial_triangle.md

This commit contains a markdown file for a "hello triangle" tutorial as well as a Python script that does two things:
1) Extracts JavaScript code blocks from the markdown to generate the code for the demo.
2) Converts the markdown into a nicely-rendered web page.
After we invoke the Python script for the first time, it will create a set of files in the root docs folder, which will automatically be published via GitHub Pages to the following URL.
https://google.github.io/filament/webgl
This gives us an official place to host the latest web demos and tutorials.
The tutorial can be previewed [here](https://prideout.net/prototype/webgl/tutorial_triangle.html). More JavaScript tutorials are forthcoming.

Add literate JavaScript tutorial and Python tangler.

---

filament/include/filament/Stream.h
filament/include/filament/driver/Platform.h
filament/src/Renderer.cpp
filament/src/Stream.cpp
filament/src/details/Stream.h
filament/src/driver/DriverAPI.inc
filament/src/driver/android/ExternalStreamManagerAndroid.cpp
filament/src/driver/android/ExternalStreamManagerAndroid.h
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/opengl/OpenGLDriver.h
filament/src/driver/opengl/PlatformCocoaGL.h
filament/src/driver/opengl/PlatformDummyGL.h
filament/src/driver/opengl/PlatformEGL.cpp
filament/src/driver/opengl/PlatformEGL.h
filament/src/driver/opengl/PlatformGLX.h
filament/src/driver/opengl/PlatformWGL.h
filament/src/driver/opengl/PlatformWebGL.h
filament/src/driver/vulkan/VulkanDriver.cpp

this returns a timestamp in nanosecond corresponding
to the desired presentation time of the latest frame
bound to a filament texture.

implemented Stream::getTimestamp()

---

filament/src/Scene.cpp
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
filament/test/filament_test.cpp
shaders/src/main.vs

This is achieved by pre-scaling the normals 
transform so that the resulting normal doesn't have
any large component allowing to do the normalize()
in the fragment shader in mediump.
This must be done for skinning too.

Avoid a normalize() in the vertex shader

---

libs/filamentjs/docs/tutorial_redball.md
libs/filamentjs/docs/tutorial_triangle.md
libs/filamentjs/jsbindings.cpp
libs/filamentjs/tests/testwasm.js
libs/filamentjs/utilities.js

This cleans up the redball tutorial and sneaks in some camera animation. More importantly, this PR  adds the following features to the JS bindings:
- One-line `render` method
- createTextureFromKtx
- createIblFromKtx

Add JavaScript utility functions to reduce boilerplate.

---

libs/filamentjs/docs/build.py
libs/filamentjs/docs/main.css
libs/filamentjs/docs/tutorial_redball.md

This simply overlays an `<a>` that jumps to the src page of the `<iframe>`.

 Add fullscreen button to embedded JS demos.

---

filament/src/details/Engine.h
shaders/src/post_process.fs

Fixes #397.
Before / after comparison:

Fix FXAA pixel alignment.

---

libs/filamentjs/docs/build.py
libs/filamentjs/docs/ref_template.html
libs/filamentjs/jsbindings.cpp
libs/filamentjs/jsenums.cpp
libs/filamentjs/utilities.js
libs/filamentjs/wasmloader.js

The JS docgen script now looks for /// comments in the binding definitions, and generates markdown from those. The reference page has three sections: classes, free functions, and enums.

Introduce JavaScript API reference.

---

libs/filamentjs/docs/tutorial_redball.md
libs/filamentjs/tests/testwasm.js
libs/filamentjs/utilities.js
libs/filamentjs/wasmloader.js

We still do not require our JS users to use the glMatrix library, but we might as well simplify things when they do.

JS users no longer need to call loadMathExtensions()

---

libs/filamentjs/docs/tutorial_redball.md
libs/filamentjs/utilities.js

We were not normalizing one of the orthonormal basis vectors, causing the visual aberration reported in #423.  (As a somewhat unrelated change, I also changed the arbitrary bitangent such that the discontinuity is at the Y+ pole where it is often less visible.)
Before / After screenshots below.
This CL also add a "back light" to the redball demo to lighten up the dark area in the IBL.
Fixes #423

Fix the JS IcoSphere tangents.

---

libs/filamentjs/CMakeLists.txt
libs/filamentjs/docs/build.py
libs/filamentjs/docs/tutorial_redball.md
libs/filamentjs/docs/tutorial_triangle.md
libs/filamentjs/extensions.js
libs/filamentjs/jsbindings.cpp
libs/filamentjs/tests/test_parquet.js
libs/filamentjs/utilities.js
libs/filamentjs/wasmloader.js

This makes our createTexture* helpers more consistent with the createMaterial helper, and extends the wrapped Engine class with new methods.
Before, clients did something like this:
const ao = Filament.createTextureFromPng(Filament.assets['foo.png'], engine);
...
engine.destroyTexture(ao);
Now, they can do:
const ao = engine.createTextureFromPng('foo.png');
...
engine.destroyTexture(ao);
This is more symmetric and concise. In general the JS API now supports a class of "buffer-like" objects which exploit dynamic typing in order to accept any of the following: BufferDescriptor, asset string, or Uint8Array.

JavaScript: concise texture creation functions

---

filament/src/Froxelizer.cpp
libs/utils/include/utils/JobSystem.h
libs/utils/include/utils/architecture.h

We used to assume 32-bytes cache lines when running on ARM 32-bit mode,
however, that was wrong because 32-bit mode doesn't change the cpu's
cache line. On all modern platforms we support, the cache line
is 64 bytes.
Set Job storage to 48 bytes on all platforms.

Set cache size to 64 bytes on all platforms

---

libs/utils/include/utils/Allocator.h
libs/utils/include/utils/JobSystem.h

Instead of returning nullptr, the pool allocator returned an
invalid pointer.

Fix a crasher when allocating the last Job

---

filament/src/driver/vulkan/VulkanSamplerCache.cpp

Noticed this when working on the Metal backend. Anisotropy is provided as a logarithmic value, so we should bit-shift to get the correct value, as the [OpenGL driver does](https://github.com/google/filament/blob/master/filament/src/driver/opengl/OpenGLDriver.cpp#L2469).

Fix max anisotropy in Vulkan backend

---

README.md

I don't think it's useful to indent the entire tree, so this removes
the redundant root. More importantly, it adds the "web" folder. :)

Update "Directory structure" in toplevel README.

---

web/docs/tutorial_triangle.md
web/filament-js/extensions.js
web/filament-js/jsbindings.cpp
web/filament-js/utilities.js
web/samples/leaks.html
web/samples/parquet.html
web/samples/suzanne.html
web/samples/triangle.html

The new `build()` wrapper solves the builder leak, it does not solve the tiny leak incurred when users call `getInstance` on a component manager without calling embind's `delete` method afterwards. Since there's no way to auto-delete component instances, this CL fixes up our sample code and docstrings.
Fixes #429

Fix JS API leaks by auto-deleting builders, etc.

---

filament/src/View.cpp
filament/src/details/View.h
shaders/src/depth_main.vs
shaders/src/main.vs

Recall that Vulkan has a right-handed NDC system. Currently, our Vulkan
backend is not handling VERTEX_DOMAIN_DEVICE correctly, but we didn't
notice because the culling mode is not honored yet (a separate PR is on
the way for that).
To fix this, we considered adding a shader-based fixup only for the
device domain and keeping our Vulkanish projection matrix as-is.
However, this would cause the skybox shader to compute an incorrect
wrong eye vector due to in the inconsistent definition of clip space.
After discussion with Mathias and Ben, we decided that the most elegant
fix is for Filament to have only one canonical clip space, which for
now is the clip space that OpenGL requires.
Ben pointed out that spirv-cross has a flag for injecting shader-based
fixups. However we don't invoke …

Handle Vulkan ClipSpace in GLSL rather than C++.

---

libs/filaflat/src/TextDictionaryReader.cpp

This fixes the "shader is not ASCII" error seen with GL backend, introduced when we changed blob ownership semantics to accommodate shader compression. It was due to missing null terminators.
We actually never bothered including the trailing null in blob length, which was wrong but happened to work because the BlobDictionary held a weak reference to chunk data. SInce it now holds an actual copy, the lack of null caused our strings to contain garbage memory.

Fix regression with non-Vulkan backends.

---

samples/CMakeLists.txt
samples/app/MeshAssimp.cpp
samples/app/MeshAssimp.h

This caused regressions with some of our samples like vk_hellopbr:
- For the new 1x1 textures, RGB isn't accepted by Vulkan and Metal.
Currently these platforms require RGBA, although we plan on adding
reshaping functionality for the future.
- Too many texture samplers in a single shader, this causes a run time
error. This could be alleviated by creating an atlas.
- vk_hellopbr assumes that all materials have a "metallic" param.
Going forward, we plan on creating a new library that avoids MeshAssimp,
so for now let's just disable gltf_viewer.

Roll back MeshAssimp enhancements for now.

---

CMakeLists.txt
third_party/spirv-cross/tnt/CMakeLists.txt
third_party/spirv-cross/tnt/README.md
third_party/spirv-tools/CMakeLists.txt

This change enables `filamat` to compile for all platforms, both desktop and non-desktop. Specifically, web and Android were having issues with Spir-V cross, which by default uses exceptions.

Compile filamat and dependencies for all platforms

---

libs/filabridge/include/filament/EngineEnums.h

In practice this limits materials to 10 samplers since Filament uses 5
for lights and skips 1 slot for the post-process sampler. This can
probably be optimized.

Raise sampler limit to 16.

---

filament/test/filament_benchmark.cpp
libs/math/include/math/fast.h

fast::pow(x, 2.2f) is about 100x faster than std::pow.
std::pow(x, 2.2f) takes roughly 1000 cycles.

a fast approximation of pow() and pow(x, 2.2f)

---

docs/Filament.md.html

The new formula should be the correct one according to this document (first line p86): https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf

Corrected exposure from ev100 formula

---

docs/Filament.md.html

It looks like there is a minus sign missing in there, see https://www.wolframalpha.com/input/?i=(((1%2Bsqrt(x))+%2F+(1+-+sqrt(x)))+-+1.5)+%2F+(((1%2Bsqrt(x))+%2F+(1+-+sqrt(x)))+%2B+1.5)
I'm not sure what the code does though https://github.com/google/filament/blob/master/shaders/src/brdf.fs#L282

Corrected typo in formula

---

libs/math/include/math/TQuatHelpers.h
libs/math/include/math/TVecHelpers.h
libs/math/include/math/compiler.h
libs/math/include/math/half.h
libs/math/include/math/mat2.h
libs/math/include/math/mat3.h
libs/math/include/math/mat4.h
libs/math/include/math/quat.h
libs/utils/include/utils/Allocator.h
libs/utils/include/utils/compiler.h

Relates to #522 and #517 and serves mostly as a basis for discussion.
Summary of changes:
- Introduced constexpr in places where MSVC complained about missing constexpr
- Removed constexpr from functions that directly or transitively called std::sqrt (since it's not constexpr)
- Some places needed `static_cast` when templates were instantiated with T=float and A=int (i.e. `math::float3(1)`), because MSVC will emit a warning for implicit conversions from int to float.
- Moved some leftover compiler defines into compiler.h, and added dummy defines for MSVC (PURE -> MATH_PURE, MAKE_CONSTEXPR)
- Moved #pragma nounroll into a new define MATH_NOUNROLL using _Pragma("nounroll") to replace the original #pragma (which can't go into a #define itself)
- This also has the "fix" for the Allocator …

Fixes various MSVC issues in public headers

---

libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/include/filamat/PostprocessMaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
tools/matc/src/matc/Config.h
tools/matc/src/matc/MaterialCompiler.cpp
tools/matc/src/matc/PostprocessMaterialCompiler.cpp

Deprecate the `codeGenTargetApi` method on `MaterialBuilder`, as it is confusing and not useful to clients. Clients should only care about setting `targetApi` correctly.
Tested before and after change with all optimization, platform, and API combinations on all materials inside `samples/materials`.

Remove codeGenTargetApi builder method from MaterialBuilder

---

libs/filamat/CMakeLists.txt
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/PostprocessMaterialBuilder.cpp
libs/filamat/src/eiff/DictionaryTextChunk.cpp
libs/filamat/src/eiff/DictionaryTextChunk.h
libs/filamat/src/eiff/MaterialTextChunk.cpp
libs/filamat/src/eiff/MaterialTextChunk.h
libs/filamat/src/eiff/ShaderEntry.h
libs/filamat/src/eiff/TextChunk.h

This PR is in preparation for adding the Metal shading language to Filament's material blobs.
Metal shaders will be stored in material blobs in the Metal Shading Language (MSL) which, like GLSL, is an ASCII-based text format.
Because of this, we can reuse a lot of the GLSL logic with name changes for clarity.
1. The first commit renames GLSL-specific chunk files into a more generic "Text" nomenclature:
```
DictionaryGlslChunk.cpp => DictionaryTextChunk.cpp
DictionaryGlslChunk.h   => DictionaryTextChunk.h
MaterialGlslChunk.cpp   => MaterialTextChunk.cpp
MaterialGlslChunk.h     => MaterialTextChunk.h
GlslChunk.h             => TextChunk.h
```
2. The second commit makes `MaterialTextChunk` and `DictionaryTextChunk` more generic, removing from their implementations the hard-coded GLSL …

Rename GlslChunk to TextChunk

---

filament/include/filament/Box.h

I missed another compilation error in Box.h for MSVC:
In this particular case, MSVC does not implicitly convert 0.5f to a float3 here, so my suggested fix is to make it explicit (just here in the public header).
I guess it'd be nicer to figure out why exactly the implicit conversion is not occurring, but this likely requires very intensive digging.

[MSVC] Fix for unsupported implicit conversion to float3

---

libs/utils/include/utils/Allocator.h

I believe this fixes #524, given the following rationale:
The assert on `next` should not occur before `compare_exchange_weak` succeeds, because only that indicates the absence of a race condition.
Between the atomic load of `mHead` and `storage[currentHead.offset].next`, another thread might have already returned the storage pointed at by mHead to a caller, which could have overwritten the memory with it's own data (hence making it moot to assert anything about the value of `next`).
It would also be nice if someone could check if the comments I added are actually correct.
After making this change, I tested both my app and the material_sandbox with 100 monkeys, and both didn't crash anymore.

Fixes assertion failure in AtomicFreeList used by Job System Allocator

---

filament/src/Material.cpp
filament/src/RenderPass.cpp
filament/src/details/Material.h

FADE is just a variant of TRANSPARENT that only affects shading.
This change introduces the "render blending mode" which is the
blending mode that must be used when generating the render keys.

Sort FADE materials with TRANSPARENT materials

---

filament/CMakeLists.txt
filament/src/driver/CommandStream.h
filament/src/driver/CommandStreamDispatcher.h
filament/src/driver/noop/NoopDriver.cpp
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/vulkan/VulkanDriver.cpp

systrace can now be enabled in the CommandStream's Dispatcher, which
allows it to work with all backends.

split CommandStream.h and add systrace option

---

CMakeLists.txt
filament/CMakeLists.txt

By providing a function in our top-level CMakeLists, we can make it easier to use resgen in multiple projects (e.g., for samples or MeshAssimp).
Also removed an redundant edge in the dependency graph.

Refactor resgen functionality in CMake.

---

libs/utils/include/utils/Allocator.h

An assert checking invariants would sometime trigger, the problem
was a logic error that would be exposed by a race when running out
of space in the list.
The root of the problem is that in one place we were not remapping the 
-1 offset to nullptr, storing a pointer violating our invariants.
Also added more asserts!!!
Fixes #524

Fix another bug in AtomicFreeList

---

libs/filamat/src/sca/GLSLTools.cpp

`matc` crashes when encountering the following material function:
```
fragment {
void material(inout MaterialInputs material) {
}
}
```
```
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: vector
```
This fixes the crash and lets matc exit gracefully, albeit with an error code.

Fix matc crash for empty material function

---

build/common/test_list.txt
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/sca/GLSLTools.cpp
libs/filamat/src/sca/GLSLTools.h
libs/filamat/tests/test_filamat.cpp
samples/sample_cloth.cpp
samples/sample_full_pbr.cpp
samples/sample_normal_map.cpp
samples/sample_opacity_mask.cpp
samples/sample_pbr.cpp
samples/sample_position_offset.cpp
samples/sample_subsurface.cpp
tools/matc/src/matc/ParametersProcessor.cpp

The `set()` method is no longer needed on `MaterialBuilder`, as static code analysis will be performed automatically. Likewise, this PR deprecates the "defines" field on material definitions, which is no longer useful to clients.

Deprecate set method on MaterialBuilder

---

samples/CMakeLists.txt
samples/vk_hellopbr.cpp

This shows how resgen can be used for mesh data. It also removes the MeshAssimp dependency from samples that were meant to be small and self-contained.

Remove assimp usage from some sample apps.

---

libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/sca/ASTHelpers.cpp
libs/filamat/src/sca/GLSLTools.cpp
libs/utils/include/utils/Log.h

Use `utils::slog` instead of `iostream` in `filamat`.
`matc` Binary size difference:
```
Before: 5790796
After:  5786756
===============
Diff:      4040
```

Remove use of iostream in filamat

---

libs/image/include/image/KtxUtility.h
web/filament-js/jsbindings.cpp

This makes it easier for C++ clients to use KTX files and simplifies the JavaScript bindings.

KtxUtility improvements.

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/Renderer.cpp
filament/src/View.cpp
filament/src/details/Renderer.h
filament/src/details/View.h

View::setRenderQuality gives the ability to control the rendering quality
of a given view. In particular this allows the app to lower the quality
of the HDR color buffer by using R11G11B10F instead of RGB(A)16F.

Add RenderQuality API

---

build.sh

build.sh -p all builds everything which may be too much. -p now
accepts a list of platforms. For instance to build Android and
desktop:
./build.sh -p android,desktop release

Add the ability to build several platforms, but not all

---

libs/image/include/image/KtxUtility.h
samples/CMakeLists.txt
samples/app/IBL.cpp
samples/app/IBL.h

We already have several KTX environments in the repo, so you can clone a fresh tree and do:
gltf_viewer --ibl={FILAMENT}/docs/webgl/pillars_2k DamagedHelmet.gltf
This results in the screenshot below.
Note that we have several hundred files in `samples/envs`, we should consider replacing those or copying the environments from `docs/webgl` (which git would internally de-dup, due to content hashing).

FilamentApp can now use KTX environments.

---

libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/include/filamat/PostprocessMaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/PostprocessMaterialBuilder.cpp
libs/filamat/src/sca/GLSLTools.h

Deprecate the `postprocessor` method of `MaterialBuilder`, which isn't needed by clients anymore.

Deprecate MaterialBuilder::postprocessor

---

libs/filamat/tests/test_filamat.cpp
shaders/src/variables.fs
shaders/src/variables.vs

Compiling materials with both `uv0` and `uv1` attributes fail:
```
material {
name : Test,
requires : [
uv0,
uv1
],
shadingModel : unlit,
}
fragment {
void material(inout MaterialInputs material) {
prepareMaterial(material);
}
}
```
```
ERROR: 0:383: 'zw' : vector swizzle selection out of range
ERROR: 0:383: '' : missing #endif
ERROR: 0:383: '' : compilation terminated
ERROR: 3 compilation errors.  No code generated.
```
The fix is to use a `vec2` for the `vertex_uv01` attribute when **only** `uv0` coords are requested.

Fix use of UV0 and UV1 coordinates

---

libs/filameshio/CMakeLists.txt
libs/filameshio/include/filameshio/filamesh.h
libs/filameshio/src/MeshIO.cpp
samples/CMakeLists.txt
tools/filamesh/CMakeLists.txt
tools/filamesh/README.md
tools/filamesh/src/MeshWriter.cpp
tools/filamesh/src/MeshWriter.h
tools/filamesh/src/main.cpp
web/docs/tutorial_suzanne.md
web/samples/CMakeLists.txt

Note that the WebGL build uses filameshio, but Android does not. Our
Android samples therefore do not yet understand the compressed format.
For web, I measured the before / after:
```
BEFORE: filament.wasm = 505796, suzanne.filamesh = 521476
AFTER: filament.wasm = 510915, suzanne.filamesh = 333489
```

filamesh: Add support for COMPRESSION

---

docs/webgl/reference.html
libs/filameshio/CMakeLists.txt
libs/filameshio/include/filameshio/MeshReader.h
libs/filameshio/include/filameshio/filamesh.h
libs/filameshio/src/MeshIO.cpp
libs/filameshio/src/MeshReader.cpp
libs/filameshio/tests/test_filamesh.cpp
samples/sample_cloth.cpp
samples/sample_normal_map.cpp
samples/vk_hellopbr.cpp
tools/filamesh/src/MeshWriter.cpp
tools/filamesh/src/MeshWriter.h
web/filament-js/extensions.js
web/filament-js/jsbindings.cpp
web/filament-js/utilities.js

- The first commit reduces compressed suzanne from 333489 bytes to 272761.
- The second commit renames the MeshIO class to `MeshReader` to make it symmetric with `MeshWriter`.

 filamesh: Compress attributes individually.

---

libs/image/CMakeLists.txt

This allows client to properly make use of the (very useful!) KTX texture loading, when using the libraries from an installed location.

Install the image library

---

web/filament-js/extensions.js
web/filament-js/filament.d.ts
web/filament-js/utilities.js
web/filament-js/wasmloader.js

This restores the canvas-based decoding method that was removed in #214,
but only for JPEG images. We continue to decode PNG images in C because
canvas-decoding mucks with alpha and prevents us from reading 16-bit
PNG.

Support JPEG textures in the JS API.

---

CMakeLists.txt

This adds a new CMake option that allows the user to set whether they want the static or shared visual studio runtime to be linked against filament.
The previous behavior was to use the shared runtime for debug builds and the static runtime for release builds without a way to switch.
After this change, it will use the static runtime for both release and debug builds by default, but offers an option to switch to the shared runtime for both.

Add a CMake option to use the shared CRT on Windows

---

filament/src/UniformBuffer.h
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h

- use the exact required size for bone data instead of always the max
of 256 bones. This also reduces the amount of data to update and
copy into the command stream.
- also get rid of the "reuse component" optimization, which is less
needed now that renderables don't have their own transform UBO.

improve skinning memory usage and udpates

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/View.cpp
filament/src/details/View.h
filament/src/driver/Driver.h
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/opengl/OpenGLDriver.h
filament/src/driver/vulkan/VulkanBinder.cpp
filament/src/driver/vulkan/VulkanDriver.cpp
filament/src/driver/vulkan/VulkanDriverImpl.cpp
filament/src/driver/vulkan/VulkanDriverImpl.h
filament/src/materials/skybox.mat
filament/src/materials/skyboxRGBM.mat

This API can be used to flip all meshes in a render pass
inside out. This is useful for mirrored rendering.
This change also disables face culling on the default skybox
renderable. Since it is unlit, there is no downside to this
and the mesh being in the device vertex domain it can never
be backfacing unless front face winding is inverted.
Example:

Add View::setFrontFaceWindingInverted() API

---

libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/GLSLPostProcessor.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/PostprocessMaterialBuilder.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.h
tools/matc/src/matc/MaterialCompiler.cpp
tools/matc/src/matc/ParametersProcessor.cpp

Because external samplers are not properly supported by SPIRV and
associated library (spirv-cross and spirv-tools) we currently disable
all optimizations when we encounter a material with external samplers.
This however causes issues on some misbehaved drivers (not running
the optimizations has a side effect which causes a crash). To enable
the optimization pass we simply rely on the Vulkan codegen target to
substitute samplerExternal with sampler2D. We then analyze the output
GLSL (post-optimization) and revert the relevants sampler2D declarations
to samplerExternal declarations.
This fixup only occurs after optimization and for mobile targets and
if external samplers were declared.

Enable optimization passes on materials with external samplers

---

libs/image/include/image/ColorTransform.h
libs/image/include/image/ImageOps.h
libs/image/src/ImageOps.cpp
tools/mipgen/src/main.cpp

This is useful because our Vulkan backend currently does not accept
3-band texture data. (although we intend to fix that soon)

mipgen: support generation of 4-band KTX files

---

libs/utils/src/JobSystem.cpp

We used to only wake up a job-queue if there was already some jobs
running, the idea was that the current thread would handle the new job
as soon as calling wait(). However, there is no guarantee that wait() 
will be called anytime soon.
cv.signal() is not very expensive on Android/Linux, as we're using
a custom implementation.

Always wake up a job queue when a job is ran

---

filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h

I was trying to fill out all 256 bone matrices in an attempt to debug a model issue I had when I noticed this actually causes a crash.
The reason is the silent downcast of the bone count to uint8_t, which overflows to 0. That makes it impossible to set any bone matrices afterwards.
p.s.: uint16_t would have been sufficient here but since the entire public API surface uses size_t for the bone count, I opted to use it here as well. It doesn't seem like this struct will be allocated terribly often so it shouldn't have a noticeable memory impact.

Fixes an overflow issue when exactly 256 bones are used

---

android/build/filament-tasks.gradle
android/samples/hello-triangle/app/src/main/materials/baked_color.mat
android/samples/lit-cube/app/src/main/materials/lit.mat
docs/Materials.md.html
docs/webgl/tutorial_redball.html
docs/webgl/tutorial_suzanne.html
filament/CMakeLists.txt
libs/filagui/CMakeLists.txt
libs/filamat/include/filamat/MaterialBuilder.h
samples/CMakeLists.txt
tools/matc/src/matc/CommandlineConfig.cpp
tools/matc/src/matc/Config.h
web/docs/build.py
web/docs/tutorial_redball.md
web/docs/tutorial_suzanne.md
web/samples/CMakeLists.txt

Release builds of Filament only work well with optimize shaders,
turning optimizations on by default will help avoid mismatches.
This change also adds -g to disable all optimizations, for debug
builds.
This PR fixes #606

Turn on shaders optimization by default

---

filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/opengl/OpenGLDriver.h
libs/utils/include/utils/Profiler.h
libs/utils/src/Profiler.cpp

- make Profiler::readCounters() not inline as it didn't need to be, 
it's not performance critical and it's sufficiently large.
- don't inline hasExtensions(), same reason.

code size optimizations

---

filament/src/DebugRegistry.cpp
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/vulkan/VulkanDriver.cpp
libs/filabridge/include/private/filament/SamplerInterfaceBlock.h
libs/filabridge/include/private/filament/UniformInterfaceBlock.h
libs/image/src/ImageSampler.cpp
libs/utils/include/utils/CString.h
libs/utils/test/test_CString.cpp

In a lot of case the StaticString hash can be computed a compile time,
so we now take advantage of that.
Removed StaticString(const char*) ctor, and replaced it with a
StaticString::make() method.
Fixed a couple wrong uses of the old StaticString(const char*) ctor.

Improve StaticString hashing

---

filament/src/View.cpp
libs/utils/include/utils/JobSystem.h
libs/utils/src/JobSystem.cpp

JobSystem::waitAndRelease used to spin to wait for the job to finish,
usually this wasn't a problem because the spinning thread was
able to handle other jobs. However, in cases where no job was
available it would actually spin in burn cpu cycles.
we now use a (separate) condition variable to handle that case.

Improve JobSystem::wait

---

filament/src/Renderer.cpp
libs/utils/include/utils/JobSystem.h
libs/utils/src/JobSystem.cpp
tools/cmgen/src/CubemapIBL.cpp
tools/cmgen/src/CubemapUtils.cpp
tools/cmgen/src/CubemapUtils.h
tools/skygen/src/main.cpp

It was only used to clear the master job, instead the master job is
cleared when waited on.

get rid of JobSystem::reset()

---

libs/utils/CMakeLists.txt
libs/utils/benchmark/benchmark_JobSystem.cpp
libs/utils/include/utils/JobSystem.h
libs/utils/src/JobSystem.cpp

- only signal waitAndRelease() when the corresponding job finishes and
only if there is waitAndRelease() active -- instead of signaling 
every time a job ends.
- don't surrender time slice when attempting to steal a job and it fails
as long as some queue has jobs.
- check that we have to wait, because taking the lock
- add a benchmark
This change more than doubles the amount of jobs we can handle per
second (~965,000 jobs/s on Pixel3)

Improve JobSystem, especially under contention

---

CMakeLists.txt
filament/CMakeLists.txt
filament/src/driver/noop/NoopDriver.cpp
filament/src/driver/noop/PlatformNoop.cpp

Fixed some issues on Windows:
- `clang-cl` doesn't handle `-fstack-protector`
- Moved `NoopDriver` and `PlatformNoop` into `SRCS` because multi-configuration generators like Visual Studio or Xcode can't handle conditional source lists (i.e., `CMAKE_BUILD_TYPE` is empty for them).
- Deleted unnecessary check for iOS

Fix Windows Debug builds

---

libs/image/src/LinearImage.cpp

LinearImage leaks memory if assigned to itself, this ensures the old LinearImage::SharedReference object will be deleted first

Fixes LinearImage memory leak

---

shaders/src/main.vs

Apply skinning to model space normals/tangents and then transform to world space since world space transforms can also include rotations/scaling.
Fixes #653.

Fixes #653: Skin normals/tangents before applying world space transform

---

libs/utils/include/utils/CString.h

Fixes a header usage problem for MSVC, which complains about StaticString not having a constexpr constructor thus making the "make" method not constexpr.

Add constexpr constructor to StaticString

---

samples/suzanne.cpp
samples/vk_animation.cpp
samples/vk_depthtesting.cpp
samples/vk_hellopbr.cpp
samples/vk_hellotriangle.cpp
samples/vk_imgui.cpp
samples/vk_shadowtest.cpp
samples/vk_strobecolor.cpp
samples/vk_texturedquad.cpp
samples/vk_vbotest.cpp
samples/vk_viewtest.cpp

The `main` function needs a return value otherwise we see crashes in Debug mode on Windows:
```
UNHANDLED EXCEPTION - Reason: Illegal Instruction (0xc000001d)
```

Add return 0 to main functions to avoid crashes on Windows

---

libs/image/include/image/ColorTransform.h

Adds rounding to nearest whole integer, supports copying over an alpha channel for linear to srgb conversion. Code would previously incorrectly apply sRGB conversion to alpha.

Improves linear to srgb conversion functions

---

libs/image/src/ImageOps.cpp
libs/image/src/ImageSampler.cpp

Background: with the Vulkan backend, RGB8 textures do
not work (at least not on my hardware). This makes me unable to run some
examples, because they use normal maps in RGB8 format.
It appears that the following commit addresses the problem by adding a
special command line option to mipgen:
https://github.com/google/filament/commit/8dda07bf2c19f9ebd8ab499ca2c3849d7b1f031f
However, processing normal maps with this option does not work: certain
assertions in the image library fail.
This PR changes these functions in the image library to handle 4-channel
images instead of failing.

Make 4-channel versions of certain image operations.

---

libs/imageio/src/ImageEncoder.cpp
tools/skygen/src/main.cpp

Bring back the normalization and gamma correction command line flags,
render the ground in the lower half of the image.

Improve skygen

---

CMakeLists.txt
build/common/test_list.txt
tools/glslminifier/CMakeLists.txt
tools/glslminifier/src/GlslMinify.cpp
tools/glslminifier/src/GlslMinify.h
tools/glslminifier/src/main.cpp
tools/glslminifier/tests/test_glslminifier.cpp

Right now, shader code is included in our binaries without any type of minification- that is, they include unnecessary comments, newlines, etc. This adds a tool, `glslminifier`, which can be used to strip glsl files to reduce binary size. Stripping comments and newlines saves around 59Kib at the moment, and there's room for more improvement.
This PR only adds the `glslminifier` tool. It will be enabled in a later PR.

Add glslminifier tool

---

filament/src/Renderer.cpp

This moves the call to `endFrame` after `commit`. This is done in preparation for Metal. Certain resources (like command buffers) are allocated on a per-frame basis inside of `beginFrame`. Since they are still needed in `commit`, this makes it straightforward to free them inside of `endFrame`. We could always free them inside of `commit`, except that this isn't called in the case of canceled frames.

Move call to endFrame after commit

---

filament/src/driver/opengl/OpenGLDriver.cpp

According to [documentation](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBlendFuncSeparate.xhtml) function call should look like this:
`glBlendFuncSeparate(srcRGB, dstRGB, srcA, dstA);`
instead:
`glBlendFuncSeparate(srcRGB, dstRGB, dstA, srcA);`

Incorrect order of arguments in glBlendFuncSeparate function call.

---

filament/src/driver/vulkan/PlatformVkCocoa.mm
samples/CMakeLists.txt
samples/app/FilamentApp.cpp
samples/app/NativeWindowHelper.h
samples/app/NativeWindowHelperCocoa.mm

More prep for adding Metal. This removes a hack we were using to get MoltenVK to work. OpenGL and Vulkan are still supported.

Remove Metal layer hack for MoltenVK

---

build/web/ci-common.sh

This preps for an upcoming regression test that ensures our TypeScript
annotations are valid.

Add TypeScript to Kokoro for web for testing.

---

third_party/gl-matrix/gl-matrix.d.ts

Filament supports (but does not require) gl-matrix, and our TypeScript
annotations will need to use this file to support clients that use
gl-matrix.

Add TypeScript annotations for gl-matrix to third_party.

---

android/samples/image-based-lighting/app/src/main/java/com/google/android/filament/ibl/MeshLoader.kt
android/samples/textured-object/app/src/main/java/com/google/android/filament/textured/MeshLoader.kt
tools/filamesh/README.md

The loader was not updated to support the SNORM16 format now sometimes
used to encode UV sets in filamesh files.
Fixes #708

Fix the Android filamesh file loader

---

samples/app/FilamentApp.cpp
samples/app/FilamentApp.h

Apple changes the backing `layer` on us when using OpenGL, so only attempt to resize it when using MoltenVK.

Fix metal layer resize crash with OpenGL

---

android/filament-android/src/main/cpp/VertexBuffer.cpp
android/filament-android/src/main/java/com/google/android/filament/VertexBuffer.java
android/samples/image-based-lighting/app/src/main/java/com/google/android/filament/ibl/MeshLoader.kt
android/samples/textured-object/app/src/main/java/com/google/android/filament/textured/MeshLoader.kt
filament/include/filament/VertexBuffer.h
filament/src/VertexBuffer.cpp
libs/filameshio/src/MeshReader.cpp
tools/filamesh/README.md
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

This enables more concise creation of VertexBuffer and avoids breaking existing API.

VertexBuffer builder normalized now accepts "false".

---

docs/Materials.md.html
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/MaterialInfo.h
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/common_material.vs
tools/matc/src/matc/ParametersProcessor.cpp
tools/matc/src/matc/ParametersProcessor.h

Materials can disbale this behavior by setting flipUV: false
in the header section of the material definition.
Fixes #672

Document UV flipping behavior and add control attribute

---

filament/src/driver/opengl/OpenGLDriver.cpp

When clients deleted renderables that referred to index buffers that
were still active, it was possible for our shadow ELEMENT_ARRAY_BUFFER
binding to get out of sync with the actual binding.
It is somewhat amazing that this has never caused issues before. Perhaps
it is rare for clients to "recycle" index buffers across multiple
renderable lifetimes.
This fixes #718.

Fix diabolical VAO state management bug.

---

filament/src/Material.cpp
libs/filabridge/include/private/filament/Variant.h

The engine tries to be smart by using a single vertex shader when
rendering unskinned, non-alpha masked, non-customized materials.
This leads to a lot of issues when laying down the depth prepass.
This change simply gets rid of this optimization (which wasn't
properly profiled anyway). Correctness is more important.
Fixes #645

Fix depth prepass

---

build/toolchain-aarch64-linux-android.cmake
build/toolchain-arm7-linux-android.cmake
build/toolchain-x86-linux-android.cmake
build/toolchain-x86_64-linux-android.cmake

This change allows these toolchains to work on Windows. `README` update to come later. Fixes #711

Update Android toolchains for building on Windows

---

filament/CMakeLists.txt
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h
filament/src/fg/FrameGraphPass.h
filament/src/fg/FrameGraphPassResources.h
filament/src/fg/FrameGraphResource.h
filament/test/CMakeLists.txt
filament/test/filament_framegraph_test.cpp
filament/test/filament_test_exposure.cpp
libs/utils/include/utils/Log.h

The design of the frame graph is largely inspired from Yuriy O'Donnell's '17 GDC talk.
This is still work in progress, in particular the API might change.
Currently supported: importing resources, culling of unreferenced passes, versioning to guarantee graph integrity, resource aliasing, resource lifetime tracking.
There is enough support for running filament's post processing all within the framegraph.
One of the major missing piece to at least get back to parity with the previous code, is tracking accesses to renter targets attachments so that we can discard them properly. Currently no discard is performed, which is not great for tilers.

new frame graph for filament

---

build.sh

Gradle creates a hidden .externalNativeBuild folder when issuing CMake
for the first time. This folder contains cached command line parameters
that get passed to CMake, and these can become stale when switching
between "normal" Android builds and Vulkan-enabled Android builds, which
leads to frustrating build errors.

Add another folder to the build's "clean" task.

---

android/filament-android/src/main/cpp/Texture.cpp

Amazingly, the size field in PixelBufferDescriptor was often totally
incorrect for Java-based clients. The reason we did not notice: OpenGL
often consumes a pointer to image data without consuming a byte count
(e.g. glTexImage2D).
OpenGL infers size from dimensions + format, but Vulkan does not. This
caused texture corruption with Vulkan on Android.
This fix follows a pattern used in other places such as
FRenderer::readPixels.

JNI fix for badly-sized PixelBufferDescriptors. (!)

---

filament/src/driver/DriverBase.h
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/vulkan/VulkanHandles.cpp
filament/src/driver/vulkan/VulkanHandles.h

We were stashing the GL format but not the Filament format.
This simplifies VulkanTexture and will allow us to implement a very
simple mipmap generator in DriverBase.
Motivated by #749.

HwTexture now remembers the format.

---

tools/cmgen/src/cmgen.cpp

Currently `cmgen` writes to the console (when generating the spherical harmonics) even with the `--quiet` flag enabled which I assume is a mistake.

Prevent cmgen outputting to the console whilst the quiet flag is enabled

---

CMakeLists.txt
android/filamat-android/CMakeLists.txt
android/filamat-android/libfilamat-jni.map
android/filamat-android/libfilamat-jni.symbols
build.sh
third_party/spirv-cross/tnt/CMakeLists.txt

This adds CMake configuration and an option to `build.sh` to build the `filamat-jni` libraries for Android. It isn't enabled by default, as building `filamat` and thus Spir-V related tools increases the build time significantly. For now, we can build it manually- in the future this might be turned on in a separate CI job.

Add filamat-jni to CMake and build.sh

---

libs/filabridge/include/private/filament/SamplerInterfaceBlock.h
libs/filaflat/include/filaflat/FilaflatDefs.h
libs/filaflat/src/MaterialParser.cpp
libs/filaflat/src/TextDictionaryReader.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/GLSLPostProcessor.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/PostprocessMaterialBuilder.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
third_party/spirv-cross/tnt/CMakeLists.txt
tools/matc/src/matc/CommandlineConfig.cpp
tools/matinfo/src/main.cpp

Add Metal shader compilation to `matc`. Metal shaders are stored in a new text chunk (`MAT_METL`) with associated dictionary (`DIC_METL`). Also update the `mat_info` tool to show Metal shader information via the `--print-metal` flag.

Add Metal shading language compilation to matc

---

libs/utils/include/utils/JobSystem.h
libs/utils/src/JobSystem.cpp

This reverts a JobSystem optimization that attempted to avoid signaling
a condition when there was no waiters. Unfortunately, there was a
race that caused the the signaling thread to miss that the waiter flag
was set, thus not signaling.

fix #755: a race condition cousing a deadlock

---

android/filament-android/build.gradle
filament/src/driver/vulkan/VulkanDriver.cpp

This allows Filament to find validation layers in debug builds.  It does not hurt anything for non-Vulkan builds.

Add jniLibs search path to filament-android for Vulkan.

---

CODE_STYLE.md
filament/src/Texture.cpp

This functionality regressed when we replaced the OpenGL implementation
with our own.
I proved both the regression and the fix by running suzanne with the
following hacks.
```
--- a/libs/image/include/image/KtxUtility.h
+++ b/libs/image/include/image/KtxUtility.h
@@ -129,8 +129,9 @@ namespace KtxUtility {
for (uint32_t level = 0; level < nmips; ++level) {
ktx.getBlob({level, 0, 0}, &data, &size);
PixelBufferDescriptor pbd(data, size * 6, dataformat, datatype, cb, cbuser);
-                texture->setImage(*engine, level, std::move(pbd), Texture::FaceOffsets(size));
+                if (level == 0) texture->setImage(*engine, level, std::move(pbd), Texture::FaceOffsets(size));
}
+            texture->generateMipmaps(*engine);
return texture;
}
--- a/samples/app/IBL.cpp
+++ …
```

Repair generateMipmaps for cubemaps.

---

CMakeLists.txt
android/filamat-android/CMakeLists.txt
android/filamat-android/build.gradle
libs/filamat/CMakeLists.txt
shaders/CMakeLists.txt

Install filamat as a single static library to make linking against it easy. This updates the `android/filamat-android/CMakeLists.txt` to __only__ be used to build filamat-jni for Android, invoked through Gradle. It now closely mirrors `android/filament-android/CMakeLists.txt`.
TODO:
- Desktop `filamat-jni` library
- C++ / Java example of using `filamat`.

Install filamat and dependencies as single static library

---

filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/opengl/OpenGLDriver.h

we could crash by dereferencing something that's 
not a pointer when blitting to a rendertarget not
backed by a texture (i.e. renderbuffer).
also there was a case where we couldn't disambiguate
between the two cases.

fix a possible crash in the gl backend

---

shaders/src/brdf.fs
shaders/src/light_indirect.fs
shaders/src/shading_model_standard.fs
shaders/src/shading_model_subsurface.fs

Our visibility terms don't make use of roughness, only of
roughness^2. This change simplifies the shaders, which will
help for specular AA.

Remove unnecessary function parameter

---

README.md

The Windows example should run the same program as was built in the previous step.

Fix example running a different app than built

---

filament/CMakeLists.txt
filament/src/driver/metal/MetalEnums.h
filament/src/driver/metal/MetalState.h
filament/src/driver/metal/MetalState.mm

This adds a few state-management classes for Metal, `StateCache` and `StateTracker`, as well as some logic to create various Metal state objects.

Add Metal state creation logic

---

libs/filameshio/include/filameshio/MeshReader.h
libs/filameshio/src/MeshReader.cpp
samples/sample_cloth.cpp
samples/sample_normal_map.cpp
samples/suzanne.cpp
samples/vk_hellopbr.cpp
web/filament-js/jsbindings.cpp

This class will not extend well to glTF so this cordons it off into the
filamesh namespace, which is an already-existing namespace that we use
for the things related to the filamesh file format.
For glTF we might create a new library with its own MeshReader so
this will mitigate confusion.

Move MeshReader into filamesh namespace.

---

samples/frame_generator.cpp
samples/gltf_viewer.cpp
samples/lightbulb.cpp
samples/material_sandbox.cpp
samples/sample_cloth.cpp
samples/sample_full_pbr.cpp
samples/sample_normal_map.cpp

Fixes #797 
In multiple samples when a file didn't exist, it printed the first file as being the offending argument, regardless of which actually was.

Fixed printing of wrong file names

---

android/filament-android/src/main/cpp/NioUtils.cpp
android/filament-android/src/main/cpp/NioUtils.h
android/filament-android/src/main/cpp/VertexBuffer.cpp

The bug was reproduced and the fix was verified by copying the following
code snippet into one of our Android samples:
val norm = floatArrayOf(1.0f, 0.0f, 0.0f)
val tang = floatArrayOf(0.0f, 1.0f, 0.0f, 1.0f)
val expected = floatArrayOf(0.5f, 0.5f, 0.5f, 0.5f)
val resultBuffer = FloatBuffer.allocate(4)
val qtc = VertexBuffer.QuatTangentContext()
qtc.quatCount = 1
qtc.quatType = VertexBuffer.QuatType.FLOAT4
qtc.outBuffer = resultBuffer
qtc.normals = FloatBuffer.wrap(norm)
qtc.tangents = FloatBuffer.wrap(tang)
VertexBuffer.populateTangentQuaternions(qtc)
Log.e("Filament", "${expected[0]} == ${resultBuffer[0]}")
Fixes #695.

JNI enhancement: allow mutation of non-direct buffers.

---

filament/src/driver/opengl/PlatformCocoaTouchGL.mm

`makeCurrent` can be called with a bound framebuffer of 0, which is invalid on iOS. We need to explicitly bind the default framebuffer before calling `glRenderbufferStorage`. Fixes #814

Fix incomplete framebuffer assert thrown for iOS

---

CMakeLists.txt

This is make it a lot easier to distributes binaries like cmgen or
matc.

always use the static version of libc++abi

---

android/filament-android/src/main/cpp/Renderer.cpp
filament/include/filament/Viewport.h
filament/src/Froxelizer.cpp
filament/src/PostProcessManager.cpp
filament/src/RenderPass.cpp
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp
filament/src/Texture.cpp
filament/src/View.cpp
filament/src/driver/DriverAPI.inc
filament/src/driver/metal/MetalDriver.mm
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/vulkan/VulkanDriver.cpp
filament/src/fg/FrameGraph.cpp
filament/test/filament_framegraph_test.cpp
libs/filabridge/include/filament/driver/DriverEnums.h

We split out Viewport and RenderPassFlags.

Split RenderPassParams into multiple structs

---

filament/include/filament/Scene.h
filament/src/Engine.cpp
filament/src/Scene.cpp
filament/src/details/Scene.h

This is an efficient method that allows clients to add a slew of
entities to the scene. This is particularly useful for the upcoming
gltfio library, which is agnostic of the Scene and exposes a flat
list of entities.

Introduce addEntities method to Scene.

---

samples/app/MeshAssimp.cpp

I noticed this while working on the new lighter weight loader.

MeshAssimp: fix glTF material hash function.

---

build/windows/build.bat
build/windows/variants.bat
filament/README.md

Add all Windows runtime variants (`/MD`, `/MDd`, `/MT`, and `/MTd`) to Windows release builds. Fixes #810.
The Windows release directory structure will look like:
```
bin
docs
include
lib
|-- x86_64
|-- md
|-- *.lib
|-- mdd
|-- *.lib
|-- mt
|-- *.lib
|-- mtd
|-- *.lib
|-- filamat-jni.dll
|-- filament-jni.dll
```

Build all run-time variants on Windows for CI release and continuous

---

libs/utils/CMakeLists.txt
third_party/meshoptimizer/CMakeLists.txt

`filameshio` depends on the meshoptimizer lib, so install that alongside other Filament libs. `MeshReader.h` also includes the `utils/Path.h` header, so copy that to the install folder as well.

Install requirements for linking against filameshio

---

filament/src/Texture.cpp
filament/src/driver/DriverAPI.inc
filament/src/driver/metal/MetalDriver.mm
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/vulkan/VulkanDriver.cpp

Fixes #808.  See also comments in #749.

DriverAPI: add generateMipmaps and canGenerateMipmaps.

---

filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/opengl/OpenGLDriver.h

the texture's max level wasn't set properly when uploading
data for level 0 (it was for other levels).
this would cause uninitialized levels to be accessed by the GPU.

set textures max level properly

---

filament/test/CMakeLists.txt

It looks like out static libc++abi that we use on linux needs
pthread, even if the exe doesn't use it. 
Adding libutils to this test fixes the build on my local linux machine.
The real fix is probably something else, bug I don't quite
understand these shenanigans.

fix linux debug build

---

CMakeLists.txt
filament/src/driver/metal/MetalDriver.h
filament/src/driver/metal/MetalDriver.mm
ios/samples/hello-triangle/build-materials.sh
ios/samples/hello-triangle/hello-triangle.xcodeproj/project.pbxproj
ios/samples/hello-triangle/hello-triangle/FilamentView.mm

A few changes to get Metal working on iOS. Replace the MoltenVK version of the sample with a Metal version.
Since this changes a few CMake variables, the iOS CMake directories will to be cleaned and rebuilt in order for the sample app to work (via `./build.sh -c -p ios debug release`).

Replace MoltenVK with Metal for iOS sample

---

filament/docs/Versioning.md
filament/src/Engine.cpp
filament/src/Material.cpp
libs/filabridge/include/filament/MaterialEnums.h
libs/filaflat/include/filaflat/MaterialParser.h
libs/filaflat/src/MaterialParser.cpp
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/PostprocessMaterialBuilder.cpp
tools/matc/src/matc/CommandlineConfig.cpp

Material archives already contain two version chunks (post process and
normal) but the renderer was ignoring these. The change makes it so that
matc writes a new MaterialEnums value into these chunks, and the engine
panics when receiving a material version that it does not expect.
This also adds a --version option to matc. No changes were necessary
to matinfo because it already prints out these values.
Fixes #796.

Introduce MATERIAL_VERSION and panic.

---

android/filamat-android/src/main/cpp/MaterialBuilder.cpp
android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/PostprocessMaterialBuilder.cpp
libs/filamat/src/sca/GLSLTools.cpp
libs/filamat/src/sca/GLSLTools.h
tools/matc/src/matc/MaterialCompiler.cpp
tools/matc/src/matc/MaterialCompiler.h
tools/matc/src/matc/PostprocessMaterialCompiler.cpp

`init` prepares glslang for material compilation. `shutdown` frees resources. Internally, we keep track of calls to `init` vs `shutdown` so we can warn users if `init` has not been called. glslang [does something similar](https://github.com/KhronosGroup/glslang/blob/58d6905ea01f7c44652eb082d26b662ca811df25/glslang/MachineIndependent/ShaderLang.cpp#L1271).

Add Init and Shutdown methods to MaterialBuilder

---

filament/src/driver/opengl/OpenGLDriver.cpp

we never rely (or should rely) on the fact that glBinderBufferRange()
also sets the generic binding, so we don't need to check for that when
calling glBindBufferRange().
This helps a little bit reducing the numbers of GL calls, especially
when several consecutive draw calls use the same material instance.

improve bindBufferRange() state tracking

---

samples/app/MeshAssimp.cpp
third_party/libassimp/code/CalcTangentsProcess.cpp
third_party/libassimp/tnt/README.md

Assimp's CalcTangentSpace deviates from de facto glTF 2.0 so we were
compensating for this with an unconditional fixup in MeshAssimp. However
the fixup should apply only when CalcTangentSpace is active, i.e. when
the model is missing tangents.
This makes it so that NormalTangentMirrorTest (has tangents) and
NormalTangentTest (needs tangents) both look reasonable.
I also noticed that MeshAssimp was inexplicably applying
aiProcess_CalcTangentSpace twice: once as a flag, and once as a
post-process. I removed the latter.
This will be fixed in the upcoming cgltf-based loader, which will
use our officially-sanctioned utility method in VertexBuffer.
See #528

Tangent-related fixups in MeshAssimp.

---

samples/sample_cloth.cpp
samples/sample_full_pbr.cpp
samples/sample_normal_map.cpp

`MaterialBuilder::init` now must be called before building any materials.

Initialize MaterialBuilder in samples

---

filament/src/Engine.cpp
filament/src/MaterialInstance.cpp

Setting material parameters on default material instances has no effect- i.e., the following:
```
MaterialInstance* instance = material->getDefaultInstance();
instance->setParameter("myParameter", RgbType::LINEAR, {1.0, 0.0, 0.0});
```
This happens with both float and sampler parameters. I'm a bit surprised this hasn't been discovered yet, so maybe I'm missing something.
Also, I think the UBO usage flag for the default material instance should match explicitly-created instances (`DYNAMIC`) unless we want the semantics that the default instance's parameters aren't meant to change...

Fix, can't set material parameters on default material instance

---

libs/filamat/CMakeLists.txt

This is one of those CMake gotchas, we should always use
CMAKE_CURRENT_SOURCE_DIR instead of CMAKE_SOURCE_DIR to allow
Filament to exist as a subproject.
In particular, this was causing the following build error when trying to
build Filament as a nested project.
combine-static-libs.sh: No such file or directory
Fixes #861.

Do not use CMAKE_SOURCE_DIR.

---

filament/src/driver/opengl/gl_headers.cpp
filament/src/driver/opengl/gl_headers.h

iOS only has headers up to OpenGL ES 3.0, so we have to fake this in order for Filament to compile.

Add glRenderbufferStorageMultisampleEXT declaration to iOS

---

shaders/src/post_process.fs
shaders/src/post_process.vs

vertex shader interpolants are interpolated at pixel centers by the GPU,
but we were doing our own "pixel-center" adjustment, so we ended-up with
"vertex_uv" at a pixel corner instead of center.
The half-pixel adjustment is removed.
This leads to sharper looking images because in addition to shifting 
everything by 0.5 pixels, this was essentially applying a box-filter
to the whole picture -- kind of like taking 1 mip level down.

Fix fxaa offset (#868)

---

filament/src/RenderTargetPool.cpp
filament/src/Renderer.cpp
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/opengl/OpenGLDriver.h
filament/src/driver/opengl/gl_headers.cpp
filament/src/driver/opengl/gl_headers.h

It's now possible to create a multisample FBO with a non-multisample
texture attachment. In this case, the drive is responsible for
automatically resolving the multisample buffer into the texture on
endRenderPass().
This allows us to avoid doing a "resolve blit" on the client side, but 
more importantly, it allows the driver to do this efficiently,
especially on tilers.
The semantic of this operation is the same than with
EXT_multisampled_render_to_texture. i.e. the multisample buffer is
lost after resolve. For GL/GLES drivers if 
EXT_multisampled_render_to_texture is not available this behavior
is emulated with a renderbuffer + blit.
This CL also fixes the creation of attachments to a face of a cubemap.

rework multisample driver api

---

samples/app/MeshAssimp.cpp

Our treatment of emissive values in glTF was not matching other viewers because we were interpreting emissive texture alpha as an energy compensation term, but the glTF lighting model does not include an energy compensation term for emissive.
This change makes gltf_viewer appear more consistent with other viewers.  Before / After screenshots of the boombox:

Fix up emissive energy compensation for glTF.

---

libs/filagui/include/filagui/ImGuiHelper.h
libs/filagui/src/ImGuiHelper.cpp

This allows for use in contexts where ImGui's AddFontFromFileTTF can fail, as well as support for >1 font

ImGuiHelper gets a public method for creating atlas texture

---

filament/src/components/RenderableManager.cpp

The move ctor wasn't implemented properly. We actually fix this by
using a std::vector<> instead of a raw allocation for storing entries.
This std::vector<> is never reallocated.

Fix #871 -- double free if RenderableManager::Builder

---

libs/math/include/math/TQuatHelpers.h

My earlier fix (3b373e5) was insufficient in some cases, this new
approach is cribbed from glMatrix.

Fix nans in math::slerp, second attempt.

---

filament/CMakeLists.txt
filament/src/driver/metal/MetalContext.h
filament/src/driver/metal/MetalContext.mm
filament/src/driver/metal/MetalDriver.h
filament/src/driver/metal/MetalDriver.mm
filament/src/driver/metal/MetalHandles.h

No functional changes, just cleaning up.
- Rename `MetalImpl` to `MetalContext` and move the definition into a header
- Remove "m" prefix from MetalContext variables
- Factor out an `acquireDrawable` function

Metal context cleanup

---

filament/include/filament/Material.h
filament/include/filament/Scene.h

Clang was issuing warnings for these when building iOS sample apps.

Fix a few documentation issues

---

filament/include/filament/Scene.h
filament/include/filament/TransformManager.h
filament/src/Scene.cpp
filament/src/components/TransformManager.cpp
filament/src/components/TransformManager.h
filament/src/details/Scene.h

These new queries are used for the tree view feature in the upcoming glTF viewer.  Sneak peek:

Add new queries to TransformManager and Scene.

---

filament/include/filament/Viewport.h

The default constructor of the Viewport class left the view properties in an uninitialized state that could lead to an undeterministic behavior in the later stages during rendering.
In our case, the issue manifested in the Froxelizer class in the setViewport() method that was flaky because sometimes the old viewport in the Froxelizer class (mViewport) was equal to the newly set viewport which caused the mDirtyFlags to not be updated. This then resulted in a crash because Froxelizer's mPlanesX and mPlanesY were not allocated in the update() function even though they were used.

Fixed uninitialized properties in the Viewport class.

---

ios/samples/hello-pbr/hello-pbr.xcodeproj/project.pbxproj
ios/samples/hello-triangle/hello-triangle.xcodeproj/project.pbxproj

@prideout Seems like this is a temporary dependency? If so, we can revert this change when Filament no longer depends on `geometry`.

Link iOS sample apps with the geometry library

---

ios/samples/transparent-rendering/.gitignore
ios/samples/transparent-rendering/build-materials.sh
ios/samples/transparent-rendering/transparent-rendering.xcodeproj/project.pbxproj
ios/samples/transparent-rendering/transparent-rendering.xcodeproj/project.xcworkspace/contents.xcworkspacedata
ios/samples/transparent-rendering/transparent-rendering.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
ios/samples/transparent-rendering/transparent-rendering/AppDelegate.h
ios/samples/transparent-rendering/transparent-rendering/AppDelegate.m
ios/samples/transparent-rendering/transparent-rendering/Assets.xcassets/AppIcon.appiconset/Contents.json
ios/samples/transparent-rendering/transparent-rendering/Assets.xcassets/Contents.json
ios/samples/transparent-rendering/transparent-rendering/Base.lproj/LaunchScreen.storyboard
ios/samples/transparent-rendering/transparent-rendering/Base.lproj/Main.storyboard
ios/samples/transparent-rendering/transparent-rendering/FilamentView.h
ios/samples/transparent-rendering/transparent-rendering/FilamentView.mm
ios/samples/transparent-rendering/transparent-rendering/Info.plist
ios/samples/transparent-rendering/transparent-rendering/ViewController.h
ios/samples/transparent-rendering/transparent-rendering/ViewController.m
ios/samples/transparent-rendering/transparent-rendering/bakedColor.mat
ios/samples/transparent-rendering/transparent-rendering/main.m

iOS actually supports transparent rendering quite easy. This adds a new iOS transparent-rendering sample. It's the exact same as the hello-triangle sample, with the addition of a `UITextView` and the following changes to `FilamentView.mm`:
```
@@ -124,13 +124,18 @@ static constexpr uint8_t BAKED_COLOR_PACKAGE[] = {
CGRect nativeBounds = [UIScreen mainScreen].nativeBounds;
metalLayer.drawableSize = nativeBounds.size;
+
+    // This is necessary so iOS composites the Filament view on top of other UIViews.
+    metalLayer.opaque = NO;
#endif
}
- (void)initializeGLLayer
{
CAEAGLLayer* glLayer = (CAEAGLLayer*) self.layer;
-    glLayer.opaque = YES;
+
+    // This is necessary so iOS composites the Filament view on top of other UIViews.
+    glLayer.opaque = NO;
}
- (void)initializeFilament
@@ …
```

Add transparent-rendering iOS demo

---

shaders/src/post_process.vs

This fixes incorrect post-processing when Metal render target dimensions weren't a multiple of 32.

Fix post processing issue for Metal

---

filament/src/DebugRegistry.cpp
filament/src/View.cpp
filament/src/details/Engine.h
samples/material_sandbox.cpp

This is effectively moving all shader computations to view space,
improving floating-point precision in the shaders, by staying
around zero where fp precision is highest. This also ensures that
when the camera is very far from the origin, objects are still
rendered and lit properly.
Below is a before/after with the scene/camera positioned at 1600 Km from the origin -- at this distance fp32 precision is about 10cm.

Always centers the camera to the world origin

---

filament/src/ShadowMap.cpp

when we compute the depth range of the shadow map, if znear is behind
zfar, it just means we don't have any shadow caster in front of
a receiver, and we can just bail out without shadowing -- as opposed
to asserting.

remove an incorrect assert() in shadow mapping

---

android/filamat-android/src/main/cpp/MaterialBuilder.cpp
filament/include/filament/Material.h
filament/include/filament/VertexBuffer.h
filament/src/MaterialParser.h
filament/src/details/VertexBuffer.h
filament/src/driver/Program.h
filament/src/driver/metal/MetalState.h
filament/src/driver/vulkan/VulkanBinder.h
filament/src/driver/vulkan/VulkanHandles.h
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/EngineEnums.h
libs/filabridge/include/private/filament/SamplerBindingMap.h
libs/filabridge/include/private/filament/SamplerInterfaceBlock.h
libs/filabridge/src/SamplerBindingMap.cpp
libs/filabridge/src/SibGenerator.cpp
libs/filabridge/src/UibGenerator.cpp
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/eiff/MaterialInterfaceBlockChunk.h
libs/filamat/src/sca/GLSLTools.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.h
libs/filamat/src/shaders/MaterialInfo.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.h
libs/filamat/tests/test_filamat.cpp
tools/matinfo/src/main.cpp

- EngineEnums.h is not a private headers as it contained mostly private
stuff
- MaterialEnums.h is still public, but now only contains public stuff.
Private parts were moved to MaterialEnums.h or MaterialBuilder.h
- And finally SamplerBinderMap is moved under private/ as well, since
it's certainly not a public API.
With this change, the public headers of filabridge become more reasonable
and limited.

More headers clean-up

---

CMakeLists.txt
README.md
build.sh
build/web/markdeep-rasterizer/.gitignore
build/web/markdeep-rasterizer/cli.js
build/web/markdeep-rasterizer/package.json
docs/.gitignore
docs/Filament.html
docs/Materials.html

build.sh -w can now be used to "rasterize" Markdeep .md.html files
to regular, static .html files. These files load faster and do not
suffer from an initial flash of uninitialized content.
This new command requires node, npm and nx to run puppeteer to
"rasterize" the Markdeep documents. This should eventually be
integrated in the actual build system to automatically re-generate
the HTML files when the Markdeep documents are edited.

Add build command for Markdeep files

---

filament/src/ShadowMap.cpp
filament/test/filament_test.cpp
libs/math/include/math/TMatHelpers.h
libs/math/include/math/mat2.h
libs/math/include/math/mat3.h
libs/math/include/math/mat4.h
libs/math/tests/test_mat.cpp
samples/app/CameraManipulator.cpp
samples/app/Cube.cpp
samples/gltf_viewer.cpp
samples/lightbulb.cpp
samples/material_sandbox.cpp
samples/suzanne.cpp
samples/vk_animation.cpp
samples/vk_depthtesting.cpp
samples/vk_hellopbr.cpp
samples/vk_hellotriangle.cpp
samples/vk_shadowtest.cpp

scale() -> scaling()
translate() -> translation()
rotate() -> rotation()
These static functions create a matrix, they don't modify it.
Fixes #826

API change: rename matrix factory functions

---

filament/src/Engine.cpp
filament/src/Material.cpp
filament/src/MaterialParser.cpp
filament/src/MaterialParser.h
filament/src/driver/Program.cpp
filament/src/driver/Program.h
filament/src/driver/metal/MetalHandles.mm
filament/src/driver/opengl/OpenGLProgram.cpp
filament/src/driver/vulkan/VulkanHandles.cpp
libs/filaflat/include/filaflat/ShaderBuilder.h
libs/filaflat/src/MaterialChunk.cpp
libs/filaflat/src/ShaderBuilder.cpp
libs/filaflat/src/Unflattener.cpp
libs/utils/include/utils/CString.h
libs/utils/src/CString.cpp
tools/matinfo/src/main.cpp

Program::shader() was taking a string before which didn't make sense
for spirv.  Now it's just a blob, in the case of GL/Metal, the blob
must be a null terminated c-string, and the size must include the
terminating null character.
This fixes an out-of-bound access in ShaderBuilder::getShader() (which
doesn't exist anymore), because it was creating a CString passing
a size that included the null terminating char, which is not was CString
expects. CString can now assert() in that case.
driver::Program now uses a std::vector<> for storage, which we should
fix at some point (b/c it's a public header). CString was not suited to
store binary blobs.

Program::shader() now only takes a void* + size

---

filament/src/driver/vulkan/VulkanDriverImpl.cpp
filament/src/driver/vulkan/VulkanHandles.cpp

This change happens to "fix" issue #875, although we may wish to rethink
our DFG representation in the future.

Vulkan: support R16G16B16 textures via DataReshaper.

---

filament/src/MaterialParser.cpp

when testing we're often using the NoopDriver, which
is has neither spirv or text shaders, so we default
to text to make this case work.

fix filameshio test

---

libs/filabridge/src/SamplerBindingMap.cpp

This fixes #935
SamplerBindingMap was always adding the post-process samplers to the
map -- but matc doesn't generate those. This led the vulkan backend
to believe there was a post-process sampler bound, when there wasn't.
This is also technically a bug in the Vulkan backend because it should
have used the SamplerInterfaceBlock to determine which shaders are
actually used instead of blindly going through the whole list and 
trusting SamplerBindingMap.
The fix is kind of a hack, but the whole SamplerBindingMap is kind of a
hack anyways.

fix SamplerBindingMap for non postprocess materials

---

libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/ResourceLoader.cpp

gltfio computes two types of bounding boxes: one for renderables (used
for frustum culling) and one for the overall asset (used for
positioning the camera or asset).
Both of these are based on the min+max attributes in the glTF file, but
the asset-level box was incorrect because only two corners of the
transformed AABB were considered.
This CL also adds optional computation of bounding boxes that crawls
through the vertex positions. This is useful when diagnosing potential
issues with the asset's min+max info.
These enhancements are motivated by a culling issue seen with the voxel
Cathedral on sketchfab.

gltfio: fix up and enhance AABB functionality.

---

libs/gltfio/CMakeLists.txt
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp
libs/gltfio/src/Wireframe.cpp
libs/gltfio/src/Wireframe.h

Since glTF has embedded min/max info, it is useful to visualize these when diagnosing issues with frustum culling.  The API is similar to Animator in that it is exposed through FilamentAsset but is created lazily and is implemented outside of FilamentAsset.

gltfio: add optional wireframe functionality.

---

filament/src/driver/vulkan/PlatformVkAndroid.cpp
filament/src/driver/vulkan/PlatformVkCocoa.mm
filament/src/driver/vulkan/PlatformVkCocoaTouch.mm
filament/src/driver/vulkan/PlatformVkLinux.cpp
filament/src/driver/vulkan/PlatformVkWindows.cpp

only filament/driver/* are allowed. These were not even needed.

'driver' shouldn't include filament/*.h headers

---

libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/MaterialGenerator.cpp
libs/gltfio/src/MaterialGenerator.h

- rename gltfio::AlphaMode to use glTF nomenclature
- keep depth writes enabled for transparent renderables

gltfio: transparency fixups

---

filament/include/filament/Engine.h
filament/src/Engine.cpp
filament/src/components/CameraManager.h
filament/src/details/Engine.h

- getCameraComponent(Entity) retrieves a Camera component from an entity
- destroyCameraComponent(Entity) destroys just the camera component
attached to an entity.
destroyCamera() are now deprecated because the API is confusing, it's
not immediately clear that it's destroying all component + the entity
itself.
Node: We don't add the corresponding Java APIs yet because there is no 
easy way to guarantee they're safe without making sure that 
getCameraComponent() will always return the same instance (which it
wouldn't currently).

Better Camera component management

---

android/filament-android/src/main/cpp/IndexBuffer.cpp
android/filament-android/src/main/cpp/VertexBuffer.cpp
filament/include/filament/IndexBuffer.h
filament/include/filament/VertexBuffer.h
filament/src/IndexBuffer.cpp
filament/src/VertexBuffer.cpp
filament/src/details/IndexBuffer.h
filament/src/details/VertexBuffer.h
filament/src/driver/DriverAPI.inc
filament/src/driver/metal/MetalDriver.mm
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/vulkan/VulkanDriver.cpp

It was redundant with BufferDescriptor::size.

remove the "byteSize" parameter from update[Vertex|Index]Buffer

---

CMakeLists.txt
libs/gltfio/CMakeLists.txt
libs/gltfio/materials/ubershader.mat.in

We will need 6 pre-compiled materials (lit vs nonlit and the 3 blend
modes). This uses CMake's "configure_file" functionality to generate 6
mat files, then invokes matc on each one. They are then combined using
resgen.

gltfio: add ubershader template.

---

libs/geometry/include/geometry/SurfaceOrientation.h
libs/geometry/src/SurfaceOrientation.cpp

I reproduced the issue by hacking our redball demo and visually verified the fix.
cc @AdrianAtGoogle

Avoid NaN when normal is colinear with fake axis.

---

web/filament-js/extensions.js
web/filament-js/jsbindings.cpp
web/filament-js/utilities.js

These bindings are not user friendly because clients need to manually allocate / deallocate memory. However it gets the job done.
Fixes #959.

geometry: add JS bindings for SurfaceOrientation

---

filament/src/MaterialParser.cpp
filament/src/MaterialParser.h

no need to hide the implementation anymore, since the whole thing
is internal and doesn't appear in public headers.
this saves a dynamic allocation when unflattening materials.

simplify MaterialParser

---

filament/include/filament/Box.h
filament/test/filament_test.cpp
libs/math/include/math/TVecHelpers.h
libs/utils/test/test_StructureOfArrays.cpp

they're dangerous as they will make things like
std::min() work, but probably won't do the
right thing.

remove vector comparison operators

---

filament/src/driver/opengl/PlatformWGL.cpp

The Windows compiler apparently lets us jump to a label where we test a variable that hasn't been declared yet. And that variable was uninitialized too.

Don't test an undeclared variable

---

filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/opengl/OpenGLDriver.h

Some GPU seem to loose the content of UBOs for draw calls emitted 
before a glFlush followed by more draw calls.
On those GPUs, we just never call glFlush, which could result in
reduced parallelism between the cpu and gpu.
This is a workaround for #974

Workaround a UBO/glFlush interaction on some GPUs

---

CMakeLists.txt
android/filamat-android/src/main/cpp/MaterialBuilder.cpp
android/samples/README.md
android/samples/material-builder/README.md
build.sh
build/android/build.sh
build/common/build-common.sh
build/common/ci-common.sh
build/linux/ci-common.sh
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/EngineEnums.h
libs/filamat/include/filamat/MaterialBuilder.h

Filamat public headers were including a private header. This PR fixes
this problem. It also forces filamat to always be compiled to avoid
breaking filamat without noticing. The flag `-l` is not available anymore
in `build.sh` as a result.
See issue #1001 for more information.

Fix filamat build

---

filament/src/PostProcessManager.cpp
filament/src/Renderer.cpp
filament/src/Texture.cpp
filament/src/driver/DriverAPI.inc
filament/src/driver/metal/MetalDriver.mm
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/vulkan/VulkanDriver.cpp

Because with OpenGL ES backends, it's not allowed
to blit with a linear filter when depth/stencil is used, we need to
expose the filtering option.
In the GLES backend if the linear filter is selected and depth/stencil 
is selected, filtering is downgraded to nearest silently.

Add filter parameter to the blit() backend function

---

filament/src/driver/opengl/PlatformEGL.cpp
filament/src/driver/opengl/gl_headers.cpp
filament/src/driver/opengl/gl_headers.h

On Android this can cause a dead-lock, because it looks like dlopen()
holds a lock while calling static initializers.
Bug: 126424427

don't call EGL during static initialization

---

filament/src/ShadowMap.cpp
filament/src/details/MaterialInstance.h
filament/src/driver/DriverAPI.inc
filament/src/driver/metal/MetalDriver.mm
filament/src/driver/opengl/OpenGLDriver.cpp
filament/src/driver/vulkan/VulkanDriver.cpp
libs/filabridge/include/filament/driver/DriverEnums.h

- the IGNORE_VIEWPORT flag is gone. It wasn't actually needed and what
it was doing was ambiguous.
- removed the backend viewport() API which wasn't actually needed.
- beginRenderPass() now ALWAYS sets the viewport and scissor but 
doesn't necessarily clears honoring the scissor (based on the
IGNORE_SCISSOR flag).
- the GLES backend now just sets the scissor when it needs it, as opposed
to always trying to keep it set. we now rely on state tracking to
de-dup the gl calls.

rework scissor/viewport API a bit in the backend

---

filament/CMakeLists.txt
filament/src/driver/vulkan/VulkanBuffer.cpp
filament/src/driver/vulkan/VulkanDisposer.cpp
filament/src/driver/vulkan/VulkanDisposer.h
filament/src/driver/vulkan/VulkanDriver.cpp
filament/src/driver/vulkan/VulkanDriver.h
filament/src/driver/vulkan/VulkanDriverImpl.cpp
filament/src/driver/vulkan/VulkanDriverImpl.h
filament/src/driver/vulkan/VulkanHandles.cpp

This introduces a reference counting mechanism to allow us to defer
destruction of Vulkan resources to the correct time, rather than doing
an aggressive flush-and-wait before every vkDestroy*().
This also preps for removal of the "pending work" queues of
std::function, in favor of using the new Vulkan command buffer
designated for extra-frame activities such as uploads, blits, and layout
transitions.

VulkanDriver: introduce disposer and command buffer wrapper.

---

filament/src/driver/vulkan/VulkanBuffer.cpp
filament/src/driver/vulkan/VulkanDriver.cpp
filament/src/driver/vulkan/VulkanDriverImpl.cpp
filament/src/driver/vulkan/VulkanDriverImpl.h
filament/src/driver/vulkan/VulkanHandles.cpp

This gets us closer to being able to remove the pendingWork queues.

VulkanDriver: do not defer uploads.

---

filament/src/driver/metal/MetalContext.h
filament/src/driver/metal/MetalDriver.h
filament/src/driver/metal/MetalDriver.mm
filament/src/driver/metal/MetalHandles.h
filament/src/driver/metal/MetalHandles.mm
filament/src/driver/metal/MetalState.h

Update Metal driver to use new `SamplerGroupInfo`. We're no longer keeping track of which textures / samplers are already bound to the command encoder as the process was error-prone and isn't worth the effort for now.
Also fixed a memory leak when creating a new depth texture inside of `createRenderTargetR`.
Fixes #1008

Fix Metal sampler binding and memory leak

---

build.sh

ImportExecutable* was generated in the root, instead of the out
folder when using the build script. This is more hermetic.

generate the ImportExecutable*.cmake files in the build directory

---

filament/include/filament/View.h
filament/src/Renderer.cpp

It's more logical to do it this way in the API. Also, MSAA needs an
intermediate buffer (currently), so enabling MSAA in the "UI" view 
wouldn't do what's expected -- it would prevent the "UI" to be blended
properly (again, currently).

MSAA is now disabled when post-processing is disabled

---

libs/gltfio/src/GltfEnums.h

If the glTF file defines bits of the sampler but not the min/mag filters,
gltfio otherwise uses NEAREST. And it looks bad.

Use LINEAR/LINEAR_MIPMAP_LINEAR as the default sampling methods

---

android/samples/hello-triangle/app/build.gradle
android/samples/image-based-lighting/app/build.gradle
android/samples/lit-cube/app/build.gradle
android/samples/texture-view/app/build.gradle
android/samples/textured-object/app/build.gradle
android/samples/transparent-view/app/build.gradle

It is easy to run into our new material version error if a stale
filamat file is sitting around, this helps with that.

Add an extra clean task to Android samples.

---

filament/src/Renderer.cpp

There are a couple reasons for this change. First of all, creating a
Vulkan fence outside of beginFrame / endFrame is not ideal because
the backend does not know yet which command buffer will be chosen
during swap chain acquisition.
Secondly, the Renderer currently calls endFrame in this order:
frameInfoManager.endFrame
mFrameSkipper.endFrame
driver.endFrame
However the beginFrame calls were ordered like this:
frameInfoManager.beginFrame
driver.beginFrame
mFrameSkipper.beginFrame
This change makes it such that the beginFrame calls have the reverse
ordering of the endFrame calls, which is less surprising.
I did a poor man's sanity check by running textured-object on a Pixel 2,
(which enables dynamic resolution) and hacking PostProcessManager to
make it visually obvious if anything were …

(affects OpenGL) Move beginFrame calls to fix fence lifetime.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.h

There are two changes involved here:
1) Recreate (do not recycle) the submission fences at every frame.
2) Add shared ownership semantics to existing fences to allow DriverAPI
clients to "own" fences.
The first change was motivated by FrameSkipper, which might have a
fence list that is longer than the number of swap chain contexts.
The second change was implemented simply by creating a tiny wrapper
struct for VkFence with a proper constructor and destructor, then
leveraging shared_ptr.

Add HwFence support to the Vulkan backend.

---

filament/backend/CMakeLists.txt
filament/backend/include/private/backend/OpenGLPlatform.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLPlatform.cpp
filament/backend/src/opengl/PlatformCocoaGL.h
filament/backend/src/opengl/PlatformCocoaTouchGL.h
filament/backend/src/opengl/PlatformDummyGL.h
filament/backend/src/opengl/PlatformEGL.h
filament/backend/src/opengl/PlatformGLX.h
filament/backend/src/opengl/PlatformWGL.h
filament/backend/src/opengl/PlatformWebGL.h

There is a new static method that can be used by derived classes to
instantiate an OpenGLDriver.
This is to support existing clients that use their own implementation
of OpenGLPlatform with filament's OpenGLDriver implementation.

make OpenGLPlatform semi-public again

---

filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

There will (probably) be a follow-up change that makes this even
simpler.

Fix Vulkan sampler enumeration to be similar to MetalDriver.

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/Program.h
filament/backend/src/vulkan/VulkanBinder.h
libs/filabridge/include/private/filament/EngineEnums.h
libs/filabridge/include/private/filament/SibGenerator.h
libs/utils/include/utils/compiler.h

This fixes two issues related to the Vulkan backend, one being a build
issue and the other being a run-time issue:
(1) Compile-Time Issue
To prevent accidental introduction of padding into hashed structures,
the Vulkan backend was static-asserting the size of the hash input. I
think it's fine to simply use a pragma pack instead.
(2) Run-Time Issue
SibGenerator was erroneuously using BindingPoints::COUNT instead of
UNIFORM_BINDING_COUNT for determining the first sampler binding index.
(Hopefully this logic will go away after some upcoming Vulkan cleanup.)
Since SibGenerator does not include Program, this moves the uniform and
sampler counts into EngineEnums, which might be a good place anyway
since they are ideally "config" constants.

Allow configurable attribute and binding counts.

---

libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/PostprocessMaterialBuilder.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.h
shaders/src/common_types.fs

This is just a cleanup and does not change any behavior. The old code
was a little strange because we'd generate code designed for OpenGL but
we'd pass VULKAN to the code generator. This was a little white lie that
really meant: "I will need SPIRV (for optimization purposes only)"

Rename CodeGenTargetApi to TargetLanguage.

---

filament/backend/src/vulkan/VulkanBinder.cpp
filament/backend/src/vulkan/VulkanBinder.h
filament/backend/src/vulkan/VulkanDriver.cpp
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/SibGenerator.h
libs/filamat/src/shaders/CodeGenerator.cpp

This allows us to start Vulkan sampler bindings at zero, similar
to uniforms. Further cleanup will be implemented in a subsequent pull
request.

MATERIAL BREAK: VulkanBinder now binds 2 descriptor sets at a time.

---

libs/filameshio/include/filameshio/MeshReader.h
libs/filameshio/src/MeshReader.cpp
samples/sample_cloth.cpp
samples/sample_normal_map.cpp
web/filament-js/jsbindings.cpp

Removing STL headers from the filamesh reader. Not sure that the jsbindings were amended correctly. Also still has `<functional>` from the `CString` header using it for `std::hash` specialisation, maybe that could be moved to another header to be included only by internal source files, as `std::hash` should only be used by STL headers anyway? (I think).

Removing STL headers from filameshio

---

web/filament-js/extensions.js

One of the recent releases of emsdk moved its GL-related utility methods
into an object called GL, previously it exposed them directly.
This change also makes it so that we create the WebGL 2.0 context
and register it with emscripten, rather than the other way around.
Note that our CI does "emsdk activate latest", not sure when this broke
exactly.

WebGL fix for "createContext is not a function".

---

android/filamat-android/src/main/cpp/MaterialBuilder.cpp
android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java
docs/Materials.html
docs/Materials.md.html
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/Enums.cpp
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/MaterialInfo.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/filamat/tests/test_filamat.cpp
samples/materials/sandboxLit.mat
shaders/src/common_material.fs
shaders/src/main.fs
tools/matc/src/matc/ParametersProcessor.cpp
tools/matc/src/matc/ParametersProcessor.h

This property can be used to modify the color computed in the lighting
passes of the materials. That color is blended with the computed color
according to the postLightingBlending option (add, transparent or opaque).

Add `postLightingColor` property to materials

---

filament/backend/CMakeLists.txt
filament/backend/src/metal/MetalBufferPool.h
filament/backend/src/metal/MetalBufferPool.mm
filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

Before this change, there was a 1:1 mapping between a Filament uniform buffer and a Metal buffer. This causes conflicts if the CPU attempts to perform a uniform update while the buffer is being used by the GPU. To solve this, the Metal backend now has a pool of buffers which are used to avoid access conflicts along with allowing multiple uniform updates per frame.
`MetalBufferPool` is copied from `VulkanStagePool` with modifications made for Metal.

Add MetalBufferPool to Metal backend

---

filament/src/IndirectLight.cpp

Thankfully, the setRotation() method does work, which provides a
workaround.

uhm, actually set the IBL rotation from the builder

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalEnums.h
ios/samples/hello-pbr/hello-pbr/FilamentApp.cpp
ios/samples/hello-pbr/hello-pbr/FilamentApp.h

There was an issue with shadow maps on iOS (and possibly desktops) because the `storeAction` of the shadow buffer wasn't set correctly. This implements correct load and store actions for render passes.

Add correct Metal load and store actions

---

android/filament-android/src/main/cpp/LightManager.cpp
android/filament-android/src/main/java/com/google/android/filament/LightManager.java
filament/include/filament/LightManager.h
filament/src/ShadowMap.cpp
filament/src/components/LightManager.cpp
filament/src/components/LightManager.h
filament/src/details/ShadowMap.h
samples/material_sandbox.cpp
samples/material_sandbox.h

We were using the view frustum as a basis instead of the shadow 
receivers volume which didn't give a good warping for the scene, we
were working around it by setting a virtual near plane dynamically.
Now that the warping frustum is tight, the virtual near plane is 
no longer needed -- it's still needed for the user to adjust the
precision and the default is still 1m.

fix LISPSM warping frustum computation

---

filament/src/GPUBuffer.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp
filament/src/details/Engine.h
filament/src/details/ShadowMap.h
filament/src/details/View.h
samples/material_sandbox.cpp

Each tile of the checker board corresponds to 8x8 texels in the shadow map.

 debug option to fill the shadowmap with a checkerboard

---

android/filament-android/src/main/cpp/MaterialInstance.cpp
android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java
docs/Materials.md.html
filament/include/filament/MaterialInstance.h
filament/src/Material.cpp
filament/src/MaterialInstance.cpp
filament/src/details/Material.h
filament/src/details/MaterialInstance.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/MaterialInfo.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/gltfio/materials/ubershader.mat.in
libs/gltfio/src/MaterialGenerator.cpp
libs/gltfio/src/UbershaderLoader.cpp
shaders/src/getters.fs
shaders/src/shading_parameters.fs
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

Note that `materialThreshold` was already dynamic, this just makes it a little easier.
The only way in which the `doubleSided` change could impact existing applications is that materials that explicitly set doubleSided to false will now respect the material's culling mode, rather than forcing it to NONE.

Allow dynamic doubleSided and materialThreshold.

---

filament/backend/CMakeLists.txt
filament/backend/src/metal/MetalBufferPool.mm
filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/metal/MetalResourceTracker.cpp
filament/backend/src/metal/MetalResourceTracker.h

This adds a new class, `MetalResourceTracker`, which helps the Metal driver track resources that are used per command buffer.
This also fixes an issue with releasing uniform buffers too early in scenarios such as the following:
**Frame N:**
update uniform
draw
frame completes on GPU
**Frame N + 1**
draw
update uniform
The uniform would be released back into the pool at the time of the second update, which isn't correct. Uniforms need to persist until the end of _each_ frame that utilizes them in a draw call.

Add MetalResourceTracker to Metal backend

---

android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java
android/filament-android/src/main/java/com/google/android/filament/Material.java
docs/Materials.md.html
libs/filabridge/include/filament/MaterialEnums.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/common_lighting.fs
shaders/src/common_material.fs
shaders/src/shading_lit.fs
tools/matc/src/matc/ParametersProcessor.cpp
tools/matinfo/src/main.cpp

This adds a shading model based on KHR_materials_pbrSpecularGlossiness.
The corollary gltfio change will be in an upcoming PR.

Add new shading model to Filament for specularGlossiness.

---

tools/matc/src/matc/ParametersProcessor.cpp
tools/matc/src/matc/ParametersProcessor.h

(1) Merge two same-sized lists into a single map with struct values.
(2) Constify all the string-to-enum maps and move them into the
scope where they are used.
(3) Move a bunch of object methods into static free functions to
simplify the header and reduce code duplication.
(4) The PARAM_KEY_FOO string constants were referenced only once (except
in a few error messages) so replace them with string literals.

Simplify matc.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp

This adds a condition variable to ensure that the wait occurs after the
flush.
Longer term we would like to not use fences to measure frame time and
instead use timing queries.
Fixes #1051.

Fix fence-related Vulkan validation warnings.

---

filament/src/ShadowMap.cpp
filament/src/View.cpp
filament/src/details/ShadowMap.h
libs/filabridge/include/private/filament/UibGenerator.h
samples/material_sandbox.cpp
samples/material_sandbox.h
shaders/src/shadowing.vs

- add normal/constant bias slider to debug ui
- remove sin(x) approximation by sin(x)^2, not worth it.
- fix calculation of constant bias so it works with non-ortho projections
- optimize constant bias calculation out, by backing it into the shadow map

Fix and optimize shadow bias calculation

---

shaders/src/common_lighting.fs
shaders/src/common_material.fs
shaders/src/light_indirect.fs
shaders/src/shading_parameters.fs

The previous clamping used abs(NoV) + EPS which could be much higher
than needed when NoV < -EPS.

Better clamping for dot(N, V)

---

tools/matinfo/src/main.cpp

- Fix the "CString size mismatch" assert seen in debug config.
- Fix the --print-glsl option, which was printing junk.

Some matinfo fixes.

---

filament/include/filament/Box.h
filament/include/filament/Frustum.h
filament/src/Box.cpp
filament/src/Frustum.cpp
filament/src/ShadowMap.cpp
filament/src/details/ShadowMap.h
libs/math/include/math/scalar.h

- switched the frustum/box intersection code to double. With large 
scenes, we were getting very wrong intersection points (up to 1m off).
This doesn't seem to happen with doubles. 
- reject points that end-up outside the frustum
- made LiSPSM code more robust against the problem above. When points
were falsely placed behind the near plane (due to bad intersections),
we could end-up with NaN (sqrt of negative numbers).

Better frustum/box intersection, make code more robust

---

filament/CMakeLists.txt
filament/backend/CMakeLists.txt
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalContext.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalExternalImage.h
filament/backend/src/metal/MetalExternalImage.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/include/filament/Texture.h
filament/src/Texture.cpp

Add external image support to Metal through the `MetalExternalImage` class. A new synchronous driver method, `setExternalImageS` is necessary because the `CVPixelBufferRef ` must be retained on the same thread that `setExternalImage` is called.

Add external image support to Metal backend

---

filament/src/ShadowMap.cpp

We were too aggressive removing vertices resulting from
the triangle/segment intersection test, that were not
contained in the frustum (this invariant should hold).
This happens because our triangle/segment intersection
is not watertight. Removing those vertices entirely would lead
to wrongly reduced light frustum.
Now that the lispsm code is more robust to these invalid vertices,
we can keep them. Most of the time they're harmless, because they're
close to the correct solution.

fix a "shadow disappear" bug introduced recently

---

filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp

Now that generate and execute commands are separate, we don’t need the
setExecuteSync() functionality — it can just be done explicitly when
needed.

simplify RenderPass

---

libs/gltfio/include/gltfio/MaterialProvider.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/MaterialGenerator.cpp
libs/gltfio/src/MaterialProvider.cpp
libs/gltfio/src/UbershaderLoader.cpp

Harmless cleanup. The cutoff value is a uniform and therefore does not
need to be a part of the material configuration structure.

gltfio: remove alpha cutoff from MaterialKey.

---

filament/src/fg/FrameGraph.cpp

It would happen when using a rendertarget without a color buffer and 
a moveResource operation was set. We would incorrectly dereference the
color texture (which didn't exist).

Fix crasher in framegraph

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/OpenGLProgram.cpp

We would leak an FBO when using the same texture with multiple FBOs 
and MSAA, this is because we have to allocate a sidecar FBO in this case
and we were doing so even if it was already existing.
Also store the sidecar fbo with the texture instead of the RenderTarget,
because it has nothing to do with the later. In fact we could have
several textures (e.g. color + depth) who both need a sidecar fbo,
so it can't be stored in the RenderTarget structure.
Also clean-up bindTexture().

fix FBO leak when using MSAA in some cases

---

libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/ResourceLoader.cpp
web/filament-js/extensions.js

This fixes the intermittent bug seen in this screenshot of the helmet demo. This was caused by junk data being uploaded into an index buffer. (free before use)

 Fix intermittent JavaScript bug in gltfio.

---

filament/src/ShadowMap.cpp
shaders/src/shadowing.fs

Found this shadow issue when testing shadows on iOS (which does not have fixed-point depth texture
support).
To reproduce on Mac, set `g_shadowPlane` to `true` in `material_sandbox` and force the depth texture
in `ShadowMap.cpp` to be 32 bit:
```
mShadowMapHandle = driver.createTexture(
-            SamplerType::SAMPLER_2D, 1, format, 1, dim, dim, 1,
+            SamplerType::SAMPLER_2D, 1, TextureFormat::DEPTH32F, 1, dim, dim, 1,
TextureUsage::DEPTH_ATTACHMENT);
```
The fix is to clamp the depth comparison value between 0 and 1. spirv-opt optimizes the `clamp` and
does it only once, even though we may be calling `sampleDepth` multiple times.

 Fix incorrect depth comparisons with floating point depth formats

---

filament/src/Renderer.cpp
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h

Imported render target's discard flags (i.e. the imported flags)
were ignored, which means we were discarding the imported buffer
each time we were drawing into it, especially the 2nd time when
drawing the ImGUI.

Fix a FrameGraph discard bug with imported rendertargets

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

- No need to create a depth buffer automatically for Metal swap chains
- A potential bug when loading shader text if the data isn’t null-terminated
- Check that we've rendered to the default render target before trying to present it at the end of a frame

Slight Metal improvements

---

libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/ResourceLoader.cpp
samples/gltf_viewer.cpp

The cgltf "base path" that gets passed to cgltf_load_buffers should
actually be the path to original glTF file, otherwise bin filepaths
are resolved incorrectly.

gltfio: fix file path bug.

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/DriverBase.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp
filament/src/Texture.cpp
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraphResource.h

We have a new TextureUsage::SAMPLEABLE flag, that is the default,
used for "regular" textures that can be sampled.
When this flag is not set, a RenderBuffer (in GL parlance) is
created instead.
This will be needed in an upcoming PR for creating RenderTarget more
explicitly.

backend textures can now represent a renderbuffer

---

filament/backend/CMakeLists.txt
filament/backend/src/metal/MetalBlitter.h
filament/backend/src/metal/MetalBlitter.mm
filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalExternalImage.h
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/metal/MetalState.mm

Blitting color / depth now supported via the rasterization pipeline. This is to overcome Metal's
native blitting limitations (pixel formats must match, scaling is not allowed). An optimization
might be to opt to use Metal's blitting methods if the limitations are met.

Implement Metal blitting

---

filament/backend/src/metal/MetalHandles.mm

Certain devices, like Intel integrated graphics, don't support the `Depth24Stencil8` format. We'll choose `MTLPixelFormatDepth32Float` instead.

Only use Depth24Stencil8 textures on supported devices

---

web/filament-js/jsbindings.cpp

Both TransformManager::create and VertexBuffer::Builder::attribute were bound incorrectly in jsbindings.cpp, so calling them would cause a crash (VertexBuffer::Builder::attribute would crash if the offset was > 255,  TransformManager::create would always crash).  Corrected bindings so both will work.

Correct JS bindings for 

---

RELEASE_NOTES.md
libs/geometry/src/SurfaceOrientation.cpp

Fix #1158, highlighted by the red triangles in the following images.
I tried a few approaches, the one I settled on happen to work well for the test model below (these are before / after screengrabs).

Improve SurfaceOrientation robustness when using UVs.

---

libs/filagui/src/ImGuiExtensions.cpp
libs/filagui/src/ImGuiHelper.cpp
libs/gltfio/CMakeLists.txt
libs/gltfio/include/gltfio/Animator.h
libs/gltfio/include/gltfio/AssetPipeline.h
libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/Animator.cpp
libs/gltfio/src/AssetPipeline.cpp
third_party/cgltf/cgltf_write.h

AssetPipeline offers a place for doing things like scene flattening,
transform baking, and optimization of glTF assets. These types of scene
manipulations will allow us to tackle lightmap baking in the upcoming
atlasgen tool.
This initial PR includes support for scene flattening, which is fairly
non-trivial. Support for parameterization via xatlas will be added in a
subsequent PR.
In a glTF asset, a single mesh can be referenced by several nodes, and
each reference can have a unique transform. AssetPipeline can flatten
the asset such that each instanced mesh has its own vertex data, and the
node transform gets baked into the vertex data.
Recall that gltfio is composed of two libraries: the core library (no
filamat) and the full library. This adds to the size of the full library
but leaves …

Introduce AssetPipeline for performing glTF manipulations.

---

RELEASE_NOTES.md
android/filamat-android/CMakeLists.txt
android/filamat-android/build.gradle
build.sh
build/common/test_list.txt
libs/filamat/CMakeLists.txt
libs/filamat/README.md
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/PostprocessMaterialBuilder.cpp
libs/filamat/src/sca/GLSLToolsLite.cpp
libs/filamat/src/sca/GLSLToolsLite.h
libs/filamat/tests/test_filamat_lite.cpp

This is the first pass at reducing the size of the `filamat` library. This adds a new target
`filamat_lite`, which has fewer dependencies and a smaller binary size. Its restrictions:
1. Only supports OpenGL backend
1. No material optimizatione
1. No compile-time static analysis of shader code
1. Stricter requirements for setting properties in the `material` function (see
`GLSLToolsLite.h`)
Size reduction:
| Architecture | filamat | filamat_lite | % reduction |
| -- | -- | -- | -- |
| arm64-v8a/libfilamat-jni.so | 5107 KiB | 842 KiB | 16.5% |
| armeabi-v7a/libfilamat-jni.so | 3466 KiB | 462 KiB | 13.3% |
| x86/libfilamat-jni.so | 5358 KiB | 874 KiB | 16.3% |
| x86_64/libfilamat-jni.so | 5547 KiB | 879 KiB | 15.8% |
How including filamat_lite in the filament-jni library affects binary size: …

Add new filamat_lite target to filamat

---

libs/gltfio/CMakeLists.txt
libs/gltfio/include/gltfio/AssetPipeline.h
libs/gltfio/include/gltfio/SimpleCamera.h
libs/gltfio/src/AssetPipeline.cpp
libs/gltfio/src/PathTracer.cpp
libs/gltfio/src/PathTracer.h

AssetPipeline now has a path tracer and optionally uses embree. For now,
the path tracer only sends out visibility rays and generates a simple
hit-or-miss monochrome bitmap. It splits the render target into tiles
and invokes a JobSystem task for each tile.
Filament developers can optionally install embree using homebrew or a
debian package. This avoids bloating third_party and increasing our
build time. If embree is not installed, a friendly run-time error will
occur when attempting to invoke the rendering functionality in
AssetPipeline.
The AO code is not yet implemented, but this PR sets up the
infrastructure, API, and camera rays.

Introduce gltfio::PathTracer and baking API.

---

filament/src/materials/ssao.mat

Normals reconstructed from derivatives at an edge are invalid and 
Cause dark spots in the final AO. We try to detect this case and
Assume no AO, which could be wrong too, but looks better more often.
I don’t think it’ll have an impact on performance because the normals
for the whole quad should be wrong together.

Try to handle “bad” normals

---

RELEASE_NOTES.md
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.h
libs/utils/CMakeLists.txt
libs/utils/include/utils/Log.h
libs/utils/include/utils/ostream.h
libs/utils/include/utils/sstream.h
libs/utils/src/Log.cpp
libs/utils/src/ostream.cpp
libs/utils/src/sstream.cpp
libs/utils/test/test_sstream.cpp

Replace usages of `std::sstream` with our own implementation. This has a huge reduction in the
binary impace of filamat (and filamat_lite). On ARM 64, this reduced the lite version of libfilamat-jni.so from 846 KB to 370 KB (-476 KB).
A few notes:
- Pulled out a new super class, `utils::io::ostream`.
- Added a new class, `utils::io::sstream`.
- The Log class is now `utils::io::LogStream`.
- Added `ostream` buffer resizing.
- Removed the `UTILS_TINY_IO` flag. I think it's safe to assume we always want to use our "tiny IO"
now.
How including filamat_lite in the filament-jni library affects binary size:
| Architecture | Size without filamat_lite | Size increase with filamat_lite | % Size increase |
| -- | -- | -- | -- |
| arm64-v8a/libfilament-jni.so | 750 KiB | +144 KiB | 19.2% |
| …

Remove std::sstream from filamat

---

filament/CMakeLists.txt
filament/src/details/DFG.h

The size of the LUT is now configurable at build-time with -DDFG_LUT_SIZE=XX. It is 128x128 on desktop, 64x64 on Android, WebGL and iOS.
With this new default, the LUT uses 25 KiB per ABI instead of 94 KiB. For further savings a 32x32 LUT can be used (6 KiB).

Use 64x64 DFG LUT on mobile targets

---

samples/sample_full_pbr.cpp
shaders/src/ambient_occlusion.fs
shaders/src/common_lighting.fs
shaders/src/light_directional.fs
shaders/src/light_indirect.fs
shaders/src/shading_lit.fs

Micro-shadowing is derived from ambient occlusion maps and applies to directional lighting. The implementation comes from Chan 2018, _Material Advances in Call of Duty: WWII_. It's an approximation that estimates the visibility cone at any given point based on the local ambient occlusion value.

Add micro-shadowing feature

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

The Metal backend now supports creating MSAA textures and attaching them to render targets. If a
MSAA render target is created with a single-sampled texture, an automatic resolve into the attached
texture at the end of the render pass is performed.

Allow MSAA textures in Metal backend

---

filament/backend/src/opengl/OpenGLDriver.cpp

We now disable the depth test entirely when possible. this should save
a few gl calls.

improve depth test usage and tracking

---

android/samples/image-based-lighting/app/src/main/java/com/google/android/filament/ibl/MainActivity.kt
filament/CMakeLists.txt
filament/src/PostProcessManager.cpp
filament/src/materials/sao.mat
filament/src/materials/ssao.mat
filament/tools/ssaogen.cpp

Both SSAO and SAO are available, but currently only
SSAO can be used.
SAO is more correct and produces less "halos", but
SSAO is sometimes more pleasant.
Note that this doesn't implement all the SAO optimizations
yet.

Use SAO style ambient occlusion

---

docs/webgl/tutorial_redball.html
docs/webgl/tutorial_redball.js
web/docs/tutorial_redball.md
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

JavaScript does not have overloading so we generally use a numeric
suffix to distinguish overloads.
Fixes #1202

jsbindings: add setColor4Parameter and rename setColorParam.

---

android/filament-android/proguard-rules.pro
android/filament-android/src/main/java/com/google/android/filament/Engine.java
android/filament-android/src/main/java/com/google/android/filament/Material.java
android/filament-android/src/main/java/com/google/android/filament/NioUtils.java
android/filament-android/src/main/java/com/google/android/filament/Texture.java
android/filament-android/src/main/java/com/google/android/filament/proguard/UsedByNative.java
android/filament-android/src/main/java/com/google/android/filament/proguard/UsedByReflection.java
java/filament/CMakeLists.txt

Filament references a few classes from native code and by reflections,
so when proguarding binaries we typically had to add an exception for
filament to make it run:
-keep class com.google.android.filament.** {*;}
In a compiled .dex file, the filament namespace takes about 120kb
(before compression), even if the classes aren't used.
To enable proguarding and stripping out unused filament classes,
introduce a UsedByNative and UsedByReflection annotation to explicitly
mark classes that need to be kept in the dex, so that the rest can be
potentially stripped out.
In my testing, this reduces the filament namespace in the .dex from
120kb->40kb, which translates to about 30kb apk size savings after
compression.

Add proguard annotations for code used by native/reflection

---

filament/backend/src/metal/MetalBlitter.h
filament/backend/src/metal/MetalBlitter.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

Implement bliting from MSAA render targets to non-MSAA targets, which also resolves the samples. Also clean up `MetalBlitter` by using preprocessor macros to generate blit shaders on the fly.

Accept MSAA render targets in MetalBlitter

---

filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp

There are now only 2 main commandTypeFlags, COLOR and DEPTH,
indicating if we need to generate respectively COLOR and DEPTH commands.
The command generation code, only has 3 implementations: DEPTH, COLOR and
DEPTH + COLOR.
We also add "options" flags that get passed along, used to control what
goes into the the depth pass -- this because sometimes we don't want
translucent or alpha masked objects. e.g. when rendering the shadow pass,
we want the DEPTH + shadow casters regardless of if they're translucent.
With this, we can fix a SSAO problem where alpha-masked objects where
not participating when the depth pre-pass was used. Now, we add those
objects to the DEPTH if SSAO is active and MSAA is not.

fix ssao issue and rework RenderPass commandTypeFlags

---

filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraphResource.h

It's now possible to set if a render target's attachment is accessed
for read and/or write -- instead of always being hardcoded to both.
We just add an "access" field to Attachment, which is still set to
RW by default, but can be set in useRenderTarget(). 
The access mode only affects building the graph -- in the end it's just
a regular render target.

FrameGraph RenderTarget can now control how they're accessed

---

filament/src/PostProcessManager.cpp
filament/src/materials/sao.mat
filament/src/materials/ssao.mat

Since we have a depth buffer, we might as well use it for depth-culling,
this automatically discards the skybox's fragments -- which we can
assume won't participate in SSAO.

 Use depth culling when computing SSAO

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/RenderPass.h
filament/src/Renderer.cpp
filament/src/materials/sao.mat
filament/src/materials/ssao.mat

- this means that we cannot share the depth pass between ssao and color
passes, so all this code is removed, which simplify things a lot.
- the depth pass code is moved into the ssao codepath since they're now
intimately linked.
- and finals ssao shader can't rely on frameUniform which is set up with
the main buffer's size (instead of 1/4 res).

ssao is now done in quarter resolution

---

filament/src/PostProcessManager.cpp
filament/src/materials/sao.mat
filament/src/materials/ssao.mat

Since we have a depth buffer, we might as well use it for depth-culling,
this automatically discards the skybox's fragments -- which we can
assume won't participate in SSAO.

Use depth culling when computing SSAO

---

libs/utils/src/ostream.cpp

Even when hex modifier is used, 'char' should be printed as characters,
this is particularly relevant with 0.
e.g. out << (char)0, should write a nul terminator, not "0".

fix our ostream << hex << char

---

filament/backend/src/opengl/OpenGLDriver.cpp

This fixes a problem where the min lod of a texture would be set
incorrectly when first drawing into the base level (common case) and
then creating a mipmap chain from it using blits.
Because drawing into the texture doesn't set the base level, after the
blit, the min level would be set to 1 instead of 0.
In fact, there was no way to set the level of a texture by drawing into
it, the only ways were by blitting or uploading data.
This change updates the min/max LOD when a texture level is attached to 
a rendertarget, regardless of whether we read or write -- assuming that
we will write to it. The problem is that at that stage we don't know
if we will read or write. That said, if the user attaches an uninitialized
level to read from it, who cares what really happens

update min/max LOD when using a texture as attachment

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/src/PostProcessManager.cpp
filament/src/Texture.cpp
filament/src/details/Texture.h
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h
filament/src/fg/FrameGraphPassResources.h
filament/src/fg/FrameGraphResource.h
filament/test/filament_framegraph_test.cpp

- Fix wrong assert in createRenderTarget() 
- useRenderTarget() has a helper for simple cases, make it even more
easy to use. It assumes a single color attachment w/ WRITE access,
which is a common case.
- it's now possible to use a level of a texture as an attachment of
a rendertarget in the framegraph, by simply setting the desired level
when specifying an attachment.
- for now, removed the (never used) feature where the framegraph could
resize a resource under-the-hood.
- when requesting the physical renderder target by calling
getRenderTarget(), we now must specify the same level that was used
when the rendertarget was created. This is not ideal, and we hope
to fix that in the future, but it'll require some serious internal
changes (and maybe API changes)

 handle levels of textures in the framegraph 

---

libs/gltfio/include/gltfio/AssetPipeline.h
libs/gltfio/src/AssetPipeline.cpp
samples/gltf_baker.cpp

This preserves original materials but substitutes (or adds) the occlusion texture with generated AO map.  Before baking / after bake for the glTF buggy model shown below.
SSAO is disabled in both screenshots.

Add replaceOcclusion() to AssetPipeline.

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp

It used to be hard-coded, which meant the size SAO radius changed with
the screen resolution.

compute the projection scale properly.

---

filament/backend/include/backend/DriverEnums.h

GCC complains about these enums when the DriverEnums.h header is included
```
filament/out/debug/filament/include/backend/DriverEnums.h:683:36: error: declaration of ‘using CullingMode = enum class filament::backend::CullingMode’ [-fpermissive]
using CullingMode = CullingMode;
^
filament/include/backend/DriverEnums.h:252:12: error: changes meaning of ‘CullingMode’ from ‘enum class filament::backend::CullingMode’ [-fpermissive]
enum class CullingMode : uint8_t {
^~~~~~~~~~~
filament/include/backend/DriverEnums.h:685:40: error: declaration of ‘using BlendEquation = enum class filament::backend::BlendEquation’ [-fpermissive]
using BlendEquation = BlendEquation;
^
filament/include/backend/DriverEnums.h:644:12: error: changes meaning of ‘BlendEquation’ from ‘enum class …
```

Fixed enum scoping in DriverEnums.h to allow compilation with gcc

---

libs/filameshio/src/MeshReader.cpp

Was getting segmentation faults in my test project, due to the current move constructor not nullifying the rhs implementation pointer. This leads to it being deleted when the moved from object is destroyed.
Fix makes sure to nullify the moved from objects implementation pointer.

Fixed the move constructor and assignment operator for MeshReader::MaterialRegistry

---

CMakeLists.txt
README.md
build.sh
build/linux/ci-common.sh

Fixes #1239 
If this works everywhere, we may not need `FILAMENT_REQUIRES_CXXABI` anymore.

Add link_library(libc++.a)

---

filament/backend/include/private/backend/CircularBuffer.h
filament/backend/src/CircularBuffer.cpp

There was typo that prevented the ashmem fallback code to work.
This became briefly a problem on Android Q before we fixed our
use of private APIs.

fix typo in ashmem fallback code

---

libs/gltfio/src/AssetPipeline.cpp

The rubber ducky model has non-uniform scale so it exposed a bug in the flattener. Screenshots below to see the bug and the fix.  :)

AssetPipeline: renormalize after baking transforms.

---

libs/filagui/CMakeLists.txt
libs/filagui/include/filagui/ImGuiMath.h
libs/gltfio/include/gltfio/AssetLoader.h
libs/gltfio/include/gltfio/AssetPipeline.h
libs/gltfio/include/gltfio/SimpleViewer.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/AssetPipeline.cpp
samples/app/FilamentApp.cpp
samples/app/FilamentApp.h
samples/gltf_baker.cpp
samples/materials/aoPreview.mat

This is complete rewrite of the baking UI although the AssetPipeline implementation is largely untouched.
As per the design doc, this makes the app somewhat usable by adding an "export options" dialog box, eliminating hardcoded filenames, removing the hidden state machine, etc.

Overhaul UI for gltf_baker.

---

libs/gltfio/include/gltfio/AssetPipeline.h
libs/gltfio/src/AssetPipeline.cpp
libs/rays/include/rays/PathTracer.h
libs/rays/src/PathTracer.cpp
samples/gltf_baker.cpp
samples/materials/aoPreview.mat

The new normals visualizer reveals why the shader ball is splotchy in one area:

gltf_baker: add more options and visualizations.

---

filament/src/VertexBuffer.cpp

If a client asks for more than 8 buffers in a VertexBuffer, they will
either crash (release) or hit an assert in OpenGLDriver (debug). It's
better to catch this earlier.
This was noticed while investigating #1256.

Additional validation in VertexBuffer::Builder::build.

---

.gitignore
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/ResourceLoader.cpp

Instead of using the actual glTF attribute indices, we now pack them
so that unused indices do not take up any VertexBuffer slots.
Fixes #1256.

gltfio: consolidate buffer slots.

---

libs/gltfio/src/AssetPipeline.cpp
samples/gltf_baker.cpp

My Blender-exported model seems to bake reasonably well now:

Fix baker crash with meshes that already have TEXCOORD_4. 

---

libs/gltfio/include/gltfio/AssetPipeline.h
libs/gltfio/src/AssetPipeline.cpp
samples/gltf_baker.cpp

The shader ball AO was splotchy because of badly located seed points during segmentation. This improves dramatically by allowing the seed heuristic to make a second attempt, as seen in the below before / after montage.

gltf_baker: allow users to adjust to seed iterations.

---

shaders/src/dithering.fs

This eliminates the flicker caused by triangle noise based dithering
when FXAA is turned on. This will require further investigation to
see if we can use triangle noise with FXAA without such artifacts.

Switch desktop to interleaved RGB noise

---

libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/PostprocessMaterialBuilder.cpp
libs/filamat/src/eiff/ChunkContainer.cpp
libs/filamat/src/eiff/ChunkContainer.h
libs/filamat/src/eiff/DictionarySpirvChunk.cpp
libs/filamat/src/eiff/DictionarySpirvChunk.h
libs/filamat/src/eiff/DictionaryTextChunk.cpp
libs/filamat/src/eiff/DictionaryTextChunk.h
libs/filamat/src/eiff/LineDictionary.cpp
libs/filamat/src/eiff/LineDictionary.h
libs/filamat/src/eiff/MaterialSpirvChunk.cpp
libs/filamat/src/eiff/MaterialSpirvChunk.h
libs/filamat/src/eiff/MaterialTextChunk.cpp
libs/filamat/src/eiff/MaterialTextChunk.h
libs/filamat/src/eiff/ShaderEntry.h
libs/filamat/src/sca/GLSLTools.cpp
libs/filamat/src/sca/GLSLTools.h
libs/filamat/tests/test_filamat.cpp

This is the first of a few `MaterialBuilder` refactorings that pave the way for post-process
material domains.
Two main changes:
- Pass shader code directly to `GLSLTools::findProperties`, instead of the `MaterialBuilder`
instance.
- Moved material chunk emission to a separate method. Doing so required some changes in how
`ChunkContainer` temporarily stores chunks before flattening.
Compiled materials are bit-for-bit the same before and after this change.

Refactor MaterialBuilder chunks, findProperties

---

libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/MaterialVariants.h

This changes continues to clean up `MaterialBuilder` in preparation for material domains:
- removes code duplication in shader generation loop by consolidating into `generateShaders` method
- moves variant calculation into separate method, `determineVariants`
Compiled materials are bit-for-bit identical before and after this change.

Refactor MaterialBuilder, remove code duplication

---

filament/backend/src/opengl/OpenGLDriver.cpp

GLVertexBuffer.gl.buffers is a std::array which is not
default-initialized, and createVertexBuffer only initializes the first
bufferCount fields of the array.
When destructing, destroyVertexBuffer iterated over all buffers to unset
bindings, but it was erroneously iterating over the entire array instead
of the initialized values.  Update the loop to only iterate over known
initialized values.

Fix msan use-of-uninitialized-value in destroyVertexBuffer

---

filament/src/RenderPass.cpp
filament/src/Renderer.cpp
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h

Instead of flushing the driver and command queue in RenderPass, we now
do that in the framegraph.
We flush the command queue after each pass -- which reduces memory
pressure on the command queue and improves parallel execution
with the backend thread. We flush the driver only after the last
pass -- maybe we could improve this in the future as the framegraph
gain more knowledge about what's going on.

better command queue flushing

---

android/filament-android/src/main/cpp/Renderer.cpp
android/filament-android/src/main/java/com/google/android/filament/Renderer.java
filament/include/filament/Renderer.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h

"mirror" was misleading, like it would apply a symmetry to the frame.
mirrorFrame() is just a blit from a swapchain to another, so it's a
copy.
The Java language API is kept for compatibility.

rename mirrorFrame() to copyFrame()

---

shaders/src/conversion_functions.fs
shaders/src/tone_mapping.fs

This change also cleans up tone mapping and transfer functions by
getting rid of unused code paths

Add Filmic ALU tone mapping operator

---

libs/gltfio/include/gltfio/MaterialProvider.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/MaterialGenerator.cpp

The bistro model has some UV-free primitives associated with textured materials. This caused Filament to emit warnings like:
[entity=445, primitive @ 0] missing required attributes (0xb), declared=0x3
We now catch these in gltfio, which enables a friendlier warning so that the artist can go make a fix. These new warnings contain the mesh name, e.g.:
Missing UV0 data in Bistro_Research_Exterior_Paris_Building_01_paris_building_01_bottom_4669

gltfio: improve robustness for missing attributes.

---

libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/include/filamat/Package.h
libs/filamat/src/MaterialBuilder.cpp

Two small additional changes to `MaterialBuilder`:
- split `runStaticCodeAnalysis` into `findProperties` and `runSemanticAnalysis`
- add `invalidPackage` convenience method

Split runStaticCodeAnalysis into separate methods

---

filament/src/UniformBuffer.h
libs/filabridge/src/UniformInterfaceBlock.cpp

Arrays in unform buffers are stored in std140, i.e. they have an
alignment of float4. This wasn't taken into account when setting
arrays (other than mat3)

Fix #1270 Inconsistent setParameter behavior for arrays

---

samples/lucy_bloom.cpp
samples/lucy_utils.cpp

By carefully sampling between texel centers during each 1D pass, this achieves a higher quality blur without increasing the number of texture lookups.

lucy_bloom: use LINEAR to reduce texture lookups

---

filament/include/filament/Skybox.h
filament/src/Skybox.cpp
filament/src/View.cpp
filament/src/details/Skybox.h

When there is no indirect light it wasn't possible to control the
skybox's intensity. Now the skybox has its own intensity that
is used in that case.

Fix #477, add a way to set the intensity of the skybox

---

filament/backend/src/opengl/OpenGLDriver.cpp

The bug was reproduced and the fix was verified by making the following
changes to the `lucy_bloom` demo.
Fixes #1300.
```
diff --git a/samples/lucy_bloom.cpp b/samples/lucy_bloom.cpp
index c3a887ca..98f19c53 100644
--- a/samples/lucy_bloom.cpp
+++ b/samples/lucy_bloom.cpp
@@ -87,6 +87,7 @@ static void setup(LucyApp& app, Engine* engine, View* finalView, Scene* finalSce
app.reflection.color = Texture::Builder()
.width(FBO_WIDTH).height(FBO_HEIGHT).levels(1)
+        .sampler(Texture::Sampler::SAMPLER_CUBEMAP)
.usage(Texture::Usage::COLOR_ATTACHMENT | Texture::Usage::SAMPLEABLE)
.format(Texture::InternalFormat::RGBA8).build(*engine);
app.reflection.depth = Texture::Builder()
@@ -96,6 +97,7 @@ static void setup(LucyApp& app, Engine* engine, View* finalView, Scene* finalSce …
```

Fix incomplete FBO when rendering to cubemap.

---

filament/src/View.cpp

Some projections matrices were incorrectly inverted. 
This also fix #1281, fortunately, the incorrect matrix wasn't used
in that case.
Camera::inverseProjection only handles projection matrices it
created (as opposed to custom ones, which is what the shadowmap
code uses)

Properly inverse the projection matrix for the shader

---

android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java

This changes addresses issue #1307. We recently fixed the way we support arrays
of parameters to allow arrays of 1 element. Previously single elements (e.g. float)
were treated as an array of 1 element and the other way around. Unfortunately our
Java bindings relied on this behavior to set colors. This change simply directly
calls the float3 and float4 variants of setParameter() when setting a color.

Fix MaterialInstance Java color bindings

---

libs/gltfio/include/gltfio/AssetLoader.h
libs/gltfio/src/AssetLoader.cpp

**NOTE:** Should we expose `Engine::getEntityManager()` to help with issues like this? e.g. it would allow gltfio to extract it from the engine rather than consuming an additional argument.
This fixes an entity id collision that I saw when building gltfio into its own DSO (e.g. on Android). Since it is a separate executable it has its own EntityManager singleton. This id collision was causing unwanted entities to be added to the scene.

gltfio: allow clients to pass in EntityManager.

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

Implement mipmap selection for Metal render targets. This is in preparation for Metal supporting SSAO, where a chain of depth mipmaps need to be generated.

Add mipmap level selection to Metal render targets

---

libs/math/CMakeLists.txt
libs/math/include/math/half.h
libs/math/tests/test_half.cpp

We introduce a templated fp<> class that can represent any float
format and convert to/from float32.

rework math::half to be more generic

---

shaders/src/shading_lit.fs

This change finds the max of the clear coat and base layer roughness
then lerps the base layer roughness according to the amount of clear
coat.

Don't use clear coat roughness as base roughness if clear coat is 0

---

android/filament-android/src/main/cpp/Texture.cpp
android/filament-android/src/main/java/com/google/android/filament/Texture.java

Clients need this ability in order to use the new RenderTarget API.

Expose texture usage flags to Java / Kotlin.

---

libs/gltfio/CMakeLists.txt

Attempting to create a shared library linking in gltfio results in the following.
/usr/bin/ld.gold: error: /home/joetoth/projects/psycho/third_party/filament/out/release/filament/lib/x86_64/libgltfio.a(MaterialGenerator.cpp.o): requires unsupported dynamic reloc 11; recompile with -fPIC
After adding -fPIC for CXX I then got...
/usr/bin/ld.gold: error: /home/joetoth/projects/psycho/third_party/filament/out/release/filament/lib/x86_64/libgltfio_core.a(stb.c.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
added -fPIC to CMAKE_C_FLAGS fixed this.

Compile gltfio with -fPIC

---

filament/include/filament/Material.h
filament/src/Material.cpp
filament/src/MaterialParser.cpp
filament/src/MaterialParser.h
filament/src/details/Material.h
libs/filabridge/include/filament/MaterialChunkType.h
libs/filabridge/include/filament/MaterialEnums.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
tools/matc/src/matc/ParametersProcessor.cpp

First installment for material domain changes. This adds support for the `domain` keyword in Filament materials and adds a new material domain chunk to material files.

Add material domains boilerplate

---

libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/ResourceLoader.cpp

`ResourceLoader` was assuming that all primitives in the asset have TANGENTS in the same slot.
Fixes #1326.

 gltfio: fix bug with colliding TANGENT buffers.

---

filament/src/Engine.cpp

In commit d955e73 we changed the default IBL from RGBM to RGB, but we
kept its internal format of RGBA8. Since the internal format is not
compatible with the data format, we see GL_INVALID_OPERATION during the
texture upload.
This is a single-pixel black texture, so the format does not really
matter, but this clears up a GL error seen on some platforms.

Fix GL_INVALID_OPERATION in the default IBL.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/MaterialInstance.cpp

Previously we used the <T=float> template instantiation of setParameter
when the client specified FLOAT4. This resulted in the lower layer
adding needless padding, thus causing a buffer overflow.
Moreover the JNI code for this was somewhat cryptic because it casted an
enum value to an int, then added 1 to compute the size. We now use
a switch statement to improve readability.
This issue was discovered (and the fix was verified) with the upcoming
Android port of the bloom demo.

Fix JNI for parameter arrays in MaterialInstance.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/RenderableManager.cpp
android/filament-android/src/main/java/com/google/android/filament/Material.java
android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java

Discussed this feature with Mathias, we decided to create
MaterialInstance Java wrappers on the fly, and create Material Java
wrappers lazily. This is simple and avoids caching the wrapper objects,
which might otherwise lead to complexity and bugs.
Note that gltfio creates material instances behind the scenes, so this
feature is particularly useful for gltfio clients.

Java clients can now get material instances from renderables.

---

libs/filamat/CMakeLists.txt
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/MaterialVariants.cpp
libs/filamat/src/MaterialVariants.h
libs/filamat/src/PostprocessMaterialBuilder.cpp
libs/filamat/src/eiff/ChunkContainer.h
libs/filamat/src/eiff/DictionaryTextChunk.cpp
libs/filamat/src/eiff/DictionaryTextChunk.h
libs/filamat/src/eiff/LineDictionary.h
libs/filamat/src/eiff/MaterialTextChunk.h

- Move the static function declared in MaterialVariants.h to the .cpp
- Fix several use-after-move that were horribly wrong

Fix various errors discovered by clang-tidy

---

third_party/stb/stb.c

This only removes 40k but at least it is easy.

gltfio: Disable file formats that we do not need.

---

ios/samples/hello-ar/hello-ar/FilamentArView/FilamentApp.cpp
ios/samples/hello-ar/hello-ar/FilamentArView/FilamentApp.h
ios/samples/hello-gltf/hello-gltf/FilamentView/App.cpp
ios/samples/hello-gltf/hello-gltf/FilamentView/App.h
ios/samples/hello-pbr/hello-pbr/FilamentApp.cpp
ios/samples/hello-pbr/hello-pbr/FilamentApp.h
libs/image/include/image/KtxBundle.h
libs/image/src/KtxBundle.cpp
samples/app/IBL.cpp

This uses strtof rather than stringstream and provides a common location
that can be leveraged by the upcoming JNI bindings.
Note that this new method lives in KtxBundle rather than KtxUtility. The
latter creates Filament textures and therefore does not get built into
libimage.

Add spherical harmonics parser, reduce code duplication.

---

libs/utils/include/utils/WorkStealingDequeue.h
libs/utils/test/test_JobSystem.cpp

It's better to use std::memory_order_seq_cst in pop() and
steal() because we rely on ordering of access to
mTop and mBottom members.

better comments and potential fix for work-stealing dequeue

---

android/filament-android/src/main/cpp/IndirectLight.cpp
android/filament-android/src/main/java/com/google/android/filament/Asserts.java
android/filament-android/src/main/java/com/google/android/filament/Camera.java
android/filament-android/src/main/java/com/google/android/filament/IndirectLight.java
android/filament-android/src/main/java/com/google/android/filament/LightManager.java
android/filament-android/src/main/java/com/google/android/filament/TransformManager.java
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/IndirectLight.h
filament/src/IndirectLight.cpp
filament/src/details/IndirectLight.h
java/filament/CMakeLists.txt

This change also factors a bunch of assert methods in a single place
which should slightly decrease binary size.

Add missing getter in IndirectLight

---

libs/filabridge/include/private/filament/EngineEnums.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/MaterialVariants.cpp
libs/filamat/src/MaterialVariants.h

Post-process materials will have two variants: opaque and translucent. This PR adds a new function to
calculate post-process variant combinations. The `PostProcessStage` enum will eventually be removed.
Also split `writeChunks` into `writeCommonChunks` and `writeSurfaceChunks`, only writing out surface chunks for surface materials.

Post-process materials: add post-process variant enum, split writeChunks function

---

samples/app/MeshAssimp.cpp

Tested this via material_sandbox, seems to be fine.
Fixes #1366.

Use std::move in MeshAssimp.

---

libs/imageio/src/BlockCompression.cpp

`algorithm` header necessary for `std::min` and `std::max`.

Fix windows build

---

web/filament-js/utilities.js
web/samples/CMakeLists.txt
web/samples/helmet.html
web/samples/suzanne.html

Filament no longer decodes RGBM, so it's better to use a
floating-point format such as R11F_G11F_B10F.

Stop using DXT5 in web samples for the IBL.

---

libs/math/include/math/half.h

math::half is an arithmetic type even on msvc

---

filament/backend/src/opengl/OpenGLDriver.cpp

I noticed that point sprites were working on mobile and web but not
desktop.  This is why.  :)

OpenGL driver: allow point sprites on desktop.

---

filament/src/PostProcessManager.cpp
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/src/UibGenerator.cpp
shaders/src/post_process.vs

The `yOffset` uniform is no longer needed by post-process shaders (it's currently always 0). Previously, post-process passes needed to know the offset because the framebuffer size didn't always match the size of the viewport. Removing it simplifies post-process materials.

Remove unneeded yOffset uniform

---

libs/math/include/math/mat4.h

MSVC doesn't have `M_PI`. We could define `_USE_MATH_DEFINES` and include `math.h`, but IMO just defining `PI` is a cleaner solution given this is a public header file.

Manually define PI to fix MSVC issue

---

RELEASE_NOTES.md
android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java
docs/Materials.md.html
libs/filabridge/include/filament/MaterialEnums.h
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.h
shaders/src/getters.vs
shaders/src/inputs.vs
tools/matc/src/matc/ParametersProcessor.cpp
tools/matinfo/src/main.cpp
web/filament-js/filament.d.ts
web/filament-js/jsenums.cpp

This is a prep step for the upcoming morph feature and does not require
a bump to our material version number.
Stay tuned for a new sample app that demonstrates this feature.

Add support for custom vertex attributes.

---

filament/backend/src/opengl/OpenGLDriver.h

Necessary to call `enable(GL_PROGRAM_POINT_SIZE)`

Handle GL_PROGRAM_POINT_SIZE correctly

---

filament/src/IndirectLight.cpp
libs/ibl/include/ibl/CubemapSH.h
libs/ibl/src/CubemapSH.cpp
tools/cmgen/src/cmgen.cpp

The conversion factors from radiance to irradiance where wrong.
The bug above was found while refactoring the code to be clearer. Now
the method that computes the coefficients for the shader calls the
regular SH code and applies all the appropriate factors on that.
With this change the options`--sh-shader` and `-sh=3 -i` won't
produce the same result because `--sh-shader` includes the lambertian
diffuse. `--sh` now always produces actual SH coefficients.

fix IndirectLight::radiance()

---

libs/ibl/include/ibl/CubemapSH.h
libs/ibl/src/CubemapSH.cpp
libs/ibl/src/CubemapUtils.cpp
tools/cmgen/src/cmgen.cpp

--sh-window=band, -w band : this low-pass-filters the environment
such that bands above 'band' are zero. This can be used to reduce ringing
when the source environment has high frequencies
--noclamp : turns off clamping before processing the cube map
This is still work in progress.

New experimental filtering options to cmgen

---

libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.h

Update `ShaderGenerator` to take a material domain and generate defines based on the post-process material variant.

Pass material domain, variant to ShaderGenerator

---

android/gltfio-android/CMakeLists.txt
build.sh

Note that these are SHARED rather than STATIC dependencies.
Issue #1414.

Add deps to gltfio-android when Vulkan is enabled.

---

libs/math/include/math/TMatHelpers.h
libs/math/include/math/TVecHelpers.h
libs/math/include/math/mat2.h
libs/math/include/math/mat3.h
libs/math/include/math/mat4.h
libs/math/include/math/vec2.h
libs/math/include/math/vec3.h
libs/math/include/math/vec4.h
libs/math/tests/test_mat.cpp
libs/math/tests/test_vec.cpp

It turns out that most of libmath couldn't be used in constexpr
expression due to our use of union{}. The C++ standard requires that
all accesses to a union{} in a constexpr expression be the same
element.
Also because libm and cmath are not constexpr some functions such
as length() or normalize() can't be constexpr. The same is true for
anything needing things like sqrt, cos, sin, ceil, floor.
This change mainly does the following:
- replace all accesses to vector elements by operator[]
(this ensure all of libmath uses the same union element)
- avoid use of std::min / std::max / std::abs
- avoid uninitialized variables, which can't be constexpr
- remove 'constexpr' keyword on functions that can never be
It is now possible to write things like:
constexpr mat4f I = inverse( …

make libmath much more constexpr friendly

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/DriverBase.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/src/VertexBuffer.cpp
filament/src/details/VertexBuffer.h
libs/filabridge/include/filament/MaterialEnums.h

This combines two constants into one, and changes it into a value that
is actually correct.  :)
Technically the movement of the CUSTOM attributes will change the layout
qualifier and therefore merits a materials version bump, however custom
attributes were only recently introduced so this seems unnecessary.
Did some quick testing with 3 samples: gltf_viewer, lucy_bloom, and
point_sprites.

Fix upper limit on vertex attributes. (affects GL)

---

filament/src/Texture.cpp
libs/ibl/include/ibl/CubemapIBL.h
libs/ibl/src/CubemapIBL.cpp
tools/cmgen/src/cmgen.cpp

When processing very high dynamic range environments, the importance
sampling code falls appart, it becomes a user choice to decide if
prefilter importance sampling is better or worse than just regular
importance sampling -- both are usually bad.
--ibl-no-prefilter gives the user this choice.
Importance Sampling
Prefiltered Importance Sampling

added an option to turn off pre-filtering in cmgen

---

filament/src/Material.cpp
filament/src/details/Material.h

This PR splits `getProgramSlow` into two new methods:
- `getSurfaceProgramSlow`
- `getPostProcessProgramSlow`

Update Material class to handle both surface and post-process materials

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/metal/MetalState.h
filament/backend/src/metal/MetalState.mm

This addresses part of the issue raised in #1279 for the Metal backend.
Missing vertex attributes previously resulted in a crash, but now the shader will read 0s from any attributes that aren't set.

Handle missing vertex attributes in Metal backend

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/RenderableManager.cpp
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
docs/Materials.md.html
filament/include/filament/RenderableManager.h
filament/src/Material.cpp
filament/src/RenderPass.cpp
filament/src/Scene.cpp
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
filament/src/details/Scene.h
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/include/private/filament/Variant.h
libs/filabridge/src/UibGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/depth_main.vs
shaders/src/getters.vs
shaders/src/main.vs
tools/matc/src/matc/CommandlineConfig.cpp
tools/matc/src/matc/ParametersProcessor.cpp
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp
web/filament-js/jsenums.cpp

This works by aliasing CUSTOM0 - CUSTOM7 to morphing attributes, and by
extending our existing skinning variant.
This PR was tested against some upcoming changes to gltfio.
Issue #1149, #1417

Filament now supports GPU vertex morphing.

---

filament/src/Scene.cpp

Fix skinning regression (uninitialized bytes in UBO).

---

android/gltfio-android/CMakeLists.txt
build.sh

(1) Sometimes (but not always!) gltfio-android was failing to build due to two missing ANativeWindow functions. Linking in `android` seems to fix this, and is consistent with libfilament-jni.
(2) Improve our `build.sh -c` utility by clobbering some additional Android build directories. This is especially useful after adding `-Pextra_cmake_args=-DFILAMENT_SUPPORTS_VULKAN=ON`, otherwise Gradle will try to use a cached CMake configuration.

Build tweaks for Android.

---

filament/backend/src/vulkan/VulkanDriver.cpp

This fixes one of the bugs seen with `gltf-bloom` on Android.
We already dynamically map Filament's DEPTH24 format to either VK_FORMAT_D32_SFLOAT or VK_FORMAT_X8_D24_UNORM_PACK32, depending on the platform. Therefore we should return `true` when asked if the backend supports DEPTH24. Otherwise the client will not be able to create a depth texture.

Fix VulkanDriver query for the DEPTH24 format.

---

libs/gltfio/CMakeLists.txt
samples/CMakeLists.txt

We now build three gltfio libraries:
- gltfio_core ....... lightweight library with ubershaders
- gltfio ............ uses filamat to generate materials at runtime
- gltfio_pipeline ... depends on path tracer functionality

Desktop samples should not link Embree.

---

filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

VkFramebuffer requires its attachments to have only one miplevel each, but our VulkanRenderTarget wrapper was sharing the VkImageView that is owned by the underlying texture object.
This fixes up VulkanRenderTarget so that it owns a unique VkImageView that is pinned to a specific miplevel.

Vulkan: fix mipmapped render targets.

---

filament/backend/src/opengl/OpenGLDriver.cpp

Avoid enabling scissors when the viewport is the same size as the
buffer. On Adreno devices, running clearWithGeometryPipe adds
three additional unresolves for each bin.

OpenGL: Avoid unresolves on render pass

---

filament/backend/src/opengl/PlatformEGL.cpp
filament/backend/src/opengl/PlatformEGL.h

A prior change that reworked some code incorrectly attempted to
use the existing EGL extensions to set a GL extension boolean.
Added additional GL extension code.

Use GL_EXTENSION for GL_OES_EGL_image_external_essl3

---

filament/src/ShadowMap.cpp
libs/gltfio/src/ResourceLoader.cpp

We should not use the address of a stdlib function for BufferDescriptor
callbacks. With emcc this compiles without warnings or errors, but
produces incorrect code that causes intermittent out-of-memory errors at
run time.

Fix wasm by avoiding the "&free" trick.

---

filament/CMakeLists.txt
filament/src/Engine.cpp
filament/src/Renderer.cpp
filament/src/details/Engine.h
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h
filament/src/fg/ResourceAllocator.cpp
filament/src/fg/ResourceAllocator.h
filament/test/filament_framegraph_test.cpp

Some drivers have performance issues when repeatedly (once per frame)
allocating and destroying render targets, so we will
re-introduce a cache for that.
this just adds the hooks for the cache.

laying the foundations for a rendertarget cache

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.mm

Label command queue for easier debugging when there's multiple contexts.
Add asserts for texture creation failure.

Small improvements to Metal backend

---

filament/backend/src/metal/MetalHandles.mm

This silences the slew of unused variable warnings reported by Metal when compiling shaders.

Silence Metal shader compilation warnings

---

docs/Materials.md.html
filament/src/View.cpp
filament/src/details/Camera.h
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/src/UibGenerator.cpp
shaders/src/common_getters.fs

This allows advanced shader authors like myself to get coordinates in the API level world space.
Fixes #1485.  Here is an animation of a user-defined clip plane:
This example was achieved by adding this to the fragment shader:
```glsl
vec4 wpos = vec4(getWorldPosition() + getWorldOffset(), 1.0);
if (dot(wpos, vec4(.7, .7, .0, -.5)) > .0) {
discard;
}
```

Add getWorldOffset() shader API, enhance docs.

---

filament/src/Engine.cpp
filament/src/Renderer.cpp
filament/src/fg/FrameGraph.cpp
filament/src/fg/ResourceAllocator.cpp
filament/src/fg/ResourceAllocator.h
libs/utils/include/utils/Hash.h

We're only caching textures (not render targets yet), and we're
evicting cache entries older than 30 allocations.
This should cut down on texture allocation / gl calls.
The cache should get in a stable state very quickly (less than half
second).

Implement a basic Texture cache for the framegraph

---

filament/src/fg/ResourceAllocator.cpp
filament/src/fg/ResourceAllocator.h
filament/test/filament_framegraph_test.cpp

because we don't expect many items in the cache, using a linear
search is not a problem -- multimap generates tons of code 
by comparison.

replace multimap by a vector for the framegraph texture cache

---

shaders/src/dithering.fs

This is an improved workaround for a known limitation with Vulkan
drivers on Android P. The offending SPIR-V sequence was introduced
during shader optimization and can be avoided by using full precision
for certain variables.

Better Adreno workaround for #1096.

---

filament/src/components/LightManager.h
filament/src/components/RenderableManager.h
filament/src/components/TransformManager.h
libs/utils/include/utils/SingleInstanceComponentManager.h
libs/utils/include/utils/StructureOfArrays.h

This is because we can't create a constexpr SoA in the first place,
and it wouldn't be very useful if we could.
This change ripples into users of SoA.

most StructureOfArray<> methods cannot be constexpr

---

libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/GLSLPostProcessor.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/PostprocessMaterialBuilder.cpp
libs/filamat/src/eiff/DictionarySpirvChunk.cpp
libs/filamat/src/eiff/DictionarySpirvChunk.h
libs/gltfio/materials/ubershader.mat.in
tools/matc/src/matc/MaterialCompiler.cpp
tools/matinfo/src/main.cpp

This enhances the existing matc option `--debug` so that it enables debug information in the resulting SPIR-V.
Previously we tied this to the build configuration which was not flexible. Moreover this needs to be orthogonal to shader opts, because we often need to debug problems that arise from optimization.
This CL also gives meaningful names to the ubershader materials and fixes up the new matinfo analysis so that it prints the entire SPIRV chunk that corresponds to each potentially problematic GLSL codeline.
Motivated by #1516.

matc, matinfo et al: improve diagnostic output

---

libs/gltfio/src/ResourceLoader.cpp
libs/gltfio/src/Wireframe.cpp

It is not safe to take the address of a stdlib function with emscripten, this causes an intermittent crash in the WebGL backend.

Web: remove more &free callbacks.

---

libs/gltfio/src/MaterialGenerator.cpp
shaders/src/main.vs

I'm perplexed why OpenGL wasn't affected by this, but I believe adding this check to mirror line 39 is this is the right fix..

Fix normal mapping with skinning / morphing in Metal

---

filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

It is valid for Filament to create a uniform buffer but not load any data into it, as long as the
shader does not read from the uniform. Previously, Metal uniform buffers were allocated at the first
data load, but this change "preallocates" a uniform buffer allocation at creation time to handle
this case. It's a Metal validation error to draw with a program that references an unbound uniform
buffer.

Preallocate uniform buffers in Metal

---

filament/backend/src/metal/MetalExternalImage.mm

If the return is taken on line 90, the `NSAutoreleasePool` will be leaked.

Fix potential Metal memory leak

---

RELEASE_NOTES.md
filament/CMakeLists.txt
filament/src/Engine.cpp
filament/src/Material.cpp
filament/src/details/Engine.h
libs/filaflat/include/filaflat/ChunkContainer.h
libs/matdbg/CMakeLists.txt
libs/matdbg/include/matdbg/DebugServer.h
libs/matdbg/src/DebugServer.cpp
libs/matdbg/src/JsonWriter.cpp
libs/matdbg/web/index.html
libs/matdbg/web/script.js
libs/matdbg/web/style.css
tools/matinfo/src/main.cpp

This also links matdbg into the Filament Engine in debug config (allowing live inspection of raw shader code) and the matinfo tool (to support the `--web-server` option).
In both cases, the library spins up a small web server that listens to http://localhost:8080. You can run any Filament app and attach to it.
The web client caches all material information. This allows the user to close an atttached Filament app, and the web app will continue to function properly (useful for crash diagnosis). Moreover the user can launch a second Filament app and the web client will add its materials to the existing list (useful when comparing two Filament apps).
For now this only supports inspection, not editing. Some of the material info such as required attributes is not yet displayed but this will be …

matdbg: add the DebugServer.

---

filament/backend/CMakeLists.txt
filament/backend/include/private/backend/BackendUtils.h
filament/backend/src/BackendUtils.cpp
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/vulkan/VulkanUtility.cpp
filament/src/Texture.cpp

Drivers shouldn't be depending on details/Texture.h, especially not when it's only for a single, straightforward function. This moves the `getFormatSize` implementation to a new `BackendUtils.h` file.

Break driver dependency on Texture.h

---

filament/backend/src/opengl/OpenGLDriver.h
filament/src/Froxelizer.cpp
filament/src/details/Allocators.h
libs/utils/include/utils/Allocator.h
libs/utils/src/Allocator.cpp

This can be enabled by using the Tracking::Debug policy,
currently this just fills allocation on alloc() and free(),
which is useful to help detect access to uninitialized memory
and use after free.
Now enabled by default in libfilament allocators on debug builds.
This caught uninitialized access in the froxelizer.

simple allocation debugger

---

filament/CMakeLists.txt
filament/src/PostProcessManager.cpp
filament/src/Renderer.cpp
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h
filament/src/fg/FrameGraphHandle.h
filament/src/fg/FrameGraphPassResources.h
filament/src/fg/ResourceAllocator.cpp
filament/src/fg/ResourceAllocator.h
filament/src/fg/fg/PassNode.h
filament/src/fg/fg/RenderTarget.cpp
filament/src/fg/fg/RenderTarget.h
filament/src/fg/fg/RenderTargetResource.h
filament/src/fg/fg/ResourceNode.h
filament/test/filament_framegraph_test.cpp

The major change here is that declaring render targets now returns a `FrameGraphRenderTargetHandle` later used to retrieve the concrete render target. Before this change, one of its attachment had to be used. This was confusing and complexified the implementation.
Other changes:
- the sample count when declaring render targets for the 2nd time doesn't need to be specified,
the framegraph will just reuse the previous sample count.
- also, no need to specify the sample count for attachments, it'll be set automatically from the
sample count of the render target.
- use .sample() instead of .read() when the intention is to sample from a texture (as opposed to using it as a renderbuffer for instance).

Improve framegraph API and simplify implementation

---

filament/src/Engine.cpp
filament/src/Material.cpp
filament/src/details/Material.h

This only adds Engine-side support for edits. The debugger client will
be enhanced in another PR. This works by simply clearing the program
cache and swapping out the MaterialParser. Neat!
However, there are some gotchas:
- The DebugServer callback is triggered on another thread so to be safe
we defer the swap until the subsequent call to getProgram().
- The getProgram() method is const but in reality it can insert entries
into a mutable cache. This CL makes the constness of it even more
misleading by applying edits.

Engine: add support for material edits.

---

filament/backend/src/opengl/GLUtils.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLProgram.cpp

We now check for FILAMENT_ENABLE_MATDBG and simply skip the draw call
when the program is invalid. The initial error message is still dumped
to the console, but we will not terminate or dump an infinite cascade of
error messages.

OpenGL: shader errors should not cause termination.

---

RELEASE_NOTES.md
libs/matdbg/CMakeLists.txt
libs/matdbg/include/matdbg/DebugServer.h
libs/matdbg/include/matdbg/ShaderExtractor.h
libs/matdbg/include/matdbg/ShaderReplacer.h
libs/matdbg/src/DebugServer.cpp
libs/matdbg/src/ShaderExtractor.cpp
libs/matdbg/src/ShaderReplacer.cpp
libs/matdbg/web/script.js
tools/matinfo/src/main.cpp

This performs surgical modification of the IFF chunks rather than
invoking filamat from within matdbg. Low-level direct manipulation
(bypassing optimization passes etc) allows us to diagnose issues with
the shading pipeline.
This CL also adds keystroke bindings to the Monaco editor. You can
press Cmd+S to rebuild the current materials, or use Ctrl+Arrow to
navigate between shader variants and materials.
In a subsequent CL I will add a README that describes how this works in
detail, it will include a list of limitations and a feature wishlist.

matdbg: allow live editing for GLSL shaders.

---

filament/backend/include/private/backend/DriverAPI.inc

by using variadic macros we can greatly simplify the macros
definitions for declaring the backend API.
in particular we don't need a macro per number-of-argument, this is
now done automatically.
Unfortunately, we still can't handle zero-argument declarations, so
we keep the _0 variants.

simplify DriverAPI.inc macros

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h

some driver don't support all float buffers as rendertarget, so we
improve the backends (opengl in this PR) to return what it actually
supports and we update the client (filament) to take that into
account when making decisions.
fixes #1533

better handle float rendertargets

---

libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp
web/filament-js/extensions.js
web/filament-js/jsbindings.cpp
web/samples/helmet.html

Some buffers (like animation data) do not contain any vertex data but web-based clients still need to know about them.
This interface is much simpler than the bindings lists, and in fact we might remove the binding lists in the future to simplify the API.
Fixes #1593.

gltfio: expose all resource URI strings.

---

.github/workflows/presubmit-ios.yml
.github/workflows/presubmit.yml

For some reason, the iOS GitHub action is failing when it tries to make an archive. We can deal with that problem later; for now, we can ensure PRs trigger a "presubmit" job (with no archive generation), which they weren't because env vars are case sensitive.

Ensure GitHub actions target presubmit

---

libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.h
shaders/CMakeLists.txt
shaders/src/post_process.vs
shaders/src/post_process_getters.vs
shaders/src/post_process_inputs.fs
shaders/src/post_process_inputs.vs

Support custom vertex shaders in post-process materials:
```
vertex {
void postProcessVertex(inout PostProcessVertexInputs postProcess) {
vec4 position = getPosition(); // clip-space
postProcess.customVariable.xy = (position.xy * 0.5 + 0.5);
}
}
```

Add custom vertex shaders for post-process materials

---

tools/resgen/src/main.cpp

Previously, whenever we changed a resource (e.g. a shader), we would need to re-compile and re-link. This makes it so that it incurs only a re-link.
Before this, changing `sandboxLit.mat` incurred a 30-second release build (single job), this change reduces it to 8 sec.

Use resgen to make builds faster.

---

tools/resgen/src/main.cpp

Minor simplification: remove the unused, confusing, and incorrect constant that was meant to represent the sum of all resource sizes.

resgen: remove unused / incorrect constant.

---

filament/src/PostProcessManager.cpp

The suzanne Vulkan demo was asserting because `setViewportScissor` can
only be called within a render pass, which means that
`MaterialInstance::use` can only be called within a render pass.
We probably need a better way to enforce these rules...

PostProcessManager: repair Vulkan by re-ordering commands.

---

build.sh
ios/samples/README.md

This hopefully fixes the iOS GitHub Action. The install was always being done, which fails (maybe due to lack of space on the CI machine?). If this is the case, then we'll need to revisit for release builds (which require an install / archive).

Only install iOS builds if requested

---

filament/CMakeLists.txt
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/materials/fxaa.mat
libs/filabridge/include/private/filament/UibGenerator.h

Convert the FXAA to a post-process material. This also removes:
- `setSource` method, which isn't needed anymore
- The `uvScale` uniform, which was always 1.0

Use post-process material domain for FXAA

---

filament/src/Engine.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
libs/filabridge/include/private/filament/EngineEnums.h
libs/filabridge/include/private/filament/SibGenerator.h
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/src/SamplerBindingMap.cpp
libs/filabridge/src/SibGenerator.cpp
libs/filabridge/src/UibGenerator.cpp
libs/filamat/src/PostprocessMaterialBuilder.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/dithering.fs
shaders/src/post_process_old.fs
shaders/src/post_process_old.vs

This removes "old" post-process uniforms and samplers. The new post-process materials don't need them, as they use `PER_MATERIAL_INSTANCE` ones. Dithering uses the `time` uniform, which it now gets from `frameUniforms`.

Remove post-process uniform / sampler blocks

---

filament/backend/include/backend/PipelineState.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/PostProcessManager.cpp
filament/src/RenderPass.cpp
filament/src/details/MaterialInstance.h

setViewportScissor is gone, which will avoid a runtime error if
called outside of begin/endRenderPass, making the driver API more
robust.

scissor is now part of PipelineState

---

filament/src/Engine.cpp
filament/src/materials/blur.mat
filament/src/materials/fxaa.mat
filament/src/materials/sao.mat
filament/src/materials/ssao.mat
filament/src/materials/tonemapping.mat
shaders/src/post_process.vs
shaders/src/post_process_getters.vs
shaders/src/post_process_inputs.vs

If you tried removing `culling: none` from any post-process materials, everything would be fine in GL but Vulkan would be black because our full-screen triangle was back-facing.
Usually this did not manifest as a discernible issue because tex coords were also flipped.

Fix full-screen triangle winding.

---

filament/backend/CMakeLists.txt
filament/backend/src/opengl/OpenGLBlitter.cpp
filament/backend/src/opengl/OpenGLBlitter.h
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/OpenGLProgram.cpp
filament/backend/src/opengl/OpenGLProgram.h
filament/backend/src/opengl/PlatformEGL.cpp

We now have OpenGLContext which only tracks the OpenGL state.
It exposes an API very similar to OpenGL and does all the state
tracking. Currently, it doesn't expose non state-changing APIs 
(e.g. draw methods) and only implements the state-changing API we
need (to track the state of).

Split OpenGLDriver in two files

---

libs/math/include/math/TMatHelpers.h
libs/math/include/math/fast.h
libs/math/include/math/mat2.h
libs/math/include/math/mat3.h
libs/math/include/math/mat4.h
libs/math/include/math/quat.h
libs/math/include/math/vec2.h
libs/math/include/math/vec3.h
libs/math/include/math/vec4.h

This is nicer because this way the methods that don't match don't
even exist. Also make it better when editing code with a C++ aware
ide.
Also use the less verbose `std::enable_if_t<>`

use enable_if<> instead of static_assert()

---

filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Scene.cpp
filament/src/details/Scene.h
libs/math/include/math/TMatHelpers.h

We now inverse the face winding order based on the determinant of
each render primitive world's transform. This prevents front/back faces
to be reversed when using a left-handed basis, after transform.
Fix #1520

handle basis inverting transforms (e.g. planar symmetries)

---

filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanFboCache.h
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

We now use GENERAL layout for depth-sampled images in order to support
the SSAO use case of simultaneous binding + sampling.
We may be able to optimize this in the future by enhancing DriverAPI
so that it feeds more information into the render pass.
Fixes #1627, #1649.

Vulkan: fix layout and miplevel for depth attachments.

---

filament/src/View.cpp
libs/utils/include/utils/Entity.h

use double for the shader's 'second' time calculation, since 1 billion cannot be stored
in a float accurately.

Fix minor time calculation imprecision

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.mm

Fixes #1525
`mesh_bone_indices` is a special vertex attribute (it's uvec4, as opposed to vec4). If a renderable
doesn't provide the attribute, we read from a faux vertex buffer called the "zero buffer". The
vertex format still needs to be specified as `MTLVertexFormatUInt4`, otherwise Metal errors.
This is a hack for now—we've discussed the idea of programatic vertex pulling as a potential future
workaround.

Fix, allow missing bone indices vertex attribute in Metal driver

---

libs/math/include/math/TMatHelpers.h
libs/math/include/math/TVecHelpers.h
libs/math/include/math/mat2.h
libs/math/include/math/mat3.h
libs/math/include/math/mat4.h
libs/math/include/math/quat.h
libs/math/include/math/vec2.h
libs/math/include/math/vec3.h
libs/math/include/math/vec4.h
libs/math/tests/test_mat.cpp
libs/math/tests/test_vec.cpp

We now follow the same rules than for basic types, when performing
mixed-precision operations, e.g.:
float3 + double3 -> double3
double3 + float3 -> double3
dot(float3, double3) -> double
In particular, e.g. swapping the arguments to arithmetic operations
now always yields to the same result type (before, float3 + double3
would not return the same type than double3 + float3).

improve mixed-precision vector operations

---

filament/docs/doxygen/filament.doxygen
libs/filamat/include/filamat/IncludeCallback.h
libs/filamat/include/filamat/MaterialBuilder.h

This simply updates the `MaterialBuilder` documentation to be compatible with Doxygen. I'll make another pass to flesh out the documentation and make it consistent.

Update MaterialBuilder header comments for Doxygen

---

filament/backend/include/backend/BufferDescriptor.h
filament/backend/include/backend/DriverEnums.h
filament/backend/include/backend/Handle.h
filament/backend/include/backend/PipelineState.h
filament/backend/include/backend/PixelBufferDescriptor.h
filament/backend/include/backend/TargetBufferInfo.h
filament/docs/doxygen/filament.doxygen
filament/include/filament/LightManager.h
filament/include/filament/RenderTarget.h
filament/include/filament/TextureSampler.h
filament/src/RenderTarget.cpp

We need to document the backend headers that are public. 
Added documentation for:
- DriverEnums.h
- BufferDescriptor.h
- PixelBufferDescriptor.h
Disabled doxygen for public headers of backend that don't need to
be public for filament's API.
Also improved documentation for:
- LightManager.h
- RenderTarget.h
- TextureSampler.h

Improve backend documentation

---

android/filamat-android/build.gradle
android/filament-android/build.gradle
android/gltfio-android/build.gradle
android/samples/gltf-bloom/app/build.gradle
android/samples/hello-triangle/app/build.gradle
android/samples/image-based-lighting/app/build.gradle
android/samples/lit-cube/app/build.gradle
android/samples/material-builder/app/build.gradle
android/samples/texture-view/app/build.gradle
android/samples/textured-object/app/build.gradle
android/samples/transparent-view/app/build.gradle

Android Q (API 29) is now out and it's good practice to compile and target the latest API level to verify behavior.

Update compile & targetSdk from 28 to 29

---

libs/math/include/math/compiler.h
libs/math/include/math/quat.h
libs/math/include/math/vec2.h
libs/math/include/math/vec3.h
libs/math/include/math/vec4.h
libs/math/tests/test_vec.cpp
libs/utils/include/utils/algorithm.h

the C++ standard says:
if T is a class type with a default constructor that is neither 
user-provided nor deleted (that is, it may be a class with an
implicitly-defined or defaulted default constructor), the object 
is zero-initialized and then it is default-initialized if it has a 
non-trivial default constructor
Unfortunately, MSVC always calls the default constructor, even if it 
is trivial, which breaks constexpr-ness. 
To workaround this, we're always zero-initializing TVecN<>
Also removed constexpr from default constructors, since they never can
be constexpr as they're not initializing the vector.

workaround an MSVC bug with brace initialization

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/SamplerGroup.h
filament/backend/src/metal/MetalBlitter.mm
filament/include/filament/TextureSampler.h
filament/src/PostProcessManager.cpp

This is to allow designated aggregate initialization in C++20.
We do this because we have been relying on C99 designated
initialization, which is only supported by clang, other compilers need
c++20 to get a similar functionality. Therefore, we now try to limit
Ourselves to C++20 rules.
This could break existing code, since now SamplerParams needs to be
zero-initialized:
SamplerParams p{};
This is generally not an issue because the intended use is:
doSomethingWithSamplerParams({
.filterMag = LINEAR,
});

SamplerParams is not default-initialized anymore

---

libs/math/include/math/TQuatHelpers.h
libs/math/tests/test_quat.cpp

The last codeline in our `slerp` implementation was checking if `d < 0`, but it was always false.
Verified with a unit test and with the gltf file that's in the bug description.
Fixes #1716.
This regressed in c65e561c59c70fdf2f960823ea15ecef5b5b1bfe.

Fix quat slerp so it takes shortest path.

---

tools/matinfo/src/main.cpp

Fix, matinfo doesn't work on Windows

---

filament/src/Camera.cpp
filament/src/IndirectLight.cpp
filament/src/components/LightManager.cpp
filament/test/filament_test.cpp
filament/tools/ssaogen.cpp
libs/bluevk/CMakeLists.txt
libs/bluevk/tests/test_bluevk_sdl.cpp
libs/filagui/src/ImGuiExtensions.cpp
libs/ibl/src/CubemapIBL.cpp
libs/ibl/src/CubemapSH.cpp
libs/ibl/src/CubemapUtils.cpp
libs/image/src/ImageSampler.cpp
libs/math/benchmarks/benchmark_fast.cpp
libs/math/include/math/fast.h
libs/math/include/math/scalar.h
libs/math/tests/test_fast.cpp
libs/math/tests/test_mat.cpp
libs/math/tests/test_quat.cpp
libs/math/tests/test_vec.cpp
libs/rays/src/PathTracer.cpp
tools/skygen/src/main.cpp
tools/specular-color/src/main.cpp

These constants are not part of the standard and not guaranteed to be part of `math.h`.
We instead use our own constexpr definitions in the filament::math namespace, as part of
the scalar.h include. To avoid conflicts, our definitions are named `F_*` instead of `M_*`.

Use our own constants instead of M_PI, M_*, etc.

---

filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/src/VertexBuffer.cpp

The vertex shader in the material variant for skinning-and-morphing
declares a `uvec4` attribute that can be unused and disabled, but still
needs to be typed correctly.
The fix is motivated by WebGL, but the issue might occur with other
OpenGL implementations that have strict drivers.
Fixes #1726

OpenGL driver: fix error with uvec4 attribs, clean up Vulkan/Metal.

---

filament/src/Engine.cpp
filament/src/IndexBuffer.cpp
filament/src/IndirectLight.cpp
filament/src/Material.cpp
filament/src/RenderTarget.cpp
filament/src/Skybox.cpp
filament/src/Stream.cpp
filament/src/Texture.cpp
filament/src/VertexBuffer.cpp
filament/src/components/LightManager.cpp
filament/src/components/RenderableManager.cpp
filament/src/details/Engine.h

We now assert if the Engine given is invalid,
which would happen if it was used after being
destroyed.
Builder::build() is a reasonable place for this since it's generally
not in the critical path.

validate Engine in all Builder::build() methods

---

libs/math/include/math/mat2.h
libs/math/include/math/mat3.h
libs/math/include/math/mat4.h
libs/math/include/math/vec2.h
libs/math/include/math/vec3.h
libs/math/include/math/vec4.h

this gets rid of a few ide-warnings about static initialization of
arrays with math types.

noexcept-ize libmath a bit more

---

filament/src/MaterialInstance.cpp

`mCulling` wasn't being set if the `initDefaultInstance` code path is taken.

Fix culling in MaterialInstance

---

libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/ResourceLoader.cpp

Sparse accessors are easy to punt gracefully, we can emit a warning
and instead use the dense "base" data.
Also, after cgltf support for this lands, we will need to apply sparse
data in ResourceLoader, so this adds a bit of plumbing to prep for that.
Relates to #1727.

gltfio: do not abort for sparse data, warn instead.

---

libs/math/include/math/TQuatHelpers.h
libs/math/tests/test_quat.cpp

libmath: prevent NaN's in slerp due to acos.

---

libs/math/CMakeLists.txt
libs/math/include/math/TMatHelpers.h

- we use by-value parameters in some places, which helps the compiler
(not sure why, but assuming references can be aliased and the
compiler is cautious about that).
This helps matrix multiplies (which is almost never inlined) and
transpose (but that's almost always inlined and merged with
something else, so the gain here is not completely real)
- remove support for matrices-of-matrices because this wasn't complete
anyways.
- improve matrix * scalar by inlining the loop manually instead of
going through *=, this saves some extra writes.

some optimizations to the math code

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/gl_headers.cpp
filament/backend/src/opengl/gl_headers.h

There's no longer a need to fake ES 3.1 support, the OpenGL driver supports iOS's ES 3.0 now (with one tiny define necessary).

Remove iOS OpenGL ES 3.1 hack

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

We were getting Xcode assertions like the following when rendering skinned meshes:
```
validateFunctionArguments:3478: failed assertion `Vertex Function(main0): argument bonesUniforms[0] from buffer(2) with offset(0) and length(64) has space for 64 bytes, but argument has a length(16384).
```
Filament materials have a bones UBO that can hold the _max_ number of bones, but when Filament loads data into the bones uniform, it often loads far less data for meshes that have less than the _max_ count of bones. The Metal backend was allocating a buffer smaller than the full UBO size, hence the Xcode assertion.

Fix assertion using bones with Metal backend

---

filament/src/Engine.cpp
filament/src/details/Engine.h
filament/test/filament_test.cpp

We were destroying the engine manually (by calling delete) which is
not allowed.
Also made FEngine::shutdown() private.

fix a double-free when exiting the FroxelData test

---

filament/src/components/TransformManager.cpp

during a transaction, it makes no sense iterating through all
children just so that we can iterate through their children...
and do nothing else.

remove unneeded loop in TransformManager

---

RELEASE_NOTES.md

Let me know if I've missed anything!

Update RELEASE_NOTES for v1.4.1

---

filament/backend/src/noop/NoopDriver.cpp

Mobile shader model is GL_ES_30 instead of GL_CORE_30 - renaming in Noop backend.

Fix typo in Noop on mobile.

---

android/filament-android/src/main/java/com/google/android/filament/Box.java
android/filament-android/src/main/java/com/google/android/filament/Colors.java
android/filament-android/src/main/java/com/google/android/filament/MathUtils.java
java/filament/CMakeLists.txt

This also adds MathUtils to the desktop JNI bindings, which was missing (unless this was done on purpose?)

Add Javadoc for Colors, Box, and MathUtils

---

filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/gl_headers.cpp
filament/backend/src/opengl/gl_headers.h

This extension dumps out some interesting vendor-specific information
to the log, which could be useful for debugging. Interestingly, some
of Android demos produce this output on Pixel 3:
```
KHR_debug: EsxBufferObject::Map - Ignoring EsxBufferMapUnsyncedBit
```
Enabled for debug builds only.

OpenGL Driver: add support for KHR_debug.

---

README.md

Issue #1770 mentioned difficulty in understanding which CMake variables belong to Filament when using the CMake GUI. This adds a section to our README that lists all of our Filament-specific ones.
We could consider prefixing all of these with `FILAMENT_` to make it obvious which options are Filament's.

Add README section on Filament CMake options

---

shaders/src/common_shading.fs
shaders/src/getters.fs
shaders/src/shading_parameters.fs

If we assume the tangents and bitangents were generated using mikktspace,
we should use the unnormalized vectors, as indicated at mikktspace.com
or in http://www.metalliandy.com/mikktspace/downloads/mikktspace/mikktspace.h
(see last comment at the end of the file).

Use unnormalized vectors to compute bump mapping.

---

filament/src/Engine.cpp
filament/src/IndexBuffer.cpp
filament/src/IndirectLight.cpp
filament/src/Material.cpp
filament/src/RenderTarget.cpp
filament/src/Skybox.cpp
filament/src/Stream.cpp
filament/src/Texture.cpp
filament/src/VertexBuffer.cpp
filament/src/components/LightManager.cpp
filament/src/components/RenderableManager.cpp
filament/src/details/Engine.h

This enhances the assert added in 2548da9 in the following ways:
- Adds console output at startup to help detect "double load" bugs.
- Adds PRETTY_FUNCTION to show where the invalid usage is coming from.
- Tweaks the wording since use-after-destroy is not always the cause.
- Consolidates usage of static globals into a helper class.
Motivated by #1811.

Minor improvements to Engine validation.

---

android/filament-android/CMakeLists.txt
android/gltfio-android/CMakeLists.txt
android/samples/gltf-bloom/app/src/main/java/com/google/android/filament/gltf/MainActivity.kt

Filament keeps a global static list of engines for verification purposes which was being recreated multiple times, causing a panic in our gltf demo. After a lot of experimentation with the build, the only way to avoid the double-init is to statically link filament into gltfio-jni, and ask clients to load only that.  Dynamically loading both libraries separately seems to be problematic due to their interdependency.
Fixes #1811.

gltfio-jni: Fix double-initialization panic.

---

CMakeLists.txt

Optimized macOS builds can trigger "stack_not_16_byte_aligned_error"
when building with clang 11. We happen to see this with resgen but it
could happen anywhere.
https://forums.developer.apple.com/thread/121887
Fixes #1823

Work around unaligned stack with clang 11.

---

libs/gltfio/src/AssetLoader.cpp

We honored node-level defaults but not mesh-level.
Fixes #1840.

gltfio: support mesh-level morph weights.

---

android/filament-android/src/main/cpp/Renderer.cpp
android/filament-android/src/main/java/com/google/android/filament/Renderer.java
filament/include/filament/Renderer.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h

Before it was limited to reading back from the SwapChain.

Renderer::readPixels() can now read back from a RenderTarget

---

android/filament-android/src/main/cpp/Engine.cpp
android/filament-android/src/main/java/com/google/android/filament/Engine.java
android/filament-android/src/main/java/com/google/android/filament/SwapChain.java
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/include/private/backend/OpenGLPlatform.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/PlatformCocoaGL.h
filament/backend/src/opengl/PlatformCocoaGL.mm
filament/backend/src/opengl/PlatformCocoaTouchGL.h
filament/backend/src/opengl/PlatformCocoaTouchGL.mm
filament/backend/src/opengl/PlatformEGL.cpp
filament/backend/src/opengl/PlatformEGL.h
filament/backend/src/opengl/PlatformGLX.cpp
filament/backend/src/opengl/PlatformGLX.h
filament/backend/src/opengl/PlatformWGL.cpp
filament/backend/src/opengl/PlatformWGL.h
filament/backend/src/opengl/PlatformWebGL.cpp
filament/backend/src/opengl/PlatformWebGL.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/include/filament/Engine.h
filament/src/Engine.cpp
filament/src/SwapChain.cpp
filament/src/details/Engine.h
filament/src/details/SwapChain.h
filament/test/CMakeLists.txt
filament/test/filament_rendering_test.cpp

This is useful for unit tests. The content of the swapchain can be
read to main memory with Renderer::readPixels().
This PR doesn't implement this new feature in the following backends and
platforms (TODO):
VulkanDriver.cpp
MetalDriver.mm
PlatformWGL.cpp
PlatformWebGL.cpp
PlatformCocoaGL.mm
PlatformCocoaTouchGL.mm

Implement Headless SwapChain mode.

---

android/filament-android/src/main/java/com/google/android/filament/Texture.java
filament/backend/include/backend/BufferDescriptor.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/src/Engine.cpp

This doesn't change the user facing API because it already used a
callback.
With this change we implement readPixels() with a PBO, which won't
stall the GPU. Then we periodically check a fence to see when the
command is completed, at which point we map the PBO and copy the data
to the user buffer.

Make filament's readPixels() asynchronous wrt the GPU

---

libs/utils/include/utils/algorithm.h
libs/utils/test/test_algorithm.cpp

This was caught by ASAN.
Our algorithm header has many one-liners that compute the "next power of
two length / 2" but they all have the caveat that if the input is
already POT, then the "/ 2" part does not occur.
Usually we deal with this by testing the difference against zero.
However in `partition_point` we were skipping the test, thus causing a
potential out-of-bounds access.
I fixed `partition_point` and added a few more tests for non-POT cases.

Fix out-of-bounds in an [unused] utility.

---

RELEASE_NOTES.md
filament/src/UniformBuffer.h
filament/test/filament_test.cpp
libs/filamat/tests/test_filamat.cpp

Clients who do not yet have this fix can usually work around this issue
by calling the non-array overload of `MaterialInstance::setParameter`
when the array size is 1.

Fix an assert when the last uniform is an array.

---

filament/src/Scene.cpp
filament/src/details/Allocators.h
libs/utils/include/utils/Allocator.h
libs/utils/src/Allocator.cpp
libs/utils/test/test_Allocators.cpp

TrackingPolicy::Debug didn't store the base pointer of the Area, and
instead relied on the first allocation to discover it, however, because
of alignment, the first allocation may not match the base pointer.
Because of that there could be an overflow in onRewind(), i.e. we
could rewind to a pointer before the (wrongly computed) base. This
overflow caused the debug memset to go awry and stomped on memory.
This is fixed by passing the base pointer to the constructor of the
TrackingPolicy. This base pointer could be nullptr with certain
allocators, but in that case, onReset/onRewind should never be called;
and this is enforced at compile time.
Also fixed a (luckily) harmless buffer overflow when preparing the
dynamic lights, if the number of lights wasn't a multiple of 4. This
was harmless …

fix a possible memory corruption in debug builds

---

build/common/test_list.txt

This is currently causing continuous tests to fail when running in CI. Let's temporarily disable until we can investigate.

Disable RenderingTest from CI test suite

---

filament/src/Renderer.cpp

When using the OpenGL backend, updateStreams makes GL calls such as
glEGLImageTargetTexture2DOES and therefore requires a valid GL context.

Renderer: call updateStreams AFTER makeCurrent.

---

shaders/src/common_material.fs

The "clampNoV" shader function is ignoring the passed dot product argument and recomputing the dot product itself. This will result in the wrong NoV value being used for clear coat IBL computations.

clampNoV function ignores argument

---

libs/utils/include/utils/Allocator.h
libs/utils/include/utils/Condition.h
libs/utils/include/utils/Mutex.h

TSAN seems to have problems with homegrown sync primitives, such as
spinlocks, so we just don't use them when TSAN is enabled.

don't use our own sync primitives when TSAN is used

---

RELEASE_NOTES.md
shaders/src/main.vs

I tested this with the CesiumMan model, the lighting seems improved
around his hands.
Fixes #1848.

Fix normals with skinning when there is no normal map.

---

filament/src/details/Material.h

Initialize some members inside of `FMaterial`, in case they aren't present inside the compiled material. Some of these (like `mShading`) aren't present in post-process materials, but he still try to access them—hence UB.

Fix UB inside FMaterial

---

filament/backend/include/private/backend/CommandStream.h

- this is to allow the use of C++17 std::invoke
- don't std::move() each argument of the tuple<> instead
std::move() the tuple itself and perfectly-forward each argument.
- handle return values
- handle synchronous commands

tweak how we invoke commandstream's commands

---

filament/src/details/Allocators.h

On Debug builds, HeapAllocatorArena needs LockingPolicy::Mutex because
it uses a TrackingPolicy, which needs to be synchronized.
On Release builds, HeapAllocatorArena doesn't need a LockingPolicy 
because HeapAllocator is intrinsically synchronized as it relies on
heap allocations (i.e.: malloc/free)

fix a data race on Debug builds

---

filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp

New internal API to add custom commands (lambda) before or after each
pass. These commands can be added at any point and will be sorted
properly.
e.g.:
appendCustomCommand(Pass::COLOR, CustomCommand::PROLOG, 0, [](){
// custom code
});
Also split appendSortedCommands() in two functions to make it easier
to insert custom commands.

custom command support in the renderloop

---

filament/src/RenderPass.cpp

This fixes an oversight in #1641 for scenes that have only 1 primitive
when the depth prepass is enabled. In such cases, the same prim is
rendered twice in a row: once for depth and once for color.
We had enhanced the main render loop to override the primitive's
backface culling state when the material instance changed, but that was
not sufficient since the same material instance can be used for depth
and color passes.
Fixes #1872.

Fix dynamic backface culling.

---

filament/src/PostProcessManager.cpp
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp

RenderPass's API now doesn't need to know about FScene, instead we
pass the geometry info as parameters.
This is one step towards keeping the "scene" concept more away from
rendering.

RenderPass cleanup/refactoring

---

android/common/CallbackUtils.cpp
android/common/CallbackUtils.h
android/filament-android/src/main/cpp/Stream.cpp
android/filament-android/src/main/java/com/google/android/filament/Stream.java
filament/backend/CMakeLists.txt
filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/AcquiredImage.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/include/private/backend/OpenGLPlatform.h
filament/backend/src/Driver.cpp
filament/backend/src/DriverBase.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/PlatformEGL.cpp
filament/backend/src/opengl/PlatformEGL.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/include/filament/Stream.h
filament/src/Stream.cpp
filament/src/details/Stream.h

Previously, Streams had two modes (native and texid), this adds a third
mode called "acquired", which allows for copy-free synchronized external
textures in OpenGL and paves the way for Vulkan.
The native mode is now deprecated but texid mode needs to stay around
until all clients can be upgraded.
In an early prototype, this functionality was added directly into
Texture but required quite a bit of additional state tracking, so the
Stream API seemed like a better fit.
This API is probably not necessary for Metal due to Metal's shared
ownership semantics.
This has been tested with a new Android sample that will be added in a
subsequent PR.

Stream API now supports acquire / release semantics.

---

filament/src/RenderPass.cpp
filament/src/RenderPass.h

We used to have this functionality, but it we removed it because we
didn't have a use for it and it was costly.
This new implementation is only internal, and would (will?) be useful
if we wanted to generate a special buffer for SSAO for instance (instead
of just depth). This implementation, overrides the material at the time
the commands are executed, which is much cheaper than the previous
implementation.

Add a way to override the material of a RenderPass

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp

1) When scaling is enabled, we're using a blit at the end of the frame,
however, if MSAA is also enabled, this blit is not allowed, so we
need an explicit MSAA resolve.
2) When rendering directly into the default render target with MSAA
enabled, we need an explicit resolve ONLY IF there is a format
conversion, because those are also not allowed. 
Before, we were doing this resolve regardless.
3) The test for "rendering directly into the default target" had
become wrong because, the Render target can now be a user texture
(which is assumed to have the proper MSAA-ness and a depth buffer),
so no intermediate buffer should be needed for those. We now
check that render target is actually the default render target

fix a few issues with MSAA blits

---

RELEASE_NOTES.md
shaders/src/light_indirect.fs

We used to use SH2 on mobile/webgl, but the quality degradation is too
prominent. This adds ~16 adds though.

Always use SH3 for indirect lighting

---

RELEASE_NOTES.md
filament/CMakeLists.txt
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h
filament/src/materials/blit.mat
samples/app/FilamentApp.cpp

Fix #1165
In order to use transparent views, post-processing had to be disabled
because we were not able to blit post-processed buffers with blending.
This is now fixed by simply reverting to a quad.
A side effect of this, is improved performance when a scaling blit is
needed when MSAA is active.
This also introduced new "bugs", or at least weird behaviors: the
system needs to know when blending is needed, and this has to be
based on heuristics (unless we add a new api). Currently the heuristic
is that the COLOR buffer is not discarded and the view is cleared with 
an alpha value (or not cleared).

Fix a long standing bug preventing the use of transparent views

---

README.md

Removing this line as the build badges no longer link to anything. If we decide to add continuous build artifacts back in we can update this.

Update README.md to reflect build link removal

---

filament/src/materials/blur.mat
filament/src/materials/sao.mat
filament/tools/ssaogen.cpp

We go from 9 to 15 taps to better match the 16x16 noise pattern.

Use a larger blur filter for SSAO

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/materials/tonemapping.mat

This fixes an issue where the alpha channel could be left to garbage in
opaque mode with FXAA disabled.

Tone mapping always sets alpha channel to 1 in opaque mode

---

filament/src/Renderer.cpp
filament/src/fg/FrameGraphHandle.cpp

A texture resource can end-up with not usage bit set if it is used as
an attachment of a render target that gets replaced by a moveResource()
call. The framegraph should take care of culling our this resource,
in that case, but currently doesn't.
We worked around this issue by not declaring the resources, but it's
better to do this in the frame graph code, as to not affect the 
user facing API.

Better workaround a resource culling issue.

---

.github/workflows/release.yml
build/common/upload-assets.py
build/windows/build-github.bat

This adds a new GitHub workflow to the repository that triggers release builds when a new Filament release is created. The workflow will automatically upload and attach built assets to the release.
The release workflow can be triggered for individual platforms through a GitHub [repository dispatch](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#external-events-repository_dispatch) event. This allows us to trigger a single platform to rebuild if we need to.

Add release GitHub workflow

---

CMakeLists.txt
web/filament-js/CMakeLists.txt
web/filament-js/jsbindings.cpp
web/filament-js/utilities.js

Unfortunately we require RTTI to be disabled for web builds
due to the way in which we handle array buffers. This may change
in the future but for now I think it's an acceptable constraint,
especially given the fact that RTTI adds bloat anyway.

wasm: add support for DEBUG builds by disabling RTTI.

---

filament/backend/src/opengl/PlatformWGL.cpp

Pass shared context on Windows to wglCreateContextAttribs

---

filament/backend/src/opengl/OpenGLDriver.cpp

This removes an incorrect `if` conditional, given that bindFramebuffer can be called from other places.
Fixes #1914.

Fix missing call to glInvalidateFramebuffer().

---

filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalContext.mm
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/PlatformCocoaGL.mm
filament/backend/src/opengl/PlatformEGL.cpp
filament/backend/src/opengl/PlatformGLX.cpp
filament/backend/src/opengl/PlatformWebGL.cpp
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/Renderer.cpp
filament/src/fg/FrameGraphHandle.cpp

This is to allow direct rendering of 3D objects into the swapchain 
under certain circumstances (no msaa or postprocessing).

Swap chains are now always created with a depth buffer

---

RELEASE_NOTES.md
docs/Materials.md.html
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalExternalImage.h
filament/backend/src/metal/MetalExternalImage.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/include/filament/Texture.h
filament/src/Texture.cpp
filament/src/details/Texture.h
shaders/src/common_graphics.fs

This change allows mapping individual planes of iOS external images to Filament textures. This
allows the YCbCr -> RGB conversion to be done in the fragment shader (as opposed to a compute
shader).

Add support for mapping individual planes of iOS external images

---

android/filament-android/src/main/cpp/nativewindow/Darwin.mm

Sometimes CMake decides to use the JNI bits included with XCode instead
of those from the installed JDK. The header files are located in different
directories. This does the proper include.

Make including jawt_md.h more resilient

---

CMakeLists.txt

These flags should be set for MSVC too, not just Clang. Fixes #1920

Fix Windows build variants

---

filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp

some drivers declare supporting anisotropic filtering, but don't
support calling glSamplerParameter() to set the max anisotropy, presumably because they only support glTexParameter().
We simply turn off anisotropic filtering on these drivers.

workaround OpenGLES driver bug

---

samples/app/CameraManipulator.cpp
samples/app/CameraManipulator.h
samples/app/FilamentApp.cpp
samples/app/FilamentApp.h

This removes a lot of code and will make it easier to migrate into a new
library with Java bindings, etc.
- The clipping planes and projection matrix were unused, removed them.
- In split view mode, our demos were using only 2 of the 3 manipulators,
removed one.
- Instead of callbacks and update methods, users can simply ask for the
current matrix at every frame.
- The manipulator's job is to consume mouse events and maintain an
"look at" basis, there is no need to store a reference to a Filament
Camera.

Simplify CameraManipulator.

---

filament/src/RenderPass.cpp

This regressed when we added support for dynamic backface culling
(#1641). Also note another fix we made: #1877.

Repair twoPassesTwoSides transparency.

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/src/fg/ResourceAllocator.cpp

this helps reducing churn in the resourceallocator cache.

Round non-texture FBO attachments to 32 pixels

---

filament/backend/src/opengl/OpenGLContext.cpp

According to the OpenGL spec, proper cubemap filtering is disabled by
default in non-ES OpenGL.

OpenGL: enable cubemap filtering on desktop.

---

RELEASE_NOTES.md
filament/src/IndirectLight.cpp
tools/cmgen/src/cmgen.cpp

Filament will now allow incomplete mipmap chains for the IBL and
map the roughness to the available chain.
This allows to create roughness cubemaps with a minim size for
roughness==1, instead of always mapping it to 1x1.
cmgen will now use 16x16 cubemaps for roughness==1, which
improves the quality of rough objects significantly.
The beauty of this is that there is no asset or API change. Old assets
will continue to work like before.
Before:
After:

Improve low roughness significantly

---

RELEASE_NOTES.md
filament/src/Engine.cpp
filament/src/IndirectLight.cpp
filament/src/Scene.cpp
filament/src/View.cpp
filament/src/details/IndirectLight.h

This cleans up 3 related issues, but only the first of these caused an
actual user-visible bug:
(1) When the IBL was null, prepareLighting was failing to bind the black
1x1 texture.
(2) If you added and removed an IBL from a Scene, then Scene was not
returned to its initial state.
(3) The default 1x1 IBL used an intensity of 1 rather than 30000, which
is inconsistent with the null IBL.
Fixes #1940.

Fix bad state after setIndirectLight(null).

---

shaders/src/light_punctual.fs

This fixes punctual lights with Metal and Vulkan. Metal and Vulkan have a vertically flipped texture space, so we need to adjust the fragment coords when calculating froxel coords, otherwise we incorrectly sample the froxel texture.
To test, I ran `lightbulb` and passed the `-d` flag.

Fix froxel coordinate calculation on Metal and Vulkan

---

web/filament-js/extensions.js

In PR #1906 we enabled depth for all backends, but we forgot web.
Note that this required 0 new codelines whereas Vulkan required 116
additional codelines. :)

WebGL: enable depth buffer in swap chain.

---

filament/backend/CMakeLists.txt
filament/backend/src/metal/MetalBuffer.h
filament/backend/src/metal/MetalBuffer.mm
filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/test/BackendTest.h
filament/backend/test/TrianglePrimitive.cpp
filament/backend/test/TrianglePrimitive.h
filament/backend/test/test_BufferUpdates.cpp

This moves the logic behind allocating Metal buffers out of `MetalUniformBuffer` and into a new class, `MetalBuffer`. This allows vertex and index buffers to be updated within a frame

Refactor Metal buffers, allow in-frame vertex and index updates.

---

README.md
filament/README.md

We no longer officially support building for Windows with Clang, which simplifies a lot of our README :)

Update Windows READMEs for building with VS2019

---

shaders/src/light_indirect.fs

The thin roughness remapping only makes sense for thin surfaces, it was
a mistake to apply it to solids. It assumes that a ray will go
undisturbed though the thin surface with an ior of 1.

don't apply roughness remapping for solid refraction

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/IndirectLight.cpp
android/filament-android/src/main/java/com/google/android/filament/IndirectLight.java
filament/include/filament/IndirectLight.h
filament/src/IndirectLight.cpp
filament/src/details/IndirectLight.h
libs/ibl/src/CubemapSH.cpp
samples/app/IBL.cpp
samples/app/IBL.h
samples/material_sandbox.cpp
shaders/src/light_indirect.fs
tools/cmgen/src/cmgen.cpp
web/filament-js/jsbindings.cpp

Before: Spherical Harmonics fail to encode the diffuse.
After: Diffuse is better encoded, but shows some undersampling.

Improve ibl diffuse with absolute hdr environments

---

libs/math/include/math/TVecHelpers.h
libs/math/include/math/compiler.h
libs/math/include/math/half.h

The latest version of MSVC appears to not allow `std::is_arithmetic` specializations for custom types. This is the best workaround I can think of at the moment.
Fixes #1939

Fix MSVC 2019 16.4 build

---

RELEASE_NOTES.md
filament/backend/src/opengl/PlatformCocoaGL.mm

Fix Catalina by moving some calls to the UI thread.

---

filament/src/PostProcessManager.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp

When doing the depth path for ssao, we need to remove the blended
objects, i.e. produce a depth path similar to the regular depth prepass.

Fix SSAO when blending is used

---

build.sh
samples/CMakeLists.txt

This adds a shortcut for building `gltf_viewer` then immediately running it with the default model, which is something we do a lot.  Lets you avoid typing the path to executable.

CMake: add a convenient "run" target for quick testing.

---

docs/math/IBL Roughness Remapping.nb
shaders/src/light_indirect.fs
tools/cmgen/src/cmgen.cpp

This greatly improves the quality of semi-rough materials.

Better roughness remapping for IBLs

---

RELEASE_NOTES.md
samples/CMakeLists.txt
tools/cmgen/src/cmgen.cpp
web/docs/tutorial_redball.md
web/samples/CMakeLists.txt

With KTX, we should simply create the specified output folder and put the KTX file(s) in there. There is no need to create a subfolder of the output folder.
This change also allows users to pick a custom name for their KTX file, because we only use the deployment name when generating filenames.

cmgen: do not create useless folder for KTX files

---

filament/src/fg/ResourceAllocator.cpp

#1976  had a missing `!` which had the effect of disabling heterogenous FBO sizing on Desktop.  *welp*

Repair web samples by fixing typo in previous fix.

---

filament/backend/src/BackendUtils.cpp
filament/backend/src/TextureReshaper.cpp
filament/backend/src/TextureReshaper.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalEnums.h
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

- Textures are now PRIVATE, which should improve mobile GPU performance
- Textures can be updated each frame without conflicting with GPU
- Fixed support for BC textures
- Respect PixelBufferDescriptor's left, top, and alignment parameters when uploading textures

Improve Metal textures

---

filament/backend/src/opengl/GLUtils.h
filament/backend/src/opengl/PlatformEGL.cpp
filament/backend/src/opengl/PlatformEGLAndroid.cpp
filament/backend/src/opengl/PlatformEGLAndroid.h

Fixes #1989 by fetching extension function pointers that were refactored
in #1977. Moved string-splitting utility to a common location so that
the base class and concrete classes can both use it.

Repair Android extension pointers.

---

libs/gltfio/src/AssetLoader.cpp

In glTF, multiple nodes can refer to the same mesh, and each node can be
assigned a unqiue string label. Previously we used NameComponentManager
to annotate entities with mesh labels rather than node labels. This was
wrong because Filament entities are 1:1 with nodes, not meshes.
We still fall back to mesh labels when node labels are not provided.

gltfio: honor node labels if they exist.

---

libs/utils/include/utils/EntityManager.h
libs/utils/src/Panic.cpp

This enables dynamic linking to Filament inside of Sceneform by exporting symbols that are used in Sceneform's native layer.

Make EntityManager and Panic dynamic-linkable.

---

RELEASE_NOTES.md
samples/CMakeLists.txt
samples/heightfield.cpp
samples/materials/heightfield.mat

This is a sample I created to test continuous texture updates when implementing some features for the Metal backend. It generates a noise texture each frame, uploads it to the GPU, and samples from it to offset vertices in a heightfield. There's a few additional options, such as updating a sub-region of the texture, adding additional padding to the pixel buffer, or using a different texture format.

Add new heightfield sample

---

filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h
filament/src/fg/ResourceAllocator.cpp
filament/src/fg/ResourceAllocator.h
filament/test/filament_framegraph_test.cpp

We have one very important unit test that is supposed to make sure
the framegraph reuses the same rendertarget between 2 passes, this
unit test would always succeed when using the NoopDriver.
Now that we can mock the ResourceAllocator, we can ensure this unit
test is doing its job.

Make ResourceAllocator mockable and update test

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp
filament/src/details/Renderer.h
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h
filament/src/fg/fg/RenderTarget.cpp
filament/test/filament_framegraph_test.cpp
libs/utils/include/utils/Slice.h

This is in preparation to supporting screen-space effects.
There are two major changes:
- RenderPass is now copiable and intended to be passed by copy to
the execute stage of frame graph passes
- The color pass is in its own function now
This actually simplify RenderPass api.

refactor Renderer to make it more flexible

---

android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/ResourceLoader.cpp

This was untested because our only glTF Android sample uses glb instead
of JSON. We will soon be adding a new Android demo that uses an actual
gltf file.
This fixes #1841.

gltfio: support external resources on Android.

---

filament/src/fg/FrameGraphHandle.cpp
filament/src/fg/fg/RenderTarget.cpp

The FrameGraph would erroneously specify a sample count on textures
that are sampleable and used as an attachment to a multisampled 
target -- however, that's not allowed.
We didn't run into issues, because had a workaround for this when
creating the texture. This is augmented by an assertion.

Fix a multisample related bug in the FrameGraph

---

filament/src/components/TransformManager.cpp

Ensure that parents are always before children in transform manager, even after reparenting happens.
The current code only updates the order in the transaction commit if there's a single out-of-order node in the scene graph, but if multiple are out of order (or one swap doesn't fully fix the ordering), then we end up with out of order scenes, and incorrect world transforms.
Additionally, when nodes are reparented outside of a transaction, the order is not updated.

Correct out-of-order transform instances

---

filament/src/components/TransformManager.cpp
filament/test/filament_test.cpp

setParent() is not supposed to reorder child/parents in the array
because it doesn't rely on them being orderer. This also has the
advantage of not invalidating Instances.
However, commitLocalTransformTransaction() does rely on child/parent
ordering and the previous change did fix that.

revert part of a recent TransformManager change

---

libs/camutils/include/camutils/Manipulator.h
libs/camutils/src/Manipulator.cpp
libs/camutils/tests/test_camutils.cpp
samples/app/FilamentApp.cpp

This makes the upcoming Java bindings simpler and improves parity with
existing API conventions.
Note that camutils does not depend on filament and therefore cannot use
BuilderBase.
Note that the Manipulator Builder state is public which breaks with
convention but makes implementation simple and allows C++ clients to
continue using modern initializer syntax if they wish.

camutils: add support for Builder pattern.

---

libs/gltfio/src/AssetLoader.cpp

glTF specifies that client implementations must support at least two UV
texture coordinate sets but does not seem to have an upper limit.
We use a mapping table in order to honor high-numbered UV set indices,
but our mapping table only accomodates 8 entries.
Fixes #2042

Fix out-of-bounds when glTF has many UV sets.

---

android/gltfio-android/src/main/cpp/FilamentAsset.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
libs/gltfio/src/ResourceLoader.cpp

According to Android Studio, this makes `gltf-viewer` Java usage go from 18 MB to 6 MB.

gltfio + Android: improve memory management.

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/GestureDetector.kt
android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
android/filament-utils-android/src/main/java/com/google/android/filament/utils/Utils.kt
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt

This reduces the LOC of our gltf-viewer app from 260 to 146. This could
have been more, but I feel this provides good balance between
flexibility and convenience.
The raw gltfio API involves multiple objects (FilamentAsset,
AssetLoader, ResourceLoader) whereas the ModelViewer has a simple facade
consisting of two methods, one for GLB and one for GLTF. The underlying
gltfio objects are available via non-settable properties.

Android: introduce ModelViewer helper.

---

filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/noop/NoopDriver.h

The NOOP backend didn’t call user-API callbacks from the main thread
(instead calling them from the “backend thread”). This caused problems
with unit tests for instance.

Fix a NOOP backend threading bug

---

filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/PlatformEGL.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/include/filament/Texture.h
filament/src/Texture.cpp
filament/src/details/Texture.h

If you need this, you know who you are.
The new Texture::Builder::import() allows to specify a OpenGLES texture
id from a shared GL context, effectively importing the texture into
filament.
The texture is NOT destroyed when calling Engine::destroy(Texture*), only
its filament handle.

New API to import textures into filament

---

build.sh
filament/backend/src/opengl/CocoaTouchExternalImage.mm

This fixes a deprecation warning in `MetalDriver.mm` and a few unused variable warnings. CMake must be re-run before the deprecation warning will be silenced.

Fix some macOS / iOS build warnings

---

RELEASE_NOTES.md
android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
android/gltfio-android/src/main/cpp/ResourceLoader.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/ResourceLoader.java
libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/ResourceLoader.cpp
samples/gltf_viewer.cpp
web/filament-js/extensions.js
web/filament-js/jsbindings.cpp

We were already using jobs for decoding PNG and JPEG files, but we were doing a join. This add three methods to ResourceLoader that allow clients to amortize the decoding process across multiple frames, even on single-threaded platforms like WebGL.
This PR adds async loading to the following demos:
- samples/gltf_viewer (now shows a progress bar in the UI)
- android/sample-gltf-viewer
- web/samples/helmet.html
Fixes #1876.

gltfio: Introduce the asynchronous API and use it.

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/View.cpp
filament/src/details/View.h
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraphHandle.cpp
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/src/UibGenerator.cpp
shaders/src/light_indirect.fs

We now use a fixed-size kernel (right now 17), for each mip-level.
And we workout the mapping from roughness to such mip.
This improves performance by reducing significantly the number of taps
per mip, however, we don't control how much blur is actually applied
at each level. This gives a mip-chain that is proportional to
'roughness'.
It's now easier to tune quality vs. speed by tweaking the kernel's width
as well as how we map 'sigma' to a the kernel width.

rework refraction filtering/blurring to improve performance

---

build.sh
filament/src/Engine.cpp

If a client application selects a backend that is not supported by the
build, Engine::create() now returns null, which allows the Java wrapper
to throw IllegalStateException. Prevously, we would crash in the native
layer by hitting a null pointer in Engine::loop().

Missing backend now throws Java exception, not segfault.

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
android/gltfio-android/src/main/cpp/FilamentAsset.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
libs/gltfio/CMakeLists.txt
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/include/gltfio/SimpleViewer.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/DependencyGraph.cpp
libs/gltfio/src/DependencyGraph.h
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp
libs/gltfio/src/ResourceLoader.cpp
samples/gltf_baker.cpp
samples/gltf_viewer.cpp
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp
web/samples/helmet.html

This feature adds one new method to `FilamentAsset` and uses it in our
Kotlin, JavaScript, and C++ helpers:
utils::Entity popRenderable() noexcept;
This pops a ready renderable off an internal queue, or returns 0 if no
renderables have become ready. It provides a simple way for clients to
gradually add renderables to the scene as they become ready. Previously
clients could only get the entire list of entities, regardless of
whether they had Renderable components or complete textures.
To facilitate this feature, this PR adds a new internal-only class to
gltfio called `DependencyGraph`, which is a temporary object used for
bookkeeping during the asynchronous load.
`DependencyGraph` discovers ready-to-render entities by tracking the
textures that each entity depends on. This is a graph …

gltfio: hide entities with not-yet-ready textures.

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/fg/fg/RenderTargetResource.cpp

- always take the "blit" path (rather than quad path) when MSAA
and is on. we now rely on the render target to have been resolved
into its texture (implicitly or explicitly). This means in some cases
there will be 2 bliss in a row -- but that's still better than a
blit and a quad. These are unavoidable without using a custom resolve.
- removed creating renderbuffer with the EXT_multisampled_render_to_texture
extension because we didn't support it fully and didn't support
the fallback mode (for desktop or if the extension is not there).
Also this case never happens currently.
- added more assert()
- added a bunch of comments explaining the restrictions of using MSAA
regarding blitting.

More comments and small bug fixes regarding MSAA

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp

the input and output are now separate (don't need to be the same
texture)

make the gaussian blur pass more generic

---

filament/src/PostProcessManager.cpp
filament/src/materials/separableGaussianBlur.mat

It turns out that textureLod() only reads the base layer if the sampler
is not set to xxx_MIPMAP_xxx. This prevented the gaussian-blur code
to work properly.
Specifically, the horizontal pass would always use the base layer. Not
only this made the blur unstable, but also hurt performance significantly.
With this change, the untonamap/tonemap is no longer needed and the 
results are much more convincing with objects with highlights.

fix screen-space refraction roughness calculation

---

RELEASE_NOTES.md
libs/geometry/include/geometry/SurfaceOrientation.h
libs/geometry/src/SurfaceOrientation.cpp
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/ResourceLoader.cpp

This "fixes" the new animated Fox model in the glTF conformance suite. As per the glTF spec, we now generate per-face normals for the case where normals are not specified in the model.
Note that true flat shading (i.e. flat interpolation) is not a requirement in the glTF spec, since some Khronos members advocate for WebGL 1.0 compatibility.
Fixes #2088.

gltfio: add nominal support for flat shading.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/MaterialInstance.cpp
android/filament-android/src/main/java/com/google/android/filament/Material.java
android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java
filament/include/filament/Material.h
filament/include/filament/MaterialInstance.h
filament/src/MaterialInstance.cpp
filament/src/RenderPass.cpp
filament/src/details/MaterialInstance.h
libs/filamat/include/filamat/MaterialBuilder.h
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

Fulfills a request from tirichards@.
This is similar in some ways to dynamic backface culling but simpler
because there is no interaction with double-sided lighting.
For reference, dynamic backface culling was implemented with #1936, #1877, #1641.

Add dynamic raster states to MaterialInstance.

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h

because the intermediate buffer could have non-square pixels, blurring
the buffer would result in an anamorphic blur.
We fix this by properly scaling the buffer before blurring.

Fix a SSRefr when dynamic-scaling is enabled

---

RELEASE_NOTES.md
android/filament-android/CMakeLists.txt
android/filament-android/src/main/cpp/SurfaceOrientation.cpp
android/filament-android/src/main/java/com/google/android/filament/SurfaceOrientation.java
android/filament-android/src/main/java/com/google/android/filament/VertexBuffer.java
filament/src/VertexBuffer.cpp
ios/samples/hello-ar/hello-ar/FilamentArView/FilamentApp.cpp
libs/geometry/include/geometry/SurfaceOrientation.h
libs/geometry/src/SurfaceOrientation.cpp
libs/gltfio/src/ResourceLoader.cpp
samples/lucy_utils.cpp
web/filament-js/jsbindings.cpp

Note that libgeometry is already included in `filament-android`, this
simply exposes more of its existing functionality.
The Java version of SurfaceOrientation is similar to the JavaScript
version because we are bundling it into the main Filament package, even
though it is a separate library in C++. This is much simpler than
creating a brand new Java package.
New Android sample that tests this is forthcoming.
Fixes #1729.

Add Java bindings for SurfaceOrientation.

---

filament/src/materials/skybox.mat

This is a temporary (hopefully) hack to make the skybox sun look 
better when bloom is enabled (this doesn't affect how the "sun" lights
objects, only how it looks in the skybox).
This scale factor was adjusted empirically.

Make sure sun in the skybox blooms enough

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
filament/src/materials/bloomDownsample.mat

Threshold can be either on or off, and only thresholds at 1.0 when 
activated (in pre-exposed mode).
This allows to use very high strengths values for the bloom without
softening the rest of the image, and is useful for artistic considerations.

Add a threshold option (enabled by default) for bloom.

---

android/gltfio-android/CMakeLists.txt
android/gltfio-android/src/main/cpp/Gltfio.cpp
android/gltfio-android/src/main/cpp/ResourceLoader.cpp
libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/ResourceLoader.cpp
libs/utils/src/Path.cpp
libs/utils/test/test_Path.cpp
samples/gltf_baker.cpp
samples/gltf_viewer.cpp
web/filament-js/jsbindings.cpp

For Android and wasm we do not use the filesystem and therefore do not
need `utils::Path`.
```
libgltfio-jni.so BEFORE 1.9 MB (693 KB gzipped)
libgltfio-jni.so AFTER  1.4 MB (542 KB gzipped)
```

gltfio: remove locale.cpp dependency

---

android/filament-android/src/main/cpp/Camera.cpp
android/filament-android/src/main/cpp/IndirectLight.cpp
android/filament-android/src/main/cpp/SurfaceOrientation.cpp
android/filament-android/src/main/cpp/TransformManager.cpp
filament/include/filament/Camera.h
filament/include/filament/DebugRegistry.h
filament/include/filament/IndirectLight.h
filament/include/filament/LightManager.h
filament/include/filament/Material.h
filament/include/filament/MaterialInstance.h
filament/include/filament/RenderableManager.h
filament/include/filament/TransformManager.h
filament/include/filament/View.h
filament/include/filament/Viewport.h
filament/src/Camera.cpp
filament/src/DebugRegistry.cpp
filament/src/IndirectLight.cpp
filament/src/components/TransformManager.cpp
filament/src/details/IndirectLight.h
libs/filagui/src/ImGuiExtensions.cpp
libs/image/include/image/ColorTransform.h
libs/math/CMakeLists.txt
libs/math/include/math/mathfwd.h
libs/math/include/math/scalar.h
web/filament-js/jsbindings.cpp

math/mathwfd.h forward declares all {mat|vec}{2|3|4}<> classes,
which allows us to remove their respective #include in a lot of
our public headers.
Our math headers are full of templates, so this should help build times
a bit.
Also we want to keep the public headers as minimalist as possible.

New mathfwd.h header

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/materials/separableGaussianBlur.mat

We untonemap/tonemap the first level of blur to reduce the very high
frequencies due to HDR highlights in the image, this produce a softer
image at higher roughness. This can programmatically be turned off,
but that setting is not exposed.

improve SSrefr highlights at low roughness

---

RELEASE_NOTES.md
docs/Materials.html
docs/Materials.md.html
filament/backend/src/metal/MetalState.h

A state tracking bug led to disappearing objects rendered with the `twoPassesOneSide` setting.

Fix incorrect twoPassesOneSide rendering with Metal

---

filament/src/materials/bloomUpsample.mat

This doesn't affect quality significantly, but saves 30% of gpu time
on the upsampling, overall it's about 0.1 ms. This brings The bloom
effect below 2ms on Pixel4.

On mobile, use a more efficient up-sampler

---

android/filament-android/CMakeLists.txt
android/filament-android/libfilament-jni.map
android/filament-utils-android/src/main/cpp/Utils.cpp
android/gltfio-android/CMakeLists.txt
android/gltfio-android/libgltfio-jni.map
android/gltfio-android/src/main/cpp/AssetLoader.cpp
android/gltfio-android/src/main/cpp/Gltfio.cpp
filament/include/filament/Box.h
libs/gltfio/CMakeLists.txt

The net effect of these 3 changes on arm64 reduces the uncompressed libgltfio so from 1.5 MB to 850 KB.  Over 55% of the newly optimized binary is its rodata section (i.e. materials).
As a bonus, this ultimately reduces libfilament so by 8 KB because it fixes a typo in our CMake file wrt `--gc-sections`.
Later today, we would like to create a "gltfio-lite" which would only support lit opaque materials.  This would have a size of ~470 KB .

Reduce size of gltfio for Android.

---

android/gltfio-android/CMakeLists.txt
libs/gltfio/CMakeLists.txt
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/UbershaderLoader.cpp

This is 466 KB insted of the usual 850 KB. It assumes that users do not
need spec-gloss, non-lit, or a special transparency mode.
(uncompressed SO size on arm64)
We can add a new maven project for this next week.

Introduce gltfio-lite.

---

android/filament-android/src/main/java/com/google/android/filament/Texture.java
filament/backend/include/backend/DriverEnums.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/include/filament/Texture.h
libs/filamat/src/shaders/CodeGenerator.cpp
libs/matdbg/src/CommonWriter.h

This reworks Filament's array texture support, adding a new `SAMPLER_2D_ARRAY` sampler type and support for array textures in Metal. This is in preparation for spot light shadows, which will change the current shadow map into an array texture, each layer for a separate light.

Rework array texture support

---

CMakeLists.txt
build/launch-c.in
build/launch-cxx.in

To benefit from ccache, first install ccache (for instance with
brew install ccache on macOS). On my machine a clean build takes
~5 minutes the first time. A second clean build with ccache enabled
takes 34 seconds.

Add support for ccache

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/materials/bilateralBlur.mat
filament/src/materials/sao.mat

During the SSAO pass, we pack the decoded depth to the GB channels of
the AO texture, which reduces our bandwidth requirements during the
blurring pass, as well as some ALU usage.
It puts SSAO at about 2ms on pixel4/1080p.

Another SSAO optimization saving another ~16% 

---

web/filament-js/extensions.js
web/filament-js/filament.d.ts

This patches up all the holes discovered when I tried porting the fidelity tests in `model-viewer` to our TypeScript declarations.
FYI @elalish

Add missing TypeScript declarations.

---

RELEASE_NOTES.md
web/filament-js/extensions.js
web/filament-js/filament.d.ts
web/samples/animation.html
web/samples/helmet.html
web/samples/morphing.html

After the native async functionality landed, there was no way for web clients to be notified that the decoding has finished. This PR changes the existing `onDone` callback so that it gets called after all textures have been decoded. (Previously it was called after downloading rather than decoding.)
This has the side effect of simplifying the API because clients no longer need to call a finalize function.
I realized that this needed to be done while locally upgrading the `model-viewer` fidelity tests to a Filament release candidate.  FYI @elalish

WebGL: Improve the callback API for glTF.

---

RELEASE_NOTES.md
filament/src/materials/sao.mat

The syntax for the equivalent of `textureLod` in Metal shading language precludes us from using a variable named `level`.

Fix Metal crash on Catalina

---

BUILDING.md
CMakeLists.txt
android/Windows.md
android/build.gradle
android/samples/sample-gltf-bloom/build.gradle
android/samples/sample-gltf-viewer/build.gradle
android/samples/sample-hello-camera/build.gradle
android/samples/sample-hello-triangle/build.gradle
android/samples/sample-image-based-lighting/build.gradle
android/samples/sample-lit-cube/build.gradle
android/samples/sample-material-builder/build.gradle
android/samples/sample-stream-test/build.gradle
android/samples/sample-texture-view/build.gradle
android/samples/sample-textured-object/build.gradle
android/samples/sample-transparent-view/build.gradle
build.sh
filament/backend/CMakeLists.txt
filament/backend/src/Platform.cpp
filament/backend/src/opengl/gl_headers.cpp
filament/backend/src/opengl/gl_headers.h
java/filamat/CMakeLists.txt
java/filament/CMakeLists.txt
samples/CMakeLists.txt
web/samples/CMakeLists.txt

`-DFILAMENT_SKIP_SAMPLES=ON` with CMake
`-Pfilament_skip_samples` with Gradle
This change also renames CMake options specific to Filament
to avoid clashes with subprojects.
This change fixes #1431.

Add options to skip samples

---

filament/src/MaterialInstance.cpp
filament/src/details/MaterialInstance.h

This caused color writes to be disabled in our "hello triangle" samples.
Fixes #2164.

Fix regression with getDefaultInstance().

---

filament/backend/include/private/backend/CommandStream.h
filament/backend/include/private/backend/DriverAPI.inc

- the tuple<> where we store the parameters should only remove the
reference, but not decay, so that arrays could theoretically
be stored (more on this below).
- use std::forward<> instead of std::move<> in Command's ctor, this is
more appropriate, we just want to forward the arguments unchanged.
- add std::move() to all parameters on the command stream stub, it is
appropriate here, because we receive parameters by value or r-value 
references.
All this was an attempt to support C-style arrays as parameters, but
it doesn't work because they are decay'ed to pointers when they
appear as parameters.

cleanup command stream parameter passing

---

libs/filamat/include/filamat/MaterialBuilder.h
libs/gltfio/include/gltfio/MaterialProvider.h
libs/gltfio/materials/ubershader.mat.in
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/MaterialGenerator.cpp
libs/gltfio/src/MaterialProvider.cpp
libs/gltfio/src/UbershaderLoader.cpp
shaders/src/main.vs
third_party/cgltf/cgltf.h
third_party/cgltf/cgltf_write.h

Here is an example of `gltf_viewer` after loading the [official Khronos clear coat sample asset](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ClearCoatTest):

Add support for KHR_materials_clearcoat to gltfio

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/backend/TargetBufferInfo.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanDriver.h

- this simply changes the createRenderTarget() API to take an
'MRT' structure for the color attachment. The MRT structure is
just a wrapper around an array of four TargetBufferInfo.
- in this PR only implemented for OpenGL

Add support for MRT to the backend

---

filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h
filament/src/fg/ResourceAllocator.cpp
filament/src/fg/fg/RenderTarget.h
filament/src/fg/fg/RenderTargetResource.cpp
filament/src/fg/fg/RenderTargetResource.h
filament/src/fg/fg/ResourceEntry.h
filament/src/fg/fg/VirtualResource.h
filament/test/filament_framegraph_test.cpp

The ultimate goal is to get rid of the concept of render targets in
the framegraph, and this is the first step. Here RenderTarget doesn't
store the discard flags anymore. These flags are now calculated
per-resource, per-pass.
A side effect of this change is that the discard flags are now slightly
better, as they don't contain attachments that don't exist.
i.e. we won't see the STENCIL flag set for instance.

First step in reworking how rendertargets work in the framegraph

---

samples/CMakeLists.txt
samples/gltf_viewer.cpp
samples/lightbulb.cpp
samples/material_sandbox.cpp
samples/materials/groundShadow.mat

The shadow is always positioned at the bottom of the loaded object's bounding box to ground it perfectly.

Add ground shadow option to gltf_viewer

---

filament/backend/src/opengl/PlatformCocoaGL.mm
filament/src/Fence.cpp

Closes #2159
There was two issues:
1) Fence::wait would return prematurely when the the timeout was
set to WAIT_FOREVER.
2) (At least) when running from the command line, events were not
read from the main queue. Instead we have to use NSRunLoop instead
of NSApplication APIs.

Fir a deadlock when exiting on MacOS (GL backend)

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp

This fixes the validation error that occurs when rendering to one miplevel while sampling from another. It might even be faster since fewer layout transitions are required.

Vulkan: use GENERAL layout for render target textures.

---

filament/backend/src/opengl/OpenGLDriver.cpp
libs/utils/src/Allocator.cpp

The allocator debug code didn't check that allocations where
successful before filling buffers.

Allocators shouldn't crash when allocation fails

---

filament/src/View.cpp
filament/src/details/View.h
libs/filabridge/include/private/filament/EngineEnums.h

This PR contains more preparation for spot lights shadows.
- visibility mask bits renamed and new ones are added for spot lights
- `computeVisibilityMasks` is refactored to be easier to reason about. Its logic remains the same.

Refactor computeVisibilityMasks logic, visibility bits

---

shaders/src/light_indirect.fs

Some drivers were tripping up at the quotes. Fixes #2184.

Remove unnecessary quotes from shader

---

filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/details/Scene.h

With spot light shadows, render passes will need the ability to "skip" over certain renderables. `setVisibilityMask` accomplishes this by allowing clients to set a mask that is tested againt each renderable's `VISIBLE_MASK` to determine whether or not it should be skipped.

Add visibility mask to RenderPass

---

filament/include/filament/LightManager.h
filament/src/components/LightManager.cpp
filament/src/components/LightManager.h

Spot lights will need this data in order to calculate the shadow frustum.

Add getSpotLightOuterCone method to LightManager

---

filament/src/Scene.cpp
filament/src/details/Scene.h
filament/test/filament_test.cpp
libs/filabridge/include/private/filament/UibGenerator.h
shaders/src/common_lighting.fs
shaders/src/light_punctual.fs

This adds shadow information into the Lights UBO. This data gets packed into 32 bits and sent down to the shader, where they're unpacked and (in the near future) will be used to implement spot light shadows.

Add additional shadow info to lights uniform

---

filament/src/ShadowMap.cpp
libs/filabridge/src/SibGenerator.cpp
shaders/src/light_directional.fs
shaders/src/shading_unlit.fs
shaders/src/shadowing.fs

This switches the shadow map from a 2D texture to a 2D array texture. We are still only rendering into the first layer.

Use array texture for shadow maps

---

RELEASE_NOTES.md
libs/gltfio/CMakeLists.txt
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/Bindings.h
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp

The binding list can be internalized, clients should instead use `getResourceUris()` and `ResourceLoader` to load external resources.

gltfio: simplify API, privatize bindings.

---

filament/src/ShadowMap.cpp
filament/src/View.cpp
filament/src/details/View.h

This add a new group to the partitioning schemed used inside View to partition renderables. The new scheme is:
0. renderables
1. renderables and directional shadow casters
2. directional shadow casters only
3. **punctual light shadow casters only**
4. invisible renderables
Spot light passes iterate through groups 0-3 (inclusive), skipping renderables that aren't part of that spot light pass.

Refactor renderable partitioning scheme for spot light shadows

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/RenderTarget.cpp
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp
filament/src/fg/FrameGraphHandle.h
filament/src/fg/ResourceAllocator.cpp
filament/src/fg/ResourceAllocator.h
filament/src/fg/fg/RenderTargetResourceEntry.cpp
filament/test/filament_framegraph_test.cpp

This adds support for MRT in the FrameGraph, and also enables it in the GL backend.
This PR also removes the concept of 'ignoreScissor' in beginRenderPass() -- it's now always ignored, this is to match how discard flags work (and how Metal works).

Finish MRT support (GL backend only)

---

filament/src/RenderPass.cpp
filament/src/fg/FrameGraph.cpp

A debug marker is emitted for each pass.
This greatly improves debugging with RenderDoc for instance.

The FrameGraph is now emitting debug markers

---

filament/src/fg/FrameGraph.cpp

This is so that render targets are destroyed before their
attachments. In practice it doesn't matter too much, at least
on OpenGL, but it is cleaner.

framegraph: destroy resources in reverse order

---

libs/utils/include/utils/Allocator.h

we've had issues with some devices running in arm mode, where they
would throw spurious SIGILL on the WFE instruction used in spin locks.
Since on Android Mutexes are very efficient, we just use that instead.
This might fix #2197

disable spinlocks on ARMv7

---

filament/src/fg/FrameGraphPass.h

`execute` is an rvalue reference and not a forwarding reference, so `std::move` is more appropriate

Replaced unnecessary std::forward with std::move

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/CMakeLists.txt
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/materials/blitHigh.mat
filament/src/materials/blitLow.mat
filament/src/materials/blitMedium.mat

It controls the quality of the upsampling filter. This can help a lot
if heavy scaling is needed to maintain performance, it also helps if
MSAA is not enabled.
There are 3 quality levels, low, medium and high. 1, 4 and 9 bilinear
taps are used for each level respectively. The high quality setting
employs a tent filter.

Add a quality option to dynamic-scaling

---

filament/src/materials/bloomUpsample.mat

We were not using the correct offsets, however because everything
was so blurry, it wasn't obvious that something was wrong.
This should result in a bit smoother bloom effect.

fix bloom upsample shaders

---

libs/filaflat/include/filaflat/BlobDictionary.h
libs/filamat/src/GLSLPostProcessor.cpp
libs/matdbg/include/matdbg/ShaderExtractor.h
libs/matdbg/src/ShaderExtractor.cpp
tools/matinfo/src/main.cpp

This change adds new commands to matinfo to print dictionaries.
This feature is useful to debug dictionaries, and I just used
it to identify that using a shared dictionary would save ~12 KiB
in the Android build. The macOS build (GLSL + Metal) would go
down to 71 KiB from 136 KiB.
The SPIRV to Metal conversion leaves leading spaces and some
comments. This change also runs the shrinker on optimized Metal
shaders to further reduce the size of shaders.

matinfo can print dictionaries, shrink Metal dictionary

---

libs/utils/include/utils/algorithm.h
libs/utils/test/test_algorithm.cpp

Our fallback 64-bits ctz() was completely wrong. 
The unit tests were wrong too.
The code was also more complex than it needed to be, because we 
only need versions for uint32_t and uint64_t, in the details
namespace.

fix utils::ctz() when builtins are not available

---

filament/CMakeLists.txt
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/details/ShadowMap.h
filament/src/details/View.h
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/include/private/filament/Variant.h
shaders/src/getters.fs
shaders/src/getters.vs
shaders/src/inputs.fs
shaders/src/inputs.vs
shaders/src/light_directional.fs
shaders/src/light_punctual.fs
shaders/src/main.vs
shaders/src/shadowing.vs

Add spot light shadow support to Filament. This removes a lot of the logic inside of `ShadowMap`, which was added to `ShadowMapManager`. This also adds the view logic for calling into `ShadowMapManager` and the shader code to sample the shadow map array.

Add support for spot light shadows

---

libs/filamat/src/GLSLPostProcessor.cpp

deactivate "mergeReturnPass" because it triggers a segfault with
AMD drivers on MacOS.

update GLSLPostProcessor optimization passes to latest

---

filament/src/fg/fg/RenderTargetResourceEntry.cpp
filament/src/fg/fg/RenderTargetResourceEntry.h

Imported render targets are only partially implemented, which
caused a discard flags bug. It would happen when an imported
render target is used more than once like when using SSrefr
without tone mapping.  In that case, the 2nd pass would use the same
discard flags as the first pass.

workaround a framegraph bug with imported rendertargets

---

filament/backend/src/SamplerGroup.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/UniformBuffer.h
filament/src/View.cpp
filament/src/details/Renderer.h
filament/src/details/View.h
filament/src/fg/FrameGraph.h

- decouple the depth and ssao passes, so that the depth
pass could be used by another client, down the framegraph
- set uniforms/samplers from the execute closure of the color pass,
instead of using a separate pass. This is more correct and it 
potentially reduces calls to commitUniforms.
- make setSampler check that the value set is different,
the idea here is that it's much more costly to have to commit the
samplers rather than having to compare them. Also realistically we
don't have a lot of samplers in a frame, so that's not a lot of
compares.
- one downside of this change is that commands for the SSAO pass are
always generated, we will fix that in an upcoming change.

Cleanup render loop to prepare for more features

---

filament/src/RenderPass.h

this helps a lot with vegetations, which often uses alpha masking

include alpha-masked objects in SSAO

---

CMakeLists.txt

This caused failures in CI builds.
This reverts commit c132ede510c14bf2e67148c922e4c6182a3c5d88.

Revert "enable ASAN's -fsanitize=address in debug builds"

---

.github/workflows/ios-continuous.yml
.github/workflows/presubmit.yml

The iOS CI script should have caught the recent ASAN linker errors.

Fix iOS build samples CI

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/LightManager.cpp
android/filament-android/src/main/cpp/RenderableManager.cpp
android/filament-android/src/main/java/com/google/android/filament/LightManager.java
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
filament/include/filament/LightManager.h
filament/include/filament/RenderableManager.h
filament/src/Renderer.cpp
filament/src/Scene.cpp
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
filament/src/details/View.h
filament/src/fg/FrameGraph.cpp
libs/filabridge/include/private/filament/SibGenerator.h
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/src/SibGenerator.cpp
libs/filabridge/src/UibGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/gltfio/include/gltfio/SimpleViewer.h
samples/material_sandbox.cpp
samples/material_sandbox.h
shaders/src/light_directional.fs
shaders/src/shadowing.fs

Large scene using LiSPSM, without and with screen-space contact shadows:

Add support for screen-space contact shadows

---

shaders/src/getters.vs

When reconstructing the position from clip-space, we need to apply
the .w divide.
Also use getWorldFromClipMatrix() directly.

fix computation of shading_posiiton for clip space domain shader

---

libs/utils/include/utils/CString.h
libs/utils/include/utils/JobSystem.h
libs/utils/include/utils/Log.h
libs/utils/include/utils/NameComponentManager.h
libs/utils/include/utils/Panic.h
libs/utils/include/utils/Path.h
libs/utils/include/utils/SingleInstanceComponentManager.h
libs/utils/include/utils/bitset.h
libs/utils/include/utils/ostream.h

Expose APIs used by other libraries' public headers and by sample apps.
This PR fixes #2265.

Expose libutils APIs that should have been public

---

libs/gltfio/include/gltfio/SimpleViewer.h

They don't look very good since most glTF files are single, small-ish objects.

Turn off contact shadows by default in gltf viewer

---

shaders/src/light_indirect.fs

We 4-tap filter the diffuse map, which generally is very small
(e.g. 16x16), to improve quality a bit.

improve quality of diffuse sampling on desktop

---

filament/backend/src/opengl/PlatformCocoaGL.mm

When using Filament with GLFW on macOS (10.14.6, Radeon Pro Vega 20 4 GB), resizing a window does not resize the backing store. At least, it does not change the number of pixels that are displayed. I created a program that sets the clear color to white and then changes it to a random color on each resize (attached). Using just GLFW and glClear, the window resized correctly. With GLFW + Filament and calling view->setClearColor(), the initial draw is correct, but resizing leaves red areas. If the window is made larger, the original area is a random color but the right and bottom are red. If the window is made smaller, it looks like the original area is translated down. I preferred debugging by opening the window on a low-res monitor and then moving it to my retina laptop monitor; exactly …

Fixes resizing window not resizing the OpenGL backing store on macOS

---

libs/utils/CMakeLists.txt

Fix "[Expose libutils APIs that should have been public](https://github.com/google/filament/commit/45df197bd62681e1dd5899f8b7e4bc083a801cb8)" commit which does not install the subfolder to dest dir properly

Fix cmakelist to install subdir properly

---

android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/View.cpp
libs/gltfio/include/gltfio/SimpleViewer.h
samples/material_sandbox.cpp
shaders/src/fog.fs

- handle heightFalloff=0 (i.e. fog doesn't depend on height) correctly,
previously, a divide-by-zero on the cpu side would get in the way.
The fix is to clamp heightFalloff to a small-enough value, and to
make sure that this is handled correctly in the shader.
- default fog distance is 0 instead of 1m
- inScatteringSize parameter should be allowed to be large in samples

fog improvements

---

BUILDING.md
build.sh
third_party/spirv-tools/CMakeLists.txt
third_party/spirv-tools/filament-specific-changes.patch

Be compatible with CMake 3.10 again

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h

we now always mask out target bits that don't exist in the render
target before converting them to GLenums.
Fixes #2285

fix an assert() when using custom render targets

---

libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/include/gltfio/SimpleViewer.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp

This should make it easier to test lighting setups. Note: Blender can export glTF files with lights, but it does not write out the correct intensity values.

Support lights in gltfio / gltf_viewer

---

.github/workflows/android-continuous.yml
.github/workflows/ios-continuous.yml
.github/workflows/linux-continuous.yml
.github/workflows/mac-continuous.yml
.github/workflows/presubmit.yml
.github/workflows/release.yml
.github/workflows/web-continuous.yml
.github/workflows/windows-continuous.yml
build/windows/build-github.bat

Previous Windows CI jobs were running out of server disk space. This isn't a permanent solution, but gives us an extra gig of wiggle-room by building Debug first (which requires more temp space) and switching to Checkout v2, which does a shallow checkout.

Try to fix Windows build by reducing disk space footprint

---

filament/src/PostProcessManager.cpp
filament/src/Renderer.cpp
filament/src/Scene.cpp
filament/src/details/Renderer.h
filament/src/details/Scene.h

the structure (depth path) wasn't culled even if both ssao and
contact-shadows were disabled.

make sure "structure" pass is culled when not needed

---

filament/src/Renderer.cpp
filament/src/fg/fg/RenderTargetResourceEntry.cpp
samples/app/FilamentApp.cpp

the view clear flags would not be honored when rendering directly
into an imported render target.
note: now that this works this could cause an issue when using
multiple views side-by-side and one of them doesn't have a skybox,
that view will trigger a clear of the whole buffer (because clears
clear everything, not just the viewport).
A solution will come in a later PR.
Fixes #2312

fix a clearing bug with imported rendertargets

---

android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
filament/backend/CMakeLists.txt
filament/backend/include/backend/Handle.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/DriverBase.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/TimerQuery.cpp
filament/backend/src/opengl/TimerQuery.h
filament/backend/src/opengl/gl_headers.cpp
filament/backend/src/opengl/gl_headers.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/FrameInfo.cpp
filament/src/FrameInfo.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h

This adds a simple query API to the backend.
There are 2 methods to create/destroy queries, which are
essentially futures.  And 3 methods to mesure elapsed time:
beginTimerQuery/endTimerQuery and getTimerQueryValue.
The begin/end pair is not nestable.
On the GL backend side, there are 2 implementations of this, one uses
arb_timer_query or disjoint_timer_query, the other uses fences.
We need both implementations because on some GPUs, including
qualcomm's elapsed-time timer query is useless, as it measures
cpu time. 
Metal/Vulkan implementations will be part of subsequent PRs. Vulkan
will be able to implement this with vkWriteTimestamp which is
reported to be accurate.
An immediate benefit is that we can now get frame times on MacOS, which
should allow it to use dynamic-resolution.

add support for timer queries in the backend

---

filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/TimerQuery.cpp

It's possible for a timer query to be destroyed before the result is
known, in this case, we don't want to write through that pointer!

fix a potential use-after-free

---

libs/utils/include/utils/JobSystem.h
libs/utils/src/JobSystem.cpp

mThreadMap needs to be protected as it's accessed from multiple threads.

fix a race-condition in JobSystem

---

android/filament-android/src/main/cpp/Texture.cpp
android/filament-android/src/main/java/com/google/android/filament/Texture.java
android/filament-utils-android/src/main/java/com/google/android/filament/utils/TextureLoader.kt
filament/backend/include/backend/DriverEnums.h
filament/backend/include/backend/PixelBufferDescriptor.h
filament/backend/src/opengl/GLUtils.h
web/filament-js/filament.d.ts
web/filament-js/jsenums.cpp

This requires exposing a new `USHORT_565` pixel data type. Fixes #2336.

Fix support for 565 textures

---

shaders/src/ambient_occlusion.fs
shaders/src/light_directional.fs

On metals (made only of specular light), specular AO can
create large black spots. This change simply kills specular
AO to avoid this artifact. In practice we should take into
account multiple bounces but this is rasterization...

Kill specular AO at low roughness

---

filament/backend/include/backend/Handle.h
filament/backend/src/DriverBase.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/OpenGLProgram.h
filament/src/Fence.cpp
filament/src/details/View.h

Until now, only the memory of Hw handes was allocated synchronously,
handles were constructed later asynchronously. This was error prone
with the few (but growing) synchronous calls we have.
Now we have an init<> call that allocates and constructs handles synchronously,
the asynchronous construction if needed, is still performed with construct<>,
which is now implemented as "destroy+construct", this is okay because
most of our handles have trivial dtors.
This fixes a race with TimerQuery and Fence. Fences are still not fully 
working though, but at least won't access uninitialized memory.
Currently backend fences MUST be used trough FFence.

[GL backend] ensure that Handle<> are synchronously constructed

---

libs/filagui/src/ImGuiHelper.cpp
libs/filagui/src/materials/uiBlit.mat

Stores font texture as RGBA instead of R. This is because the ui material will not be compatible for RGBA textures, as it is expecting an R texture. I was unable get a texture with ALPHA format to function as I wanted.
This also removes material instance caching by scissor rect. Instead it just assigns the scissor rect to each new primitive, as well as an optional texture.

Texture support for filagui/ImGui

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/backend/Handle.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/DriverBase.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/FrameSkipper.cpp
filament/src/details/FrameSkipper.h

A sync object for us is like a fence that cannot be waited on. It can
only be queried.
This is useful for filament to know if (not when) some previous
commands have finished executing.
In OpenGL this is different from "fences" which only exist in EGL and
can be waited on from any thread.
"sync" objects correspond to GLsync object in OpenGL and are widely
supported, as opposed to EGL fences.
So we use the term "fence" to refer to synchronization object that are
external to OpenGL and the term "sync" for the native gl synchronization
objects. This distinction may or may not exist in other APIs.
rewrite the FrameSkipper to use this, which enables it on MacOS.

Add "sync" objects to the driver

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/TimerQuery.cpp
filament/backend/src/opengl/TimerQuery.h
filament/src/Renderer.cpp

On drivers that don't implement timer queries properly, we use
fences instead, however we can't use a fence to determine the start
time of the GPU work (only the end time). To workaround this we
use the last call to glFlush() as a proxy.
At least on Pixel it works very well.
We also remove all mid-frame calls to flush(), we did this to kick
cpu work early, but it's not as efficient as overlapping the work
with the previous frame, it increases latency a bit though.

better GPU timings on Android

---

RELEASE_NOTES.md
android/filamat-android/src/main/cpp/MaterialBuilder.cpp
android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java
docs/Materials.html
docs/Materials.md.html
filament/include/filament/Scene.h
filament/src/Renderer.cpp
libs/filabridge/include/filament/MaterialEnums.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/MaterialInfo.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/filamat/tests/test_filamat.cpp
libs/gltfio/materials/ubershader.mat.in
libs/gltfio/src/MaterialGenerator.cpp
samples/sample_full_pbr.cpp
shaders/src/ambient_occlusion.fs
tools/matc/src/matc/ParametersProcessor.cpp

The user can now choose amongst 3 specular AO methods:
- None, specAO is off
- Simple, specAO is inferred from roughness and diffuse AO:
- Bent normals, specAO is computed accurately from cone intersections:
The last method is more expensive but produces the best results.
This change also fixes a few issues:
- Rename materialRefraction() and materialRefractionType() for
consistency
- Fixes user time in shaders

Change specularAmbientOcclusion from boolean to enum

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/src/FrameSkipper.cpp
filament/src/Renderer.cpp

in OpenGL we need to check the status of queries on the gl thread,
so we did this in when beginFrame was called -- however, this is
too late, because beginFrame is asynchronous, so we were always
behind by 1 frame.
we fix this by running the callbacks more often.

fix a some problems with timer queries in the OpenGL backend

---

libs/gltfio/CMakeLists.txt
libs/gltfio/materials/gltflite.mat.in

gltfio-lite now has its own template rather than re-using the ubershader one, which allows us to remove support for various glTF extensions like texture matrices.

gltfio-lite optimization

---

filament/backend/src/opengl/TimerQuery.cpp
filament/src/Renderer.cpp

we now flush the backend (e.g. GL) after the color pass, this a 
good time because a lot of GPU work has been queued by that point, this
allows the GPU to start while we queue the post-processing commands.
This reduces latency by about 2.5ms on pixel4.

improve latency a bit

---

shaders/src/post_process.fs

we clamp the output of post_process materials to 0,FLT16_MAX

fix shader overflows leading to black pixels

---

filament/backend/src/metal/MetalDriver.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

This implements `createSync` and `getSyncStatus` in Metal. It also fixes a race condition with fences in Metal.

Revamp MetalFence and implement Metal sync objects

---

samples/animation.cpp
samples/depthtesting.cpp
samples/hellopbr.cpp
samples/hellotriangle.cpp
samples/strobecolor.cpp
samples/suzanne.cpp
samples/texturedquad.cpp
samples/vbotest.cpp
samples/viewtest.cpp

There is nothing specific to Vulkan in these tests, I meant to remove
the backend override when I removed the `vk_` prefix last week.

Desktop samples now use default backend.

---

android/filament-android/src/main/java/com/google/android/filament/Renderer.java
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/include/filament/Renderer.h
filament/src/FrameSkipper.cpp
filament/src/Renderer.cpp
filament/src/details/Renderer.h

ignoring beginFrame() return value is allowed, but doing so would
leave filament in an invalid state.
we now make sure that we don't execute any code after determining whether
the frame should be skipped, and execute the remainder of beginFrame() 
upon the first call to render(View*).
We also make sure the FrameSkipper can deal with its endFrame() being 
called when the current fence hasn't signaled.

fix issues with ignoring beginFrame() return value

---

filament/src/PostProcessManager.cpp

the depth buffer in this case is only used for 
skipping the skybox

ssao blur: don't forget to attach the depth buffer

---

CMakeLists.txt
libs/math/include/math/scalar.h
tools/cso-lut/CMakeLists.txt
tools/cso-lut/README.md
tools/cso-lut/src/main.cpp

This tool is for internal usage only. It computes a 3D lookup table
for cone/sphere occlusion computations. These can be used to implement
specular occlusion, directional ambient occlusion, etc.

Add new tool cso-lut

---

RELEASE_NOTES.md
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp
filament/src/View.cpp
filament/src/details/View.h

the problem was that the actual viewport's origin can be different
from the viewport set by the user, for instance when the view is
rendered in an intermediate buffer.

Fix point/spot lights when viewport is not in 0,0

---

filament/src/Engine.cpp
filament/src/IndexBuffer.cpp
filament/src/IndirectLight.cpp
filament/src/Material.cpp
filament/src/RenderTarget.cpp
filament/src/Skybox.cpp
filament/src/Stream.cpp
filament/src/Texture.cpp
filament/src/VertexBuffer.cpp
filament/src/components/LightManager.cpp
filament/src/components/RenderableManager.cpp
filament/src/details/Engine.h

Originally it was used for validating the Engine* used, but this
makes no sense (no reason to validate this pointer more than any
other one).
The list also made sure that Engine instances were automatically 
destroyed when the filament library was unloaded, but again, there
is no reason to do this -- it's C++ after all!

get rid of the static list of Engines

---

shaders/src/ambient_occlusion.fs
shaders/src/common_math.fs

The two spherical caps used in the intersection computations
have angles in the range 0..pi/2.

Use a simplified fast acos() for specular AO

---

filament/src/Engine.cpp

It looks like using `half` during static initialization causes issues,
where sometimes these values are not initialized correctly.
The problem goes away when some other random static initializer 
executes, which suggests a race, except there is only a single thread
at that point.
I think for some reason `half4` are not put in the data section where
float4 are.
note: we don't understand the exact issue yet

fix a strange static initialization problem on macOS

---

filament/src/Froxelizer.cpp

we would be short by one froxel on the left, usually this wasn't
a problem due to the light falloff.

Fix a froxelization bug

---

filament/include/filament/LightManager.h
filament/src/components/LightManager.cpp
libs/gltfio/src/AssetLoader.cpp
shaders/src/light_punctual.fs

filament spotlights use half-angles, which is the same as gltf.

fix spotlight documentation and clamping

---

libs/filamat/src/sca/GLSLTools.cpp

Our enum-to-string converter was throwing an exception rather than
printing a friendly error message in some cases.
To be specific, I hit this when writing:
vec3 worldTangent;
toTangentFrame(mesh_tangents, material.worldNormal, worldTangent);

matc: do not crash when material passes bad out arg.

---

android/filament-android/src/main/cpp/LightManager.cpp
android/filament-android/src/main/java/com/google/android/filament/LightManager.java
filament/include/filament/LightManager.h
filament/src/Scene.cpp
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/components/LightManager.cpp
filament/src/components/LightManager.h
filament/src/details/Scene.h
filament/src/details/View.h
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/src/UibGenerator.cpp
libs/gltfio/include/gltfio/SimpleViewer.h
shaders/src/common_lighting.fs
shaders/src/light_directional.fs
shaders/src/light_punctual.fs
shaders/src/shading_unlit.fs

- contact shadows are now supported for point and spot lights
- and are now independent from regular shadows, that is they can
be enabled without enabling regular shadows
The only limitation currently is that the distance and step count for
ALL contact shadow are taken from the directional light options.

improve contact shadows support

---

RELEASE_NOTES.md
docs/Materials.html
docs/Materials.md.html
libs/filamentapp/src/MeshAssimp.cpp
libs/gltfio/materials/gltflite.mat.in
libs/gltfio/materials/ubershader.mat.in
libs/gltfio/src/MaterialGenerator.cpp
samples/material_sandbox.cpp
samples/material_sandbox.h
shaders/src/material_inputs.fs
shaders/src/shading_lit.fs
shaders/src/shading_unlit.fs

Emissive was previously defined in exposure compensation stops, which
was confusing to many. It is now a value in nits, with the alpha
channel controlling how much the camera exposure affects the emissive.
At 0, the emissive value is just added to the final pixel color, at
1 the emissive value is multiplied by the exposure just like with
regular lights.
The intensity of the emissive property can be computed from an
exposure value (EV) easily with the following formula:
emissive.rgb = emissive.rgb * pow(2.0, EV - 3.0);
This formula is available as Exposure::luminance(float) already
in Filament.

Change how emissive works

---

tools/mipgen/src/main.cpp

This option (short: -m) can be used to limit the number of mip
levels generated. Using -m 1 allows to use mipgen as a cheap-ish
image converter.
Fixes #2419.

Add new --mip-levels option to mipgen

---

filament/src/PostProcessManager.cpp

it's not good enough to clear the SSAO buffer, we also need to clear
*all* buffers involved in the final SSAO buffer, in particular the
bilateral blur buffers.
all this clearing is needed because we ignore skybox pixels based on the
depth buffer test, yet we need an initialized buffer.

fix an SSAO bug with transparents objects

---

filament/backend/CMakeLists.txt
libs/filabridge/CMakeLists.txt
libs/filaflat/CMakeLists.txt
samples/CMakeLists.txt
tools/matc/CMakeLists.txt

This adds a new "backend_headers" target because small changes to any
backend cpp file was resulting in a huge build, causing materials to be
rebuilt, etc. Note that filabridge only needs DriverEnums, nothing else.

Improve build turnaround by breaking dependencies.

---

libs/matdbg/CMakeLists.txt
samples/CMakeLists.txt
samples/hellopbr.cpp
samples/suzanne.cpp
third_party/civetweb/tnt/CMakeLists.txt
tools/matinfo/CMakeLists.txt

This change allows us to modify + test Filament without re-invoking resgen.
The only apps that need the monkey filamesh are `suzanne` and `hellopbr`, so they are now the only apps that have it as a dependency.

Remove monkey mesh dependency from samples.

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/src/Texture.cpp

Chrome was dumping GL_INVALID_ENUM.  According to the spec, swizzling is not supported.
> Texture swizzles can not be implemented in a performant manner on Direct3D based WebGL implementations. Applications relying on this functionality would run significantly more slowly on those implementations. Applications are still able to swizzle results of texture fetches in shaders and swizzle texture data before uploading without this interface.

Fix swizzle error in WebGL.

---

filament/backend/src/opengl/OpenGLProgram.cpp

sometimes this happens because the shader actually doesn't use the
texture (e.g. in a uber shader model), however this is an error in
metal and vulkan.

add a warning log when there is no texture bound to a used texture unit

---

filament/src/Renderer.cpp
libs/filagui/src/ImGuiHelper.cpp
libs/filamentapp/src/FilamentApp.cpp
samples/gltf_viewer.cpp

- there was a case where setting a clear color on the Renderer
would clear a blended view with that color instead of transparent
pixels.
- move configuring the ui view into ImGuiHelper
- fix gltf_viewer sidebar so its background is not uninitialized

more clear fixes

---

filament/src/Froxelizer.cpp

- fix a floating-point exception when the viewport is too small, this could lead to w/h froxel count to be 0, later leading to divide-by-zero. There could also be a case where the viewport itself had w/h of zero, also leading to divide-by-zero exception.
- the last froxel on the right was sometimes improperly rejected, this would happen when a sphere (light) would not actually intersect any plane, but would he contained by the froxel.

fix more froxelization bugs

---

android/filament-utils-android/src/main/cpp/Manipulator.cpp
android/filament-utils-android/src/main/java/com/google/android/filament/utils/GestureDetector.kt
android/filament-utils-android/src/main/java/com/google/android/filament/utils/Manipulator.java
libs/camutils/CMakeLists.txt
libs/camutils/include/camutils/Bookmark.h
libs/camutils/include/camutils/Manipulator.h
libs/camutils/src/FreeFlightManipulator.h
libs/camutils/src/Manipulator.cpp
libs/camutils/src/MapManipulator.h
libs/camutils/src/OrbitManipulator.h
libs/filamentapp/include/filamentapp/FilamentApp.h
libs/filamentapp/src/FilamentApp.cpp

This adds a new camera manipulator that allows WASD movement with nodal camera panning. This PR only adds the new manipulator type, it doesn't enable it yet inside of `FilamentApp` (we'll need to decide how we want to expose it, possibly through a command-line flag).

Add a new free flight camera manipulator

---

filament/backend/src/vulkan/VulkanHandles.cpp

The Vulkan backend was failing to clear the depth buffer in apps that do
not have a textured skybox, such as hellotriangle.

Vulkan: fix bad depth clears.

---

filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

In Vulkan, the arrayness of a texture is an aspect of the "image view", not the image itself.
In my earlier attempt I used `VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT` on the image, which MoltenVK does not support. Confusingly, that flag is actually meant for rendering into a slice of a 3D texture, which we are not doing.
Vulkan is hard.

Vulkan: add support for 2D texture arrays.

---

filament/backend/src/vulkan/VulkanDriver.cpp

It is illegal for shaders to sample from images that have a blit layout.

Vulkan: fix InvalidImageLayout validation errors.

---

.github/workflows/android-continuous.yml
.github/workflows/ios-continuous.yml
.github/workflows/linux-continuous.yml
.github/workflows/mac-continuous.yml
.github/workflows/presubmit.yml
.github/workflows/release.yml
.github/workflows/web-continuous.yml
BUILDING.md
build/README.md
build/android/build.sh
build/ios/build.sh
build/linux/build.sh
build/linux/ci-common.sh
build/mac/build.sh
build/web/build.sh

Fixes #2455.
- Display a prompt and require user confirmation
- Only runs system install commands in GitHub CI environments
- Add extra README file detailing what the scripts are for

Make CI scripts safer

---

filament/src/components/LightManager.cpp

Some of the options in `ShadowOptions` were not being copied overly correctly from the builder.

Respect all of ShadowOptions when building a light

---

filament/include/filament/LightManager.h

the Instance id was off-by-one and didn't match the
given entity.
in gltf_viewer this caused contact shadows to not work
when there was only a single directional light

fix LightManager::forEachComponent()

---

android/filament-android/src/main/cpp/LightManager.cpp
android/filament-android/src/main/java/com/google/android/filament/LightManager.java
filament/include/filament/LightManager.h
filament/src/components/LightManager.cpp
filament/src/components/LightManager.h
libs/gltfio/src/AssetLoader.cpp

This adds a new `intensityCandela` builder method and `setIntensityCandela` API method for updating a punctual light's intensity in candela, as opposed to lumens or watts.

Add intensityCandela API to LightManager

---

filament/src/ShadowMap.cpp
filament/src/details/ShadowMap.h

This fixes an issue when using stable directional shadows. See how the shadows disappear when the light's direction becomes perfectly orthogonal to the camera:
https://drive.google.com/a/google.com/file/d/1qWTavtkbL2PO-oEVaTZ9bJwZGbMw7ZMt/view?usp=sharing

Fix incorrect lightspace 2D bounds calculation for stable shadows

---

filament/src/details/Camera.h

Make sure that Camera returns a positive field-of-view, even when
the projection matrix has a symmetry (negative scaling).

fix a arithmetic error in SSR when a symmetry was present

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h

In OpenGL with use glInvalidateFramebuffer() for hinting controlling
the load/store of tiles. However, glInvalidateFramebuffer() conceptually
destroys the content of the framebuffer attachment.
This causes a problem when we want for instance to use a buffer for
reading only (e.g. a depth buffer) in multiple passes. In such
scenario, the attachment will be marked as "discard" (which is a
misnomer for storeOp==DONT_CARE in vulkan parlance), without the
intention of making the buffer invalid.
We fix this by ignoring the discardEnd flags entirely if a buffer
has not been written. In this case, we relying on the driver to not
write the tiles out -- but we don't have any other way to express
this in GL.
This issue cannot be encountered currently because the framegraph 
is not aggressive enough …

GL backend: Fix an issue with discardEnd flags

---

docs/Materials.md.html
shaders/src/ambient_occlusion.fs
shaders/src/common_shading.fs
shaders/src/getters.fs
shaders/src/inputs.fs
shaders/src/inputs.vs
shaders/src/light_punctual.fs
shaders/src/main.vs
shaders/src/shading_parameters.fs

This fixes dynamic lighting and SSAO when a viewport is not in 0,0.
In practice this currently happens only when all post-processing is
disabled.
Instead of using gl_FragCoord we introduce a new API, 
getNormalizedViewportCoord(), which as the name implies returns
normalized [0, 1] viewport coordinates with origin at the bottom-left,
on all platforms.
This is implemented in this PR by interpolating gl_Position.

Don't use gl_FragCoord anywhere as it breaks with custom viewports

---

android/gradle/wrapper/gradle-wrapper.properties

Updated gradle version to 6.3 for openjdk 13 support
`./build.sh -p android release` was getting error `FilamentPlugin.groovy' Unsupported class file major version 57` when java_home is set to openjdk 13

Adding support for openjdk 13

---

filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp

This fixes a crash with `lightbulb -m`.
- During VkImage creation, the subresource depth should be 1 since it is
meant for 3D textures.
- Render targets should select a single level from an array texture, not
all of them.

Vulkan: fix array textures.

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
filament/src/details/View.h
filament/src/materials/dof.mat
filament/src/materials/dofBlur.mat
filament/src/materials/dofUtils.fs

- bokeh rotates with the aperture diameter
- match sample count on cpu and cpu sides which affects CoC calculation
- feather blur radius to avoid visible "steps" in bokeh size

improvements to DoF

---

libs/filamat/src/GLSLPostProcessor.cpp

this fixes a crasher when using --optimize-size

remove CreateEliminateDeadMembersPass which breaks UBO layout

---

android/Windows.md

Building with Clang on Windows was deprecated https://github.com/google/filament/pull/2243
However `android/Windows.md` still refers Clang usage.

Update Android building instruction on Windows

---

filament/include/filament/Frustum.h
filament/include/filament/LightManager.h
filament/src/Frustum.cpp
filament/src/ShadowMap.cpp
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/components/LightManager.cpp
filament/src/details/Engine.h
filament/src/details/ShadowMap.h
filament/src/details/ShadowMapManager.h
filament/src/details/View.h
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/EngineEnums.h
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/src/UibGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/gltfio/include/gltfio/SimpleViewer.h
shaders/CMakeLists.txt
shaders/src/common_graphics.fs
shaders/src/common_shadowing.fs
shaders/src/getters.fs
shaders/src/getters.vs
shaders/src/light_directional.fs
shaders/src/main.fs
shaders/src/main.vs
shaders/src/shading_unlit.fs

This adds basic CSM support with a uniform split scheme, and no blending between cascades.

Add rudimentary cascading shadow map support

---

libs/gltfio/include/gltfio/AssetLoader.h
libs/gltfio/src/AssetLoader.cpp

Currently AssetLoader only load name with nodes contains mesh. The hotfix load every node's name no matter the mesh. It'll set the node name "node" if name not found.
Test
test with mac and gltf_viewer devtool

Fix AssetLoader to load name of node without mesh

---

android/common/CallbackUtils.cpp
android/common/CallbackUtils.h
android/common/NioUtils.cpp
android/common/NioUtils.h
android/filament-android/src/main/cpp/Texture.cpp

- we were allocating objects with a destructor in the command stream
which is always invalid because there is no guarantee that when 
the callback is called, the underlaying memory is still valid
(and it wasn't).
- AutoBuffer move-ctor wasn't moving some of its state, which would
lead to destroying the same ref several times.

fix JNI objects allocation and memory corruption
