google/filament

filament/src/ShadowMapManager.cpp
libs/filabridge/include/private/filament/UibGenerator.h
libs/gltfio/include/gltfio/SimpleViewer.h
shaders/src/light_directional.fs

There were a few bugs sampling from an outdated shadow cascades. We should only sample from cascades that have visible shadows, otherwise the shadow layer may have garbage.

Fix, don't sample from cascades without visible shadows

---

libs/gltfio/include/gltfio/SimpleViewer.h
libs/gltfio/src/MaterialGenerator.cpp
libs/gltfio/src/UbershaderLoader.cpp

To see proof that this works, use gltf_viewer with -u and examine the
node hierarchy. You will now see the correct material names instead of
the ubershader names.

gltfio: use the new material name feature.

---

android/build.gradle

Build on Windows fails due to incorrect path, backalshes instead of forward slashes.
```
* What went wrong:
Execution failed for task ':filament-utils-android:generateJsonModelFullRelease'.
> C:\Users\silentnuke\Projects\filament\android\filament-utils-android\CMakeLists.txt : C/C++ fullRelease|x86 : CMake Error at C:/Users/silentnuke/Projects/filament/android/gltfio-android/CMakeLists.txt:75 (add_library):
Syntax error in cmake code when parsing string
C:\Users\silentnuke\Projects\filament\out\android-release\filament/include/gltfio/resources/gltfresources_lite.h
Invalid character escape '\U'.
```
There is a few approaches to fix that:
1. Normalize path in Cmake using `file(TO_CMAKE_PATH)`. However this would require more changes.
2. IMHO more preferable, fix once in Gradle before …

Fix filament-utils-android build on Windows

---

android/Windows.md

During build on Windows I faced a few issues which make sense to clarify in the instruction:
1.  `FilamentPlugin.groovy` relies on the installed desktop host tools. However Windows building instruction doesn't mention that step.
> Execution failed for task ':samples:sample-gltf-viewer:filamentGenerateIbl'.
> Could not find filament\out\release\filament\bin\cmgen.exe. Ensure Filament has been built/installed before building this app.
2. Build instraction mentions how to build for single abi by modifying a `build.gradle` , however there is an easy way - passing `filament_abis` parameter.
3. Building SDK takes long time, since it builds all samples. So we can note that we can skip it by passing `filament_skip_samples` flag.

Clarify Windows build instructions

---

android/filament-android/src/main/cpp/MaterialInstance.cpp
android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
android/gltfio-android/src/main/cpp/FilamentAsset.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java

Tested locally by hacking gltf-viewer on Android, added the following
lines to MainActivity:
```kotlin
for (mat in modelViewer.asset!!.materialInstances) {
Log.d("gltf-viewer", mat.name)
}
```

gltfio: expose getMaterialInstances to Java.

---

filament/include/filament/Engine.h
filament/src/Engine.cpp
filament/src/ShadowMap.cpp

- When creating a Camera component, it is the responsibility of the caller
to destroy the Entity. ShadowMap didn't do that, so it would leak two
entities.
- When destroying a Camera component with the legacy (and deprecated)
API, Engine::destroyCamera() should destroy the associated Entity
(and was documented as doing so). However, it actually didn't.
- don't use the static EntityManager is ShadowMap.

Fix Entity leaks with Camera

---

RELEASE_NOTES.md
android/filament-android/src/main/java/com/google/android/filament/IndirectLight.java
android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java
android/filament-android/src/main/java/com/google/android/filament/Skybox.java
android/filament-android/src/main/java/com/google/android/filament/Texture.java
android/filament-utils-android/src/main/java/com/google/android/filament/utils/KtxLoader.kt
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java

This removes (rather than deprecates) all public constructors that
take a native pointer without an accompanying Engine.
Most notably, MaterialInstance had a public pointer constructor which
is now package private. This means that FilamentAsset needs an Engine,
so it now takes the one from AssetLoader.

Make JNI constructors private unless they take Engine.

---

libs/utils/include/utils/EntityManager.h
libs/utils/src/EntityManager.cpp
libs/utils/src/EntityManagerImpl.h

Set FILAMENT_UTILS_TRACK_ENTITIES to true when building libutils to
activate entity tracking. This adds two public methods:
getActiveEntities() and dumpActiveEntities() the later displays the
stack trace of where the remaining entities were allocated.
This is useful for tracking leaks.

debug option to track Entities

---

filament/src/materials/tonemapping.mat
shaders/src/dithering.fs

- only triangular noise needs to be scaled between +/-1, other noises
have a uniform distribution and need to be scaled between +/-0.5
- all dither routines work in RGBA
- fixed FXAA in opaque mode when dithering modified the alpha channel
(which is used by FXAA). This fixes flickering when FXAA and dithering
was enabled.
- use triangular noise dithering on mobile and desktop. The cost in
not measurable on a pixel 4 / 1080p, and the quality is better.
- refactor dithering code a bit such that:
- noise methods are not temporal
- all dither functions have the same structure

Fix a few issues with dithering

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
libs/utils/include/utils/Systrace.h

EXT_debug_marker is not supported GL debuggers won't show these
markers, so as an alternative, we dump them in systrace.

use systrace when EXT_debug_marker is not supported

---

filament/src/fg/FrameGraph.cpp

this was a misguided optimization, on low-end devices this actually
has a large overhead (presumably because of the smaller cache and
increased branch missprediction as well as extra synchronization).
on some low-end devices we see the gl thread go from ~40ms to ~10ms
with the gltf sample.

don't kick the driver thread after each framegraph pass

---

filament/backend/src/android/ExternalStreamManagerAndroid.cpp
filament/backend/src/android/ExternalStreamManagerAndroid.h

We were not holding a global ref on more recent version of android,
this made the Stream API inconsistant. 
Filament now always keeps a global ref on the surfacetexture while in
use.

always hold a global ref on the surfacetexture

---

filament/backend/src/opengl/PlatformCocoaGL.mm
libs/filamentapp/src/FilamentApp.cpp

This is done for consistency with the Android samples. Tested with
gltf_viewer against Vulkan, Metal, and OpenGL. Dragged window between
high DPI and low DPI displays.
Since resizing does not trigger the "NSView has changed" handler in
PlatformCocoaGL, it now must to detect a resize in order to make the
required call to NSOpenGLContext::update() as per the following
documentation.
https://developer.apple.com/documentation/appkit/nsopenglcontext/1436135-update
Fixes #2528

FilamentApp: do not recreate SwapChain upon resize.

---

libs/filamentapp/include/filamentapp/Config.h
libs/filamentapp/src/FilamentApp.cpp
samples/frame_generator.cpp

These changes make it easier to test headless rendering in macOS.
I verified that this works using the frame_generator tool, however
it requires the fixes in PR #2529.

Add headless support to FilamentApp and frame_generator.

---

CMakeLists.txt
android/build.gradle
build.sh
build/android/build.sh

The presence of a special Gradle property is now used to exclude Vulkan
support from the build. By making Vulkan "always on" for local
development, we can avoid stale CMake cache issues that arise from
toggling the Gradle property. It also lets you avoid adding the flag
to Android Studio preferences.
This is motivated by testing and does not indicate production readiness.
Clients still need to pass VULKAN into the Engine constructor to select
the Vulkan backend.
To keep APK size down and keep CI fast, we are continuing to exclude
Vulkan from official Android builds.
After syncing this change, you might need to use `./build.sh -c` to
clobber various build caches.

Enable Vulkan for Android by default.

---

filament/backend/src/metal/MetalHandles.mm

Fixes the validation assertion:
```
Validation error: Shader reads texture (sourceColor[0]) whose usage (0x04) doesn't specify MTLTextureUsageShaderRead.
```

Fix, Metal validation error with SSR and post-processing turned off

---

filament/CMakeLists.txt
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h
filament/src/materials/tonemappingWithSubpass.mat
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/GLSLPostProcessor.h
libs/filamat/src/MaterialBuilder.cpp
tools/matc/src/matc/ParametersProcessor.cpp

This allows to never store/load to main memory the HDR color buffer,
saving precious bandwidth. This mode relies on the
ext_framebuffer_fetch extension being present and can't be enabled
with certain features (currently MSAA, Bloom, DoF).
This will eventually be supported on Metal and Vulkan as well.
The current implementation is a slightly hackish: it uses a special tonemapping material which itself uses private material properties. Eventually we will find a better way to support Vulkan subpasses.

tone mapping fast path on tilers

---

filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.h

This allows FrameSkipper to work on desktop.
Similar to the GL backend, we can only query the fence from tick().
The Vulkan spec stipulates that a fence object cannot be accessed by
more than one thread simultaneously. My initial implementation violated
this, which was caught by the validation layer.

Vulkan: add support for sync objects.

---

libs/matdbg/src/ShaderExtractor.cpp
tools/matinfo/src/main.cpp

The value we pass to spvContextCreate() is not SPV_ENV_UNIVERSAL_1_3,
which is what we use in GLSLPostProcessor.
Also add a call to spvValidateBinary(), which would have caught this
oversight.

matinfo / matdbg: fix SPIRV version, add validation.

---

filament/backend/src/opengl/OpenGLDriver.cpp

Due to a typo that became relevant when we switched the gles headers to
3.0 from 3.1, MSAA started to take the emulated path.

Make MSAA fast(er) again on Mobile

---

libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/sca/GLSLTools.cpp
libs/matdbg/src/DebugServer.cpp
libs/matdbg/src/ShaderExtractor.cpp

Since we are still on Vulkan 1.0, we cannot use SPIR-V 1.3.
If we try to do so, this error is generated:
Invalid SPIR-V binary version 1.3 for target environment SPIR-V 1.0
In non-optimized builds, we were already generating spirv 1.0, but
when we enabled the shader optimizer, we generated spirv 1.3.
This bug has actually been around forever, but we did not notice because
we were only invoking the optimizer in release builds, which does not
enable validation.
We cannot upgrade to Vulkan 1.1 because the latest LunarG SDK for macOS
does not support it.

filamat: generate spirv 1.0 rather than spirv 1.3

---

filament/backend/src/vulkan/PlatformVkAndroid.cpp
filament/backend/src/vulkan/PlatformVkCocoa.mm
filament/backend/src/vulkan/PlatformVkLinux.cpp
filament/backend/src/vulkan/PlatformVkWindows.cpp
filament/backend/src/vulkan/VulkanBinder.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanPlatform.h

It is convenient to control the debug_info extension and the validation
layers from one central place. This makes it easier to force-enable
validation in Release builds to validate optimized shaders.

Vulkan: refactor the ENABLE_VALIDATION flag.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp

This was sometimes causing a cascade of log messages and swap chain
re-creations on Android.
To support resizing, we still re-create the swap chain when encountering
VK_ERROR_OUT_OF_DATE_KHR.
Suboptimal means: "A swapchain no longer matches the surface properties
exactly, but can still be used to present to the surface successfully."

Emit a one-time warning for VK_SUBOPTIMAL_KHR.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

This contains the following two fixes, but the second fix is more
important because it prevents an actual validation error on Android.
1. The query pool bitset was written in the main thread but read
in the driver thread, this is now protected with a mutex.
2. Querying a timestamp before it has been written into the command
buffer was still causing validation errors, despite the fact
that we are now properly using the AVAILABILTY flag. This is a
CPU-side synchronization problem and can therefore be fixed using
std::atomic<bool>.

Vulkan: fix synchronization issues with timestamps.

---

filament/src/Renderer.cpp

Refracted objects could be drawn on top of opaque objects that were
closer to the camera.
Du to a typo, we were not reusing the existing depth buffer during the
refraction pass.
Fixes #2576

Fix refracted objects drawing order

---

web/filament-js/extensions.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

Adding this for completeness, although the feature triggers a known
issue with Chrome's WebGL implementation that emits an error when
source and destination textures of a draw call are the same.

Add JS bindings for DoF.

---

libs/gltfio/src/AssetLoader.cpp

Vulkan complains if a pipeline declares an integer vec2 attribute but
the shader consumes it as "vec2" rather than "ivec2". gltfio was doing
this when supplying dummy texture coordinates.
This fixes one of the two bugs reported in #2573.

gltfio: fix vertex attribute type mismatch.

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt

Fixes: [#2599](https://github.com/google/filament/issues/2599)
When using ModelViewer with a TextureView instead of a SurfaceView, it throws an error because the displayHelper is not initialized. But the displayHelper is needed and is used here,  [ModelViewer.kt#L288](https://github.com/google/filament/blob/6d04ae250afd33dbdba0a222e42a4700777389a9/android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt#L288).
I think this constructor it is not used very often but I am implementing filament inside an example where I have already a SurfaceView and wanted to try if it would work with TextureView

Initialize DisplayHelper when using textureView in ModelViewer

---

filament/backend/include/private/backend/CommandStream.h
filament/backend/src/CommandStream.cpp

To enable some basic profiling of the gl thread using performance
counters, the "filament.perfcounters" property must be set to 1
(before the Filament Engine is created):
adb shell setprop filament.perfcounters 1
This is so that filament doesn't interfere with simpleperf by default.

perfcounters are now disabled by default

---

RELEASE_NOTES.md
filament/backend/src/TextureReshaper.cpp
filament/backend/src/TextureReshaper.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

`scheduleDestroy` wasn't being called in a lot of places.

Add correct scheduleDestroy calls to Metal backend

---

RELEASE_NOTES.md
libs/gltfio/CMakeLists.txt
libs/gltfio/include/gltfio/Animator.h
libs/gltfio/include/gltfio/AssetLoader.h
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/include/gltfio/FilamentInstance.h
libs/gltfio/include/gltfio/SimpleViewer.h
libs/gltfio/src/Animator.cpp
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FFilamentInstance.h
libs/gltfio/src/FilamentInstance.cpp
libs/gltfio/src/ResourceLoader.cpp
samples/CMakeLists.txt
samples/gltf_instances.cpp

This adds createInstancedAsset() to AssetLoader, which creates a master asset and a set of slave instances. Vertex buffers, index buffers, textures, and material instances are shared. Entities and components are duplicated.
Instances have their own API object that exposes a subset of the master asset's entity hierarchy and an optional Animator object.
This also adds a new sample app called `gltf_instances`.  It is similar to `gltf_viewer` but with no GUI.  It has additional command line arguments for a number of instances and animation.
Java and JavaScript bindings will be added in a subsequent PR.
Fixes #1513

 gltfio: Add support for "software instancing".

---

libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/ResourceLoader.cpp

On a Pixel 3a, this reduces load time for Bistro from ~6.5 seconds to ~2.5 seconds, where "load
time" is the time between app launch and the first mesh being rendered.
After these optimizations, we still see some low CPU utilization during the load, which appears
to be due to AssetManager usage on the Java side. It might be possible to optimize this too.
Note that AABB computation is optional since glTF has built-in min/max values, but we currently
enable it by default for robustness. In a future PR I would like to change this from opt-out to
opt-in.

gltfio: Use JobSystem to compute tangents and AABB's.

---

filament/src/PostProcessManager.cpp

make sure all fields are always initialized and the IDE stops 
complaining.

minor cleanup of PostProcessManager ctor

---

android/filament-android/src/main/java/com/google/android/filament/View.java
filament/CMakeLists.txt
filament/include/filament/ColorGrading.h
filament/include/filament/Engine.h
filament/src/ColorGrading.cpp
filament/src/Engine.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/ToneMapping.h
filament/src/details/ColorGrading.h
filament/src/details/Engine.h

A ColorGrading object will eventually be settable on a View to
choose the tone mapping and other color transformations.
There is currently only a single default ColorGrading instance
used by all views.

Introduce ColorGrading API

---

RELEASE_NOTES.md
docs/math/White Balance.nb
filament/backend/include/backend/DriverEnums.h
filament/include/filament/ColorGrading.h
filament/include/filament/View.h
filament/src/Color.cpp
filament/src/ColorGrading.cpp
filament/src/ColorSpace.h
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/ToneMapping.h
filament/src/View.cpp
filament/src/details/ColorGrading.h
filament/src/details/View.h
libs/math/include/math/TVecHelpers.h
samples/material_sandbox.cpp
samples/material_sandbox.h

Each View can now have its own `ColorGrading` object, which defines various color transforms.
These transforms currently include:
- Tone mapping (linear, Reinhard, ACES, Filmic and display range for debugging)
- White balance (temperature/tint offsets)
Here is an example of a scene rendered using ACES:
And the same scene using ACES and a custom white balance to emphasize the sunset in the IBL:

Add per-view color grading LUT

---

RELEASE_NOTES.md
android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
android/gltfio-android/src/main/cpp/ResourceLoader.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/ResourceLoader.java
samples/gltf_viewer.cpp
web/filament-js/extensions.js
web/filament-js/jsbindings.cpp

glTF assets are required to provide min/max attributes for POSITION,
so in theory we never need to compute the AABB. However the option is
still there.
This PR also makes it so that Java clients can choose this option,
previously it was hardcoded for all non-native clients.

 gltfio: improve performance by assuming assets are well-formed.

---

RELEASE_NOTES.md
docs/math/Shadow Midtones Highglits.nb
filament/include/filament/ColorGrading.h
filament/src/ColorGrading.cpp
filament/src/ColorSpace.h
filament/src/ToneMapping.h
samples/material_sandbox.cpp
samples/material_sandbox.h

This feature can be used to color correct specific tonal ranges. The tonal zones can be precisely controlled.
Here is an example of a scene before tonal range correction:
And after:

Add new color grading feature: shadows/mid-tones/highlights

---

RELEASE_NOTES.md
android/filament-utils-android/build.gradle
android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt

If you now try loading Bistro, the skybox shows up fairly quickly.
This works by moving AssetManager uncompression off the UI thread.

Add new async method to ModelViewer.

---

RELEASE_NOTES.md
filament/CMakeLists.txt
filament/include/filament/ColorGrading.h
filament/src/Color.cpp
filament/src/ColorGrading.cpp
filament/src/ColorSpace.h
filament/src/ToneMapping.h
filament/src/details/ColorGrading.h
libs/math/include/math/TVecHelpers.h
samples/material_sandbox.cpp
samples/material_sandbox.h

Adds two new color adjustments: saturation and contrast.
Example of a scene before adjustments:
And after:
This change also adds comments, renames/moves a few functions around to make the color grading code more precise and explicit.

Color grading: add saturation and contrast

---

libs/gltfio/src/ResourceLoader.cpp

If a client opts in to AABB computation and uses instancing, the AABB
would be clobbered with an infinite box.
Fixes #2639

gltfio: fix AABB when instancing is enabled

---

filament/backend/include/private/backend/CommandBufferQueue.h
filament/backend/src/CommandBufferQueue.cpp
filament/src/Engine.cpp
filament/src/details/Engine.h

- assert that shutdown() is called from the main thread
- attempt to catch whether CommandBufferQueue::mExitRequested gets corrupted
(which could explain the ANR).

more debug code to help catch an ANR

---

libs/filameshio/src/MeshReader.cpp

Although I don't know the exact details of the `MeshWriter` and `MeshReader` I noticed that it's currently possible that there are more `Part`s in a filamesh file than that there are materials. This results in a segfault when using the `i` variable to select a material name. To fix this we have to use `parts[i].material` as that points to the correct and stored material.
To reproduce this, you have to create a particle system in blender and let it pick a random object from a collection. The number of used materials needs to be smaller then the number of objects in the collection. See the attached blend file; export this to .obj and convert that to .filamesh. 
[particles.tar.gz](https://github.com/google/filament/files/4740592/particles.tar.gz)

Fix: cannot use parts index for material index.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/ColorGrading.cpp
android/filament-android/src/main/java/com/google/android/filament/ColorGrading.java
filament/include/filament/ColorGrading.h
filament/src/ColorGrading.cpp
samples/material_sandbox.cpp
samples/material_sandbox.h

This change improves the UI of the color grading tools in `material_sandbox`. Screenshots of before color grading and after:

Add new curves color grading tool

---

filament/backend/src/android/ExternalStreamManagerAndroid.cpp

This used to be tolerated, but no more with recent versions of android.

don't attempt to call Android private APIs

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/ColorGrading.cpp
android/filament-android/src/main/java/com/google/android/filament/ColorGrading.java
filament/include/filament/ColorGrading.h
filament/src/ColorGrading.cpp
samples/material_sandbox.cpp
samples/material_sandbox.h

Compared to the saturation API, vibrance tries to not saturate already saturated colors and tries to preserve red hues. Vibrance also does not desaturate the image completely.
Saturation = 2.0
Vibrance = 2.0
Saturation = 0.0
Vibrance = 0.0

Add new color grading feature, vibrance

---

android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java

When invoking MaterialBuilder.samplerParameter with Java enum SAMPLER_EXTERNAL it was wrongly recast as native enum SAMPLE_CUBEMAP in the JNI interface because the Java enum was missing SAMPLE_2D_ARRAY.

SamplerType JNI definition was out of step with the native definition.

---

android/gltfio-android/src/main/java/com/google/android/filament/gltfio/Animator.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java

Someone wise once said: "It is better to throw in Java than to crash in
Native."
Motivated by #2654.

Throw Java exception when using destroyed Animator.

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
libs/matdbg/src/JsonWriter.cpp

- don't crash when a material doesn't have a name
- don't cache the program in PostProcessManager so we can do live
editing. Not needed anyways, because Material has a cache.

minor fixes for matdbg

---

filament/backend/src/vulkan/VulkanDriver.cpp

The blit DriverAPI command was not enforcing correct synchronization.
On Android, this manifested as an intermittent issue with bad mipmap
levels.
This did not trigger any validation warnings and therefore took a long
time to track down.
Fixes #2643

Vulkan: fix mipmap generation on Android.

---

libs/filameshio/src/MeshReader.cpp

#2652 introduced a bug, we still want to call `builder.material` with `i` as the material index for this renderable.
Verified that the file attached in the issue still works.

Fix MeshReader material bug

---

libs/filagui/include/filagui/ImGuiExtensions.h
libs/filagui/src/ImGuiExtensions.cpp
libs/gltfio/include/gltfio/SimpleViewer.h
samples/gltf_viewer.cpp
samples/material_sandbox.cpp
samples/material_sandbox.h
third_party/imgui/tnt/CMakeLists.txt

This change also changes the default sidebar width because it was clipping some of the UI elements.

Add (improved) color grading UI to gltf-viewer

---

web/filament-js/extensions.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

Fixes #1988
Example loading a glTF camera:
```
const cameras = asset.getCameraEntities();
const c = engine.getCameraComponent(cameras[0]);
// adjust aspect ratio
c.setScaling([1, window.innerWidth / window.innerHeight, 1, 1]);
view.setCamera(c);
```

Add JS bindings to gltfio camera funcs

---

RELEASE_NOTES.md
web/filament-js/extensions.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp
web/filament-js/utilities.js

Web developers should not be expected to call malloc on the emscripten
heap. This new API is better aligned with how we handle vertex buffers.
Fixes #2702.

Improve JS API for SurfaceOrientation helper.

---

RELEASE_NOTES.md
web/filament-js/extensions.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp
web/samples/animation.html

This repairs the `animation.html` sample. Using a JS array is more
natural for web developers and more consistent with the latest
JavaScript bindings in gltfio.

Improve JS API for Scene::addEntities.

---

filament/CMakeLists.txt

CocoaPods distribution requires a LICENSE file in the archive.

Install Filament LICENSE alongside README

---

build.sh
build/ios/build.sh
build/ios/create-universal-libs.sh

For iOS releases, combine arm64 and x86_64 binaries into universal ones. This allows developers to link against a single set of static libraries, and is necessary for CocoaPods distribution.

Create universal libraries for iOS releases

---

third_party/spirv-tools/FILAMENT_README.md
third_party/spirv-tools/source/CMakeLists.txt

This target gets added to "ALL" but we don't depend on it anywhere in Filament (only the static variant). It causes issues on Linux.

Remove unused SPIRV-Tools-shared library

---

libs/gltfio/include/gltfio/SimpleViewer.h

The Animation selector is now a top-level group (collapsed by default),
previously it was in the Hierarchy group, which was non-intuitive.
Also:
- Use indent() for consistency with other UI groups.
- Remove un-necessary usage of a lambda.

gltf_viewer: move "Animation" UI

---

libs/gltfio/src/Animator.cpp

Tested with Polly the robo-hound and ensured that InterpolationTest
did not regress.
Partial fix for #2714.

Fix CUBICSPLINE interpolation for morph weights.

---

filament/include/filament/Engine.h
filament/include/filament/IndirectLight.h
filament/include/filament/Renderer.h
filament/include/filament/VertexBuffer.h
filament/include/filament/View.h
libs/utils/include/utils/compiler.h

This silences a few Clang warnings seen in Xcode when compiling Filament headers.
```
Declaration is marked with '\deprecated' command but does not have a deprecation attribute
Empty paragraph passed to '@param' command
```

Silence warnings in public headers

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
libs/gltfio/src/ResourceLoader.cpp
samples/gltf_viewer.cpp
web/filament-js/extensions.js
web/filament-js/filament.d.ts

- Allow JavaScript and Java / Kotlin clients to configure this setting.
- Opt in by default (this was disabled in #2621)
- Optimize large assets like Bistro by iterating through prims only when the asset actually has skins.
Fixes #2714.

gltfio: various improvements to skinning normalization.

---

CMakeLists.txt
android/filament-android/CMakeLists.txt
filament/CMakeLists.txt
libs/matdbg/README.md

Also group FILAMENT_ENABLE_MATDBG with all our other CMake options.

 CMake: build matdbg / civetweb only when enabled.

---

filament/src/PostProcessManager.cpp

if NEAREST or LINEAR min filter is used, texelFetch is actually
undefined when the LOD is not 0.

texelFetch w/ LOD requires at least MIPMAP_NEAREST

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanFboCache.h
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

If a render target attachment is not cleared or discarded, then it should be preserved and therefore requires VK_ATTACHMENT_LOAD_OP_LOAD.

Vulkan: fix bloom on Android by supporting LOAD_OP_LOAD.

---

filament/src/Camera.cpp

Saw this specifically with some glTF files that apply a root level scaling matrix to the entire scene, including the camera.

Fix, incorrect camera view matrix with non-rigid transformations

---

libs/filamat/src/GLSLPostProcessor.cpp

This would happen when using math -E -a vulkan. GLSLangCleaner lifetime
must be shorter than TProgram/TShader.
I think we can fix this by using another scoped GLSLangCleaner.
Tested successfully with ASAN.

fix a use after free in filamat

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

This PR is comprised of three fixes:
(1) Fix intermittent InvalidImageLayout error for main depth buffer upon startup.
This was caused by the fact that we didn't bother flushing the work command buffer that is used for initial depth buffer transition, so the pipeline barrier didn't always have a chance to be processed before the first draw call.
(2) Allow LOAD_OP_LOAD when rendering to swap chain.
This was fixed by adding an "invalid" flag to the swap chain state that we track.
(3) Transition to PRESENT layout only once per frame.
This was fixed by performing the transition using a barrier rather than a render pass flag.  The render pass was a bad place because it cannot know if it is the last one in the frame.

Vulkan: fix several image layout issues

---

filament/backend/src/metal/MetalDriver.mm

This fixes a crash seen when initializing an `Engine`, issuing some driver commands but not rendering a frame (like generating mipmaps), and then calling `engine->destroy(&engine)`.

Flush pending command buffer in MetalDriver::terminate

---

filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.h

This prevents the following validation error:
Cannot get query results on queryPool 0x2 with index 0 as data has
not been collected for this index.
This was occasionally triggered when we attempted to query a timer that
had not yet been inserted into any command stream. (The error seems
bogus to me since we've enabled the AVAILABILITY flag, but we might as
well fix it anyway.)

Vulkan: fix intermittent InvalidQuery on Android.

---

filament/src/materials/dof.mat
filament/src/materials/dofDilate.mat
filament/src/materials/dofTiles.mat
filament/src/materials/dofUtils.fs

glslang generate much less code when function parameters are marked
const (it also works around a bug where highp intermediate variables
are introduced -- but this will be fixed soon).
Also remove non-trivial uses of ?: as it also triggers a similar problem 
in glslang.

DoF: make all function parameter const

---

libs/filamat/include/filamat/IncludeCallback.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/Includes.cpp
libs/filamat/src/Includes.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/filamat/tests/MockIncluder.h
libs/filamat/tests/test_includes.cpp
libs/utils/include/utils/CString.h
shaders/CMakeLists.txt
tools/glslminifier/src/main.cpp
tools/matc/src/matc/DirIncluder.cpp
tools/matc/src/matc/DirIncluder.h
tools/matc/src/matc/MaterialCompiler.cpp
tools/matc/tests/test_includer.cpp

When `matc` reports an error, it will now include the name of the material file and the correct line number. For example:
```
ERROR: sandboxUnlit.mat:20: 'bafeColor' : undeclared identifier
ERROR: sandboxUnlit.mat:20: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
```
This works just as well with files `#include`d by a material:
```
ERROR: Unable to parse fragment shader:
ERROR: dofUtils.fs:30: 'assign' :  cannot convert from ' const 3-component vector of float' to ' temp 4-component vector of float'
ERROR: dofUtils.fs:30: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
```
and even with errors in Filament shaders in debug builds:
```
ERROR: shadowing.fs:323: 'ShadowSample_PCF_Low' : no matching overloaded function found
ERROR: …
```

Improve matc error reporting

---

filament/src/PostProcessManager.cpp
filament/src/materials/dof.mat
filament/src/materials/sao.mat

We now get away with a sin/cos per fragment instead of per-sample,
this increases a little bit the ALU load but decreases the EFU's.
This is not necessarily faster, but sin/cos may cost more power or
have longer latencies.

ssao: optimize sin/cos per sample

---

libs/matdbg/web/script.js
libs/matdbg/web/style.css

This has two commits:
- Support scenes that have many materials.
- To fix this, matdbg now downloads the source of each variant only after it gets selected, rather than flooding the server with a bunch of requests at startup.
- Autoselect a variant after clicking a material.
- This prevents the weird mismatch that would occur between the editor and the highlighted material name.

matdbg: fix large # of materials + autoselect variant

---

filament/backend/src/vulkan/VulkanDriver.cpp

This fix has the side effect of causing a validation warning due to
a declared fragment shader output that has no corresponding attachment.
We can fix that in a future PR.
Fixes #2752

Vulkan: fix SSAO by removing bogus workaround.

---

filament/backend/src/vulkan/VulkanBinder.cpp
filament/backend/src/vulkan/VulkanBinder.h
filament/backend/src/vulkan/VulkanDriver.cpp

This is step 1 for supporting subpasses (aka framebuffer fetch).
Vulkan requires us to explicitly bind the shader to any framebuffers
that we read from. These are called input attachments in Vulkan
parlance, and each binding is called a descriptor.
For simplicity we only create homogeneous descriptor sets where each
descriptor set is comprised of only one type of binding (i.e. all
uniforms or all samplers). I see no reason to break with that
architecture right now, so input attachments live in their own set.
In the long term, we should probably think about partitioning
descriptors differently (e.g. according to their frequency of change).
This PR also renames some internal fields in order to avoid nomenclature
confusion, such as `mDescriptorSets` => `mDescriptorBundles` . Each
entry in …

Vulkan: add support for input attachment descriptors.

---

libs/filagui/include/filagui/ImGuiHelper.h
libs/filagui/src/ImGuiHelper.cpp

The existing API was fine for FilamentApp but it prevented clients from
making ImGui calls from arbitrary places, which forced them in some
cases to queue up their ImGui calls using vector<function<>>.
This PR publicizes the low-level method that consumes the ImGui draw
list and removes calls to global functions.

filagui: publicize the low-level draw data handler.

---

web/docs/demo_template.html
web/docs/tutorial_suzanne.md
web/docs/tutorial_triangle.md

This makes the tutorials more consistent with the live demos and lets us
more easily ensure that the tutorials are kept up to date without
errors. In fact it caught an error in the Suzanne tutorial.
Since this affects source rather than served files, this PR is intended
for main.  The master branch will be updated in a subsequent PR.

Web tutorials now use a CDN for the npm package.

---

filament/src/materials/colorGradingAsSubpass.mat

I believe Ben is working on generalizing this from the codegen standpoint, but until then we might as well use the correct set index.

Update the descriptor set index in colorGrading.

---

android/filament-android/src/main/java/com/google/android/filament/Texture.java
filament/backend/include/backend/DriverEnums.h
filament/backend/src/vulkan/VulkanHandles.cpp
filament/src/Renderer.cpp
filament/src/fg/FrameGraphHandle.h
web/filament-js/filament.d.ts
web/filament-js/jsenums.cpp

We do not really need to expose this to the public but we expose all our other usage flags.

DriverEnums: add usage flag for SUBPASS_INPUT

---

BUILDING.md
RELEASE_NOTES.md
build/web/ci-common.sh
web/filament-js/CMakeLists.txt
web/filament-js/wasmloader.js

Since postRun can no longer be set from within the extern post JS, we
now use the promise rather than postRun.
This upgrades emsdk to 1.39.19 (see note in #2800).

WebGL: Upgrade emsdk and refactor initialization.

---

filament/backend/src/noop/NoopDriver.cpp

This allows us to do WASM-based unit tests using the NOOP driver.

NoopDriver now uses ShaderModel::GL_ES_30 on WASM

---

.github/workflows/release.yml

Release assets will now be uploaded in the format: `filament-v1.8.0-android.aar`.

Include Filament version instead of date in release assets

---

README.md
build.sh
filament/backend/src/metal/MetalHandles.mm
ios/CocoaPods/Filament.podspec
ios/samples/HelloCocoaPods/Podfile
ios/samples/README.md
site/content/posts/cocoapods.md
third_party/clang/iOS.cmake

Internal Google clients already rely on Filament supporting iOS 11 and above, this makes it "official". This also fixes one usage of a newer API.

Set Filament iOS support to iOS 11

---

web/filament-js/filament.d.ts

- buffers processed by getBufferDescriptor can be an asset string or JS typed array.
- https://github.com/google/filament/blob/185ed0cc68cf5e2a148ff36bd817acc6b5c2b811/web/filament-js/extensions.js#L17-L27
---
replaces #2789

Filament.d.ts: Add BufferReference type alias, update to accept typed arrays

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/Renderer.cpp

This makes two changes to the Driver API:
1. Adds the beginSubpass() method.
2. Adds subpassMask to RenderPassParams.
Locally I've proven that this PR is sufficient by making a series of Vulkan changes; sneak peek is available at commit bfef6914a7d288bbd25926c02ec93d231a8c0d07.
Note that this PR also moves the new usage flag to a different texture because I had placed it on the wrong one.
See also #2780.

Add simple subpass support to the Driver API.

---

libs/filabridge/src/SamplerBindingMap.cpp

uint8_t is char, so it prints junk on the screen and wakes up your dog
with beeping sounds.

Fix garbage in "Exceeded max sampler" message.

---

filament/CMakeLists.txt
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/materials/dof.mat
filament/src/materials/dofCombine.mat
filament/src/materials/dofDownsample.mat
filament/src/materials/dofMedian.mat
filament/src/materials/dofMipmap.mat
filament/src/materials/dofTiles.mat
filament/src/materials/dofUtils.fs

- make sure all downsampling is exactly correct and use proper
uv values to access these textures. This stabilizes the DoF a bit.
- for now only use NEAREST filtering, as bilinear can't be used naively.
- noise is now mandatory, fix noise radius
- add a median pass (performance is not impacted because DoF is faster
due to using NEAREST filtering)
- fix  be consistant in how the kernel radius is computed, fix a couple
errors in that area.
- change ring density from 8 to 4 (but starting with 8), so each new
ring is 4 samples larger than the previous. This reduces the number
of samples needed from 25 to 21 on mobile, and 49 to 37 on desktop. 
It also makes it conceivable to use 5 rings (57 samples). Quality is
not visibly impacted because the center ring is still 8 samples.
This density, …

DoF: fix many quality/performance issues

---

android/filament-android/src/main/cpp/Scene.cpp
android/filament-android/src/main/java/com/google/android/filament/Scene.java
android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
filament/include/filament/Scene.h
filament/src/Scene.cpp
filament/src/details/Scene.h
libs/gltfio/include/gltfio/AssetLoader.h
libs/gltfio/include/gltfio/SimpleViewer.h
web/filament-js/extensions.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

For testing purposes, sample-gltf-viewer reloads the model when the
user double-taps the screen. This operation was causing a buildup of
blank entities in the Scene, because we were merely destroying the
components, not removing them from the Scene.

Introduce removeEntities API / fix leak in ModelViewer (!)

---

filament/src/materials/dof.mat

- Use the random offset to calculate the correct intersection radius.
For the center sample, the ring radius is otherwise zero, which means
any sample in the random disk with a CoC radius > 0 would intersect,
and that seems wrong.
- The selected mip was off by one.
We were always picking a mip too high because the CoC are in
high resolution, but our mip-chain is 1/4 res from that.
This improves rendering quality quite a lot.

DoF: bug fixes and quality improvements

---

filament/src/materials/dof.mat

Using a ring density of 4 was wrong -- apparently I can't add.
With a density of 8 we can guarantee we don't have gaps between samples
when using mips properly (or at least gaps are consistant and 
predictable).

DoF: improve quality

---

filament/src/components/TransformManager.cpp

When a node is set to have no parent, its .next is not updated. The result is that later operations, such as removing this node from the graph result in what was previously its next sibling node being corrupted.
Note that this failure is masked in debug builds because removeNode sets parent/prev/next to 0 in those cases.

Fix Hierarchy Corruption

---

filament/src/PostProcessManager.cpp
filament/src/materials/dof.mat

fast tiles (i.e. where all pixels have the same circle-of-confusion)
are allowed to use bilinear filtering.
this results in better looking DoF in these areas.

DoF: improve quality in "fast tiles"

---

filament/src/materials/dofDilate.mat

We were using texelFetch which doesn't handle wrap modes, and this
resulted in all edge tiles to be undefined. Use textureLod() instead.

DoF: fix tiles dilate pass edges

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/backend/PixelBufferDescriptor.h
filament/backend/src/CommandStream.cpp
filament/backend/src/opengl/GLUtils.h
filament/backend/src/vulkan/VulkanUtility.cpp
filament/src/ColorGrading.cpp

- we were not clamping the color grading output to [0,1]
- we were not using a supported input (cpu) pixel format for the
3d LUT in low and medium quality

fix a few issues with color grading

---

filament/src/ColorGrading.cpp
filament/src/Texture.cpp
filament/src/details/Texture.h

We now validate supported combinations of internalFormat vs. format/type.
We currently follow the GLES specification, but we could be more 
restrictive if needed for vulkan/metal.
The validation terminates in debug builds and logs (and becomes a no-op)
in release builds.

Add validation for Texture::setImage()

---

libs/gltfio/src/MaterialGenerator.cpp

This fixes the depth fighting in the column of red spheres in the test
model while in filamat mode. Thanks Romain for catching this.
It also makes filamat mode more consistent with ubershader mode.
before / after screenshots

gltfio: fix depth writes for transmissive materials.

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/materials/blitHigh.mat
filament/src/materials/blitLow.mat
filament/src/materials/blitMedium.mat
filament/src/materials/dof.mat
filament/src/materials/dofCombine.mat
filament/src/materials/dofDilate.mat
filament/src/materials/dofDownsample.mat
filament/src/materials/dofMedian.mat
filament/src/materials/dofMipmap.mat
filament/src/materials/dofTiles.mat

The two main changes are:
- materials are now stored in a hash map which allows us to
automatically destroy all of them using one loop -- instead of
having to call terminate() for each of them.
- factored a very common sequence of code:
commit()
use()
beginRenderPass()
draw()
endRenderPass()
This makes the code easier to write and also results in less code.
There are also minor other changes, e.g. RenderPass constructor is not
inline anymore.

attempt to reduce code size in PostProcessManager

---

RELEASE_NOTES.md
filament/src/Material.cpp
shaders/src/shading_unlit.fs

- Do not mutate alpha in the render target (useful for transparent render targets).
- Make non-lit behavior consistent with lit.

Two fixes for MASKED blending mode.

---

libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/GLSLPostProcessor.h

If we don't run the MergeReturnPass, we see a bunch of warnings:
```
warning: :0:0:0: The function '%114 = OpFunction %18 None %106' could not be inlined because the return instruction is not at the end of the function. This could be fixed by running merge-return before inlining.
```
We still can't run the MergeReturnPass on desktop, due to an AMD driver crash. But we can at least run it on mobile.

 Run MergeReturnPass only on mobile

---

filament/src/Material.cpp
filament/src/details/Material.h
libs/matdbg/include/matdbg/DebugServer.h
libs/matdbg/include/matdbg/JsonWriter.h
libs/matdbg/src/DebugServer.cpp
libs/matdbg/src/JsonWriter.cpp

Noticed this when trying to edit depth shaders. `VARIANT_COUNT` is now 64, so we need a 64 bit int to hold a mask of active variants.

Fix variant-limiting bug in matdbg

---

filament/src/PostProcessManager.cpp
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraphHandle.h
filament/src/fg/fg/PassNode.cpp
filament/src/fg/fg/ResourceNode.h

The FrameGraph cannot store pointers internally because all objects
are stored in vectors. Unfortunately we were storing the writer of
resources as a pointer. 
This is fixed by storing an index instead.

fix a FG crasher when we have more than 32 passes

---

filament/src/fg/fg/PassNode.cpp
filament/src/fg/fg/PassNode.h
filament/src/fg/fg/ResourceNode.h

a recent fix actually badly broke moveResource, we were using the
index of the newly created resource instead of the pass index.

fix a moveResource which was broken recently

---

web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp
web/samples/helmet.html

In retrospect, I should've exposed ints to JS instead of entities.
Making this fix is already a TODO, but it will be a tedious change. For
now, this PR fixes two issues that were causing tiny but frequent memory
leaks, according to the emscripten memory leak widget.
(1) Do not include Entity in the list of classes that should only be
passed around by pointer.
(2) Clients should always call delete() on returned Entities.

JavaScript bindings: fix a frequent 4-byte memory leak.

---

libs/gltfio/src/FilamentAsset.cpp
samples/gltf_viewer.cpp
web/filament-js/jsbindings.cpp

This fixes two oversights in the FilamentAsset destructor:
- Destroy the faux root Entity.
- If it exists, remove the name component from each Entity.

gltfio: fix some small memory leaks.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
android/samples/sample-image-based-lighting/src/main/java/com/google/android/filament/ibl/MainActivity.kt
filament/include/filament/View.h
filament/src/Renderer.cpp
filament/src/View.cpp
filament/src/details/View.h
libs/gltfio/include/gltfio/SimpleViewer.h
samples/lightbulb.cpp
samples/material_sandbox.cpp
samples/material_sandbox.h

setAmbientOcclusion (and associates) is now deprecated (but still works),
in favor of the new .enabled field in AmbientOcclusionOptions.

API CHANGE: make ssao options work like all other options

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp

This fixes a null pointer exception that we saw after disabling several
View -process effects.

Vulkan: allow blit to default render target.

---

filament/backend/src/vulkan/PlatformVkAndroid.cpp
filament/backend/src/vulkan/PlatformVkAndroid.h
filament/backend/src/vulkan/PlatformVkCocoa.h
filament/backend/src/vulkan/PlatformVkCocoa.mm
filament/backend/src/vulkan/PlatformVkCocoaTouch.h
filament/backend/src/vulkan/PlatformVkCocoaTouch.mm
filament/backend/src/vulkan/PlatformVkLinux.cpp
filament/backend/src/vulkan/PlatformVkLinux.h
filament/backend/src/vulkan/PlatformVkWindows.cpp
filament/backend/src/vulkan/PlatformVkWindows.h
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanPlatform.h
libs/filamentapp/src/NativeWindowHelperCocoa.mm

This removes the old getClientExtent stuff that I added a while back,
and replaces it with the strategy espoused by the MoltenVK author found
here:
https://github.com/KhronosGroup/MoltenVK/issues/428
I tested this PR on macOS with Vulkan and Metal. I tested both on high
and low DPI displays. I also tried dragging the window between the two
displays.
Android still has issues with rotation, I will deal with that next.

Fix resizing issues with MoltenVK.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp

This fixes the visual hang that would occur after going to the task
switcher and back.
After recreating the swap chain, all of its associated fences and sync
objects become invalid. Since we were not tracking this, FrameSkipper
was going into an infinite wait after the swap chain was created.

Vulkan: fix Android after pause / resume.

---

filament/backend/src/vulkan/VulkanDriver.cpp

The stride passed to Vulkan for query pools is the stride between
queries, not the stride between individual values. I realized this after
seeing the SwiftShader implementation of queries.
I also used log statements to confirm that this fixes bogus frame
skipping on my Pixel 4.

Vulkan: fix zealous frame skipping on Android.

---

README.md
android/proguard-rules.pro

The proguard-rules.pro file provided by @jwmcglynn  [#1207](https://github.com/google/filament/pull/1207)
works perfectly for Android projects with minifyEnabled.
Add the config file back to the repository and update README.md
to help other Android users setup release build.

Add back proguard file for Android

---

android/filament-android/src/main/cpp/Texture.cpp
android/filament-android/src/main/java/com/google/android/filament/Texture.java
filament/include/filament/Texture.h
filament/src/Texture.cpp
filament/src/details/Texture.h

Also cleanup all setImage() error reporting. All error checks are
changed from silent to NON_FATAL_ASSERT, which means they'll throw
if exceptions are enabled or do a no-op and log a message otherwise.
Also added more precondition checks.

Add public APIs for texture 3D and texture 2D arrays

---

filament/backend/test/ShaderGenerator.cpp
shaders/src/depth_main.vs
shaders/src/main.vs

This is more similar to the Vulkan shader pipeline and less magical.
There are 3 places in our shader code where we perform fixups like this:
- main.vs
- depth_main.vs
- post_process_getters.vs
That last one needs no change since it does not involve Z.

Metal: use explicit shader fixup for clip space Z.

---

libs/filabridge/include/private/filament/Variant.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/matdbg/CMakeLists.txt
libs/matdbg/src/CommonWriter.cpp
libs/matdbg/src/CommonWriter.h
libs/matdbg/src/JsonWriter.cpp
libs/matdbg/src/TextWriter.cpp
shaders/src/inputs.vs
shaders/src/main.vs

Due to some bugs in `Variant.h`, we're generating a lot (17) of unnecessay variants.
These get removed because FOG doesn't affect the depth variants:
```
gl41   vs 0x30   DEP|FOG
gl41   fs 0x30   DEP|FOG
gl41   vs 0x38   SKN|DEP|FOG
```
These get removed because FOG doesn't affect vertex shading:
```
gl41   vs 0x20   FOG
gl41   vs 0x21   DIR|FOG
gl41   vs 0x22   DYN|FOG
gl41   vs 0x23   DIR|DYN|FOG
gl41   vs 0x25   DIR|SRE|FOG
gl41   vs 0x26   DYN|SRE|FOG
gl41   vs 0x27   DIR|DYN|SRE|FOG
gl41   vs 0x28   SKN|FOG
gl41   vs 0x29   DIR|SKN|FOG
gl41   vs 0x2a   DYN|SKN|FOG
gl41   vs 0x2b   DIR|DYN|SKN|FOG
gl41   vs 0x2d   DIR|SRE|SKN|FOG
gl41   vs 0x2e   DYN|SRE|SKN|FOG
gl41   vs 0x2f   DIR|DYN|SRE|SKN|FOG
```
DYN _does_ affect the vertex shader (it was implicit before). This makes it …

Audit material variants

---

filament/backend/src/vulkan/VulkanDriver.cpp

This fixes the long-standing "black rectangle" issue in our shadowtest
sample.
We were mistakenly constraining the clear to the viewport, which
is meant only to affect the vertex pipeline.
Also, we were needlessly setting the scissor rect in BeginRenderPass(),
since we already do so in Draw().

Vulkan: fix bad shadow map boundaries.

---

filament/backend/src/DriverBase.h
filament/src/ColorGrading.cpp
filament/src/PostProcessManager.cpp

For single-sampled textures we were using 0 in some places and 1 in some
places. It's better to be consistent.

DriverAPI sample count should be > 0.

---

libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/Variant.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/matdbg/src/CommonWriter.cpp
tools/matc/src/matc/CommandlineConfig.cpp
tools/matc/src/matc/ParametersProcessor.cpp

This reserves 7 new variants for VSM (no shader code change yet):
```
#31  gl41   fs 0x45   DIR|SRE|VSM
#32  gl41   fs 0x46   DYN|SRE|VSM
#33  gl41   fs 0x47   DIR|DYN|SRE|VSM
#34  gl41   fs 0x50   DEP|VSM
#35  gl41   fs 0x65   DIR|SRE|FOG|VSM
#36  gl41   fs 0x66   DYN|SRE|FOG|VSM
#37  gl41   fs 0x67   DIR|DYN|SRE|FOG|VSM
```

Add new shader variants for VSM

---

filament/src/Material.cpp
libs/filabridge/include/private/filament/SibGenerator.h
libs/filabridge/include/private/filament/Variant.h
libs/filabridge/src/SamplerBindingMap.cpp
libs/filabridge/src/SamplerInterfaceBlock.cpp
libs/filabridge/src/SibGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/common_lighting.fs
shaders/src/depth_main.fs
shaders/src/depth_main.vs
shaders/src/light_directional.fs
shaders/src/light_punctual.fs
shaders/src/shading_unlit.fs
shaders/src/shadowing.fs

`getPerViewSib` now takes a `uin8t_t` variant key, because the Sib changes slightly depending on if VSM is on or not.

Add VSM shader changes

---

android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/Renderer.cpp

Marking a view with a custom render target will now disable blending
for that view but require an alpha channel for intermediate buffers.
Blending is disabled because it is meaningless.
fixes #2802

fix translucent views with custom render targets

---

filament/backend/src/vulkan/VulkanBinder.h
filament/backend/src/vulkan/VulkanFboCache.h
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h
filament/backend/src/vulkan/VulkanStagePool.h

Filament calls createRenderTarget very frequently, so this PR has the
side effect of reducing a huge amount of create-destroy churn in other
Vulkan objects such as VkRenderPass and VkFramebuffer.

Vulkan: add very simple cache of VkImageView.

---

filament/backend/src/metal/MetalBufferPool.mm
filament/backend/src/vulkan/VulkanBinder.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanStagePool.cpp

This fixes a Vulkan validation error seen on Android about destroying a
framebuffer that is still in use by an active command buffer.

Vulkan + Metal: fix bad cache gc due to unsigned overflow.

---

web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp
web/samples/helmet.html

This regressed when we added a callback argument, because the callback
cannot be bound.
This commit also modifies the helmet example to use the low-level API
for testing purposes.
Note that this omits the optional nanoseconds argument. JavaScript
does not support overloading and this argument probably cannot be
accurately provided anyway in a web environment.
Fixes #3002.

WebGL: repair beginFrame() bindings.

---

filament/backend/src/vulkan/VulkanBinder.cpp
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanFboCache.h
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

This does not include lazy allocation or support for an MSAA swap chain.
Those features will come later.

Vulkan: add support for MSAA render targets.

---

filament/src/ResourceAllocator.cpp

FrameGraphTexture::Descriptor uses "0" to mean "auto" but the
sample count that is passed to the backend should always be 1 or
greater.
See also #2957.

Do not pass a zero sample count to the backend.

---

filament/src/PostProcessManager.cpp

the history projection wasn't initialized for the first frame.

fix a whole screen flicker when enabling TAA

---

filament/backend/src/vulkan/PlatformVkAndroid.cpp
filament/backend/src/vulkan/PlatformVkCocoa.mm
filament/backend/src/vulkan/PlatformVkLinux.cpp
filament/backend/src/vulkan/PlatformVkWindows.cpp
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanDriver.h

Motivated by upcoming SwiftShader support, The old debug_report
extension is apparently deprecated but we need to keep it alive
for Android.

Vulkan: Add support for VK_EXT_debug_utils.

---

BUILDING.md
CMakeLists.txt
build.sh
filament/backend/CMakeLists.txt
filament/backend/src/Platform.cpp
filament/backend/src/opengl/gl_headers.cpp
filament/backend/src/opengl/gl_headers.h
filament/backend/src/vulkan/VulkanContext.cpp
samples/CMakeLists.txt

This also adds a -t flag to the easy build script for convenience.
SwiftShader on Vulkan can now be used as follows.
git clone https://github.com/google/swiftshader.git
cd swiftshader/build
cmake .. &&  make -j && export SWIFTSHADER_LD_LIBRARY_PATH=`pwd`
cd ../filament
./build.sh -t debug && ./out/cmake-debug/samples/gltf_viewer -a vulkan
Note that `third_party/swiftshader` does not need to exist since we already have Vulkan headers. I will remove it in a subsequent PR.

Migrate the SwiftShader build to Vulkan.

---

libs/utils/include/utils/compiler.h

Changed if defined WIN32 to if defined WIN32 or _WIN32 because MSVC doesn't define WIN32 or WIN64.

Changed ifdef WIN32 to WIN32 or _WIN32

---

filament/backend/include/backend/DriverEnums.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
shaders/src/ambient_occlusion.fs

- don't apply SSAO to blended objects
these are not drawn into the structure buffer, so they don't 
participate in SSAO.
- remove unused code that was needed for the depth prepass, which
simplifies handling of blended objects.
- always treat alpha-masked objects as opaque.

Fix a few issues with alpha-masked objects

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
filament/src/details/View.h
filament/src/materials/bloom/bloomDownsample.mat

This avoid unrealistic looking bloom halos from very strong highlights.
This is enabled by default.

optionally compress highlights before bloom

---

RELEASE_NOTES.md
filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/gl_headers.cpp
filament/backend/src/opengl/gl_headers.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/Material.cpp
filament/src/MaterialInstance.cpp
filament/src/PostProcessManager.cpp
filament/src/RenderPass.cpp
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/details/MaterialInstance.h
filament/src/details/View.h
filament/src/materials/ssao/sao.mat
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/src/UibGenerator.cpp
shaders/src/depth_main.vs
shaders/src/main.vs
shaders/src/post_process.vs
shaders/src/shadowing.fs

This significantly improve the depth-buffer resolution utilization
through the near-infinity range on Metal and Vulkan.
On OpenGL, this benefit is only seen when glClipControl is available.
The user-facing clip plane is unchanged [-1,1], the conversion
happens in filament's vertex shaders.
The bulk of this change consists in:
- invert the clip space's z in the vertex shader
- clear the depth buffer with 0
- invert all depth function comparisons
- fix all screen-space effects, e.g. ssao, DoF
- fix shadows and shadow biases
- use floating-point depth
- add a driver API to query which clip-space is used
- add glClipControl support to the gl backend

Use "inverted-Z" depth buffer

---

RELEASE_NOTES.md
filament/include/filament/Engine.h
filament/src/Engine.cpp
filament/src/details/Engine.h

Because initializing the backend can be relatively slow, creating an
Engine can block the main thread, is this is a problem, this new API
can be used instead; while a bit more complex, it allow the engine to
be initialized asynchronously.

New API to create an Engine asynchronously

---

filament/src/materials/dof/dofDownsample.mat
filament/src/materials/dof/dofMipmap.mat

apply the "fireflies" reduction during the downsampling pass instead of
the mipmap pass -- which didn't make a lot of sense.

improve stability of DoF with highlights

---

shaders/src/getters.fs

this broke recently with the reverse-z, the froxel calculation relies
on the depth, which is now inverted.
we actually fix our getNormalizedViewportCorrd() public API, which the
froxel code uses.

fix dynamic lighting frozen calculation

---

filament/src/PostProcessManager.cpp
filament/src/View.cpp
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/src/UibGenerator.cpp
samples/material_sandbox.cpp
shaders/src/ambient_occlusion.fs

- fix a recent typo that affected SSAO quality
- add a upsampling quality checkbox in material_sandbox
- make use of textureLodOffset instead of texelFetch, so that
we emulate more closely textureGather
- don't hardcode bilateral filter edge-distance in the shader
(still hardcoded on the cpu side)

ssao code improvements and bug fixes

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/materials/colorGrading/colorGrading.mat
filament/src/materials/colorGrading/colorGradingAsSubpass.mat
shaders/src/dithering.fs

- don't use frameUniform.time as the temporal noise seed because
this has a cycle to it. It's not very visible on dithering but
obvious when used for other things.
- don't use fract(time) since time was already in [0,1] -- though it's
moot now.
- instead of time pass a random number in [0,1] generated on the CPU
each frame.
This will also allow to control temporal noise more easily if
needed in the future (e.g. for accessibility or rendering tests)

rework a bit dithering noise

---

filament/src/materials/ssao/sao.mat

We add noise do the radius of the samples on the spiral 
(instead of adding noise only to the angle), this reduces a visible
"echo", especially at higher radii.
before:
after:

attempt at a better noise for SSAO

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt

tombstone happens if run destory while loadModelGltfAsync in ModelViewer.kt
To Reproduce
1.loadModelGltfAsync
2.detach from the winodw quickly
3.tombstone ..

CoroutineScope job should be canceled before destory

---

filament/src/Camera.cpp
filament/src/PostProcessManager.cpp
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp
filament/src/ToneMapping.h
filament/src/components/LightManager.cpp
filament/src/details/Camera.h
filament/test/filament_test.cpp
libs/math/include/math/scalar.h

e.g. `F_PI` is also available as `d::PI` and `f::PI` as `double` or
`float` respectively.
Most of our uses of those constants are `float` and it was error prone
and cumbersome to have to cast to that each time we used them.
The `F_` constants are intended to mimic `math.h`, however these new
constants are not, and all the "n over" constants are named
`N_OVER_` instead of `N_`, which helps avoiding the confusion that e.g.:
`F_2_PI` is actually `2/pi` and not `2*pi`.
Also added `F_TAU` which is 2 * PI.

add float versions of math constants to libmath

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/materials/ssao/bilateralBlur.mat
filament/src/materials/ssao/sao.mat

- simulate a standard deviation of 8 by skipping every other pixel
when blurring the AO buffer at LOW or MEDIUM quality. This creates
a faint checker pattern, but does look much better than the low
frequency noise that is introduced otherwise.
- tweak AO parameters to give a more uniform and smooth AO effect by
default. This also makes AO even more consistant between quality
modes.
- add a simple dithering stage to AO blur to help eliminate banding
artifacts at higher sample counts.
before:
after:

Improvements to SSAO quality

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
docs/webgl/filament.js
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
filament/src/details/Camera.h
filament/src/details/View.h
samples/gltf_viewer.cpp
web/filament-js/extensions.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

.blurScale was in fact a scale factor applied to the circle of
confusion (which makes it indeed a "blur scale", but let's use
a more precise language here). 
Update comments to show how to  use .cocScale to control the DoF
effect independently from the camera aperture, which can be useful for
artistic reasons.

rename .blurScale to .cocScale in dof options

---

android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
libs/filabridge/src/UibGenerator.cpp
libs/gltfio/include/gltfio/SimpleViewer.h
samples/material_sandbox.cpp
shaders/src/fog.fs

- inScatteringSize actually cannot be set to zero because it produces
a 0^0 in the shader. So with this change, in-scattering must be
strictly > 0 to enable.
- inScatteringSize on the java side had an incorrect default value of
zero (which of course, now doesn't matter anymore).
- also clamp the fog altitude to 1mm which simplifies the shader quite
a bit for the same result.
Fixes #3069

several fog fixes

---

filament/src/fg/fg/ResourceEntry.h

resources structures where not cleared when destroyed, and some code
relies in the handles being set or not to decide if a texture should
be used.  in this case, the texture would be set in the shader after
it was destroyed, because its handle wasn't cleared.

fix use after free in the framegraph

---

filament/backend/src/opengl/CocoaTouchExternalImage.mm
filament/backend/src/opengl/GLUtils.cpp
filament/backend/src/opengl/GLUtils.h
filament/backend/src/opengl/OpenGLBlitter.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h

There was an inconsistency in the gles backend where non-sampleable,
non-MS textures failed (assert) if they were used with a render target 
with MS (i.e. "magic resolve" case).
We fix this by taking the same code path for textures and renderbuffers,
the only difference being the calls to glFrameBufferRenderbuffer
instead of glFramebufferTexture2D.

non-sampleable textures didn't support "magic resolve"

---

filament/src/materials/dof/dof.mat

This is a bit of a hack but it helps a lot -- for some reason the
background layer often has a sharp transition to the in-focus plane and 
because we're calculating the DoF at 1/4 resolution these transitions
are quite visible. We work around this by fading out the transition over
a 1 CoC unit, specifically between a CoC of 2 to 1 pixel. Below 1 pixel,
we currently clamp to 0.
Before:
After:

smooth out the transition from the background layer

---

filament/src/Renderer.cpp
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/details/ShadowMapManager.h
filament/src/details/View.h

contact shadows wouldn't work if shadowmap-based shadows were not
enabled, in this case the (unneeded) shadow pass would run and
attempt to create the shadow-map with an incorrect size (0), which
would later crash/assert in the backend.

fix a recent regression with contact shadows

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
filament/src/details/View.h
filament/src/materials/ssao/sao.mat
libs/gltfio/include/gltfio/SimpleViewer.h
samples/material_sandbox.cpp

We borrow a page from the HBAO book here and allow to limit the angle
with the horizon of SSAO samples. This can help reducing the effects
of low tessellation, which tend to create unwanted creases with SSAO.
Before:
After:

ssao: reduce creases caused by geometry tessellation

---

libs/gltfio/materials/ubershader.mat.in
libs/gltfio/src/MaterialGenerator.cpp

The glTF spec doesn't call for this and there are extensions to deal with this manually.

Disable clear coat layer IOR change in glTF files

---

libs/gltfio/src/MaterialProvider.cpp

The equality operator for MaterialKey was missing some fields (also, its
ordering was inconsistent with the struct), which caused faulty behavior
in the material cache.
I ran into this bug when testing against a Blender-exported model that
has some materials with texture transforms, and some without.

gltfio: Fix "uniform not found" errors.

---

filament/src/Scene.cpp
libs/math/include/math/mat3.h
libs/math/tests/test_mat.cpp
shaders/src/main.vs

This is similar to my first attempt but now I'm more happy with the comments and explanations that I've added.
This was tested by replacing the node 0 scale in BusterDrone with [-1, 1, 1].
For future reference, commit f728776 shows when we switched from transpose(inverse()) to cof(). This was a good change, but before that particular change, we had a "two wrongs made a right" situation for mirrored normals.
Fixes #3001.
Before / After screenshots for Node_NegativeScale_07:

Flip the shading normal when det < 0.

---

libs/matdbg/README.md
libs/matdbg/include/matdbg/DebugServer.h
libs/matdbg/src/DebugServer.cpp
libs/matdbg/web/script.js
libs/matdbg/web/style.css
libs/utils/include/utils/CString.h
libs/utils/src/CString.cpp

- Fixed edits for large shaders.
- If the shader source exceeds the websocket max size, we might receive it in chunks.
- We now allow for this by including a length prefix in the EDIT command.
- Added support for UTF-8 string encoding.
- Display an orange warning when editing an unused shader variant.

matdbg: fix edits for large shaders. 

---

libs/matdbg/web/script.js

This makes it so that the primary material in Sponza is always "untitled 0", which makes it easier to figure out which material to modify.

matdbg: stable ordering for anonymous materials.

---

web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

There's no really good solution, so this just keeps it simple and makes
is so that embind consumes an integer rather than an embind enum object.
Tested by hacking _createTextureFromImageFile.
Fixes #3028.

JavaScript bindings: fix TextureUsage bitmask.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp

This image barrier should wait until all write operations are complete. This was not set up correctly (src and dst flags were flipped) but this did not manifest in any visible problems or validation errors.
I also tried to document this better, since using an image barrier for the swap chain seems to be an unusual thing to do (e.g. the Sascha Willems demos do not do this).

Vulkan: fix final image barrier used for swap chain.

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/CMakeLists.txt
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
filament/src/details/View.h
filament/src/materials/ssao/dominantLightShadowing.fs
filament/src/materials/ssao/sao.mat
filament/src/materials/ssao/ssaoUtils.fs
libs/gltfio/include/gltfio/SimpleViewer.h
libs/math/include/math/scalar.h
samples/material_sandbox.cpp

This is a technique from Naughty Dog used in TLOU2, where we compute
the "ambient" shadowing of a dominant light in screen-space using cone
tracing.
This is currently integrated to the SSAO pass.

Implement Screen Space Cone Tracing (SSCT)

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/CMakeLists.txt
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
filament/src/details/View.h
filament/src/materials/ssao/sao.mat
filament/src/materials/ssao/ssct.fs
libs/viewer/src/SimpleViewer.cpp
samples/material_sandbox.cpp

- Use lower depth LOD as the cone radius increases.
This is the same technique we use for SAO.
The better cache access significantly improve performance.
On a test on Pixel4 at 585MHz, SAO pass improves by 30%.
This also helps the algorithm scale with the shadow distance.
- Shadow direction/length no longer dependent on aspect-ratio and camera
orientation.
This is fixed by doing all the computations in screen-space instead of 
normalized screen space.
- Shadow parameters are no longer dependent on the field of view.
- Also rename dominantLightShadowing.fs to ssct.fs
- remove zoom parameter, it wasn't very useful.

SSCT optimizations and fixes

---

filament/src/ShadowMap.cpp
filament/src/ShadowMapManager.cpp
filament/src/details/ShadowMap.h
shaders/src/common_shadowing.fs
shaders/src/depth_main.fs
shaders/src/getters.fs
shaders/src/light_directional.fs
shaders/src/light_punctual.fs
shaders/src/shadowing.fs

This switches to using the light space Z coordinate as the VSM depth metric. This fixes precision issues seen with a distant camera far plane.

Use light space Z as VSM depth metric

---

libs/viewer/CMakeLists.txt
libs/viewer/include/viewer/Automation.h
libs/viewer/include/viewer/Settings.h
libs/viewer/include/viewer/SimpleViewer.h
libs/viewer/src/Automation.cpp
libs/viewer/src/Settings.cpp
libs/viewer/src/SimpleViewer.cpp
libs/viewer/src/jsonParseUtils.h
libs/viewer/src/parse.h
libs/viewer/tests/test_settings.cpp

This lets us generate long lists of settings permutations by writing a
simple JSON spec. For example, the following spec would generate six
`Settings` objects, all of which have SSAO enabled. See the unit test
for a larger example.
```
{
"name": "viewopts",
"base": { "view.ssao.enabled": true }
"permute": {
"view.dithering": ["NONE", "TEMPORAL"],
"view.sampleCount": [1, 4, 8]
}
}
```

Introduce a configurable test case generator.

---

.gitignore
libs/viewer/CMakeLists.txt
libs/viewer/include/viewer/AutomationEngine.h
libs/viewer/include/viewer/AutomationSpec.h
libs/viewer/include/viewer/SimpleViewer.h
libs/viewer/src/AutomationEngine.cpp
libs/viewer/src/AutomationSpec.cpp
libs/viewer/tests/test_settings.cpp
samples/CMakeLists.txt
samples/gltf_viewer.cpp

This adds `AutomationEngine` to libs/viewer, which iterates through
`Settings` instances that were generated from a JSON spec and applies
them to a Filament `View`. It can be configured to sleep between tests
using a time delay or a frame count.
This also adds command line arguments and user-interface elements to
`gltf_viewer` for automated testing.

gltf_viewer: Add automation UI and functionality.

---

libs/viewer/include/viewer/AutomationEngine.h
libs/viewer/include/viewer/Settings.h
libs/viewer/src/AutomationEngine.cpp
libs/viewer/src/Settings.cpp
libs/viewer/tests/test_settings.cpp
samples/gltf_viewer.cpp

This adds a `material` key to `Settings`, as a sister to `view`.
The image attached to this PR description was generated with the following commands.
```
gltf_viewer --batch=batch.json third_party/models/shader_ball/shader_ball.gltf
montage -border 0 -geometry 660x -tile 3x2 test*.png atlas.png
```
Contents of `batch.json`:
```json
[{
"name": "metallic_vs_roughness",
"permute": {
"material.scalar.roughnessFactor": [0.0, 0.5, 1.0],
"material.scalar.metallicFactor": [0.0, 1.0]
}
}]
```
Currently this is limited to float, vec3, and vec4 parameters.

Automation: add support for materials.

---

libs/viewer/include/viewer/AutomationEngine.h
libs/viewer/src/AutomationEngine.cpp
samples/gltf_viewer.cpp

The Filament View that gets passed to tick() is retained briefly when
screenshots are enabled, but it may be destroyed by the time the
PixelBufferDescriptor callback is invoked. So, we needed a way of
notifying the AutomationEngine.

Automation: fix segfault when closing the app early.

---

android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/RenderableManager.h
filament/include/filament/View.h
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/details/View.h
shaders/src/shadowing.fs

VSM is unique in that both shadow casters AND shadow receivers must be rendered into the shadow map.  This differs slightly from PCF shadows:
|caster|receiver|PCF rendered|VSM rendered|example|
|--:|--:|--:|--:|--:|
|0|0|NO|NO|skybox|
|0|1|NO|YES|ground plane|
|1|0|YES|YES|an offscreen [cucoloris](https://en.wikipedia.org/wiki/Cucoloris)|
|1|1|YES|YES|typical object|
The second scenario, where PCF and VSM differ, is what is being updated here.
- Rename `VISIBLE_DIR_SHADOW_CASTER` type visibility bits to `VISIBLE_DIR_SHADOW_RENDERABLE`, to make them more general
- Update `computeVisibilityMasks` logic to mark all shadow receivers visible during VSM shadow passes.

VSM: render both shadow casters and receivers

---

filament/backend/src/DataReshaper.h
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

This adds support for headless rendering as well as readPixels. These features are necessary for automated testing.
NOTE: invoking readPixels with a non-headless SwapChain seems to fail with MoltenVK. I will investigate this later.

Vulkan: support readPixels and headless swap chains.

---

filament/backend/src/DataReshaper.h
filament/backend/src/vulkan/VulkanDriver.cpp

Fixes a color issue seen with SwiftShader in non-headless mode.

Vulkan ReadPixels: fix platforms that use BGRA.

---

libs/utils/src/JobSystem.cpp

If hardware_concurrency() returned 2 while UTILS_HAS_HYPER_THREADING was
enabled, `mThreadCount` was resulting in zero, so jobs (such as texture
decoding) would simply never start. This problem was noticed with
GitHub Actions.
I tested this fix locally by replacing `hardware_concurrency()` with
fixed values like 1 or 2, and verified that the hang went away.

JobSystem: work around hang on 2-CPU machines

---

filament/include/filament/Renderer.h
filament/include/filament/Scene.h
filament/src/Scene.cpp
libs/utils/include/utils/compiler.h
libs/utils/src/linux/futex.h

The non-const getSkybox() method is especially useful to client code
that needs to change the clear color, but does not have direct
access to the Renderer object.

Various changes to help clients upgrade Filament.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
filament/CMakeLists.txt
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/details/ShadowMapManager.h
filament/src/details/View.h
filament/src/materials/vsmMipmap.mat
libs/filamat/src/Enums.cpp
libs/viewer/include/viewer/Settings.h
libs/viewer/src/Settings.cpp
libs/viewer/src/SimpleViewer.cpp
libs/viewer/tests/test_settings.cpp

Anisotropic filtering helps improve VSM shadow quality at glancing angles.

VSM: add support for mipmaps and anisotropic sampling

---

filament/backend/src/vulkan/PlatformVkLinux.cpp
filament/backend/src/vulkan/PlatformVkLinux.h
libs/bluevk/include/vulkan/vk_platform.h

This allows clients to build the Vulkan backend with either XLIB or XCB
support. I did a quick smoke test of the XCB option, but for now we are
continuing to default to XLIB. Note that the native window type used to
create the swap chain differs between these two API's.

Add optional XCB support to PlatformVkLinux.

---

filament/backend/src/DataReshaper.h
filament/backend/src/DriverBase.h
filament/backend/src/TextureReshaper.cpp
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanDriver.h
filament/backend/src/vulkan/VulkanUtility.cpp
filament/backend/src/vulkan/VulkanUtility.h

This adds support for more format conversions and removes a bogus
assert that prevented ReadPixels within beginFrame / endFrame.
This was tested with:
backend_test_mac --api vulkan --gtest_filter=BackendTest.ReadPixels

Vulkan: improve the ReadPixels implementation.

---

filament/backend/src/DriverBase.h
filament/backend/src/vulkan/VulkanDisposer.h
filament/backend/src/vulkan/VulkanDriver.h

This fixes a regression introduced by 548b28c6e manifesting as
intermittent assertions. The VulkanDisposer gc() should only be called
from the driver thread.

Vulkan: fix thread safety regression in Disposer.

---

filament/backend/src/vulkan/VulkanBuffer.cpp
filament/backend/src/vulkan/VulkanBuffer.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

This avoids the following validation error when clients create then
immediately destroy vertex buffers, index buffers, and uniform buffers.
VUID-vkDestroyBuffer-buffer-00922
Cannot free VkBuffer that is in use by a command buffer.
Buffers that are used across multiple frames were fine, but
create-and-destroy scenarios were problematic.

Vulkan: Improve refcounting for vertex buffers.

---

CMakeLists.txt
android/filament-android/src/main/java/com/google/android/filament/SwapChain.java
filament/backend/include/backend/DriverEnums.h
filament/backend/src/vulkan/PlatformVkAndroid.cpp
filament/backend/src/vulkan/PlatformVkAndroid.h
filament/backend/src/vulkan/PlatformVkCocoa.h
filament/backend/src/vulkan/PlatformVkCocoa.mm
filament/backend/src/vulkan/PlatformVkCocoaTouch.h
filament/backend/src/vulkan/PlatformVkCocoaTouch.mm
filament/backend/src/vulkan/PlatformVkLinux.cpp
filament/backend/src/vulkan/PlatformVkLinux.h
filament/backend/src/vulkan/PlatformVkWindows.cpp
filament/backend/src/vulkan/PlatformVkWindows.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanPlatform.h
filament/include/filament/SwapChain.h
libs/bluevk/include/vulkan/vk_platform.h

You can now build Filament with support for both X11 APIs, or neither.
If both are supported, run-time selection is achieved using a SwapChain
flag.
Supporting only one API at build time (or neither) is useful because our
list of "required" VkInstance extensions can vary according to which
API's are supported. During VkInstance creation, we do not have a priori
knowledge about what kinds of swap chains will be created. (headless vs
non-headless, XCB vs XLIB, etc)
Note that some Vulkan implementation (e.g. some builds of SwiftShader)
only support XCB.

PlatformVkLinux now supports all combos of XLIB and XCB.

---

filament/src/materials/colorGrading/colorGradingAsSubpass.mat

This fixes the blank screen seen with Vulkan when all view options are
disabled.

Fix colorGradingAsSubpass when dithering is off.

---

filament/backend/src/vulkan/VulkanBinder.cpp
filament/backend/src/vulkan/VulkanBinder.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

This fixes a slew of validation warnings and errors seen when multiple
subpasses are enabled, starting with:
Attachment 1 not written by fragment shader; undefined values will
be written to attachment
The Vulkan driver was using the same color attachment list for both
subpasses, so the first subpass had unused attachments.
Note that Vulkan makes a distinction between color attachments and input
attachments and requires separate lists to be supplied for each subpass,
but our Driver API consolidates everything into a single list. This
should perhaps be refactored at a later date.

Vulkan: fix color attachment list in first subpass.

---

libs/mathio/include/mathio/ostream.h
libs/mathio/src/ostream.cpp

This functionality was accidentally lost when we created the mathio lib.

mathio: add ostream operator for quaternions.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanHandles.cpp

After a blit that targets the swap chain, we were transitioning it straight to VK_IMAGE_LAYOUT_PRESENT_SRC_KHR.  This became incorrect when we changed our layout strategy such that swap chain images are normally kept in VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL until the end of the frame.

Vulkan: fix layout mismatch after blits to swap chain.

---

android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
libs/gltfio/include/gltfio/AssetLoader.h
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/Animator.cpp
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/DependencyGraph.cpp
libs/gltfio/src/DependencyGraph.h
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/ResourceLoader.cpp
samples/gltf_instances.cpp
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

Note that this API is on the loader rather than the asset. This is
because the loader knows how to create Filament entities by traversing
a cgltf node hierarchy.
We did not add destroyInstance() because gltfio favors flat arrays for
long term storage of entity lists and instance lists, which would be
slow to shift. We also wish to discourage create/destroy churn since it
is more efficient to pre-allocate instances and selectively add them
into the scene.
Fixes #3137.

gltfio: add createInstance() to AssetLoader.

---

filament/backend/src/metal/MetalHandles.mm
filament/src/Fence.cpp

We use the highest value of a `uint64_t` in nanoseconds to denote an infinite timeout for fences. However, `std::chrono::nanoseconds` uses a signed `int64_t`. This causes a negative timeout when passing the value to a `std::cv`.

Fix bug with Fence timeouts

---

libs/utils/include/utils/linux/Condition.h

The number of infinite nanoseconds was negative because we asked
chrono for a signed integer, so "wait forever" really meant "do not
wait at all".

Fix FENCE_WAIT_FOR_EVER in Linux.

---

filament/src/Fence.cpp

FFence::wait() has some logic that tests if "timeout" is equal to
FENCE_WAIT_FOR_EVER, which is actually impossible because it would
be modified by the clamp in this situation.
In practice I think this oversight would not cause any problems. I
noticed it while reviewing the code.
To recap why the clamp exists: according to the ISO C++ spec, the
"nanoseconds" duration in chrono is at least a signed 64-bit type, but
our sentinel constant might not (and does not) fit within this range.

Another fix for FENCE_WAIT_FOR_EVER.

---

filament/backend/src/metal/MetalHandles.mm
filament/src/Fence.cpp

Fence.cpp:
My previous fix to the fix was insufficient because a signed integer
overflow could still occur as follows (this was observed in an internal
test at Google).
If the conditional on line 87 is true, then a clamped value is passed
into `wait`, which causes the conditional on line 133 to fail, which
causes `wait_for` to be called inappropriately, which is where an
overflow would occur.
MetalHandles.mm:
This is more theoretical, but to prevent potential integer overflow
within STL, I think we should call `wait()` rather than `wait_for()`
when an infinite timeout is desired.
This is our fourth fix to fences in since November 2; see also dcca236,
e9c9e45, and 8969416.  :)

More fixes for signed integer overflow.

---

filament/backend/src/vulkan/PlatformVkAndroid.cpp
filament/backend/src/vulkan/PlatformVkCocoa.mm
filament/backend/src/vulkan/PlatformVkCocoaTouch.mm
filament/backend/src/vulkan/PlatformVkLinux.cpp
filament/backend/src/vulkan/PlatformVkWindows.cpp
filament/backend/src/vulkan/VulkanBinder.cpp
filament/backend/src/vulkan/VulkanBuffer.cpp
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanSamplerCache.cpp
filament/backend/src/vulkan/VulkanUtility.cpp
libs/bluevk/bluevk-gen.py
libs/bluevk/include/bluevk/BlueVK.h
libs/bluevk/include/vulkan/vulkan.h
libs/bluevk/include/vulkan/vulkan_beta.h
libs/bluevk/include/vulkan/vulkan_core.h
libs/bluevk/src/BlueVK.cpp
libs/bluevk/tests/test_bluevk_sdl.cpp

This moves all Vulkan entry points into the bluevk namespace
to avoid conflicts with other Vulkan loaders.
This also updates the header files and loader code to version 1.2.159 of
the Vulkan spec, which is currently available at the following links.
https://khronos.org/registry/vulkan/specs/1.2/html/vkspec.html
https://github.com/KhronosGroup/Vulkan-Headers/commit/87451c55aa8b4f00831fab6ffc4b721d0f148102

Regenerate BlueVK, use a C++ namespace.

---

filament/src/Material.cpp
filament/src/details/Material.h

This fixes errors that would occur when using the NOOP backend with
materials that were built without OpenGL support.

NOOP backend should not care about GLSL vs SPIRV.

---

RELEASE_NOTES.md
filament/backend/src/opengl/PlatformCocoaGL.mm
libs/filamentapp/src/FilamentApp.cpp

@prideout I'm fine with this if you are. I guess neither of us can remember why this change was needed. The Filament rendering tests still pass.
This reverts commit d5d77a46ec41283e1629dbd19031eb5609f41204.
Fixes #3264.

Revert "macOS: fix headless rendering."

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/backend/PresentCallable.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/test/test_BufferUpdates.cpp
filament/backend/test/test_MRT.cpp
filament/backend/test/test_MissingRequiredAttributes.cpp
filament/backend/test/test_ReadPixels.cpp
filament/include/filament/Renderer.h
filament/include/filament/SwapChain.h
filament/src/Renderer.cpp
filament/src/SwapChain.cpp
filament/src/details/Renderer.h
filament/src/details/SwapChain.h

This adds new new APIs to SwapChain:
- `FrameScheduledCallback` (previously `FrameFinishedCallback`). Called when a frame is scheduled by the OS for GPU execution. This is needed on iOS to correctly synchronize between UI elements and 3D rendering.
- `FrameCompletedCallback`. Called when a frame has completed on the GPU (similar to a hard fence).

Add callback API to SwapChain

---

filament/src/Renderer.cpp
filament/src/details/Renderer.h

This fixes a bug seen with client applications that use ClearOptions
instead of Skybox, and one or more offscreen RenderTarget objects.
These apps would see junk pixels because Filament would only clear the
first render target in the frame.
The fix is to factor some the flag-setting logic in `beginFrame()` into
a private method, and call this method from `render()` each time
the user-level RenderTarget has been changed.
I wrote a simple C++ demo to reproduce the issue and to verify that
this fix works.

Fix clear behavior with RenderTarget API.

---

android/common/CallbackUtils.cpp
android/common/CallbackUtils.h
android/filament-android/CMakeLists.txt
android/filament-android/src/main/cpp/SwapChain.cpp
android/filament-android/src/main/java/com/google/android/filament/SwapChain.java

I'm leaving the `FrameScheduledCallback` out, as it has virtually no utility outside of native Objective-C/C++ code.

Add setFrameCompletedCallback JNI binding

---

filament/backend/include/private/backend/Program.h
filament/backend/src/opengl/OpenGLProgram.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/Material.cpp

With Vulkan, this warning would sometimes be a false positive. It could trigger for internal samplers like `ssao` and `structure`, even though they were not declared in SPIR-V.
With OpenGL, this warning would never be a false positive because it has the luxury of calling `glGetUniformLocation`.
This adds an internal field to samplers called `strict` that indicates whether or not a sampler should always have a bound texture. For now the only strict samplers are the custom ones declared in the user's material.
In the future, we should consider adding [spirv-reflect](https://github.com/KhronosGroup/SPIRV-Reflect) to our tree to help with problems like this.

Improve the "unbound texture" warnings.

---

filament/src/Engine.cpp
filament/src/View.cpp

This prevents a SwiftShader crash and/or a slew of "no texture bound"
warnings that would appear when the client provides an IBL without
providing reflections texture, which should be a valid thing to do.
Note that it is okay to declare a sampler in GLSL that never gets bound,
as long as it is never sampled from. Since we always sample from the
IBL specular texture, we should always bind something to it.

Filament should always bind an IBL texture.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp

When passing only 1 fence to vkWaitForFences, the `waitAll` argument should not have any effect, but SwiftShader seems to skip the wait when this argument is set to VK_FALSE.
More specifically, the failure to wait in `acquireWorkCommandBuffer` allows the subsequent destruction of an in-use fence, which causes a TSAN failure with Google's internal tests.
I am consulting with the SwiftShader team on a real fix, meanwhile we can commit this easy workaround.
Note that we have 5 usages of vkWaitForFences, one of which uses multiple fences and should have used VK_TRUE anyway.

Vulkan: change vkWaitForFences usage for SwiftShader.

---

filament/backend/src/opengl/PlatformWGL.cpp

Newer compilers are picky about variable initialization and goto statements.

Fix Windows build.

---

libs/utils/include/utils/StructureOfArrays.h
libs/utils/include/utils/Zip2Iterator.h

I <3 C++
This boils down to the differences between a `const iterator` and a `const_iterator`.
Dereferencing a `const iterator` should return a non-const reference, so it can be assigned:
```
const Zip2Iterator it;
const StructureOfArrays soa;
*it = ...
*soa = ...
```
Fixes #3319, #3327, #3312

Fix Windows iterator issue in Zip2Iterator and StructureOfArrays

---

android/filament-android/libfilament-jni.map

We now export only two groups of symbols: (1) JNI and (2) dynamic linker
symbols used by the companion libraries.
This commit has the following impact:
- Shrinks the arm64 so from 1024 KiB to 954 KiB.
- Shrinks the arm64 aar from 560 KiB to 538 KiB.
Note that the patterns in the map file are tested against mangled names
and therefore should not be used to match the double-colon operator.

Android: do not export internal symbols.

---

filament/backend/src/opengl/OpenGLDriver.cpp

This was problematic with Chrome's ANGLE backend; more information at:
https://bugs.chromium.org/p/chromium/issues/detail?id=941671#c10
Fixes #3308

WebGL: RGB16F is not color renderable.

---

libs/gltfio/src/ResourceLoader.cpp

I load a gltf file, then assert failed at this point:
After spending some time to investigate, the problem is found here:
This is the log's out puts:

Fix computeTangents

---

filament/src/Renderer.cpp
filament/src/details/Renderer.h

This fixes a bug Renderer clearing a render target multiple times when the first time and back again.
Usually the default RenderTarget is unintentionally cleared/discarded in the current behavior.
1) Renderer renders a view without custom RenderTarget having full-screen viewport,
2) Renderer renders a view with custom RenderTarget
3) And Renderer renders an another view without custom RenderTarget having different viewport from 1)
You may see junk or empty pixels in outside of the viewport of the view 3), depending on ClearOptions and the backend.
This fix make Renderer put RenderTargets into a set and check them to be cleared only for the first time, instead of comparing the previous RenderTarget to the current RenderTarget.

Fix clearing Rendertarget multiple times

---

libs/matdbg/src/CommonWriter.cpp
libs/matdbg/src/CommonWriter.h
libs/matdbg/src/JsonWriter.cpp
libs/matdbg/src/TextWriter.cpp
libs/matdbg/web/index.html

Also some minor HTML stuff:
- Hide "Required attributes" header when there are none.
- Remove legend for variants (takes too much space).

matdbg / matinfo: fix post-process variant string

---

filament/src/ShadowMap.cpp
libs/gltfio/src/math.h

This does not change our API, it merely reduces the number of
non-inlined function instantiations appearing in non-optimized binaries.

math: reduce template bloat for matrices

---

build.sh

This makes the tgz consistent with the npm package. Fixes #3268.
This also removes a stale comment in the script (we stopped packaging the old HTML docs a while back).
Going forward, we would like to use the TS declarations as documentation because they must be kept up to date anyway, and they already contain type information. This was discussed in #3250.

build.sh: Add TypeScript bindings to the tgz file.

---

filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.mm

When deleting a texture, we previously only unbound that texture from sampler groups that were bound. This caused a bug when a deleted texture lingered in a sampler group that happened to be unbound at the time of texture deletion. The fix is to check all sampler groups for references to the texture.
Fixes #3384

Unbind texture from all sampler groups upon destroy

---

third_party/spirv-tools/filament-specific-changes.patch
third_party/spirv-tools/source/CMakeLists.txt

This library causes issues on Linux. We had removed it previously, but it got reintroduced during the last spirv-tools upgrade.

Remove libSPIRV-Tools-shared from spirv-tools

---

filament/test/filament_rendering_test.cpp

`RenderingTest` is failing due to our change to use a LUT for tonemapping.
Even when set to `LINEAR` and `ULTRA`, a linear value of 1.0f tonemaps to 254.

Fix Filament RenderingTest

---

libs/gltfio/src/ResourceLoader.cpp
samples/gltf_viewer.cpp

Fixes a crash when dropping a model while the old model is still decoding textures.
Relates to #3383

gltf_viewer: call asyncCancelLoad in drop handler

---

libs/gltfio/include/gltfio/AssetLoader.h
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/Animator.cpp
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp
libs/gltfio/src/FilamentInstance.cpp
libs/gltfio/src/ResourceLoader.cpp

The gltfio API allows users to destroy `ResourceLoader` or `FilamentAsset` even when various asynchronous work (e.g. uploading buffers to the GPU) has not yet been completed. This was achieved in an error-prone manner using manual reference counting and an internal management object called `AssetPool`.
This PR refactors gltfio by internally wrapping cgltf_data in `shared_ptr`, which I usually try to avoid. However in this case it provides the precisely the functionality that is needed.
I tested this PR for memory leaks and crashes by hacking gltf_viewer and monitoring memory usage in Activity Monitor.
This fixes #3383 and makes it easier to implement some missing features, such as animation support for instanced assets.

Simplify lifetime management of cgltf_data.

---

libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/ResourceLoader.cpp
samples/gltf_viewer.cpp

This could occur when trying to exit the app while textures are still being decoded.

gltf_viewer: fix sporadic crash when exiting.

---

samples/CMakeLists.txt
samples/materials/mirror.mat
samples/rendertarget.cpp

When we removed the old "ghetto bloom" demo, we ceased to have any samples demonstrating the RenderTarget API. This demo is a fairly simple demonstration of planar reflection.

Add simple RenderTarget demo (planar reflection)

---

filament/test/filament_framegraph_test.cpp

don't use slog from a static variable, because it might not have been
constructed yet, due to static initialized order.
For some reason, this happens on aarch64 macs, but this was actually
a real problem.

fix filament_test on aarch64 mac

---

filament/src/ResourceAllocator.cpp
filament/src/ResourceAllocator.h

Only items older than a certain value were purged from the cache,
this allowed the cache to grow unbounded before this age limit was
reached.
We now purge the cache at each frame if it's above the size threshold.
Fixes #3381

make sure the ResourceAllocator stays below the cache size limit

---

libs/gltfio/include/gltfio/Animator.h
libs/gltfio/include/gltfio/AssetLoader.h
libs/gltfio/include/gltfio/FilamentInstance.h
libs/gltfio/src/Animator.cpp
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/ResourceLoader.cpp
samples/gltf_instances.cpp

I tested this by viewing CesiumMan with our `gltf_instances` sample app.
There is now a need for some general refactoring in gltfio. I feel that
the high-level objects have become too tightly coupled to each other.
Fixes #3137.

gltfio: support animation in dynamically-added instances.

---

filament/src/Froxelizer.cpp

Fix a possible out-of-bound access when reading the x-planes array. 
Also account for the fact that the loops filling the froxels assume
stl-like iterators (1-past the end on the right), while the indices
themselves were right-inclusive.
fixes #3142

fix missing froxel

---

libs/utils/include/utils/Allocator.h
libs/utils/include/utils/SingleInstanceComponentManager.h

This allows StructureOfArraysBase's move constructor to compile.
Removed an apparent workaround in SingleInstanceComponentManager.

Add swap() methods to Allocator.h

---

filament/backend/src/opengl/PlatformCocoaGL.mm

This fixes "illegal hardware instruction" seen on my MacBook, which
is the same as #1839, but triggered only in a test environment where
the main thread is the same as the driver thread, and filament is built
with HAS_THREADING enabled.

Repair backend unit tests on macOS.

---

filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h

This is a follow-on to #3451, which adds optional ping-pong support to the bloom generator.

Plumbing for disabling feedback loops on Intel.

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h

Second attempt after abandoning #3451.
Feedback loops do not work with Chrome or Intel GPU's, so we now have an optional ping-pong implementation of Bloom.
Issue #2338.

Introduce optional ping-pong bloom implementation.

---

shaders/src/shading_lit.fs
shaders/src/shading_unlit.fs

This prevents light from being emitted from completely transparent pixels.
Fixes #3454.

Modulate emissive by alpha on blended objects

---

filament/src/ColorGrading.cpp
libs/utils/include/utils/compiler.h

This hopefully silences a false-positive TSAN warning seen when running presubmit tests.
```
WARNING: ThreadSanitizer: data race (pid=3367)
Write of size 8 at 0x7ffc9caf90a0 by main thread:
#0 memcpy third_party/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:810:5 (3144f0fc6ff5d690d2d6dd958acc0500298d9d65e2370c148d7cfe62f7c06bb4_020008bb7de0+0x12d0a90)
#1 selectColorGradingTransformIn third_party/filament/filament/src/ColorGrading.cpp (3144f0fc6ff5d690d2d6dd958acc0500298d9d65e2370c148d7cfe62f7c06bb4_020008bb7de0+0x21ea269)
#2 filament::FColorGrading::FColorGrading(filament::FEngine&, filament::ColorGrading::Builder const&) third_party/filament/filament/src/ColorGrading.cpp:446:37
Previous read of size 8 at 0x7ffc9caf90a0 by thread T35:
#0 …
```

Fix sporadic data race warning seen in Google3

---

RELEASE_NOTES.md
android/filamat-android/CMakeLists.txt
android/filamat-android/src/main/cpp/MaterialBuilder.cpp
android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java
android/filament-android/src/main/cpp/Engine.cpp
android/filament-android/src/main/java/com/google/android/filament/Engine.java
android/samples/sample-material-builder/src/main/java/com/google/android/filament/material_builder/MainActivity.kt
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/GLSLPostProcessor.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/tests/test_filamat.cpp
libs/filamat/tests/test_includes.cpp
libs/filamentapp/src/MeshAssimp.cpp
libs/gltfio/src/MaterialGenerator.cpp
samples/sample_cloth.cpp
samples/sample_full_pbr.cpp
samples/sample_normal_map.cpp
tools/matc/src/matc/MaterialCompiler.cpp

We currently generate 128 shader variants per target API per material. On a 12-core MacPro, running `matc` on
`sandboxCloth.mat` takes ~12 seconds. After multi-threading using `JobSystem` it takes ~2 seconds. There are
many optimizations we could do to further improve these numbers, mainly around allocations, especially in
`GLSLPostProcessor`.
Unfortunately we rely on `glslang` and `spirv-*` which don't make any thread safety guarantees. Actually `glslang`
is particularly hostile since it uses globals in unsafe ways in various places. This is worked around by first running
a single job by itself that ensures `glslang` is properly initialized.

Multi-thread shaders generation when compiling materials

---

libs/gltfio/src/AssetLoader.cpp

MaterialGenerator selects a custom blend mode for transmissive models,
therefore the AssetLoader should look at the material's blend mode when
it sets up properties, not the one requested by the glTF file.
Fixes #3444.

gltfio: Fix "_maskThreshold not found" error.

---

libs/math/include/math/TQuatHelpers.h
libs/math/tests/test_quat.cpp

I noticed that our slerp function sometimes produces a jolt in
animation, but only when the time delta is very small, and only when the
two operands have completely opposing signs.
For example, let's say you are slerping from <0.76, 0.39, 0.51, 0.19>
to <-0.72, -0.45, -0.49, -0.17>.
These quats are actually quite near to each other because the total
negation of the second quat is similar to the first quat.
We were already doing the short path check in the proper slerp path, but
not when falling back to lerp due to a small angle.

Quaternion slerp: ensure "short path" when falling back to lerp.

---

RELEASE_NOTES.md
filament/backend/src/opengl/OpenGLDriver.cpp

This fixes `GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE` caused by the following spec clause being violated:
```
The value of RENDERBUFFER_SAMPLES [must be] the same for all
attached renderbuffers and, if the attached images are a mix of
renderbuffers and textures, the value of RENDERBUFFER_SAMPLES
is zero.
```
Tested on Chrome with Triangle and Helmet demos (after enabling MSAA).
Also tried running the automation suite in a debug build on macOS, to see if any asserts or GL errors would be triggered.
Fixes #3128.

Fix MSAA for OpenGL ES 3.0 core. (third attempt)

---

docs/Materials.md.html
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/GLSLPostProcessor.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/sca/GLSLTools.cpp
libs/filamat/src/sca/GLSLTools.h
shaders/src/getters.vs

In order to support vertex indices (OpenGL: `gl_VertexID` or Vulkan: `gl_VertexIndex`), we need to
update some glslang options when compiling GLSL to SPIR-V under OpenGL semantics.
This change is a bit risky, and I'm still in the process of checking that nothing breaks.
As far as I can tell, there's only one scenario where we use GLSL Vulkan semantics but still compile
to OpenGL-flavored GLSL, and that's for framebuffer fetch. I treat this as a special case, which
we're already doing somewhat.

Add getVertexIndex API for vertex shaders

---

android/filament-android/CMakeLists.txt
filament/backend/CMakeLists.txt

We should probably change our continuous CI so that it does not
exclude Vulkan, but keep our release CI as is (for small binaries).
Fixes #3505

Repair Vulkan-enabled Android builds.

---

libs/gltfio/src/UbershaderLoader.cpp

Since the ubershader does not have variants for clear coat, the dummy texture there should be unconditional.

Fix logcat spam with ubershaders.

---

filament/src/ColorGrading.cpp

This is a second attempt to fix Google3 TSAN failures seen inside of the `ColorGrading` constructor.
```
WARNING: ThreadSanitizer: data race (pid=3367)
Write of size 8 at 0x7ffc9caf90a0 by main thread:
#0 memcpy third_party/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:810:5 (3144f0fc6ff5d690d2d6dd958acc0500298d9d65e2370c148d7cfe62f7c06bb4_020008bb7de0+0x12d0a90)
#1 selectColorGradingTransformIn third_party/filament/filament/src/ColorGrading.cpp (3144f0fc6ff5d690d2d6dd958acc0500298d9d65e2370c148d7cfe62f7c06bb4_020008bb7de0+0x21ea269)
#2 filament::FColorGrading::FColorGrading(filament::FEngine&, filament::ColorGrading::Builder const&) third_party/filament/filament/src/ColorGrading.cpp:446:37
Previous read of size 8 at 0x7ffc9caf90a0 by thread T35:
#0 …
```

Fix TSAN issue by using lock in ColorGrading constructor

---

RELEASE_NOTES.md

The 1.9.11 release is a larger release than normal. Here's my attempt at compiling the release notes.
Feel free to make suggestions or directly modify this PR if I've left something out.
You can see all the commits here: https://github.com/google/filament/compare/release...rc/1.9.11

Update RELEASE_NOTES for 1.9.11

---

filament/backend/src/vulkan/VulkanBinder.cpp
filament/backend/src/vulkan/VulkanBinder.h
filament/backend/src/vulkan/VulkanDriver.cpp

This prevents an "Invalid VkImageView Object" error that would occur
after disabling bloom.
This was caused by the fact that we do not bother zeroing out all the
descriptor slots that are not used by the current draw call.

Vulkan: fix lifetime issue with image views.

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/ShadowMapManager.cpp

This fixes some OpenGL non-compliance (as per "Rendering Feedback
Loops" in the spec), as well as validation errors with Vulkan.
I'm hopeful this can be automatic in the new frame graph. :)

PostProcessManager: call setMinMaxLevels in more places.

---

libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp

When running semantic analysis on a material, we were arbitrarily choosing the first code gen permutation to analyze. So, running `matc` with arguments `--api metal` versus `--api all` would run analysis on slightly different shader code. This causes bugs when flags passed to glslang differ during semantic analysis. This change updates all semantic analysis to always use the same shader code.

matc: Use consistent params for semantic code analysis

---

filament/backend/src/vulkan/VulkanBinder.cpp
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp

According to the portability spec: "If this extension is supported by
the Vulkan implementation, the application must enable this extension."
On my 2019 MacBook, enabling this extension triggers errors relating to
depth comparison samplers which I believe to be bogus, so I filed a
LunarG bug. For now we silence this specific error message.

Vulkan: conform to PORTABILITY_SUBSET for Molten.

---

libs/bluevk/src/BlueVKLinuxAndroid.cpp

One of Filament's Linux clients at Google wishes to specify a special
path to the SwiftShader library that proffers Vulkan entry points, and
this path can only be determined at run time.
An environment variable seems like the easiest way to support this
functionality. To prevent a security hazard, the env var is checked only
if a special build-time flag is enabled.

BlueVK: optionally consult environment variable.

---

filament/src/Scene.cpp
libs/utils/include/utils/compiler.h

I verified that this code is not enabled in our GitHub builds, and I
verified that the MSAN error goes away.

Avoid uninitialized reads in computeVisibilityMasks.

---

android/filament-android/libfilament-jni.map
libs/gltfio/src/AssetLoader.cpp

Without this change, a valid glTF file only supplies values between 0 and 1 for `emissiveFactor` which means emissive surfaces never bloom. I used a somewhat arbitrary EV factor (see comment for reasons) but we could also apply the inverse tonemap operator to `emissiveFactor`.

Attempt at improving bloom/emissive with glTF files

---

filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.mm

This makes debugging Metal captures much easier to follow.

Label Metal render encoders with group markers

---

.github/workflows/linux-continuous.yml
.github/workflows/presubmit.yml
.github/workflows/release.yml

`ubuntu-latest` now points to `ubuntu-20.04`, which causes our Linux builds to fail with:
```
/usr/bin/ld: /usr/lib/llvm-8/bin/../lib/libc++abi.a: error adding symbols: archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Downgrade Linux GitHub Actions environment to fix error

---

CMakeLists.txt
filament/backend/CMakeLists.txt

This adds `-fno-exceptions` to iOS builds, to mirror Android.
A better way to control exceptions, as @pixelflinger mentioned, is to make this a CMake setting, exposed to `build.sh`. I'll leave that work to a separate change.

Remove exceptions on iOS

---

libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/eiff/ShaderEntry.h

With multithreaded variant compilation, compiled materials differ based on which variants finish first. This change ensures that compiled materials are always bit-for-bit identical.
This is helpful when comparing two compiled materials. Hashing the material files can be used to check for equality. It's also convenient for variants to occupy the same index when using matinfo's `--print-glsl` flag, for example.

Make material compilation deterministic

---

filament/CMakeLists.txt
filament/include/filament/MaterialInstance.h
filament/src/MaterialInstance.cpp
filament/src/MaterialParser.cpp
filament/src/PostProcessManager.cpp
filament/src/ToneMapping.cpp
filament/src/ToneMapping.h
filament/src/UniformBuffer.cpp
filament/src/UniformBuffer.h
filament/src/details/MaterialInstance.h
filament/src/fg2/DependencyGraph.cpp
filament/src/fg2/details/DependencyGraph.h
libs/filaflat/include/filaflat/ChunkContainer.h
libs/filaflat/include/filaflat/MaterialChunk.h
libs/filaflat/src/ChunkContainer.cpp
libs/filaflat/src/MaterialChunk.cpp
libs/utils/include/utils/Allocator.h

MaterialInstance: generate versions of setParameter() methods that
are templated on the parameter sizeof(), which allows us to
coalesce implementations, e.g. float4 and int4 are now
the same. We make the compiler generate non-inline version of all
these methods, the typed version just call through, taking
advantage of the tail-call optimization in clang.
MaterialParser: improve code to avoid calling multiple methods that
all did more or less the same thing and were inlined.
PostProcessManager: use a loop to initialize the materials
ToneMapping: de-dup ACES implementation
And other more minor optimizations.

More code size optimizations

---

.github/workflows/presubmit.yml

👋 hello there! I'm a fellow Googler who works on projects that leverage GitHub Actions for CI/CD. Recently I noticed a large increase in our queue time, and I've tracked it down to the [limit of 180 concurrent jobs](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration) for an organization. To help be better citizens, I'm proposing changes across a few repositories that will reduce GitHub Actions hours and consumption. I hope these changes are reasonable and I'm happy to talk through them in more detail.
- Only run GitHub Actions for pushes and PRs against the main branch of the repository. If your team uses a forking model, this change will not affect you. If your team pushes branches to the repository directly, this changes actions to only run against the …

Improve Actions hygiene

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/RemoteServer.java
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
libs/viewer/include/viewer/RemoteServer.h
libs/viewer/src/RemoteServer.cpp

This fixes two different logcat messages that would occur when scrubbing
a slider in the UI:
- "Discarding message, message queue overflow."
- "Downloading model..." would repeat itself needlessly

RemoteServer code cleanup and logcat cleanup.

---

RELEASE_NOTES.md
filament/src/materials/ssao/sao.mat
filament/src/materials/ssao/ssaoUtils.fs
filament/src/materials/ssao/ssct.fs

SAO calculations rely on two coordinate spaces:
- UV-space: framebuffer/texture space, graphics API dependent.
- screen-space: origin bottom left, normalized coordinates.
We didn't see any issues with OpenGL, as its UV-space matches screen-space (Y up). However, Metal and Vulkan's UV-space is vertically flipped (Y down).
This is my attempt to resolve the discrepancy by adding in conversions between the spaces when necessary. @pixelflinger I'm curious if you have other ideas or prefer different terminology.
Fixes #3619

Fix dominant light shadows in Metal and Vulkan

---

filament/src/Froxelizer.cpp
libs/utils/include/utils/JobSystem.h

- one version of run() ignored the flags parameter
- don't immediately signal created jobs in froxelizer
to avoid redundant calls to signal()

minor jobsystem fixes

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h

This wasn't very useful in the first place because we're recycling
handles very quickly. Additionally there was a race condition
which cause false positives.
This reverts commit bc6acd5c5a1d7ee4b703fe9facfd8bf695b617d0.
This reverts commit 3a15756c78605395c4bdd2fa29d25587cc37e9f7.

Revert GL backend handle tracking

---

libs/utils/CMakeLists.txt
libs/utils/include/utils/CallStack.h
libs/utils/src/CallStack.cpp

This requires dladdr() and __cxa_demangle().

demangle callstacks in debug builds (unixes only)

---

samples/rendertarget.cpp

we can't use a projection with infinite far as a custom
projection matrix, because this is not suited for culling.
recently a new version of setCustomProjection was added which allows
to specify both the rendering and culling projections.

fix rendertarget sample app

---

libs/utils/include/utils/JobSystem.h
libs/utils/src/JobSystem.cpp

The hang was caused by a subtle race. When a job is completed, its 
thread must signal all the threads that might be waiting on this job.
The signaling code was attempting to signal only the minimum number
of threads -- this was important especially in the case where no threads
were waiting, then the call to notify() could be avoided.
Unfortunately, for performance reasons we're not calling notify() with
the condition lock held, this meant that between the time the number of 
waiting threads was latched and the time of the notify() call, more
threads could enter their condition variable wait(), and it would
then be possible for these threads to wake up, instead of the thread
we were trying to wake up (the one waiting on the job).
It would then get stuck forever.
This bug was introduced in …

Fix a hang in JobSystem

---

filament/src/RenderTarget.cpp

Inside `RenderTarget`, we're only ever constructing `TargetBufferInfo` with a `TextureCubemapFace`. This is problematic, because `TargetBufferInfo` uses a `union` to keep track of the face or layer:
```
union {
// face if texture is a cubemap
TextureCubemapFace face;
// for 3D textures
uint16_t layer = 0;
};
```
`TextureCubemapFace` occupies only 8 bits, so even if we pass in `POSITIVE_X` (value of 0), the full 16 bits of the union aren't set, and when reading back `layer` we read garbage.

Fix RenderTarget slice bug

---

android/gltfio-android/CMakeLists.txt
libs/gltfio/CMakeLists.txt
libs/gltfio/src/Animator.cpp
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp
libs/gltfio/src/MorphHelper.cpp
libs/gltfio/src/MorphHelper.h

This allows us to handle many more models, such as those exported by Modo, and the horse model in #1852.
We do this by picking the highest 4 weights. The indices for these weights are called the "primary indices", and we construct a new VertexBuffer for each unique set of primary indices.
In the near future this will be made more efficient by adding a new VertexBuffer API to the Filament core.
Fixes #1487.

gltfio: Add internal MorphHelper, enable up to 255 targets.

---

filament/src/materials/dof/dof.mat
filament/src/materials/dof/dofDilate.mat
filament/src/materials/dof/dofDownsample.mat
filament/src/materials/dof/dofTiles.mat
filament/src/materials/dof/dofUtils.fs

We're implementing the two-layer technique described in
Jimenez DoF paper, where the foreground field is split in two layers, front
and back. In addition we compute accurately the foreground field alpha.
From a performance standpoint, most of the extra work is increased
register pressure and a bit of ALU.

Dof: cleanup and improve significantly foreground layer

---

libs/utils/src/CString.cpp

(string_views lack a null terminator)

CString can construct from a string_view

---

filament/CMakeLists.txt
filament/src/PostProcessManager.cpp
filament/src/materials/dof/dof.mat
filament/src/materials/dof/dofCoc.mat
filament/src/materials/dof/dofDilate.mat
filament/src/materials/dof/dofUtils.fs

This is mostly used for debugging and having somewhat of a reference.
Change to the shader are minimal because all CoC values were always
treated as full-resolution. We just need to replace the downsampling
shader by one that just calculates the CoC. And we need to introduce
a CoC scale factor to compute the LOD to use (this was hardcoded
before).
On the C++ side, it's mostly a matter of replacing hardcoded buffer size
scales by a runtime or compile time variable.

DoF: support full-resolution DoF

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
libs/viewer/src/Settings.cpp
samples/gltf_viewer.cpp
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp
web/filament-js/jsenums.cpp

Currently the only NONE and MEDIAN are available options, at some 
point we may add a "MAX" option which is cheaper.
There is no real practical uses for this option with these only two
choices, other than for debugging.

DoF: add a "filter" parameter to the DoF settings

---

android/filament-android/src/main/cpp/Texture.cpp
android/filament-android/src/main/java/com/google/android/filament/Texture.java

- setImage() used the width of the texture for calculating the required
user buffer size, but this was too large when only updating a
portion of the texture. It would result in a BufferOverFlowException.
- setImage3D() had the opposite problem where it didn't take into
account the depth of the texture.
- the offset in the user buffer was called "bottom" on the C++ JNI side,
but it is called "top" on the java and filament side.
Fixes #3685

fix JNI setImage and friends buffer size calculation

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h
filament/backend/test/TrianglePrimitive.cpp
filament/src/Engine.cpp
filament/src/RenderPrimitive.cpp

As far as I can tell, there is no need for the `enabledAttributes`
argument in `setRenderPrimitiveBuffer`. This helps pave the way for
the upcoming BufferObject API.

Minor Driver API simplification.

---

filament/backend/src/opengl/OpenGLDriver.cpp

This was put in as a workaround for #2856. I made a fix to emscripten
itself (yay open source) in July. So, this workaround is no longer
necessary.
Verified with the rigged figure model.
https://github.com/emscripten-core/emscripten/pull/11742

Remove old emscripten workaround from GL backend.

---

filament/src/materials/dof/dof.mat

We now use the same calculation than for the foreground, this seems
to produce slightly smoother transitions

DoF: slightly better opacity for the background

---

filament/src/materials/dof/dof.mat

This adjustment is conservative, i.e. we limit the number of rings in
the kernel based on the kernel size in a way that it won't impact the
result. For instance, if the kernel size is 2 or lower, we don't need 4
rings.
This improves performance significantly, especially with large maximum
right counts.

DoF: dynamically and conservatively adjust the kernel density per tile

---

android/filament-android/src/main/cpp/Camera.cpp
android/filament-android/src/main/java/com/google/android/filament/Camera.java
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/Camera.h
filament/include/filament/View.h
filament/src/Camera.cpp
filament/src/PostProcessManager.cpp
filament/src/View.cpp
filament/src/details/Camera.h
libs/viewer/include/viewer/Settings.h
libs/viewer/src/Settings.cpp
samples/gltf_viewer.cpp
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

The DofOption parameter is now deprecated, but will still work if the
focus distance is not set on Camera.

move the focus distance from DofOptions to Camera

---

filament/src/materials/dof/dof.mat
filament/src/materials/dof/dofUtils.fs

The gist of it is that we can't always accumulate samples naively, and
we have to use different strategies with different tile types.
For the fast tiles it seems enough to reorder the sum, accumulating each
ring first, and then accumulating that into the output, because all
samples have the same weight.
For the foreground tiles, for some reason I couldn't find any major
issue and I'm not sure why.
For the background tiles, we need to use highp intermediates because
every sample has different magnitudes (weights)

DoF: fix several mediump-related bugs

---

filament/src/RenderTarget.cpp

This fixes a recent regression that would occur when a RenderTarget
does not have a depth attachment.

RenderTarget: fix NPE when depth is not present.

---

filament/src/materials/dof/dof.mat

This small bug was introduced recently with the dynamic kernel size
changes, the noise radius depends on the number of rings in the kernel.

DoF: fix noise radius calculation

---

filament/backend/src/metal/MetalHandles.mm

This fixes a crash in material_sandbox introduced in #3695.
Fixes #3706. I'll also cherry-pick this into rc/1.9.19.

Fix, regression inside MetalRenderPrimitive

---

filament/src/materials/dof/dof.mat

there has been a typo in the DoF code a while, but fixing it looks
much worse. we need to understand why. so for now we at least
document the typo in the code.

DoF: document a typo

---

filament/src/materials/dof/dof.mat

We use the technique used by Jimenez for the foreground applied to the
background, where we "guess" the missing background information from
neighboring pixels. In several papers it's not deemed useful for the
background, however, it does improve the blur quality a lot very shallow
DoF, i.e. when a moderately blurred background sits over a strongly 
blured one.
before:
after:

DoF: implement "background hole filling"

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

Metal textures can't have the `.swizzle` property set if they're used as render targets. So instead, we create a swizzled "texture view" which is used when binding the texture for sampling.

Fix Metal texture swizzling

---

docs/remote/update.sh

This script makes it easy to update the web page at
https://google.github.io/filament/remote/ even if you do not have the
emscripten SDK. It works by downloading the latest continuous web
build, then placing the wasm file in the right place.
After running the script, the user must make a git commit to finish the
operation.

Add script that updates remote UI.

---

web/filament-js/extensions.js
web/filament-js/jsbindings.cpp

We now annotate the JS wrapper for Engine with a GL context handle.
This is fairly hacky because emscripten hides its internal GL object
from JavaScript, and it does not provide a mechanism to pass JS objects
into inline assembly.

WebGL: support for multiple <canvas> elements.

---

filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLProgram.cpp

We now alwyas scrap this extension usage if the driver doesn't support
it, regardless of being in debug or release mode.

Better handle GL_GOOGLE_cpp_style_line_directive

---

libs/filamat/src/shaders/CodeGenerator.cpp

It looks like the layout(location) is needed for output parameters of
the fragment shader in GLES. Adreno dirver didn't seem to care, but
Mali drivers do. 
This fixes shaders that use multiple out buffers in debug mode.

fix output location in fragment shaders

---

filament/backend/src/opengl/OpenGLDriver.cpp

according to the gl spec, we can't mix the EXT versions of
glRenderbufferStorageMultisample/glFramebufferMultisample with
the regular versions. Other drivers are more permissive.
When allocating a renderbuffer and the extention is supported, we always
use it.

fix MSAA w/ multisampled_render_to_texture on Mali

---

libs/gltfio/src/ResourceLoader.cpp

This fixes the issue seen with RecursiveSkeletons.gltf, which is a model
that might soon be added to the Khronos sample models repo.
Fixes #3765.

gltfio: honor stride in normalizeSkinningWeights.

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/DriverBase.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/metal/MetalState.h
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h
filament/backend/test/TrianglePrimitive.cpp
filament/backend/test/TrianglePrimitive.h
filament/src/VertexBuffer.cpp
filament/src/details/VertexBuffer.h

This includes changes to OpenGL, Metal, and Vulkan backends.
At the backend level, vertex buffers are now always composed of buffer
objects. This lets us simplify the Driver API and some bookkeeping in
the backends.
This change also splits MAX_VERTEX_ATTRIBUTE_COUNT into two constants
because the maximum number of bound buffers is a separate concept from
the maximum number of attribute semantics (e.g. consider interleaving).
For now these two constants are set to the same value.
We also now store a byte count in HwBufferObject, which allows us to
remove the byte count from the Metal-specific handle, and to add some
asserts to debug builds to prevent size overflow.

VertexBuffer cleanup and simplification.

---

filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.mm

Not all GPUs support texture swizzling on Metal. Fixes #3754

Fix texture swizzling crash with older Nvidia GPUs

---

filament/backend/include/private/backend/CommandStream.h
filament/backend/include/private/backend/Driver.h
filament/backend/src/Driver.cpp
filament/backend/src/DriverBase.h
filament/backend/src/metal/MetalDriver.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanDriver.h

- it was called on the main thread side, which didn't allow to,
for instance, systrace commands on the backend thread side.
- moved to a begin/end callback model
- implemented basic logging/systracing for all backends in Driver.cpp
(and removed this functionality for the metal driver).

rework the "debugCommand" feature of backend

---

libs/filamat/src/shaders/CodeGenerator.cpp

GLSL ES requires precision qualifiers on all sampler types. `sampler2DArray` and `sampler3D` have no default precision, so we get an error when compiling materials that include one of these as a parameter with no explicit precision qualifier:
```
ERROR: 0:166: 'sampler/image' : type requires declaration of default precision qualifier
```
This isn't needed for other sampler types. From the [OpenGL ES Shading Language spec](https://www.khronos.org/files/opengles_shading_language.pdf):
> The vertex language has the following predeclared globally scoped default precision statements:
>     precision highp float;
>     precision highp int;
>     precision lowp sampler2D;
>     precision lowp samplerCube;
> 
> The fragment language has the following predeclared globally scoped default precision …

Add default precision qualifiers for special sampler types

---

filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/OpenGLProgram.cpp
filament/backend/src/opengl/OpenGLProgram.h

Some drivers claim to support anisotropic filtering but don't allow
setting it via glSamplerParameter. Until now we were disabling 
anisotropic filtering entirely on these drivers at compile time.
With this change, we should detect at runtime which drivers have this
issue and use a workaround -- instead of disabling anisotropic 
filtering entirely.

better handle anisotropic filtering with various drivers

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt

contact-shadows needs to be enabled per object.

enable contact-shadows functionality in mobile gltf-viewer

---

filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLProgram.cpp

It's an error to ask for a higher MSAA sample count than supported by
the gl driver, and results in corrupted rendering.
We now always clamp the requested sample count to the maximum allowed 
but the gl driver.
includes some minor refactoring.

silently clamp MSAA sample count to maximum allowed

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt

- If a resource file is missing, show toast instead of crashing.
- Allow glb files in zip files.
- Run blocking calls like createTempFile() on IO thread.

sample-gltf-viewer: more improvements for zip files.

---

filament/backend/src/vulkan/VulkanHandles.cpp

After eyeballing this barrier that we issue after updating a UBO, I realized it was configured incorrectly and overly aggressive.
It merely needs to ensure that the UBO is fully updated before it gets consumed by the vertex shader associated with the next draw call.

VulkanDriver: clean up pipeline barrier for UBOs.

---

filament/test/filament_framegraph_test.cpp

I don't think the `template` keyword is needed here, and it breaks MSVC.
Fixes #3791

Fix Windows build error in filament_framegraph_test.cpp

---

filament/backend/src/vulkan/VulkanHandles.cpp

Even though the vertex shader comes before the fragment shader,
both bits needs to be present in the barrier, since a Vulkan
implementation might partition its uniform cache between stages.
Thanks to Chris Forbes for pointing this out.

Vulkan: another fix to the UBO barrier.

---

filament/backend/src/metal/MetalDriver.mm

This fixes the crash seen when using the new `renderStandaloneView` API

Metal: Check that drawSwapChain exists inside endFrame

---

filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp

On Adreno devices, a driver bug prevents bliting from a renderbuffer into certain layers of a texture array, which is precicely what we do for VSM MSAA. For now, we'll just disable support for MSAA and simply fallback to normal, non-MSAA rendering.
It'd be nice to not have to disable this for all Adreno devices, but for now I can only assume the bug is present on all of them. 😕 
I also attempted to clarify the logic inside `OpenGLDriver::framebufferTexture`.

Disable VSM MSAA on Adreno devices

---

libs/filamat/src/shaders/CodeGenerator.cpp

#3786 added default sampler precision specifiers, but these specifiers are only valid in ES.
Fixes #3823

Specify sampler precision only on GLES

---

filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanUtility.cpp
filament/backend/src/vulkan/VulkanUtility.h

The SCALED formats are useful when the shader consumes a float, but
you want to give it an integer.

Vulkan: fix VK_FORMAT to correctly handle non-integer types.

---

android/filament-android/CMakeLists.txt
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/GltfEnums.h
libs/gltfio/src/ResourceLoader.cpp

This fixes issues seen seen with Vulkan in conjunction with quantized model variants in the glTF samples repo such as the Avocado.
We already support the quantized glTF extension, which is when this
comes up. Technically this is only needed for Vulkan but gltfio does
not (and should not) know which backend is being used, so we simply
apply these transformations assuming the worst.
In practice this code usually won't be activated, and if even when it
is, it won't hurt loading time as much as other things like large
textures.

gltfio: Use the new Transcoder API in some cases.

---

libs/viewer/src/SimpleViewer.cpp

The parameters would turn out as NaN.
We might need a better API for this, but it's
never okay to set NaN values.

don't set sun parameters if we didn't have SH

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/backend/TargetBufferInfo.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalBlitter.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/metal/MetalState.h
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.h
filament/include/filament/RenderTarget.h
filament/src/RenderTarget.cpp
filament/src/details/RenderTarget.h
filament/src/fg2/PassNode.cpp
libs/filamat/include/filamat/MaterialBuilder.h
shaders/src/post_process.fs
shaders/src/post_process_inputs.fs

We chose 8 renderbuffer because it seems to be commonly supported
on mobile gpu and is more than 6 which is needed for generating
cubemaps. 4 was the minimum guaranteed by ES3.0.
The main changes here are:
- TargetBufferFlags is now a uint32_t instead of uint8_t
- The number of render buffer supported by filament and supported by
the hardware can now be different. Applications/users now must
query this value if more than 4 is needed.
- added a backend query (used gl terminology)

Support a maximum of 8 render buffers (from 4)

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/backend/TargetBufferInfo.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalBlitter.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/metal/MetalState.h
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.h
filament/include/filament/RenderTarget.h
filament/src/RenderTarget.cpp
filament/src/details/RenderTarget.h
filament/src/fg2/PassNode.cpp
libs/filamat/include/filamat/MaterialBuilder.h
shaders/src/post_process.fs
shaders/src/post_process_inputs.fs

This reverts commit 6f948c101f9eb817cc84761d6af30550c8c63d5a.
This is breaking rendering on Android when certain postprocessing
effects are disabled (e.g. bloom/msaa/dof).

Revert "Support a maximum of 8 render buffers (from 4)"

---

build/android/build.sh

This makes release builds consistent with continuous builds and default
local builds. It also makes it easier to test the Vulkan backend.
Clients who need a smaller APK size can always make their own build.
This also makes filament-android-release.aar go from 1.8M to 2.3M.
Note that we are now including bluevk, vkshaders (for the blit shader),
smol-v (for SPIRV decompression) and vk_mem_alloc (for mem allocation).

Enable Vulkan in our Android Release package.

---

build/ios/build-samples.sh
filament/backend/src/opengl/PlatformCocoaTouchGL.mm
ios/samples/README.md
ios/samples/gltf-viewer/.gitignore
ios/samples/gltf-viewer/build-resources.sh
ios/samples/gltf-viewer/gltf-viewer.xcodeproj/project.pbxproj
ios/samples/gltf-viewer/gltf-viewer.xcodeproj/project.xcworkspace/contents.xcworkspacedata
ios/samples/gltf-viewer/gltf-viewer.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
ios/samples/gltf-viewer/gltf-viewer.xcodeproj/xcshareddata/xcschemes/gltf-viewer Metal.xcscheme
ios/samples/gltf-viewer/gltf-viewer.xcodeproj/xcshareddata/xcschemes/gltf-viewer OpenGL.xcscheme
ios/samples/gltf-viewer/gltf-viewer/AppDelegate.h
ios/samples/gltf-viewer/gltf-viewer/AppDelegate.m
ios/samples/gltf-viewer/gltf-viewer/FILModelView.h
ios/samples/gltf-viewer/gltf-viewer/FILModelView.mm
ios/samples/gltf-viewer/gltf-viewer/FILViewController.h
ios/samples/gltf-viewer/gltf-viewer/FILViewController.mm
ios/samples/gltf-viewer/gltf-viewer/SupportFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
ios/samples/gltf-viewer/gltf-viewer/SupportFiles/Assets.xcassets/Contents.json
ios/samples/gltf-viewer/gltf-viewer/SupportFiles/Base.lproj/LaunchScreen.storyboard
ios/samples/gltf-viewer/gltf-viewer/SupportFiles/Base.lproj/Main.storyboard
ios/samples/gltf-viewer/gltf-viewer/SupportFiles/Info.plist
ios/samples/gltf-viewer/gltf-viewer/SupportFiles/main.m
ios/samples/gltf-viewer/project.yml
libs/gltfio/src/ResourceLoader.cpp

This sample is akin to Android's `sample-gltf-viewer`. It allows loading glTF files and updating settings through the Filament Remote site. The idea is for this to replace the `hello-gltf` sample, which has grown stale. It doesn't have complete feature parity yet; namely loading zipped glTF files is not yet supported.
One hitch is that the Filament remote site will need to be updated to support specifying an IP address, as iOS does not have the equivalent of `adb forward`. I'll add this in a separate PR.

Add gltf-viewer iOS sample

---

libs/utils/include/utils/NameComponentManager.h

Calls to `strdup` must be balanced with calls to `free`.

Fix memory leak inside utils::details::SafeString

---

filament/backend/CMakeLists.txt
filament/backend/src/vulkan/VulkanBlitter.cpp
filament/backend/src/vulkan/VulkanBuffer.cpp
filament/backend/src/vulkan/VulkanCommands.cpp
filament/backend/src/vulkan/VulkanCommands.h
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDisposer.cpp
filament/backend/src/vulkan/VulkanDisposer.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanDriver.h
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h
filament/backend/src/vulkan/VulkanStagePool.cpp

This removes a lot of caveats that we had in the Vulkan backend. Many driver API calls were unsupported due to a potential "missing" command buffer, but in the new scheme, a command buffer is always made available, and there's no weird separate "work and swap chain command buffers".
Here's how various driver API entry points now map into Vulkan actions:
```
makeCurrent => Acquire Swap Chain.
beginFrame => Do nothing.
endFrame => Submit command buffer and create a new one.
commit => Submit commit buffer again if necessary, Present Swap Chain.
```
This handles both `copyFrame` (which does not do beginFrame / endFrame) and `renderStandaloneView` (which does not do makeCurrent / commit).

Vulkan: big refactor for command buffer management.

---

filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

When rendering into a single cubemap face, we should use
VK_IMAGE_VIEW_TYPE_2D rather than VK_IMAGE_VIEW_TYPE_CUBE.

Vulkan: fix image view type for render target attachments.

---

filament/backend/include/backend/TargetBufferInfo.h
filament/src/Texture.cpp

We now handle SAMPLER_2D_ARRAY, but SAMPLER_3D is still unsupported.

improve Texture::generateMipmap fallback

---

libs/iblprefilter/include/filament-iblprefilter/IBLPrefilterContext.h
libs/iblprefilter/src/IBLPrefilterContext.cpp
libs/iblprefilter/src/materials/iblprefilter.mat

- move kernel weight computation to the gpu side as a small cost, in
order to simplify the CPU side and reduce the binary size.
- skip samples with a weight of 0, which is a completely coherent 
check.
- fix a typo in move ctor

ipbprefilter: simplify cpu side

---

web/samples/remote.html

With the latest Chrome update, `websocket.send(file)` no longer works. Chrome sends a binary message of length 0 bytes. `.send` accepts a `Blob` object, which `File` supposedly inherits from, but I bet we have to actually _read_ the entire file stream before sending it.

Fix Filament remote file upload

---

ios/samples/gltf-viewer/gltf-viewer/FILModelView.mm

This causes a crash because `materialProvider` deletes an internal `dummyTexture`, which is never re-created.

ios: Don't destroy gltfio materials between asset loads

---

filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/materials/bloom/bloomDownsample.mat

- remove areFeedbackLoopsSupported from backend API, since this is only
a problem on WebGL
- binary only include either the regular or webgl version of the bloom
code, never both, which should save some binary size
- bloom pass is now called outside of the colorGrading pass, which is
cleaner and makes it available for other pass, should they need it
(not the case right now).
- always pass ColorGradingConfig to all color grading related methods,
instead of individual parameters
- very minor optimization in bloom shader

cleanup bloom

---

filament/backend/src/opengl/OpenGLDriver.cpp

This leak was introduced in the following PR on April 7 and was therefore released to the wild in v1.9.20.
https://github.com/google/filament/pull/3775
We were creating and allocating low-level VBO handles, but then they got clobbered later when the new BufferObject VBO handles were pushed to the VertexBuffer.
Fixes #3888

Fix bad memory leak in the GL backend.

---

filament/backend/src/opengl/OpenGLDriver.cpp

The handle still needs to be destroyed.
Fixes #3888.

Second memory leak fix in GL backend.

---

filament/src/ShadowMapManager.cpp

iOS (and possibly Android) doesn't support filtering from RG32F textures. There is no discernible quality difference between 32 and 16 bit, so I'll just make this the default for now.

Use 16 bit format for VSM

---

filament/backend/test/test_Blit.cpp

This test is similar to manual mipmap generation for cubemaps and
can uncover issues that are provked by libiblprefilter. It simply
dumps out a PNG that can be manually inspected.
Also, this test does not do makeCurrent / commit and is therefore
similar to renderStandaloneView.

BackendTest: add blit cubemap test.

---

filament/src/materials/dof/dof.mat

It did improve the look of the blur on far way geometry in some case,
but overall it hurts a lot more.
The case that falls appart is when everything is in the background layer
but there is a large depth difference anyways.
This creates a halo around edges.
Fixes #3221
Here an extreme example:
before:
after:

DoF: don't use hole filling for the background

---

filament/backend/src/opengl/OpenGLDriver.cpp

We should take care not to call `glVertexAttribPointer` when there is no bound ARRAY_BUFFER (i.e. when its binding is zero).
This fixes the black screen seen with some WebGL samples after the recent memory leak fix related to the new BufferObject API.

OpenGL: fix INVALID_OPERATION and WebGL breakage

---

filament/backend/src/vulkan/VulkanCommands.cpp
filament/backend/src/vulkan/VulkanConstants.h
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanPipelineCache.cpp
filament/backend/src/vulkan/VulkanPipelineCache.h

This fixes the "descriptor set fragmentation" error that we would see on
Mali.
The pipeline cache now maintains an arena of descriptors that can be
re-used. We call this an "arena" to avoid confusion with
VkDescriptorPool.
Descriptors are returned to the arena only when they are not in use
by any pending command buffer. This allows them to be mutated safely
without worrying about synchronization.

VulkanPipelineCache: add a descriptor set arena.

---

web/samples/remote.html

This adds a URL input to the Remote Viewer that lets users specify a device IP to connect to. This is useful when connecting to iOS devices, which don't have the equivalent of "adb forward".
I refactored the WebSocket logic into a `Connection` class to make the logic a bit simplier.

Add URL input to Filament Remote Viewer

---

RELEASE_NOTES.md
filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/CommandStream.h
filament/backend/include/private/backend/Program.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalState.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/OpenGLProgram.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanPipelineCache.h
filament/src/Froxelizer.cpp
filament/src/Material.cpp
filament/src/PostProcessManager.cpp
filament/src/View.cpp
filament/src/details/Froxelizer.h
filament/src/details/View.h
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/EngineEnums.h
libs/filabridge/include/private/filament/SibGenerator.h
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/src/SibGenerator.cpp
libs/filabridge/src/UibGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/light_punctual.fs

MATERIAL BREAKAGE: this change breaks materials
In order to use one less sampler, we now use a UBO instead of a texture
to store the "froxel records". Currently this UBO is limited to 16KiB
vs. 64KiB before with the texture.
We also handle running out of record space better, by using a predefined
record that has all the lights in the scene. This way the scene will be
rendered properly, albeit at a potentially large performance cost.

Use a UBO instead of a texture for froxels data structure

---

libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/MorphHelper.cpp
libs/gltfio/src/MorphHelper.h

The code that determined the "base slot" (i.e. the buffer object index
for the first morphed attribute) was very fragile and buggy.
MorphHelper now simply looks up the slot index in a stored mapping,
rather than trying to mimic the AssetLoader to determine the base slot.
Until now, most of the models we tested against only morphed the
position attribute, and never had a large set of target weights that
could be non-zero in a given time slice.
Fixes #3961

gltfio: fix morphing bugs uncovered by MorphStressTest.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/Stream.cpp
android/filament-android/src/main/cpp/Texture.cpp
android/filament-android/src/main/java/com/google/android/filament/Stream.java
android/filament-android/src/main/java/com/google/android/filament/Texture.java
filament/include/filament/Stream.h
filament/include/filament/Texture.h

deprecate Stream::stream(intptr_t).
This method was needed for ARCore back in the days, but there is now a
zero-copy way to achieve the same thing. This API shouldn't be used anymore.

add java API for Texture::Builder::import()

---

filament/src/materials/flare/flare.mat
tools/matc/src/matc/MaterialLexer.cpp
tools/matc/src/matc/MaterialLexer.h

matc was failing to report certain kinds of syntax errors and would
read out-of-bounds memory.
This change casuses the flare material to fail.

matc: detect missing end brace.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h

This prevents potentially bogus validation messages from arising.

Vulkan: enable the maintenance extensions if available.

---

filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp

Vulkan does not permit the GENERAL layout when the depth buffer that is
currently being used for depth testing is also sampled from.
This (finally) fixes the last validation error that we were silencing,
which would occur only when SSAO was enabled.

Vulkan: change depth layout to permit feedback loops.

---

android/filament-android/libfilament-jni.map
android/filament-android/src/main/java/com/google/android/filament/IndirectLight.java
android/filament-android/src/main/java/com/google/android/filament/Skybox.java
android/filament-android/src/main/java/com/google/android/filament/Texture.java
android/filament-utils-android/src/main/java/com/google/android/filament/utils/KtxLoader.kt

(1)
The C++ RenderTarget API might be used by an external Android library
such as filament-utils-android and therefore needs to be in the map
file.
(2)
Texture, Skybox, and IndirectLight each had two "nativeObject"
constructors which exist for the benefit of filament-utils-android,
but each of these classes only need one nativeObject constructor.

JNI Cleanup: Remove useless constructors, publicize RenderTarget.

---

libs/filagui/include/filagui/ImGuiHelper.h
libs/filagui/src/ImGuiHelper.cpp

The texture binding in the material instance needs to be restored to the
glyph atlas when a custom image is not in use.

ImGuiHelper: fix support for custom images.

---

android/filament-utils-android/CMakeLists.txt
android/filament-utils-android/src/main/cpp/HDRLoader.cpp
android/filament-utils-android/src/main/cpp/Utils.cpp
android/filament-utils-android/src/main/java/com/google/android/filament/utils/HDRLoader.kt
android/filament-utils-android/src/main/java/com/google/android/filament/utils/KTXLoader.kt
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
android/samples/sample-textured-object/build.gradle
libs/imageio/CMakeLists.txt
libs/imageio/include/imageio/HDRDecoder.h
libs/imageio/src/HDRDecoder.cpp
libs/imageio/src/ImageDecoder.cpp
web/samples/remote.html

This adds support for decoding HDR files, dropping them into the remote
web page, and sending them over the wire.  However the decoded results
are not yet passed into IBLPrefilterContext, that will be subsequent
PR.
Rename KtxLoader to KTXLoader.
The remote UI has been tweaked a bit, so that it shows a more helpful
message when disconnected:

Add HDRLoader for JVM clients.

---

RELEASE_NOTES.md
android/samples/sample-multi-view/src/main/java/com/google/android/filament/multiview/MainActivity.kt
filament/include/filament/RenderTarget.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h
filament/src/fg2/FrameGraphRenderPass.h
filament/src/fg2/PassNode.cpp

Until now, all attachments of RenderTarget beyond COLOR0 were discarded
after rendering.
With this change, attachment whose texture has the SAMPLEABLE usage
bit set will be kept.
Fixes #3962

a way to keep the content of custom RenderTarget attachments

---

libs/viewer/src/AutomationSpec.cpp
libs/viewer/tests/test_settings.cpp

~This fixes the test, though I'm not sure why it's required. I also don't understand why the original test had 65 test cases, instead of only 64 (2^8). It seems only settings with a "permute" key would affect the number of automation combinations.~
Oh, maybe I do understand. Each top-level entry in the automation spec generates a _independent_ set of test cases.

Fix Automation test_settings

---

filament/src/Renderer.cpp

This was introduced recently.
Fix #3962

Fix a crash when using custom rendertargets

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/RemoteServer.java
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt

The sample would crash when removing `orientation` from `configChanges`
and rotating the device, because the old RemoteServer would still be
alive when creating the second one, so the WebSocket port would be
unavailable.

sample-gltf-viewer: fix lifetime cycle for RemoteServer.

---

filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanSwapChain.cpp
filament/backend/src/vulkan/VulkanSwapChain.h
filament/backend/src/vulkan/VulkanUtility.cpp
filament/backend/src/vulkan/VulkanUtility.h

Newer versions of MoltenVK seem to behave similarly to Android,
so there's no need to separate codepaths. I tested this by not only
resizing the window, but also dragging between displays with different
pixel ratios, and rotating on Android with & without `orientation` in
`configChanges`. I also tried our headless unit tests.

VulkanSwapChain: simplify and repair swap chain resizing.

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
libs/utils/include/utils/Allocator.h

- we issue better logs when the allocation fails
- the pool selection is now performed at compile time

improve handle creation in opengl backend

---

filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp

this helps save a lot of space in the CommandStream, it especially
matters with scenes with a lot of draw calls.

replace all size_t with uint32_t in the backend API

---

filament/src/ResourceAllocator.cpp
filament/src/ShadowMapManager.cpp
filament/src/Texture.cpp
filament/src/details/ShadowMapManager.h
filament/src/fg2/DependencyGraph.cpp
filament/src/fg2/FrameGraph.h
filament/src/fg2/ResourceNode.cpp
filament/src/fg2/details/DependencyGraph.h
filament/src/fg2/details/ResourceNode.h
libs/ibl/include/ibl/CubemapIBL.h
libs/ibl/src/CubemapIBL.cpp
libs/utils/CMakeLists.txt
libs/utils/include/utils/Allocator.h
libs/utils/include/utils/FixedCapacityVector.h
libs/utils/include/utils/Slice.h
libs/utils/include/utils/compressed_pair.h
libs/utils/src/EntityManagerImpl.h

This is (almost) drop-in replacement for std::vector, the main 
difference is that FixedCapacityVector has a fixed (at runtime)
capacity, which makes it a lot more efficient and small for operations
like push_back();
The capacity can be set (and re-set) as usual with reserve(),
but exceeding the capacity when adding items will throw.
The capacity is also set when creating the vector with a size.
In addition a FixedCapacityVector<> instance is only 16 bytes instead
of 24 for std::vector<>.
The aim here is to reduce code bloat.

A fixed capacity vector.

---

RELEASE_NOTES.md
docs/Materials.html
docs/Materials.md.html
libs/gltfio/include/gltfio/MaterialProvider.h
libs/gltfio/materials/gltflite.mat.in
libs/gltfio/materials/sheen.mat.in
libs/gltfio/materials/transmission.mat.in
libs/gltfio/materials/ubershader.mat.in
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/MaterialGenerator.cpp
libs/gltfio/src/MaterialProvider.cpp
libs/gltfio/src/UbershaderLoader.cpp
shaders/src/material_inputs.fs
shaders/src/shading_lit.fs

This change makes available the existing IOR material parameter to materials that don't have refraction enabled.
Here is a glTF model with an IOR of 1:
And the same model with an IOR of 2:
Note that using this parameter on a non-refractive object is equivalent to setting the reflectance parameter.
IOR support is implemented either as IOR or reflectance in ubershaders to use a more optimized code path
for the common case (no IOR set).

Add support for KHR_materials_specular to glTF

---

filament/backend/src/CommandBufferQueue.cpp

the CommandStream is limited in size and can get corrupted if
that size (default 1 MiB) is exceeded. We used to catch this
only on Debug builds, but this is too serious and unrecoverable, so
it must be caught in Release builds too.
At the point of detection the stream is corrupted, which can cause
the backend to get in an unknown state. But worse, program execution
could end up anywhere because the stream contains function pointers.

panic in release builds when command stream is corrupted

---

filament/backend/src/vulkan/VulkanBuffer.cpp
filament/backend/src/vulkan/VulkanConstants.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp

This fixes most of the warnings that are emitted by the relatively new
SYNCHRONIZATION_VALIDATION feature that LunarG provides.
This commit does not fix a warning that is emitted when SSAO is enabled,
when we sample from the currently bound depth attachment. This one is
tricky to fix.

Vk: Fix some synchronization validation warnings.

---

filament/backend/src/opengl/OpenGLContext.cpp
libs/utils/include/utils/Log.h
libs/utils/include/utils/ThreadLocal.h
libs/utils/include/utils/compiler.h
libs/utils/include/utils/ostream.h
libs/utils/src/Log.cpp
libs/utils/src/ostream.cpp

This reverts commit cc6201b0db0ac487115464629a29b920b20f9b37.
On Android the loggers are not always initialized when several .so are
used, leading to crashes. It's not completely clear what is exactly 
happening.

Revert "improve logs and tls support"

---

build.sh

The android/ directory is now left as if it was freshly checked out, 
all non-git files (including those in .gitignore) are deleted.
This is to prevent a recurring problem where "clean" builds where not
actually clean in some cases.

build.sh -c option entirely cleans the android/ directory

---

third_party/spirv-tools/CMakeLists.txt
third_party/spirv-tools/filament-specific-changes.patch

This started happening with the Visual Studio 2019 16.10 update.

spirv-tools: turn off warnings as errors to fix Windows build

---

filament/backend/src/Platform.cpp

On Android, set `debug.filament.backend` to the desired backend:
- 0: default
- 1: gl/gles
- 2: vulkan
- 3: metal
- 4: noop
example:
`adb shell setprop debug.filament.backend 2`
This will affect all filament apps on the device.
This sets the backed as if it was set from the public API.

add system property to override the backend selection

---

filament/src/RenderPass.cpp
filament/src/components/RenderableManager.cpp
filament/src/details/Engine.h

The CommandStream hold backend commands, but it has a limited size.
With some large models, we can run out of space especially during
initialization.
We can combat this by flushing the command stream regularly. With this
change, we do this every 128 renderable creation.
We also flush the CommandStream just before generating the draw
commands for the frame.
If the buffer is not sized correctly (currently at compile time), this
could cause stalls, which will be logged in DEBUG builds.

Flush the CommandStream in a few strategic places

---

libs/gltfio/src/ResourceLoader.cpp

Fixes the "triangle count is zero" assertion with the big car model.
We do have nominal support for points and lines, but we should not
attempt to compute tangents for these.
As a reminder, glTF also supports loops, strips, and fans; this is the
only way in which Filament is non-conformant.
#3986

gltfio: fix crash with non-triangles.

---

filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanPipelineCache.cpp
filament/backend/src/vulkan/VulkanPipelineCache.h

This fixes an issue caught by a memory sanitizer, whereby padding in the
cache key structure was being consumed by a hashing function. In
practice this oversight was fairly harmless, but this change makes the
code more safe and predictable.

VulkanPipelineCache: do not hash uninitialized data.

---

filament/backend/src/CommandStream.cpp

"filament.perfcounters" is renamed to "debug.filament.perfcounters", 
because otherwise it can't be set by users on recent Android 
versions.

use "debug" namespace for system properties

---

shaders/src/light_punctual.fs

getLight() should initialize all fields.

---

libs/utils/include/utils/FixedCapacityVector.h

std::allocator::deallocate() expects the same value that was given
during allocate().
Interestingly, this bug did not manifest any issues (even with ASAN) on
some platforms.

Fix FixedCapacityVector destructor.

---

filament/backend/include/private/backend/BackendUtils.h
filament/backend/src/CommandBufferQueue.cpp
filament/src/details/Allocators.h

If your build system does not provide a definition for this macro, then
you cannot compile this cpp file.  Since Allocators.h provides a
backup value, it needs to be included.
Note that this makes it so that the backend includes a file from
src/details, but I did not see any better alternative.

Ensure FILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB is available.

---

filament/backend/src/vulkan/VulkanCommands.cpp
filament/backend/src/vulkan/VulkanConstants.h
filament/backend/src/vulkan/VulkanPipelineCache.cpp

This constant was previously set to 3 because of triple buffering, which
does not account for the fact that Filament may issue multiple commit()
calls during a single frame.
This new number was determined via experimentation.
On a Pixel 4, this reduces a 4.5 ms gap in "GPU Queue 0" to 420 us.

Adjust VK_MAX_COMMAND_BUFFERS to prevent a 5 ms stall.

---

filament/backend/src/vulkan/VulkanFboCache.cpp

This gets rid of the "GMEM Store Depth / Stencil" bars seen with AGI.

Vulkan: fix storeOp for depth attachment.

---

libs/utils/include/utils/FixedCapacityVector.h

We were initializing the new data with the default
Actor by accident.

Fix FixedCapacityVector::reserve()

---

filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp

Vulkan group markers do not show up in an AGI system trace, but we can sneak in the top string in the marker stack by using debug_utils to assign labels to VkFramebuffer, which shows up in the "Surface" slices.  See screenshot below.
Note that the debug_utils extension is enabled only when launching your app from AGI.
Many thanks to @pmuetschard for fixing this feature in AGI.

Vulkan: use EXT_debug_utils for custom labels.

---

filament/backend/src/vulkan/VulkanBuffer.cpp
filament/backend/src/vulkan/VulkanConstants.h
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanStagePool.cpp

This makes the car load in 3 seconds instead of 30 seconds on Mali.
On devices that have bufferImageGranularity set to 1 in the
VkPhysicalDeviceLimits caps structure, we observe that vmaCreateBuffer
can be two orders of magnitude faster than with devices that have a
higher value for their bufferImageGranularity.
According to the Vulkan spec, the bufferImageGranularity aligment
constraint needs to be honored only when linear and non-linear resources
live next to each other in memory.  Since all VkBuffer objects are
linear, we can allocate them all from the same pool and ignore the
alignment constraint.

Vulkan: Use custom VMA pools to speed up Mali.

---

filament/backend/src/vulkan/VulkanSwapChain.cpp

I broke this when migrating to FixedCapacityVector.

Vulkan: repair headless swap chains.

---

android/filament-utils-android/src/main/cpp/Utils.cpp

This is annoying, but we're technically doing something bad here. The `JNINativeMethod` struct looks like this:
```
typedef struct {
char *name;
char *signature;
void *fnPtr;
} JNINativeMethod;
```
To comply with Google3's stricter build rules, we have to provide a non-const `char*` (string literals are constant). Otherwise, I see the following error:
```
error: ISO C++11 does not allow conversion from string literal to 'char *' [-Werror,-Wwritable-strings]
```
Alternatively, if we assume that JNI won't try to mutate the string, we could just cast to a `char*`. I think that's a bit riskier though.

filament-utils-android: fix string literal conversions

---

filament/src/PostProcessManager.cpp
filament/src/Renderer.cpp
filament/src/fg2/FrameGraphRenderPass.h
filament/src/fg2/PassNode.cpp
libs/viewer/src/SimpleViewer.cpp

Imported render targets are a special case in the frame graph, in particular, the texture resource that refers to them is not a real texture with a HwTexture handle, it can be converted back to the render target, but it can never be used as an actual texture -- in particular it can't be used to create a HwRenderTarget.
There was other problem related to clearing render targets, individual fixes are explained in their respective CL.
This should fix #4085

Fix several FrameGraph issues related to imported render targets

---

android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
filament/src/details/View.h

This reworks how we compute the bloom buffer size. The main changes are:
- The BloomOptions.resolution is changed to height instead of minor axis.
This keeps a consistant look of the bloom regardless of the viewport.
- The anamorphism setting now dilates the bloom rather than to compress
it (in the other direction), which maintains the same amount of bloom.
However, the resolution decreases meaning that the user might need to
adjust resolution and/or levels.
- limit the resolution do 2048 which is gles minspec.

fix a possible crash when bloom is enabled

---

filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanSwapChain.cpp
filament/backend/test/BackendTest.cpp
filament/backend/test/BackendTest.h
filament/backend/test/test_FeedbackLoops.cpp

1) Add a missing destroyTexture to the test, which I believe fixed
the Metal assert that I was seeing, as well as some Vulkan validation
warnings.
2) Add a flushAndWait() utility to BackendTest, which is useful for
diagnostics.
3) Fix a layout validation issue in VulkanSwapChain for empty render
passes.

Fix issues in test_FeedbackLoops and VulkanDriver.

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
libs/utils/include/utils/Allocator.h

The array size in the GL structure didn't match the number of supported
render targets.

fix a potential memory corruption when using more than 4 render targets

---

RELEASE_NOTES.md
filament/backend/include/backend/DriverEnums.h
filament/backend/src/Platform.cpp
libs/filamentapp/include/filamentapp/Config.h
libs/filamentapp/src/FilamentApp.cpp

- OpenGL ES on Android
- Metal on MacOS/iOS
- Vulkan everywhere else (Linux/Windows)
The main change here is that OpenGL is no longer the default on
desktop.
Most of our samples have a `-a` option that can be use to specify the
desired backend.

Backend::DEFAULT now selects a backend most suited for the platform

---

libs/gltfio/src/UbershaderLoader.cpp

This avoids an assertion in debug builds. We will document this behavior
much more thoroughly in a subsequent PR.
Fixes #4143.

gltfio: do not set clear coat in GLTFIO_LITE config.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/VulkanTexture.h

When creating a texture with a swizzle, the swizzle should be applied to
the image view only when sampling from that texture.  When a swizzled
texture is used as a render target attachment, the image view should not
have any swizzle applied.

Vulkan: fix swizzle support.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/LightManager.java
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/backend/include/private/backend/SamplerGroup.h
filament/include/filament/LightManager.h
filament/include/filament/View.h
filament/src/Scene.cpp
filament/src/ShadowMap.cpp
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/details/Scene.h
filament/src/details/ShadowMap.h
filament/src/details/ShadowMapManager.h
filament/src/details/View.h
libs/filabridge/include/private/filament/UibGenerator.h
libs/filabridge/src/UibGenerator.cpp
libs/viewer/src/Settings.cpp
libs/viewer/src/SimpleViewer.cpp
shaders/src/common_shadowing.fs
shaders/src/depth_main.fs
shaders/src/getters.fs
shaders/src/light_directional.fs
shaders/src/light_punctual.fs
shaders/src/shading_unlit.fs
shaders/src/shadowing.fs

- use EVSM (exponential VSM), helps a lot with light bleeding
- don't apply shadow biases with VSM
- improve VSM user settings: added more controls, expose to java
- minor code cleanups:
- rename some structures
- remove unused parameters
- remove unused uniforms

VSM improvements and fixes

---

filament/CMakeLists.txt
filament/src/Material.cpp
filament/src/PostProcessManager.h
filament/src/RenderPass.cpp
filament/src/Scene.cpp
filament/src/ShadowMapManager.cpp
filament/src/TypedUniformBuffer.h
filament/src/UniformBuffer.h
filament/src/View.cpp
filament/src/components/RenderableManager.h
filament/src/details/Froxelizer.h
filament/src/details/ShadowMapManager.h
filament/src/details/View.h
filament/test/filament_test.cpp
libs/filabridge/CMakeLists.txt
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/CMakeLists.txt
libs/filamat/src/UibGenerator.cpp
libs/filamat/src/UibGenerator.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/utils/include/utils/CString.h

Filament uses a handful of known UBO, the code for creating their
interface block is not needed in filament (via filabridge), so
reorganize things so that we can move that code to filamat.
On the other hand, filament needs the C structure corresponding to
the UBO, to find the fields offset and ubo size and name.
We now have a UibStructs.h in filabridge which only defines C struct
with a static name for the interface block's.
This should slightly reduce the size of filament proper.
We also now have a new helper TypedUniformBuffer<> which simply holds
one of these structs (or an array), and allows to set the fields
directly and more naturally from C++. std140 alignment is now left to
the caller, when going through that class.

Rework a bit UniformBuffer and friends

---

android/gltfio-android/src/main/cpp/FilamentAsset.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

This allows clients to obtain the extras strings for the asset and
for individual nodes.  Note that extras for buffer views, accessors, etc
are not supported, although C++ clients can access the raw cgltf data
directly if they need to.

gltfio: introduce support for extras strings.

---

filament/src/PostProcessManager.cpp

DoF now works on Vulkan, and with zero validation warnings:
This is also required for OpenGL, for Intel drivers.

PostProcessManager: call setMinMaxLevels for DoF mipmaps.

---

libs/gltfio/include/gltfio/MaterialProvider.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/MaterialGenerator.cpp
libs/gltfio/src/UbershaderLoader.cpp
samples/gltf_instances.cpp
samples/gltf_viewer.cpp

We want anybody to write their own class that descends from
MaterialProvider, so it doesn't make sense to have an enum of
concrete types.

gltfio: remove hacky RTTI from MaterialProvider.

---

filament/src/PostProcessManager.cpp
filament/src/materials/dof/dofMipmap.mat

On some qualcomm drivers, textureSize() with a level != 0 aborts the
pixel shader.

workaround drivers that don't implement textureSize() properly

---

RELEASE_NOTES.md
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/common_shadowing.fs
shaders/src/getters.fs
shaders/src/getters.vs
shaders/src/inputs.fs
shaders/src/inputs.vs
shaders/src/main.vs

We have a limited number of interpolants, and 2 were used for spotlights,
but this is a fairly uncommon case, so we move the calculation to the
fragment shader. A side effect of this is that we are not limited to 
two spot-light anymore from the shader's point of view.
This essentially adds a vector transform per fragment, but on the other
hand, it removes communication between the vertex and fragment shader,
as well as interpolation of the position.

spotlight light-space position moved to the fragment shader

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp
filament/src/ShadowMap.cpp
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/details/Renderer.h
filament/src/details/ShadowMap.h
filament/src/details/ShadowMapManager.h
filament/src/details/View.h
filament/src/fg2/FrameGraphPass.h
libs/utils/include/utils/Allocator.h

This is split in 3 CLs, but the main changes are:
- rework RenderPass allocations
- simplify ShadowMap cpde
See each CL for details.

RenderPass and ShadowMap code cleanup

---

filament/src/ShadowMapManager.cpp

The operator!= in std::array compares SPLIT_COUNT elements, which
is potentially greater than cascadeCount, which was the number of
initialized elements in splitPercentages.

ShadowMapManager: fix MSAN use-of-uninitialized-value.

---

filament/backend/CMakeLists.txt
filament/backend/include/private/backend/HandleAllocator.h
filament/backend/src/HandleAllocator.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h

This means it can easily be used by our other backend.
HandleAllocator uses 3 pool (which currently can't be configured),
and is very efficient in terms of memory overhead and handle to
pointer conversion.
A Handle<> is just an offset into a large heap managed by the 3 pools.

moved HandleAllocator outside of the OpenGL backend

---

filament/README.md
samples/CMakeLists.txt

This helps users try out Filament without having to compile it themselves.

Add gltf_viewer and material_sandbox to release archives

---

libs/filabridge/include/private/filament/EngineEnums.h

This is a trivial change since we moved the lightspace computation
in the fragment shader. The limitation to 6 is due to how we're storing
the culling result.

enable up to 6 spot shadows

---

tools/matc/src/matc/MaterialCompiler.cpp

matc: log error when input material definition is empty

---

shaders/src/light_indirect.fs

See https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TransmissionRoughnessTest
for details.

When IOR=1.0, there should be no transmission roughness

---

shaders/src/light_directional.fs
shaders/src/light_punctual.fs

We can skip lighting in the areas fully shadowed, we can also skip
shadowing outside the radius of punctual lights.

Skip lighting/shadowing when possible

---

docs/remote/index.html
web/samples/remote.html

The most recently loaded model is now automatically re-loaded if you re-start the `sampler-gltf-viewer` app while keeping the remote page open.
Super useful in my case for `rgb-lights.glb` :)

Remote UI: auto load last loaded model.

---

filament/src/Scene.cpp
filament/src/View.cpp
filament/src/details/Scene.h
filament/src/details/View.h

We always may need to discard lights because we have a limited 
number we can use in the shader. We now do this earlier, in particular
before we set up the shadowmaps.
Because we also have a limited (smaller) number of shadowmap, this 
allows us to automatically select the ones that are closer to the 
camera, which gives better results.

Sort and discard lights early

---

libs/utils/include/utils/Zip2Iterator.h
libs/utils/test/test_Zip2Iterator.cpp

We should never be returning `value_type` from the iterator. That would only ever make sense, for example, in a `ConstZip2Iterator` class, _not_ for a `const Zip2Iterator`.
This led to `std::sort` not working correctly on Windows, which caused flickering punctual lights. Fixes #3395

Fix, MSVC's std::sort fails on Zip2Iterator

---

filament/backend/CMakeLists.txt
filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.mm

This helps profiling CPU time to encode a frame.

Add signposts to Metal backend

---

filament/src/Renderer.cpp

We were inserting the colorgrading subpass command between the
refracted and blended objects, instead of after all of them.
Another bad side effect of this was to trigger the refraction pass for
no reason.

Fix colorgrading as subpass

---

RELEASE_NOTES.md
android/filamat-android/src/main/cpp/MaterialBuilder.cpp
android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java
docs/Materials.md.html
libs/filamat/include/filamat/Enums.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/Enums.cpp
libs/filamat/src/MaterialBuilder.cpp
tools/matc/src/matc/ParametersProcessor.cpp

matc now honors 'precision' on non-samplers in mat files, and
the filamat API now allows clients to specify precision for
non-samplers.
This involved flattening a union that is internal to filamat.

API CHANGE: honor user-defined precision, rename SamplerPrecision.

---

filament/backend/src/Platform.cpp

My windows laptop does not support vulkan (or at least the cmake does not detect it). That means the samples crash because the backend is defaulting to vulkan. This change just makes the backend default openGL in the case that Vulkan is not available.

default to openGL when windows does not support VULKAN

---

filament/backend/include/private/backend/HandleAllocator.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h

We now have:
allocate<> which just allocates the handle's memory
construct<> which constructs the handle allocated with allocate<>
allocateAndConstruct<> which allocates AND constructs the handle
destroyAndConstruct<> which destroys and constructs a handle in place
Normally you'd use allocate/construct but with synchronous calls, it
might be necessary to have an initialized handle immediately.

Improve HandleAllocator API

---

filament/backend/src/HandleAllocator.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanDriver.h
filament/backend/src/vulkan/VulkanHandles.h
filament/backend/src/vulkan/VulkanSwapChain.h

Previously we were zero filling the data blob used to store all Vulkan
handles. This occured in VulkanDriver::alloc_handle().
There were several places that depended on the zero fill. These
have now been fixed up so that the handle can be constructed in a
more natural way.
Also: remove the OPENGL specific constant from HandleAllocator. This
breaks in non-CMake build systems (e.g. Bazel) that do not provide the
constant at a global level.

Prep for using new handle allocator in Vulkan.

---

filament/src/ColorGrading.cpp
filament/src/ColorSpace.h
filament/src/PostProcessManager.cpp
filament/src/ToneMapping.cpp
libs/imageio/src/ImageDecoder.cpp

Saturation and vibrance were using the wrong luminance weights,
and this change switches EVILS to HK weighted luminance weights
to give better results.

Small cleanup and improvements in ColorGrading

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/ColorGrading.cpp
android/filament-android/src/main/java/com/google/android/filament/ColorGrading.java
filament/include/filament/ColorGrading.h
filament/src/ColorGrading.cpp
filament/src/ToneMapping.cpp
filament/src/ToneMapping.h
libs/viewer/include/viewer/Settings.h
libs/viewer/src/Settings.cpp
libs/viewer/src/SimpleViewer.cpp
libs/viewer/tests/test_settings.cpp
samples/material_sandbox.cpp
samples/material_sandbox.h
web/filament-js/jsenums.cpp

Previously the luminance scaling step was tied to a specific tone mapping operator, called "EVILS" in the API. This was however somewhat misleading as EVILS really is a color handling system that's independent of what we call tone mapping.
This change splits the luminance scaling step from the tone mapping step, allowing the use of luminance scaling (the LICH part of EVILS) with any tone mapping operator.
As a result, the operator known as EVILS is currently mapped to the linear operator and renamed to "RESERVED" until it is replaced by a proper — configurable — operator.
Here is for instance the `ACES (Legacy)` operator without and with luminance scaling:
And the `Filmic` operator without and with luminance scaling:

Generalize luminance scaling in color grading

---

RELEASE_NOTES.md
android/filament-android/CMakeLists.txt
android/filament-android/src/main/cpp/RenderableManager.cpp
android/filament-android/src/main/cpp/SkinningBuffer.cpp
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
android/filament-android/src/main/java/com/google/android/filament/SkinningBuffer.java
filament/CMakeLists.txt
filament/include/filament/RenderableManager.h
filament/include/filament/SkinningBuffer.h
filament/src/Engine.cpp
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Scene.cpp
filament/src/SkinningBuffer.cpp
filament/src/View.cpp
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
filament/src/details/Engine.h
filament/src/details/Scene.h
filament/src/details/SkinningBuffer.h
filament/test/filament_test.cpp

The API now allows to create a standalone BufferObject containing
Bones for skinning. This BufferObject can even be very large and
contains bone data for several renderable.
A new API on RenderableManager allows to set the BufferObject to use.
This is still WIP:
- currently not possible to set the binding offset
- currently not possible to go back to the old API after using the new one

Implement sharing of bones for skinning

---

CMakeLists.txt
libs/gltfio/src/MaterialGenerator.cpp

This lets you see highly readable GLSL when transpiling the generated
SPIRV back to GLSL, with the original variable names preserved.
For now this is only useful when using `matinfo`, but it will soon be
useful in `matdbg` too.

Enable debug info in materials in debug builds.

---

filament/backend/src/metal/MetalBlitter.h
filament/backend/src/metal/MetalBlitter.mm
filament/backend/src/metal/MetalHandles.mm
filament/backend/test/test_LoadImage.cpp

When performing blits that do pixel format conversions (such as during texture uploads), we use the geometry pipeline. However, this requires that the destination texture have `MTLTextureUsageRenderTarget` set as one of its usage flags, which is sub-optimal. Instead, blit to an intermediate texture to perform the conversion, then use Metal's native blitting to perform the final blit.

Metal: Use an intermediate texture to avoid setting UsageRenderTarget on all textures

---

filament/backend/src/metal/MetalHandles.mm

When a render pass contains too much geometry, `MTLResourceStorageModeMemoryless` fails. For now, we'll prioritize correctness over performance and always use the private storage mode.
Fixes #4202

Metal: use private instead of memoryless textures for MSAA

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/src/ResourceAllocator.cpp

this allows the sidecar buffer to have the same lifetime than the
texture it represents, and therefore participate to the caching of
that texture.
Fixes #4338

associate sidecar MS buffer to its texture instead of RenderTarget

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/PostProcessManager.cpp
filament/src/details/View.h
libs/viewer/src/Settings.cpp
web/filament-js/jsbindings.cpp

This can have a dramatic effect on SSAO and needs 
to be adjusted based on the scene's scale/units.
The default value used to be about 6cm, and has 
been changed to 5mm.

Add bilateral threshold in SSAO options.

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/Matrix.kt

The previous code was a lot cleaner but caused 1+N (where N is
the dimension of the matrix) on each multiply.

Optimize matrix multiplications to avoid allocations

---

filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/test/TrianglePrimitive.cpp
filament/src/VertexBuffer.cpp

`BufferUsage` is no longer needed as an argument to `createVertexBuffer`. Instead, usage can be set on the individual `BufferObject`s that make up the `VertexBuffer`.

Remove BufferUsage flag from createVertexBuffer driver API

---

android/filament-android/CMakeLists.txt
build.sh
libs/matdbg/CMakeLists.txt
libs/matdbg/README.md
libs/matdbg/include/matdbg/ShaderReplacer.h
libs/matdbg/src/DebugServer.cpp
libs/matdbg/src/ShaderExtractor.cpp
libs/matdbg/src/ShaderReplacer.cpp
libs/matdbg/web/script.js
libs/matdbg/web/style.css
tools/matc/CMakeLists.txt

matdbg now links in filamat and provides a language tab at the top of the UI.
If a Vulkan shader is selected and edits are made in the GLSL tab, then glslang is used to regenerate the SPIR-V.
In the future we would like to support editing the original GLSL (not the transpiled GLSL) but this provides a short-term solution to Vulkan editing.

 matdbg: add support for editing Vulkan shaders

---

filament/backend/src/metal/MetalBuffer.h
filament/backend/src/metal/MetalBuffer.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

Only use CPU buffers for `DYNAMIC` or `STREAM` buffer usages.

Metal: take BufferUsage into account

---

android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h

Experimenting more with this, it seems better to be too blurry than
not enough for AO. The 5cm default seems to work better with more
scenes.

Change back default AO's bilateral blur edge to 5cm

---

filament/backend/src/BackendUtils.cpp
filament/backend/test/test_LoadImage.cpp

When reshaping pixels, we need to make sure the new `PixelBufferDescriptor` has the same attributes, like stride, left, and top.

Metal/Vulkan: Fix reshaped image uploads with buffer padding or offsets

---

filament/backend/include/private/backend/SamplerGroup.h
filament/backend/src/SamplerGroup.cpp

SamplerGroup was comparing texture handles to decide if a texture needed
to be updated, however, texture handles are (quickly) recycled and
therefore can't be used for that purpose. e.g. if a texture is destroyed,
its handle could be reused quickly by another texture, if that texture 
is now set on the SamplerGroup, it will ignore it, thinking it's not
different.

fix an issue where a sampler could fail to be updated

---

libs/gltfio/include/gltfio/AssetLoader.h
libs/gltfio/src/AssetLoader.cpp

This fixes two bugs that combined in a way that prevented a double-free
error.
The destructor of the impl class for AssetLoader was never called, which
was sort of good, because it should not destroy the material provider.
The asset loader was never meant to have ownership over the provider.

gltfio: fix AssetLoader leak, remove unwanted destructor.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp

It looks like they are not working, at least with the current version
of the drivers and/or MoltenVK. It is not impossible that we have a
bug in how we set the subpasses as well. This will need more investigation
later.

don't use Vulkan subpasses on Apple M1

---

filament/src/materials/colorGrading/colorGradingAsSubpass.mat

It was confusing how it reused the input as a temporary variable.

cleanup colorGradingAsSubpass shader

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/opengl/GLUtils.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp

This all started because the gl backend version of blit() didn't
handle color attachments other than COLOR0 *AND* would actually
corrupt the destination attachments other than COLOR0 if present. 
This is due to how very stateful the gl API is.
Since this is a case we're not running into currently, the GL backend will
now assert in that case.
Updated the Vulkan and Metal backends to also reject blits where
color buffers other than COLOR0 are requested.
Ultimately, we need to change entirely our backend blit API so it 
is less GL centric.

make blit() of all backend more similar

---

android/gltfio-android/src/main/cpp/UbershaderLoader.cpp

Fix nCreateMaterialInstance in UbershaderLoader: JNI_ABORT does not propagate changes

---

filament/backend/CMakeLists.txt
filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalContext.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalEnums.h
filament/backend/src/metal/MetalEnums.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

This removes a bunch of assumptions that only iOS devices have Apple GPUs. For example, M1 Macs should now also support compressed texture formats like ASTC and ETC.

Metal: support Apple GPU pixel formats on M1 Macs

---

docs/Materials.html
docs/Materials.md.html
shaders/src/ambient_occlusion.fs
shaders/src/light_indirect.fs

This helps prevent over-darkening but it's an artistic hack.
We need to check how we compute the bent normals as it seems we
find occlusion where there is no occlusion. The effect is
particularly visible on clear coat materials like a car's body.

Fade specular AO from bent normals at grazing angles

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h

When we associate a sidecar renderbuffer (for MSRTT emulation) to a 
texture, the msaa count comes from the rendertarget -- if this texture
is later used with a rendertarget with a different MS count, it should
still work -- in this case we have to reallocate the sidecar buffer.

cached sidecar renderbuffer must honor MS count

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/LightManager.cpp
android/filament-android/src/main/cpp/RenderableManager.cpp
android/filament-android/src/main/java/com/google/android/filament/LightManager.java
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLProgram.cpp
filament/include/filament/LightManager.h
filament/include/filament/RenderableManager.h
filament/src/Scene.cpp
filament/src/View.cpp
filament/src/components/LightManager.cpp
filament/src/components/LightManager.h
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
filament/src/details/Scene.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/UibGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
shaders/src/common_getters.fs
shaders/src/common_lighting.fs
shaders/src/getters.vs
shaders/src/light_directional.fs
shaders/src/light_punctual.fs
shaders/src/main.vs
shaders/src/shading_unlit.fs
web/filament-js/jsbindings.cpp

We use fp16 for most values (e.g.: direction, color), which 
ultimately frees a vec4 (Currently unused) and a few other bits.

Implement light channels

---

shaders/src/ambient_occlusion.fs
shaders/src/light_indirect.fs

We used a single specular AO term for the sheen and clear coat layers,
computed for the base layer. This was creating occlusion that was way
too strong when the roughness from the top layers was very different from
the roughness of the base layer. The effect was particularly obvious
on clear coat materials (car paint for instance).
With this change we can also remove the "grazing angle fade" artistic
hack that was previously introduced to combat this effect.
Ambient occlusion:
Specular ambient occlusion from screen-space bent normals with this fix:

Fix specular AO for the sheen and clear coat layers

---

android/filament-android/src/main/java/com/google/android/filament/Camera.java
filament/include/filament/Camera.h
filament/src/Camera.cpp
filament/src/details/Camera.h

Camera::getProjectionMatrix and Camera::getCullingProjectionMatrix used
to return the projection matrix modified by scaling and shift, instead
they should return the value set by the user, especially when
setCustomProjection() is used.

Camera::get*ProjectionMatrix should return the value set by the user

---

libs/filamentapp/include/filamentapp/NativeWindowHelper.h
libs/filamentapp/src/FilamentApp.cpp
libs/filamentapp/src/NativeWindowHelperCocoa.mm

By default windows on macOS are tagged with the display's color profile. This is fine if the app performs its own conversion from its working color space to the display profile's color space. However, Filament expects to output sRGB in sRGB windows and does not attempt to match the display profile, leaving this to the underlying operating system.
As a result, sRGB content output by Filament was stretched to the gamut volume of the display, which are commonly P3-ish nowadays. This resulted in over-saturated colors. With this change, our windows are properly tagged as sRGB and preserve the colors as expected.

Tag SDL2 windows as sRGB

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/Camera.cpp
filament/src/PostProcessManager.cpp
filament/src/ShadowMap.cpp
filament/src/details/ShadowMap.h
shaders/src/depth_main.vs
shaders/src/getters.vs
shaders/src/main.vs
shaders/src/post_process.vs

We now set the projection matrix so that the clip space for the z
axis follows the inverted DX convention, i.e.: z_clip between 1 (near)
and 0 (far), which matches our screen space.
Note that the actual clip space in the GPU can revert to the "inverted
GL convention", i.e.: z_clip between -1 and 1, if the clip_control
extension is not present. In that case the precision benefits are 
mostly lost.
Also note that there shouldn't be any user facing changes. 
The projection matrix at the API level, still follows the GL convention.
Also, currently, the VERTEX_DOMAIN_DEVICE for materials also keeps
the GL convention (this is corrected in the vertex shader).
The gist of this change is to move the "reversed DX" mapping from the
vertex shader to the projection matrix.

Use a clip space that matches our screen space for the z axis

---

filament/src/Renderer.cpp

We made this wrong assumption that views with a custom rendertarget
are never blended, but it's not true -- e.g. two views can use the
same rendertarget.
Fixes #4430
May impact #2802

views with custom render target should be blendable

---

filament/src/ColorGrading.cpp
filament/src/PostProcessManager.cpp
filament/src/details/ColorGrading.h
filament/src/materials/colorGrading/colorGrading.mat
filament/src/materials/colorGrading/colorGradingAsSubpass.mat

With this change we properly sample from the texel centers when we should, thus avoiding a bias toward the low values. This was particularly problematic in the darks, resulting in darker results than they should have been.
Before:
After:

Properly address the color grading LUT

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/Camera.cpp
android/filament-android/src/main/java/com/google/android/filament/Asserts.java
android/filament-android/src/main/java/com/google/android/filament/Camera.java
filament/include/filament/Camera.h
filament/src/Camera.cpp
filament/src/Scene.cpp
filament/src/ShadowMap.cpp
filament/src/View.cpp
filament/src/details/Camera.h
filament/src/details/Scene.h
ios/samples/hello-gltf/hello-gltf/CameraManipulator.cpp
web/filament-js/jsbindings.cpp

This PR only changes the API, internal storage and computation are 
still done in float, but this paves the way to double precision 
transforms.

model/view matrices on Camera now use double precision

---

filament/CMakeLists.txt
filament/src/ColorGrading.cpp
filament/src/ColorSpace.cpp
filament/src/ColorSpace.h
libs/math/include/math/TVecHelpers.h
libs/viewer/src/SimpleViewer.cpp

CAT16 is the transform from CIECAM16 which improves on CIECAM02/CAT02, with more accurate perceptual results.
The gamut mapping code is based on the Oklab color space and projects out-of-gamut colors onto the gamut volume. We use adaptive L0=0.5 and a default alpha of 0.05 but we should probably explore other projections (with Lcusp, etc.). This code is currently not used but will/may serve as the foundation for gamut mapping once we start using wider color gamuts during the color grading pass.

Switch white balance to CAT16 and add gamut mapping code

---

samples/image_viewer.cpp
samples/materials/image.mat

- Images with an alpha channel are now properly supported. Blending is implemented directly in the image material by blending against the known opaque background color.
- Non-EXR/HDR images were not applying the proper transfer function and were therefore displayed incorrectly.

Improve image_viewer compatibility

---

android/filament-android/src/main/java/com/google/android/filament/ToneMapper.java
filament/include/filament/ToneMapper.h
libs/viewer/include/viewer/Settings.h

The new default values match almost exactly the filmic tone mapper which
is itself a close approximation of ACES. This result in a slightly more
contrasty and pleasing image out of the box.

Slight tweak to the generic tone mapper

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/TransformManager.cpp
android/filament-android/src/main/java/com/google/android/filament/TransformManager.java
filament/include/filament/Engine.h
filament/include/filament/TransformManager.h
filament/src/Camera.cpp
filament/src/Engine.cpp
filament/src/Scene.cpp
filament/src/components/TransformManager.cpp
filament/src/components/TransformManager.h
samples/lightbulb.cpp

Augment the TransformManager so it can maintain the 4th column as
double precision; we accomplish this by storing an extra float3 per matrix.
It's calculated as `doubleTranslation - float3{doubleTranslation}`.
We also add methods to set and get a transform as mat4, internally only
the 4th column is kept as double precision.
Finally when we calculate the worldTransform, we take this extra data into
account, but only for calculating the new 4th column, so the extra work
is small.
model/view matrices on Camera now store their translation as double
double precision. This allows filament to handle a very large world
space (thousands of kilometers).

double-precision accurate translation

---

filament/backend/src/metal/MetalBlitter.h
filament/backend/src/metal/MetalBlitter.mm
filament/backend/src/metal/MetalHandles.mm
filament/backend/test/test_LoadImage.cpp

This allows 3D texture uploads to perform format conversions, such as RGBA16F -> RGBA32F.

Metal: support blitting 3D textures

---

filament/src/details/Material.h
libs/filabridge/include/private/filament/Variant.h
libs/utils/include/utils/bitset.h

There was a confusion on utils::bitset<> API, it specifies the number
of words to use, not then number of bits in the set.
VariantList was sized to store 8192 bits instead of 128.

fix VariantList type

---

filament/CMakeLists.txt
filament/include/filament/Options.h
filament/include/filament/View.h
filament/src/Exposure.cpp
filament/src/PerViewUniforms.cpp
filament/src/PerViewUniforms.h
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/details/ShadowMapManager.h
filament/src/details/View.h
libs/filabridge/include/private/filament/UibStructs.h

- move all `View` options to a new public header `Options.h`. This decouples these simple C-structs from `View`. These are more about rendering settings than `View` (which is about the camera and scene really).
- move all code managing the "per-view" uniforms to its own class. This is because in the future this won't be necessarily "per view", anymore (e.g. shadow maps should probably have their own).

View refactoring & cleanup

---

filament/src/ShadowMap.cpp
filament/src/ShadowMap.h
filament/src/ShadowMapManager.cpp
filament/src/ShadowMapManager.h

The main changes are:
- Break dependency of ShadowMap over View
- shadowmap command generation is now done in the framegraph pass 
itself, which allows it to be culled should the pass be culled.
- CameraInfo is created only once instead of twice / shadowmap. 
It's not super heavy but also not cheap, as several matrices are 
computed.
- simplified code.

Small ShadowMapManager refactoring 

---

CMakeLists.txt

See https://github.com/google/filament/discussions/4501#discussioncomment-1197696
This should also be cherry-picked for rc/1.12.1

Windows: fix incorrect CRT flags with Visual Studio generators

---

android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java

Java gltfio: fix use-after-free error in shutdown.

---

filament/backend/src/metal/MetalDriver.mm

Fixes #4534
This should also be cherry-picked to rc/1.12.2

Fix missing bookkeeping in bindUniformBufferRange

---

filament/backend/src/metal/MetalBuffer.h
filament/backend/src/metal/MetalBuffer.mm

My algorithm to manage the offset into the stream buffer was completely wrong. `getGpuBufferStreamOffset` needs to return the offset last written into.
This should also be cherry-picked to rc/1.12.2

Fix Metal STREAM buffers

---

filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/OpenGLDriver.cpp

Non sampleable buffers (Renderbuffers) are always rounded to 32 pixels
currently and on the backend side this buffer can end up being cached
as a sidecar buffer for MSAA. When it is created, it needs to be created
with the size of the texture it represents, not the size of the FBO,
which might be smaller.

Fix resizing issue when MSAA is active 

---

filament/src/materials/fsr/ffx_a.h

these approximations don't work in mediump and int/float bitcasting
is not well supported on mobile (can be slow).
This fixes RCAS on Mali.

don't use integer approximations on mobile

---

filament/src/materials/fsr/ffx_fsr1_mobile.fs

We used the "float" code with the "half" texture coords, turns out FSR
uses slightly different code for both.
We're now using the "half" code (using mediump float).

Fix integration bug in FSR mobile

---

filament/src/Engine.cpp

the gc usually runs for a very short amount of time, so the jobsystem
overhead is very significant compared to the actual work.
additionally this works around a scheduling issue that happens sometimes
on some devices where a thread could be "runnable but not running" for
many milliseconds.

don't run the component manager gc in a job each

---

filament/src/components/LightManager.cpp

The max is `f::PI_2`, so we should never have been setting this to more than that. >= `f::PI_2` causes shadows to disappear. `f::PI_4` is a much better default.

Use more sensible defaults for spot light inner outer cone angles

---

RELEASE_NOTES.md
filament/src/PerViewUniforms.cpp
filament/src/PerViewUniforms.h
filament/src/Renderer.cpp
filament/src/View.cpp
filament/src/details/View.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/GLSLPostProcessor.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/UibGenerator.cpp
libs/filamat/src/sca/ASTHelpers.cpp
libs/filamat/src/sca/ASTHelpers.h
libs/filamat/src/sca/GLSLTools.cpp
libs/filamat/src/sca/GLSLTools.h
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/depth_main.fs
shaders/src/main.fs

A lod bias can be applied to textures when dynamic resolution is
enabled. A proper lod bias is calculated and applied for quality levels
HIGH and ULTRA.
Lod Bias is implemented in glslang, which mean it's ignored when
glslang is not used, which currently happens with OpenGL backends with
optimization turned off (which includes filament LITE). This may be
fixed in the future.

Implement lod bias for user materials

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp

The timestamps are given in "ticks", not in nanoseconds, like our API expects.
Fixes #4588

Fix timer queries in Vulkan backend

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/IBLPrefilterContext.java
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
libs/iblprefilter/include/filament-iblprefilter/IBLPrefilterContext.h
libs/iblprefilter/src/IBLPrefilterContext.cpp

The finalizer can't be used to dispose of filament resource, because
it runs on its own thread.
Added a destroy() method to all IBLPrefilter related classes that must
be called once the object is no longer needed.
note: Resources will be freed eventually anyways when the Engine itself is
destroyed.
fixes #4633

IBLPrefilter relied on finalizer which could cause crashes

---

shaders/src/shading_unlit.fs

By definition, an emissive surface won't be affected by shadowing
since it's its own light source.

Emissive needs to be applied after shadowing

---

filament/src/Material.cpp
filament/src/RenderPass.cpp

the code generating the commands for the structure pass (called DEPTH)
in the code was different that from the color. This made sense, but 
isn't great from an architectural standpoint.
Moreover, the special filtering flags DEPTH_FILTER_*_OBJECTS were
useless because part of their functionality was handled in the DEPTH
code directly.
Instead, we now generate the DEPTH commands the same way than we do for
COLOR, but we honor the DEPTH_FILTER_*_OBJECTS flags properly.

improve how the structure pass commands are generated

---

filament/backend/src/metal/MetalBlitter.mm

Older versions of iOS (<= 13.0) report shader warnings as errors, which was causing the assertion to fire.

Fix MetalBlitter crash when shader contains warnings

---

filament/backend/src/metal/MetalExternalImage.h
filament/backend/src/metal/MetalExternalImage.mm

`createTextureViewWithSwizzle` should not be called directly, as it's only available on newer systems. This was causing a build warning and potentially a crash with older (< iOS 13.0) devices.

Metal: don't call createTextureViewWithSwizzle directly

---

filament/backend/src/vulkan/VulkanDriver.cpp

vulkan expected a vertical offset from the top, but the api is in
gl convention with the offset from the bottom.

fix readPixels vertical offset in vk backend

---

RELEASE_NOTES.md
android/common/CallbackUtils.h
android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/backend/src/DataReshaper.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/include/filament/View.h
filament/src/Material.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp
filament/src/Scene.cpp
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/components/RenderableManager.h
filament/src/details/View.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filabridge/include/private/filament/Variant.h
libs/filamat/src/UibGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/depth_main.fs
shaders/src/depth_main.vs

This is a pixel accurate implementation of picking. Picking queries
can be created on view, and upon completion a user provided callback
is called with the Entity of the renderable at the queried coordinates
in the viewport.
Picking queries typically have 1 or 2 frame of latency and may impact
performance on some drivers.
It is mostly intended for use by editors, or when latency is not a major
concern. This api should not be used for dragging/moving objects, it is
intended for initial picking only.
Picking is implemented in the structure pass.

Implement picking functionality

---

filament/src/Color.cpp
filament/src/ColorGrading.cpp
filament/src/ColorSpace.h
shaders/src/dithering.fs

Nothing wrong with EOCF/OECF but the "T" version is more common and readers will
therefore be more likely to be more familiar with it.

Use the more common EOTF/OETF acronyms

---

android/filament-android/src/main/java/com/google/android/filament/Engine.java
filament/backend/include/private/backend/Driver.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/include/filament/Engine.h
filament/src/Engine.cpp
filament/src/details/Engine.h

A new Engine::pumpMessageQueues() method can be used to trigger all
pending user callbacks right away. This can help reducing latency
of certain callbacks such as picking queries.
This is typically called once before calculating the next frame's
parameters (e.g. object positions or appearance that may depend on a 
callback result).
Fix some comments and documentation.

improve user callbacks latency

---

filament/backend/src/vulkan/VulkanBlitter.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanStagePool.cpp
filament/backend/src/vulkan/VulkanStagePool.h
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/VulkanTexture.h
filament/backend/src/vulkan/VulkanUtility.cpp
filament/backend/src/vulkan/VulkanUtility.h
libs/bluevk/src/BlueVKDarwin.cpp

The main issue that gets fixed here are:
- VK_IMAGE_LAYOUT_UNDEFINED cannot be used if the image content is to 
be preserved after the transition. Unfortunately, there is more than a 
few places in the VK backend where we use VK_IMAGE_LAYOUT_UNDEFINED on
images that are later used as sources.
- accessing an image memory from the host is only supported if the the 
layout is PREINITIALIZED or GENERAL. However, images in the staging
pool were transitioned to other layouts and put back into the pool,
later they would be mapped/memcpy'ed into. Instead we now always use
the GENERAL layout and never change it.
- images that where in the pool where transitioned using the miplevel
of the texture we were copying into, however this didn't make sense
because images from the pool don't have mip …

rework Vulkan image layout transitions

---

filament/src/PostProcessManager.cpp
filament/src/Renderer.cpp

The DSR options were carried all the way to the final blit that is 
sometimes needed to impedence-match our rendering features with the
swapchain. This blit is never a scaling blit, but we were using the
FSR option, which would sometimes trigger the FSR scaling code.

fix an issue where we'd use the FSR scaling instead of a dumb blit

---

filament/backend/src/vulkan/VulkanDriver.cpp

The actual problem is with the basic "blit" functionality which
is broken, and is sometimes triggered when subpasses are used.

MoltenVk actually does support subpasses on M1

---

filament/src/PerViewUniforms.cpp
filament/src/ShadowMap.cpp
filament/src/ShadowMap.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/UibGenerator.cpp
shaders/src/depth_main.vs
shaders/src/main.vs

When calculating the linear depth for VSM, we were using the whole
range between 0 and the far plane, the near plane wasn't taken into
account.
This can be a problem is the light is very far, but it's near plane is
closer to the camera/scene, in this case the depth precision wasn't
used optimally.
Note that we don't hit this problem currently, because the directional
light is constructed such that its origin is at the near plane, and the
spotlights have a fixed near plane (which is a problem and will be 
fixed at a later time).

fix depth precision with VSM

---

filament/include/filament/LightManager.h
filament/src/Froxelizer.cpp
filament/src/components/LightManager.cpp

The froxel code was failing when a spotlight cone was too narrow. This
is fixed here by never using a cone smaller than 0.5 degrees during
forxelization. 
Additionally we now silently clamp the cone angles to 0.5 degrees at
the API level because, the falloff was also failing due to floating
point precision in the shader.
Finally, we clamp the inner cone upper value to the outer cone's
instead of the other way around. i.e. the outer cone defines the 
spotlight while the inner cone just controls the falloff.

Fix very narrow spotlight lighting and other minor issues

---

filament/src/ShadowMap.cpp
filament/src/ShadowMap.h
filament/src/ShadowMapManager.cpp
filament/src/ShadowMapManager.h

Near/far plane is now computed dynamically, this significantly
improves the shadowmap depth resolution.
Quite a bit of refactoring was necessary to get all the right data 
in the right place, in particular SceneInfo is now passed around for
both directional and spot shadows.

Improve computation of spotlight near/far plane

---

filament/src/ShadowMap.cpp
filament/src/ShadowMap.h
filament/src/ShadowMapManager.cpp
filament/src/ShadowMapManager.h
filament/src/View.cpp
filament/src/details/Scene.h

We now cull the shadow casters before computing the near/far plane
for spotlights -- we can do that because we know the light's frustum.
So only these casters that contribute to the shadow are accounted for
when calculating the near/far plane.
This PR also include more cleanup and simplifications.

Tighten spotlights near/far further

---

android/filament-android/src/main/cpp/LightManager.cpp
android/filament-android/src/main/java/com/google/android/filament/LightManager.java
filament/include/filament/LightManager.h
filament/src/ShadowMap.h
filament/src/ShadowMapManager.cpp

- constant bias and normal bias default values in java didn't match
C++ or the documentation
- stable shadows were enabled by default in java
- polygon offset biases were missing from the java API
- document and don't apply polygon offset to VSM
- remove unused code

Fix java shadow biases + minor cleanups

---

filament/src/ShadowMap.cpp
shaders/src/common_shadowing.fs
shaders/src/getters.fs
shaders/src/main.vs

The normal bias is now computed correctly, this requires to compute
the z in lightspace in the shader.
Note that this would not work as well if we used LISPSM, but we'll
cross that bridge when we get there.

Fix normal bias for spotlights.

---

shaders/src/shadowing.fs

- remove PCF "low" quality, we only use "HARD" now, when using PCF.
Higher quality levels are achieved by using VSM.
- added a version of PCF that doesn't use a shadowSampler for future
use.

simplify shadowing code

---

shaders/src/shadowing.fs

Shadow Receiver Plane Depth Bias is only needed when using large PCF
filters, which we are no longer doing. Large filter kernels are now 
supported through VSM sampling.

Remove all "Shadow Receiver Plane Depth Bias" related code

---

.github/workflows/release.yml

This will allow us to trigger release builds from the GitHub UI.

Use workflow_dispatch instead of repository_dispatch

---

filament/backend/src/opengl/OpenGLContext.cpp

I don't understand why, but I'm able to reproduce the VSM/cascade issue on Android again. I want to bisect recent commits and see if I can track down where this started reproducing again, but for now I'm going to re-enable the fix.

Android: re-enable VSM cascade fix

---

shaders/src/main.vs

A recent refactor was causing the following error when the vertex domain was set to `device`:
```
ERROR: main.vs:23: 'material' : undeclared identifier
ERROR: main.vs:23: 'materialVertex' : no matching overloaded function found
```

Fix material compilation error with device vertex domain

---

filament/backend/src/metal/MetalState.h

#4860 introduced a bug caused by default-initializing the Metal depth stencil state. `MTLCompareFunctionAlways` should be the default comparison function, which turns off depth testing.

Fix Metal depth comparison initialization

---

libs/image/src/KtxBundle.cpp
libs/utils/CMakeLists.txt
libs/utils/include/utils/string.h
libs/utils/src/string.cpp
libs/utils/test/test_string.cpp
tools/matc/src/matc/JsonishParser.cpp
tools/specular-color/src/main.cpp

strtof and friends are locale aware and won't parse decimal numbers
with a period ("12.6" for instance) in locales that use another
character for the decimal period ("," in French for instance).
This change introduces a new function called strtof_c that forces
the use of a specific locale (called "C") to make sure we always
parse floats in the desired "C" format ("12.6").
With C++17 we should be able to use std::from_chars but this API
is not implemented in clang for floats at the moment.
Fixes #4883.

Use locale-independent string->float conversion

---

filament/src/SkinningBuffer.cpp

If the upper 3x3 of the bone matrix contains all zeroes, then we end up dividing by zero which generates `NaN`s in the shader.
Fixes the issue seen with https://github.com/google/model-viewer/issues/2890

Avoid divide-by-zero inside FSkinningBuffer::makeBone

---

android/filament-android/src/main/java/com/google/android/filament/Engine.java
android/filament-android/src/main/java/com/google/android/filament/LightManager.java
android/filament-android/src/main/java/com/google/android/filament/Material.java
android/filament-android/src/main/java/com/google/android/filament/RenderTarget.java
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
android/filament-android/src/main/java/com/google/android/filament/Stream.java
android/filament-android/src/main/java/com/google/android/filament/Texture.java
android/filament-android/src/main/java/com/google/android/filament/TextureSampler.java
android/filament-android/src/main/java/com/google/android/filament/View.java
android/filament-utils-android/src/main/java/com/google/android/filament/utils/Manipulator.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/UbershaderLoader.java

Each call to .values() allocates a new array. Let's cache them once
and for all to avoid unncessary allocations.

Cache calls to Enum.values()

---

RELEASE_NOTES.md
filament/src/ShadowMap.cpp
filament/src/ShadowMap.h
filament/src/ShadowMapManager.cpp
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/UibStructs.h
shaders/src/common_types.fs
shaders/src/getters.fs

The calculation was completely wrong due to several typos more or less
canceling each other, that led to some misunderstanding!

Fix spotlight normal bias calculation

---

filament/include/filament/Engine.h
filament/src/Engine.cpp

This commit enables Engine::destroy(SkinningBuffer*), which is already implemented internally in FEngine.
I implement a shared animator class for multiple renderables utilizing SkinningBuffer instances. I found FEngine already has destroy function for FSkinningBuffer, but there is no trampoline somehow.

Expose Engine::destroy(SkinningBuffer*)

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/Options.h
filament/src/PerViewUniforms.cpp
libs/viewer/src/Settings.cpp

this is an internal parameter and has no reason to be user settable.

remove 'exponent' from VsmShadowOptions

---

shaders/src/getters.fs

`vertex_worldNormal` should never be used directly, for one thing it's
not guaranteed to be normalized.

use the correct normal when calculating spotlight bias

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h

Call `import` and `detach` outside of TAA, since SSR will also need color history.

Rework color history in preparation for SSR

---

filament/backend/src/opengl/OpenGLDriver.cpp

- compressed textures debug checks could improperly fail
- setting data to cubemap mip levels could fail

fix typos when setting texture data

---

android/common/CallbackUtils.cpp

We were acquiring a reference twice by accident.
Fix #4957

Fix a java global reference leak

---

android/common/CallbackUtils.h
android/filament-android/src/main/cpp/Texture.cpp

The version of Texture::setBitmap() that tool an Android bitmap handled
callbacks differently and in certain case caused a "double release" of
the callback object. This didn't actually cause problems though.
We now use the same mechanism used elsewhere (i.e. JniCallback).

Fix a double release with Android bitmaps callbacks

---

filament/backend/src/metal/MetalDriver.mm

In certain scenarios, the passed-in `height` might be greater than the source texture's actual `height`. This causes an underflow on line 1038.
Fixes #4077

Metal: clamp readPixels width and height to texture dimensions

---

tools/matc/tests/MockConfig.cpp

This is in preparation for a new version of MSVC. See #5006

Avoid calling std::string(nullptr) in MockConfig.cpp

---

README.md
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
filament/backend/include/backend/DriverEnums.h
filament/backend/src/metal/MetalEnums.h
filament/backend/src/ostream.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
libs/gltfio/src/GltfEnums.h
web/filament-js/filament.d.ts
web/filament-js/jsenums.cpp

Initially discussed [here](https://github.com/google/filament/issues/4508l)
Strips are supported on all current backends and can be useful in some cases.
The changes are minimal.

Added line/triangle strip support

---

filament/backend/src/opengl/OpenGLDriver.cpp

Cubemap update was broken by this commit: [6fa82ea73d7263931d6c96d56a42b5cca20a07a0](https://github.com/google/filament/commit/6fa82ea73d7263931d6c96d56a42b5cca20a07a0)
Cubemap update call setcompressedTextureData/setTextureData with 0, 0 as width and height as this was relying on those methods to just use the t->width, t->height instead of the function arguments.
Not sure if that is legal, maybe an assert should check for that case or it should be handled in the function (width = width ? width : t->width)

Fixed cubemap update

---

libs/filamentapp/src/FilamentApp.cpp

This is very helpful for debugging apps that don't use ImGui.

FilamentApp: use PrtScn key to capture debug frame

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
android/gltfio-android/src/main/cpp/ResourceLoader.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/ResourceLoader.java
docs/remote/filament.js
docs/viewer/filament-viewer.js
docs/webgl/filament.js
libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/ResourceLoader.cpp
samples/gltf_viewer.cpp
web/filament-js/extensions.js
web/filament-js/filament-viewer.js
web/filament-js/jsbindings.cpp

For a skinned gltf model, its mesh primitives world transform may not be the same as its bind transform. This pr aims to recompute aabb based on bind transform to fix misalignment issue.
| | Suzanne     | torus | 
|----------|-----------|----------|
| Before | ![Suzanne_skinning_before](https://user-images.githubusercontent.com/21233675/146144254-fedd3fb3-de75-40b2-994a-7a4c5da5d982.png)   | ![torus_before](https://user-images.githubusercontent.com/21233675/146144424-2fb56624-462f-4f37-a047-99bee3fdf0cb.png) |
| After | ![Suzanne_skinning_after](https://user-images.githubusercontent.com/21233675/146144352-4ac69261-315a-4f66-b08d-cdd0aee793d0.png)  | ![torus_after](https://user-images.githubusercontent.com/21233675/146144380-e6316cdd-a5ca-45c6-8fc3-7d08f5f206d8.png) |
Test models: …

fix aabb misalignment for skinned gltf model

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt

Moving `UiHelper` to the constructor which allows for more composable control of the underlying views & surface.
More specifically, I needed to set the opacity of the underlying views within `ModelViewer`.

ModelViewer move UiHelper to constructor 

---

libs/gltfio/src/UbershaderLoader.cpp

The macro GLTFRESOURCES_LITE_LIT_BLEND_DATA is not defined anywhere, it should be GLTFRESOURCES_LITE_LIT_FADE_DATA. This solves the issue of rendering transparent objects using GLTFIO_LITE macro, i.e. using gltfresources_lite.bin. If we don't change this macro, the transparent objects will be rended using lit_opaque material instead of lit_fade material.
I think [this issue](https://github.com/google/filament/issues/4164) recorded is also caused by this bug. It should be fixed after this macro change.

fix a bug of rendering transparent object when using GLTFIO_LITE/gltfresources_lite.bin

---

android/filament-android/src/main/cpp/ToneMapper.cpp
android/filament-android/src/main/java/com/google/android/filament/ToneMapper.java
filament/include/filament/ToneMapper.h
filament/src/ColorGrading.cpp
filament/src/ColorSpace.h
filament/src/ToneMapper.cpp
libs/math/include/math/TVecHelpers.h
libs/viewer/include/viewer/Settings.h
libs/viewer/src/Settings.cpp
libs/viewer/src/SimpleViewer.cpp
libs/viewer/tests/test_settings.cpp

This change removes the shoulder parameter which had inconsistent
behaviors. The new curve is simpler and designed to still match
by default the gray point and the contrast of ACES in a bright
surround.

Replace generic tonemap curve with a simpler one

---

CMakeLists.txt
filament/backend/src/android/ExternalTextureManagerAndroid.cpp
filament/backend/src/android/ExternalTextureManagerAndroid.h
filament/backend/src/opengl/platforms/ExternalStreamManagerAndroid.cpp
filament/backend/src/opengl/platforms/ExternalStreamManagerAndroid.h
third_party/spirv-cross/spirv_glsl.cpp

This uses compile time guarded calls to weak symbols, and allows us to
call NDK APIs without having to dlsym() them.

Use NDK29 new (and experimental) way to access NDK functions

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp

Move the command generation of the structure pass into its execute 
block, meaning that if the structure pass is culled, the command 
generation is now skipped too.

improve structure pass performance when not used

---

libs/filabridge/include/private/filament/Variant.h
libs/viewer/src/SimpleViewer.cpp

When VSM is turned on but shadow receiver is turned off for a renderable, we're hitting an assertion:
```
reason: ../../filament/src/Material.cpp:366: failed assertion `!Variant::isReserved(variantKey)'
```
The variant in question is 0x41, which is a reserved variant:
```
//                      +-----+-----+-----+-----+-----+-----+-----+-----+
// Variant              |  0  | VSM | FOG | DEP | SKN | SRE | DYN | DIR |   128
//                      +-----+-----+-----+-----+-----+-----+-----+-----+
//  0x41                   0     1     0     0     0     0     0     1
```
It's reserved because it doesn't make sense to have shadows if the shadow receiver bit is off.
This variant should get filtered to 0x01. We were checking for this in `isValidStandardVariant`, but not accounting for it in …

Fix, assertion with shadowReceiver = false and VSM

---

filament/backend/src/metal/MetalDriver.mm

The `uint8_t` here needs to be cast to an integer to be printed
correctly. Also these warnings seem to be quite common so we should
hide them in Release builds.
These warnings probably indicate an actual problem that I do not fully
understand yet.

Reduce cascade of run-time warnings.

---

filament/src/PerViewUniforms.cpp
filament/src/PerViewUniforms.h
filament/src/Renderer.cpp
filament/src/View.cpp
filament/src/details/View.h
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/light_indirect.fs

what's not allowed at this point is an object which has both screen
space refraction and reflection.
this is accomplished by just always disabling screen-space reflections
for the translucent step of the refraction pass
.

allow a scene to have both transmission and reflection

---

filament/src/details/View.h
shaders/src/light_indirect.fs
shaders/src/light_reflections.fs

screen-space reflections are integrated in the indirect light computation
(similarly to screen-space refraction), this is because it can be seen as
the specular term of screen-space GI.
However, because this effect is screen-space, the data it accesses has 
the ibl luminance (and exposure) applied.
Besides some minor refactoring, this change just applies the 
screen-space reflections *after* the ibl's specular term is exposed.

Fix integration of screen-space reflections with lighting

---

filament/backend/src/vulkan/VulkanTexture.cpp

2D array textures are initialized with .depth = 1 and layerCount = depth (see line 58 in VulkanTexture.cpp). By setting layerCount = 1 only the first layer was copied over, leaving the other layers uninitialized.

Fixed VulkanTexture::copyBufferToImage for 2D texture arrays

---

filament/backend/src/opengl/OpenGLProgram.cpp

When a program had an unused SamplerInterfaceBlock, other samplers
could be bound to the wrong TMU
Fixes #5088 which was exposed by #4999.

[GL backend] fix sampler binding bug

---

filament/src/Engine.cpp
filament/src/MorphTargetBuffer.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/details/Engine.h
filament/src/details/MorphTargetBuffer.h

This is because we're using the same program variant for skinning
and morphing, in the skinning-only case, the buffer won't be accessed
in the shader, but it must be present.
fixes #5085

A morphing buffer must be bound when skinning is active

---

filament/src/MorphTargetBuffer.cpp
filament/src/Renderer.cpp
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/details/MorphTargetBuffer.h
filament/src/details/View.h

There is no need to go through all primitive and call updateSamplerGroup,
because the SamplerGroup never changes -- it just hold the texture that
holds the data.

Simplify and optimize morphing

---

filament/backend/src/vulkan/VulkanBlitter.cpp
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanSwapChain.cpp
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/VulkanTexture.h
filament/backend/src/vulkan/VulkanUtility.cpp
filament/backend/src/vulkan/VulkanUtility.h

This fixes validation errors and makes a first pass at simplification.
VulkanTexture now tracks image layout using RangeMap, which paves the
way for further simplification.

Vulkan: clean up image layout management.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/VulkanTexture.h

This allows `MorphStressTest` to work on Vulkan.
However, `Horse` is still broken because it provides positions but not
tangents.  Separate fix for that is coming.
Partial fix for #5109.

Vulkan now supports offsets when uploading texture data.

---

filament/include/filament/MorphTargetBuffer.h
filament/src/components/RenderableManager.cpp
shaders/src/getters.vs

- Document that both positions and tangents must be provided.
- Don't memset buffer before filling it
- Don't read 4 identical weights in shader

Minor optimizations and documentation cleanup

---

libs/utils/src/android/ThermalManager.cpp

"#include <android/Thermal.h>" will cause some errors when building aar on Linux,
the corrret answer is "#include <android/thermal.h>"

fix build android aar on Linux because of case sensitive

---

build/web/ci-common.sh

Now， Filament WebGL could  be compiled on MacOS. I add somethings in webgl/common-ci.sh scripts to support linux platform compile.

WebGL: Support compile filament.wasm on Linux platform.

---

libs/gltfio/src/MorphHelper.cpp

This allows the `Horse.glb` model to work with Vulkan without any
validation errors. As a reminder, the glTF spec says:
```
When normals are not specified, client implementations MUST calculate
flat normals
```
Fixes #5115.

gltfio morphing: generate normals when they are missing.

---

filament/src/PostProcessManager.cpp
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp
libs/filabridge/include/private/filament/Variant.h

Instead of building the Variant based on flags in RenderPass, we just
pass the Variant itself to RenderPass. The caller has more knowledge
of what it wants to do.

simplify how we select a material Variant

---

filament/include/filament/MorphTargetBuffer.h
filament/include/filament/RenderableManager.h
filament/src/MorphTargetBuffer.cpp
filament/src/details/MorphTargetBuffer.h

Because the morphing buffer is actually a texture, it's possible that
the last line is not a full-width line when updating the buffer.
Because textures are updated via a rectangle, it was possible to read
past the malloc'ed buffer during the update.
Moreover, because the count can be specified, we can't just blindly send
more "dummy" data. 
Finally, added an offset to match the skinning API, and in that case, 
the first line can also be incomplete.
We fix this by issuing up to 3 texture update calls if needed.
The java/js API update will come later.

fix an out-of-bound access when setting morphing buffer

---

libs/filamentapp/include/filamentapp/FilamentApp.h
libs/filamentapp/src/FilamentApp.cpp

This fixes the gltf_viewer automated testing mode, invoked via
`--batch=default --headless`.
ReadPixels was being issued with an out-of-bounds size on high DPI
platforms, which caused weird backend errors.
Since we create an invisible SDL window while in headless mode, the
presence of the SDL window does *not* indicate headless vs non-headless.
Partial fix for #5111

gltf_viewer: fix bad ReadPixels size in headless mode

---

libs/utils/include/utils/Range.h

Needed for `std::random_access_iterator_tag`.

Add missing include to Range.h

---

filament/backend/src/vulkan/VulkanPipelineCache.cpp
filament/backend/src/vulkan/VulkanPipelineCache.h

This PR has two commits that should not be squashed.  The first commit is a cleanup pass.  The second commit contains the actual fix for #5142.

Fix Vulkan crash regression

---

filament/src/PerViewUniforms.cpp
shaders/src/light_reflections.fs

- Make sure to disabled SSR when it's... disabled.
- Fade the reflection when the ray direction is towards de camera,
where it will likely hit a back face
- Simplify the fading code, for near identical results.

A few screen space reflections improvements

---

libs/gltfio/src/AssetLoader.cpp

glTF spec says that all primitives MUST have the same number of morph targets in the same order so these changes are more correct.

Get the morph target count from glTF

---

filament/src/PerViewUniforms.cpp
filament/src/PerViewUniforms.h
filament/src/Renderer.cpp
filament/src/View.cpp
filament/src/details/View.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/UibGenerator.cpp
shaders/src/light_indirect.fs
shaders/src/light_reflections.fs

- Rename projectToPixelMatrix to uvFromViewMatrix, this match our 
existing style better.
- slightly more efficient direction transform
- limit roughness to 0.1 instead of 0.01, because in a lot of cases, 
the roughness increases with the LOD, for instance if it comes from
a texture (to combat aliasing).

Minor cleanups

---

filament/backend/src/vulkan/VulkanCommands.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanPipelineCache.cpp
filament/backend/src/vulkan/VulkanPipelineCache.h

All three types of internal caches (descriptor sets, pipelines, and pipeline
layouts) are now managed in exactly the same way. They all use an LRU
eviction scheme that is based on a count of command buffer flush
events.
Vulkan objects can only be destroyed if there are no in-flight command
buffers that reference them, so an easy way to know when it is safe to
evict a given entry is to wait for "N" flushes after its last use, where
"N" is the number of command buffers in the command buffer ring.
Another big simplification is that there are no more dirty flags,
instead we store two sets of state vectors for each type of cache: the
"currently bound" state, and the "current requirements" state.

Rewrite VulkanPipelineCache (without changing its API).

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h

- make code mode readable, hopefully
- SSR mipmap generation is now more or less standalone
- when possible, resolve color buffer directly into
mimpmapped texture's base level.

refactor refraction code

---

libs/filabridge/include/filament/MaterialEnums.h

This is useful for clients who previously relied on `MAX_MORPH_TARGETS` being 4.

Add a MAX_LEGACY_MORPH_TARGETS definition

---

filament/src/RenderTarget.cpp

the validation could fail if attachments used different LODs but the
sizes still matched.

fix typo in RenderTarget::build attachment size validation

---

android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java

Filament now supports the number of morph target up to 256.

Fix an annotation for the morph target count

---

web/filament-js/utilities.js

If emscripten grows the heap inside one of our BufferDescriptor binding
functions, then the old heap becomes "detached" and an error can
occur.
This fixes the issue seen with the Parquet demo that Ben caught.

WebGL: remove buffer sharing optimization.

---

filament/backend/src/vulkan/VulkanBlitter.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanFboCache.h
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanSwapChain.cpp
filament/backend/src/vulkan/VulkanSwapChain.h
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/VulkanTexture.h

Two big changes to simplify and fix layout transitions:
(1) The RenderPassKey struct has been reduced from 88 bytes to 56 bytes
by using custom enum types and bitmasks. It also now has separate fields
for "final" and "initial" image layouts.
(2) VulkanSwapChain now leverages VulkanTexture, which enables it to
share tracking functionality, avoid duplicated state, and have less code
overall.
In a future PR we will clean up the ReadPixels and Blit paths, and also
remove some hacks that appease Vulkan when SSAO is enabled.

Crucial refactoring of VulkanFboCache and VulkanSwapChain.

---

libs/utils/include/utils/RangeMap.h
libs/utils/test/test_RangeMap.cpp

The existing unit test had an incorrect expectation in what happens
after splicing an existing range. Fixing the unit test revealed an
actual bug in the RangeMap implementation. It should never modify the
lower bound of an existing interval, because that invalidates the
iterator.

Fix some RangeMap behavior and improve its unit test.

---

filament/backend/src/vulkan/VulkanBlitter.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanUtility.cpp

VulkanSwapChain is now always backed by VulkanTexture, so these
code paths can be simplified.

Vulkan: clean up ReadPixels and Blit paths.

---

filament/backend/src/vulkan/VulkanBlitter.cpp
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h
filament/backend/src/vulkan/VulkanSwapChain.cpp
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/VulkanTexture.h

Do not squash, these are actually 3 separate refactorings.

Vulkan: simplify management of "default" render target.

---

filament/backend/src/vulkan/VulkanBlitter.cpp
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h
filament/backend/src/vulkan/VulkanSwapChain.cpp

Now that VulkanRenderTarget is always backed by textures, it no longer
needs to track state that is already tracked by VulkanTexture.

VulkanRenderTarget: remove duplicated state tracking.

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/PostProcessManager.cpp
filament/src/RenderPass.cpp
filament/src/RenderPass.h

Previously, the Vulkan backend made an educated guess about the depth
write state during the start of the render pass. The logic for this
did not make any sense, so now we're replacing it with an explicit
hint that PostProcessManager sets up. In a sense this gives backends
a sneak peek into the raster state.

Add read-only mask to RenderPassParams.

---

web/filament-js/filament-viewer.js
web/filament-js/wasmloader.js

This fixes the emscripten binding errors that we've been seeing
with the <filament-viewer> test page, which prevented us from
including web in the last few Filament releases.
The binding errors were caused by double-initializing the emscripten
module.
I fixed this by allowing clients (e.g. FilamentViewer) to call
Filament.init() more than once. We now accumulate a list of "on ready"
callbacks that get triggered after the emscripten module becomes ready.
As far as I can tell, multiple canvases were actually always broken, and
the viewer test page worked in the past only because we got lucky.

Fix web apps that have multiple Filament viewers.

---

libs/gltfio/src/AssetLoader.cpp

We now handle "too many bone weights" in the same way that we handle
"too many UV sets".  i.e. emit an error message and do not panic.
This change allows us to render the model in #5234 quite reasonably.
Fixes #5234.

gltfio: be graceful when model has > 4 weights per vert.

---

filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanUtility.cpp

When we overhauled image layout transitions, we moved as many
transitions as possible into the render pass. However the transition
that we perform for "depth read only" layout still needs to be applied to
multiple miplevels, so we cannot use the render pass for that.

Vulkan: fix hack by allowing SSAO to read from all mips.

---

filament/backend/src/vulkan/VulkanDriver.cpp

We were passing the wrong texture object to VulkanDisposer::acquire().
MSAA depth sidecar textures are not managed by VulkanDisposer, but their
parent textures are.
Fixes #5217.

Vulkan: fix lifetime issue with sidecar depth.

---

filament/backend/src/vulkan/VulkanHandles.cpp

Every sidecar texture should have the same dimensions as its parent
texture.
Prior to this change, the sidecar texture would have the dimensions of
the RenderTarget wrapper rather than the parent texture. This was wrong
because the RenderTarget might be slightly smaller than the texture.
This caused an issue when the same texture was attached to two render
targets with different sizes, because there's only 1 cached sidecar per
texture.

Vulkan: fix issue with MSAA sidecar dimensions.

---

filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanPipelineCache.cpp

This makes it so that we emit a nice error message instead of triggering
a hairy validation error due to UNDEFINED image layout.

Vulkan: be graceful when apps use uninitialized textures.

---

libs/gltfio/src/UbershaderLoader.cpp

Fixes logcat spam seen with IridescentDishWithOlives.

gltfio ubershader: provide dummy texture for volume thickness.

---

filament/backend/src/vulkan/VulkanBlitter.cpp

When we introduced texture-based morphing, our custom depth resolver
needed to be updated to set up samplers correctly. This fixes a
validation error about shader stage access.

Vulkan: Fix regression with IridescentDishWithOlives.

---

libs/utils/include/utils/CString.h

This caused a unit test failure because a StaticString constructed
from "make" had a different hash than one constructed from a literal,
even though the two strings were lexicographically equivalent.

libutils: fix inconsistent hash in StaticString

---

filament/backend/src/vulkan/VulkanBlitter.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h
filament/backend/src/vulkan/VulkanPipelineCache.cpp
filament/backend/src/vulkan/VulkanPipelineCache.h
filament/backend/src/vulkan/VulkanSwapChain.cpp
filament/backend/src/vulkan/VulkanSwapChain.h

This optimizes our memory footprint and does some cleanup. 
There are no behavioral changes.
This PR is composed of 3 commits that should stay separate.

Vulkan: shrink PipelineKey from 608 bytes to 304 bytes, et al.

---

filament/backend/src/vulkan/VulkanMemory.cpp
filament/backend/src/vulkan/VulkanMemory.h

In the current version of the library, it looks like the DYNAMIC config macro has been replaced with a STATIC config macro.
Also disabled the "unused-private-field" warning when building this library.

Minor updates to how we include vk_mem_alloc.

---

filament/backend/src/vulkan/VulkanPipelineCache.cpp
filament/backend/src/vulkan/VulkanPipelineCache.h

When we added per-layout arenas for each of the 3 descriptor types, we did not
account for them when determining how much of the Vk Pool is in use.
Therefore the "growth" (really a re-creation) of the Vk Pool wasn't
always occurring when necessary, causing descriptor set allocation
to fail with large models.

Vulkan: fix logic that determines when to grow descriptor pool.

---

filament/src/details/Material.h
libs/matdbg/README.md
libs/matdbg/src/DebugServer.cpp
libs/matdbg/src/JsonWriter.cpp
libs/matdbg/web/script.js

The JSON response to /api/active became malformed after #4465 because
raw hex strings need to be enclosed by quotes.
This commit changes the variant format in the /api/materials response
to be consistent with one used for /api/active. By using integers
instead of strings, we're avoiding the need to parse integers at run
time.
The JSON error did not appear in the Chrome console because it was being
silenced as a hack to appease "matinfo --web-server". I fix this by
removing the hack and simply emitting a valid response when there's
no live backend.
Also fixed the display of materials, which were always being marked
as active even when they had no active variants.

matdbg: repair invalid JSON and display of active variants.

---

filament/src/details/Engine.cpp

This fixes "uninitialized texture" warnings from the Vulkan backend
when viewing Littlest Tokyo in a debug build.

Bring back initialization of DummyMorphTarget.

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/backend/TargetBufferInfo.h
filament/backend/src/opengl/GLUtils.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/ostream.cpp
filament/backend/test/test_Blit.cpp
filament/backend/test/test_MRT.cpp
filament/backend/test/test_ReadPixels.cpp
filament/src/PostProcessManager.cpp
filament/src/details/RenderTarget.cpp
filament/src/details/Texture.cpp

Instead of having 2 fields we're following the vulkan convention of
having only the layer field.
The layer/face convention is still maintained in the public APIs.
fixes #5273

fix TargetBufferInfo uses an union for the face (uint8_t) and layer (uint16_t)

---

filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/VulkanTexture.h

This fixes a validation warning, since not all depth textures are
necessarily used as depth attachments.

VulkanTexture: remove VkAspect state, derive it on the fly.

---

libs/bluevk/bluevk-gen.py

Two changes:
1) Khronos has moved from "master" to "main".
2) BlueVK was attempting to generate reasonable "operator<<" support for
bit flags but this was buggy due to type aliases. Since we weren't using
it anyway, I simply removed this functionality from BlueVK.

BlueVK: remove flaky operator<< for flags, update GitHub paths.

---

libs/gltfio/src/AssetLoader.cpp
libs/viewer/src/SimpleViewer.cpp

Morph weights can be zero even if the primitive has morph targets.
Fixes #5289

Retrieve morph target count from the primitive

---

filament/src/details/Engine.cpp
filament/src/details/Engine.h
filament/src/details/Renderer.cpp

we didn't need one per Renderer, and doing so created complexity in the
backends.
fixes #5291

create only a single "default render target"

---

android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentInstance.java
libs/gltfio/include/gltfio/Animator.h
libs/gltfio/include/gltfio/AssetLoader.h
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/include/gltfio/FilamentInstance.h
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FFilamentInstance.h
libs/gltfio/src/FilamentAsset.cpp
libs/gltfio/src/FilamentInstance.cpp
libs/gltfio/src/ResourceLoader.cpp
libs/viewer/src/SimpleViewer.cpp
samples/gltf_viewer.cpp

In the past there was an API gotcha because users had to "get" the
animator before releasing the glTF source data. This could have been
surprising because it was a getter method, not a factory method.
This was due to overeager optimization on my part, I wanted to avoid
animator overhead for non-animated models, when in fact it has very
little overhead.
Moreover, the animator is conceivably useful even when there are no
pre-supplied animations (e.g. for applying skins), so let's just create
it unconditionally.
Motivated by #5299.

gltfio: simplify API, make animator always available.

---

libs/viewer/src/SimpleViewer.cpp
web/filament-js/filament-viewer.js

This changes the WebGL and desktop glTF viewers so that they always
call `updateBoneMatrices`, even when there are 0 animations. Note
that our Android sample was already doing this correctly.
When combined with #5301, this fixes #5299, although users would need to
use the `recomputeBoundingBoxes` feature in gltfio (`-r` in the desktop
viewer) for this model to be scaled to fill the viewport, since its
embedded bounds are quite large.

Always apply bone matrices, even for non-animated models.

---

libs/filamat/src/shaders/CodeGenerator.cpp
shaders/CMakeLists.txt
shaders/src/attributes.vs
shaders/src/varyings.glsl

We now have a single varyings.glsl containing our varyings for both
the vertex and fragment shader. This file is included with the right
definition of VARYING as `in` or `out`.
inputs.vs is now renamed attributes.vs

cleanup attributes/varyings generation

---

filament/src/components/RenderableManager.cpp

Was checking for `MAX - 1` instead of `MAX`.
@dsternfeld7 since he had the original change in a prototype CL.
@daemyung and @pixelflinger for review.

Fix precondition for RenderableManager::setMorphWeights.

---

RELEASE_NOTES.md
android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
android/gltfio-android/src/main/cpp/AssetLoader.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/MaterialProvider.java

This is a Java-only gltfio API change (!)
Jave clients now need to call destroy on MaterialProvider.
Previously, the Java AssetLoader took ownership of the native
material provider upon construction, but this was neither documented
nor consistent with the C++ layer. (This is historical; in the past we
did not expose MaterialProvider to Java.)
One motivation for this (aside from API consistency) is that users may
wish to preserve the material cache from one run to another.
Fixes #5132.

gltfio: decouple MaterialProvider lifetime from AssetLoader.

---

filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanDriver.h
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanHandles.h

- Remove some special handling of the default render target lifetime that is no longer needed
- Rename "surface" to "swapChain" where it is appropriate to do so
- Remove some state from the VulkanDriver class

Vulkan: misc SwapChain-related cleanup. 

---

libs/utils/include/utils/JobSystem.h
libs/utils/src/JobSystem.cpp

We were decrementing activeJobCount after removing the job from the
queue, which could cause other threads in the pool to preempt us before
the decrement, causing them to spin forever trying to get a non-existant
job, until the decrement actually happened.
Now we always decrement first and fix-up the count if we couldn't get
a job from the queues. The race is inverted, and doesn't cause threads
to spin a long time.
fixes b/201100123

fix a race in jobsystem (2nd attempt)

---

RELEASE_NOTES.md
docs/Materials.md.html
filament/src/PerViewUniforms.cpp
filament/src/PerViewUniforms.h
filament/src/details/Material.cpp
filament/src/details/Renderer.cpp
filament/src/details/View.cpp
filament/src/details/View.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/UibGenerator.cpp
shaders/src/shading_lit.fs
shaders/src/shading_unlit.fs

The existing behavior was surprising for users who draw opaque objects
into a semitransparent views, and this was especially evident with
the labels in `TextureLinearInterpolationTest`.
We now disable blending for MASKED, which is what our existing materials
documentation already says. We also now set the fragment alpha to 1 when
the fragment is not discarded, which prevents the "punch through"
effect. This is consistent with ThreeJS.
Fixes #4576.

New behavior for BlendingMode::MASKED.

---

filament/src/details/Material.cpp
libs/filabridge/include/private/filament/SamplerBindingMap.h
libs/filabridge/src/SamplerBindingMap.cpp

The main simplification is that we don't need an actual map to retrieve
the global offset of a sampler, it can be easily calculated as:
global_offset = offset_of_the_block + local_offset

greatly simplify SamplerBinderMap

---

tools/zbloat/evmar_bloat.py
tools/zbloat/zbloat.py

The tool now works with Python 3 and handles binaries that have multiple
embedded material archives.  Example screenshot of good/bad minimaps is shown below.  Note how big `<stream>` is.  :P

Update the zbloat tool

---

filament/include/filament/FilamentAPI.h
filament/src/FilamentAPI-impl.h
libs/utils/CMakeLists.txt
libs/utils/include/utils/PrivateImplementation-impl.h
libs/utils/include/utils/PrivateImplementation.h
libs/utils/include/utils/ostream.h
libs/utils/include/utils/sstream.h
libs/utils/src/Log.cpp
libs/utils/src/ostream.cpp
libs/utils/src/ostream_.h

- move BuilderBase to libutils and rename to PrivateImplementation
- hide ostream implementation details into ostream.cpp
Fixes #5343

move BuilderBase to libutils and rename to PrivateImplementation

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/details/Engine.cpp
filament/src/details/Engine.h
filament/src/details/Renderer.cpp

This partially fixes the Metal crashes with SSR.

Fix, use zero texture array when SSR is off

---

third_party/etc2comp/EtcLib/EtcCodec/EtcBlock4x4Encoding_RGB8.cpp
third_party/etc2comp/tnt/README

Better fix is to replace etc2comp and astcenc with basis.

Temporary workaround for WebGL builds on macOS.

---

filament/include/filament/Frustum.h
filament/src/Frustum.cpp
filament/src/ShadowMap.cpp
filament/src/ShadowMap.h

Instead of recomputing the Frustum from its 8 vertices, we compute it
from the projection matrix directly. This ensures this works with any
projection matrix.  Building a Frustum object from 8 vertices required
these vertices to be given in a certain order which wasn't correct if
the projection was flipped for instance.
Removed the API to construct a Frustum from vertices.
fixes b/225975881

Fix shadow frustum computation wrt projection matrix

---

libs/filamat/CMakeLists.txt
third_party/glslang/SPIRV/tnt/CMakeLists.txt

This avoids a duplication of doc.cpp, the largest compilation unit
(about 650KiB).

remove SPVRemaper lib, fold it into glslang directly

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLProgram.cpp
filament/backend/src/opengl/OpenGLProgram.h

This reduces the size of OpenGLProgram from 64 to 32 bytes and
improves the code that sets new samplers.
The main simplification is that we're not trying to "pack" the 
texture units used in the program. For e.g. we could be using
units 0,3,4, where before it would be 0,1,2.
This allows us to do less tracking.
Another optimization is that we're discarding entirely a SamplerGroup 
if the program doesn't use any of its samplers. This helps remove
a test in updateSampler which in turn remove somem tracking data.

Simplify OpenGLProgram sampler bindings

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/OpenGLProgram.cpp

With this change, shaders are compiled at program creation, programs
are linked at the start of the next render pass and queries are
deferred until first use.
This should improve overall performance on some drivers.

batch all program linking at begin renderpass time

---

filament/src/details/MorphTargetBuffer.cpp

I noticed this bug while helping someone at Google understand our new morph API.

Fix 12x overallocation of memory in MorphTargetBuffer.

---

filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h
filament/src/fg/ResourceNode.cpp
filament/src/fg/details/ResourceNode.h

the crash would happen when forwarding a subresource of a subresource,
because in this case the parent's handle would be reset to the null
handle.

fix a framegraph crash when forwarding a subresource

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/details/Renderer.cpp
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h
filament/src/fg/ResourceNode.cpp
filament/src/fg/details/ResourceNode.h

unlike for refraction, the reflection buffer is distinct from "the"
color buffer, this allows an optimization (compared to ssr) when we
generate the mipmap chain -- we can allocate the mipmaped texture
and render the SSR pass directly into its level 0. This achieved
use the framegraph's forward resource feature.

avoid an extra copy during the screen-space reflection pass

---

filament/src/details/Engine.cpp
filament/src/details/Material.cpp
filament/src/details/Material.h

we add a checkProgramEdits() method that must be called periodically
on all materials. This is currently done at the beginning of a frame.

repair and optimize matdbg

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/details/Renderer.cpp
filament/src/details/Renderer.h
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h
filament/src/fg/FrameGraphPass.h
shaders/src/light_indirect.fs

With this change we are now generating refraction and reflections
buffer into their own layer of a 2D array -- so they can coexist.
This change doesn't actually enable both at the same time yet.
There are downsides to this approach:
- a 2d array of 2 layers is created even if only one of reflection or
refraction is active. This could be fixed at the cost of more
complexity.
- if reflections are active then refraction must use a RGBA16F texture
instead of RGB_11_11_10, because they share the texture

one more step towards reflection+refraction support

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/details/Renderer.cpp
filament/src/details/Renderer.h
filament/src/fg/FrameGraph.cpp
filament/src/fg/ResourceNode.cpp
filament/src/fg/details/ResourceNode.h
shaders/src/light_indirect.fs

Both "SSR" can now be used on the same material. This is made possible
by using a 2D array to store both buffers
.

enable both screen-space refraction and reflection

---

libs/filagui/src/ImGuiHelper.cpp

This is the fix for the same problem in rendering code as described in https://github.com/ocornut/imgui/issues/4863

Use index offset provided by ImGui when rendering UI

---

docs/webgl/demo_redball.html
docs/webgl/demo_suzanne.html
docs/webgl/demo_triangle.html
web/docs/demo_template.html
web/docs/tutorial_triangle.md

Some of our web samples were using unpkg to refer to the Filament build rather than using the local copy, which was inconsistent with the other web samples.
We now use the local copy of Filament for everything except the drag-and-drop viewer, which always uses the latest version of Filament.

Fix suzanne and redball live web demos.

---

third_party/basisu/tnt/CMakeLists.txt
third_party/basisu/tnt/README.md

We do not support these formats and they add bloat to the basis tables.
In a release x86 build, this reduces the transcoder size from 774 KiB to
475 KiB.
(This library is not yet used, stay tuned.)

Shrink BasisU transcoder.

---

libs/image/include/image/ColorTransform.h
libs/imageio/include/imageio/BlockCompression.h
libs/imageio/src/BlockCompression.cpp
samples/CMakeLists.txt
tools/mipgen/src/main.cpp

The `g_linearized` variable was being used for two purposes: to denote
the linearity of the source format AND the linearity of the destination
format. This was confusing and is now split is `sourceIsLinear` and
`destIsLinear`.
This change has no effect on the the look of the suzanne demo.

mipgen: fixups / clarification regarding sRGB.

---

libs/ktxreader/include/ktxreader/Ktx1Reader.h
libs/ktxreader/src/Ktx1Reader.cpp

When creating a KTX file (e.g. with mipgen), you can of course choose
whether or not you want to use an sRGB format.
At load time, your app has an expectation about whether a particular
texture has an sRGB format. e.g. the glTF convention is that albedo
textures should be sRGB, while roughness textures are linear.
Before this commit, our KTX loader would look at the app's expectation,
then silently re-interpret the bits in the glTF texture in order to
match this expectation. This seems very wrong.
Instead, if the expectated format does not match the format in the KTX
file, we now print a warning.
Fixes #2422, which will also be obsoleted by our upcoming KTX2 support.
Suzanne Demo Before / After:

Fix sRGB correctness in Ktx1Reader.

---

filament/backend/src/opengl/GLUtils.h
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
libs/utils/include/utils/ostream.h
libs/utils/src/ostream.cpp

- don't use __PRETTY_FUNCTION__ and try to parse it, __func__ is
standardized and in most case returns what we want (the function name).
- add native support for string_view in our ostream.
- uninline string support from ostream

string improvements

---

android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt

Path resolution was broken with #5285, which only fixed the case where the glTF happened to be at root level. This new fix has been tested against:
- Sponza zip file that has all files in a "sponza" folder.
- Bistro zip file that has resources in a child folder relative to the gltf file.
- A self-created flat zip using IridescentDishWithOlives, with everything at root level.
Side note: Bistro still fails on a Pixel 6 Pro Mali but for an unrelated reason: (null deref in `backend::TimerQueryNative::queryResultAvailable`)

sample-gltf-viewer: fix regression with zip files.

---

filament/src/details/Renderer.cpp
filament/src/details/Renderer.h
filament/src/fg/FrameGraph.cpp

This is only a good place for a flush *if* we're going to draw another
view (so the GPU can start working). Otherwise, it can be costly
on some drivers and unnecessary since swapbuffers will do the same.

don't issue a flush systematically after framegraph's execute

---

filament/src/Froxelizer.cpp
filament/src/Froxelizer.h
filament/src/PerViewUniforms.cpp
filament/src/PerViewUniforms.h
filament/src/PostProcessManager.cpp
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/ShadowMap.cpp
filament/src/ShadowMap.h
filament/src/ShadowMapManager.cpp
filament/src/ShadowMapManager.h
filament/src/details/Camera.cpp
filament/src/details/Camera.h
filament/src/details/Renderer.cpp
filament/src/details/View.cpp
filament/src/details/View.h

this state only exists during Renderer::render(), having it outside
of view is more flexible as it give us an opportunity to adjust
camera parameter globally before drawing.
Also greatly reduced the size of RenderPass (which is a Value object).

remove the CameraInfo state from FView

---

filament/src/Froxelizer.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/UibGenerator.cpp
shaders/src/light_punctual.fs

this is because this uniform is not well defined -- it's unclear if
it is set to the viewport or the buffer size.
also, it's not needed, and removes a couple multiplies from the shader.

don't rely on frameUniform.resolution for froxelization

---

filament/src/details/RenderTarget.cpp
filament/src/details/RenderTarget.h
filament/src/details/Renderer.cpp

we just store the "sampleable" attachments as a bitmask in 
RenderTarget instead of computing it each time.

Optimize custom rendertargets use in Renderer

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/OpenGLProgram.h
filament/backend/src/vulkan/VulkanPipelineCache.h
libs/filabridge/include/private/filament/EngineEnums.h

12 UBOs is the minspec in GLES3.0.  This in preparation of an upcoming change.

update binding points from 8 to 12.

---

libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/UibGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.h
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/iblprefilter/src/materials/generateKernel.mat
shaders/CMakeLists.txt
shaders/src/common_getters.glsl

post-process materials don't need common_shadowing nor common_shading.
also don't rely on MIN_ROUGHNESS in .mat files, because it's not public.

shrink post-process materials a bit

---

filament/backend/src/opengl/OpenGLContext.cpp

It was assumed that ETC2 is supported on all ES3 devices, but WebGL on
desktop machines does not support ETC2.
Note that WebGL has its own special extension strings for compressed
textures.

WebGL: fix isTextureFormatSupported for ETC2 formats.

---

RELEASE_NOTES.md
docs/Materials.md.html
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/details/Renderer.cpp
filament/src/details/Renderer.h
filament/src/details/View.cpp
filament/src/fsr.cpp
filament/src/fsr.h
filament/src/materials/antiAliasing/fxaa.mat
filament/src/materials/blitLow.mat
filament/src/materials/colorGrading/colorGrading.mat
filament/src/materials/fsr/fsr_easu.mat
filament/src/materials/fsr/fsr_easu_mobile.mat
filament/src/materials/fsr/fsr_easu_mobileF.mat

A "safe" mip-level is one that has exactly half the dimensions of
the current level. In other words, we guarantee that we can halve the
dimensions 4 times without loss (i.e. odd dimension).
This is achieved by effectively padding the viewport (i.e. making the
viewport's dimensions multiple of 16). The post-processing passes
eventually take care of cropping the extra padding so the final
image is unchanged.
This is a more generic solution to dynamic resolution padding, helps
with memory allocations and helps all the algorithms that depend on
mipmaping (e.g. DoF, SSAO, Bloom).
One important improvement brought by this change is that all "final"
post-processing effects are now able to handle a sub-region of the
source, including: color-gradding, fxaa and upscaling.

Ensure we always have 4 "safe" mip levels

---

filament/src/PostProcessManager.cpp
filament/src/ShadowMapManager.cpp

When there was more than one shadowmap we would hit an assert. This 
bug was introduced recently and was due to incorrect use of the 
framegraph.

repair VSM gaussian blur

---

libs/ktxreader/src/Ktx2Reader.cpp
third_party/basisu/tnt/CMakeLists.txt

This caused DXT5 content to be interpreted as DXT3 by the GPU,
which seemed to manifest as visual artifacts in the alpha channel.

Ktx2Reader: Fix error in enum translation table.

---

README.md
android/gltfio-android/CMakeLists.txt
android/gltfio-android/src/main/cpp/ResourceLoader.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/ResourceLoader.java
ios/samples/gltf-viewer/gltf-viewer/FILModelView.mm
libs/gltfio/CMakeLists.txt
libs/gltfio/include/gltfio/TextureProvider.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/Ktx2Provider.cpp
libs/gltfio/src/ResourceLoader.cpp
libs/gltfio/src/StbProvider.cpp
samples/gltf_viewer.cpp
web/filament-js/extensions.js
web/filament-js/filament-viewer.js
web/filament-js/jsbindings.cpp

This adds a new implementation of the TextureProvider interface called
Ktx2Provider.
Tested using the KTX2 variant of the StainedGlassLamp model in the
Khronos samples repo.
Tested on WebGL 2.0 (Chrome v100), Android (Pixel 6 Pro), and Desktop
(Metal, OpenGL, and Vulkan via MoltenVK).

Add support for KHR_texture_basisu.

---

filament/CMakeLists.txt
filament/src/RendererUtils.cpp
filament/src/RendererUtils.h
filament/src/details/Engine.cpp
filament/src/details/Renderer.cpp
filament/src/details/Renderer.h
libs/utils/include/utils/Allocator.h

The main changes are:
- ColorPass() and RefractionPass() are now static and moved into a 
new RendererUtils file. These methods don't need FRenderer and are 
more like a big "script".
- Cleaned-up includes
- Reformatted/reordered methods

Cleanup Renderer.cpp

---

android/gltfio-android/src/main/cpp/FilamentAsset.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp
libs/viewer/include/viewer/ViewerGui.h
libs/viewer/src/ViewerGui.cpp
samples/gltf_instances.cpp
samples/gltf_viewer.cpp
web/filament-js/extensions.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp
web/samples/helmet.html

- For completion, FilamentAsset now has getRenderableEntities(). This is
similar to sister methods getLightEntities() and getCameraEntities()
except there is no need to store a separate array.
- The web helmet demo does not need to enable shadows, they are already
enabled.
- The ViewerGui populateAsset() method was doing two things that are
now decoupled for clarity: setAsset() and populateAsset().
- The updateRootTransform() method is now called only when the autoscale
checkbox is toggled, instead of every frame.
- The getFooEntities() methods in Java now skip doing work for empty
lists. Actually these should not return arrays at all, but let's fix
that later, since it will break backwards compatibility.

Various glTF-related cleanup and enhancements.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/Renderer.cpp
android/filament-android/src/main/java/com/google/android/filament/Renderer.java
android/filament-android/src/main/java/com/google/android/filament/android/DisplayHelper.java
filament/include/filament/Renderer.h
filament/src/Renderer.cpp
filament/src/details/Renderer.cpp
filament/src/details/Renderer.h

Also deprecate some fields of DisplayInfo this shouldn't be a problem
because they were not actually used.
This change should allow an external-to-filament code to manage 
frame pacing (e.g. something like swappy).

Add presentation time to Renderer

---

filament/src/details/Renderer.cpp

we were not reseting the active region after passes that "resolve" the
guard bands, causing an extra blit to cause that resolving.

fix extra unnecessary blit

---

filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanUtility.cpp
filament/backend/test/test_Blit.cpp

This also removes clipping of the blit rectangle that occurred in the VK
backend that is no longer necessary. There's also no need to assert
since validation will catch out-of-bounds blitting.
Reverts the clipping in acdb8addfdb5c65072589caebf13193ac1d5d213.

Fix Vulkan y offset in blit + add backend tests.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/Options.h
filament/include/filament/View.h
filament/src/View.cpp
filament/src/details/Engine.h
filament/src/details/Renderer.cpp
filament/src/details/View.cpp
filament/src/details/View.h
libs/viewer/include/viewer/Settings.h
libs/viewer/src/AutomationSpec.cpp
libs/viewer/src/Settings.cpp
libs/viewer/src/ViewerGui.cpp
web/filament-js/extensions.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

When the guard band is enabled, the effective rendering area is
increased by a certain amount (currently 16 pixels on each side) so
that screen-space effects (e.g. SSAO, SSR, DoF) behave better around
the edges of the screen. Of course, this comes at a performance and
memory cost.
Currently the guard band is not configurable other than being optional.
Added c++, java and js bindings.

Implement an optional guard band for screen-space effects

---

filament/backend/CMakeLists.txt
filament/backend/include/backend/DriverEnums.h
filament/backend/src/opengl/GLUtils.h
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/test/BackendTest.cpp
filament/backend/test/BackendTest.h
filament/backend/test/test_StencilBuffer.cpp
filament/src/RenderPass.h

A first pass at implementing complete stencil buffer support. We still need to support other backends and a user-facing API.

Complete the OGL backend's stencil support and add test case

---

libs/gltfio/src/ResourceLoader.cpp

gltfio: use ifstream::binary for external resources

---

filament/src/details/Renderer.cpp
filament/src/details/Renderer.h
filament/src/fg/FrameGraph.cpp

This is a temporary workaround for a memory corruption issue observed on
some devices from a specific vendor. We will likely make this workaround
more targeted in the future.
Partial revert for b2cdf9f2b41ec732abd7bd56639b2c3c9316acc0.

Workaround: partially revert "don't issue a flush..."

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/details/Renderer.cpp
filament/src/fsr.cpp
filament/src/fsr.h

The FSR API documentation is a bit misleading, it expects offsets
with different origin depending on the backend API.
Also cleanup blitting passes:
We now have 3 public APIS:
- opaqueBlit() which is used for basic blitting and scaling and
supports sub-resources.
- blit() which is used for blitting + composition
- can optionally perform basic scaling
- doesn't support sub-resources
- upscale() which is used for high quality upscaling
- can do composition (blending)
- doesn't support sub-resources

fix FSR upscaling offset on metal/vulkan

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java

This makes Java match better with C++ and helps prepare for
autogenerated Java bindings.

Java minor API change: ssctStartTraceDistance => ssctShadowDistance

---

filament/include/filament/Options.h
tools/beamsplitter/README.md
tools/beamsplitter/java.go
tools/beamsplitter/java.template
tools/beamsplitter/javascript.go
tools/beamsplitter/javascript.template
tools/beamsplitter/main.go
tools/beamsplitter/parse/parse.go
tools/beamsplitter/serializer.go
tools/beamsplitter/serializer.template

Unlike our JavaScript bindings, our Java bindings (usually) reflect the nested nature of the C++ types that they expose.  This change makes beamsplitter more robust at handling namespace hierarchy.
e.g. the entries in the type database that it creates now has "parent" pointers.

beamsplitter: progress with Java codegen.

---

samples/materials/image.mat

Many EXR files may contain negative values, we don't want to output
those to our color buffer.

Fix image_viewer

---

filament/backend/include/private/backend/Program.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/OpenGLProgram.cpp

the shader source blob's size included the null terminating character,
which ended up being passed to the opengl/metal API.

fix trailing zero when setting shader sources

---

RELEASE_NOTES.md
android/filament-android/src/main/java/com/google/android/filament/View.java
tools/beamsplitter/README.md
tools/beamsplitter/java.go
tools/beamsplitter/java.template
tools/beamsplitter/javascript.go
tools/beamsplitter/javascript.template
tools/beamsplitter/parse/parse.go
web/filament-js/filament.d.ts

Note that JNI c++ functions still need to be manually maintained, as well as the setter / getter
methods.
Everything before the following codeline must be manually maintained:
```
// The remainder of this file is generated by beamsplitter
```

beamsplitter: use generated code for View.java

---

ios/samples/README.md
ios/samples/gltf-viewer/gltf-viewer/FILViewController.mm
libs/gltfio/src/ResourceLoader.cpp

Some textures would persist in the cache between calls to `loadResources`, but had since been destroyed. This caused a crash in the iOS gltf-viewer sample when reloading the model.
Fixes #5527

gltfio: Clear texture caches before loading resources

---

shaders/src/main.vs

When the material doesn't need TBN, Filament doesn't calculate morph target's normal. As a result, the geometry is changed but the geometry's normal is not changed while morphing. This PR fixes this issue and now calculating normals while morphing.

Fix not calculating the normal while morphing in the legacy path

---

RELEASE_NOTES.md
shaders/src/getters.vs
shaders/src/main.vs

Our `morphNormal` GLSL function treats each normal target as a displacement from the base normal. However the normal that is extracted from the tangent frame is actually an absolute normal, not a displacement vector.
In other words, if _b_ is the base normal, we were doing:
b = b + w0 * n0 + w1 * n1 + ...
This is obviously wrong, since the base normal has an overpowering influence.
The fixed math looks like this:
b = b + w0 * (n0 - b) + w1 * (n1 - b) + ...
Fixes #5584.

Fix morphed normals.

---

android/filament-android/src/main/java/com/google/android/filament/MorphTargetBuffer.java
filament/include/filament/MorphTargetBuffer.h

I think the most important thing here is that we now let users know that
"offset" is not a byte count.  This also fixes some small typos, e.g.
"weights" was used in the docstring instead of "positions".
To avoid making API changes, this does not fix a few weird things I
noticed in the Java API. For example, there is a redundant "count"
argument in methods that take an array.  Also some methods do not
provide an "offset" argument, which is not consistent with C++.

Morphing API docstring fixups.

---

libs/gltfio/include/gltfio/ResourceLoader.h
libs/gltfio/src/Animator.cpp
libs/gltfio/src/FFilamentInstance.h
libs/gltfio/src/ResourceLoader.cpp
samples/gltf_viewer.cpp

This optimizes and cleans up some code from a 3P contributor.
When computing a bounding box, there was no need for an inner loop
through the entire skins array.
Tested using the torus model in #4973 and the `-r` flag in gltf_viewer.

gltfio: Streamline the AABB + skinning computation.

---

RELEASE_NOTES.md
android/gltfio-android/src/main/cpp/FilamentAsset.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

Sceneform allowed users to attach and detach bones, so this seems like
a useful feature.
Fixes #3075

gltfio: add public attach / detach methods for bones

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/RenderableManager.cpp
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
filament/include/filament/RenderableManager.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/RenderPrimitive.h
filament/src/RenderableManager.cpp
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
web/filament-js/jsbindings.cpp

blendOrder was used to control the draw order of blended render
primitive within a Renderable. We now have an option to make the
blend order global, in this case those primitives with a global blend
order are always sorted solely using the blend order value (i.e. the 
distance from the camera is not take into account).

extend `blendOrder` functionality

---

filament/src/details/Engine.h

In practice on most systems this would only consume address space,
since most of those pages won't be accessed.
fixes #5608

fix overallocation by about 17MB

---

libs/gltfio/materials/sheen.mat.in

This makes ubershader mode more consistent with jit mode.
SheenChair and ToyCar in the samples repo both have opaque cloth.

gltfio ubershader mode: set sheen to OPAQUE.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/RenderableManager.cpp
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanDriver.h
filament/backend/test/TrianglePrimitive.cpp
filament/include/filament/RenderableManager.h
filament/src/RenderPrimitive.cpp
filament/src/RenderPrimitive.h
filament/src/RenderableManager.cpp
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
filament/src/details/Engine.cpp
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

To do this we have to remove the partial update version of `RenderableManager::setGeometryAt`, which is a **public API breakage**, however, the "full" version of `RenderableManager::setGeometryAt` can be used instead.

make HwRenderPrimitive immutable

---

RELEASE_NOTES.md
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/test/test_Blit.cpp

The Metal backend wasn't correctly handling the case where Filament would blit from a RenderTarget whose width & height were smaller than the backing Texture.
To test on non-M1 MacBooks, make the following change to Renderer.cpp:
```
-                input = ppm.colorGrading(fg, input, xvp,
+                input = ppm.colorGrading(fg, input, svp,
bloom, flare,
colorGrading, colorGradingConfig,
bloomOptions, vignetteOptions);
// the padded buffer is resolved now
-                xvp.left = xvp.bottom = 0;
-                svp = xvp;
```
then, disable all post-processing effects (but keep post-processing turned on), disable MSAA & SSAO, turn on dynamic resolution, and adjust the max scale slider.

Metal: fix blitting when render target is smaller than texture

---

.github/actions/verify-release-notes/Dockerfile
.github/actions/verify-release-notes/action.yml
.github/actions/verify-release-notes/verify_release_notes.py
.github/workflows/verify-release-notes.yml

This check will verify that all PRs henceforth modify RELEASE_NOTES.md. To bypass, apply the 'internal' label to your PR.
Note: the check will fail for this PR since it checks out the `.github/` path from main, so won't work until this PR is merged.

GitHub Actions: verify RELEASE_NOTES is updated for each PR

---

RELEASE_NOTES.md
libs/filamat/src/GLSLPostProcessor.cpp

Fixes #5614
This fixes the issue, though I still think this is a bug with spirv-cross / spirv-opt. We should be good to enable the "merge return pass" for Metal though.

Metal: fix invalid MSL generated due to missing optimization pass

---

filament/src/HwRenderPrimitiveFactory.h

a 64 bytes pool seems to work with both clang and msvc, unfortunately,
c++ doesn't let us know the allocator object size at compile time
for map containers, so we have to guess.

configure render primitive pool so it works with msvc

---

RELEASE_NOTES.md
filament/backend/src/opengl/OpenGLContext.cpp
filament/src/details/Renderer.cpp
filament/src/details/Renderer.h
filament/src/fg/FrameGraph.cpp

This reverts commit c049a1 and reenables commit b2cdf9:
"don't issue a flush systematically after framegraph's execute"

Revert "Workaround: partially revert "don't issue a flush..." (#5557)"

---

RELEASE_NOTES.md
filament/include/filament/RenderableManager.h
filament/include/filament/SkinningBuffer.h
filament/src/RenderPass.cpp
filament/src/components/RenderableManager.cpp
filament/src/details/Material.cpp
filament/src/details/SkinningBuffer.cpp
filament/src/details/SkinningBuffer.h
libs/filabridge/include/private/filament/EngineEnums.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/UibGenerator.cpp

- rename PerRenderableUibBones to PerRenderableBonesUib to be more
consistant with other interface block naming.
- make sure the C++ struct and the UBO definition match. 
PerRenderableBonesUib is a UBO with one bones[256] field, but the
C++ struct has a single bone and treated the UBO as an array.
This makes things less confusing.
We can now use sizeof(PerRenderableBonesUib) in many places which
better expresse what we are doing.
- Fix an off-by-one assert when setting a skinning buffer to a renderable
- Asserts that no more than 256 bones are associated to a renderable
- improve documentation and fix some typos

cleanup and fixes regarding skinning UBO

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalBuffer.h
filament/backend/src/metal/MetalBuffer.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/GLUtils.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/ostream.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/details/Scene.cpp
filament/src/details/View.cpp

Unsynchronized update just means that the buffer is updated regardless
if what the gpu is doing, the synchronization is the responsibility of
the caller.
Also added resetBufferObject(), which essentially destroys and reallocate
a buffer for the same handle.
With this change, per-renderable UBO updates are no longer using the
unsynchronized algorithm. We will reinstate this later.

backend: remove STREAM buffers and add Unsynchronized buffer update API

---

filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/ResourceAllocator.cpp
filament/src/fg/PassNode.cpp

Homogeneous attachments are a requirement for Metal (and possibly Vulkan) correctness. If rendering to a RenderTarget that has a smaller height than the underlying Texture, the Metal backend must set the Viewport to be the bottom-left of the texture, to match OGL. However, it can only do this correctly if all attachments have the same size.

Always use homogeneous attachment sizes

---

filament/src/RenderPass.cpp

a lot of primitive may use the same UBO slot, if they happen to be
in a sequence, we don't need to rebind the UBO.

small optimization that helps avoid bindUniformBufferRange calls

---

RELEASE_NOTES.md
libs/gltfio/src/Animator.cpp
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/GltfEnums.h
third_party/cgltf/README.md
third_party/cgltf/cgltf.h
third_party/cgltf/cgltf_write.h
third_party/cgltf/fuzz/data/BadBasisU.gltf
third_party/cgltf/fuzz/gltf.dict
third_party/cgltf/test/test_all.py
third_party/cgltf/tnt/README

Update cgltf, remove a morphing constraint.

---

RELEASE_NOTES.md
filament/backend/src/DataReshaper.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanUtility.cpp
filament/backend/src/vulkan/VulkanUtility.h

This fixes the OOB seen with picking.

Vulkan: fix ReadPixels with 2-component formats.

---

filament/backend/src/noop/NoopDriver.h

Problem: the `NoopDriver` always returns the same handle for RenderPrimitives (even if the buffers are different). This break's `HwRenderPrimitiveFactory`'s assumption that `createRenderPrimitive` will always be unique. What ends up happening is multiple `RenderPrimitive`s map to the same `HwRenderPrimitive`, which causes an assertion to fail upon a Google3 test termination.

NoopDriver: return unique handles

---

filament/backend/src/vulkan/VulkanDriver.cpp

This was occasionally useful for debugging specific problems, but it is
much too intrusive to enable in all debug builds.

Vk: do not raise SIGINT for validation errors.

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp

This lets us avoid the following validation error.
Attempting to create a VkDevice from a VkPhysicalDevice which is
from a portability driver without the
VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR bit in the
VkInstanceCreateInfo flags being set...

Vk: set ENUMERATE_PORTABILITY_BIT for MoltenVK.

---

filament/backend/src/vulkan/VulkanBuffer.cpp
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanStagePool.cpp

Now that we've updated vkmemalloc, the "poor allocator performance" workaround (#4128) is no longer necessary. Removing this fixes #5432.

Vk: remove slow allocations workaround.

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

Now that all RenderTarget attachments are the same size, we can correctly compute the viewport for render passes.

Metal: correctly compute viewport

---

libs/filagui/src/ImGuiHelper.cpp

If the font path is the directory then it's undefined behavior.

Check the font path is the file

---

RELEASE_NOTES.md
libs/filagui/include/filagui/ImGuiHelper.h
libs/filagui/src/ImGuiHelper.cpp

Reflects a change from Betty and should be cherry picked to v1.23.3
Users could customize the ImGuiHelper camera, but they had no control
over the scissor coordinates. This allows them to use vertically flipped
coordinates, which, unfortunately, is required for MediaPipe
integration.

ImGuiHelper: add support for Y flip.

---

RELEASE_NOTES.md
libs/gltfio/CMakeLists.txt
tools/matc/src/matc/CommandlineConfig.cpp
tools/matc/src/matc/CommandlineConfig.h
tools/matc/src/matc/Config.h
tools/matc/src/matc/MaterialCompiler.cpp

This makes it easier to generate ubershaders without the fancy CMake machinery available in its `configure_file` command.

matc: add --template option.

---

filament/src/MaterialParser.cpp

If `ChunkContainer::parse` failed, then `MaterialParser::parse` was returning SUCCESS.

Fix swallowed errors in MaterialParser.

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/Camera.cpp
android/filament-android/src/main/java/com/google/android/filament/Camera.java
filament/include/filament/Camera.h
filament/include/filament/Frustum.h
filament/src/Camera.cpp
filament/src/Frustum.cpp
filament/src/ShadowMapManager.cpp
filament/src/details/Camera.cpp
filament/src/details/Camera.h
libs/math/include/math/mat4.h
samples/rendertarget.cpp

- getNear() and getCullingFar() now return doubles
- updated documentation
- all setProjection() calls can now throw (when enabled) and will
do so if preconditions are not met (instead of setting a default
projection).
- Frustum can now be logged on debug builds

Camera API and documentation improvements

---

RELEASE_NOTES.md
filament/src/Renderer.cpp
filament/src/details/Renderer.h

`Renderer::getUserTime()` now returns seconds as documented

---

libs/filamat/src/eiff/BlobDictionary.cpp
libs/filamat/src/eiff/BlobDictionary.h
libs/filamat/src/eiff/DictionarySpirvChunk.cpp
libs/filamat/src/eiff/DictionaryTextChunk.cpp
libs/filamat/src/eiff/LineDictionary.cpp
libs/filamat/src/eiff/LineDictionary.h
libs/filamat/src/eiff/MaterialTextChunk.cpp
libs/filamat/src/eiff/MaterialTextChunk.h

BlobDictionary and LineDictionary were storing blobs as map keys to achieve simple compression, but they also stored duplicates in a vector for index-based lookup.
Now, the vector is storage and the map has keys that are string_view.

filamat: dictionaries now store each blob once, not twice. 

---

filament/include/filament/Engine.h
filament/src/Froxelizer.cpp
filament/src/Froxelizer.h
filament/src/details/Engine.cpp
filament/src/details/Engine.h
filament/src/details/IndirectLight.cpp

- add configuration for irradiance map to Config
(currently, still unused)
- move all froxel configuration constants out of Engine.h, unlike
the previous todo/comment, these shouldn't be part of Engine::Config.

more Engine configuration cleanup

---

filament/backend/src/metal/MetalBuffer.h
filament/backend/src/metal/MetalBuffer.mm
filament/backend/src/metal/MetalBufferPool.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/test/BackendTest.cpp
filament/backend/test/BackendTest.h
filament/backend/test/TrianglePrimitive.cpp
filament/backend/test/TrianglePrimitive.h
filament/backend/test/test_BufferUpdates.cpp

This PR changes how Metal handles buffer updates. Previously, Metal allocated a full new buffer each time an `updateBufferObject` command was issued; however, it did not copy the previous contents of the buffer over to the new buffer, so partial updates did not work correctly.
Now, Metal allocates a single, private GPU buffer and employs temporary staging buffers whose contents get blitted to the private buffer at each update.
There's still some room for optimizations, and I need to give more thought to how I want to implement `updateBufferObjectUnsynchronized`.

Use staging buffers to implement Metal buffer updates

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/Texture.cpp
android/filament-android/src/main/java/com/google/android/filament/Texture.java
filament/backend/include/backend/DriverEnums.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/ostream.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/VulkanTexture.h
filament/backend/test/test_Blit.cpp
filament/backend/test/test_FeedbackLoops.cpp
filament/backend/test/test_LoadImage.cpp
filament/include/filament/Texture.h
filament/src/Froxelizer.cpp
filament/src/PostProcessManager.cpp
filament/src/Texture.cpp
filament/src/details/Engine.cpp
filament/src/details/Engine.h
filament/src/details/Texture.cpp
filament/src/details/Texture.h
libs/filamentapp/include/filamentapp/IBL.h
libs/filamentapp/src/IBL.cpp
libs/ktxreader/src/Ktx1Reader.cpp

The main goal is to allow more flexibility, allow cubemap arrays in 
the future and better match vk and metal apis.
Main changes:
- remove updateCubeImage
- remove update2DImage
- update3DImage is now the only texture upload backend API
cubemaps are now treated just like a 2D array of 6 layers.
For this reason, Texture::setImage(..., FaceOFfsets) is deprecated.
Additionally, the 2D versions of Texture::setImage() become inline
helpers.
A side effect of this change is that it is now possible to update only
a single face of a cubemap, but also a region of a face (or faces).

rework backend texture upload APIs

---

filament/src/details/Texture.cpp
filament/src/details/Texture.h

the depth of the texture wasn't taken into account. In practice this
would restrict the number of mip levels of a 3d texture that would have
a larger dimension in depth.

fix max mipmap levels calculation for 3D textures

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/metal/MetalEnums.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/gl_headers.h
filament/backend/src/ostream.cpp
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/VulkanUtility.cpp
filament/backend/test/test_LoadImage.cpp
filament/src/details/Texture.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/matdbg/src/CommonWriter.h

This is not intended to be used yet because we're not currently
checking that cubemap array are actually supported, however, if they
are, they should work.

Add support for cubemap arrays in the backends

---

BUILDING.md
RELEASE_NOTES.md
build/web/ci-common.sh
web/filament-js/jsbindings.cpp

Starting with 3.1.14, embind started to support for `noexcept`
which caused multiple definition errors since we have a workaround
in place that alreadys supplies template instantiations for `noexcept`.
This change should not affect G3 since our JS bindings are not used
in G3.
The upstream fix is here:
https://github.com/emscripten-core/emscripten/pull/17140
Fixes #5789.

Upgrade to emscripten 3.1.15 and remove workaround.

---

filament/backend/CMakeLists.txt
filament/backend/include/backend/SamplerDescriptor.h
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/include/private/backend/SamplerGroup.h
filament/backend/src/DriverBase.h
filament/backend/src/SamplerGroup.cpp
filament/backend/src/metal/MetalDriver.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/OpenGLProgram.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanHandles.h
filament/backend/test/test_FeedbackLoops.cpp
filament/backend/test/test_LoadImage.cpp
filament/backend/test/test_RenderExternalImage.cpp
filament/src/PerViewUniforms.cpp
filament/src/details/MaterialInstance.cpp
filament/src/details/MorphTargetBuffer.cpp

reviewers: it'll be much easier to review each CL separately.
The main changes are:
- updateSamplerGroup() now uses a BufferDescriptor
- SamplerGroup is "almost" a filament-only API. It's still in the backend right now because metal/vk still use it.
`SamplerGroup` was supposed to be just a helper to set/create/manager a set of samplers, while HwSamplerGroup was the backend object. However, the later used to "own" a `SamplerGroup` which was confusing and just bad design.
In the GL backend we now take advantage of the HwSamplerGroup abstraction by resolving the sampler (i.e. creating a GL sampler object) when the data changes, rather than each time when setting a program.

many improvements around sampler groups

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLProgram.cpp
filament/backend/src/ostream.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/details/Material.cpp
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/sca/GLSLTools.cpp
libs/filamat/src/sca/GLSLTools.h
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/matdbg/src/CommonWriter.h

GL_ES_30   becomes MOBILE
GL_CORE_41 becomes DESKTOP
ShaderModel controls which flavor of GLSL (GL or ES) is used both when 
reading and outputting materials.
It's also used to set default quality settings and the default precision
of all fragment shaders.
Technically, Vulkan and Metal don't need this distinction, but the GL
backend does.

rename `ShaderModel` enums

---

filament/backend/src/opengl/OpenGLDriver.cpp
web/samples/suzanne.html

The issue was that WebGL2.0 doesn't support texture swizzle.
Fixes: #5828

Fix DoF on WebGL

---

RELEASE_NOTES.md
filament/src/components/TransformManager.cpp

When FTransformManager computes accurate world transforms, it adds downcasted leftover to translation part to restore precision.
However, both translation and leftover are given as float3 - simply adding them resut float3, so addling leftover become meaningless.
one or both should be upcasted first.

Fix incorrect precision restoration when computing accurate world translations

---

RELEASE_NOTES.md
filament/include/filament/MaterialInstance.h
filament/src/MaterialInstance.cpp
filament/src/details/Material.cpp
filament/src/details/MaterialInstance.cpp
filament/src/details/MaterialInstance.h
libs/filabridge/include/private/filament/SamplerInterfaceBlock.h
libs/filabridge/include/private/filament/UniformInterfaceBlock.h
libs/filabridge/src/SamplerInterfaceBlock.cpp
libs/filabridge/src/UniformInterfaceBlock.cpp

Internally we use std::string_view and the public API is augmented
with APIs that take a length for strings, which makes them useable
with string_view parameters.
Also fix exception specification for all setParameter methods, which
can throw if exceptions are enabled (or exit the program otherwise).

MaterialInstance public API friendly to std::string_view

---

CODE_STYLE.md
filament/backend/include/private/backend/Program.h
filament/backend/src/Program.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/test/test_Blit.cpp
filament/backend/test/test_BufferUpdates.cpp
filament/backend/test/test_FeedbackLoops.cpp
filament/src/MaterialParser.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/details/DebugRegistry.cpp
filament/src/details/DebugRegistry.h
filament/src/details/Material.cpp
filament/src/details/Material.h
filament/src/fg/Blackboard.cpp
filament/src/fg/Blackboard.h
filament/src/fg/ResourceNode.cpp
libs/filabridge/include/private/filament/SamplerInterfaceBlock.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filabridge/include/private/filament/UniformInterfaceBlock.h
libs/filabridge/src/SamplerInterfaceBlock.cpp
libs/filabridge/src/UniformInterfaceBlock.cpp
libs/filamat/src/MaterialBuilder.cpp
libs/image/src/ImageSampler.cpp
libs/matdbg/src/DebugServer.cpp
libs/utils/include/utils/CString.h
libs/utils/src/CString.cpp
libs/utils/test/test_CString.cpp

In most places this is simply replaced by `std::string_view`.
We also change a few internal/private headers so they accept 
`std::string_view` instead of `utils::CString`.

get rid of `utils::StaticString`

---

filament/include/filament/Camera.h
filament/src/RendererUtils.cpp
filament/src/components/RenderableManager.cpp
filament/src/details/IndirectLight.cpp
filament/src/details/Material.cpp
filament/src/details/RenderTarget.cpp
filament/src/details/Skybox.cpp
filament/src/details/Texture.cpp
filament/src/details/VertexBuffer.cpp
filament/src/fg/FrameGraph.cpp
filament/src/fg/FrameGraph.h
filament/src/fg/Resource.cpp
filament/src/fg/details/Resource.h

We used to have a mix of fatal and non-fatal assertions for precondtions
errors. From now on, we always throw if exceptions are enabled or 
crash with a log otherwise.

make all public API pre-condition violation fatal

---

filament/include/filament/Camera.h
filament/src/Camera.cpp
filament/src/details/Camera.cpp
filament/src/details/Camera.h

This was already mostly the case, but we had two stray APIs that were still `float3` at the public API level, but were already `double3` internally.

make all camera APIs double

---

filament/backend/include/backend/DriverEnums.h
filament/backend/include/backend/PipelineState.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalEnums.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/test/test_StencilBuffer.cpp

This allows us to grow the stencil state without having to pack additional bits into `RasterState`. In a separate PR I'll add support for separate front/back stencil states and masking.

Move stencil state out of RasterState

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp

`Texture::isTextureFormatSupported` always returned `true` for ASTC, it
now queries the hardware as expected.
Fixes #5872

Return support for ASTC formats properly.

---

libs/utils/include/utils/SingleInstanceComponentManager.h
libs/utils/include/utils/StructureOfArrays.h

StructureOfArray always aligned each array to the same alignment as
malloc (usually 8 bytes), but that was not enough if one of its type 
has stricter alignment requirements. 
StructureOfArray now always honors at least the alignment requirement
of each array.
Also removed dependency on EntityInstance.h
Fixes #5727

Fix StructureOfArray alignments

---

filament/src/ShadowMapManager.cpp

It was culled by the frame-graph because it didn't have "read" from 
any of its resource, only writes. However, it does set uniforms, so need
to be called.
fix #5874

The "Prepare Shadow Pass" was never executed

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalState.h
filament/backend/src/metal/MetalState.mm
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/test/test_StencilBuffer.cpp

Separate out stencil operations for back/front facing primitives and add read/write masks.

Add additional state to StencilState

---

filament/include/filament/Renderer.h
filament/include/filament/Texture.h
filament/src/details/Texture.h

Renderer and Texture headers use the Attribute Specifier Sequence syntax instead of the UTILS_DEPRECATED macro which could cause issues when interfacing with compilers without support for this syntax. 
This merge request simply changes any occurrence of [[deprecated]] in the headers to UTILS_DEPRECATED

Ensure UTILS_DEPRECATED is used in the public API

---

RELEASE_NOTES.md
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp
libs/gltfio/src/ResourceLoader.cpp

These new methods allow gltfio to be integrated into internal Google
libraries.

gltfio: add 'detach' methods to allow ownership transfer

---

RELEASE_NOTES.md
libs/gltfio/src/ResourceLoader.cpp

Earlier versions of cgltf did not support file reader customization.
This was fixed back in Dec 2019 but at the time I did not notice, so
we never bothered cleaning up our usage.
In the future we would like WebGL + Android builds to permit texture
downloads to occur concurrently with the texture decoder jobs. This PR
is basically a preparatory refactoring, but with the nice side effect of
removing a memcpy.

gltfio: remove a memcpy via custom cgltf_file_options.

---

RELEASE_NOTES.md
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/ResourceLoader.cpp
web/filament-js/extensions.js
web/samples/helmet.html

This feature can improve load time when textures are downloaded from the
web on non-filesystem platforms like Android.
More specifically, this allows downloaded texture assets to arrive after
the user calls asyncBeginLoad(), which means that decoding and
downloading can occur concurrently.
Prior to this PR, we already used JobSystem for decoding, but we did not
kick off any jobs until after all assets were downloaded.
Still TBD: add this feature for external vertex data.
Partial fix for #5909.

gltfio: concurrent texture downloading and decoding.

---

libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/ResourceLoader.cpp

The custom release callback that I provided was in the wrong place; it
was only being used for a path string, not the actual buffer content.
The cgltf API is a bit awkward in this area.
No need to update RELEASE_NOTES because this will be cherry picked to
the RC branch, which is where the bug introduced.
Fixes #5918.

gltfio Android: Fix double free error.

---

RELEASE_NOTES.md
libs/filabridge/include/private/filament/EngineEnums.h
libs/filabridge/include/private/filament/UibStructs.h

Developers who know their users have powerful devices may wish to exceed ES3.0
minspec constraints to allow more bones and / or morph targets.
Fixes #5785.

Add CONFIG_MINSPEC_UBO_SIZE and fix comment.

---

filament/backend/src/SamplerGroup.cpp

Similar to https://github.com/google/filament/pull/4363, we must avoid comparing texture handles. This manifested as a bug when running with the Metal backend.
Fixes https://github.com/google/filament/issues/5897

Fix SamplerGroup update issue

---

libs/utils/include/utils/Condition.h
libs/utils/include/utils/Mutex.h

For other linux distributions we use the generic C++ ones. I think this
is probably safer and more friendly to non-linux unixes.
Fixes #2861

use our custom mutex/condition only on ANDROID

---

RELEASE_NOTES.md
docs/Materials.md.html
filament/src/PerViewUniforms.cpp
filament/src/PostProcessManager.cpp
filament/src/details/Camera.h
filament/src/details/Renderer.cpp
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/UibGenerator.cpp
libs/filamat/src/shaders/MaterialInfo.h
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/main.vs
shaders/src/material_inputs.vs
tools/matc/src/matc/ParametersProcessor.cpp

With VERTEX_DOMAIN_DEVICE the vertex shader doesn't apply the 
projection (since the vertices are already in clip space), however,
both TAA and guard bands need to jitter/offset the clip space, and
it is done at the projection level.
We now store the clip space offset separately so that it can be applied
to VERTEX_DOMAIN_DEVICE vertices.
Fixes #5917

Fix guard bands and TAA with VERTEX_DOMAIN_DEVICE

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalEnums.h
filament/include/filament/Renderer.h
filament/include/filament/View.h
filament/src/RendererUtils.cpp
filament/src/RendererUtils.h
filament/src/View.cpp
filament/src/details/Renderer.cpp
filament/src/details/View.h

Will update RELEASE_NOTES when the Material API is added, otherwise at the moment there's no way to use the stencil buffer.

Add View API to enable the stencil buffer

---

third_party/glslang/glslang/OSDependent/Unix/CMakeLists.txt
third_party/glslang/glslang/OSDependent/Windows/CMakeLists.txt

Apologies for the repeat PR after https://github.com/google/filament/pull/5934; I accidentally undid one-too-many folder additions in https://github.com/google/filament/pull/5934/commits/4f8e3ed4449ab7342540b6bcc5908a31629296d6 which left the `glslang/OSDependent` subproject as the sole sub-project not sorted into a folder.   This should fix that.

Add glslang/OSDependent to ThirdParty folder

---

RELEASE_NOTES.md
android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
android/gltfio-android/src/main/cpp/AssetLoader.cpp
android/gltfio-android/src/main/cpp/FilamentAsset.cpp
android/gltfio-android/src/main/cpp/FilamentInstance.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/AssetLoader.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentInstance.java
ios/samples/gltf-viewer/gltf-viewer/FILModelView.mm
ios/samples/hello-gltf/hello-gltf/FilamentView/App.cpp
libs/gltfio/include/gltfio/Animator.h
libs/gltfio/include/gltfio/AssetLoader.h
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/include/gltfio/FilamentInstance.h
libs/gltfio/src/Animator.cpp
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FFilamentInstance.h
libs/gltfio/src/FilamentAsset.cpp
libs/gltfio/src/FilamentInstance.cpp
libs/gltfio/src/ResourceLoader.cpp
samples/gltf_instances.cpp
samples/gltf_viewer.cpp
web/filament-js/extensions.js
web/filament-js/filament-viewer.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp
web/samples/animation.html
web/samples/helmet.html
web/samples/morphing.html

This change was motivated by some internal work at Google and has the benefit of simplifying the gltfio API and
implementation. There are 2 major API changes:
(1) Consolidate separate loader entry points for GLB and GLTF.
The distinction between GLB and GLTF can be made from the file content alone, because GLB has a 4-byte magic string in its header. There is no need for separate entry points.  Clients do not (and should not) need to check the file name extension.
(2) Remove the distinction between "instanced" and "non-instanced" glTF assets.
In the new scheme, all assets have at least 1 instance.
Broadly speaking, in gltfio an "asset" is a collection of Filament objects like textures and vertex buffers, while an "instance" is a collection of entities and components (e.g. the transform …

gltfio API change: assets are now always 'instanced' etc

---

filament/backend/src/opengl/OpenGLProgram.cpp
libs/filabridge/src/SibGenerator.cpp
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.h

- remove unused SamplerBindingMap parameter 
In fact, the SamplerBindingMap is used, but it is passed inside the
MaterialInfo structure, so it doesn't need to be passed as parameter.
- Don't create unneeded SamplerBindingMap temporaries

cleanup SamplerBindingMap usages

---

libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FilamentAsset.cpp

Adding this getter lets us remove some duplicated state from an
internal client at Google.

gltfio: add ownership query

---

filament/backend/include/backend/Program.h
filament/backend/src/Program.cpp
filament/backend/test/ShaderGenerator.cpp
filament/backend/test/ShaderGenerator.h
filament/src/details/Material.cpp

partially revert a recent change where Program needs a DriverApi in its
ctor. This was a misguided change. Backend API never take a DriverApi
as parameter.
Checking the feature level, for instance, should happen as a 
precondition, or in the backend as postcondition.

It was a mistake to change Program's ctor

---

libs/filamentapp/src/FilamentApp.cpp

This is a simple PR that changes FilamentApp to delay its rendering to be roughly in line with the monitor framerate.
This helps all the samples look temporally smooth on higher refresh rate monitors, while still leaving it clear how to decouple rendering from vsync for new programmers.
Alternative techniques (with finer than 1ms granularity) like using `SDL_GL_SetSwapInterval` or `SDL_RENDERER_PRESENTVSYNC` might be preferable, but I'm still too new to SDL to figure out how to integrate them.    Even with integer milliseconds, the beat-frequency (rate of frame stutters) will never exceed ~1hz~ 0.5hz, so the incremental improvement will be minimal.

Set Frame Delay according to Monitor Refresh Rate
