google/filament

RELEASE_NOTES.md
android/filament-android/src/main/cpp/MaterialInstance.cpp
android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java
filament/include/filament/MaterialInstance.h
filament/src/Engine.cpp
filament/src/Material.cpp
filament/src/MaterialInstance.cpp
filament/src/details/Engine.h
filament/src/details/MaterialInstance.h

It's now possible to duplicate a MaterialInstance.

added MaterialInstance::duplicate(...)

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h

fix MRTs >= COLOR4 in the GL backend

---

filament/backend/src/vulkan/PlatformVkAndroid.cpp
filament/backend/src/vulkan/PlatformVkCocoa.mm
filament/backend/src/vulkan/PlatformVkWindows.cpp
filament/backend/src/vulkan/VulkanBlitter.cpp
filament/backend/src/vulkan/VulkanCommands.cpp
filament/backend/src/vulkan/VulkanCommands.h
filament/backend/src/vulkan/VulkanConstants.h
filament/backend/src/vulkan/VulkanDriver.cpp

Also fix some warnings seen with MSVC.

 Vk: emit best practices warnings when validation is enabled.

---

libs/image/include/image/KtxUtility.h

image: Respect sRGB option for compressed formats

---

android/filament-android/src/main/java/com/google/android/filament/RenderTarget.java
filament/backend/include/backend/TargetBufferInfo.h
filament/include/filament/RenderTarget.h
filament/src/RenderTarget.cpp
samples/rendertarget.cpp

AttachmentPoint in java and c++ mismatch

---

filament/src/components/LightManager.cpp
filament/src/components/LightManager.h

fix LightManager::getFalloff

---

filament/src/Scene.cpp
filament/src/ShadowMap.cpp
filament/src/View.cpp
libs/utils/include/utils/JobSystem.h
libs/utils/src/JobSystem.cpp

Tweak how we signal/wakeup threads so we get better parallelism 
on Android.

Better systrace logging and small improvements to JobSystem

---

filament/backend/src/opengl/OpenGLContext.cpp
libs/utils/include/utils/Log.h
libs/utils/include/utils/ostream.h
libs/utils/src/Log.cpp
libs/utils/src/ostream.cpp

- cleanuo Log header file
- lazy initialization of the log buffer
- aggressively resize down the log buffer

bring some improvements to logging from a reverted change

---

libs/utils/CMakeLists.txt
libs/utils/include/utils/Systrace.h
libs/utils/src/Systrace.cpp

Use the official systrace API when available.

Systrace now uses the official ATrace API

---

web/filament-js/filament.d.ts
web/filament-js/jsenums.cpp

Fix BindingType in TypeScript definitions.

---

filament/backend/src/CommandBufferQueue.cpp
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/TimerQuery.cpp
filament/backend/src/vulkan/VulkanCommands.cpp
filament/src/Engine.cpp
filament/src/Fence.cpp
filament/src/Froxelizer.cpp
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/View.cpp
filament/src/details/Engine.h
libs/ibl/src/CubemapUtilsImpl.h
libs/utils/benchmark/benchmark_JobSystem.cpp
libs/utils/include/utils/JobSystem.h
libs/utils/src/CountDownLatch.cpp
libs/utils/src/CyclicBarrier.cpp
libs/utils/src/EntityManagerImpl.h
libs/utils/src/JobSystem.cpp
libs/utils/test/test_JobSystem.cpp

These improvement are based on analyzing systraces of scenes we many objects which should benefit from the JobSystem.
This changes attempts to reduce the overhead of running/finishing jobs, but also to increase significantly the size of jobs. A good rule of thumb is that running a job as an overhead of 50-100us, so the job itself should be much larger than that to see some benefit.
Also removed "optimizations" that didn't work well and made the code more complicated.

Several improvements to the JobSystem

---

.github/workflows/release.yml
build.sh
build/android/build.sh

This builds, signs, and uploads sample-gltf-viewer with releases.

Include sample-gltf-viewer with Android releases

---

web/filament-js/extensions.js

JS bindings: remove bogus stride argument.

---

android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt

More precisely, this logs the time that the Filament backend takes
to process all the commands that were issued in the gltfio synchronous
loading phase, which mostly consists of creating and populating vertex
buffers.
This can be quite slow for vertex-heavy (CAD-style) models, and seems to
vary by several orders of magnitude from device to device on Vulkan.

sample-gltf-viewer: log the load time (useful for large models)

---

RELEASE_NOTES.md
android/filament-android/src/main/cpp/LightManager.cpp
android/filament-android/src/main/java/com/google/android/filament/LightManager.java
filament/include/filament/LightManager.h
filament/src/Material.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/ShadowMap.cpp
filament/src/ShadowMapManager.cpp
filament/src/View.cpp
filament/src/components/LightManager.cpp
filament/src/components/LightManager.h
filament/src/details/Engine.h
filament/src/details/ShadowMapManager.h
libs/filabridge/include/private/filament/UniformInterfaceBlock.h
libs/filabridge/src/UniformInterfaceBlock.cpp
libs/viewer/src/Settings.cpp
libs/viewer/src/SimpleViewer.cpp
samples/material_sandbox.cpp

This is still somewhat work-in-progress, but good enough to be useful.
Some caveats:
- large blurs don't work well with cascades
- the implementation uses more memory than it could

Implement blurring of VSM shadow maps

---

filament/backend/src/Platform.cpp

we need to select opengl on webgl.

fix webgl build

---

filament/src/materials/separableGaussianBlur.mat

This is to acomodate hdr and evsm blurring.

The gaussian blur running sum must be in highp

---

android/filament-android/src/main/java/com/google/android/filament/RenderTarget.java

Fix out of bounds access in java bindings

---

shaders/src/shadowing.fs

mediump is not enough for sampling positions.

PCF shadows need some math in highp

---

android/filament-utils-android/src/main/cpp/AutomationEngine.cpp
android/filament-utils-android/src/main/java/com/google/android/filament/utils/AutomationEngine.java
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
ios/samples/gltf-viewer/gltf-viewer/FILViewController.mm
libs/viewer/include/viewer/AutomationEngine.h
libs/viewer/include/viewer/Settings.h
libs/viewer/src/AutomationEngine.cpp
libs/viewer/src/Settings.cpp
libs/viewer/src/SimpleViewer.cpp
samples/gltf_viewer.cpp

Settings UI: LightManager ShadowOptions now affect all lights.

---

filament/backend/test/test_ReadPixels.cpp

Add simple ReadPixels performance test.
This simply lets the gtest framework report the total test time, which includes startup and teardown.  However we perform 100 runs of the render+readback code to reduce the run-to-run variance. For 100 runs of a 2000x2000 buffer, I see the following results on my mac (total time for all 100 runs):
- Vulkan: 1881 ms
- Metal: 1625 ms
- OpenGL: 978 ms
The test can be built & invoked like this:
```
./build.sh release backend_test_mac && \
./out/cmake-release/filament/backend/backend_test_mac -a opengl --gtest_filter="*ReadPixelsPerformance"
```
See also issue #4246.

Add simple ReadPixels performance test.

---

filament/backend/src/opengl/OpenGLProgram.cpp
filament/include/filament/Stream.h
filament/include/filament/Texture.h

enforce CLAMP_TO_EDGE for external textures

---

filament/src/Renderer.cpp
libs/viewer/src/SimpleViewer.cpp

There was no good reason not allow this.
Fixes #2533

Allow MSAA when post-processing is disabled

---

libs/filamat/src/UibGenerator.cpp
shaders/src/common_getters.fs
shaders/src/shading_lit.fs
shaders/src/shading_unlit.fs

Work around Qualcomm issue with point lights.

---

libs/gltfio/materials/sheen.mat.in
libs/gltfio/materials/transmission.mat.in
libs/gltfio/materials/ubershader.mat.in
libs/gltfio/src/MaterialGenerator.cpp

Fixes #4253 but also requires #4287 in order to work.

gltfio: fix precision in KHR_texture_transform

---

samples/image_viewer.cpp
samples/materials/image.mat

Image loading errors are handled more gracefully by showing a
background color.
Added UI to set the background color.
Replaced fragment discards with solid background color.

Improvements to image_viewer

---

filament/src/Renderer.cpp

What was happening is that we were doing two blits at the end of the
frame instead of one, those blits are setup so that they only work
when the destination is the an imported target (it doesn't have to be
this way, but currently that's the only case we should have). Because
of the 2nd blit, the first one's destination would not be the
imported target and it would fail.
The real problem is that we shouldn't be doing two blits, just one
is enough. That was happening because the logic to decide if we 
needed the last blit was flawed.
Fixes #4306

fix a case where blended views + dynamic scaling didn't work

---

samples/image_viewer.cpp

We load textures using a float buffer but we want RGB16F textures at runtime. This previously required a manual conversion
from a float3* to a half4*, but this is now taken care of by our Metal backend.

Simplify image loading now that Metal can reshape textures

---

filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp

Improve s3tc_srgb detection on desktop

---

third_party/glslang/tnt/CMakeLists.txt

Update our version of glslang's CMakeLists.txt. Corresponds to https://github.com/KhronosGroup/glslang/commit/05798c17fb17d339d66e064a407e75ceae4c0316
Fixes #4304

Update glslang's tnt/CMakeLists.txt

---

libs/matdbg/src/DebugServer.cpp

Previously, if you accidentally had two matdbg tabs open in Chrome, the
web app would hang. This fixes two bugs that prevented multiple
simultaneous clients:
1) The websocket handler broadcasted edit events to only the most
recent connection.
2) The number of server threads was only 2, but the actual web app
requires at least 2 threads for each instance, due to the
externally linked CSS file.

matdbg: support multiple simultaneous clients.

---

libs/utils/include/utils/Allocator.h
libs/utils/include/utils/SpinLock.h

Make sure SpinLock cannot be used by accident on ARMv7

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

This keeps the MSAA texture around when the texture is attached to multiple RenderTargets.

Cache Metal MSAA sidecar textures in MetalTexture

---

android/gltfio-android/src/main/cpp/MaterialKey.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/MaterialProvider.java

MaterialKey: expose constrainMaterial to Android

---

shaders/src/light_punctual.fs

When calculating the froxel z slice, a depth buffer value of exactly
1 (i.e. far plane) would map to after the last slice, this value
must be clamped.
made the code more readable, hopefully.
Fixes #4388

Fix a possible out of bound access on the GPU

---

filament/include/filament/LightManager.h

Fixed double to float cast warning.

Fixed compiler warning

---

filament/src/PostProcessManager.cpp

fix TAA reprojection

---

libs/utils/src/JobSystem.cpp

Will also cherry-pick into rc/1.12.0 branch.

Attempt to fix TSAN failure in ColorGrading.cpp

---

filament/backend/src/opengl/OpenGLDriver.cpp

glInvalidateFramebuffer is not available before GL4.3.

use glClear instead of glInvalidateFrambuffer on desktop

---

shaders/src/shadowing.fs

this broke recently with #4440

fix contact-shadow ray iteration

---

libs/filabridge/src/SibGenerator.cpp
shaders/src/shadowing.fs

We were missing a few "highp" math.

fix contact shadows on mobile

---

shaders/src/getters.vs

this fixes the skybox's fog.
this broke recently with #4440

Fix VERTEX_DOMAIN_DEVICE world space

---

filament/src/Froxelizer.cpp
filament/src/details/Froxelizer.h
shaders/src/getters.fs
shaders/src/light_punctual.fs

We need to take into account our new clip space.
This broke recently with #4440.

Fix froxelization (computation of z slice)

---

filament/src/ShadowMap.cpp
shaders/src/light_directional.fs
shaders/src/shading_unlit.fs

`shading_unlit.fs` was missing a check :)

Fix CSM glitch with ground plane

---

filament/src/Culler.cpp
filament/src/Culler.h
filament/src/details/View.h
libs/filabridge/include/private/filament/EngineEnums.h

Increase the number of spot shadows to 14 (from 6)

---

filament/backend/src/opengl/OpenGLProgram.cpp
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/shaders/CodeGenerator.cpp

enable GL_ARB_shading_language_packing on GL 4.1

---

filament/src/PostProcessManager.cpp
filament/src/fsr.cpp
filament/src/fsr.h
filament/src/materials/ssao/geometry.fs
filament/src/materials/ssao/sao.mat
filament/src/materials/ssao/saoBentNormals.mat
filament/src/materials/ssao/saoImpl.fs
filament/src/materials/ssao/ssaoUtils.fs
filament/src/materials/ssao/ssctImpl.fs
libs/viewer/src/SimpleViewer.cpp

- added viewport parameter to FSR
- cleanup ssao parameters for linearizing the depth
- added some sliders to simpleviewer

More cleanup in preparation of dynamic resolution improvements

---

libs/gltfio/src/AssetLoader.cpp

gltfio: generate tangents if requested by the material

---

android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java

Fix crash when duplicating material instances

---

filament/backend/src/opengl/OpenGLDriver.cpp

we were not handling drawbuffers 4 to 7.

fix typo where not all requested draw buffers would be cleared

---

libs/utils/include/utils/JobSystem.h
libs/utils/src/JobSystem.cpp

We were decrementing activeJobCount after removing the job from the
queue, which could cause other threads in the pool to preempt us before
the decrement, causing them to spin forever trying to get a non-existant
job, until the decrement actually happened.
Now we always decrement first and fix-up the count if we couldn't get
a job from the queues. The race is inverted, and doesn't cause threads
to spin a long time.

fix a race in jobsystem

---

android/filament-utils-android/build.gradle
android/samples/sample-gltf-viewer/build.gradle

Fix filament-utils-android 'lite' flavor

---

filament/backend/include/backend/BufferDescriptor.h
filament/backend/include/backend/PixelBufferDescriptor.h

There a just new inline helpers to more easily use lambdas, functors and 
method callbacks with {Pixel}BufferDescriptor.
A `BufferDescriptor` can be constructed like this:
`auto bd = BufferDescriptor::make(buffer, size, [](void* b, size_t s){ });`
or
`auto bd = BufferDescriptor::make(buffer, size, &Foo::bar, *foo);`

new helpers for setting {Pixel}BufferDescriptor callbacks

---

RELEASE_NOTES.md
filament/backend/include/backend/DriverEnums.h
filament/src/ShadowMapManager.cpp
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filabridge/include/private/filament/UniformInterfaceBlock.h
libs/filabridge/src/UniformInterfaceBlock.cpp
libs/filamat/src/UibGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.h
libs/matdbg/src/CommonWriter.h
shaders/src/common_math.fs
shaders/src/common_shadowing.fs
shaders/src/common_types.fs
shaders/src/getters.fs

The struct must be declared in common_type.fs, so custom
structures are not supported.

Add a (crude) way to have structs in our UBOs

---

android/build.gradle
android/gradle.properties
android/samples/sample-gltf-viewer/build.gradle
android/samples/sample-hello-camera/build.gradle
android/samples/sample-hello-triangle/build.gradle
android/samples/sample-image-based-lighting/build.gradle
android/samples/sample-lit-cube/build.gradle
android/samples/sample-live-wallpaper/build.gradle
android/samples/sample-material-builder/build.gradle
android/samples/sample-multi-view/build.gradle
android/samples/sample-page-curl/build.gradle
android/samples/sample-stream-test/build.gradle
android/samples/sample-texture-view/build.gradle
android/samples/sample-textured-object/build.gradle
android/samples/sample-transparent-view/build.gradle

Skip task incompatible with configuration caching

---

filament/backend/src/metal/MetalDriver.mm

Metal: fix validation error when rendering to RT without depth

---

filament/backend/src/opengl/OpenGLContext.cpp

A workaround for the tile load/store is no longer needed on recent
version of the GLES3.x drivers on qualcomm SoC.

disable workaround on recent adreno drivers

---

filament/src/Froxelizer.cpp
filament/src/Froxelizer.h
filament/src/PerViewUniforms.cpp
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/UibGenerator.cpp
shaders/src/light_punctual.fs

the fade takes place over 10% of the light far distance.

Fade lights out when close to light far plane

---

android/gltfio-android/src/main/cpp/AssetLoader.cpp

Add missing JNI impl

---

libs/filamat/src/GLSLPostProcessor.cpp

Enable GL_ARB_shading_language_packing in vertex shaders

---

filament/src/Scene.cpp
filament/src/SkinningBuffer.cpp
filament/src/components/RenderableManager.cpp

Make sure to object are aligned properly when allocated in the renderstream

---

filament/backend/include/backend/DriverEnums.h

attempt to fix compilation failure with gcc

---

android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/RenderTarget.h
filament/include/filament/View.h

improve documentation regarding post-processing and render targets

---

shaders/src/shadowing.fs

The same can be achieved with VSM + blur=3 however, this is noticeably
slower. Also when using transparent shadows, VSM needs a much larger
blur to iron out the dithering pattern.
Fixes #5048, #5039

Bring back the 3x3 filter for PCF shadows

---

filament/backend/src/opengl/OpenGLProgram.cpp

Morphing is enabled but no morph targets in some models.
Fixes #5059

Fix, potential null dereferences in OpenGLProgram

---

shaders/src/common_math.fs
shaders/src/dithering.fs
shaders/src/light_reflections.fs
shaders/src/shadowing.fs

this helps a lot when stride is > 1

randomly jitter the ray with screen-space reflections

---

libs/filabridge/include/private/filament/Variant.h
libs/matdbg/src/CommonWriter.cpp
tools/matc/src/matc/CommandlineConfig.cpp
tools/matc/src/matc/ParametersProcessor.cpp

- Improved formating
- Added more compile-time sanity checks
- Renamed Variant bits to 3 letters

Improve (again) comments in Variants.h

---

libs/viewer/include/viewer/SimpleViewer.h
libs/viewer/src/SimpleViewer.cpp

Morphable entities can selectable and morphing is grayed out when playing animations.

Make morphable entities selectable in UI

---

libs/bluevk/bluevk-gen.py

This fixes a double-initialization problem for one of the function
pointers, and also updates the BlueVK generator to fix issues with the
latest Khronos XML file.
The corollary C++ changes will be made in a subsequent PR since they
will be difficult to review.
See #5026.

BlueVK: Do not double initialize vkGetInstanceProcAddr.

---

libs/bluevk/bluevk-gen.py
libs/bluevk/src/BlueVK.cpp

Fix typo in BlueVK script that caused segfault.

---

shaders/src/getters.vs

try to workaround optimizer/compiler bugs

---

libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/common_lighting.fs
shaders/src/common_shadowing.fs
shaders/src/depth_main.fs
shaders/src/getters.fs
shaders/src/getters.vs
shaders/src/inputs.fs
shaders/src/inputs.vs
shaders/src/light_directional.fs
shaders/src/light_indirect.fs
shaders/src/light_punctual.fs
shaders/src/light_reflections.fs
shaders/src/main.fs
shaders/src/main.vs
shaders/src/material_inputs.fs
shaders/src/shading_lit.fs
shaders/src/shading_model_standard.fs
shaders/src/shading_unlit.fs
shaders/src/shadowing.fs

all defines coming from material parameters are named `MATERIAL_HAS_...` 
and all defines coming from the variant are named `VARIANT_HAS_...`

be more consistant with defines names in shaders

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/Matrix.kt
android/filament-utils-android/src/main/java/com/google/android/filament/utils/Quaternion.kt
android/filament-utils-android/src/main/java/com/google/android/filament/utils/Scalar.kt
android/filament-utils-android/src/main/java/com/google/android/filament/utils/Vector.kt

Changes incorporated from github.com/romainguy/kotlin-math

Update Kotlin math API to latest

---

shaders/src/light_indirect.fs

Fix NaN values encountered with SSR and Metal

---

android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java
filament/backend/src/opengl/OpenGLProgram.cpp
filament/include/filament/MaterialInstance.h
filament/src/MaterialInstance.cpp

warn about this condition on debug builds

turns out GLES3.x forbids depth texture filtering

---

filament/src/Engine.cpp
filament/src/MorphTargetBuffer.cpp
filament/src/details/Engine.h

Fix validation errors on Metal

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h

also, allow it to specify the output format.

move generateGaussianMipmap to PostProcessManager

---

filament/include/filament/Scene.h
filament/src/Scene.cpp
filament/src/details/Scene.h
libs/utils/CMakeLists.txt
libs/utils/include/utils/Invocable.h

Added Scene::forEach to iterate through a scene's entities 

---

web/filament-js/utilities.js

The previous code would convert each element of the source data
into 8 bit-per-element, but we want to preserve the original format
that the user provides.
The new solution is to use `slice()` which is a robust way to clone
all the data in a typed array.
This fixes the new regression with Triangle that Ben caught.

WebGL: another fix for BufferDescriptor bindings.

---

filament/src/SkinningBuffer.cpp

make sure skinning bones are correctly initialized

---

web/docs/tutorial_redball.md

To avoid `Material version mismatch`

Make sure one use the right combination of version

---

filament/src/FrameHistory.h
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/Renderer.cpp

The new SSR code allows to clean-up TAA code a bit.
TAA should now be more standalone/abstracted.

cleanup TAA

---

android/filament-android/src/main/cpp/RenderableManager.cpp
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/test/BackendTest.cpp
filament/backend/test/test_Blit.cpp
filament/backend/test/test_BufferUpdates.cpp
filament/backend/test/test_FeedbackLoops.cpp
filament/backend/test/test_MRT.cpp
filament/backend/test/test_MissingRequiredAttributes.cpp
filament/backend/test/test_ReadPixels.cpp
filament/backend/test/test_RenderExternalImage.cpp
filament/include/filament/RenderableManager.h
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Scene.cpp
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
filament/src/details/Scene.h
shaders/src/getters.vs

We just add an instance count to the backend draw command.

instancing support for the backends

---

android/filament-android/src/main/java/com/google/android/filament/Texture.java

Missing public modifier in Texture.java

---

RELEASE_NOTES.md
libs/filabridge/include/filament/MaterialEnums.h

This this needed by recent SSR changes.

update material version

---

filament/src/components/RenderableManager.cpp
libs/filabridge/include/private/filament/UibStructs.h

There was still a case where skinning wasn’t correctly default initialized

---

filament/backend/include/backend/Handle.h
filament/backend/src/Handle.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/Renderer.cpp
filament/src/fg2/FrameGraphId.h

This saves about 7KB on `libfilament_jni.so`.

size and performance micro optimizations

---

filament/src/Engine.cpp

We should to initialize these textures to prevent warnings with Vulkan.

Engine: fill dummy textures with zeroes.

---

filament/src/PostProcessManager.cpp

Guarantee Texture's minimum width and height must be 1

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/Matrix.kt

Reference: https://github.com/google/filament/blob/49b8e5e5d2c90b62cada2b77941db1f8bcfdfbc9/libs/math/include/math/mat4.h#L538

Bugfix: lookAt z axis negated

---

libs/gltfio/src/UbershaderLoader.cpp

@prideout I'm not sure if this fix is correct (I had 50% chance!) but it fixes the build.

fix android build

---

filament/backend/src/vulkan/VulkanPipelineCache.cpp

We held a reference to a cache item after potentially clearing it due to
pool growth. I was able to trigger an error only after enabling ASAN and
loading a large model.  Many thanks to @jeanlemotan for catching this.

VulkanPipelineCache: fix use-after-free when growing pool.

---

android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt

Dragging a zip file into the Remote Viewer page would fail if it
contained a glTF with `./` prefixes in the `images` section. The best
fix is to use Java's proper URI object rather than trying to parse the
string.

Android Viewer: fix URI bug for some zips files.

---

libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FFilamentInstance.h
libs/gltfio/src/FilamentAsset.cpp
libs/gltfio/src/FilamentInstance.cpp

Retrieve skins from FilamentAsset

---

filament/src/Froxelizer.cpp
shaders/src/light_punctual.fs

The froxel parameter for the Z slice were not correct.
Fixes #5318

fix point light lighting with ortho projection

---

libs/filabridge/include/filament/MaterialEnums.h

Update MAX_MORPH_TARGETS to 256

---

filament/backend/CMakeLists.txt
filament/backend/include/private/backend/Program.h
filament/backend/src/Program.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/test/BackendTest.h
filament/backend/test/TrianglePrimitive.cpp
filament/backend/test/test_Blit.cpp
filament/backend/test/test_FeedbackLoops.cpp
filament/src/details/Material.cpp
libs/utils/include/utils/Invocable.h

This would mean that the backend is not independent of our material
system. Thankfully we didn't have too many dependencies that leaked
there.

The backend CANNOT depend on filabridge

---

shaders/src/getters.vs

skip work when morphtarget weight is zero

---

filament/backend/include/private/backend/Program.h
filament/backend/src/DriverBase.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLProgram.cpp
filament/backend/src/opengl/OpenGLProgram.h
libs/utils/include/utils/CString.h
libs/utils/src/CString.cpp

This is the first step before we defer a lot of the glGet* calls.

cleanup OpenGLProgram

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLProgram.cpp
filament/backend/src/opengl/OpenGLProgram.h

in an upcoming PR we'll move linking back a bit earlier to allow
more batching.

defer gl program link + query to first use (draw)

---

android/gltfio-android/src/main/cpp/FilamentInstance.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentInstance.java
libs/gltfio/include/gltfio/FilamentAsset.h
libs/gltfio/include/gltfio/FilamentInstance.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
libs/gltfio/src/FFilamentInstance.h
libs/gltfio/src/FilamentInstance.cpp
libs/gltfio/src/ResourceLoader.cpp
samples/gltf_instances.cpp
web/filament-js/jsbindings.cpp

gltfio: material variants can now be applied to FilamentInstance.

---

filament/src/PostProcessManager.cpp
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/details/Material.cpp
filament/src/details/Material.h

from now on, the backends can assume that programs are created outside
of begin/endRenderpass.

programs must now be created outside of renderpasses

---

README.md
RELEASE_NOTES.md
docs/webgl/helmet.html
libs/gltfio/include/gltfio/MaterialProvider.h
libs/gltfio/materials/sheen.mat.in
libs/gltfio/materials/transmission.mat.in
libs/gltfio/materials/ubershader.mat.in
libs/gltfio/materials/volume.mat.in
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/MaterialGenerator.cpp
web/samples/helmet.html

gltfio: add support for KHR_materials_emissive_strength

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/ShadowMapManager.cpp
filament/src/ShadowMapManager.h
filament/src/details/Renderer.cpp
filament/src/details/View.cpp
filament/src/details/View.h

This makes the code simpler to follow.

remove all references to the "Blackboard" from PostPorcessManager

---

filament/backend/src/metal/MetalHandles.mm

Fix Metal validation error when reading from default SwapChain

---

web/filament-js/wasmloader.js

WebGL: fix intermittent 'detached ArrayBuffer' errors.

---

RELEASE_NOTES.md
android/gltfio-android/src/main/cpp/Animator.cpp
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/Animator.java
libs/gltfio/include/gltfio/Animator.h
libs/gltfio/src/Animator.cpp
libs/viewer/include/viewer/SimpleViewer.h
libs/viewer/src/SimpleViewer.cpp
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp

gltfio Animator: add resetBoneMatrices().

---

filament/src/PostProcessManager.cpp

This version is used only on qualcomm devices. It's now forbidden to
create a program inside a renderpass. Unfortunately there was still
one codepath doing so.

fix the 2 passes version of FSR

---

filament/src/PostProcessManager.cpp

Bloom now works fine (tested with Chrome 100 on a x86 MacBook) without
this workaround for overly aggressive feedback loop detection.

Remove WebGL workaround for bloom.

---

filament/src/PerViewUniforms.cpp
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/ShadowMap.cpp
filament/src/details/Camera.cpp
filament/src/details/Camera.h
filament/src/details/Renderer.cpp
filament/src/details/Renderer.h
filament/src/details/View.cpp
filament/src/details/View.h
filament/src/materials/antiAliasing/fxaa.mat
filament/src/materials/dof/dof.mat
filament/src/materials/dof/dofUtils.fs
filament/src/materials/ssao/bilateralBlur.mat
filament/src/materials/ssao/bilateralBlurBentNormals.mat
filament/src/materials/ssao/saoImpl.fs
filament/src/materials/ssao/ssaoUtils.fs
filament/src/materials/ssao/ssct.fs
samples/gltf_viewer.cpp

it's easier to review the CL separately.
Most of the cleanup are about removing unused code or data, or simplifying existing code.

various cleanups

---

libs/ktxreader/include/ktxreader/Ktx1Reader.h
libs/ktxreader/src/Ktx1Reader.cpp

Some G3 clients rely on this function.

Move toCompressedFilamentEnum to Ktx1Reader header

---

ios/samples/hello-pbr/hello-pbr/FilamentApp.cpp
ios/samples/hello-pbr/hello-pbr/FilamentApp.h
ios/samples/hello-pbr/hello-pbr/FilamentView.mm
ios/samples/hello-pbr/hello-pbr/ViewController.m

Update hello-pbr sample to work in all orientations

---

filament/src/RenderPass.cpp

We can't call prepareProgram() from any thread, since it is calling
into the backend. When we had more than a certain number of commands,
we would use the jobsystem to generate them and so prepareProgram()
could end up being called from a jobsystem thread.
This is fixed by looping through all the commands once they're generated
and calling prepareProgram() then.

fix a potential threading/memory corruption

---

RELEASE_NOTES.md
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/GLSLPostProcessor.h
libs/filamat/src/MaterialBuilder.cpp

Metal: add RelaxedtoHalfPass for improved ALU performance

---

RELEASE_NOTES.md
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/details/Scene.cpp
filament/src/details/Scene.h
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/UibGenerator.cpp
libs/utils/include/utils/StructureOfArrays.h
shaders/src/common_getters.glsl
shaders/src/getters.vs
shaders/src/light_directional.fs
shaders/src/light_punctual.fs
shaders/src/main.vs
shaders/src/shading_unlit.fs

- move skinning info into PrimitiveInfo
- par PerRenderableUib so it could fit 2 entries per slot in the future
⚠️ **material breakage**

improvement to rendering renderables

---

RELEASE_NOTES.md
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/ShadowMap.cpp

disable user scissor while rendering the shadowmaps

---

RELEASE_NOTES.md
filament/backend/src/opengl/platforms/PlatformWGL.cpp

Fix WGL requested context attributes

---

RELEASE_NOTES.md
filament/src/ResourceAllocator.cpp
filament/src/ResourceAllocator.h
libs/utils/include/utils/Stopwatch.h

also added a basic `Stopwatch` to libutils.

Improve ResourceAllocator a bit by reserving 128 cache entries

---

RELEASE_NOTES.md
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp
web/samples/helmet.html

Fixes https://github.com/google/filament/issues/5627.

Expose picking to JavaScript, use it in helmet demo.

---

shaders/src/main.vs

it would be initialized after user material code was called.

fix getInstanceIndex()

---

libs/filaflat/src/DictionaryReader.cpp
libs/matdbg/README.md
libs/matdbg/src/ShaderReplacer.cpp

This was too tricky, it highlights that we definitely need refactor this
to share code with the flattener / unflattener pipeline. I'll look at
that next.

Quick repair to matdbg for alignment padding.

---

libs/image/src/ImageSampler.cpp

Fix Conflict with glibc 2.35+ macro.

---

filament/backend/src/DataReshaper.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/src/RendererUtils.cpp
filament/src/ResourceAllocator.cpp
filament/src/details/Material.cpp
filament/src/details/Material.h
filament/src/details/Renderer.cpp
filament/src/details/Scene.cpp
filament/src/details/View.cpp

- try to help DataReshaper a bit
- fix some typos in comments
- address a few "todos"
- protect mActivePrograms with a lock, as it should

code maintenance/cleanups

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/src/details/Texture.cpp
libs/filamentapp/src/IBL.cpp
libs/ktxreader/src/Ktx1Reader.cpp

There was a wrong assert in Texture::setImage() as well as a typo when
calling setImage() itself in the sample code.

fix cubemap uploading

---

filament/backend/src/metal/MetalBlitter.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalEnums.h
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/metal/MetalState.h
filament/backend/src/metal/MetalState.mm
filament/backend/test/test_StencilBuffer.cpp

Metal: add initial support for stencil buffers

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/opengl/GLUtils.h
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h

reviewers: it'll much easier to review each CL separately. thanks.

smalls improvement to GL backend stencil and raster state

---

android/filament-android/src/main/java/com/google/android/filament/Texture.java

Fix Texture documentation

---

libs/filamat/src/shaders/ShaderGenerator.cpp

both fragment and vertex shaders need material defines

---

filament/src/details/Texture.cpp

this regression was introduced recently.

fix incorrect assert when uploading cubemaps

---

RELEASE_NOTES.md
filament/backend/include/backend/DriverEnums.h
filament/include/filament/MaterialInstance.h
filament/src/MaterialInstance.cpp
filament/src/RenderPass.cpp
filament/src/details/MaterialInstance.cpp
filament/src/details/MaterialInstance.h

Java / JavaScript APIs coming next!

Add stencil state APIs to MaterialInstance

---

android/filament-android/src/main/java/com/google/android/filament/Material.java
android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java
android/gltfio-android/src/main/java/com/google/android/filament/gltfio/MaterialProvider.java

Android: prevent misc obfuscation for gltfio

---

web/samples/CMakeLists.txt

Noticed this while trying to help with #5859.

CMake: fix wasm build on windows machines

---

libs/utils/include/utils/BinaryTreeArray.h

don't use std::is_pod which is soon to be deprecated

---

filament/src/ShadowMap.cpp

this case could cause an assert in debug builds. There was a few bugs:
- when computing the intersection between a box and a frustum, a special
case test had a typo which would cause extra work in some case. Also,
we were not detecting correctly when there was no intersection at all.
This could result in some intersection point being found.
- Finally, we reject the intersection volume when it has only 3 vertices
because that's not a volume.
Fixes #5933

fix shadows when there is no receivers in the frustum

---

RELEASE_NOTES.md
filament/backend/src/opengl/OpenGLProgram.cpp
libs/filabridge/include/private/filament/EngineEnums.h

This is a temporary fix until spec constants arrive.

WASM: Set CONFIG_MAX_INSTANCES to a small value + hack the GLSL.

---

filament/src/ShadowMap.cpp

We were early-exiting too aggressively in the some case.

fix (again) frustum-box intersection

---

RELEASE_NOTES.md
libs/gltfio/src/AssetLoader.cpp

Spotlights were accidentally disabled in PR #5932.

gltfio: fix spotlight regression.

---

CMakeLists.txt
filament/include/filament/Engine.h
shaders/src/light_punctual.fs

Also added some ascii art to explain better how the various arenas are
used.

The default arena sizes in the makefile didn't match the code

---

ios/CocoaPods/Filament.podspec

Fix uberarchive not included in PodSpec

---

libs/gltfio/src/AssetLoader.cpp

The recent introduction of index-based mapping between cgltf objects and Filament objects was broken for the case where the model omits a material specification (which is a valid thing to do).
This fix also refactors some hodgepodge data & logic into a proper class called `MaterialInstanceCache` (which is internal only).

gltfio: fix crash when material is unspecified

---

android/filament-utils-android/src/main/cpp/AutomationEngine.cpp
android/filament-utils-android/src/main/java/com/google/android/filament/utils/AutomationEngine.java
android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
filament/backend/src/opengl/OpenGLProgram.cpp
filament/src/details/Engine.h
ios/samples/gltf-viewer/gltf-viewer/FILViewController.mm
libs/filamentapp/include/filamentapp/Config.h
libs/filamentapp/src/FilamentApp.cpp
libs/viewer/include/viewer/AutomationEngine.h
libs/viewer/include/viewer/Settings.h
libs/viewer/src/AutomationEngine.cpp
libs/viewer/src/Settings.cpp
libs/viewer/src/ViewerGui.cpp
samples/gltf_viewer.cpp
samples/image_viewer.cpp

[reviewers, probably easier to review the 3 CL separately]

a few fixes related to feature levels

---

filament/backend/src/vulkan/VulkanPipelineCache.cpp
filament/backend/src/vulkan/VulkanPipelineCache.h

Also, there's no such thing as a "bound layout".

Vk: When the layout requirement change, the pipeline is "dirty".

---

samples/image_viewer.cpp

Fix memory leak

---

libs/gltfio/src/AssetLoader.cpp

AssetLoader now loads assets in two passes:
- Pass 1 creates VertexBuffer objects, MorphTargetBuffer objects, etc.
- Pass 2 creates entities, renderables, etc (only if numInstances > 0)
This feature will help us integrate gltfio with an internal library at Google.

gltfio: prep step for allowing zero-instance assets

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/vulkan/VulkanPipelineCache.cpp
filament/backend/src/vulkan/VulkanPipelineCache.h
filament/src/MaterialParser.cpp
libs/filabridge/include/private/filament/SamplerBindingsInfo.h
libs/filabridge/include/private/filament/SamplerInterfaceBlock.h
libs/filamat/src/SamplerBindingMap.cpp
libs/utils/include/utils/bitset.h

This is needed for feature level 2.

bump max sampler count to 62

---

RELEASE_NOTES.md
libs/gltfio/include/gltfio/Animator.h
libs/gltfio/include/gltfio/FilamentInstance.h
libs/gltfio/src/Animator.cpp
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentInstance.h
libs/gltfio/src/FilamentInstance.cpp

In the future, we will allow instances to be constructed from immutable assets (this is a Google feature request) so this PR prepares for that.

gltfio: FilamentInstance owner is now const.

---

filament/src/ShadowMap.cpp

it is not true that the whole box is inside the frustum if we have 8 vertices and some frustum vertices are in the box -- that's even non-sensical.
We now test for this case by checking that we have all (8) vertices of the box inside the frustum.
This caused some shadows to be missing.

fix (again) the box-frustum intersection

---

libs/filamentapp/src/FilamentApp.cpp
libs/filamentapp/src/NativeWindowHelperLinux.cpp

-move Wayland specific code into getNativeWindow
-make wayland struct static
Signed-off-by: Joel Winarske <joel.winarske@gmail.com>

Wayland FilamentApp

---

libs/utils/CMakeLists.txt

Fix generic/Mutex.h not installed on Linux

---

RELEASE_NOTES.md
libs/gltfio/materials/base.mat.in
libs/gltfio/materials/sheen.mat.in
libs/gltfio/materials/transmission.mat.in
libs/gltfio/materials/volume.mat.in
libs/gltfio/src/JitShaderProvider.cpp

gltfio: fix occlusion strength

---

RELEASE_NOTES.md
android/build.gradle
android/samples/sample-gltf-viewer/build.gradle
build/toolchain-arm7-linux-android.cmake
build/toolchain-x86-linux-android.cmake
filament/backend/src/opengl/platforms/PlatformEGLAndroid.cpp

this is so that we can support OpenGL ES3.1

switch our min sdk from 19 to 21

---

android/filamat-android/src/main/AndroidManifest.xml
android/filament-android/src/main/AndroidManifest.xml
android/filament-utils-android/src/main/AndroidManifest.xml
filament/backend/src/opengl/OpenGLContext.h

Fixes for 1.27.2 release

---

RELEASE_NOTES.md
libs/gltfio/src/ArchiveCache.cpp
libs/gltfio/src/ArchiveCache.h
libs/gltfio/src/UbershaderProvider.cpp

Fix a crash by setting not exist material parameters on ubershader

---

RELEASE_NOTES.md
libs/gltfio/src/AssetLoader.cpp

gltfio ubershader mode: fix re-loading.

---

filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

Fix Metal argument buffer encoding

---

filament/backend/src/metal/MetalBuffer.h

Metal: fix simulator regression due to arg buffers

---

filament/src/ShadowMap.cpp

the shadow frustum could be be smaller than expected.

fix a directional light shadowing issue

---

RELEASE_NOTES.md
samples/CMakeLists.txt

Fix installed IBL location for desktop.

---

filament/backend/src/metal/MetalBuffer.h

Metal: fix use-after-free ASAN error

---

filament/src/details/Engine.cpp
libs/fgdbg/CMakeLists.txt
libs/fgdbg/include/fgdbg/DebugServer.h
libs/fgdbg/src/DebugServer.cpp

Test this by running Filament, and opening a browser to `http://localhost:8082/`
console:
```
var webSocket = new WebSocket('ws://localhost:8082');
webSocket.onmessage = function(data) { console.log(data.data); }
```

Add DebugServer for fgdbg with support for Websockets

---

RELEASE_NOTES.md
libs/gltfio/src/ResourceLoader.cpp

Fix glTF breaking issue

---

RELEASE_NOTES.md
web/filament-js/filament.d.ts
web/filament-js/jsbindings.cpp
web/filament-js/jsenums.cpp

Expose missing ColorGrading::Builder methods to JS

---

RELEASE_NOTES.md
filament/src/PerShadowMapUniforms.cpp
filament/src/PerShadowMapUniforms.h
filament/src/PerViewUniforms.cpp
filament/src/ShadowMap.cpp
filament/src/ShadowMap.h
filament/src/ShadowMapManager.cpp
filament/src/ShadowMapManager.h
filament/src/details/Scene.cpp
filament/src/details/Scene.h
filament/src/details/View.cpp
filament/src/details/View.h
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/EngineEnums.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/UibGenerator.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
shaders/src/common_lighting.fs
shaders/src/common_types.glsl
shaders/src/getters.fs
shaders/src/getters.vs
shaders/src/light_directional.fs
shaders/src/light_punctual.fs
shaders/src/main.vs
shaders/src/shading_unlit.fs
shaders/src/shadowing.fs

- update comments
- remove unused or unneeded methods
- the layer is now stored in the shadow ubo
- we now have one shadow ubo per face
- ShadowMap holds UBO index even for cascades
- move some shadow "view" uniforms into the shadow UBO

shadowmapping code improvements

---

RELEASE_NOTES.md
filament/src/BufferPoolAllocator.h
filament/src/details/Scene.cpp
filament/src/details/Scene.h

Fix memory corruption in FScene

---

filament/src/AtlasAllocator.cpp

it could return an orphan node, that is some of the parent in its ancestry have no children.

fix atlas allocator

---

RELEASE_NOTES.md
filament/src/ShadowMapManager.cpp
libs/filabridge/include/filament/MaterialEnums.h
libs/filabridge/include/private/filament/UibStructs.h
shaders/src/common_lighting.fs
shaders/src/common_shadowing.glsl
shaders/src/common_types.glsl
shaders/src/getters.fs
shaders/src/light_directional.fs
shaders/src/light_punctual.fs
shaders/src/shading_unlit.fs
shaders/src/shadowing.fs

We already have it in the Light structure.

don't store the light direction in the shadowmap structure

---

samples/viewtest.cpp

- it didn't clear the swapchain
- added support for `-a` option

fix viewtest

---

RELEASE_NOTES.md
filament/src/components/TransformManager.cpp
filament/src/components/TransformManager.h
filament/test/filament_test.cpp

The residual would be corrupted when using transactions.

fix TransformManager high precision mode

---

RELEASE_NOTES.md
web/filament-js/filament.d.ts

Add TS definition for Engine.destroy

---

filament/backend/src/BackendUtils.cpp
filament/backend/src/Callable.cpp
filament/backend/src/CircularBuffer.cpp
filament/backend/src/CommandBufferQueue.cpp
filament/backend/src/CommandStream.cpp
filament/backend/src/opengl/GLUtils.cpp
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/opengl/OpenGLProgram.cpp
libs/utils/include/utils/Systrace.h

fix new code quality warnings enabled by CLion

code cleanup

---

filament/backend/src/vulkan/VulkanDriver.cpp

[vulkan] Break when desired layer is found

---

filament/src/details/Engine.cpp
filament/src/details/Engine.h
libs/fgdbg/CMakeLists.txt
libs/fgdbg/include/fgdbg/DebugServer.h
libs/fgdbg/include/fgdbg/Pass.h
libs/fgdbg/include/fgdbg/Resource.h
libs/fgdbg/include/fgdbg/Session.h
libs/fgdbg/src/Session.cpp

Still in WIP, feel free to take a look and leave suggestions

Add fgdbg::Session.h, Pass.h, Resource.h dtos/models

---

libs/utils/include/utils/Path.h
libs/utils/src/Path.cpp

Allow to create a path from a string view.

Create a path from a string view

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanUtility.h

Use templates to help clean up VK property/layer enumerations.

[vulkan] Refactor vkEnumerate methods

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanUtility.h

This reverts commit 8d608830d468f2a4bff8ff2ef954edca220dc1aa.
Reason: broke Android build -> https://github.com/google/filament/actions/runs/3841550984

Revert "[vulkan] Refactor vkEnumerate methods (#6423)"

---

.github/workflows/android-continuous.yml
.github/workflows/ios-continuous.yml
.github/workflows/linux-continuous.yml
.github/workflows/mac-continuous.yml
.github/workflows/presubmit.yml
.github/workflows/release.yml
.github/workflows/web-continuous.yml
.github/workflows/windows-continuous.yml

Update to the latest version of `actions/checkout`.

Update actions/checkout version

---

filament/src/RenderPass.cpp

Fix a typo with auto instancing

---

RELEASE_NOTES.md
filament/backend/src/vulkan/VulkanDriver.cpp

vulkan: Fix readPixels memory leak

---

RELEASE_NOTES.md
shaders/src/depth_main.fs

Initialize object_uniforms in depth shader

---

filament/src/details/Engine.cpp
libs/fgdbg/client/build.gradle.kts
libs/fgdbg/client/gradle.properties
libs/fgdbg/client/src/main/kotlin/Main.kt
libs/fgdbg/include/fgdbg/DebugServer.h
libs/fgdbg/include/fgdbg/Session.h
libs/fgdbg/src/DebugServer.cpp
libs/fgdbg/src/Session.cpp

Uploading [Pass] and [Resource] information to the server. 
Much of the code in this PR is prototype (No error handling, no optimisations) just to get something working quickly and iterate later. Don't usually code in cpp, feedback appreciated.

Improve Session API, send formatted string to server

---

libs/utils/include/utils/StructureOfArrays.h

Instead of storing the arrays into an array of void*, we use a  tuple<> instead. This improves debugging because now the tuple<> has pointer with the correct types.
It also improves most of the code except `push_back` which now relies on a hack -- this is the only place where I'm not able to  resolve the array strictly at compile time, even if in practice it is.

improve SoA a bit

---

filament/backend/src/vulkan/VulkanSwapChain.cpp

vulkan: Assert that graphics-QF is present-QF

---

libs/geometry/CMakeLists.txt
libs/geometry/include/geometry/TangentSpaceMesh.h
libs/geometry/src/TangentSpaceMesh.cpp
libs/geometry/tests/test_tangent_space_mesh.cpp

Added:
- Hughes-Moller
- Frisvad's method
- Flat shading

geometry: Add TangentSpaceMesh implementations

---

libs/viewer/src/ViewerGui.cpp

We use isnan() to detect that the estimation of directional light parameters from the IBL has failed, however isnan() always returns false with -ffast-math, which we're using in release builds. This works around that. The affected code is non essential, performance is not a concern here.

workaround our -ffast-math

---

filament/src/details/View.cpp

we need to use the culling projection matrix for culling!

fix a main camera far plane culling

---

filament/backend/src/opengl/OpenGLDriver.cpp

We were not testing for that case properly. This case is taken when  either:
- depth & stencil textures are the same and not null
- or, only depth is specified but both attachments are requested
Also cleanup the dimension checks in debug builds.

fix DEPTH_STENCIL case for fbo attachments

---

filament/backend/src/vulkan/VulkanDriver.cpp

Full validation label is: BestPractices-vkCmdBeginRenderPass-ClearValueWithoutLoadOpClear

vulkan: fix validation BestPractices - ClearValueWithoutLoadOpClear

---

shaders/src/fog.fs

- update comments and some names

cleanup fog

---

filament/src/fg/PassNode.cpp
filament/test/filament_framegraph_test.cpp

An attachment would be wrongly discarded if used as read-only: because it didn't have a dependency to it, the discard flag was set. This is fixed by setting the discard flag only if a resource is written and has dependencies to it.
Should fix: #5005

fix a discard flags issue

---

libs/fgdbg/client/src/main/kotlin/Main.kt
libs/fgdbg/include/fgdbg/Session.h
libs/fgdbg/src/Session.cpp

[Perform a hash check + Verify that the data is valid] before upload

Data verification before server upload

---

samples/gltf_viewer.cpp

gltf-viewer: update API/backend usage description

---

docs/Filament.html
docs/Materials.html

The web docs needed rebuilding:
```
./build.sh -w
```

Update web docs

---

android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
filament/include/filament/RenderableManager.h
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/components/RenderableManager.cpp

only use the instanced UBO with automatic instancing.
Fixes #6579

fix manual instancing

---

samples/CMakeLists.txt
samples/gltf_viewer.cpp

debug builds are unchanged, release builds will now optimize shaders and either build can be overridden with OPTIMIZE_MATERIALS.

gltf_viewer now respects FILAMENT_DISABLE_MATOPT

---

filament/backend/src/opengl/platforms/PlatformWGL.cpp

better selection of opengl context version on desktop

---

NEW_RELEASE_NOTES.md
libs/gltfio/src/Animator.cpp
samples/gltf_viewer.cpp

We are doing skinning computations effectively in world space, so
some of the math must be done in high-precision.

skinning now works when the model is far from the origin

---

docs/Filament.md.html

fix typos in documentation

---

libs/filamat/src/shaders/CodeGenerator.cpp

`float`s in GLSL must have a decimal point. Recent changes to `ostream` omit the decimal when outputting whole integers, so we'll do our own formatting.

Fix float spec constant formatting

---

filament/backend/src/opengl/OpenGLProgram.cpp

- boolean where handled as int
- always cast float to float()

fix specification constant injection in glsl

---

.github/workflows/android-continuous.yml
.github/workflows/presubmit.yml
BUILDING.md
android/build.gradle
android/filamat-android/build.gradle
android/filament-android/build.gradle
android/filament-android/src/main/java/com/google/android/filament/ColorGrading.java
android/filament-utils-android/build.gradle
android/gltfio-android/build.gradle
android/gradle.properties
android/gradle/gradle-mvn-push.gradle
android/gradle/wrapper/gradle-wrapper.properties
build/android/build.sh
build/common/ci-common.sh

This upgrade lets us remove several hacks we needed to properly publish our artifacts on Maven.

Upgrade to AGP/Gradle 8.0.0, and other dependency upgrades

---

android/filament-utils-android/src/main/java/com/google/android/filament/utils/Half.kt
android/filament-utils-android/src/main/java/com/google/android/filament/utils/Matrix.kt
android/filament-utils-android/src/main/java/com/google/android/filament/utils/Quaternion.kt
android/filament-utils-android/src/main/java/com/google/android/filament/utils/Scalar.kt
android/filament-utils-android/src/main/java/com/google/android/filament/utils/Vector.kt

Fixes bugs and adds new useful APIs.
Fixes #6760 6760

Update Kotlin math APIs

---

NEW_RELEASE_NOTES.md
android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
docs/Materials.md.html
filament/include/filament/View.h
filament/src/PerViewUniforms.cpp
filament/src/PerViewUniforms.h
filament/src/View.cpp
filament/src/details/View.cpp
filament/src/details/View.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/shaders/UibGenerator.cpp
shaders/src/common_getters.glsl
web/filament-js/jsbindings.cpp

A material global is a variable seen by all materials. There are 4 such  variable which are all vec4 and they can be set on a per-view basis.
All materials used during Renderer::render() will see the same value.
These variable can be accessed in the materials by using  getMaterialGloabal{0|1|2|3}.

very basic API for materials to have global variables

---

filament/backend/include/backend/platforms/PlatformEGL.h
filament/backend/src/opengl/platforms/PlatformEGL.cpp

- add a helper Config class to more easily manage EGL's attribute pairs.
- consolidate config selection code

cleanup PlatformEGL a bit.

---

NEW_RELEASE_NOTES.md
filament/CMakeLists.txt
filament/include/filament/Engine.h
filament/include/filament/InstanceBuffer.h
filament/include/filament/RenderableManager.h
filament/src/Engine.cpp
filament/src/InstanceBuffer.cpp
filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/RenderableManager.cpp
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
filament/src/details/Engine.cpp
filament/src/details/Engine.h
filament/src/details/InstanceBuffer.cpp
filament/src/details/InstanceBuffer.h
filament/src/details/Scene.cpp
filament/src/details/Scene.h
libs/filabridge/include/private/filament/UibStructs.h
libs/math/include/math/mat3.h
shaders/src/common_getters.glsl
shaders/src/common_instancing.glsl
shaders/src/common_types.glsl

Clients can now supply a local transform for each GPU instance. Still working through some TODOs, putting this up for early feedback.

Add support for supplying instance local transforms

---

filament/backend/src/opengl/OpenGLDriver.cpp

opengl: fix web readPixels

---

shaders/src/common_defines.glsl
shaders/src/common_shadowing.glsl
shaders/src/light_reflections.fs

Remove `const` from `const highp mat4` just for mobile+vulkan
Fixes #5294

vulkan: Fix Adreno crash for debug build

---

filament/backend/src/opengl/platforms/PlatformCocoaTouchGL.mm

this is needed because filament does state tracking.

iOS: make sure to save/restore the framebuffer binding

---

shaders/src/fog.fs
shaders/src/main.fs

Fog should be calculated in the user's world coordinates

---

tools/cmgen/src/cmgen.cpp

- Passing filename.bin to --sh-output generates a file containing the SH as binary floats in native endianness (LE on x86 and arm64)
- Fix --sh-output so it works properly with -x
- Cleanup variable names to avoid shadowing

Add .bin option to --sh-output to generate SH in binary

---

filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.h

vulkan: fix unitialization

---

NEW_RELEASE_NOTES.md
android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
docs/Materials.md.html
filament/include/filament/Options.h
filament/src/PerViewUniforms.cpp
filament/src/PerViewUniforms.h
filament/src/details/View.cpp
libs/filabridge/include/private/filament/SibStructs.h
libs/filabridge/include/private/filament/UibStructs.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/SibGenerator.cpp
libs/filamat/src/shaders/UibGenerator.cpp
libs/viewer/src/Settings_generated.cpp
shaders/src/fog.fs
web/filament-js/extensions_generated.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings_generated.cpp

Support for custom fog-color texture

---

filament/backend/include/private/backend/CircularBuffer.h
filament/backend/include/private/backend/CommandBufferQueue.h
filament/backend/src/CircularBuffer.cpp
filament/backend/src/CommandBufferQueue.cpp
libs/utils/CMakeLists.txt
libs/utils/include/utils/architecture.h
libs/utils/src/architecture.cpp

It's already 16K on macOS and other systems.

don't hardcode the system page size to 4096

---

NEW_RELEASE_NOTES.md
filament/backend/CMakeLists.txt
filament/backend/include/backend/platforms/VulkanPlatform.h
filament/backend/src/vulkan/VulkanBuffer.cpp
filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanDriver.h
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanStagePool.cpp
filament/backend/src/vulkan/VulkanSwapChain.cpp
filament/backend/src/vulkan/VulkanSwapChain.h
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/VulkanTexture.h
filament/backend/src/vulkan/VulkanUtility.cpp
filament/backend/src/vulkan/VulkanUtility.h
filament/backend/src/vulkan/platform/VulkanPlatform.cpp
filament/backend/src/vulkan/platform/VulkanPlatformAndroidLinuxWindows.cpp
filament/backend/src/vulkan/platform/VulkanPlatformApple.mm
filament/backend/src/vulkan/platform/VulkanPlatformSwapChainImpl.cpp
filament/backend/src/vulkan/platform/VulkanPlatformSwapChainImpl.h

- Introduce new custom swapchain API for VulkanPlatform.h
- Implement the API for the base VulkanPlatform by refactoring the existing swapchain code.
- VulkanSwapChain is now a wrapper for VulkanPlatform's swap chain API.
- Actual implementation is in vulkan/platform/VulkanPlatformSwapChainImpl.{h,cpp}

vulkan: platform swapchain API

---

filament/backend/src/vulkan/platform/VulkanPlatformAndroidLinuxWindows.cpp

vulkan: fix freebsd platform breakage

---

filament/src/MaterialParser.cpp
libs/filaflat/include/filaflat/ChunkContainer.h
libs/filaflat/include/filaflat/Unflattener.h
libs/filaflat/src/ChunkContainer.cpp
libs/filaflat/src/Unflattener.cpp

- improves performance
- reduces code size

MaterialParser micro optimizations

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/ShadowMapManager.cpp
filament/src/components/RenderableManager.cpp

fix a crash on adreno when vsm is enabled

---

filament/backend/src/vulkan/platform/VulkanPlatform.cpp

- Make sure terminate() doesn't free shared context
- Assume no extensions have been enabled.

vulkan: fix context sharing

---

filament/backend/include/backend/platforms/VulkanPlatform.h
filament/backend/src/vulkan/platform/VulkanPlatform.cpp
libs/filamentapp/include/filamentapp/Config.h
libs/filamentapp/include/filamentapp/FilamentApp.h
libs/filamentapp/src/FilamentApp.cpp
samples/gltf_viewer.cpp

- Added a optional flag to `gltf_viewer` to demonstrate this feature.

vulkan: add option to choose gpu in platform

---

NEW_RELEASE_NOTES.md
filament/backend/src/opengl/ShaderCompilerService.cpp

fix typo that prevented the shader blob cache to work

---

libs/filamentapp/include/filamentapp/FilamentApp.h
libs/filamentapp/src/FilamentApp.cpp

filamentapp: fix vulkan dependency

---

NEW_RELEASE_NOTES.md
filament/backend/src/opengl/OpenGLContext.cpp

Disable timer queries on all Mali GPUs

---

NEW_RELEASE_NOTES.md
android/filament-android/src/main/cpp/Engine.cpp
android/filament-android/src/main/java/com/google/android/filament/Engine.java
filament/backend/src/Driver.cpp
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/ShaderCompilerService.cpp
filament/backend/src/opengl/ShaderCompilerService.h
filament/backend/src/opengl/platforms/PlatformCocoaGL.mm
filament/include/filament/Engine.h
filament/include/filament/Material.h
filament/src/Engine.cpp
filament/src/ResourceList.cpp
filament/src/ResourceList.h
filament/src/details/Engine.cpp
filament/src/details/Engine.h
libs/gltfio/src/ArchiveCache.cpp
web/filament-js/jsbindings.cpp

- fix an issue causing callbacks to be called too late
- fix cleanup of material parallel compilation
- Add a way to query the validity of filament objects

Fix several issues with parallel material compilation

---

NEW_RELEASE_NOTES.md
filament/src/details/View.cpp
shaders/src/common_instancing.glsl
shaders/src/depth_main.fs
shaders/src/getters.fs
shaders/src/getters.vs
shaders/src/light_directional.fs
shaders/src/light_punctual.fs
shaders/src/main.fs
shaders/src/main.vs
shaders/src/shading_unlit.fs

Adreno drivers don't support precision qualifiers in structs.
fixes #6997

Workaround Adreno bug causing picking to fail

---

filament/src/materials/dof/dof.mat

Fix rendering issue when using DoF.  
This solves #6888.

Fix rendering issue when using DoF

---

filament/backend/src/opengl/OpenGLContext.cpp

fix a typo causing EXT_color_buffer_float enabled on al ES3 devices

---

filament/src/details/Engine.cpp

Fix missing createFence

---

android/filament-android/src/main/java/com/google/android/filament/View.java

Add fields used by JNI to proguard rules

---

filament/backend/src/opengl/OpenGLTimerQuery.cpp

fix possible NPE crasher in timerquery

---

android/filament-android/src/main/cpp/MaterialInstance.cpp
android/filament-android/src/main/cpp/TextureSampler.cpp
android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java
android/filament-android/src/main/java/com/google/android/filament/TextureSampler.java
filament/backend/include/backend/DriverEnums.h
filament/backend/src/metal/MetalState.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/vulkan/VulkanSamplerCache.cpp
filament/backend/src/vulkan/VulkanSamplerCache.h
filament/include/filament/TextureSampler.h
libs/utils/include/utils/algorithm.h

- we don't rely on it being 32-bits

remove the anonymous union in SamplerParams

---

filament/src/PostProcessManager.cpp

we were accessing an uninitialized LOD.

fix lenseflare effect

---

filament/backend/include/backend/Program.h
filament/backend/src/Program.cpp

It is currently not needed, AFAIK, and it was not implemented properly.

remove Program operator=

---

NEW_RELEASE_NOTES.md
android/filament-android/src/main/cpp/LightManager.cpp
android/filament-android/src/main/java/com/google/android/filament/LightManager.java
filament/include/filament/LightManager.h
filament/src/PerViewUniforms.cpp
filament/src/ShadowMap.cpp
filament/src/ShadowMapManager.cpp
filament/src/components/LightManager.h
libs/math/include/math/TQuatHelpers.h
libs/math/include/math/mathfwd.h
libs/math/include/math/quat.h
libs/viewer/src/Settings.cpp
libs/viewer/src/ViewerGui.cpp
web/filament-js/jsbindings.cpp

This setting only exists for artistic reasons.
b/297095805

Directional shadows can now be transformed

---

android/filament-android/src/main/java/com/google/android/filament/LightManager.java
filament/include/filament/LightManager.h
filament/src/ShadowMap.cpp
filament/src/ShadowMap.h
filament/src/ShadowMapManager.cpp
filament/src/ShadowMapManager.h

the shadow far plane (shadowFar) was only partially taken into account

repair ShadowOptions::shadowFar

---

filament/backend/src/vulkan/VulkanBlitter.cpp
filament/backend/src/vulkan/VulkanCommands.cpp
filament/backend/src/vulkan/VulkanCommands.h
filament/backend/src/vulkan/VulkanConstants.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanImageUtility.cpp
filament/backend/src/vulkan/VulkanPipelineCache.cpp
filament/backend/src/vulkan/VulkanPipelineCache.h
filament/backend/src/vulkan/VulkanReadPixels.cpp
filament/backend/src/vulkan/VulkanStagePool.cpp
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/VulkanTexture.h
filament/backend/src/vulkan/platform/VulkanPlatform.cpp

Add more fine grain debug defines and add some systrace markers.

vulkan: refactor debug defines

---

filament/backend/src/vulkan/VulkanCommands.cpp

Should only reset fences in VulkanCommands::gc

vulkan: fix fence deadlock

---

NEW_RELEASE_NOTES.md
filament/include/filament/Material.h
filament/src/Material.cpp
filament/src/MaterialParser.cpp
filament/src/MaterialParser.h
filament/src/details/Material.cpp
filament/src/details/Material.h
libs/filabridge/include/filament/MaterialChunkType.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/MaterialVariants.cpp
libs/matdbg/src/JsonWriter.cpp
libs/matdbg/src/TextWriter.cpp

new API to return a Material's supported variants

---

ios/samples/gltf-viewer/gltf-viewer.xcodeproj/project.pbxproj
ios/samples/gltf-viewer/project.yml
ios/samples/hello-ar/hello-ar.xcodeproj/project.pbxproj
ios/samples/hello-ar/project.yml
ios/samples/hello-gltf/hello-gltf.xcodeproj/project.pbxproj
ios/samples/hello-gltf/project.yml
ios/samples/hello-pbr/hello-pbr.xcodeproj/project.pbxproj
ios/samples/hello-pbr/project.yml

There are some duplicated library linkers inside ios samples Build Settings.

Fix: remove duplicated links inside ios samples.

---

filament/backend/src/vulkan/VulkanCommands.h
filament/backend/src/vulkan/VulkanHandles.h
filament/backend/src/vulkan/VulkanPipelineCache.cpp
filament/backend/src/vulkan/VulkanResources.h

- Make the size of FixedSizedVulkanResources declarable
- Rename `acquire` to `acquireAll`

vk: refactor VulkanResources.h

---

NEW_RELEASE_NOTES.md
android/filament-android/src/main/cpp/Engine.cpp
android/filament-android/src/main/java/com/google/android/filament/Engine.java
filament/include/filament/Engine.h
filament/src/details/Engine.cpp
filament/src/details/Engine.h

- Plumb Engine::Config in Java
- Add Engine::Builder for Java
- Add jobSystemThreadCount to Engine::Config
BUG=303129581

engine: add job system thread count configuration

---

filament/src/ShadowMapManager.cpp

When we update the Far plane in the projection matrix, we assumed the shape of the matrix. This fell appart when the projection matrix was (for instance) a blend between an ortho and perspective projection.
We now do this more generally, that is, with less assumptions on the projection matrix shape.

handle more generic projections for shadowFar

---

NEW_RELEASE_NOTES.md
filament/include/filament/Renderer.h
filament/src/Renderer.cpp
filament/src/details/Renderer.h
web/filament-js/jsbindings.cpp

add Renderer::getClearOptions

---

filament/src/details/Engine.cpp
filament/src/details/Engine.h
filament/src/details/Material.cpp
libs/filabridge/include/private/filament/EngineEnums.h
libs/filamat/src/shaders/CodeGenerator.cpp
samples/gltf_viewer.cpp
shaders/src/light_punctual.fs

The setting can be changed at runtime using a debug property.

Froxel visualization debug option

---

filament/backend/include/backend/platforms/PlatformEGL.h
filament/backend/include/backend/platforms/PlatformEGLHeadless.h
filament/backend/src/opengl/platforms/PlatformEGL.cpp
filament/backend/src/opengl/platforms/PlatformEGLAndroid.cpp
filament/backend/src/opengl/platforms/PlatformEGLHeadless.cpp

- EGL: fix typos in config creation (fixes ##7273)
- Add support for stenciled swapchains in EGL (fixes #7232)
- attempt to repair PlatformEGLHeadLess

EGLPlatform fixes & stencil support

---

libs/matdbg/web/experiment/app.js

screenshot of UI after adjustments:

matdbg: material info and fix resizing

---

filament/backend/include/backend/Platform.h
filament/backend/src/Platform.cpp
filament/backend/src/opengl/OpenGLBlobCache.cpp
filament/backend/src/opengl/OpenGLBlobCache.h
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/ShaderCompilerService.cpp
filament/backend/src/opengl/ShaderCompilerService.h

- the insert and retrieve handlers can now be set/unset independently. this could be useful for debugging.
- program caching is disabled if the GL implementation doesn't support it.
- removed unused code
FIXES=[307549547]

improve BlobCache API and compatibility

---

filament/backend/src/opengl/OpenGLDriver.cpp

Make sure to unbind imported textures when destroying one

---

filament/src/details/Texture.h
libs/iblprefilter/src/IBLPrefilterContext.cpp

fix max lod level computation in IBLPrefilter

---

filament/backend/src/vulkan/VulkanTexture.cpp

vk: assert updateImage is called with non-empty size

---

android/filament-android/src/main/java/com/google/android/filament/android/UiHelper.java

Add missing @NonNull annotations
FIXES=[308443790]

avoid to dereference nullable objects

---

filament/src/ShadowMap.cpp

repair visible shadow status

---

filament/backend/include/backend/BufferDescriptor.h
filament/backend/include/backend/PixelBufferDescriptor.h
filament/include/filament/View.h
libs/utils/include/utils/JobSystem.h

and attempt to make functor<->callback code less confusing.

fix [Pixel]BufferDescriptor functor callbacks

---

CMakeLists.txt
NEW_RELEASE_NOTES.md
filament/CMakeLists.txt
filament/src/details/Engine.cpp
filament/src/details/Skybox.cpp
filament/src/materials/blitLow1.mat
libs/filagui/CMakeLists.txt
libs/filagui/src/materials/uiBlit1.mat

This allows clients to selectively exclude feature level 0 support.

Add FILAMENT_ENABLE_FEATURE_LEVEL_0 option

---

filament/backend/CMakeLists.txt
filament/backend/test/BackendTest.cpp
filament/backend/test/PlatformRunner.h
filament/backend/test/linux_runner.cpp
filament/backend/test/mac_runner.mm
filament/backend/test/test_FeedbackLoops.cpp

- Also fixed a leak in `test_FeedbackLoops`

backend: Add linux as platform for tests

---

filament/include/filament/Material.h
filament/include/filament/View.h

Fix compilation errors when compiling with gcc on Linux

---

android/filament-android/src/main/java/com/google/android/filament/View.java

Fix typo in getStereoscopicOptions Java

---

libs/filamat/src/sca/GLSLTools.cpp
libs/utils/include/utils/ostream.h
libs/utils/src/Log.cpp
libs/utils/src/ostream.cpp
libs/utils/src/ostream_.h
libs/utils/test/test_sstream.cpp

this is a private API to capture filament's logs.

add a way to set a log consumer 

---

android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/Options.h
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/details/Renderer.cpp
filament/src/details/View.cpp
filament/src/details/View.h
filament/src/materials/antiAliasing/taa.mat
libs/viewer/src/Settings_generated.cpp
libs/viewer/src/Settings_generated.h
libs/viewer/src/ViewerGui.cpp
web/filament-js/extensions_generated.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings_generated.cpp
web/filament-js/jsenums_generated.cpp

- fix variance + AABB history clipping (we were computing the union of both AABB instead of the intersection).
- added a setting for the variance parameter
- added a setting for the jitter pattern
- improved some default values
- fixed a few comments
- smaller code tweaks to facilitate future improvements

TAA improvements

---

filament/src/PostProcessManager.cpp
filament/src/materials/antiAliasing/taa.mat

when upscaling is off, the confidence value is always 1.

taa: fixes input filtering option=OFF when upscaling is off

---

android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/Options.h
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/details/Renderer.cpp
filament/src/fg/details/Resource.h
filament/src/materials/antiAliasing/taa.mat
filament/src/materials/fsr/fsr_rcas.mat
libs/viewer/src/Settings_generated.cpp
libs/viewer/src/ViewerGui.cpp
web/filament-js/extensions_generated.js
web/filament-js/filament.d.ts
web/filament-js/jsbindings_generated.cpp
web/filament-js/jsenums_generated.cpp

We use the RCAS algorithm from FSR1. This is useful for when TAA
upscaling is enabled and similar to to what FSR2 is doing.

Add sharpening option to TAA 

---

libs/utils/src/CallStack.cpp

Note: this currently requires to compile filament with API_LEVEL 33.

support execinfo.h on Android 33 and above

---

android/filament-android/src/main/cpp/Engine.cpp
android/filament-android/src/main/java/com/google/android/filament/Engine.java
filament/include/filament/Engine.h
filament/src/ResourceAllocator.cpp
filament/src/ResourceAllocator.h
filament/src/details/Engine.cpp

Resource allocator cache params can be set in Engine::Config

---

libs/camutils/src/FreeFlightManipulator.h

when the time step was getting to large, the velocity update could become unstable and the camera would oscillate and eventually fly off.

fix velocity update in FreeFlightManipulator

---

filament/backend/include/backend/platforms/PlatformEGL.h
filament/src/details/SwapChain.cpp
filament/src/details/SwapChain.h

For debugging we add a way to recreate the SwapChain with different flags.

Small improvements and cleanup to SwapChain

---

filament/src/details/VertexBuffer.cpp

Previous commit [1] changed the semantic of the index to mBufferObjects. Here we just make sure that if a buffer has been allocated, we don't allocate another (otherwise, we'd leak).
Also cleaned up `updateBoneIndicesAndWeights` indexing
[1]: https://github.com/google/filament/commit/a3131a64b6cef2306965eec35a2f9a348601fc00

engine: avoid leaking vertex buffer

---

libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/MaterialInfo.h
libs/gltfio/src/JitShaderProvider.cpp

It generates required shader code for multiview based on parameters.

Update code generator for multiview

---

tools/matc/src/matc/ParametersProcessor.cpp

This fixes a warning for 6601c7c2b5a05c5e41920fa86de74c65ae430ba8

Fix a warning

---

libs/geometry/src/MikktspaceImpl.cpp
libs/geometry/src/MikktspaceImpl.h
libs/geometry/src/TangentSpaceMesh.cpp
libs/geometry/src/TangentSpaceMeshInternal.h

- Fix missing attributes in TangentSpaceMesh
- Fix missing reference in MikktspaceImpl.cpp

geometry: fix mikktspace wrapper

---

filament/backend/src/vulkan/VulkanConstants.h
filament/backend/src/vulkan/VulkanHandles.h
filament/backend/src/vulkan/VulkanTexture.cpp

- Add description to a few debug options
- Set correct usage flag for blit-src/dest images
- Correctly initialize a debug-only field in VulkanProgram

vk: minor fixes

---

filament/backend/src/opengl/OpenGLDriver.cpp

gl: Don't reference swapchain obj on Web

---

libs/iblprefilter/src/materials/equirectToCube.mat

Fixes IBL prefilter has floor and ceiling flipped

---

filament/src/PostProcessManager.cpp

This change allows the combine function for multiview to be able to combine more than two views side-by-side.

Facilitate four views for multiview

---

android/filament-android/src/main/cpp/Engine.cpp
android/filament-android/src/main/java/com/google/android/filament/Engine.java
filament/backend/include/backend/Platform.h
filament/backend/include/private/backend/HandleAllocator.h
filament/backend/src/HandleAllocator.cpp
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanResourceAllocator.h
filament/include/filament/Engine.h
filament/src/details/Engine.cpp

Add an option to disable use-after-free checks in the backend

---

filament/src/materials/skybox.mat

Fixes #7151
See my comment here: https://github.com/google/filament/issues/7151#issuecomment-1871432263

Improve Skybox eyeDirection precision

---

libs/utils/include/utils/Panic.h
libs/utils/src/Panic.cpp

the user can now set a panic handler callback

---

docs/Materials.md.html
filament/src/MaterialParser.cpp
filament/src/MaterialParser.h
filament/src/details/Material.cpp
filament/src/details/Material.h
libs/filabridge/include/filament/MaterialChunkType.h
libs/filabridge/include/filament/MaterialEnums.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/ShaderGenerator.cpp
libs/gltfio/src/UbershaderProvider.cpp
libs/matdbg/src/CommonWriter.h
libs/uberz/src/WritableArchive.cpp
tools/matc/src/matc/ParametersProcessor.cpp

add support for custom blend functions

---

libs/utils/CMakeLists.txt
libs/utils/include/utils/android/Systrace.h

make the Systrace class public

---

filament/backend/src/vulkan/spirv/VulkanSpirvUtils.cpp

vk: Fix clang-18 compiler warning

---

libs/utils/include/utils/JobSystem.h
libs/utils/src/JobSystem.cpp

- don't use thread affinity for the thread-pool
- cleanup and small improvements to JobSystem

improvements to JobSystem

---

android/filament-android/src/main/cpp/Engine.cpp
android/filament-android/src/main/java/com/google/android/filament/Engine.java
filament/include/filament/Engine.h
filament/src/Engine.cpp
filament/src/details/Engine.cpp
filament/src/details/Engine.h
web/filament-js/jsbindings.cpp

add a couple way of validating MaterialInstances

---

android/filament-android/src/main/cpp/View.cpp
android/filament-android/src/main/java/com/google/android/filament/View.java
filament/include/filament/View.h
filament/src/View.cpp
filament/src/details/Renderer.cpp
filament/src/details/View.h
libs/filamentapp/src/FilamentApp.cpp
web/filament-js/jsbindings.cpp

- also add a method to query if a camera was set

don't crash if we don't have a Camera set on View

---

filament/src/details/Material.cpp
filament/src/details/Material.h

cleanup details/Material.h

---

filament/backend/include/backend/Program.h
filament/backend/src/Program.cpp
filament/backend/src/metal/MetalShaderCompiler.mm
filament/backend/test/ShaderGenerator.cpp
filament/backend/test/ShaderGenerator.h
filament/backend/test/test_ComputeBasic.cpp
filament/src/MaterialParser.cpp
filament/src/MaterialParser.h
filament/src/details/Engine.h
filament/src/details/Material.cpp
filament/test/filament_test_material_parser.cpp

Support backends with multiple shader languages and precompiled Metal libraries

---

filament/backend/include/backend/Handle.h
filament/src/PerShadowMapUniforms.cpp
filament/src/PerShadowMapUniforms.h
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
filament/src/details/VertexBuffer.cpp
libs/utils/include/utils/StructureOfArrays.h

- add missing includes in PerShadowMapUninforms and FRenderableManager
- fix StructureOfArray::push_back(&&) which did a copy instead of a move
- give proper move semantics to Handle<>

small cleanups and fixes

---

libs/utils/include/utils/algorithm.h
libs/utils/test/test_algorithm.cpp

This is needed for utils::bitset8 and bitset16.

implement 16 and 8 bits clz, ctz and popcount

---

filament/src/RenderPass.cpp
filament/src/RenderPass.h
filament/src/details/Renderer.cpp

- it was broken by a wrong assertion
- also auto instancing + stereo instancing was always broken, but this makes it work

repair instanced stereo in debug builds

---

filament/backend/src/metal/MetalBuffer.h
filament/backend/src/metal/MetalBuffer.mm
filament/backend/src/metal/MetalBufferPool.mm
filament/backend/src/metal/MetalDriver.mm

Metal: track types of buffers

---

libs/utils/include/utils/Panic.h
libs/utils/src/Panic.cpp

currently it only returns the format string.

add getReasonLiteral() on TPanic

---

android/filament-android/src/main/cpp/Engine.cpp
android/filament-android/src/main/java/com/google/android/filament/Engine.java
filament/include/filament/Engine.h
filament/src/Engine.cpp
filament/src/details/Engine.cpp
filament/src/details/Engine.h
web/filament-js/jsbindings.cpp

Engine::unprotected() drops the command queue back to unprotected mode

---

filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/platform/VulkanPlatform.cpp

BUG=[332425392]
FIXES=[346860138]
Checks if the vulkan driver supports multiview. The result is stored in the vulkan context.

Checks if the multiview extension is supported

---

filament/backend/src/opengl/ShaderCompilerService.cpp
filament/backend/src/opengl/ShaderCompilerService.h

inject the missing packing/unpacking function in ESSL 3.0

---

android/filament-android/src/main/cpp/Engine.cpp
android/filament-android/src/main/cpp/Renderer.cpp
android/filament-android/src/main/java/com/google/android/filament/Engine.java
android/filament-android/src/main/java/com/google/android/filament/Renderer.java
filament/include/filament/Engine.h
filament/include/filament/Renderer.h
filament/src/Engine.cpp
filament/src/Renderer.cpp
filament/src/details/Renderer.cpp
filament/src/details/Renderer.h
web/filament-js/jsbindings.cpp

an easier way to pipe vsync time to beginFrame

---

filament/docs/SpirvDebugging.md
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
tools/matc/src/matc/CommandlineConfig.cpp
tools/matc/src/matc/Config.h
tools/matc/src/matc/MaterialCompiler.cpp

This is useful for debugging shaders and the spirv pipeline.

Add saveRawVariants flag to matc

---

filament/backend/src/vulkan/VulkanDriver.cpp

Fix feature level detection for VulkanDriver

---

filament/src/RenderPass.cpp

The batch size was calculated incorrectly, which in theory could lead to command buffer overflows (albeit unlikely).

RenderPass batch size was too small

---

filament/backend/include/private/backend/DriverAPI.inc
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/src/details/MaterialInstance.cpp
filament/src/details/Texture.cpp
filament/src/details/Texture.h

For descriptor sets, we want a 1:1 mapping between external image and texture handle.

New external image API

---

filament/backend/src/CommandBufferQueue.cpp

- use the same code on both ends of updating the free space. i.e. both side compute the "used" space in exactly the same way. the math was the same before, but the code was different which could be confusing.
- assert for overflow before queuing the buffer. It wouldn't matter anyways, because it's done with the condition lock held, so the consumer would never have a chance to deuque it. still, less  confusing.

minor cleanups in CommanmdBufferQueue

---

filament/src/ShadowMap.cpp

Remove flaky assertion in ShadowMap

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.mm
filament/src/details/Material.cpp
shaders/src/light_indirect.fs

Metal: fix static texture target on more devices

---

filament/backend/src/opengl/ShaderCompilerService.cpp

The current behavior is to get a UB, which usually is a crash. So this is better.

assert when a program compilation fails

---

filament/src/details/Renderer.cpp

Fix skipFrame incorrectly asserts in some cases

---

filament/src/RenderPass.cpp
filament/src/RenderPass.h

make mCommandBegin and mCommandEnd const* const, this allows to make sort() And resize() static, and instanceify() almost static..

clean-up RenderPass a bit

---

filament/include/filament/Engine.h
filament/src/Engine.cpp
filament/src/ResourceList.h
filament/src/details/Engine.cpp
filament/src/details/Engine.h

This is intended for debugging.
BUGS=[358111049]

Add a way to retrieve the list of all resources

---

filament/src/ShadowMap.cpp

min() and lowest() are different!

fix typo when calculation shadowmap frustum

---

filament/include/filament/View.h
filament/src/ShadowMapManager.cpp
filament/src/ShadowMapManager.h
filament/src/View.cpp
filament/src/details/View.h
libs/filamentapp/include/filamentapp/Cube.h
libs/filamentapp/include/filamentapp/FilamentApp.h
libs/filamentapp/src/Cube.cpp
libs/filamentapp/src/FilamentApp.cpp

improve FilamentApp split-view mode

---

filament/src/RendererUtils.cpp

layerCount is already set to colorBufferDesc.depth, directly use it instead.

Cleanup color pass for multiview

---

docs/Materials.md.html
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/CodeGenerator.h
tools/matc/src/matc/ParametersProcessor.cpp

e.g.:
variables : [
{
name : vertex,
precision : medium,
}
],

custom variables can now have their precision specified

---

filament/src/PostProcessManager.cpp
filament/src/materials/blitArray.mat
filament/src/materials/blitLow.mat

This is needed for debugging, but is a pretty low-hanging fruit.

add support for subresources in "blit"

---

filament/backend/src/metal/MetalBuffer.h
filament/backend/src/metal/MetalBuffer.mm
filament/backend/src/metal/MetalDriver.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.mm

Metal: annotate memory allocation failures with buffer tag

---

filament/backend/include/private/backend/HandleAllocator.h

this is because the key used to retrieve the tag was not "truncated" like it was when inserting the tag in the hash-map.

a handle with a tag would sometime return "no tag"

---

filament/src/PostProcessManager.cpp

Set postprocess descriptor set for color grading

Fix a crash for color grading

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/src/details/RenderTarget.cpp

Support 3D texture attachments

---

filament/src/RenderPass.cpp
filament/src/details/Renderer.cpp
libs/iblprefilter/src/IBLPrefilterContext.cpp

- fix a dangling texture issue
- make sure to use the post-process descriptor set with post-process materials

fix a couple issues with descriptor set bindings

---

filament/backend/src/metal/MetalBuffer.h
filament/backend/src/metal/MetalBuffer.mm
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm

Metal: enhance assertions for buffer uploads

---

libs/utils/src/JobSystem.cpp

Implement setThreadPriority for Apple devices

---

filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h

It always references static data. Additionnaly, we don't need to use a vector to store the specialization constants, because it's also all static data.
And finally, we don't need a boolean to know the state of the PostProcessMaterial, the mSize field can encode the same information.

no need to copy the PostProcessMaterial mConstants field

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalEnums.h
filament/src/details/IndexBuffer.cpp

Metal: add better logging for invalid index element size

---

filament/src/details/Renderer.cpp

Check that SwapChain is valid in endFrame

---

RELEASE_NOTES.md

I really enjoyed using this project, nice work! Caught a typo though 😛

Update RELEASE_NOTES.md, fix a typo

---

NEW_RELEASE_NOTES.md
filament/backend/include/backend/DriverEnums.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/BindingMap.h
filament/backend/src/opengl/GLDescriptorSet.cpp
filament/backend/src/opengl/OpenGLProgram.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/src/ds/DescriptorSetLayout.cpp
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/eiff/MaterialInterfaceBlockChunk.cpp

descriptor layouts distinguish samplers and external samplers

---

filament/backend/src/metal/MetalDriver.mm

BUGS=[371998320]
This fixes a potential crash where a `SwapChain` is destroyed and then `renderStandaloneView` is called.
This code path is problematic because `renderStandaloneView` does _not_ call `driver.makeCurrent`, so if the previously-used `SwapChain` is destroyed, then `currentDrawSwapChain` and `currentReadSwapChain` will be invalid pointers.

Metal: unbind SwapChain upon destruction

---

filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/metal/MetalShaderCompiler.h
filament/backend/src/metal/MetalState.h

Metal: remove cached pipeline states with deleted programs

---

shaders/src/shadowing.fs

fix some missing highp qualifiers

---

NEW_RELEASE_NOTES.md
filament/backend/src/vulkan/VulkanStagePool.cpp

vk: fix stage pool gc logic

---

filament/src/RenderPass.cpp

When a viewport with a negative left/bottom was used, an assert would trigger on debug builds and release builds would get a wrong scissor.
This bug was introduced recently, we now do the offset/clipping math in 64 bits, which is way simpler and convert back to Viewport at the end.
BUGS=[381902791]

Fix scissor with negative left/bottom

---

filament/src/RenderPass.cpp

Fix an assert that prevented instancing to work

---

filament/backend/src/metal/MetalContext.h
filament/backend/src/metal/MetalDriver.mm

Metal: avoid crashing for invalid programs

---

filament/backend/src/PlatformFactory.cpp
filament/backend/src/metal/MetalBuffer.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalEnums.h
filament/backend/src/metal/MetalHandles.mm
filament/backend/src/metal/MetalPlatform.mm
filament/backend/src/metal/MetalState.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/opengl/OpenGLContext.cpp
filament/backend/src/opengl/OpenGLContext.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/gl_headers.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/platform/VulkanPlatformApple.mm
filament/backend/test/BackendTest.cpp
filament/backend/test/test_Blit.cpp
filament/backend/test/test_FeedbackLoops.cpp
filament/backend/test/test_ReadPixels.cpp
libs/bluevk/include/bluevk/BlueVK.h
libs/filamentapp/src/FilamentApp.cpp
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/FFilamentAsset.h
samples/gltf_viewer.cpp
third_party/clang/iOS.cmake

Rename IOS define to FILAMENT_IOS

---

filament/backend/src/vulkan/VulkanContext.cpp
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanFboCache.cpp
filament/backend/src/vulkan/VulkanHandles.cpp
filament/backend/src/vulkan/VulkanSamplerCache.cpp
filament/backend/src/vulkan/VulkanSwapChain.cpp
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/platform/VulkanPlatform.cpp
filament/backend/src/vulkan/platform/VulkanPlatformAndroid.cpp
filament/backend/src/vulkan/platform/VulkanPlatformApple.mm
filament/backend/src/vulkan/platform/VulkanPlatformLinuxWindows.cpp
filament/backend/src/vulkan/platform/VulkanPlatformSwapChainImpl.cpp

vk: print error code on failure for vk calls

---

BUILDING.md
build/web/ci-common.sh
web/filament-js/jsbindings.cpp

Fix Web build, update Emscripten SDK to 3.1.60

---

filament/backend/include/backend/DescriptorSetOffsetArray.h
filament/backend/include/backend/DriverEnums.h
filament/backend/src/CommandStream.cpp
filament/backend/src/Handle.cpp
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/ostream.cpp
libs/utils/include/utils/CString.h
libs/utils/include/utils/Invocable.h
libs/utils/src/CString.cpp

Fix DEBUG_COMMAND_STREAM mode

---

libs/filamat/src/GLSLPostProcessor.cpp

filamat: fix spirv remap intialization

---

android/filament-android/src/main/java/com/google/android/filament/View.java
filament/CMakeLists.txt
filament/include/filament/Options.h
filament/src/PostProcessManager.cpp
filament/src/PostProcessManager.h
filament/src/details/Renderer.cpp
filament/src/materials/colorGrading/colorGrading.mat
filament/src/materials/sgsr/LICENSE.txt
filament/src/materials/sgsr/sgsr1.mat
filament/src/materials/sgsr/sgsr1_shader_mobile.fs

SGSR stands for Snapdragon Game Super Resolution. It is an efficient upscaler for mobile.
Split the upscaling passes into multiple methods in PostProcessManager. Also, add a way to preserve the alpha channel in the FXAA pass.

Add support for SGSR 1.0

---

NEW_RELEASE_NOTES.md
filament/backend/include/private/backend/Driver.h
filament/backend/src/metal/MetalDriver.h
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/noop/NoopDriver.cpp
filament/backend/src/noop/NoopDriver.h
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanDriver.h
filament/src/details/Engine.cpp
filament/src/details/Engine.h
libs/matdbg/include/matdbg/DebugServer.h
libs/matdbg/include/matdbg/JsonWriter.h
libs/matdbg/include/matdbg/ShaderReplacer.h
libs/matdbg/src/ApiHandler.cpp
libs/matdbg/src/DebugServer.cpp
libs/matdbg/src/JsonWriter.cpp
libs/matdbg/src/ShaderReplacer.cpp
libs/matdbg/web/api.js
libs/matdbg/web/app.js
tools/matinfo/src/main.cpp

Fixes #8261
Note that I haven't tested this on macOS yet.

matdbg: add support for essl1 shader debugging

---

filament/src/materials/colorGrading/colorGradingAsSubpass.mat

This broke in 48a2c64. Fixes #8401.

fix color grading as subpass

---

filament/backend/include/backend/Platform.h
filament/backend/src/Platform.cpp

Without it, DEBUG_COMMAND_STREAM does not compile.

Add ostream operator for ExternalImageHandle

---

filament/backend/src/vulkan/VulkanContext.h
filament/backend/src/vulkan/VulkanTexture.cpp
filament/backend/src/vulkan/platform/VulkanPlatform.cpp

vk: fix rendering to 2D view of 3D image

---

android/filament-android/src/main/cpp/MaterialInstance.cpp
android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java
filament/include/filament/MaterialInstance.h
filament/src/MaterialInstance.cpp
filament/src/RenderPass.cpp
filament/src/details/MaterialInstance.cpp
filament/src/details/MaterialInstance.h
web/filament-js/jsbindings.cpp

the new MaterialInstance::setCullingMode(color, shadow) API allows to set a separate face culling mode for the color pass and the shadow  passes.
FIXES[391679058]

the shadow passes get their own face culling mode

---

filament/src/ds/ColorPassDescriptorSet.cpp

descset: fix lights UBO size on setBuffer

---

android/filament-android/src/main/cpp/Texture.cpp
android/filament-android/src/main/java/com/google/android/filament/Texture.java
filament/include/filament/Texture.h
filament/src/Texture.cpp
filament/src/details/Texture.cpp
filament/src/details/Texture.h
web/filament-js/jsbindings.cpp

This will allow Filament's users to perform check beforehand.

Implement query to check if texture format is mipmappable

---

filament/backend/src/metal/MetalHandles.mm

Metal: avoid TSAN warnings inside MetalHandles

---

android/filament-android/src/main/cpp/Texture.cpp
android/filament-android/src/main/java/com/google/android/filament/Texture.java
filament/include/filament/Texture.h
filament/src/Texture.cpp
web/filament-js/jsbindings.cpp

This will help Filament users to perform this check beforehand.

Implement a query to check if combination of texture format, pixel data format and type is valid

---

libs/gltfio/src/ResourceLoader.cpp

gltfio: undo clearing when resource is loaded

---

filament/backend/include/private/backend/HandleAllocator.h

Add workaround for handle tag issue

---

filament/src/details/MaterialInstance.h

This fixes some Scuba breakages introduced with https://github.com/google/filament/pull/8422. Not sure if it's the right fix though.

Make setCullingMode also set shadow culling

---

filament/backend/CMakeLists.txt
filament/backend/src/vulkan/VulkanDriver.cpp
filament/backend/src/vulkan/VulkanPipelineCache.cpp
filament/backend/src/vulkan/VulkanPipelineCache.h
filament/backend/src/vulkan/utils/Conversion.h

- remove unused code and fields
- reformatted

vk: clean-up VulkanPipelineCache

---

filament/backend/src/metal/MetalDriver.mm

Fix: Metal crashing when a render pass is abandoned

---

CMakeLists.txt
android/build.gradle
android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java
android/filament-android/CMakeLists.txt
android/filament-android/src/main/java/com/google/android/filament/Engine.java
android/gradle.properties
build.sh
filament/backend/CMakeLists.txt
filament/backend/include/backend/DriverEnums.h
filament/backend/src/PlatformFactory.cpp
filament/backend/src/webgpu/WebGPUDriver.cpp
filament/backend/src/webgpu/WebGPUDriver.h
filament/backend/src/webgpu/WebGPUPlatform.cpp
filament/backend/src/webgpu/WebGPUPlatform.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/sca/GLSLTools.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
third_party/dawn/tnt/001-dawn-static-lib.patch
third_party/dawn/tnt/CMakeLists.txt
third_party/dawn/tnt/README.md

These changes add Dawn as a webgpu backend dependency to filament and adds stub implementation to link against it.

Compile webgpu library and stub implementation.

---

libs/fgviewer/web/app.js

When the subresources are collapsed:
- Aggregate the subresource usage to the parent resource
- Show the number of subresources next to the parent resource

fgviewer web view improvements

---

filament/src/details/Material.h
libs/matdbg/src/ApiHandler.cpp
libs/matdbg/src/ShaderInfo.cpp
libs/matdbg/web/api.js
libs/matdbg/web/app.js

- The set of active variants were not set correctly for surface materials since the frag/vert pairs could have different variant.
- Fix the default selection logic in the UI
- Random clean-ups
FIXES=328699979

matdbg: fix variant issue for surface materials

---

libs/fgviewer/web/app.js

- Collapse subresources by default
- Rename the variable accordingly for better readability

[fgviewer] Collapse subresources by default in web view

---

android/filamat-android/CMakeLists.txt
build.sh
filament/backend/src/webgpu/WebGPUDriver.cpp

Also fix a change in backend API.

webgpu: fix filamat android build

---

.github/workflows/presubmit.yml

Disable renderdiff for breakage

Disable renderdiff for breakage (#8500)

---

libs/fgviewer/src/ApiHandler.cpp
libs/fgviewer/src/DebugServer.cpp
libs/fgviewer/src/FrameGraphInfo.cpp
libs/fgviewer/src/JsonWriter.cpp
libs/fgviewer/web/app.js

- Add missing includes to prevent warnings from clangtidy
- Fix logic in web view

Some cleanups

---

filament/src/details/ColorGrading.cpp
filament/src/details/Engine.h

Note that the flag is default to false while we roll out this feature.

engine: Add 1D LUT feature flag

---

filament/backend/test/test_Blit.cpp
filament/backend/test/test_BufferUpdates.cpp
filament/backend/test/test_Callbacks.cpp
filament/backend/test/test_FeedbackLoops.cpp
filament/backend/test/test_LoadImage.cpp
filament/backend/test/test_MRT.cpp
filament/backend/test/test_MipLevels.cpp
filament/backend/test/test_MissingRequiredAttributes.cpp
filament/backend/test/test_PushConstants.cpp
filament/backend/test/test_ReadPixels.cpp
filament/backend/test/test_RenderExternalImage.cpp
filament/backend/test/test_Scissor.cpp
filament/backend/test/test_StencilBuffer.cpp

Use the backend test cleanup helper.

---

filament/backend/CMakeLists.txt
filament/backend/test/Shader.cpp
filament/backend/test/Shader.h
filament/backend/test/test_Blit.cpp
filament/backend/test/test_BufferUpdates.cpp

Add helper for creating shaders in tests.

---

filament/src/PostProcessManager.cpp
filament/src/materials/sgsr/sgsr1.mat

SGSR upscaling didn't take the viewport into account.

fix SGSR upscaling when a subpass is used

---

filament/src/details/Renderer.cpp

When Color grading is using the optimized subpass mode, it could fail if it was the last pass. This is because in that case it renders directly into the custom rendertarget which doesn't have MRTs (which is needed). The fix is to issue an extra blit.
FIXES=[406343577]

Fix subpasses with custom render targets

---

third_party/dawn/tnt/CMakeLists.txt

Android webgpu build was failing after dawn update with build.sh

Fix webgpu android build after dawn update

---

filament/backend/CMakeLists.txt
filament/backend/src/webgpu/WebGPUDriver.cpp
filament/backend/src/webgpu/WebGPUDriver.h
filament/backend/src/webgpu/WebGPUHandles.cpp
filament/backend/src/webgpu/WebGPUHandles.h
filament/backend/src/webgpu/WebGPUSwapChain.cpp
filament/backend/src/webgpu/WebGPUSwapChain.h
filament/backend/src/webgpu/platform/WebGPUPlatformApple.mm
libs/filamentapp/src/FilamentApp.cpp
samples/multiple_windows.cpp

Implement basic background color rendering through webgpu backend.
Some hardcoded code has been introduced for testing purpose, this will be cleaned/refactored, as backend gets mature.
BUGS = [397404954]

background color rendering using Webgpu 

---

filament/backend/src/vulkan/platform/VulkanPlatformApple.mm

__APPLE__ is defined for both macos and ios platform. #elif code will never be excuted.

Cleanup the dead code from VulkanPlatformApple.mm

---

filament/backend/src/webgpu/WebGPUDriver.cpp
filament/backend/src/webgpu/WebGPUDriver.h
filament/backend/src/webgpu/WebGPUHandles.cpp
filament/backend/src/webgpu/WebGPUHandles.h

adds the initial implementation of Vertex and Index Buffer
BUGS = [403577801]

wgpu: Add Vertex and Index Buffer 

---

filament/backend/src/opengl/ShaderCompilerService.cpp
filament/backend/src/opengl/ShaderCompilerService.h

There's no functional difference.

Cleanup shader compiler

---

filament/backend/CMakeLists.txt
filament/backend/test/BackendTest.cpp
filament/backend/test/BackendTest.h
filament/backend/test/PlatformRunner.cpp
filament/backend/test/PlatformRunner.h
filament/backend/test/Skip.cpp
filament/backend/test/Skip.h
filament/backend/test/linux_runner.cpp
filament/backend/test/mac_runner.mm
filament/backend/test/test_Callbacks.cpp
filament/backend/test/test_PushConstants.cpp

Add a macro for skipping tests based on backend/OS.

---

filament/backend/src/webgpu/TEMPORARY_webgpu_cpp_copy.h

This is just to stash the Dawn generated file for easier internal communication (Passing links about specific lines)

WGPU: Upload wgpu cpp header to easily reference in discussions

---

filament/backend/src/webgpu/WebGPUDriver.cpp

These are minor tweaks based on improved understanding

webgpu: Ebridgewater/webgpu minor integration

---

test/code-correctness/src/run.py
test/code-correctness/test.sh

- Sort failures alphabetically
- Add way to suppress error when necessary
- Add way to run test on a subset of files for testing
- Fix case where number of files is less than number of workers

Improve code-correctness script

---

filament/backend/src/webgpu/WGPUProgram.cpp

BUGS = [413684507]
change the callback mode to WaitAnyOnly

wgpu: Change callback mode to AllowProcessEvents

---

libs/matdbg/src/ApiHandler.cpp
libs/matdbg/src/JsonWriter.cpp
libs/matdbg/web/api.js
libs/matdbg/web/app.js

Bugs=397448737
Add WebGPU Support to matdbg

wgpu: Add WebGPU to matdbg

---

filament/backend/src/CommandStream.cpp
filament/backend/src/vulkan/VulkanConstants.h
libs/gltfio/src/AssetLoader.cpp
libs/gltfio/src/ResourceLoader.cpp
libs/gltfio/src/Utility.cpp
libs/utils/include/utils/Systrace.h
libs/utils/include/utils/android/Systrace.h
libs/utils/include/utils/darwin/Systrace.h
libs/utils/src/JobSystem.cpp
libs/utils/src/android/Systrace.cpp
libs/utils/src/darwin/Systrace.cpp

This reverts commit ca3ff7e08ed15568c49b7239d87a6832abe7804a.

Revert "Use the Perfetto SDK instead of ATRACE"

---

filament/backend/src/metal/MetalEnums.h

this prevented to upload depth data into a depth texture

add missing depth formats to getMetalFormat()

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/webgpu/WebGPUDriver.cpp
filament/backend/src/webgpu/WebGPUDriver.h
filament/backend/src/webgpu/WebGPUHandles.cpp
filament/backend/src/webgpu/WebGPUHandles.h
filament/backend/test/Shader.cpp
filament/src/details/Material.cpp
libs/filabridge/src/DescriptorSets.cpp
third_party/dawn/src/dawn/native/CommandValidation.cpp

Currently contains the hacky commits to get HelloTriangle on WebGPU

webgpu: Webgpu/hello triangle v1

---

.github/workflows/presubmit.yml
test/renderdiff/src/golden_manager.py
test/renderdiff/src/image_diff.py
test/renderdiff/src/run.py
test/renderdiff/src/workflow_presubmit_msg.py
test/renderdiff/test.sh

- Add GoldenManager to manage access to the repo containing the goldens
- Add tif comparison code
- Enable comparison by default for actual test

renderdiff: add golden repo support

---

build.sh

Clean up ndk version in build.sh

---

docs_src/markdeep/Materials.md.html
filament/backend/src/metal/MetalDriver.mm
filament/backend/src/metal/MetalHandles.mm
libs/filabridge/include/private/filament/SamplerInterfaceBlock.h
libs/filabridge/src/SamplerInterfaceBlock.cpp
libs/filamat/include/filamat/Enums.h
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/Enums.cpp
libs/filamat/src/GLSLPostProcessor.cpp
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/eiff/MaterialInterfaceBlockChunk.cpp
tools/matc/src/matc/ParametersProcessor.cpp

Materials: allow specifying the shader stages for samplers

---

filament/backend/src/webgpu/WebGPUHandles.cpp
filament/backend/src/webgpu/WebGPUHandles.h

Picks an appropriate aspect based on format and usage.

webgpu: TextureView Aspect

---

libs/filamentapp/src/FilamentApp.cpp

Resizes the metal layer for webgpu on mac

webgpu: Resize window fix on mac

---

filament/backend/test/ShaderGenerator.cpp
filament/backend/test/test_LoadImage.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
shaders/src/common_getters.glsl
shaders/src/common_graphics.fs
shaders/src/post_process_main.vs
shaders/src/surface_getters.vs
shaders/src/surface_main.vs

Webgpu: Use WebGPU target rather than rely on Vulkan similarities

---

filament/backend/test/ShaderGenerator.cpp
filament/backend/test/ShaderGenerator.h
filament/backend/test/TrianglePrimitive.h
filament/backend/test/test_PushConstants.cpp

backend-test: fix push constant test for vk

---

filament/backend/include/backend/DriverEnums.h

fix typo in SamplerParams comparison operator

---

shaders/src/surface_light_punctual.fs
shaders/src/surface_lighting.fs

Avoid using paramater name "type" in shaders which is reserved in WGSL

---

filament/backend/include/backend/PixelBufferDescriptor.h
filament/backend/src/webgpu/WebGPUDriver.cpp
filament/backend/src/webgpu/WebGPUHandles.cpp
filament/backend/src/webgpu/WebGPUHandles.h

webgpu: Ebridgewater/upload texture webgpu

---

filament/backend/test/BackendTest.cpp
filament/backend/test/BackendTest.h
filament/backend/test/test_Blit.cpp
filament/backend/test/test_BufferUpdates.cpp
filament/backend/test/test_FeedbackLoops.cpp
filament/backend/test/test_LoadImage.cpp
filament/backend/test/test_MRT.cpp
filament/backend/test/test_MipLevels.cpp
filament/backend/test/test_MissingRequiredAttributes.cpp
filament/backend/test/test_ReadPixels.cpp
filament/backend/test/test_RenderExternalImage.cpp
filament/backend/test/test_Scissor.cpp
filament/backend/test/test_StencilBuffer.cpp

In backend tests replace calls to draw with draw2.

---

filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/gl_headers.cpp
filament/backend/src/opengl/gl_headers.h
filament/include/filament/RenderTarget.h
filament/include/filament/Texture.h
filament/src/details/RenderTarget.cpp
filament/src/details/Texture.cpp
filament/src/details/Texture.h
libs/filamentapp/include/filamentapp/Config.h
samples/hellostereo.cpp

Add multiview MSAA support for custom swapchain

---

filament/src/details/VertexBuffer.cpp

offset and size must now be a multiple of 4

assert vertex attribute alignment

---

filament/src/ds/DescriptorSet.cpp

that use DescriptorType::SAMPLER_EXTERNAL.

Fix broken android samples

---

filament/src/ShadowMapManager.cpp
shaders/src/post_process_main.vs
shaders/src/surface_main.vs

webgpu: Check for WGSL Shadows

---

filament/backend/src/webgpu/WebGPUDriver.cpp
filament/backend/src/webgpu/WebGPURenderTarget.cpp
filament/backend/src/webgpu/WebGPURenderTarget.h

BUGS=[422705735]
using defaultDepthStencilFormat to check stencil loadOP and storeOP

webgpu: Pass through defaultDepthStencilFormat

---

filament/backend/src/webgpu/WebGPUPipelineCreation.cpp
samples/simple_gltf_test.cpp

add a cli arg to enable MSAA on the webgpu sample

webgpu: add condition to sample

---

filament/backend/CMakeLists.txt
filament/backend/src/webgpu/SpdMipmapGenerator/SpdMipmapGenerator.cpp
filament/backend/src/webgpu/SpdMipmapGenerator/SpdMipmapGenerator.h
filament/backend/src/webgpu/WebGPUDriver.cpp
filament/backend/src/webgpu/WebGPUDriver.h
filament/backend/src/webgpu/platform/WebGPUPlatform.cpp

Note: The SPD changes are still not fully solid, which is known. The changes here should be incrementally better, as we likely do a more full rewrite in the future as time permits. 
BUGS = [423893882]

webgpu: Mipmap driver changes

---

filament/backend/src/webgpu/WebGPUPipelineCreation.cpp

check for alpha to coverage when samples > 1

webgpu: Add alphaToCoverage check

---

filament/backend/src/webgpu/WebGPUDriver.cpp
filament/backend/src/webgpu/WebGPUPipelineCreation.cpp
filament/backend/src/webgpu/WebGPUPipelineCreation.h
filament/backend/src/webgpu/WebGPURenderTarget.cpp
filament/backend/src/webgpu/WebGPURenderTarget.h
filament/backend/src/webgpu/WebGPUSwapChain.cpp
filament/backend/src/webgpu/WebGPUSwapChain.h

webgpu: Use Target buffer flags for depth and stencil

---

filament/backend/include/backend/Platform.h
filament/backend/src/opengl/platforms/PlatformEGL.cpp
filament/backend/src/vulkan/platform/VulkanPlatform.cpp

Add a knob to control the priority of the GPU work submitted to the application. Currently it's only supported for EGL.
BUGS=[416589006]

Add flag to control the GPU priority

---

libs/matdbg/src/TextWriter.cpp

matinfo: Report if a material has custom depth

---

NEW_RELEASE_NOTES.md
libs/filamat/src/shaders/ShaderGenerator.cpp

This lets user materials check if their code is executing inside the depth variant.
BUGS=[428025097]

materials: Add VARIANT_DEPTH define for depth shader variants

---

filament/backend/src/webgpu/WebGPUDriver.cpp
filament/backend/src/webgpu/WebGPURenderTarget.cpp
filament/backend/src/webgpu/WebGPUTexture.cpp
filament/backend/src/webgpu/WebGPUTexture.h

webgpu: Solve black issue screen

---

filament/src/details/Texture.cpp

We simply compute the coordinate of the last pixel that need to be  accessed and deduce its offset, which must be smaller than the  buffer size.

fix PixelBufferDescriptor overflow calculation

---

build/common/get-mesa.sh

This fixes the check for presence of `brew`.

Fix brew check in render tests

---

filament/backend/src/opengl/OpenGLBlobCache.cpp

`glProgramBinary` can succeed but result in an unlinked program, for instance if the graphics driver has been updated. This change adds a check for `GL_LINK_STATUS` in addition to `glGetError` to ensure the program is valid.
Also adds more detailed logging on failure.
BUGS=[430290459]

gl: More robustly verify cached programs

---

filament/backend/include/backend/DriverEnums.h
filament/backend/src/webgpu/WebGPUDriver.cpp

webgpu: Return Feature Levels

---

filament/backend/src/webgpu/WebGPUProgram.cpp

Replace the `try` `catch` with a `strtol` call

webgpu: Remove try catch

---

test/renderdiff/README.md

Update renderdiff README.md

---

NEW_RELEASE_NOTES.md
android/filament-android/src/main/cpp/Renderer.cpp
android/filament-android/src/main/java/com/google/android/filament/Renderer.java
filament/include/filament/Renderer.h
filament/src/FrameSkipper.cpp
filament/src/FrameSkipper.h
filament/src/Renderer.cpp
filament/src/details/Renderer.cpp
filament/src/details/Renderer.h
web/filament-js/jsbindings.cpp

Add Renderer::shouldRenderFrame() API

---

filament/backend/test/ShaderGenerator.cpp
filament/backend/test/SharedShaders.cpp

Test Shader generation was failing to return a valid shader for WebGPU
part of BUGS = [424157731]

Add missing WebGPU checks to shader generation for tests

---

filament/backend/src/webgpu/WebGPURenderTarget.cpp

webgpu: Set Layercount to 1 instead of 0

---

filament/backend/test/test_MipLevels.cpp

webgpu: Update GLSL for mip test

---

filament/src/RenderPass.cpp
filament/src/details/Engine.cpp
filament/src/details/Material.h

Fixes an issue introduced by #9025

Fix: webgpu error regarding mismatched pipeline 

---

NEW_RELEASE_NOTES.md
docs_src/src_markdeep/Materials.md.html
libs/filamat/include/filamat/MaterialBuilder.h
libs/filamat/src/MaterialBuilder.cpp
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/MaterialInfo.h
libs/filament-matp/src/ParametersProcessor.cpp
shaders/src/surface_light_directional.fs
shaders/src/surface_shading_unlit.fs

add a material parameter to control shadow far attenuation

---

filament/backend/src/webgpu/WebGPUBlitter.cpp
filament/backend/src/webgpu/WebGPUDriver.cpp
filament/backend/test/test_Blit.cpp

webgpu: Implement blitDeprecated

---

filament/backend/src/webgpu/WebGPUDriver.cpp
filament/backend/src/webgpu/WebGPUTexture.cpp
filament/backend/src/webgpu/WebGPUTexture.h
filament/backend/src/webgpu/WebGPUTextureHelpers.h
filament/backend/src/webgpu/platform/WebGPUPlatform.cpp

wgpu: add texture swizzle support

---

filament/backend/test/test_Blit.cpp
filament/backend/test/test_FeedbackLoops.cpp
filament/backend/test/test_LoadImage.cpp
filament/backend/test/test_ReadPixels.cpp
filament/backend/test/test_RenderExternalImage.cpp
filament/backend/test/test_Scissor.cpp
filament/backend/test/test_StencilBuffer.cpp

webgpu: Skip failing tests for WebGPU

---

filament/src/BufferPoolAllocator.h
filament/src/components/RenderableManager.cpp
filament/src/details/InstanceBuffer.cpp
filament/src/details/InstanceBuffer.h
filament/src/details/Scene.cpp
filament/src/details/Scene.h
filament/src/details/View.cpp
filament/src/details/View.h

Update all per-object/instance buffers all at once 

---

NEW_RELEASE_NOTES.md
filament/include/filament/View.h
filament/src/Froxelizer.cpp
filament/src/Froxelizer.h
filament/src/details/Material.cpp
libs/filabridge/include/private/filament/EngineEnums.h
libs/filamat/src/shaders/CodeGenerator.cpp
libs/filamat/src/shaders/UibGenerator.cpp

- record buffer is dynamically sized
- zLightNear/Far are now clamped to camera's near/far
- micro optimizations is froxelization code

several froxel improvements

---

tools/zbloat/README.md
tools/zbloat/evmar_bloat.py
tools/zbloat/zbloat.py

the biggest one os that we can now use it directly with a `.a`

zbloat improvements

---

android/filament-android/src/main/cpp/RenderableManager.cpp
android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
filament/include/filament/InstanceBuffer.h
filament/include/filament/RenderableManager.h
filament/src/InstanceBuffer.cpp
filament/src/RenderableManager.cpp
filament/src/components/RenderableManager.cpp
filament/src/components/RenderableManager.h
filament/src/details/InstanceBuffer.cpp
filament/src/details/InstanceBuffer.h
web/filament-js/jsbindings.cpp

add some getters

---

filament/backend/src/metal/MetalHandles.mm
filament/backend/src/opengl/OpenGLDriver.cpp
filament/backend/src/opengl/OpenGLDriver.h
filament/backend/src/vulkan/VulkanSwapChain.cpp
filament/backend/src/vulkan/VulkanSwapChain.h
filament/backend/test/test_Callbacks.cpp

Fix frame scheduled callbacks not being latched

---

filament/backend/src/opengl/OpenGLContext.cpp

enable timer queries on Mali drivers known to be good

---

filament/backend/src/metal/MetalState.mm

assert sampler function only when it's not NONE.

---

filament/backend/src/opengl/OpenGLTimerQuery.cpp
filament/backend/src/opengl/OpenGLTimerQuery.h
libs/utils/CMakeLists.txt
libs/utils/include/utils/AsyncJobQueue.h
libs/utils/src/AsyncJobQueue.cpp

this is a very simple job queue, it spawns a thread and runs the jobs
pushed to the queue in sequence.

new utility AsyncJobQueue

---

libs/utils/include/utils/Status.h
libs/utils/src/Status.cpp

- << operator doesn't have to be friend
- simplify getErrorMessage to not use strlen internally

Minor changes in utils::Status
