google/filament

- RELEASE_NOTES.md
- libs/filabridge/include/filament/MaterialEnums.h
- libs/filabridge/include/private/filament/EngineEnums.h
This is a workaround for the following Chrome issues:
https://crbug.com/1348017 Compiling GLSL is very slow with struct arrays
https://crbug.com/1348363 Lighting looks wrong with D3D11 but not OpenGL
This requires a rebuild of materials for WebGL users.
Fixes #5859.
> WASM: Set CONFIG_MAX_INSTANCES to a small value.

- RELEASE_NOTES.md
- libs/filabridge/include/filament/MaterialEnums.h
- libs/filabridge/include/private/filament/EngineEnums.h
This caused all WebGL demos to break because of a mismatch between the GLSL array size and the UBO size, because matc doesn't know if it's compiling for WebGL.  We need to fix this another way.
This reverts commit 7aa5d4a375ac1800efc5465fcbe850347f405aaf.
> Revert "WASM: Set CONFIG_MAX_INSTANCES to a small value."

- RELEASE_NOTES.md
- android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
- android/gltfio-android/src/main/cpp/ResourceLoader.cpp
- android/gltfio-android/src/main/java/com/google/android/filament/gltfio/ResourceLoader.java
- ios/samples/gltf-viewer/gltf-viewer/FILModelView.mm
- ios/samples/hello-gltf/hello-gltf/FilamentView/App.cpp
- libs/gltfio/include/gltfio/FilamentAsset.h
- libs/gltfio/include/gltfio/FilamentInstance.h
- libs/gltfio/include/gltfio/ResourceLoader.h
- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/FFilamentInstance.h
- libs/gltfio/src/FilamentInstance.cpp
- libs/gltfio/src/ResourceLoader.cpp
- libs/viewer/src/ViewerGui.cpp
- samples/gltf_instances.cpp
- samples/gltf_viewer.cpp
- web/filament-js/extensions.js
- web/filament-js/filament-viewer.js
- web/filament-js/jsbindings.cpp
Prior to this change, `recomputeBoundingBoxes` was an opt-in config
parameter in ResourceLoader. It is now a method on FilamentInstance.
The old API did not work for dynamically created instances. Since this
is a relatively obscure feature, we considered removing it completely,
especially since the computation requires the presence of CPU-side
vertex data combined with the transform hierarchy.
Instead of removing the feature, we decided to move it to a better
place. This paves the way for some upcoming improvements, which include
reducing the memory footprint for assets. It also improves overall code
organization and separation of concerns.
> gltfio: Move the API for recomputeBoundingBoxes.

- libs/utils/src/JobSystem.cpp
This PR completes a TODO, thread names are now set on Windows too (e.g. `FEngine::loop`, `JobSystem::loop`).
Windows API requires conversion of input string to UTF-16. I assumed that the input `const char*` may not only contain ASCII characters, but also can be a UTF-8 string.
> Implement setThreadName() on Windows

- libs/filamat/include/filamat/MaterialBuilder.h
> material instanced property must be false by default.

- libs/gltfio/src/Animator.cpp
- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/FFilamentAsset.h
- libs/gltfio/src/FFilamentInstance.h
- libs/gltfio/src/FilamentInstance.cpp
- libs/gltfio/src/ResourceLoader.cpp
- libs/gltfio/src/TangentsJob.h
The immutable inverse bind matrices can be shared among instances, so
they are now stored in Asset, not in Instance.
Also, there are now two "load" phases for skinning data:
(1) storing the inverse bind matrices
(2) building the Entity mappings (for animation efficiency)
Phase 1 is done in `ResourceLoader` because inverse bind matrices can
live in an external bin file.
Phase 2 is done during Instance creation, because that's when entities
are created.
> gltfio: Refactor skinning, share duplicated data.

- filament/backend/include/backend/Program.h
- filament/backend/src/Program.cpp
- filament/backend/src/opengl/OpenGLProgram.cpp
- filament/src/details/Material.cpp
- filament/src/details/Material.h
We were keeping the list if uniform names in Material and passing
pointers to the backend. Unfortunately, HwProgram can outlive
Material because it is legal to destroy a Material once it's not
needed on the client side. e.g. just after rendering something.
This was happening with the IBLPrefilter code, but probably elsewhere
too.
We now just store CStrings in HwProgram.
> fix a use after free when setting a Program's uniform infos

- libs/filamat/tests/test_filamat.cpp
We use TargetLanguage::SPIRV instead of GLSL which affects how the
source GLSL is generated, in particular which version is used.
This change is not a problem for these unit tests, but is probably
exposing another problem -- we will address that separately.
> fix filamat unit tests

- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/GLSLPostProcessor.h
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/sca/GLSLTools.cpp
- libs/filamat/src/sca/GLSLTools.h
- libs/filamat/tests/test_filamat.cpp
- libs/matdbg/src/ShaderReplacer.cpp
in a few places filamat loses the value of targetApi and targetLanguage
and attempt to guess it from other values, this lead to inconsistencies.
we now keep both targetApi and targetLanguage and use them appropriately.
in particular we don't use the optimization level to "guess" what 
targetLangage we're on.
In the end this resolve a prior unit test failure and allows us to not
have to use "spirv" rules when generating only GLSL.
> Fix filamat internal state tracking

- RELEASE_NOTES.md
- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/DependencyGraph.cpp
- libs/gltfio/src/FFilamentAsset.h
- libs/gltfio/src/FilamentAsset.cpp
- libs/gltfio/src/ResourceLoader.cpp
For each `cgltf_material`, we now create one `MaterialInstance`, even if the asset has multiple instances. In the future, we might make this behavior configurable to make better use of Filament's auto-instancing feature.
This change is a feature request from Google, but also this behavior is more consistent with the code comments.
Also some related cleanup:
1. Use FixedCapacityVector instead of robin_map.
2. Move the cache to move out of the asset and into the loader, because it is only used at load time.
> gltfio: reset MaterialInstance cache for each instance.

- RELEASE_NOTES.md
- filament/backend/src/opengl/OpenGLDriver.cpp
There's a problem with the OpenGL backend with regards to writing to stencil buffers. We need to call `glEnable(GL_STENCIL_TEST)` if we're performing stencil testing *OR* writing to the stencil. Otherwise the writes are ineffective.
Note this contradicts some [documentation](https://www.khronos.org/opengl/wiki/Stencil_Test):
> The stencil operations are still processed when the test is disabled
I verified this is false on macOS and Windows.
> Fix OpenGL stencil buffer writes

- filament/src/MaterialInstance.cpp
- filament/src/PostProcessManager.cpp
- filament/src/details/MaterialInstance.cpp
- filament/src/details/MaterialInstance.h
One of the bloom texture ended-up dangling in the material's
SamplerGroup. That sampler group was never used to draw with, but was
made active which caused problem with the backends.
Also make sure the public API can unset a texture in a MaterialInstance
by passing nullptr for the texture.
> Fix a "dangling" texture in a SamplerGroup

- filament/backend/src/metal/MetalContext.h
- filament/backend/src/metal/MetalDriver.mm
This adds a check that dead textures aren't referenced in the sampler group passed to `updateSamplerGroup`.
We also check that sampler groups aren't created or updated during a render pass, which will be a requirement to implement Metal argument buffers.
> In debug builds, verify destroyed textures aren't in sampler groups

- libs/gltfio/src/FilamentAsset.cpp
- libs/gltfio/src/ResourceLoader.cpp
This broke asyncGetLoadProgress() and caused WebGL to crash reliably because ResourceLoader got destroyed too soon.
Bug was introduced with de7dfc2ea6dce02f9c8d8002d04df72f39fb8e0d.
I intend to cherry pick this to rc/1.27.0, which is where it was introduced, so there's no need to update the release notes.
> gltfio: do not clear out the texture slots too early.

- RELEASE_NOTES.md
- android/gltfio-android/src/main/cpp/AssetLoader.cpp
- android/gltfio-android/src/main/cpp/UbershaderProvider.cpp
- android/gltfio-android/src/main/java/com/google/android/filament/gltfio/MaterialProvider.java
- android/gltfio-android/src/main/java/com/google/android/filament/gltfio/UbershaderProvider.java
- libs/gltfio/include/gltfio/MaterialProvider.h
- libs/gltfio/src/JitShaderProvider.cpp
- libs/gltfio/src/UbershaderProvider.cpp
gltfio can now ask the material provider plugin which `Material` would be used for a given set of requirements.  Prior to this change, gltfio could only create a new `MaterialInstance`.
This method is necessary to support an upcoming gltfio feature.
> gltfio MaterialProvider: add new method for getting `Material`

- RELEASE_NOTES.md
- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/FFilamentAsset.h
- libs/gltfio/src/FilamentAsset.cpp
- libs/gltfio/src/ResourceLoader.cpp
`FilamentAsset` previously had three confusing fields related to textures: mTextures, mTextureSlots, and mTextureBindings.
These are now consolidated into a single field, which simply has one top level array item per `cgltf_texture`.
The memory footprint is smaller because we no longer bother to store `TextureSampler` objects, instead we simply defer their construction until calling setParameter.
Last but not least, we now assert in debug builds if the usages of a particular texture have inconsistent sRGB flags. In the past, inconsistent sRGB would be silently ignored.
In other words, we will now assert if you try to use the same texture for `baseColor` and `normalMap`, whereas in the past we would exhibit non-deterministic behavior in this situation (with respect to sRGB semantics).
> gltfio: big simplification for textures + add sRGB related assert.

- libs/gltfio/include/gltfio/TextureProvider.h
- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/DependencyGraph.h
- libs/gltfio/src/FFilamentAsset.h
- libs/gltfio/src/FilamentAsset.cpp
- libs/gltfio/src/Ktx2Provider.cpp
- libs/gltfio/src/ResourceLoader.cpp
- libs/gltfio/src/StbProvider.cpp
This PR also contains a small change in ResourceLoader::createTextures that will permit zero-instance assets (an upcoming gltfio feature).
> gltfio: use BitmaskFlags for sRGB

- libs/gltfio/src/AssetLoader.cpp
We need a return case here, otherwise the code implicitly falls-through in release builds which generates a compiler error in Google3.
> Add return case to fix G3 compiler error

- RELEASE_NOTES.md
- android/filament-android/src/main/java/com/google/android/filament/MaterialInstance.java
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/include/filament/MaterialInstance.h
- filament/src/MaterialInstance.cpp
- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
- filament/src/details/MaterialInstance.h
- filament/src/details/Renderer.cpp
- improve scissor documentation, specify coordinate system and clipping behavior
- scissor now takes the guard bands into account
- on the backend side the scissor is no longer clipped to the viewport
- clipping to the viewport is now done on the filament side
- don't set scissor when material instance doesn't specify one (common case)
> scissor improvements

- filament/include/filament/View.h
- samples/gltf_viewer.cpp
- fix `View::setVisibleLayers` to match code. By default only layer 0 is active, despite the documentation stating otherwise.
- add a helper to enable/disable layers more easily
- don't use layer 0,1,2 for the overdraw function as they were used by `FilamentApp` in "multi view" mode.
> Fix FilamentApp multiview mode in gltf_viewer

- libs/gltfio/include/gltfio/TextureProvider.h
- libs/gltfio/src/FFilamentAsset.h
- libs/gltfio/src/FilamentAsset.cpp
- libs/gltfio/src/ResourceLoader.cpp
Some (poorly authored) glTF assets have several `image` elements that all refer to the same URL or buffer view. When this occurs, we create only 1 Filament Texture.
These assets regressed after #6051, which consolidated the texture-related fields in `FilamentAsset`, but did not include an ownership flag in the new `TextureInfo` struct.
> gltfio: fix regression when textures are "shared"

- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.h
In VulkanPipelineCache, `getShaderStageFlags()` and `getUsageFlags()` are used to track which samplers are used in the VERTEX stage and which are used in the FRAGMENT stage. The recent change I made was incorrect because it did not account for samplers that are used in BOTH stages.
This fixes the recent regression where we see validation errors when running `gltf_viewer` in ubershader mode.
> Vulkan samplers: fit incorrect bitset logic.

- RELEASE_NOTES.md
- android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
- libs/gltfio/include/gltfio/FilamentAsset.h
- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/DependencyGraph.cpp
- libs/gltfio/src/DependencyGraph.h
- libs/gltfio/src/ResourceLoader.cpp
- libs/viewer/src/ViewerGui.cpp
- samples/gltf_instances.cpp
This is a feature request from Google. It allows users to "preload" an asset, ie you can now create all VertexBuffer objects, Texture objects, etc, without actually creating any entities or renderable components.
In the past we used TransformManager to help out with computing the big asset-level bounding box, but now we use `gltf_node_transform_world()` because entities might not yet exist.
> gltfio: allow zero-instance assets.

- docs/Materials.md.html
- filament/backend/include/backend/DriverEnums.h
- filament/backend/src/metal/MetalHandles.mm
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/src/details/Material.cpp
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/SamplerBindingMap.cpp
- libs/filamentapp/include/filamentapp/Config.h
- samples/gltf_viewer.cpp
- tools/matc/src/matc/ParametersProcessor.cpp
This is because most android devices only support 16 texture in the 
shaders (94.4%), so we can't realistically have feature level 2 demand 
that.
Instead feature level 2 enables compute/ES3.1 features.
> introduce "feature level 3" 

- RELEASE_NOTES.md
- libs/gltfio/src/AssetLoader.cpp
Punctual lights are now duplicated when adding new asset instances.  This makes sense for objects like lamp posts.
> gltfio: change instancing behavior for punctual lights

- filament/backend/src/opengl/gl_headers.h
We now compile with ES3.1 headers but we make sure we can still compile with ES3.0 headers (still needed for iOS).
> use ES3.1 headers

- filament/backend/src/metal/MetalBuffer.h
This helper class will be used soon to manage buffer allocations  for argument buffers.
> Add `MetalRingBuffer` for future argument buffer management

- RELEASE_NOTES.md
- filament/backend/src/metal/MetalBuffer.h
- filament/backend/src/metal/MetalContext.h
- filament/backend/src/metal/MetalDriver.h
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
- filament/backend/src/metal/MetalState.h
- filament/backend/src/metal/MetalState.mm
- filament/backend/src/metal/MetalUtils.h
- filament/backend/src/metal/MetalUtils.mm
- libs/filabridge/include/filament/MaterialEnums.h
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/shaders/CodeGenerator.cpp
- libs/filamat/src/shaders/CodeGenerator.h
- libs/filamat/src/shaders/ShaderGenerator.cpp
This switches Metal to use [argument buffers](https://developer.apple.com/documentation/metal/buffers/about_argument_buffers?language=objc) for referencing samplers and textures in draw calls. Argument buffers are similar to Vulkan descriptors.
The primarily reason for doing this is to support more textures/samplers for feature level 3 on newer Metal devices. This also opens up some potential CPU performance improvements.
The logic is a bit tricky, as we don't necessarily know all the final textures at `updateSamplerGroup` time, so `MetalSamplerGroup` has some additional bookkeeping to do.
> Metal: use argument buffers for SamplerGroups

- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
to emulate the bindless API in the gl backend we always used the highest texture unit available. However at feature level 3, we support up to 62 textures, so the that max was bumped to 62 -- however, where we're not on a feature level 2 device, that texture unit doesn't exist.
Instead we now always use binding 31, which is guaranteed to exist by  EGL's minspec.
> don't attempt to use more texture units than present

- RELEASE_NOTES.md
- android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
- android/gltfio-android/src/main/cpp/FilamentAsset.cpp
- android/gltfio-android/src/main/cpp/FilamentInstance.cpp
- android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentAsset.java
- android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentInstance.java
- android/samples/README.md
- android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
- filament/include/filament/Camera.h
- ios/samples/gltf-viewer/gltf-viewer/FILModelView.mm
- libs/gltfio/include/gltfio/AssetLoader.h
- libs/gltfio/include/gltfio/FilamentAsset.h
- libs/gltfio/include/gltfio/FilamentInstance.h
- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/FFilamentAsset.h
- libs/gltfio/src/FFilamentInstance.h
- libs/gltfio/src/FilamentAsset.cpp
- libs/gltfio/src/FilamentInstance.cpp
- libs/gltfio/src/ResourceLoader.cpp
- libs/viewer/include/viewer/ViewerGui.h
- libs/viewer/src/ViewerGui.cpp
- samples/gltf_instances.cpp
- samples/gltf_viewer.cpp
- web/filament-js/extensions.js
- web/filament-js/filament-viewer.js
- web/filament-js/filament.d.ts
- web/filament-js/jsbindings.cpp
- web/samples/animation.html
This moves `MaterialInstance` objects into the `FilamentInstance` objects that they apply to, rather than storing them in one monolithic list in `FilamentAsset`.
This also removes the "broadcast" animator from FilamentAsset.  Clients should simply use the per-instance animators.
In the near future, we will also move all the entity getter methods from `FilamentAsset` to `FilamentInstance`.
These changes are motivated by the need to allow instance creation from immutable assets, which is a feature request from Google.
> gltfio API changes, parts 1 and 2.

- RELEASE_NOTES.md
- android/filament-android/src/main/java/com/google/android/filament/LightManager.java
- filament/include/filament/LightManager.h
- filament/src/ShadowMap.cpp
- filament/src/ShadowMapManager.cpp
We were always adjusting the near/far of the view volume based on the scene content for shadowing, which defeated the "stable" shadows.
Also changed the default cascade splits from a linear split to a log2 split, because due to the perspective projection, the log2 split actually looks linear. Also intuitively, it makes more sense to give more resolution to the shadows close to the camera.
> fix "stable" shadows

- filament/backend/src/metal/MetalContext.h
- filament/backend/src/metal/MetalContext.mm
- filament/backend/src/metal/MetalDriver.h
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
This PR changes the storage mode of MSAA sidecar textures to [memoryless](https://developer.apple.com/documentation/metal/mtlstoragemode/memoryless) in Metal backend, on supported devices. 
Memoryless sidecars had been attempted in the past, but reverted in https://github.com/google/filament/pull/4333 due to a sparsely documented limitation of this feature: only a certain geometry complexity can be processed and rendered this way. Exceeding this limit causes a command buffer error.
We conducted a few tests and concluded that we're unable to predict this abstract "memoryless limit". It does not only differ between Apple GPU generations (e.g. A12X or M1 Pro), but it's changing based on the resolution of the rendertarget and available system memory.
Therefore, we decided to resort to a …
> Memoryless storage mode with fallback (Metal)

- filament/src/ShadowMap.cpp
- filament/src/ShadowMapManager.cpp
- filament/src/details/View.cpp
this case was causing uninitialized variables to be used creating a false positive "shadows on" in the first cascade.
The main change here is to bail out as soon as we know there is no shadowing.
> fix shadowing when the scene is outside the "shadow" view frustum

- RELEASE_NOTES.md
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
The VulkanProgram constructor was bailing out early and emitting a warning because it saw that one of the stages wasn't fulfilled. However it's okay for a pipeline to be missing a compute program.
Fixes regression that started with fabba73b1.
> Vulkan: fix black screen regression

- RELEASE_NOTES.md
- filament/src/Culler.cpp
- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- filament/src/ShadowMapManager.h
- filament/src/details/Renderer.cpp
- filament/src/details/View.cpp
- filament/src/details/View.h
- filament/src/fg/FrameGraph.cpp
- libs/filabridge/include/private/filament/EngineEnums.h
- libs/filabridge/include/private/filament/UibStructs.h
Spotlight shadow maps are now limited only by h/w limits (UBO size and
2d array maximum layers), which works out to about 146 shadows.
In practice we hardcode the limite to 64, but this can be changed at
compile time. A higher maximum increases memory usage.
There used to be a bitfield per renderable with a bit for each shadow
map indicating if the renderable was "visible" from this light. The
limit to 14 came from that bitfield. All shadow maps used to be culled
first, setting the bitfield appropriately.
Instead, we are now processing spotlight shadows one at a time,
performing culling as we go. For this reason we don't need a bit per
shadow map.
> Remove the limit to 14 spot shadow maps, now 64.

- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- filament/src/ShadowMapManager.h
- remove mEngine from ShadowMap
- remove storage of ShadowMapInfo in ShadowMap
- ShadowMap::render should be on ShadowMapManager
- remove more attributes from ShadowMap
ShadowMap is now reduced to 32 bytes.
> Reduce size of ShadowMap object

- filament/backend/src/opengl/gl_headers.h
- filament/backend/src/vulkan/VulkanHandles.cpp
A couple of fixes for G3:
- iOS does not have `GL_EXT_disjoint_timer_query`, so `GL_TIME_ELAPSED` is not defined though it's used in Filament without any `#ifdef` guard
- Vulkan does not yet support compute shaders
> G3 fixes for 1.28.0

- RELEASE_NOTES.md
- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/include/filament/Engine.h
- filament/src/Engine.cpp
- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
This makes it possible to integration with external renderers in WebGL without causing rendering artifacts.
See https://github.com/google/filament/issues/6091
> Add a function to re-set internal GL state tracking

- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
In some cases, calling `encoder.device` returns `nil`, even right after a valid `MTLArgumentEncoder` has been initialized. So far this has only been seen on the iOS simulator.
> Metal: fix, don't use encoder.device

- filament/backend/src/metal/MetalBlitter.mm
This PR resolves a Metal shader compilation warning that bloats our output window. The following unused variable warning is generated:
```
[Metal Compiler Warning] Warning: Compilation succeeded with:
program_source:73:12: warning: unused variable ‘uv’
float2 uv = uvscaled + args->srcOffset;
```
The warning originates from the `MetalBlitter.mm` implementation file. This code piece is part of the blitter’s fragment function, however the fragment shader compiles without warnings. Actually, the warning is generated when the blitter’s shader source is used for vertex shader compilation, where no `BLIT_COLOR` nor `BLIT_DEPTH` is provided, thus the preprocessor removes all code paths that used the `uv` variable from the fragment entry point. To solve this, I encapsulated the orphaned variables …
> Fix Metal unused variable warning

- shaders/src/common_lighting.fs
[`inversesqrt`](https://registry.khronos.org/OpenGL-Refpages/gl4/html/inversesqrt.xhtml) is undefined for values <= 0. This resulted in black "patches" in Metal where `aperture` was being set to 0.
> Metal: fix microshadowing artifacts

- filament/backend/src/metal/MetalContext.h
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.mm
Resolving multisampled depth attachments requires GPU support on Metal. This PR adds the necessary checks.
For reference, this feature corresponds to the "MSAA depth resolve" capability in the [Metal Feature Set Tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf). (Unfortunately the live version of this table has recently been turned incomplete, because macOS 13 dropped support for `.mac1` GPU family. Its capabilities can be checked in [this archived version of the document](https://web.archive.org/web/20220309044948/https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf)).
Based on our testing, depth resolve implies support for stencil resolve using the `.sample0` [resolve filter](https://developer.apple.com/documentation/metal/mtlmultisamplestencilresolvefilte …
> Check GPU support for depth resolve on Metal

- filament/CMakeLists.txt
- filament/src/AtlasAllocator.cpp
- filament/src/AtlasAllocator.h
- filament/test/CMakeLists.txt
- filament/test/filament_AtlasAllocator_test.cpp
- libs/utils/CMakeLists.txt
- libs/utils/include/utils/QuadTree.h
- libs/utils/test/test_QuadTreeArray.cpp
This 2D allocator only supports power-of-two, square allocations. It uses a quadtree to store the allocated regions.
The quadtree implementation currently has a fixed depth (templated).
The allocator does a best-fit match, but currently doesn't implement a free method.
> A basic POT 2D allocator

- filament/src/components/RenderableManager.cpp
- filament/src/components/RenderableManager.h
- libs/utils/include/utils/Slice.h
it's just not used anywhere. change the implementation of Slice<> to use two pointers.
> utils: get rid of GrowingSlice

- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
- filament/src/ShadowMapManager.cpp
We didn't need to store the actual RenderPass for each shadowmap pass, the executor is enough. This might prevent some mistakes later.
> shadowing: store Executor instead of whole RenderPass

- filament/src/PerViewUniforms.cpp
- filament/src/PerViewUniforms.h
- filament/src/PostProcessManager.cpp
- filament/src/RendererUtils.cpp
- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- filament/src/ShadowMapManager.h
- filament/src/TypedUniformBuffer.h
- filament/src/details/Renderer.cpp
- filament/src/details/View.cpp
- filament/src/details/View.h
Instead of constantly reusing the View's UBO, each shadowmap now
manages it own. All UBOs for all shadow maps are updated together, 
then later during rendering, we're simply binding the correct UBO.
This change will be needed later so that we can update several
shadow maps in a single texture.
There are two main changes to achieve this:
1. ShadowMap now has PerViewUniforms object
2. For point lights, each face now has a ShadowMap object
One consequence is that ShadowMap is now very large (over 2KB). This
will be addressed later.
> Each shadowmap now manages its own UBO

- RELEASE_NOTES.md
- libs/gltfio/src/AssetLoader.cpp
AABB of morph target is displacement data so it should be added to primitive's base AABB.
Fix #6231
> Calculate primitive's AABB correctly

- RELEASE_NOTES.md
- filament/backend/src/Platform.cpp
- filament/backend/src/vulkan/PlatformVkLinuxGGP.cpp
- filament/backend/src/vulkan/PlatformVkLinuxGGP.h
This PR adds support for a new Vulkan backend that enables the VK_GGP_stream_descriptor_surface vulkan extension and creates the surface using the vkCreateStreamDescriptorSurfaceGGP function provided by that extension.
> Add Vulkan GGP platform.

- filament/src/ShadowMap.h
The size of struct could be different on each architecture.
> Fix a build error on Android

- CMakeLists.txt
This PR follows up on #624 and adds back unwind tables and frame pointers to the generated code **on iOS**.
Our iOS app uses Filament for PBR rendering and uses Crashlytics for tracking crashes. We faced the problem of not seeing stack frames of Filament code in our crash reports because unwind tables and frame pointers were emitted from the Filament lib:
Adding them back fixed the issue without significantly increasing the app size. In our case, our Filament static lib grew from 137.1 MB to 139.5 MB. (The lib file in question includes  x86_64 and arm64 binaries of the following libraries and their dependencies: `backend`, `filabridge`, `filaflat`, `filament`, `ibl`, `image`, `utils`).
We tested these changes on the following platforms:
- iPadOS (arm64 devices only)
- iOS Simulator …
> Preserve iOS stack traces

- filament/src/ShadowMap.cpp
This wasn't a big issue because the "leak" would be cleaned when the engine is destroyed.
> fix UBO handle leak with ShadowMap

- build/common/check-metal-shaders.sh
- libs/filabridge/include/private/filament/SamplerInterfaceBlock.h
- libs/filamat/CMakeLists.txt
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/MetalArgumentBuffer.cpp
- libs/filamat/src/MetalArgumentBuffer.h
- libs/filamat/tests/test_argBufferFixup.cpp
- shaders/src/main.fs
We're using argument buffers for texture resources, however, we cannot rely on spirv-cross to generate the argument buffer definitions.
Consider a shader with 3 textures:
```
layout (set = 0, binding = 0) uniform sampler2D texture1;
layout (set = 0, binding = 1) uniform sampler2D texture2;
layout (set = 0, binding = 2) uniform sampler2D texture3;
```
If only texture1 and texture2 are used in the material, then texture3 will be optimized away.
This results in an argument buffer like the following:
```
struct spvDescriptorSetBuffer0 {
texture2d<float> texture1 [[id(0)]];
sampler texture1Smplr [[id(1)]];
texture2d<float> texture2 [[id(2)]];
sampler texture2Smplr [[id(3)]];
};
```
Note that this happens even if the "pad_argument_buffer_resources" and "force_active_argument_buffer_resources" …
> Metal: generate argument buffer structures ourselves

- filament/CMakeLists.txt
- filament/src/PerShadowMapUniforms.cpp
- filament/src/PerShadowMapUniforms.h
- filament/src/PerViewUniforms.h
- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- filament/src/ShadowMapManager.h
ShadowMap had recently inflated due to its internal use of  PerViewUniforms, which keeps a shadow copy of the uniform data. This copy is not needed for ShadowMaps.
> Reduce the size of ShadowMap to 40 bytes from 2KB+

- filament/src/details/MaterialInstance.cpp
certain material properties can only be set if supported by the  material.
> fix recently introduced crash on init

- shaders/src/light_punctual.fs
Spotlight attenuation was computed only when shadowing was enabled.
> fix spotlight attenuation

- filament/src/ShadowMap.cpp
breakage was due to an uninitialized variable at the beginning of the frame, caused by a recent change.
shadows would disappear when cascades were used with 'stable' shadows.
> fix shadow cascades

- filament/backend/src/metal/MetalContext.h
- filament/backend/src/metal/MetalDriver.mm
This PR adds caching for depth bias in the Metal backend. The previous check didn't eliminate redundant `setDepthBias:slopeScale:clamp` calls, instead it blocked setting `{0.0, 0.0}` which could create incorrect results if a primitive *without* bias was drawn after a primitive *with* bias.
> Fix skipped depth bias set on Metal

- filament/src/RenderPass.cpp
If a client creates a renderable, but doesn't set geometry during `RenderableManager::Builder::Build()` and also never calls `setGeometryAt`, then Filament asserts. This happens because there's no valid render primitive for the renderable. This was fine before 1.28.3, because by default we were setting the `primitiveType` to `NONE`, which would cause the command to automatically get skipped. However, when `PrimitiveType::NONE` was removed, it forced all primitives to have valid geometry.
This PR allows renderables to have missing geometry without triggering an assertion.
> Skip rendering renderables with missing geometry

- third_party/libsdl2/include/SDL_syswm.h
Fix winnt.h(2501): error C2118: negative subscript.
> Include the windows.h header after packing alignment

- filament/src/PerShadowMapUniforms.cpp
- filament/src/PerShadowMapUniforms.h
- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- libs/math/include/math/mat4.h
The viewport is now entirely handled by ShadowMap, that is, we're no longer setting a viewport in the renderpass, instead the ShadowMap uses a post projection transform to achieve the same effect. This will become useful when store shadow maps in an Atlas.
> rework how we set the viewport for shadows

- CMakeLists.txt
-Addresses issue where launch-c/launch-cxx is expected in CMAKE_BINARY_DIR
https://github.com/google/filament/issues/6285
Signed-off-by: Joel Winarske <joel.winarske@gmail.com>
> Enable CMake for  subdirectory use

- filament/src/RenderPass.cpp
don't forget to update the scissor state when setting the override.
> fix scissor override

- filament/backend/src/opengl/OpenGLDriver.cpp
When width/height is converted to GLSizei, which is signed, it can become negative, which happened with a "full" viewport. On some GL implementation, this resulted in a failure.
> don't set invalid viewport in gl backend

- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- libs/filabridge/include/private/filament/UibStructs.h
- shaders/src/common_types.glsl
- shaders/src/shadowing.fs
All shadow maps need a 1-px border for different reasons. The directional shadow needs a "not in shadow" border because it uses the intersection of receivers and casters in light-space. Other shadow types need a border because of bilinear access at the  edges. Until now, the spot/point shadow border was handled with the sampler's CLAMP.
Instead, now, we always generate a border and in one case we fill it with "not in shadow" (by not rendering into it), in the other cases we render the 2px larger shadowmap so we get completely correct bilinear  filter.
Additionally, for PCF, DPCF and PCSS we use a large filter kernel which accesses data outside the texture, until now this was handled with CLAMP, but that failed (2 of the edges were not handled in the same way) when  the shadowmap was …
> Handle shadow borders better

- filament/src/ShadowMap.cpp
Use a much more precise way to calculate the directional shadow frustum. With very large scenes, we were losing the precision on the direction of the light, and in some case even producing NaN in the matrix.
This partially addresses #6293
> Directional shadow improvements

- CMakeLists.txt
Since cmake 3.25 LINUX is automatically set based on CMAKE_SYSTEM_NAME, 
which the android cmake files are setting to "Linux". This created an
inconsistant state in our build system.
> Fix Android continuous and presubmit builds

- filament/backend/src/opengl/OpenGLProgram.cpp
- shaders/src/common_types.glsl
WebGL complained about:
Precisions of uniform block 'ShadowUniforms' member  'ShadowUniforms.shadows.texelSizeAtOneMeter' differ between VERTEX and  FRAGMENT shaders.
this field didn't have a precision qualifier, this might be specific to WebGL or a Chrome bug, unsure. Either we fix it by specifying all qualifiers.
> Fix a WebGL program link failure

- android/filament-android/src/main/java/com/google/android/filament/Renderer.java
- android/samples/sample-multi-view/src/main/java/com/google/android/filament/multiview/MainActivity.kt
- filament/include/filament/Renderer.h
- filament/src/RendererUtils.cpp
- filament/src/RendererUtils.h
- filament/src/details/Renderer.cpp
- filament/src/details/Renderer.h
When more than one view was used, only the first view was cleared with the ClearOption. This was actually intended when the views are rendering into the swapchain (e.g. post process disabled), but that's incorrect  when the views render into intermediate buffers.
The clear flags are now associated with the actual rendertarget.
> fix clear options

- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
The race coud lead to user after free and crashes.
We now keep a list of acquired streams with pending images on the  main thread, and use that to update the streams synchronously in beginFrame. We can then enqueue a command for the driver thread that will look for that stream in the active list of textures with stream attached. Race avoided.
The previous code used the later list from both threads.
> fix a race condition with acquired streams

- filament/backend/src/opengl/OpenGLDriver.cpp
this only affect the WebGL build's readPixels.
> fix a typo that caused a wrong allocation size

- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
Vulkan and Metal should be handled exactly the same within filament, when it comes to texture-space and clip-space because filament always transforms vulkan's clip-space to gl's/metal's).
Our shadow code took different paths, both equivalent though, but it's confusing.
> Handle Vulkan and Metal shadow coordinates in the same way

- RELEASE_NOTES.md
- docs/Materials.md.html
- filament/src/PerShadowMapUniforms.cpp
- filament/src/PerShadowMapUniforms.h
- filament/src/PerViewUniforms.cpp
- filament/src/PerViewUniforms.h
- filament/src/RendererUtils.cpp
- filament/src/RendererUtils.h
- filament/src/ShadowMap.cpp
- filament/src/details/Renderer.cpp
- filament/src/details/View.cpp
- filament/src/details/View.h
- libs/filabridge/include/filament/MaterialEnums.h
- libs/filabridge/include/private/filament/UibStructs.h
- libs/filamat/src/UibGenerator.cpp
- shaders/src/common_getters.glsl
- shaders/src/getters.fs
- shaders/src/light_indirect.fs
- shaders/src/light_punctual.fs
It is useful when the viewport-relative coordinates of the "logical" (i.e. user) viewport are needed, for instance when generating UVs.
>  getNormalizedViewportCoord() now returns the logical viewport coords

- RELEASE_NOTES.md
- libs/filamat/src/shaders/CodeGenerator.cpp
- libs/gltfio/materials/volume.mat.in
- shaders/CMakeLists.txt
- shaders/src/common_instancing.glsl
- shaders/src/depth_main.fs
- shaders/src/getters.fs
- shaders/src/getters.vs
- shaders/src/light_directional.fs
- shaders/src/light_punctual.fs
- shaders/src/main.fs
- shaders/src/main.vs
- shaders/src/shading_unlit.fs
At least some adreno compilers don't like returning an element of a UBO array that is a structure in the vertex shader. To work this around we have to copy the each of the structure fields.
Fixes #6355
> Workaround for a bug in Adreno's shader compiler

- filament/src/details/Scene.cpp
We need to ensure we always delete `weakShared`.
> Fix memory leak in Scene

- filament/backend/src/vulkan/VulkanContext.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanUtility.h
This reverts commit 6f7d203adb23dd62396646248c82ecaddec21c3b. The above commit (6f7d20) is the revert of #6423. Commit 6f7d20 is PR #6425.
"[vulkan] Refactor vkEnumerate methods (#6423)" failed [1] due to a missing function attribute (VKAPI_ATTR in bluevk) for ARM64 compilers.
[1]: https://github.com/google/filament/actions/runs/3841550984
> Re-land #1 "[vulkan] Refactor vkEnumerate methods (#6423)"

- filament/backend/src/vulkan/VulkanContext.cpp
- filament/backend/src/vulkan/VulkanContext.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
Move the initialization of VulkanContext fields to the class itself. This will clean up how the various extension support flags are deteremined.
Also disable debugUtils extension for Mesa driver (#6192).
> Refactor VulkanContext/Driver initialization

- filament/src/Froxelizer.cpp
- filament/src/Froxelizer.h
- filament/src/Frustum.cpp
- filament/src/Intersections.h
Forxelization made many assumptions about the shape of the projection
matrix, the gist of these fixes is to remove those assumptions.
Fix https://github.com/google/filament/issues/6390
> fix dynamic lighting with custom projections

- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/gl_headers.cpp
- filament/backend/src/opengl/gl_headers.h
We do some shenanigans so it works with API < 21 on android.
> reenable compute in the GL backend

- filament/src/materials/skybox.mat
We noticed that skybox looks weird in ortho view too. In the image below the background should be a vertical gradient but instead it's focused at the center:
Based on frame captures the `eye_position` varying was miscalculated in skybox.mat. I didn't quite follow what went wrong in the maths, but saw that `computeWorldPosition()` (called in `initMaterialVertex()`) correctly calculates the world position for DEVICE domain vertex shaders (such as skybox.mat) so I reused that and now skyboxes look correct.
Here is a before/after from gltf viewer sample (modified to use an ORTHO camera):
> Fix skybox shader in orthographic view

- filament/backend/src/vulkan/VulkanContext.cpp
`driverInfo` points to a string inside `driverProperties`, whose scope is limited to the `if` block.
```
=================================================================
==8587==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffa9f3f33c4 at pc 0x562128c65111 bp 0x7ffaa66ce010 sp 0x7ffaa66cd7d0
READ of size 1 at 0x7ffa9f3f33c4 thread T109 (FEngine::loop)
#0 0x562128c65110 in StrstrCheck(void*, char*, char const*, char const*) third_party/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:652:5
#1 0x562128c64dac in strstr third_party/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:669:5
#2 0x56212b8a9689 in strstr third_party/crosstool/v18/stable/toolchain/bin/../include/c++/v1/string.h:106:10
#3 …
```
> Vulkan: fix `stack-use-after-scope` ASAN error in VulkanContext.cpp

- RELEASE_NOTES.md
- android/filament-android/src/main/cpp/RenderableManager.cpp
- android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
- filament/include/filament/RenderableManager.h
- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
- filament/src/RenderableManager.cpp
- filament/src/components/RenderableManager.cpp
- filament/src/components/RenderableManager.h
- filament/src/details/Renderer.cpp
- web/filament-js/jsbindings.cpp
There can be up to 4 channels drawing commands can be associated to.  Channels work like "priorities" except it's the strongest command ordering  key, in particular it takes precedence over the object's blending mode.
> implement draw command channels

- libs/geometry/CMakeLists.txt
- libs/geometry/include/geometry/TangentSpaceMesh.h
- libs/geometry/src/TangentSpaceMesh.cpp
- Defined class with documentation in comments
- Implemented algorithm selection
- No actual algorithms written yet
Part of google/filament#6358
> geometry: Add TangentSpaceMesh class outline

- libs/gltfio/src/FilamentAsset.cpp
I'd appreciate a second set (or more) eyes on this. I found that some entities remained in `EntityManager` even after all the assets have been released while looking into #6481. 
Found that the [leaked entity is created][AssetLoaderCreateInstance] and set to the instance's root, but is not destroyed from `EntityManager` in the instance's destructor nor in the destructor of `FilamentAsset`. 
[AssetLoaderCreateInstance]: https://github.com/google/filament/blob/v1.31.2/libs/gltfio/src/AssetLoader.cpp#L511
>  Destroy FilamentInstance's mRoot in EntityManager

- samples/sample_full_pbr.cpp
This PR aims to fix sample_full_pbr.
Material parsing fails if the directory passed to `--material` contains a height map:
`for (int i = 0; i < numLayers; i++) {`
```metal
ERROR: 0:24: '<' :  wrong operand types: no operation '<' exists that takes a left-hand operand of type ' temp mediump int' and a right operand of type ' temp mediump float' (or there is no acceptable conversion)
ERROR: 0:24: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
```
The sun was not added to the scene (commented out).
Now it's added although for me the intensity is still way too low.
Parallax mapping was using camera eye position to calculate tangent-space view vector. This is problematic with ortho camera, as explained in #6453.
Since here `tangentFromWorld` is [the usual TBN …
> Sample Full PBR fixes

- filament/backend/src/vulkan/VulkanConstants.h
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/sca/GLSLTools.cpp
- libs/matdbg/src/DebugServer.cpp
- libs/matdbg/src/ShaderExtractor.cpp
This should be backward compatible with old materials.
> We now require Vulkan 1.1 for the vulkan backend

- CMakeLists.txt
- android/build.gradle
- android/gradle.properties
- build.sh
`-d` now enables matdbg and adds debugging data, but doesn't affect 
material optimization
`-g` disables material optimizations
A similar change is done with gradle options. The new proprety `com.google.android.filament.matnopt` is used to disable material optimizations.
These options mimic `matc` options.
> build.sh -d is now split in two options

- libs/matdbg/CMakeLists.txt
- libs/matdbg/web/script.js
we now refresh the spirv code properly after it's rebuilt from the glsl tab.
> matdbg: refresh spirv properly

- android/gltfio-android/src/main/java/com/google/android/filament/gltfio/UbershaderProvider.java
`UbershaderProvider.getNativeObject()` is accessed from `AssetLoader.cpp`, so it must be annotated with `@UsedByNative("AssetLoader.cpp")` to avoid runtime crashes when minification is applied.
I'm able to successfully run my application with minification enabled with this change.
Closes #5954
> Fix JNI after minification is applied

- RELEASE_NOTES.md
- libs/gltfio/src/ResourceLoader.cpp
When loading a glTF file on platforms without a filesystem, a client calls `addResourceData` to populate `ResourceLoader`'s cache with data. For example, a web client might make HTTP fetch requests to fill in buffer data. This internal cache of data is stored in `ResourceLoader::Impl::mUriDataCache`.
This works well, except the cache must persist until after the data has been uploaded to the GPU.
There was already a mechanism (see `struct UploadEvent ` and `uploadUserdata`) in place to ensure that glTF data persisted until after it had been uploaded to the GPU. However, this mechanism did not extend to client-provided data. Thus, a race occured between Filament's driver consuming the buffer and it getting freed.
> gltfio: Fix race condition affecting mobile and web

- RELEASE_NOTES.md
- android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
- filament/include/filament/RenderableManager.h
- filament/src/RendererUtils.cpp
- filament/src/components/RenderableManager.cpp
This also fixes some potential issues with refraction when using render channels.
> The default render channel is now 2 instead of 0

- NEW_RELEASE_NOTES.md
- libs/gltfio/src/ResourceLoader.cpp
`operator[]` is sneaky and inserts a `nullptr` element if it can't find a match, which led to a subsequent crash.
Fixes #6568.
> gltfio: Fix crash when a MIME type has no texture provider

- CMakeLists.txt
Building Filament or its parts on Windows, using the `ninja` generator, with `ccache` installed, fails with the following message: 
`ninja: fatal: CreateProcess: %1 is not a valid Win32 application.`
This is due to the way `ccache` support is implemented in the root `CMakeLists.txt` script. Executing line 70, `cmake` will find `ccache` installed, and enter the `if` branch on line 71. It will then configure the `launch-c` and `launch-cxx` Bash scripts, and after failing the `Xcode` check, will set them as compiler launchers (lines 88-90). When `ninja` tries to run these scripts, it will fail with the message above.
This PR adds a condition to handle Windows, and sets `ccache` directly as compiler launcher. In order to support passing parameters to `ccache`, either a batch file, or a …
> Support ccache on Windows with ninja generator

- filament/backend/include/backend/PixelBufferDescriptor.h
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- some of the convenience are not available in ES2
- it's less efficient
- we can save some PBO space when reading back a partial framebuffer.
We also avoid using GL_PACK_ROW_LENGTH which technically is not a convenience, but in our case we are doing an extra copy anyways, so we can account for the row-length at that point.
> don't rely on GL PACK/UNPACK convenience

- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/test/test_StencilBuffer.cpp
glReadPixel doesn't resolve automatically, but it does with the  auto-resolve extension, which we're always emulating.
> Fix readPixels() for "auto-resolved" MS color buffers

- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLTimerQuery.cpp
- filament/backend/src/opengl/OpenGLTimerQuery.h
- filament/backend/src/opengl/gl_headers.cpp
- filament/backend/src/opengl/gl_headers.h
- filament/backend/src/opengl/platforms/PlatformEGL.cpp
- iOS is treated the same way than Android now. The only difference is that iOS only provides prototypes and no typedef, whereas  Android only provides typedefs and no prototypes.
- Timer queries is core in GL and an extension on all versions of GLES. On iOS it's not available at the header level. An additional subtlety is that glGetObjectuiv is core in GLES 3.0, so it conflicts with the extension. So, now we do things correctly:
- on desktop we use the core methods
- on ios we ifdef out everything related to timer queries
- on gles 2.0 and up we use only the extension entry-points
> Cleanup how we get GL extensions entry-points

- filament/backend/src/opengl/GLUtils.h
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLProgram.cpp
- filament/backend/src/opengl/gl_headers.h
- make sure to initialize all extension booleans, we treat them as feature flags.
- be more explicit about #define'ing gl tokens, so we can more easily catch errors later.
- don't blindly use extension tokens that might not be available (e.g.: GL_TEXTURE_EXTERNAL_OES or GL_TEXTURE_CUBE_MAP_ARRAY). It would probably cause a spurious gl error.
> More improvements to how we handle extensions

- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
This small abstraction is (will be) needed because GLES 2.0 doesn't have sync object, however synchronization is sometimes available externally, in particular with EGL.
This PR doesn't provide other implementations.
> abstract OpenGL's GLSync

- filament/backend/src/opengl/OpenGLContext.h
fortunately this would only happen when using SSBOs (which are not used currently).
> fix typo that could cause a OOB

- filament/backend/src/opengl/GLUtils.h
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLProgram.cpp
- filament/backend/src/opengl/OpenGLTimerQuery.cpp
- filament/backend/src/opengl/OpenGLTimerQuery.h
- filament/backend/src/opengl/gl_headers.cpp
- filament/backend/src/opengl/gl_headers.h
try to be more explicit about which configurations are supported,
and use the same pattern everywhere for checking the gl version at
either compile and runtime.
> rework again how we manage different versions of GL 

- NEW_RELEASE_NOTES.md
- filament/src/PerViewUniforms.cpp
- filament/src/details/View.cpp
- libs/filabridge/include/private/filament/UibStructs.h
- libs/filamat/src/shaders/UibGenerator.cpp
- shaders/src/fog.fs
- precision was incorrect, `highp` is needed for part of the math (fixes fog on mobile)
- height falloff wasn't accounted for properly due to how the math was split between cpu and gpu
- fog integral computation
- fog's origin
- instability with strong falloffs
> Fix a couple issues related to fog

- NEW_RELEASE_NOTES.md
- android/filamat-android/src/main/cpp/MaterialBuilder.cpp
- android/filamat-android/src/main/java/com/google/android/filament/filamat/MaterialBuilder.java
- android/filament-android/src/main/cpp/Material.cpp
- android/filament-android/src/main/cpp/MaterialInstance.cpp
- android/filament-android/src/main/java/com/google/android/filament/Material.java
- docs/Materials.md.html
- filament/include/filament/Material.h
- filament/src/Material.cpp
- filament/src/MaterialParser.cpp
- filament/src/MaterialParser.h
- filament/src/details/Material.cpp
- filament/src/details/Material.h
- libs/filabridge/include/filament/MaterialChunkType.h
- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/MaterialBuilder.cpp
- tools/matc/src/matc/ParametersProcessor.cpp
The alphaToCoverage property lets you enable or disable alpha to coverage in a material. More importantly it lets you overrides the behavior of blending: masked which automatically enables alphaToCoverage.
This PR fixes #6585.
> Add new alphaToCoverage material property

- third_party/getopt/LICENSE
- third_party/getopt/include/getopt/getopt.h
- third_party/getopt/src/getopt.c
- third_party/getopt/src/getopt_long.c
- third_party/getopt/src/libc.h
- tnt/README.md
Our former implementation was rather ancient and was using unsupported features of C. This change removes build warnings.
> Update getopt to musl-1.1's implementation

- libs/filamentapp/include/filamentapp/IBL.h
- libs/filamentapp/src/IBL.cpp
- samples/material_sandbox.cpp
`IndirectLight::getDirectionEstimate` and others return `NaN` if we didn't load spherical harmonics (for example, in the case of an equirectangular IBL).
> Fix NaN parameters in material_sandbox

- NEW_RELEASE_NOTES.md
- shaders/src/shading_parameters.fs
[`shading_view`](https://github.com/google/filament/blob/9c3304af78b67105efdced0d920407115436971b/shaders/src/common_shading.fs#L5) is not marked `highp`. This is fine, as it stores a normalized vector. However, we need to take care that we keep full precision _until_ we normalize it. Otherwise we max out the float with large scenes which leads to numerical instability.
> Compute shading_view will full precision

- libs/geometry/include/geometry/TangentSpaceMesh.h
- libs/geometry/src/MikktspaceImpl.cpp
- libs/geometry/src/MikktspaceImpl.h
- libs/geometry/src/TangentSpaceMesh.cpp
- libs/geometry/src/TangentSpaceMeshInternal.h
- Reordered the 'const var' declarations to 'var const'
- Use std::vector for data arrays instead of manually managing allocations
> geometry: clean up TangentSpaceMesh

- NEW_RELEASE_NOTES.md
- docs/Materials.md.html
- filament/src/PerShadowMapUniforms.cpp
- filament/src/PerViewUniforms.cpp
- filament/src/ShadowMap.cpp
- filament/src/details/Camera.h
- filament/src/details/View.cpp
- libs/filabridge/include/private/filament/UibStructs.h
- libs/filamat/src/shaders/UibGenerator.cpp
- shaders/src/common_getters.glsl
- shaders/src/getters.fs
- shaders/src/shading_parameters.fs
added `getUserWorldFromWorldMatrix()` and `getUserWorldPosition()` to  retrieve the API-level (user) world position in materials.  Deprecated `getWorldOffset()`
`getWorldOffset` didn't work when an IBL rotation was applied.
> Add way to retrieve the user world-space in materials

- NEW_RELEASE_NOTES.md
- filament/backend/CMakeLists.txt
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/src/vulkan/VulkanReadPixels.cpp
- filament/backend/src/vulkan/VulkanReadPixels.h
- filament/backend/src/vulkan/VulkanTaskHandler.h
- Add a TaskHandler class for process events on the backend thread
- Check fence status when handler runs and copy bits to the client when the fence is reached.
> vulkan: async readPixels

- filament/backend/src/metal/MetalDriver.mm
The PixelBufferDescriptor was not being deallocated properly, which resulted in the leak. This patch explicitly deletes the PixelBufferDescriptor at the end of the callback to prevent the leak .This is necessary as the move constructor does not automatically deallocate the existing PixelBufferDescriptor.
> Metal: fix memory leak in readPixels

- android/samples/sample-material-builder/src/main/res/values/strings.xml
> android: fix sample-material-builder app name

- android/filament-utils-android/src/main/java/com/google/android/filament/utils/TextureLoader.kt
Hello, I do believe this was meant to be in the `com.google.android.filament.utils` package.
There where issues copying the `android/samples/sample-textured-object` into a new sample due to having this utility under the ".textured" package.
By changing to ".utils", it has allowed me to use these functions on other samples than "`sample-textured-object`".
Best Regards,
// Daniel
> Android: Fix wrong package name

- filament/backend/src/vulkan/VulkanDriver.cpp
`clearValues` needs to live past the call to `vkCmdBeginRenderPass`.
> Vulkan: fix stack use-after-free

- NEW_RELEASE_NOTES.md
- libs/filamat/src/shaders/CodeGenerator.cpp
- shaders/src/light_directional.fs
This will provide a boost to mobile devices by not computing the sun disc as it was intended.
> The sun disc should be computed in high quality only.

- shaders/src/getters.vs
In device vertex domain it is easy to specify infinite world-space coordinated (e.g. with the skybox), this results in complications everywhere. We were mitigating this by essentially moving these coordinates to around 16000 (give or take depending on the near plane), but that was way too small.
Now we move them around 1e19, which seems to work. It's important with applications rendering very large scenes to not use too small of a value.
> fix world-space coords of DEVICE vertex domain at infinity

- NEW_RELEASE_NOTES.md
- filament/CMakeLists.txt
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- filament/src/ShadowMapManager.cpp
- filament/src/details/Renderer.cpp
- filament/src/materials/debugShadowCascades.mat
- libs/filabridge/include/private/filament/UibStructs.h
- shaders/src/common_graphics.fs
- shaders/src/getters.fs
- shaders/src/main.fs
this allows us to remove code from the main shaders that is basically never used, reducing shader size and runtime costs.
> implement cascades visualization as a post-process

- NEW_RELEASE_NOTES.md
- libs/utils/include/utils/ostream.h
- libs/utils/src/ostream.cpp
- third_party/spirv-cross/spirv_common.hpp
- third_party/spirv-cross/tnt/0001-convert-floats-to-their-smallest-string-representati.patch
- third_party/spirv-cross/tnt/README.md
We only need 9 digits, not 34, to represent floats. This reduces material packages size.
> spirv-cross: use a reasonable float to string conversion

- libs/filamat/src/shaders/CodeGenerator.h
... which is needed to avoid compilation error with recent LLVM libc++ (after https://reviews.llvm.org/D146097). Previously, symbols like std::terminate() were available through other headers (e.g. <functional>, <vector>, etc.).
> Add a missing #include <exception>

- third_party/basisu/encoder/basisu_enc.cpp
- third_party/basisu/tnt/README.md
- third_party/basisu/transcoder/basisu_containers.h
These errors and warnings only appear with more recent versions of the emscripten SDK.
> Fix emscripten compilation errors and warnings

- libs/geometry/src/TangentSpaceMesh.cpp
- libs/geometry/src/TangentSpaceMeshInternal.h
- libs/geometry/tests/test_tangent_space_mesh.cpp
This PR fixes a bug in the Lengyel method to respect the normal stride.
When using the Lengyel method, there's another bug where `getTriangles(ushort3*)` crashes. Even though 16 bit indices were provided, `is16` is false. I think this is due to a problem with `InternalArray::operator bool`. If the array has a valid "borrowed" pointer, then we should return true.
Note that the Lengyel method doesn't actually remesh, but `getTriangles` should still work.
> TangentSpaceMesh fixes

- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/MaterialBuilder.cpp
- tools/matc/src/matc/CommandlineConfig.cpp
- tools/matc/src/matc/Config.h
- tools/matc/src/matc/MaterialCompiler.cpp
The feature-level option sets the maximum feature level allowed for the material. matc will fail if the specified material has a higher feature level than the value set with the feature-level option. The default is 3 (max).
This can be used to ensure that materials don't use features above a specified level.
> matc: new feature-level options

- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/eiff/ChunkContainer.h
- libs/matdbg/src/ShaderReplacer.cpp
'child' didn't make any sense in this API, push/emplace mimics std::vector, which is closer to what the api actually does.
> rename ChunkcContainer::addChild/addSimpleChild to push/emplace

- third_party/libassimp/tnt/CMakeLists.txt
- third_party/libz/tnt/CMakeLists.txt
zlib will fix this issue later (see https://github.com/madler/zlib/issues/633).
For now we will just turn off the warning.
> Suppress numerous libz warnings

- NEW_RELEASE_NOTES.md
- filament/src/details/Material.cpp
- libs/filabridge/include/private/filament/Variant.h
- libs/matdbg/src/CommonWriter.cpp
The VSM variant is never needed for unlit materials, it was filtered out correctly for color shaders but not for the depth shaders. This removes 4 variants from all unlit materials.
Also improve matinfo variants output.
> filter out VSM variant for unlit materials DEPTH shaders

- filament/backend/src/opengl/OpenGLProgram.cpp
- filament/backend/src/opengl/OpenGLProgram.h
- filament/src/MaterialParser.cpp
- filament/src/MaterialParser.h
- filament/src/details/Material.cpp
- filament/src/details/Material.h
- libs/filaflat/include/filaflat/MaterialChunk.h
- libs/filaflat/src/MaterialChunk.cpp
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/eiff/MaterialSpirvChunk.cpp
- libs/filamat/src/eiff/MaterialTextChunk.cpp
- libs/filamat/src/eiff/ShaderEntry.h
- libs/matdbg/src/ShaderExtractor.cpp
- libs/matdbg/src/ShaderReplacer.cpp
- `ProgramBuilder` is a relic, rename to `Program`
- use the enum instead of ints everywhere for `ShaderModel` and `ShaderStage`
- Improve how we cache shared shaders:
Some shaders can be shared across all materials (e.g. the depth 
shaders). We use the filament default material as the "source" of
the cache, but until now we relied on an a priori knowledge of which
variants were present in the default material.
With this change, we now query once the list of variants (of interest)
in the default material and reuse that list for caching these variants
later.
This is better because the cached variants are now entirely driven by
the default material (which they depend on anyways). This is also faster
because we don't need to query which variant we need each time we create
a material.
> improvements to material code and material creation

- NEW_RELEASE_NOTES.md
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/ShaderMinifier.cpp
- libs/filamat/src/ShaderMinifier.h
This changes the behavior of the size optimizer in matc (-S), but only for GLSL and MSL. With this change we gain a ~65% size reduction on a lit material compiled for OpenGL. To get those gains we generate extra SPIRV debug information to preserve variable names and better utilize the line dictionary. Unfortunately this break the SPIRV optimizer so we skip it and instead rely on a simple DCE pass provided by glslang. We also enhance the whitespace removal pass of the GLSL minifier to move lone { and } to the previous line, which avoids generating an extra index in each shader variant. Each index being at least as big as the character itself, this is quite wasteful.
When generating SPIRV for Vulkan, we rely on spirv-opt for size optimizations as before.
> Improve size optimizations when compiling material

- NEW_RELEASE_NOTES.md
- filament/src/materials/debugShadowCascades.mat
- libs/filabridge/include/filament/MaterialEnums.h
- libs/filabridge/include/private/filament/UibStructs.h
- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/shaders/CodeGenerator.cpp
- libs/filamat/src/shaders/CodeGenerator.h
- libs/filamat/src/shaders/ShaderGenerator.cpp
- libs/filamat/src/shaders/ShaderGenerator.h
- libs/filamat/src/shaders/UibGenerator.cpp
- shaders/src/common_getters.glsl
- shaders/src/common_lighting.fs
- shaders/src/common_types.glsl
- shaders/src/depth_main.fs
- shaders/src/getters.fs
- shaders/src/getters.vs
- shaders/src/light_directional.fs
- shaders/src/light_indirect.fs
- shaders/src/light_punctual.fs
- shaders/src/light_reflections.fs
- shaders/src/main.vs
- shaders/src/shading_unlit.fs
- shaders/src/shadowing.fs
- tools/matc/src/matc/MaterialCompiler.cpp
- refactor the code so that all defines are generated in the same place
- generate common_type after all defines are generated
- protect (with defines) structures and UBOs that are not needed, based
on the variant
- don't use a trailing `f` for floats, it's not needed and not supported in ES2
⚠️ new material version needed
> Cleanup shader generation

- filament/backend/CMakeLists.txt
- filament/backend/src/vulkan/VulkanBlitter.cpp
- filament/backend/src/vulkan/VulkanBuffer.cpp
- filament/backend/src/vulkan/VulkanContext.cpp
- filament/backend/src/vulkan/VulkanContext.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanFboCache.cpp
- filament/backend/src/vulkan/VulkanFboCache.h
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanImageUtility.cpp
- filament/backend/src/vulkan/VulkanImageUtility.h
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanStagePool.cpp
- filament/backend/src/vulkan/VulkanSwapChain.cpp
- filament/backend/src/vulkan/VulkanTexture.cpp
- filament/backend/src/vulkan/VulkanTexture.h
- filament/backend/src/vulkan/VulkanUtility.cpp
- filament/backend/src/vulkan/VulkanUtility.h
- Moved most of the layout transition logic into VulkanImageUtil so that we'd have a single place to consider if failure arises
- Add an abstraction on top of vk's layouts so that reasoning about our use cases (and corresponding layout is easier).
- Removed the redundant VulkanDepthLayout
- Refactor VulkanTexture::transitionLayout so that most of the transition paths can be done through this entry point. It also enables us to handle tracking the current layout.
- Add a special case to transition the depth attachment/texture if it is both a sampler and an attachment.
- Add a few debug printing markers across the classe - guarded under the existing FILAMENT_VULKAN_VERBOSE define.
> vulkan: refactor image layout transition

- NEW_RELEASE_NOTES.md
- filament/src/PostProcessManager.cpp
- filament/src/details/View.cpp
- shaders/src/depth_main.fs
floats can have up to 16.7M unique integers which is enough for encoding an Entity. 
This change will help a later one that adds support for ES2
> change picking to use floats

- shaders/src/fog.fs
When unlit, the IBL specular map is not defined.
> fog: disable fog color from IBL when unlit

- android/buildSrc/src/main/groovy/FilamentPlugin.groovy
- build.sh
- `-g` option was missing from `build.sh`
- `-Pcom.google.android.filament.matnopt` should be passed to the sample apps as well.
- Add logic to respect `-Pcom.google.android.filament.matnopt` in `FilamentPlugin.groovy`
> Fix no-opt build option for materials

- NEW_RELEASE_NOTES.md
- libs/filamat/src/GLSLPostProcessor.cpp
Turning off the simplification pass seems to remove all of the artifacts associated with Adreno GPUs.
Fixes #5885, Fixes #5884, Fixes #4381, Fixes #6465
> vulkan: Fix Adreno issue with optimized material

- NEW_RELEASE_NOTES.md
- filament/backend/include/backend/platforms/OpenGLPlatform.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLPlatform.cpp
- filament/src/details/Renderer.cpp
By default ancillary buffers are discarded on commit (eg. depth buffer), but in certain situations the platform may want to preserve them. this new virtual allows a concrete implementation to specify which buffers need to be preserved.
> Extend OpenGLPlatform to support preserving attachments on commit

- filament/src/details/Texture.cpp
SAMPLER_EXTERNAL is always false at texture build, cause related samples (sample-hello-camera, sample-stream-test) crash at native.
> Fix Sampler External texture build

- filament/backend/src/opengl/OpenGLContext.cpp
> deleteVertexArrays only destroyed the first VAO

- shaders/src/fog.fs
the skybox is unlit for instance, but for should still get the color from the ibl. that can't work with ES2 though.
> fog color from ibl should work with unlit

- NEW_RELEASE_NOTES.md
- android/filament-android/src/main/cpp/View.cpp
- android/filament-android/src/main/java/com/google/android/filament/View.java
- filament/include/filament/View.h
- filament/src/PerViewUniforms.cpp
- filament/src/PerViewUniforms.h
- filament/src/View.cpp
- filament/src/details/View.cpp
- filament/src/details/View.h
- libs/filabridge/include/private/filament/UibStructs.h
- libs/filamat/src/shaders/UibGenerator.cpp
- samples/gltf_viewer.cpp
- shaders/src/main.fs
- web/filament-js/jsbindings.cpp
This works by making the fog an entity which can be used to create
a TransformManager component an participate to the transform hierarchy.
This feature can be used as more advanced way to set the fog's floor,
which now can have an orientation (essentially be a plane). 
This is useful for coordinate systems that are not y-up.
> New API to apply a transform to the large-scale fog.

- NEW_RELEASE_NOTES.md
- android/filament-android/src/main/cpp/RenderableManager.cpp
- android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
- filament/include/filament/RenderableManager.h
- filament/src/RenderPass.cpp
- filament/src/RenderableManager.cpp
- filament/src/components/RenderableManager.cpp
- filament/src/components/RenderableManager.h
- web/filament-js/jsbindings.cpp
Fog can now be opted-out on a per renderable basis. When fog is disabled on a renderable it removes the requirement that this renderable's  materials have the FOG variant.
> New RenderableManager API to opt-out of fog

- NEW_RELEASE_NOTES.md
- docs/Materials.md.html
- filament/src/details/Renderer.cpp
- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/MaterialBuilder.cpp
- tools/matc/src/matc/CommandlineConfig.cpp
- tools/matc/src/matc/Config.h
- tools/matc/src/matc/MaterialCompiler.cpp
The number of usable sampler in materials is now documented and properly accounted for in matc.
> correctly account for user samplers in matc and document it

- filament/backend/src/opengl/OpenGLDriver.cpp
> Fix assertion in WebGL debug

- filament/src/RenderPass.cpp
- filament/src/details/Renderer.cpp
- we must sort commmands *after* we have added all commands!
- custom commands could change the UBO/Sampler bindings so we need to make sure to invalidate them after executing the command.
> fix a couple of subtle bugs related to custom commands

- libs/filamentapp/include/filamentapp/IBL.h
- libs/filamentapp/src/IBL.cpp
- libs/viewer/include/viewer/Settings.h
- libs/viewer/src/ViewerGui.cpp
- samples/gltf_viewer.cpp
this is implemented by here by using the skybox texture and blurring it with the irradiance filter + mipmapping. This only creates a subtle anisotropic phase-function effect.
> add support for custom fog color in gltf_viewer

- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/gl_headers.cpp
- filament/backend/src/opengl/gl_headers.h
We're just detecting the extension here, not making use of it.
> add basic support for KHR_parallel_shader_compile

- NEW_RELEASE_NOTES.md
- shaders/src/shadowing.fs
it's unclear if the problem was in spirv-cross or spirv-opt, but eitherway, the generated code at the end was invalid.
> workaround a bug in spirv-tools causing vsm to fail

- libs/filamat/src/GLSLPostProcessor.cpp
- shaders/src/shadowing.fs
spirv-opt's CreateSimplificationPass() causes spirv-cross to fail generating working glsl.
fixes b\286088016
> Workaround invalid glsl generation

- filament/backend/src/vulkan/VulkanBlitter.cpp
- filament/backend/src/vulkan/VulkanBlitter.h
- filament/backend/src/vulkan/VulkanBuffer.cpp
- filament/backend/src/vulkan/VulkanBuffer.h
- filament/backend/src/vulkan/VulkanContext.h
- filament/backend/src/vulkan/VulkanDisposer.cpp
- filament/backend/src/vulkan/VulkanDisposer.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/src/vulkan/VulkanFboCache.cpp
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.h
- filament/backend/src/vulkan/VulkanSamplerCache.cpp
- filament/backend/src/vulkan/VulkanSamplerCache.h
- filament/backend/src/vulkan/VulkanStagePool.cpp
- filament/backend/src/vulkan/VulkanStagePool.h
- filament/backend/src/vulkan/VulkanSwapChain.cpp
- filament/backend/src/vulkan/VulkanSwapChain.h
- filament/backend/src/vulkan/VulkanTexture.cpp
- filament/backend/src/vulkan/VulkanTexture.h
- filament/backend/src/vulkan/platform/VulkanPlatform.cpp
- flush() and wait() before destroying a swapchain
- Make sure the debug marker extension is enabled under correct circumstances.
- Change shared_ptrs to unique_ptrs and raw pointers.
- Rename most teardown methods to terminate()
Fixes #6838
> vulkan: minor fixes

- filament/src/PerShadowMapUniforms.cpp
this is needed on armv7 because we use alignas to get strcture-alignment, but that also implies (to the compiler) that the structure itself is aligned properly.
> align uniform buffer to 16 bytes

- NEW_RELEASE_NOTES.md
- android/filament-android/src/main/java/com/google/android/filament/android/FilamentHelper.java
- android/filament-android/src/main/java/com/google/android/filament/android/UiHelper.java
There was two related issues:
- we need to "latch" the new TextureView size when its resized. That can only be done by recreating the EGLSurface (i.e. recreating the SwapChain). UiHelper now calls onNativeWindowChanged in the case of  the TextureView resize, so clients can recreate their SwapChain.
- we also needed to make sure that all current filament frames have finished to render (i.e. the last eglSwapBuffers has been called) so that they don't pick-up a new size (this happens after  eglSwapBuffers) that doesn't match the viewport.
Fixes b/282220665
> helpers to fix jank when resizing a TextureView

- filament/backend/src/vulkan/VulkanImageUtility.cpp
Fixing validation warning of the form:
(UNASSIGNED-BestPractices-ImageBarrierAccessLayout) Validation Warning: [ UNASSIGNED-BestPractices-ImageBarrierAccessLayout ] Object 0: handle = 0x7f824f057218, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x849fcec7 | vkCmdPipelineBarrier: accessMask is VK_ACCESS_2_TRANSFER_READ_BIT, but for layout VK_IMAGE_LAYOUT_PRESENT_SRC_KHR expected accessMask are VkAccessFlags2(0).
> vulkan: fix present layout warning on mac

- filament/backend/src/vulkan/VulkanContext.cpp
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- Timer query stashed a pointer to VulkanCommandBuffer, but this points to an object that can be reused.
- We use the shared_ptr'd fence object instead to track whether the query request has been completed.
> vulkan: fix timer query

- filament/backend/src/vulkan/VulkanCommands.cpp
- filament/backend/src/vulkan/VulkanCommands.h
- filament/backend/src/vulkan/VulkanContext.cpp
- filament/backend/src/vulkan/VulkanContext.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
vkCmdEndDebugUtilsLabelEXT expects that a label was "pushed" onto the command queue (as described in the spec). It is possible to push labels across command buffers, but the pushed label must still be in the queue (unexecuted) when End is called. This implies that we need to make sure the labels are in a good state (all popped) when vkQueueSubmit is called.
- We add a stack to carry the labels across vkQueueSubmit.
- Also add CPU time durations between push and pop to provide rough CPU execution times (in debug).
- Add systrace markers for Android systrace
> vulkan: address debugUtils bug

- filament/backend/src/opengl/ShaderCompilerService.cpp
- filament/backend/src/opengl/ShaderCompilerService.h
when using the thread pool we were destroying the shaders immediately, we need to defer this until we query the program link status, so that  in case of failure we can query each shader compile status.
we make the shader handles part of the promise/future so they can be  transferred to the main thread, just like the program id is.
> fix error reporting with ShaderCompilerService

- CMakeLists.txt
Apple added `availability` annotations in the iOS 16.4 SDK to `std::bad_variant_access`. When using `std::visit` with a `std::variant`, several availability warnings are emitted by Clang (because we build for iOS 11.0):
```
OpenGLProgram.cpp:144:19: error: 'visit<(lambda at OpenGLProgram.cpp:144:25), const std::variant<int, float, bool> &, void>' is unavailable: introduced in iOS 12.0
s += std::visit([](auto&& arg) { return to_string(arg); }, sc.value);
```
Exceptions are already disabled in iOS release builds, and I think we can simply disable exceptions in iOS debug builds as well.
Fixes #6893
> Turn off iOS exceptions in debug builds

- libs/utils/src/Log.cpp
This avoids the need to use posix filesystem APIs just to write to stderr and stdout. These emscripten APIs behave the same as stdout/stderr as observed by the web assembly host.
Mirror of cl/540668528
> For web assembly, implement logging as emscripten_err and emscripten_out

- filament/backend/include/backend/platforms/PlatformEGL.h
This function is used in subclass PlatformEGLHeadless (see [here](https://github.com/google/filament/blob/1edad92d7341cb3f8dee59ef532aa6f13a411b61/filament/backend/src/opengl/platforms/PlatformEGLHeadless.cpp#L196)) resulting in build errors.
> Make initializeGlExtensions protected

- android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
- Use of getter method instead of property access syntax (for getInstance)
- 'rangeTo' or the '..' call should be replaced with 'until' (in for)
> [ModelViewer.kt, Remove Lint warning]

- build.sh
I think `./build.sh release run_gltf_viewer` doesn't work now.
> Fix typo in build.sh

- NEW_RELEASE_NOTES.md
- android/filament-android/src/main/cpp/Texture.cpp
- android/samples/sample-textured-object/src/main/java/com/google/android/filament/textured/MainActivity.kt
`AutoBitmap` extends `JniCallback` but they *both* define fields called `mHandler` and `mCallback`. This name
shadowing caused `AutoBitmap` to reference to its own `null`-initialized fields instead of the fields initialized by the
base class. This in turn caused user callbacks to not be invoked upon successful texture upload.
This issue was found while investigating bug #6936.
> Fix texture upload callbacks in Java/Kotlin

- NEW_RELEASE_NOTES.md
- android/samples/sample-transparent-view/src/main/java/com/google/android/filament/transparentrendering/MainActivity.kt
- filament/src/details/Renderer.cpp
The scene graph was using the wrong boolean to decide whether to fallback to low quality upscaling when the render target is translucent. It was instead only looking at the view's blending mode. We need to check both, as color grading does in the same function.
Fixes #6927
> Fix dynamic resolution with quality > low and translucency

- filament/backend/src/vulkan/VulkanContext.cpp
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
Call to Driver::getTimerQueryValue is synchronous so we need to make sure the fence shared_ptr is protected by a lock.
> vulkan: add lock to VulkanTimerQuery fence

- filament/backend/src/vulkan/VulkanSwapChain.cpp
Headless swapchains will use this signal to update their backing images if necessary.
> vulkan: swapchain resize condition update

- android/Windows.md
This pull request updates the Android build process documentation by replacing the deprecated Gradle flag `filament-skip-samples` in the code snippet with the new flag `com.google.android.filament.skip-samples`.
> Updated the gradle flag `filament-skip-samples` in the code snippet to align with the documentation.

- web/filament-js/jsbindings.cpp
With the *const* qualifier on the returned MaterialInstances, we cannot call setter functions like *setDepthWrite* etc. from the object, caused by
```
BindingError: Cannot convert argument of type MaterialInstance const* to parameter type MaterialInstance*
```
> web: remove const qualifier for getMaterialInstances

- NEW_RELEASE_NOTES.md
- libs/filabridge/src/Variant.cpp
The FOG variant filter has no effect because `UserVariantFilterBit::FOG != FOG`. Thus, this has no effect:
```
variant.key &= ~(filterMask & FOG);
```
I'm not sure why we needed to bitwise AND the `filterMask` with the variant bit. Maybe I'm missing something.
> Fix ineffective FOG variant filter

- NEW_RELEASE_NOTES.md
- libs/gltfio/src/ResourceLoader.cpp
see a example gltf from [gltf-Tutorial](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_017_SimpleMorphTarget.md)
> gltfio: fix crash when compute morph target without material

- NEW_RELEASE_NOTES.md
- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/ShaderCompilerService.cpp
- filament/backend/src/opengl/ShaderCompilerService.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/src/details/Material.cpp
The work queue is sorted by priority but when we insert a notification job we didn't have a priority to use for insertion, in addition the priority was taken from the token, but for the notification job we don't have a token.
The fix consists in passing the priority around so we have it when needed.
> fix a crash when using Material::compile with a callback

- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.h
- Before, we supposed that the maximum number of input attachment should match the maximum number of color attachments. But in reality, we've only used one input attachment for the second subpass.
- The problem with the above supposition is that the descriptor set layout for the input attachment descriptor set must have the exact number of input attachment specified in the shader. If the *layout* has more input attachment slots than specified in the shader, then we'd run into a validation error.
- In this patch, we fix the number of max input attachment in the descriptor set layout to 1, since we ever only make use of one.
Fixes #6513
> vulkan: fix subpass validation

- filament/backend/CMakeLists.txt
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/src/vulkan/VulkanReadPixels.cpp
- filament/backend/src/vulkan/VulkanReadPixels.h
- Carry out readPixels without blocking and wait for the read to complete own a separate thread.
- Add mContext.commands->wait() in finish()
- Wait for readPixels to complete in finish()
- Remove unused commandBuffer in Context
> vulkan: Implement async readPixels

- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/gl_headers.h
- libs/filamat/CMakeLists.txt
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/GLSLPostProcessor.h
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/SpirvFixup.cpp
- libs/filamat/src/SpirvFixup.h
- libs/filamat/src/shaders/CodeGenerator.cpp
- libs/filamat/src/shaders/CodeGenerator.h
- libs/filamat/src/shaders/ShaderGenerator.cpp
- libs/filamat/tests/test_clipDistanceFixup.cpp
- shaders/src/varyings.glsl
This PR sets up the ability for shaders to use `gl_ClipDistance`, which will be needed in the future. Desktop GL supports this natively. OpenGL ES requires the EXT_clip_cull_distance extension.
Unfortunately glslang does not support this extension, so we have to employ a workaround for mobile when going through glslang. We instead write to `filament_gl_ClipDistance`, and then modify the SPIR-V to decorate this as `gl_ClipDistance`. See the comment in SpirvFixup.h.
Note this PR does not actually use `gl_ClipDistance` yet, so there should be no change to shaders.
> Support EXT_clip_cull_distance for future use

- android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
This is useful for testing our shutdown code.
> The "back" key will now terminate the gltf_viewer activity

- NEW_RELEASE_NOTES.md
- libs/filamat/src/GLSLPostProcessor.cpp
The crashes are triggered by spirv-opt's MergeReturnPass, so we  just disable it. This pass also caused issues with AMD drivers on macOS.
fixes b/291140208
> workaround a crash with some adreno drivers

- android/filament-android/src/main/java/com/google/android/filament/RenderTarget.java
- filament/include/filament/RenderTarget.h
- filament/src/details/RenderTarget.cpp
This was a somewhat arbitrary requirement, some RenderTarget could be depth only for instance.
> `RenderTarget` needs not to have a color attachment

- NEW_RELEASE_NOTES.md
- shaders/src/main.vs
- shaders/src/post_process.vs
The PowerVR compiler systematically crashes on some devices when `gl_Position` is written twice in the vertex shader.
fixes #5118, b/190221124
> Workaround for some PowerVR devices

- filament/backend/src/opengl/ShaderCompilerService.cpp
- filament/backend/src/opengl/ShaderCompilerService.h
instead of moving the "urgent" compilation to the head of the queue, we simply remove it from the queue and process it immediately. This has the benefit that on drivers that truly support parallel compilation, the latency will be reduced as we don't need to wait for the current compile to finish.
> better handle "urgent" shader compilation

- filament/src/Froxelizer.cpp
- libs/math/include/math/mat2.h
- libs/math/include/math/mat4.h
- the return value was inverted
- fuzzyEqual could generate alignment faults
- move it out of mat4 and mat2 because it was only used in one place.
> fix fuzzyEqual

- filament/src/details/Material.h
This assert isn't really needed anymore, but I'll keep it around for posterity in case we change the variant bits in the future.
> Fix assert with matdbg enabled

- android/samples/sample-image-based-lighting/src/main/java/com/google/android/filament/ibl/MainActivity.kt
- filament/backend/include/backend/platforms/PlatformEGL.h
- filament/backend/src/opengl/platforms/PlatformEGL.cpp
EGL_KHR_surfaceless_context is needed to be able to use eglMakeCurrent without an EGLSurface.
> don't use eglMakeCurrent with EGL_NO_SURFACE unless we're allowed

- filament/backend/CMakeLists.txt
- filament/backend/src/CompilerThreadPool.cpp
- filament/backend/src/DriverBase.h
- filament/backend/src/opengl/CallbackManager.cpp
- filament/backend/src/opengl/CallbackManager.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/ShaderCompilerService.cpp
- filament/backend/src/opengl/ShaderCompilerService.h
- remove support for non-shared contextes parallel compilation. this wasn't used. we can always revive it later if we need to.
- rework how callbacks work so that we don't have to use a work list executed at each tick() in the shared context case (common case). this improves performance significantly on low-end devices, by not having to go through the list to check if all programs are compiled, multiple times per frame.
The new CallbackManager handles scheduling the callbacks after all previous programs are compiled.
> rework ShaderCompilerService to improve performance

- filament/backend/src/opengl/platforms/PlatformEGL.cpp
turns out that KHR_surfaceless_context is implied for ES3.0 when  KHR_create_context is present. However, Adreno 306 fails even if it advertises it. So, we now reset the value of KHR_surfaceless_context based on actually calling eglMakeCurrent(EGL_NO_SURFACE).
> better fix for calls to eglMakeCurrent

- filament/backend/src/vulkan/VulkanContext.h
- filament/backend/src/vulkan/VulkanReadPixels.cpp
- filament/backend/src/vulkan/VulkanTexture.cpp
- filament/backend/src/vulkan/platform/VulkanPlatformSwapChainImpl.cpp
readPixels requests staging memory to be host-visible/coherent/cached. But "cached" is not supported on Mali (Pixel 6pro).  We make it an preferrable but optional bit.
> vulkan: fix readPixels selectMemory

- filament/backend/include/backend/platforms/OpenGLPlatform.h
- filament/backend/include/backend/platforms/PlatformEGL.h
- filament/backend/src/CompilerThreadPool.cpp
- filament/backend/src/CompilerThreadPool.h
- filament/backend/src/opengl/OpenGLPlatform.cpp
- filament/backend/src/opengl/ShaderCompilerService.cpp
- filament/backend/src/opengl/platforms/PlatformEGL.cpp
CompilerThreadPool:
- it now supports a thread cleanup function
- some initialization is moved to the setup function
OpenGLPlatform:
- now cleans-up the thread pool threads upon exit
> improvements to CompilerThreadPool and OpenGLPlatform

- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- early initialization is now implemented with static methods so that it's very clear which state they need.
- the version number is no longer used outside of initialization, instead we use the feature level.
- ES3.0 Adreno devices are downgraded to feature level 0
> rework how we initialize the gl context

- libs/math/tests/test_mat.cpp
```
TYPED_TEST(MatTestT, cofactor) {
static constexpr TypeParam value_eps =
TypeParam(1000) * std::numeric_limits<TypeParam>::epsilon();
typedef filament::math::details::TMat33<TypeParam> M33T;
std::default_random_engine generator(992626); // NOLINT
std::uniform_real_distribution<TypeParam> distribution(-100.0, 100.0);
auto rand_gen = std::bind(distribution, generator);
for (size_t i = 0; i < 100; ++i) {
M33T r = M33T::eulerZYX(rand_gen(), rand_gen(), rand_gen());
M33T c0 = details::matrix::cofactor(r);
M33T c1 = details::matrix::fastCofactor3(r);
EXPECT_VEC_EQ(c0[0], c1[0]);
EXPECT_VEC_EQ(c0[1], c1[1]);
EXPECT_VEC_EQ(c0[2], c1[2]);
}
}
```
This UT failed on Mac M2 chip machine. The root cause is the floating point calculations is not exactly like intel chip.
check this link: …
> Fix Mat cofactor UT error on Mac M2 chip machine.

- NEW_RELEASE_NOTES.md
- shaders/src/shading_lit.fs
- shaders/src/shading_unlit.fs
The emissive property should not be multiplied by the color alpha in masked materials. The alpha is treated as a coverage value in that case, not an opacity value.
Before:
After:
> Properly apply emissive to masked materials

- libs/math/include/math/half.h
- libs/math/include/math/quat.h
try to fix issue #7013
I tried to use emsdk 3.1.44 to compile `webgl` platform. 
`./build.sh -p webgl release`
with following errors:
```
filament/libs/math/include/math/half.h:163:35: error: identifier '_h' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
163 | inline constexpr half operator "" _h(long double v) {
|                       ~~~~~~~~~~~~^~
|                       operator""_h
1 error generated.
```
the clang version of `emsdk` is `17.0.0`.
```
emsdk/upstream/bin/clang++ --version
clang version 17.0.0 (https://github.com/llvm/llvm-project a8cbd27d1f238e104a5d5ca345d93bc1f4d4ab1f)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Users/jacob/hack/emscripten/emsdk/upstream/bin
```
issue #7013  said …
> Bug: fix underscores literal operators c++ compatible error.

- build.sh
Refactor & Debug build.sh script:
1. Let platforms, ABIs, release/debug targets case insensitive:
```
./build.sh -p Android Debug
```
Above cmd will do nothing, because Android & Debug are case sensitive. So let those keywords case insensitive maybe a good idea.
2. Add error msg to remind the developer:
```
./build.sh -p android
./build.sh -p andr
./build.sh -p android bug
./build.sh -p android -q arm debug
```
Above error cmds will not has hints to remind the developer, so I add error msg to cover: missing targets, invalidate platform, invalidate target, invalidate ABI.
3. Let `ISSUE_DESKTOP_BUILD` as false
This var can be `false`, I just need to rearrange the build orders at the end of the script, and the only dependency is `run_tests`, I add build the desktop `Debug` target manually …
> refactor build.sh script.

- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- filament/src/ShadowMapManager.h
- libs/math/include/math/TVecHelpers.h
in stable mode the scale was ever so slightly varying with the  camera position, because it was calculated from the camera frustum in world-space, this variation was amplified when the camera is far from  the origin, which eventually caused the modulo needed for snapping the shadowmap projection to widely vary, leading to the instability.
We now calculate the camera frustum sphere in view space, which is guaranteed to be constant. If "shadow caster mode" is chosen, we  quantize the scale a little bit so it stays constant.
The snapping code itself has been cleaned.
> fix shadow stability when eye is far from world origin

- filament/backend/include/backend/DriverEnums.h
This was causing the OpenGL backend to assert on x86_64 Macs:
```
assert_invariant(mSamplerMap.find(params) == mSamplerMap.end());
```
> Fix incorrect SamplerParams operators

- filament/backend/src/opengl/ShaderCompilerService.cpp
- filament/backend/src/opengl/ShaderCompilerService.h
Otherwise, we end up calling `.put` twice.
> Only call .put if the tick op was canceled

- ios/samples/hello-gltf/hello-gltf/CameraManipulator.h
- ios/samples/hello-pbr/hello-pbr/CameraManipulator.h
1. ios sample: ios/samples/hello-gltf;
2. ios sample: ios/samples/hello-pbr;
see #7153
> fix ios samples missing functional header (#7153)

- libs/viewer/src/Settings.cpp
this "fixes" point light shadows in gltf_viewer, which were never enabled
> apply shadow settings to all lights in the scene

- NEW_RELEASE_NOTES.md
- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- samples/gltf_viewer.cpp
- shaders/src/getters.fs
- use the geometric normal to apply the shadow bias. This affects
cascades > 0 and spot/point lights.
- use the scene's origin as a reference point for stabilizing the
shadowmap, this is more robust.
- clamp directional shadowmap correctly to the 1-texel border, which
needs to be reachable, as it is a valid value.
- don't snap the shadowmap to texel boundaries if stable mode is not
active (before we only didn't do it based on lispsm). Stable mode can
make the shadow unstable when both the camera and the scene move 
together, so it's better to have a more predictable API where
"stable" mode means that the snapping occurs and doesn't otherwise.
- add "far origin" distance slider to the debug ui
FIXES=[299310624]
> Improvements to shadowing

- NEW_RELEASE_NOTES.md
- android/gltfio-android/CMakeLists.txt
- libs/gltfio/CMakeLists.txt
- libs/gltfio/include/gltfio/TrsTransformManager.h
- libs/gltfio/src/Animator.cpp
- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/FFilamentAsset.h
- libs/gltfio/src/FTrsTransformManager.h
- libs/gltfio/src/FilamentAsset.cpp
- libs/gltfio/src/TrsTransformManager.cpp
When animate for rotation or scale path, decompose the transform matrix may change the sign of scale, and then compose the matrix back with scale or rotation changed by animation, the matrix may be wrong.
This PR add a new TrsTransformManager to save the TRS value of node from gltf data, and then compose the TRS and assign to TransformManager's transform.
Here is a test gltf:
[animation.glb.tar.gz](https://github.com/google/filament/files/12488413/animation.glb.tar.gz)
Before:
After:
> Fix possible change of scale sign when decomposing matrix

- BUILDING.md
- CONTRIBUTING.md
- README.md
- android/samples/README.md
- filament/README.md
- libs/filamat/README.md
- site/content/posts/cocoapods.md
- tools/cmgen/README.md
- tools/filamesh/README.md
- tools/matinfo/README.md
- tools/mipgen/README.md
- tools/specular-color/README.md
This is admittedly a very nitpicky change.
For most of the changes, I went through the various Markdown files and added language names to the source blocks for better syntax highlighting on GitHub. It also makes it easier to copy and paste commands without copying the leading `$`. I avoided changing anything in `third_party`.
Additionally, I added some instructions for compiling the Android samples on the command line and fixed some typos.
> Tweak documentation

- filament/backend/src/vulkan/VulkanBlitter.cpp
- filament/backend/src/vulkan/VulkanBuffer.cpp
- filament/backend/src/vulkan/VulkanBuffer.h
- filament/backend/src/vulkan/VulkanCommands.cpp
- filament/backend/src/vulkan/VulkanCommands.h
- filament/backend/src/vulkan/VulkanContext.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanResourceAllocator.h
- filament/backend/src/vulkan/VulkanResources.h
- filament/backend/src/vulkan/VulkanStagePool.cpp
- filament/backend/src/vulkan/VulkanSwapChain.cpp
- filament/backend/src/vulkan/VulkanTexture.cpp
We were calling vkFreeCommandBuffers directly, but resetting the buffers implicitly (when vkBeginCommandBuffer is called) seems to be a lot more performant.
Also, cleaned up destructor for VkBuffer to no longer require a separate terminate() method.
> vulkan: implicitly free command buffers

- .github/workflows/release.yml
This probably broke due to a change from old windows command prompt to powershell. The way to refer to env variables in powershell is `$Env:var`
> Fix the output of Windows release workflow

- filament/backend/src/metal/MetalDriver.mm
- filament/backend/test/test_MipLevels.cpp
If a texture's min or max lod changed between render passes, the Metal backend wasn't correctly updating the texture binding unless `updateSamplerGroup` was also called, but that shouldn't be a requirement.
> Fix, Metal setMinMaxLevel called between render passes

- filament/include/filament/Box.h
- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- samples/gltf_viewer.cpp
Functionally this shouldn't be too different, but we have some improvements:
- better detection of "no shadows" cases
- more computations done in light-space, which should result in better light frustum.
- spit the code into several static functions
> improve/simplify "Focus on shadow casters" algorithm

- android/filament-utils-android/src/main/java/com/google/android/filament/utils/Half.kt
- build.sh
- filament/benchmark/CMakeLists.txt
- libs/image/CMakeLists.txt
- tools/cmgen/CMakeLists.txt
- tools/cso-lut/CMakeLists.txt
- tools/filamesh/CMakeLists.txt
- tools/matinfo/CMakeLists.txt
- tools/mipgen/CMakeLists.txt
- tools/normal-blending/CMakeLists.txt
- tools/roughness-prefilter/CMakeLists.txt
- tools/uberz/CMakeLists.txt
The latest macOS toolchain triggers warnings for duplicate libraries at link time. This is caused by our dependency chains.
Also remove an inlining warning in Kotlin and unnecessary warnings in build.sh when doing a clean or generating web docs.
> Fix build warnings

- filament/backend/src/opengl/OpenGLProgram.cpp
- filament/src/RenderPass.cpp
- filament/src/components/RenderableManager.cpp
- filament/src/details/SkinningBuffer.cpp
- filament/src/details/SkinningBuffer.h
all textures declared in a shader must be bound, in the case of the
new skinning API, if less than 4 bone weights are used the texture is 
not needed, but it must still be bound.
> skinning: fix a possible crash/assert

- libs/gltfio/CMakeLists.txt
- libs/gltfio/test/gltfio_test.cpp
1. **Fix the `ld` test_gltfio duplicated libraries**:
```
[2/2] Linking CXX executable libs/gltfio/test_gltfio
ld: warning: ignoring duplicate libraries: 'filament/libfilament.a', 'libs/filabridge/libfilabridge.a', 'libs/geometry/libgeometry.a', 'libs/ktxreader/libktxreader.a', 'libs/math/libmath.a', 'libs/uberz/libuberzlib.a', 'libs/utils/libutils.a', 'third_party/stb/tnt/libstb.a'
```
**Cause**:
the cmake file `libs/gltfio/CMakeLists.txt` config `link_libraries(math utils filament cgltf stb ktxreader geometry tsl trie uberzlib)` for the targets includes `test_gltfio`.
**Solution**:
clear `link_libraries` property for `test_gltfio` target.
```
set_property(TARGET test_gltfio PROPERTY LINK_LIBRARIES)
```
2. **Fix UT `glTFIOTest.AnimatedMorphCubeTransforms`**
run `test_gltfio`: …
> Fix test_gltfio cmake duplicate libs and failed UT.

- NEW_RELEASE_NOTES.md
- shaders/src/main.fs
- shaders/src/shading_lit.fs
- shaders/src/shading_unlit.fs
When a material using the MASKED blend mode, we sharpen the alpha channel to avoid banding and unwanted translucency with MSAA. To do this properly however, we must output the *sharpened* alpha value, and not the *original* alpha value. This change moves the alpha masking test to right after we initialize the material inputs with the user code so that the rest of our shaders will user the correct alpha value. The line that was causing problems in our case was the last line in evaluateLights() which returns a vec4 containing an alpha computed from the input's alpha instead of the sharpened alpha.
This change has the added benefit of unifying the alpha masking code between lit and unlit shaders, which contained duplicated code for not good reason. Note that moving the call to the …
> Fix masked materials

- NEW_RELEASE_NOTES.md
- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/sca/ASTHelpers.cpp
- libs/filamat/src/sca/ASTHelpers.h
- libs/filamat/src/sca/GLSLTools.cpp
- libs/filamat/src/sca/GLSLTools.h
- libs/filamat/src/shaders/CodeGenerator.cpp
- libs/filamat/src/shaders/MaterialInfo.h
- libs/filamat/src/shaders/ShaderGenerator.cpp
- libs/filamat/tests/test_filamat.cpp
- shaders/src/depth_main.fs
these materials would not generate proper structure or shadow buffer,
because they used a special variant that in most case removed the
user code.
now when the user code writes the depth or calls discard, the user
shader is kept.
> fix materials that write to the depth or use discard

- NEW_RELEASE_NOTES.md
- filament/src/PerViewUniforms.cpp
- filament/src/ShadowMap.cpp
- libs/filabridge/include/private/filament/UibStructs.h
- libs/filamat/src/shaders/UibGenerator.cpp
- libs/viewer/src/ViewerGui.cpp
- shaders/src/light_directional.fs
- shaders/src/light_punctual.fs
- shaders/src/shading_unlit.fs
Instead of a hard cutoff, we fade shadows out at 
the shadowFar distance if active, fading occurs
over about 10% of the shadowFar distance. 
- this works only for the directional shadow  (other lights don't use shadowFar).
> fade shadows out at shadowFar distance

- filament/CMakeLists.txt
- filament/src/details/Engine.cpp
- filament/src/details/Skybox.cpp
- filament/src/materials/defaultMaterial0.mat
- filament/src/materials/skybox0.mat
This reverts most of commit 9a6b8bf24e729c95b057aab0582310636e996cbe. The hello triangle sample remains unreverted.
The original commit inadvertently broke screen space reflections, and perhaps other features when the default material was used. The source of the issue is that MaterialBuilder.cpp (correctly) filters out variants that aren't supported in feature level 0 materials, including screen space reflections.
Unfortunately, while the "feature level 0 compatibility" feature itself was intended to make creating duplicate materials like this redundant in client code, unfortunately, it seems the best solution for resolving this issue is to simply keep these redundant materials in the core.
To elaborate: clients should expect that feature level 0 materials that they create work on /all/ …
> (Partially) revert "Remove now-redundant feature level 0 materials"

- filament/src/Culler.h
- filament/src/ShadowMap.h
- filament/src/details/View.h
It was changed to 16 a while back to handle more shadows, but since then we changed the culling algorithm and 8 bits is enough again.
> the visibility type can be 8 bits instead of 16.

- android/filament-android/src/main/java/com/google/android/filament/Engine.java
The default java class method access modifier is `protected`, The `Engine.Builder` is a static inner class of `Engine`, so the `Builder`'s methods, except the `public constructor`, are not accessible outside of `Engine` namespace.
And the `Engine.create` methods are announced `deprecated`. So I believe the `Engine.Builder`'s build methods should be publicly access from outside.
> fix java Engine.Builder method access modifiers.

- filament/include/filament/Camera.h
- filament/src/Camera.cpp
- filament/src/details/Camera.cpp
- filament/src/details/Camera.h
- setProjection and setLensProjection are now less special, they can now be entirely implemented by the user thanks to two new helper functions. Everything can now be done with setCustomProjection.
- fix some out-dated comments
- remove dead code
- reorder methods in Camera.h
> cleanup Camera code and docs

- libs/filamat/src/GLSLPostProcessor.cpp
The `emitNonSemanticShaderDebugInfo` was causing an assertion to fire in debug builds of matc and also generating problematic code that crashed on Android.
Removing it also seems to reduce lit material sizes by around 10%:
```
matc --api opengl --platform mobile --optimize-size -o out.cmat samples/materials/texturedLit.mat
```
```
Before: 154291 bytes
After: 138673 bytes
```
Fixes https://github.com/google/filament/issues/7256
> Remove problematic GlslangToSpv option: emitNonSemanticShaderDebugInfo

- libs/matdbg/CMakeLists.txt
- libs/matdbg/include/matdbg/DebugServer.h
- libs/matdbg/src/ApiHandler.cpp
- libs/matdbg/src/ApiHandler.h
- libs/matdbg/src/DebugServer.cpp
- libs/matdbg/web/script.js
The websocket code for parsing the EDIT command is pretty verbose. Proposing that we move to a HTTP POST request instead.
Also moved the API handler code out of DebugServer.h for clarity.
> matdbg: refactor EDIT command

- libs/matdbg/include/matdbg/DebugServer.h
- libs/matdbg/src/ApiHandler.cpp
- libs/matdbg/src/ApiHandler.h
- libs/matdbg/src/DebugServer.cpp
- libs/matdbg/web/script.js
- Use a hanging-GET approach to reduce dependency on websockets.
- Also add mutex to protect access to MaterialRecords, which is written to/read from from multiple threads.
> matdbg: change from websocket to GET

- BUILDING.md
- filament can be built with Visual Studio 2022 as well.
- Fix the link to the Windows SDK.
> Update BUILDING.md for the latest instruction

- libs/math/include/math/TQuatHelpers.h
We follow the same rules as C++, e.g. float * double -> double
> fix mixed-precision quaternion math

- NEW_RELEASE_NOTES.md
- filament/src/PerShadowMapUniforms.cpp
- filament/src/PerViewUniforms.cpp
- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- filament/src/details/Camera.cpp
- filament/src/details/Camera.h
- filament/src/details/Scene.cpp
- filament/src/details/Scene.h
- filament/src/details/View.cpp
- filament/test/filament_test.cpp
- libs/math/include/math/mat3.h
- libs/math/include/math/mat4.h
- libs/math/tests/test_mat.cpp
- samples/gltf_viewer.cpp
- shadows are now stable (in stable mode) when an IBL rotation is used.
- fix the shadow transform option which didn't work when an IBL rotation was used
- also use the x-axis as a reference for the "up" direction when computing the light space matrix so that we don't fall into the degenerate case when the light points straight down, which is a common case
FIXES=[299310624]
> fix a couple shadow stability bugs

- libs/viewer/include/viewer/ViewerGui.h
- libs/viewer/src/ViewerGui.cpp
For gltf models with more than one animations, we now can only check one by one, but sometimes we need to check the whole effect of all animations applied simultaneously.
This patch add a new "Apply All Animations" button for gltf_viewer, for check all animations quickly. 
Now for _mCurrentAnimation_:
_-1_: means not playing animation
_0 ~ numAnimations_: means playing the selected animation
_numAnimations_: means playing all animations
> samples: support apply all animations in gltf_viewer

- android/filament-android/src/main/java/com/google/android/filament/View.java
- filament/include/filament/DebugRegistry.h
- filament/include/filament/Options.h
- filament/src/DebugRegistry.cpp
- filament/src/PerViewUniforms.cpp
- filament/src/PerViewUniforms.h
- filament/src/details/DebugRegistry.cpp
- filament/src/details/DebugRegistry.h
- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
- filament/src/details/Material.cpp
- filament/src/details/Material.h
- filament/src/details/View.cpp
- libs/filabridge/include/private/filament/EngineEnums.h
- libs/filamat/src/shaders/CodeGenerator.cpp
- libs/viewer/src/Settings_generated.cpp
- libs/viewer/src/ViewerGui.cpp
- samples/gltf_viewer.cpp
- shaders/src/main.fs
- shaders/src/shadowing.fs
- web/filament-js/filament.d.ts
- web/filament-js/jsenums_generated.cpp
The directional shadowmap visualizer is implemented behind a 
specialization constant. Add the DebugRegistry infrastructure to be
able to update the spec-constant at runtime and have a subset of 
all materials invalidated.
This allows to toggle the visualization at runtime using a debug
property.
This is also a proof of concept that we can update spec-constants
at runtime; we could probably leverage this work for engine-wide
shader configurations.
> dynamic shadowmap visualization 

- filament/src/fg/FrameGraph.cpp
It was possible to run out of space with the Bistro scene and  everything enabled.
> Increase FrameGraph Arena to 256KiB

- filament/backend/src/vulkan/VulkanTexture.cpp
- filament/backend/src/vulkan/VulkanUtility.cpp
- filament/backend/src/vulkan/VulkanUtility.h
- filament/backend/src/vulkan/platform/VulkanPlatform.cpp
- filament/backend/src/vulkan/platform/VulkanPlatformSwapChainImpl.cpp
- filament/backend/src/vulkan/platform/VulkanPlatformSwapChainImpl.h
> vk: support stencil format in swapchain

- libs/filamat/src/MaterialBuilder.cpp
Leaving it unitialized creates msan failure.
> filamat: Fix MaterialInfo::userMaterialHasCustomDepth init

- filament/backend/src/opengl/OpenGLBlobCache.cpp
- filament/backend/src/opengl/ShaderCompilerService.cpp
- don't call BlobCache if link status false
- don't assume glGetProgramiv never fails
- don't assume malloc never fails
FIXES=[307549547]
> OpenGLBlobCache: be more robust when shader fails to compile

- filament/backend/include/private/backend/HandleAllocator.h
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
Before, each Attribute within a Filament `VertexBuffer` was bound to its own Metal buffer argument index. After this change, two buffers that share the same stride will map to the same index. This improves CPU performance by reducing redundant bindings, especially for scenes with lots of vertex attributes.
> Improve Metal vertex buffer bindings

- filament/src/components/CameraManager.cpp
- filament/src/components/CameraManager.h
- filament/src/details/Engine.cpp
CameraManager creates a Transform component for each Camera component is not already present. However, it didn't destroy the transform component when it's itself destroyed. the leaked transform component would eventually be garbage collected, but caused significant slow down and memory pressure. This is because camera components are created every frame for the shadow maps.
FIXES=[303914944]
> fix a Transform component leak in CameraManager

- NEW_RELEASE_NOTES.md
- android/filament-android/src/main/cpp/Engine.cpp
- android/filament-android/src/main/java/com/google/android/filament/Engine.java
- android/samples/sample-hello-triangle/src/main/java/com/google/android/filament/hellotriangle/MainActivity.kt
- filament/CMakeLists.txt
- filament/backend/include/backend/DriverEnums.h
- filament/include/filament/Engine.h
- filament/src/Froxelizer.cpp
- filament/src/PostProcessManager.cpp
- filament/src/RendererUtils.cpp
- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
- filament/src/details/Material.cpp
- filament/src/details/Skybox.cpp
- filament/src/details/View.cpp
- libs/filamentapp/materials/transparentColor.mat
- libs/filamentapp/src/FilamentApp.cpp
- samples/hellotriangle.cpp
- samples/materials/bakedColor.mat
This change does three main things. First, it adds an option to the Engine Builder to pick the feature level at which to instantiate Filament. The only real practical purpose of allowing this is to be able to instantiate at feature level 0. Secondly, it allows feature level 0 to properly work on non-ES2 devices. Thirdly, it changes both Android and desktop hellotriangle samples to explicitly opt-in to feature level 0.
Unfortunately, feature levels are used in two different, somewhat contradictory ways presently in Filament, which can make reasoning about this change a bit confusing. From a client perspective, feature levels refer to buckets of capabilities which are guaranteed to be supported. Internally, there is a separate "feature level" stored internally at the Driver subclass level …
> Allow explicitly initializing at feature level 0

- filament/backend/include/private/backend/HandleAllocator.h
- filament/src/details/Engine.h
We've seen hangs/ANR that are not well understood on that spinlock, so for now we're going back to mutexes, which, on android, are very  efficient under low contention (no syscall).
FIXES=[308029108]
> don't use a spinlock for the HandleArena

- filament/src/components/RenderableManager.cpp
- only check/log in debug builds
- use epsilon = 2e-7 * double(tempPairCount)
- compute boneWeightsSum in double
FIXES=[306565054]
> cleanup and better bone weight checks

- filament/backend/src/opengl/platforms/PlatformWGL.cpp
The reason is that some implementations of WGL require all contexts to be created on the same thread, which we're not necessarily doing here.
fixes #7078
> disable multiple context support on WGL

- filament/src/PerViewUniforms.cpp
- filament/src/PerViewUniforms.h
- filament/src/RendererUtils.cpp
- filament/src/RendererUtils.h
- filament/src/details/Renderer.cpp
- filament/src/details/View.cpp
- filament/src/details/View.h
When we enable SSR the first time, the SSR buffer is not initialized, this can result in the color pass fragment shader aborting, which in  turn prevents the SSR history buffer from being initialized (since  it's made from the result of the color pass), repeating the cycle.
In some other case, the system somehow recovers but we still see a flicker when enabling SSR.
The solution here is to disable SSR in the shader until the history buffer is ready (i.e. a frame later).
> fix SSR artifact when enabling SSR

- .gitignore
- build.sh
compile_commands.json was being generated, but hidden away inside of the cmake build directories. This change makes build.sh link it to the main project dir and adds some associated .gitignore entries. Now compile_commands.json is properly read when starting clangd from Emacs, for example, and probably many other editors.
> Add proper language server support

- filament/src/ShadowMapManager.cpp
- filament/src/ShadowMapManager.h
- filament/src/details/View.h
don't use FixedCapacityVector to store pointers to active shadowmaps, that's just not needed. They're all stored un a static array already and directional and spot shadows are partitioned. 
This saves a couple heap allocations as well a an pointer dereference.
> improve ShadowMapManager slightly

- NEW_RELEASE_NOTES.md
- android/filament-android/src/main/cpp/Material.cpp
- android/filament-android/src/main/java/com/google/android/filament/Material.java
- filament/backend/src/opengl/GLUtils.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/include/filament/Material.h
- filament/src/Material.cpp
- filament/src/PostProcessManager.cpp
- filament/src/details/Engine.cpp
- filament/src/materials/blitLow.mat
- libs/filabridge/include/private/filament/BufferInterfaceBlock.h
- libs/filabridge/src/BufferInterfaceBlock.cpp
- libs/filagui/src/materials/uiBlit.mat
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/shaders/CodeGenerator.cpp
- shaders/src/post_process_inputs.vs
Fix edge case where an empty struct could be generated in an ESSL 1.0 shader.
Include _maskThreshold and _doubleSided in ESSL 1.0 shaders.
Add GL_OES_standard_derivatives extension to ESSL 1.0 shaders. According to gpuinfo.org, this has 96% device coverage and supports both Mali-400 and Adreno (TM) 304.
Remove 3D sampler support from ESSL 1.0 shaders. This extension is only supported by 62% of devices.
Change filagui material to a FL0 material.
> Miscellaneous feature level 0 fixes

- libs/matdbg/web/api.js
- libs/matdbg/web/app.js
- Make sure matinfo works by selecting a default backend in the absence of activeShaders.
- Add options to select backend in matinfo mode.
- Workaround cursor misplacement for monaco
- Refactor menu sections into a common element.
> matdbg: fix matinfo use case

- libs/gltfio/include/gltfio/ResourceLoader.h
- libs/gltfio/src/ResourceLoader.cpp
- samples/gltf_viewer.cpp
Drag and dropping a gltf folder was broken:
- the handle didn't find the gltf file on drag&drop
- the ResourceLoader cached the asset path
- don't exit(1) when drag&dropping an invalid file
> repair gltf_viewer drag&drop

- filament/backend/src/vulkan/VulkanCommands.cpp
- filament/backend/src/vulkan/VulkanSwapChain.cpp
We removed the no-op queue submit for headless in PR #7264. This means that a semaphore will not be waited on and caused a validation error.  Here, we simply don't acquire that semaphore for present.
Also reorganzied the pSempaphores array code for better readability.
Fixes #7334
> vk: fix headless semaphore wait logic

- filament/src/fg/PassNode.cpp
There's no functional change. Remove an unused local variable `outgoingEdges` to save CPU resource. Tidy up an usage of local variable to slightly improve readability.
> Cleanup RenderPassNode::declareRenderTarget

- libs/gltfio/src/ArchiveCache.cpp
- samples/gltf_viewer.cpp
we recently added calls to Material::compile in gltfio to precompile materials are they are discovered. that wasn't a good call, because  this should be the responsibility of the app, not of gltfio, at least not without an option.
This is now done in gltf_viewer. We need something similar for  Android.
Bugs #7318, #7336
> don't precompile variants in gltfio

- filament/src/ShadowMap.cpp
- filament/src/ShadowMapManager.cpp
- filament/src/details/Scene.cpp
- we were not using the correct field in ShadowMapManager
- we were not computing the transform correctly, it should applied after the local transform, not before.
FIXES=[299310624]
> Fix (again) the shadow transform

- libs/gltfio/CMakeLists.txt
- libs/gltfio/include/gltfio/ResourceLoader.h
- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/DracoCache.cpp
- libs/gltfio/src/FFilamentAsset.h
- libs/gltfio/src/Ktx2Provider.cpp
- libs/gltfio/src/ResourceLoader.cpp
- libs/gltfio/src/StbProvider.cpp
- libs/gltfio/test/gltfio_test.cpp
- libs/matdbg/src/ApiHandler.h
- gltfio: Enable -Wall -Werror for gltfio_core
- gltfio: Fix various errors that were missed warnings
- matdbg: switch from std::atomic_uint64_t to std::atomic<uint64_t> for older clang
> Small compilation fixes

- NEW_RELEASE_NOTES.md
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/opengl/OpenGLProgram.cpp
- filament/backend/src/opengl/OpenGLProgram.h
- filament/src/PostProcessManager.cpp
- shaders/src/depth_main.fs
Fix specification of mipmaps when generating textures.
Fix oversight where emulated UBOs would not replace uniforms when swapped out for another.
> Fix some ES2 issues

- tools/matc/src/matc/MaterialCompiler.cpp
This change in glslang removes the include of "intermediate.h" from GlslangToSpv.h:
https://github.com/KhronosGroup/glslang/commit/62de186c3383feef067feb6ea578f79977910722
As a result, the definition of "class TIntermediate" is removed, and will fail compilation of MaterialCompiler.cpp when glslang is updated to a version including the aforementioned change. We fix this by adding an explicit include to this header in MaterialCompiler.cpp.
[internal]
> Add missing include for latest glslang

- android/filament-android/src/main/cpp/Engine.cpp
- android/filament-android/src/main/cpp/View.cpp
- android/filament-android/src/main/java/com/google/android/filament/Engine.java
- android/filament-android/src/main/java/com/google/android/filament/View.java
- filament/include/filament/Engine.h
- filament/include/filament/View.h
- filament/src/Engine.cpp
- filament/src/View.cpp
- filament/src/details/Engine.h
- filament/src/details/View.cpp
- filament/src/details/View.h
- libs/viewer/include/viewer/Settings.h
- libs/viewer/include/viewer/ViewerGui.h
- libs/viewer/src/Settings.cpp
- libs/viewer/src/ViewerGui.cpp
- samples/gltf_viewer.cpp
- web/filament-js/extensions.js
- web/filament-js/filament.d.ts
- web/filament-js/jsbindings.cpp
This also adds a public `Engine::getConfig` API, which helps simplify things.
Fixes #7330
> Move stereoscopic debug options to Settings framework

- filament/backend/test/BackendTest.cpp
- filament/backend/test/test_Blit.cpp
- filament/backend/test/test_FeedbackLoops.cpp
- filament/backend/test/test_LoadImage.cpp
- filament/backend/test/test_ReadPixels.cpp
- filament/backend/test/test_RenderExternalImage.cpp
With these fixes failing tests are:
OpenGL:
BackendTest.FeedbackLoops
Metal:
BackendTest.FeedbackLoops
BackendTest.ColorResolve
BackendTest.BufferObjectUpdateWithOffset
BasicStencilBufferTest.StencilBufferMSAA
Vulkan:
Many failures still
> fix a lot of issues with the backend tests

- CMakeLists.txt
- NEW_RELEASE_NOTES.md
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/GLSLPostProcessor.h
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/shaders/CodeGenerator.cpp
- third_party/spirv-cross/spirv_glsl.cpp
The CL introducing the ESSL 1.0 chunk in materials inadvertently disabled optimizations for said code. This commit reintroduces those optimizations and fixes associated bugs which manifested. In particular, spirv-cross was generating uints for bools; this has been fixed with a hack. Additionally, spirv-cross is now compiled with exceptions enabled so that matc can gracefully fail and show the code which failed to compile rather than abruptly aborting.
[Upstream issue for spirv-cross.](https://github.com/KhronosGroup/SPIRV-Cross/issues/2223)
[Upstream PR for spirv-cross.](https://github.com/KhronosGroup/SPIRV-Cross/pull/2227)
> Enable optimizations for ESSL 1.0 code

- android/filament-android/src/main/java/com/google/android/filament/android/UiHelper.java
We were not unregistering the TextureView or SurfaceHolder callbacks on detach, so they could fire and access an null'ed RenderSurface
FIXES=[308443790]
> Fix a possible NPE in UiHelper

- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/opengl/OpenGLProgram.cpp
- filament/backend/src/opengl/OpenGLProgram.h
- filament/backend/src/opengl/ShaderCompilerService.cpp
Until now invalid program would basically be undefined behavior, which in practice was a crash via a null pointer dereference. With this change, invalid programs cause drawing ops to become no-ops.
Additionally fixed an unsynchronized access of a the variable containing the program id. I don't think it would have caused issues though.
FIXES=[311775564]
> better handle invalid programs in release builds

- NEW_RELEASE_NOTES.md
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/shaders/CodeGenerator.cpp
- libs/filamat/src/shaders/CodeGenerator.h
- libs/filamat/src/shaders/ShaderGenerator.cpp
- libs/filamat/src/shaders/ShaderGenerator.h
matc was re-introducing the incorrect extension for external samplers in ESSL 1.0 code after spirv optimizations.
> Fix ESSL 1.0 external samplers

- android/filament-android/src/main/cpp/EntityManager.cpp
- android/filament-android/src/main/cpp/MaterialInstance.cpp
- android/filament-android/src/main/cpp/Scene.cpp
we were using the version of ReleaseIntArrayElements that doesn't always keep changes to the array.
> fix jni Scene.getEntities

- android/filament-android/src/main/java/com/google/android/filament/Texture.java
- filament/backend/include/backend/DriverEnums.h
- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/metal/MetalBlitter.h
- filament/backend/src/metal/MetalBlitter.mm
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/ostream.cpp
- filament/backend/src/vulkan/VulkanBlitter.cpp
- filament/backend/src/vulkan/VulkanBlitter.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/test/test_Blit.cpp
- filament/include/filament/Texture.h
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- filament/src/RendererUtils.cpp
- filament/src/details/Renderer.cpp
- filament/src/details/Texture.cpp
- filament/src/fg/FrameGraph.cpp
- web/filament-js/jsenums.cpp
- deprecate blit(), renamed to blitDEPRECATED. It's only used in one
place in copyFrame() now. We can't void it because we don't have
access to the texture from the RenderTarget.
- add a new blit() api that works with textures instead of render 
targets.
- add a new resolve() api that works with textures instead of render 
targets. doesn't support scaling.
- always use a shader when scaling in the framegraph
(there was only one place where we used blit)
- use the new blit() for:
- for mipmap generation on vk (fixme)
- copying the depth buffer to avoid ssao feedback loop
- use the new resolve() for:
- manually resolving MSAA color/depth
> Improve blitting APIs

- NEW_RELEASE_NOTES.md
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/shaders/ShaderGenerator.cpp
- libs/filamat/src/shaders/ShaderGenerator.h
Even if skinning is not fully implemented on FL0, we have clients which depend on materials with skinning variants that otherwise could easily be converted to FL0 materials. There are two proper ways to deal with this:
1. Support skinning/morphing in Feature Level 0.
2. Allow ESSL 1.0 code and ESSL 3.0 code to support different sets of variants.
However, the simplest solution is to just include skinning/morphing variants, but disable codegen for ESSL 1.0 code, making them identical to the base variants. This shouldn't increase the file size much due to the dictionary deflation. Of course, skinning will not work correctly on FL0, but this has always been the case. Future work here would be to properly implement one of the two solutions described above.
> Generate dummy skinning variants for FL0 mats

- CMakeLists.txt
The option is `FILAMENT_SHORTEN_MSVC_COMPILATION` and is ON by default (except for CI).
It enables multi-processor compilation and removes run-time STL checks to improve the performance of tools that runs at compile time (e.g. `matc`).
> Added an option to shorten compile time in Visual Studio

- filament/CMakeLists.txt
Changed the feature level 0 materials custom commands so that materials for all APIs are built.
This allows the following:
* Samples using the default material (e.g. hellotriangle) can be run in Vulkan (and potentially other APIs that are not OpenGL).
* The OpenGL backend can be disabled using `-DFILAMENT_SUPPORTS_OPENGL=OFF`. Previously, turning off the OpenGL backend was leading to a compilation error related to missing level 0 materials.
> Fixed feature level 0 material build rules

- shaders/src/post_process.vs
- shaders/src/post_process_getters.vs
- shaders/src/post_process_inputs.vs
we add a `position` field to PostProcessVertexInputs which the user code can modify if needed.
> Allow post-process materials to update the vertex position

- filament/backend/src/ostream.cpp
- filament/src/fg/PassNode.cpp
Imported targets always use the imported flags, not the flags that where specified when the target was created. The clear flags should be cleared after they've been used once in case that rendertarget is reused by multiple passes.
For e.g. if the clear flag is set, the target will be cleared the first time it is used, but if it's used again, we don't want to clear again,  in that case we'll use the "local" flags used when the target was created (as opposed to the imported flags).
> fix framegraph clear flags for imported targets

- filament/src/PostProcessManager.h
we make PostProcessMaterial, getPostProcessMaterial() as well as render(), commitAndRender() public (as in public to filament internals).
These methods have no reason to be private to PostProcessManager.
> make a few PostProcessManager methods "package" public

- filament/src/ShadowMapManager.cpp
- filament/src/details/View.cpp
The per-light shadow caster flag wasn't updated when a light was toggled from casting to non-casting. This resulted in an out of date or incorrect shadowmap to be used.
FIXES=[315859790]
> fix per-light shadow "caster" flag update

- filament/src/PerViewUniforms.cpp
- filament/src/ShadowMapManager.cpp
- filament/src/details/Camera.cpp
- filament/src/details/Camera.h
getUserWorldFromWorldMatrix() was always set to identity during the shadow pass. It needs to be set the the same value as the main camera.
FIXES=[315504607]
> fix getUserWorldFromWorldMatrix() during the shadow passes

- android/filament-android/src/main/java/com/google/android/filament/android/UiHelper.java
We shouldn't remove the listener callbacks when a surface is destroyed by the system (e.g. screen off/on) because then we won't know when it comes back.
But we still need to do this when the user calls UiHelper.detach() or when we are attaching to a new surface.
Fixes #7424
> Fix UiHelper

- filament/src/materials/antiAliasing/taa.mat
The history neighborhood variance needed to be computed in highp.
fixes #6504
> fix TAA on mobile devices.

- filament/backend/src/opengl/OpenGLDriver.cpp
I hit a seg fault here when (incorrectly) trying to use feature level 0 without #defining FILAMENT_ENABLE_FEATURE_LEVEL_0, which could have been caught by an assert here rather than a seg fault.
> Assert non-null texture in setTextureData

- android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentInstance.java
The current implementation restricts access to this method, and making it public will enable external classes or components to utilise this functionality
> Make`applyMaterialVariant` Method Public in FilamentInstance Class

- CMakeLists.txt
- filament/backend/src/metal/MetalBufferPool.h
- filament/backend/src/metal/MetalContext.h
1. MetalFence is constructed from two threads:
- the main thread, from `MetalDriver::createFenceS`
- the driver thread, from `MetalTimerQueryFence::beginTimeElapsedQuery`
Because the `MetalFence` constructor reads and writes to `context.signalId`, it needs to be made atomic.
2. `MetalBufferPool::mCurrentframe` needs to be made atomic, as it is accessed by two threads:
- the driver thread, from `MetalBufferPool::gc`, read/writes to `mCurrentFrame`
- a completion handler thread, from `MetalBufferPool::releaseBuffer`, reads `mCurrentFrame`
This also adds support for a new CMake flag to enable TSAN.
b/314267870
b/314265331
> Fix a couple race conditions in Metal backend

- ios/samples/gltf-viewer/gltf-viewer/FILModelView.h
- ios/samples/gltf-viewer/gltf-viewer/FILModelView.mm
- ios/samples/gltf-viewer/gltf-viewer/FILViewController.mm
This is an example implementation of how a client might utilize Filament's picking queries in an iOS app.
> Add picking queries to gltf-viewer iOS sample

- libs/matdbg/web/index.html
This font is used to render some of the icons in the matdbg editor. For some reason, monaco-editor wasn't loading this font automatically.
> matdbg: Load codicon font

- libs/utils/include/utils/ostream.h
Because `utils::io::flush(utils::io::ostream&)` is now implemented in a cpp file (introduced in https://github.com/google/filament/commit/d6b2ec49b0a9c7c166a5a39aa924808c73e28c25), its needs to be marked with public visibility to work correctly with dynamic libraries. Otherwise we get the following error:
```
ld: error: non-exported symbol 'utils::io::flush(utils::io::ostream&)' in 'blaze-out/k8-opt/bin/third_party/filament/libs/_objs/utils/ostream.pic.o' is referenced by DSO 'blaze-out/k8-opt/bin/_solib_k8/libthird_Uparty_Sfilament_Slibs_Slibimageio.ifso'
```
> Fix ostream linking error when compiling Linux DSO

- filament/src/details/MaterialInstance.cpp
There's no reason we can't report the material name here, even if the client is using the default material instance.
> Metal: Always report material name in use-after-free detector

- RELEASE_NOTES.md
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/shaders/ShaderGenerator.cpp
- libs/filamat/src/shaders/ShaderGenerator.h
See #7415 for a more detailed description of why this change is necessary.
The remaining variants which are filtered from FL0 materials are all related to lighting, so further hacks like this won't be necessary.
Future work involves properly supporting differing sets of variants based on shader language.
> Generate dummy stereo variants for FL0 mats

- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- filament/src/details/Renderer.cpp
TAA already does a fireflies reduction pass, so it's not needed when applying bloom.
> bloom: disable fireflies reduction when using TAA

- android/filament-android/src/main/java/com/google/android/filament/View.java
- filament/include/filament/Options.h
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- filament/src/details/Renderer.cpp
- libs/viewer/src/Settings_generated.cpp
- libs/viewer/src/ViewerGui.cpp
- web/filament-js/extensions_generated.js
- web/filament-js/filament.d.ts
- web/filament-js/jsbindings_generated.cpp
new DoF option to set the bokeh aspect ratio, this can be used to 
simulate anamorphic lenses
> Bokeh aspect ratio

- NEW_RELEASE_NOTES.md
- filament/backend/src/metal/MetalShaderCompiler.mm
This PR disables 'fast math' optimizations for Metal, which makes assumptions that Filament's GLSL code does not adhere to. One example is as follows.
Inside our GLSL fragment code, we use the `saturateMediump` define to clamp floating-point values to a maximum of `65504.0` (the largest finite half-precision value). The purpose is to manage values that could potentially reach Infinity during computation.
```glsl
precision mediump float;
#define MEDIUMP_FLT_MAX    65504.0
#define saturateMediump(x) min(x, MEDIUMP_FLT_MAX)
// ...
float d = // computation that could be Infinity
return saturateMediump(d);
```
However, when this code is cross-compiled to MSL with optimizations enabled, it translates to:
```c++
half d = // ...
return min(d, half(65504.0));
```
The issue here is that Metal's …
> Metal: disable fast math

- tools/matc/src/matc/JsonishLexer.cpp
When parsing a lexeme, we use one less byte than it's intended to be for comparing the current string.
This results in a success in cases like:
- true and truX
- false and falsX
- null and nulX
where X means an arbitrary character.
Fix this by using the full intended length.
> Fix a json parsing bug

- NEW_RELEASE_NOTES.md
- libs/iblprefilter/src/materials/equirectToCube.mat
- shaders/src/common_math.glsl
it was incorrectly mapping the equirect image to a cubemap due to a typo in our overload of atan2 which was swapping its parameters.
atan2 is now removed, and we use atan(y,x) instead. Also modified the code slightly so it matches almost exactly cmgen's.
FIXES=[320856413]
> fix IBLPrefilterContext::EquirectangularToCubemap

- filament/CMakeLists.txt
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- filament/src/ShadowMapManager.cpp
- filament/src/details/Engine.h
- filament/src/details/Renderer.cpp
- filament/src/materials/shadowmap.mat
- samples/gltf_viewer.cpp
The vizualizer is implemented inside filament itself and activated using the debug registry. This intended for filament development use.
> Shadowmap texture vizualizer

- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
It turns out that many drivers require to rebind the external texture after its content has changed, so we now always do that.
Bug #6188
> fix external images

- .github/workflows/android-continuous.yml
- .github/workflows/cocopods-deploy.yml
- .github/workflows/ios-continuous.yml
- .github/workflows/mac-continuous.yml
- .github/workflows/npm-deploy.yml
- .github/workflows/presubmit.yml
- .github/workflows/release.yml
- .github/workflows/web-continuous.yml
ref: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
> workflow: Update macos-latest to macos-14

- filament/backend/src/metal/MetalHandles.mm
Internal crash reports are showing crashes within `[CAMetalDrawable dealloc]`, which is currently being called on the driver thread (to match the same thread where it is acquired). It is suspected this is a poorly behaved object, which must be dealloced on the main thread.
This PR adds a new flag, `FILAMENT_RELEASE_PRESENT_DRAWABLE_MAIN_THREAD`, on by default, which changes the behavior to release the `CAMetalDrawable` on the main thread.
> Metal: schedule PresentDrawable for destruction on the main thread

- filament/backend/include/private/backend/HandleAllocator.h
- filament/backend/src/HandleAllocator.cpp
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- libs/utils/include/utils/Allocator.h
- update the pools sizes for metal and vulkan, which were very outdated.
- add debug code on all backends to print the size of each handle  (with a compile time switch)
The most important change is that now the 3 pools of HandleAllocator are sized so that each can accommodate about the same amount of handles. This makes it easier to reason about. The total amount of handles is three times that, since there are 3 pools. 
We also try to allocate the buckets so that handles are evenly distributed, however, that's very hand wavy.
With the current setup the number of handles per pool is as follows:
- GL : 3240 / pool / MiB
- VK : 1820 / pool / MiB
- MTL: 1310 / pool / MiB
> rework how we size the HandleAllocator's pools

- .github/workflows/release.yml
Seems like a `-i` is now necessary for the command. Note that we recently startede using mac-mx machines.
> [release] update `base64` command

- filament/backend/include/backend/Handle.h
- filament/backend/include/private/backend/HandleAllocator.h
- filament/backend/src/HandleAllocator.cpp
- libs/utils/include/utils/Allocator.h
- each handle now has a 4-bits "age", meaning that handles are recycled only after 16 alloc/free cycles. This is used to detect double-free and use-after free. This should also allow us to compare handles, because freeing and reallocating an object, won't produce the same Handle (at least for 16 rounds).
- removed "type safety" checks because it's almost impossible to get it wrong thanks to our compile time type safety checks. This didn't provide a useful value added.
- This feature is built on top of being able to set/get a 8 bits tag associated with the memory block returned by the pool allocator. We use the "extra" parameter of the allocator to allocate a "hidden" structure containing the age of that memory block.
- Also we don't allow to compare Handle<> of different types
> Better handle collisions and use-after-free detection

- filament/include/filament/View.h
- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- filament/src/ShadowMapManager.h
- filament/src/View.cpp
- filament/src/details/DebugRegistry.cpp
- filament/src/details/DebugRegistry.h
- filament/src/details/View.cpp
- filament/src/details/View.h
- libs/filamentapp/src/FilamentApp.cpp
- libs/math/include/math/mat3.h
This reduces resource utilisation for Views that never need shadows. It saves a UBO, two Entities and about 10KB memory. We also lazily allocate the debugging DataSource, which saves about 10K per View in debug builds.
Overall this change makes "simple" Views less than 4KB heavy down from about 24KB (debug, 14KB release).
The main changes:
- ShadowMapManager is now allocated lazily
- the ShadowMap cache object is also allocated lazily
- debug DataSource is allocated lazily
- ShadowMaps are prepared/initialized with a Builder, which makes it clearer that some APIs are only for preparing the ShadowMap cache.
> lazy initialization of the ShadowMap cache in ShadowMapManager

- filament/src/ResourceAllocator.cpp
the cache size is given in MiB not bytes, so we needed to convert it to bytes.
> fix a typo that broke the resourceallocator cache

- android/filament-android/src/main/cpp/Engine.cpp
- android/filament-android/src/main/java/com/google/android/filament/Engine.java
- filament/backend/include/backend/DriverEnums.h
- filament/include/filament/Engine.h
This new type value will determine the algorithm used when stereoscopic rendering is enabled.
> Add stereoscopic type to Engine::Config

- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/DriverBase.h
- filament/backend/src/metal/MetalDriver.h
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/test/BackendTest.cpp
- filament/backend/test/TrianglePrimitive.cpp
- filament/backend/test/test_Blit.cpp
- filament/backend/test/test_BufferUpdates.cpp
- filament/backend/test/test_FeedbackLoops.cpp
- filament/backend/test/test_MRT.cpp
- filament/backend/test/test_MipLevels.cpp
- filament/backend/test/test_MissingRequiredAttributes.cpp
- filament/backend/test/test_ReadPixels.cpp
- filament/backend/test/test_RenderExternalImage.cpp
- filament/backend/test/test_Scissor.cpp
- filament/backend/test/test_StencilBuffer.cpp
- filament/include/filament/RenderableManager.h
- filament/src/HwRenderPrimitiveFactory.cpp
- filament/src/HwRenderPrimitiveFactory.h
- filament/src/PostProcessManager.cpp
- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
- filament/src/RenderPrimitive.cpp
- filament/src/RenderPrimitive.h
- filament/src/components/RenderableManager.cpp
- filament/src/details/Engine.cpp
HwRenderPrimitive doesn't need to know about the index offset and index count, these parameters are only needed when drawing. draw() is updated consequently.
This is a first step towards being able to lower the overhead of draw similar draw calls. 
A side effect of this is that the HwRenderPrimitiveFactory now will cache buffers regardless of their index count & offset.
> Modernize HwRenderPrimitive and draw() APIs

- filament/backend/src/vulkan/VulkanConstants.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/platform/VulkanPlatform.cpp
- Also removed debugUtils workaround for Mesa since it's been addressed properly from the vk backend.
> vk: add debug names to shader modules

- filament/CMakeLists.txt
- filament/backend/include/backend/Handle.h
- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/include/private/backend/HandleAllocator.h
- filament/backend/src/DriverBase.h
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/VulkanResources.cpp
- filament/backend/src/vulkan/VulkanResources.h
- filament/backend/test/TrianglePrimitive.cpp
- filament/backend/test/TrianglePrimitive.h
- filament/src/Bimap.h
- filament/src/HwRenderPrimitiveFactory.cpp
- filament/src/HwRenderPrimitiveFactory.h
- filament/src/HwVertexBufferInfoFactory.cpp
- filament/src/HwVertexBufferInfoFactory.h
- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
- filament/src/RenderPrimitive.h
- filament/src/details/Engine.h
- filament/src/details/VertexBuffer.cpp
- filament/src/details/VertexBuffer.h
- libs/utils/include/utils/Allocator.h
[better to review the CLs separately]
HwVertexBufferInfo is a new backend object that holds the data necessary to create the Vulkan pipeline. Effectively we split HwVertexBuffer in two.
This PR doesn't actually change any functionality, it just splits HwVertexBufferInfo out of HwVertexBuffer and paves the way to actually making use of it.
> A set of CLs to introduce HwVertexBufferInfo

- filament/src/RenderPass.cpp
- filament/src/details/Scene.cpp
The OOB would happen is the scene never had any renderables, in that case the scene's SoA would stay unallocated, but the summedAreaTable code relies on it have at least a capacity of 1.
It was incorrect to skip the RenderPass entirely because it might have had some custom commands that needed to be executed (e.g. for applying post-processing in subpass mode).
> Better fix for OOB when we have no renderable

- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalShaderCompiler.h
- filament/backend/src/metal/MetalShaderCompiler.mm
Throw an NSException when a program fails to compile and then is used for drawing; this helps aid debugging compiler errors in production, where stdout logs are not available.
b/325321035
> Metal: throw an NSException when attempting to draw with invalid program

- filament/backend/include/backend/PipelineState.h
- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/test/test_MipLevels.cpp
- filament/backend/test/test_Scissor.cpp
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
We do this to better match Gl, Vulkan and Metal, which don't need to specify the scissor in the pipeline. In practice, this will also allow us to set the scissor less often, saving a bit of CPU.
> remove scissor from PipelineState

- NEW_RELEASE_NOTES.md
- android/filament-android/src/main/cpp/ToneMapper.cpp
- android/filament-android/src/main/java/com/google/android/filament/ToneMapper.java
- filament/include/filament/ToneMapper.h
- filament/src/ToneMapper.cpp
- libs/viewer/include/viewer/Settings.h
- libs/viewer/src/Settings.cpp
- libs/viewer/src/ViewerGui.cpp
This tone mapper was designed to preserve the color appearance of materials. It provides good saturation and contrast while controlling the highlights. This new tone mapper solves (most of) the color skews found in ACES and provides a good path to white similar to AgX but with better preservation of contrast and saturation. 
PBR Neutral is a good choice to showcase products or any type of scene where the appearance of the colors is important (it was designed for commerce applications).
This test compares lit and unlit materials, and the colors should match as closely as possible.
*ACES*
*AgX*
*PBR Neutral*
*ACES*
*AgX*
*PBR Neutral*
*ACES*
*AgX*
*PBR Neutral*
> Add new PBR Neutral tone mapper

- filament/backend/src/DriverBase.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/src/RenderPass.cpp
- filament/src/details/VertexBuffer.cpp
- filament/src/details/VertexBuffer.h
- added many precondition checks and asserts to VertexBuffer creation
- simplified code in VertexBuffer as well
- enforce BONE_INDICES to integer when specified by user since that's what shaders expect.
- better comments about *always* setting BONE_INDICES to integer
- some code simplification in RenderPass + some comments about skinning
- in the GL backend we no longer set the vertex buffer objects at renderprimitive creation time, because they might not be available yet. Instead, we let the natural age mechanism update them next time it's needed.  This allows us to add some asserts about the declared buffer being present
> cleanup of attributes management

- filament/backend/src/opengl/ShaderCompilerService.cpp
When shader compilation happens in threadpool mode, shader source code isn't stored correctly in the token. This leads to empty error messages if a shader has problems later on.
> Fix shader compilation in threadpool mode

- NEW_RELEASE_NOTES.md
- android/filament-android/src/main/java/com/google/android/filament/Renderer.java
From https://github.com/google/filament/issues/7539
And I got to the same conclusion based on https://github.com/google/filament/blob/f0f7e299d2ce1a5f3f62821b058353fe00c2015f/filament/src/details/View.cpp#L191
> Fix Renderer FrameRateOptions interval default

- filament/CMakeLists.txt
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- filament/src/materials/blitArray.mat
This shader takes an array texture and a layer index to draw to the current render target.
This will be used for debugging purpose to combine an array texture rendered from the multiview feature that is going to be implemented later, so that we can verify the feature properly performed.
> Add blit array shader

- filament/src/RenderPass.cpp
- filament/src/details/Renderer.cpp
- filament/src/details/View.h
- libs/filabridge/include/private/filament/Variant.h
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/shaders/CodeGenerator.cpp
- libs/filamat/src/shaders/ShaderGenerator.cpp
- libs/filamat/src/shaders/ShaderGenerator.h
- shaders/src/common_getters.glsl
- shaders/src/main.vs
- shaders/src/varyings.glsl
We're going to add a new implementation of stereoscopic rendering using multiview. Thus we want to remove the word `Instanced` from all methods and properties.
> Rename InstancedStereo as Stereo

- filament/backend/src/opengl/platforms/PlatformEGLAndroid.cpp
This is a partial rollback from
d83b3858b3dbc97b2a5e039ae9fb5d170dd95907.
Keep supporting API level 19 for some of our clients.
> Keep supporting API level 19

- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/shaders/CodeGenerator.cpp
- libs/filamat/src/shaders/MaterialInfo.h
- shaders/src/common_getters.glsl
- shaders/src/main.vs
- shaders/src/varyings.glsl
- tools/matc/src/matc/ParametersProcessor.cpp
This new parameter allows us to specify which implementation of stereoscopic rendering Filament uses for the material.
This change just includes material parameter addition and shader code changes, so it doesn't affect the current rendering behavior.
These changes will follow as separate commits.
- render pipeline changes
- material parameter override via matc parameter
- material document update
> Add a new material param, stereoscopicType

- filament/backend/src/opengl/gl_headers.cpp
- filament/backend/src/opengl/gl_headers.h
This OpenGL function is going to be used for multiview on Android. Make it available.
> Make glFramebufferTextureMultiviewOVR available for Android

- filament/src/fg/FrameGraph.cpp
- filament/src/fg/FrameGraph.h
- filament/src/fg/FrameGraphTexture.cpp
- filament/src/fg/FrameGraphTexture.h
- filament/src/fg/details/Resource.h
In protected mode, the FrameGraph will automatically add the PROTECTED usage bit to texture resources.
> Add protected mode to the FrameGraph.

- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/opengl/OpenGLTimerQuery.cpp
- filament/backend/src/opengl/OpenGLTimerQuery.h
- better naming
- TimerQueryFactory doesn't depend  on OpenGLDriver anymore, only a OpenGLContext.
- timer query factory is now owned by and accessed through OpenGLDriver
- we can't temporarily store a negative number in the query shared state, because it now indicates an error.
> more cleanup-up of timer queries

- filament/backend/CMakeLists.txt
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.h
- filament/backend/src/vulkan/VulkanResources.cpp
- filament/backend/src/vulkan/VulkanResources.h
- filament/backend/src/vulkan/VulkanUtility.h
- filament/backend/src/vulkan/caching/VulkanDescriptorSet.cpp
- filament/backend/src/vulkan/caching/VulkanDescriptorSet.h
- Add cache for ds layouts and ds
- Abstract descriptors API into VulkanDescriptorSetManager
- Note that this is just a draft and not hooked into the current implementation.
> vk: Initial draft for descriptor set refactoring

- filament/backend/src/vulkan/VulkanConstants.h
- filament/backend/src/vulkan/VulkanContext.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanFboCache.cpp
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.h
This reverts commit a9793b3cf619394dc738e3483222a7cff6b81dcf.
Due to change in output for swiftshader
> Revert "vk: remove subpasses to simplify descriptor set refactor

- NEW_RELEASE_NOTES.md
- filament/backend/src/vulkan/VulkanSwapChain.cpp
- filament/backend/src/vulkan/VulkanSwapChain.h
The validation error triggers even on **hellotriangle** using AMD (desktop), QCOM (mobile) and Mali (mobile) GPUs.
Prior to this PR, only a single semaphore object was used to synchronize all the calls to **vkAcquireNextImage** (signal) and **vkQueueSubmit** (wait).
The issue is that by the time **vkQueueSubmit** returns, the semaphore is not necessarily reset.
When multiple frames are in flight, calls to **vkAcquireNextImage** might try to reuse the semaphore while it is still in the **wait** status, because the semaphore is reset at a driver/hardware-dependent timing that's likely linked to the GPU queue execution.
The solution proposed by this PR is to use a pool of semaphores big enough to cover all queue submissions even if they were run concurrently.
> Fixed validation error VUID-vkAcquireNextImageKHR-semaphore-01779

- android/filament-android/src/main/java/com/google/android/filament/Engine.java
- filament/include/filament/Engine.h
- filament/src/ResourceAllocator.cpp
- filament/src/ResourceAllocator.h
Previously the cache would try to keep its size below a user-settable value. This was not effective because when that value was too small, it would cause a lot of churn every frame without actually keeping the memory usage below the specified value.
We now evict buffer aggressively after they've not been used (for two frames by default), but we don't cap the size of the cache. The cache will naturally settle at the size it needs. When dynamic resolution is used, it might be needed to increase resources  maximum age, which is a user-settable value still.
This improves performance on mobile on many scenes because the 64MB default value was too low, causing the crash to thrash.
> simplify the ResourceAllocator cache eviction strategy

- tools/matc/src/matc/CommandlineConfig.cpp
- tools/matc/src/matc/Config.h
- tools/matc/src/matc/MaterialCompiler.cpp
- tools/matc/src/matc/MaterialCompiler.h
- tools/matc/src/matc/ParametersProcessor.cpp
- tools/matc/src/matc/ParametersProcessor.h
This new matc parameter `-P` or `--material-parameter` allows users to set material properties to the specified value.
Values passed through this matc parameters have the highest priorities. I.e., they overwrite material properties specified in the material file.
> Add new parameter -P for matc

- NEW_RELEASE_NOTES.md
- filament/backend/include/backend/platforms/OpenGLPlatform.h
- filament/backend/include/backend/platforms/PlatformEGL.h
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLPlatform.cpp
- filament/backend/src/opengl/platforms/PlatformEGL.cpp
- filament/src/details/Renderer.cpp
Protected contexts are now supported by the OpenGLPlatform interface and implemented in EGLPlatform.
Protected contexts can read from regular and protected resources but can only write to protected resources (e.g. protected swap chains or textures backed by protected memory. These can be created on Android via AHardwareBuffer and EGLImage for instance).
The underlaying EGL implementation must support protected contexts.
Switching to a protected context is achieved by using a protected-content SwapChain in Renderer::beginFrame(). A protected-content SwapChain can be created using the new CONFIG_PROTECTED_CONTENT flag at creation time.
The OpenGL backend implementation will then use a protected context for rendering until an unprotected SwapChain is used again.
The crux of this …
> Add support for protected contexts

- libs/iblprefilter/include/filament-iblprefilter/IBLPrefilterContext.h
- libs/iblprefilter/src/IBLPrefilterContext.cpp
- libs/iblprefilter/src/materials/equirectToCube.mat
- libs/iblprefilter/src/materials/iblprefilter.mat
cmgen mirrors environment maps by default so that the reflection map appears un-mirrored. IBLPrefilter didn't do that. 
EquirectangularToCubemap now takes a Config parameter that allows to specify the mirroring, which is enabled by default.
FIXES=[320856413]
> IBLs were mirrored when using IBLPrefilter

- filament/backend/src/opengl/platforms/PlatformEGLAndroid.cpp
We set the attribute based on the usage bits of the underlaying  AHardwareBuffer.
> Set the protected attribute on EGLImage

- filament/backend/src/vulkan/VulkanCommands.cpp
- filament/backend/src/vulkan/VulkanConstants.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanResourceAllocator.h
- filament/backend/src/vulkan/VulkanResources.cpp
- filament/backend/src/vulkan/VulkanResources.h
- filament/backend/src/vulkan/VulkanTexture.cpp
- Fix broken resource leak print out.
- Add sampler name to debugUtils when enabled
> vk: clean up debug tools

- filament/backend/src/metal/MetalShaderCompiler.mm
Metal appears to serialize all shader compilation requests anyway, so we only need a single background thread.
> Metal: change shader compilation pool size to 1

- filament/backend/include/backend/DriverEnums.h
- filament/backend/include/backend/PipelineState.h
- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/include/private/backend/HandleAllocator.h
- filament/backend/src/metal/MetalContext.h
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/VulkanPipelineCache.h
- filament/src/PostProcessManager.cpp
- filament/src/RenderPass.cpp
- filament/src/RenderPrimitive.cpp
- filament/src/RenderPrimitive.h
- filament/src/details/VertexBuffer.h
PipelineState now holds a handle to a HwVertexBufferInfo. 
DriverAPI::draw() is now technically deprecated and replaced by the
more efficient draw2(), which only takes an index offset, index count 
and instance count. The Pipeline to use is now specified with a new
API bindPipeline() and the primitive to use with bindRenderPrimitive().
This allows clients to reuse RenderPrimitives and ultimately Pipelines.
This change reduces CPU usage significantly on Metal and Vulkan, by 
reducing the need to lookup for a pipeline at every draw call.
The application, however, must be a "good citizen" by reusing 
MaterialInstance and RenderPrimitive as much as possible. We do have
RenderPrimitive cache however, so reusing the same VertexBuffer and
associated parameters also works.
> Modernize draw API

- filament/CMakeLists.txt
- filament/src/details/Engine.cpp
- filament/src/details/Skybox.cpp
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/MaterialBuilder.cpp
- libs/gltfio/src/JitShaderProvider.cpp
Add prebuilt materials for the engine default materials. They'll be selected for multiview stereoscopic implementation.
> Add multiview filamat for default materials

- android/gltfio-android/CMakeLists.txt
- libs/gltfio/CMakeLists.txt
- libs/gltfio/include/gltfio/ResourceLoader.h
- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/FFilamentAsset.h
- libs/gltfio/src/ResourceLoader.cpp
- libs/gltfio/src/Utility.cpp
- libs/gltfio/src/Utility.h
- Pull certain utility functions in a separate header and cpp
- Refactor ResourceLoader::loadeResources into smaller methods
> gltfio: refactor for clarity

- CMakeLists.txt
- libs/filamentapp/CMakeLists.txt
- libs/filamentapp/src/FilamentApp.cpp
- libs/gltfio/CMakeLists.txt
- samples/CMakeLists.txt
This option can be either "instanced" or "multiview", indicating what stereoscopic rendering type shaders in samples/gltfio should be built for.
> Add option FILAMENT_SAMPLES_STEREO_TYPE for samples/gltfio

- libs/gltfio/src/Animator.cpp
A while ago an API was added that supports creating multiple instances from one asset.
Due to that that instance used in an Animator might not be `asset->mRoot`, but another instance. To account for that.
The `applyAnimation` function handled this correctly, however the `applyCrossFade` wasn't updated and was still using  `asset->mRoot`.
This PR adds a conditional to either use the provided instance in `applyCrossFade` or to use the asset's root entity.
> fix: apply applyCrossFade to correct entity

- filament/backend/include/backend/platforms/OpenGLPlatform.h
- filament/backend/include/backend/platforms/PlatformCocoaGL.h
- filament/backend/include/backend/platforms/PlatformCocoaTouchGL.h
- filament/backend/include/backend/platforms/PlatformEGL.h
- filament/backend/include/backend/platforms/PlatformGLX.h
- filament/backend/include/backend/platforms/PlatformWGL.h
- filament/backend/include/backend/platforms/PlatformWebGL.h
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/opengl/OpenGLPlatform.cpp
- filament/backend/src/opengl/platforms/PlatformCocoaGL.mm
- filament/backend/src/opengl/platforms/PlatformCocoaTouchGL.mm
- filament/backend/src/opengl/platforms/PlatformEGL.cpp
- filament/backend/src/opengl/platforms/PlatformEGLAndroid.cpp
- filament/backend/src/opengl/platforms/PlatformGLX.cpp
- filament/backend/src/opengl/platforms/PlatformWGL.cpp
- filament/backend/src/opengl/platforms/PlatformWebGL.cpp
- filament/src/details/Renderer.cpp
- assert when swapchain creation fails
- handle non-0 default FBO with protected contexts
- More Platform improvements for protected contexts
- `isSwapChainProtected()` is now virtual
- `createDefaultSwapChain()` is renamed to `getDefaultSwapChain()`
- new `getCurrentContextType()` returns the current context type
- `makeCurrent` now takes an additional `ContextType`
- `PlatformEGL::getContextForType()` to retrieve the `EGLContext` for
a given type.
- `PlatformEGL::makeCurrent` non-virtual utilities to set only the
context or swapchains.
> More Platform improvements for protected contexts 

- filament/backend/src/vulkan/VulkanBlitter.cpp
- filament/backend/src/vulkan/VulkanBlitter.h
- filament/backend/src/vulkan/VulkanCommands.cpp
- filament/backend/src/vulkan/VulkanCommands.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/src/vulkan/VulkanFboCache.cpp
- filament/backend/src/vulkan/VulkanFboCache.h
- filament/backend/src/vulkan/VulkanSamplerCache.cpp
- filament/backend/src/vulkan/VulkanSamplerCache.h
- filament/backend/src/vulkan/VulkanStagePool.cpp
- filament/backend/src/vulkan/VulkanStagePool.h
Instead of holding pointers to class instances in VulkanDriver, we standardize by making the relevant classes have proper constructors and initialize in VulkanDriver's constructor initializer list.
> vk: clean-up initialization of classes

- filament/backend/include/backend/TargetBufferInfo.h
- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/opengl/gl_headers.cpp
- filament/backend/src/opengl/gl_headers.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/test/test_Blit.cpp
- filament/backend/test/test_BufferUpdates.cpp
- filament/backend/test/test_FeedbackLoops.cpp
- filament/backend/test/test_MRT.cpp
- filament/backend/test/test_MipLevels.cpp
- filament/backend/test/test_ReadPixels.cpp
- filament/backend/test/test_Scissor.cpp
- filament/backend/test/test_StencilBuffer.cpp
- filament/src/RendererUtils.cpp
- filament/src/ResourceAllocator.cpp
- filament/src/ResourceAllocator.h
- filament/src/details/RenderTarget.cpp
- filament/src/fg/FrameGraphRenderPass.h
- filament/src/fg/PassNode.cpp
- filament/test/filament_framegraph_test.cpp
This new parameter indicates whether the render target will be created for multiview.
If the value is greater than 1, it tells the render target should be created for multiview. Otherwise, 1 or 0, it creates a single layer render target.
> Add layerCount to createRenderTarget

- android/gltfio-android/CMakeLists.txt
- libs/gltfio/CMakeLists.txt
- libs/gltfio/src/extended/AssetLoaderExtended.h
- libs/gltfio/src/extended/TangentSpaceMeshWrapper.cpp
- libs/gltfio/src/extended/TangentSpaceMeshWrapper.h
- libs/gltfio/src/extended/TangentsJobExtended.cpp
- libs/gltfio/src/extended/TangentsJobExtended.h
- TangentsJobExtended extracts data from cgltf accessor and runs geometry::TangentSpaceMesh on the attributes and computes the tangent space.
- The /extended folder is meant for running this process. Note that this API might remesh the input and will require corresponding changes that might break previous assumptions.
- The general flow of the code is modeled after src/TangentsJob.h
- This is not hooked into current code and should have no practical effect on gltfio.
> gltfio: add extended tangents job

- filament/src/HwRenderPrimitiveFactory.cpp
- filament/src/HwRenderPrimitiveFactory.h
- filament/src/HwVertexBufferInfoFactory.cpp
- filament/src/HwVertexBufferInfoFactory.h
- both files use consistent names
- enforce that the keys are not moved around
- don't pass the value (which is 4 bytes) by reference
> minor fixes and cleanup to Primitive and BufferInfo factories

- filament/src/ToneMapper.cpp
Based on model-viewer's change at https://github.com/google/model-viewer/pull/4716
The change has barely any visible impact, but it allows the resulting equation to be
more trivially invertible (which we will likely want at some point).
> Make PBR Neutral invertible

- android/filament-android/src/main/cpp/RenderableManager.cpp
- android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
- filament/include/filament/RenderableManager.h
- filament/src/RenderableManager.cpp
- filament/src/components/RenderableManager.cpp
- filament/src/components/RenderableManager.h
- web/filament-js/jsbindings.cpp
- dynamic (default) no restriction apply
- static bounds: bounds and world transform can't be changed
- static: additionaly morphing/skinning and vertex/index buffers are
immutable.
This will allow some optimizations in the future. Currently, we just
store the type but don't do anything with it.
> The type of geometry of a renderable can now be specified

- filament/backend/src/vulkan/VulkanFboCache.cpp
This is due to color attachments being set to store=discard when they are multi-sampled. It's unclear why that condition exists. For now, removing it will fix the rendering issues with transparent object + MSAA. We'll keep it as such until an issue surfaces.
Fixes #7674
> vk: fix broken gltf renderings

- ios/samples/gltf-viewer/gltf-viewer/FILModelView.mm
- libs/gltfio/include/gltfio/ResourceLoader.h
> iOS: fix gltf-viewer crash while destructing ResourceLoader

- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/src/details/Texture.cpp
We verify that the buffer given to setImage() is at least as large as needed for the given region to transfer; at least based on the size given.
This might help catch b/330407429.
> attempt to detect buffer overflows in Texture::setImage()

- filament/backend/include/backend/platforms/OpenGLPlatform.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/platforms/PlatformEGL.cpp
in case the swapchain creation fails, it will now return a swapchain with an EGL_NO_SURFACE handle. this will avoid having to nullptr check the pointer in various places and will revert to the previous behavior on failure.
FIXES=[329659681]
> PlatformEGL::createSwapChain never returns a nullptr anymore

- NEW_RELEASE_NOTES.md
- android/filament-android/src/main/cpp/Engine.cpp
- android/filament-android/src/main/java/com/google/android/filament/Engine.java
- filament/backend/include/private/backend/CommandBufferQueue.h
- filament/backend/src/CommandBufferQueue.cpp
- filament/backend/test/BackendTest.cpp
- filament/backend/test/ComputeTest.cpp
- filament/include/filament/Engine.h
- filament/src/Engine.cpp
- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
This PR adds a new `pause()` option to the `Engine` `Builder` and a new function `setPaused()` to the `Engine`. While paused, the rendering thread will pause indefinitely for commands as if none are available. As soon as the rendering thread is unpaused, the commands are immediately executed.
> Allow rendering thread to pause

- filament/backend/src/opengl/ShaderCompilerService.cpp
- filament/backend/src/opengl/ShaderCompilerService.h
- libs/filabridge/include/private/filament/EngineEnums.h
For OpenGL multiview, it honors the qualifier `layout(num_views = X)` specified in shader files to determine the number of views for multiview.
We cannot recompile materials everytime the value changes. So replace the value of num_views with the engine's eye count when shaders compile.
> Replace value of num_views with engine's eye count

- build.sh
`./build.sh -p android -k sample-gltf-viewer -i debug`
Take `sample-gltf-viewer` as an example, above cmd will result in :
`cp: samples/sample-gltf-viewer/build/outputs/apk/debug/sample-gltf-viewer-debug-unsigned.apk: No such file or directory`
The root cause is that the `android` will signed the `debug` apk with `~/.android/debug.keystore`, which is the default generated by android gradle plugin globally.
[Cause] the unsigned apk will not installed on the android, the apk must be signed anyway. So I think remove the `unsigned` keyword don't make sense, at lease let people know, it's an unsigned apk.
> fix install android debug samples apk error.

- CMakeLists.txt
- filament/CMakeLists.txt
- filament/src/details/Engine.cpp
- filament/src/details/Skybox.cpp
This allows the engine to include multiview shader code for default materials.
> Add FILAMENT_ENABLE_MULTIVIEW option

- filament/backend/include/backend/Program.h
- filament/backend/src/Program.cpp
- filament/backend/src/opengl/ShaderCompilerService.cpp
- filament/backend/src/opengl/ShaderCompilerService.h
- filament/src/details/Material.cpp
Replace the num_views for OpenGL multiviwe only when
- The engine is initialized with multiview stereo
- The variant for the material contains STE flag
- The program is for surface
- It's vertex shader (this is already in)
> Improve multiview shader replacement

- web/filament-js/jsbindings.cpp
Newer Emscripten toolchains require us to wrap raw pointers in `allow_raw_pointer`.
> Fix WebGL build with newer Emscripten

- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/src/PostProcessManager.cpp
- filament/src/RendererUtils.cpp
There was several cases where the the gl backend would wrongly  use a  renderbuffer instead of a texture.
BUGS=[329491941]
> GL backend should only allocate renderbuffers when possible

- filament/backend/include/private/backend/CommandStream.h
- filament/backend/include/private/backend/Driver.h
- filament/backend/include/private/backend/HandleAllocator.h
- filament/backend/src/CommandStream.cpp
- filament/backend/src/Driver.cpp
- filament/backend/src/HandleAllocator.cpp
- filament/backend/src/opengl/OpenGLDriver.h
going forward we want to be able to throw exceptions from the backend at the very least, we need to be consistant, currently we are potentially throwing exceptions from `noexcept` places.
this changes makes it possible to throw exceptions from the backend, during handle construction and conversion to pointers, which wasn't  allowed before.
We still can't throw from dtors because it's generally a bad idea,  better abort in that case.
> remove wrong `noexcept` in the backend

- filament/src/ShadowMapManager.cpp
- filament/src/ShadowMapManager.h
We were calculating the shadow visibility of spot/point lights. The visibility was calculated during the "execute" phase of the FrameGraph but it was used/needed during the setup phase. The result was that the visibility was always delayed by one frame (really it was stale  data from the previous calculation).
We are now computing the shadow visibility earlier, during the setup phase. This is also better because we can now skip culling of these shadow maps entirely if we know they're not visible.
Fixes #7715
> Fix point/spot shadow rendering bug

- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.h
- filament/backend/src/vulkan/VulkanResources.cpp
- filament/backend/src/vulkan/VulkanResources.h
- filament/backend/src/vulkan/VulkanUtility.cpp
- filament/backend/src/vulkan/VulkanUtility.h
- filament/backend/src/vulkan/caching/VulkanDescriptorSet.cpp
- filament/backend/src/vulkan/caching/VulkanDescriptorSet.h
- filament/backend/src/vulkan/spirv/VulkanSpirvUtils.cpp
- filament/backend/src/vulkan/spirv/VulkanSpirvUtils.h
- Move VulkanDescriptorSet to VulkanHandles.h
- Add VulkanDescriptorSetLayout to VulkanHandles.h
- Add "input" descriptor set types to VulkanUtility.h. These are structs that will be defined in the backend API (shared across all backends) and eventually passed from the front-end to the vk backend.
- Logic to parse descriptor set layout from the spirv-v shaders.
- Move UsageFlags type to VulkanUtility.h
- Just prep work. No effect to current implementations.
> vk: add descriptor set/layout types to handles

- libs/utils/include/utils/debug.h
We use this in other utils public include files, so I think it should be exported.
> Export utils::panic function

- filament/backend/src/metal/MetalDriver.mm
This was originally done in #7581, but was reverted due to a refactor.
> Metal re-apply: throw an NSException when attempting to draw with inalid program

- filament/backend/src/vulkan/VulkanCommands.cpp
- filament/backend/src/vulkan/VulkanCommands.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.h
- filament/backend/src/vulkan/VulkanResourceAllocator.h
- filament/backend/src/vulkan/caching/VulkanDescriptorSetManager.cpp
- filament/backend/src/vulkan/caching/VulkanDescriptorSetManager.h
- filament/backend/src/vulkan/caching/VulkanPipelineLayoutCache.cpp
- filament/backend/src/vulkan/caching/VulkanPipelineLayoutCache.h
- Use new descriptor set and layout caching
- Remove descriptor set related code in VulkanPipelineCache
- Fix leaks in VulkanDescriptorSetManager
FIXES=248594812,325157400
> vk: Use new descriptor set caching 

- filament/backend/include/backend/DriverEnums.h
- filament/src/MaterialParser.cpp
- libs/filabridge/include/filament/MaterialChunkType.h
- libs/filaflat/include/filaflat/MaterialChunk.h
- libs/filaflat/src/DictionaryReader.cpp
- libs/filaflat/src/MaterialChunk.cpp
- libs/filamat/CMakeLists.txt
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/eiff/DictionaryMetalLibraryChunk.cpp
- libs/filamat/src/eiff/DictionaryMetalLibraryChunk.h
- libs/filamat/src/eiff/MaterialBinaryChunk.cpp
- libs/filamat/src/eiff/MaterialBinaryChunk.h
- libs/filamat/src/eiff/ShaderEntry.h
- libs/matdbg/src/ShaderExtractor.cpp
- libs/matdbg/src/ShaderReplacer.cpp
- libs/matdbg/src/TextWriter.cpp
- tools/matinfo/src/main.cpp
This change introduces a new chunk type to material files for precompiled Metal libraries. Previously, SPIR-V was the only binary type, so there's also a couple of refactor commits present here. Nothing is changed in Filament or matc yet.
BUGS=[333547148]
> Introduce a new precompiled Metal material chunk type

- filament/backend/include/backend/DriverEnums.h
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/src/details/Engine.cpp
Originally we did this because we wanted to run on a big core on  android. However setting the thread affinity in this way is fragile, we are not guaranteed to be on a big core, and we don't even know if some thread is pinned to that core already; which was the case with some GL drivers. This can also cause scheduling problems with other threads.
We just remove this logic entirely for now, and we'll figure out  something better later to run on a big core.
Fixes #7748
BUGS=[333949404]
> don't use thread affinity for the backend thread

- libs/iblprefilter/src/materials/iblprefilter.mat
The top and bottom faces were swapped in the reflection map.
FIXES=[333421281]
> fix another ibl-prefilter bug introduced recently

- filament/backend/src/vulkan/platform/VulkanPlatform.cpp
Setting the pEngineName helps with the collection of metrics and is generally good practice.
> Set VkApplicationInfo.pEngineName to Filament

- filament/src/PostProcessManager.cpp
Previous PR #7758 accidentally removed the setting of 'resolution' for shaders other than 'blitLow'.  This PR undoes that.
> Fix broken dynamic resolution

- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
the gl backend did some of its cleanup in the its destructor, including calling into OpenGL, however, the destructor is called from the main thread, not the GL thread, so these calls would be no-ops at best, and crashes in the worst case.
> fix a GL backend crash when shutting down

- filament/src/details/Material.cpp
- filament/src/details/Material.h
- filament/src/details/MaterialInstance.cpp
- filament/src/details/MaterialInstance.h
FMaterialInstance needed a default ctor because it is a field of FMaterial but cannot be initialized before FMaterial itself is initialized. So we had a defautl ctor and we'd finish the initialization later. Conceptually the default material instance should have been  new'ed and a pointer to it stored instead. 
That's basically what we do now, but to avoid the extra allocation, we in-place new and delete the default material instance into an aligned_storage inside FMaterial.
> don't rely on FMaterialInstance having a default ctor

- filament/backend/src/opengl/GLTexture.h
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
In opengl it's possible to bind several textures to the same texture unit as long as they're a different target. Until now we were tracking that state. In practice it's not very useful to bind several textures to the same unit (it is a little bit when updating texture data, but not when rendering). With the coming change to a descriptor set API, it is better to have a 1-to-1 mapping between bound textures and texture units.
So with this change, only a single texture can be bound to a texture  unit. If another texture in bound to the same unit with a different target, we first unbind the texture from the current target.
There is less state to track, and it allows us to  "unbind a texture unit" (whereas before we'd have to iterate through  all the possible targets for that unit and unbind …
> gl: simplify how we track bound textures

- filament/CMakeLists.txt
- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
- filament/src/RendererUtils.cpp
- filament/src/RendererUtils.h
- filament/src/ShadowMapManager.cpp
- filament/src/SharedHandle.h
- filament/src/details/Renderer.cpp
- filament/src/details/Scene.cpp
- filament/src/details/Scene.h
- filament/src/details/View.cpp
- filament/src/details/View.h
The main goal of this change is to avoid having to select the 
"per renderable" UBO at execution time. Instead we want the
PrimitiveInfo structure to already know which UBO will be used.
Concretely, this means that this determination must be done when
the RenderPass is created.
When automatic instancing is used, the RenderPass creates a temporary
UBO to store the instance info. This UBO's life-time is dictated by both
the life-time of the RenderPass and the Executors that where created
from it. For this reason we introduce SharedHandle<> to correctly 
account for the owner's lifetime. This fixes a potential bugs where
that handle could have been destroyed and used later; in practice this
bug didn't happen however.
A couple other changes:
- RenderPass has a bunch of fields that were …
> clean-ups to prepare for descriptor set changes

- filament/backend/src/vulkan/VulkanBuffer.cpp
- filament/backend/src/vulkan/VulkanBuffer.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/src/vulkan/VulkanFboCache.cpp
- filament/backend/src/vulkan/VulkanFboCache.h
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- At the end of a renderpass we use a more fine-grained barrier for each of the attachments in the render target
- Make sure that buffer update are barrier'd from previous reads
- Remove previous Mali workaround barriers.  Seems to be fine without them on pixels + Mali.
> vk: finer-grain barrier at renderpass end

- libs/filamat/src/GLSLPostProcessor.cpp
For generating MSL, turning off `--optimize-size` optimization passes (still keeping the ones necessary for fp16), reduces sizes of lit materials by nearly 400 KiB:
- sandboxLit.mat: 376.6 KiB savings
- gltfio lit_opaque.mat: 395.7 KiB savings
- bakedColor.mat: 1.799 KiB increase
Note there is a slight increase with unlit materials, as seen above with bakedColor.mat.
Removing these optimizations helps the line dictionary compress better. It's likely the Metal compiler itself does a lot of these optimizations.
An added benefit is this makes MSL shaders much easier to debug.
> Remove spirv-opt size optimizations for MSL

- NEW_RELEASE_NOTES.md
- libs/filagui/CMakeLists.txt
- libs/filagui/include/filagui/ImGuiHelper.h
- libs/filagui/src/ImGuiHelper.cpp
- libs/filagui/src/materials/uiBlitExternal.mat
I was unfortunately naive about the way that Filament handled external textures on non-GLES platforms. This fix restricts the changes to Android (which is the only place this change is required in the first place). Long story short, the change broke WebGL. Desktop seems to be unaffected.
> Fix broken ImGui on web

- filament/src/details/Scene.cpp
- filament/src/details/Skybox.cpp
- filament/src/details/Skybox.h
The material parameter changes are committed automatically in Engine::prepare(), no need to do it explicitly for SkyBox.
> Skybox doesn't need a commit() method

- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/src/PostProcessManager.cpp
- make sure we can build with ES2 headers only
- make sure to not use ES3 features when in ES2 mode (post processing was accidentally creating an R8 texture,  which is not supported)
> fix ES2 support

- filament/backend/src/opengl/OpenGLDriver.cpp
While using Filament with ANGLE on Windows (using D3D11 backend of ANGLE) we noticed getting lots of warnings like this:
```
OpenGL framebuffer error 0x8219 (GL_FRAMEBUFFER_UNDEFINED) in "blit" at line 3581
```
We use Filament v1.50.3 and there the problematic driver calls comes from [here](https://github.com/google/filament/blob/v1.50.3/filament/src/PostProcessManager.cpp#L753). Looking at the implementation of `OpenGLDriver::blit()` it seemed to me there was a bug (fix me if I am wrong). It:
- binds an FBO **as DRAW** target then attaches images to it
- checks the completeness of **READ target** FBO (_what if there's no FBO bound as READ target?_)
- binds another FBO **as READ** target then attaches images to it
- checks the completeness of **DRAW target** FBO (_this technically works …
> Fix mixed up FBO targets in status check code in OpenGLDriver::blit()

- shaders/src/getters.vs
gl_ViewID_OVR is of uint type. Explicitly convert it to int to fix the error.
> Fix a shader error

- android/filament-android/src/main/cpp/Engine.cpp
- android/filament-android/src/main/java/com/google/android/filament/Engine.java
- filament/backend/include/backend/Platform.h
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/platforms/PlatformEGL.cpp
- filament/include/filament/Engine.h
- filament/src/details/Engine.cpp
This setting is only meaningful on GLES backends, it's otherwise ignored. When set to true, the backend will try to force a ES2 context if supported. If not supported by the platform,
the backend will pretend it's a ES2 context.
This setting is currently only taken into account by the EGL platform.
> Add an Engine debug setting to force GLES 2.0

- filament/src/details/Material.cpp
the STL's stream headers can bring in a lot of code, we don't use them.
> remove the single <sstream> usage we have

- filament/backend/src/metal/MetalShaderCompiler.mm
If a .metallib was compiled with a target iOS version that's newer than the current device, loading the .metallib as an `id<MTLLibrary>` may succeed, but finding `main0` (or any other function in it) will fail and return nil. Currently, this causes a crash due to an assert; logging the error and returning `MetalFunctionBundle::error()` will still crash, but in a way that's easier to diagnose.
(Note that in practice, this will probably be a useless "Compiler encountered an internal error" message -- the GPU backend is crashing, and the Metal stub library sees as `XPC_ERROR_CONNECTION_INTERRUPTED`. It retries up to 3 times, crashing each time, and then gives up.)
> Improve logging for Metallib function lookup failures

- filament/backend/src/metal/MetalBuffer.h
- filament/backend/src/metal/MetalBuffer.mm
- filament/backend/src/metal/MetalBufferPool.h
- filament/backend/src/metal/MetalBufferPool.mm
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.mm
This PR updates our Metal buffer tracking logic to use a `NSHashTable` to track alive buffers. `NSHashTable` is configured to hold weak references to the buffers we add to it. When a buffer is deallocated, it is automatically removed from the hash table. By counting the number of buffers in the hash table, we get an accurate count of the number of alive buffers.
The previous implementation had the limitation that once we pass a buffer off to Metal (when a command buffer becomes the sole owner of it, for example), we assume Metal will eventually release it and and decrement our count. In reality, that buffer could stay alive for a frame or two while the command buffer executes. Using the hash table should give us a more accurate tally of the alive buffer count.
> Metal: implement more accurate buffer tracking

- filament/backend/include/backend/TargetBufferInfo.h
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/ostream.cpp
- filament/backend/test/test_FeedbackLoops.cpp
- a field was added, which broke the layout of the structure. We fix it by adding constructors which will handle the old and new way of initializing this structure.
- one of the test needed a hash update
- OpenGLContext wrongly asserted when trying to unbind texture 0
> backend tests were broken by a change in TargetBufferInfo

- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
we use a different hook for the draw() call when on an ES2 context, this eliminates completely the overhead of supporting ES2 for the draw call. draw calls are expected to be the most common calls.
> backend: zero-cost ES2 draw()

- filament/backend/CMakeLists.txt
- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/test/test_Callbacks.cpp
- filament/src/details/SwapChain.cpp
There was a bug where the `frameScheduledCallback` and `frameCompletedCallback` needed to be set before every frame, otherwise they would either be called only once or crash in debug builds.
Fixes #7826
> Metal, fix callbacks being called only once

- android/filament-android/src/main/cpp/RenderableManager.cpp
- android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
- filament/include/filament/RenderableManager.h
- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
- filament/src/RenderableManager.cpp
- filament/src/components/RenderableManager.cpp
- filament/src/components/RenderableManager.h
- filament/src/details/MorphTargetBuffer.cpp
- libs/filabridge/include/private/filament/EngineEnums.h
- samples/hellomorphing.cpp
- shaders/src/getters.vs
- we add support of the `offset` parameter when setting a morph target. This is made possible by using the new push-constants feature
- we deprecate the old morphing api that allowed a morph target buffer per primitive. the new API is currently implemented on top of the old one.
> morphing API changes

- filament/src/details/Engine.h
- libs/viewer/src/ViewerGui.cpp
Set combine_multiview_images to false by default as it's the desirable setting for most Android devices.
Set the flag to true for GUI by default.
Put the `Combine Multiview Images` checkbox under the `Stereo mode` box for an easier access.
> Update combine_multiview_images flag

- filament/backend/src/vulkan/spirv/VulkanSpirvUtils.cpp
- filament/src/details/Engine.cpp
- libs/gltfio/src/extended/TangentSpaceMeshWrapper.cpp
- libs/matdbg/src/ApiHandler.h
- libs/viewer/src/Settings_generated.cpp
- tools/matedit/src/main.cpp
When `USE_STATIC_LIBCXX` is off, some cannot be compiled because of implicit headers.
> Add explicit headers for supporting libstdc++

- filament/backend/include/private/backend/HandleAllocator.h
- filament/backend/src/CircularBuffer.cpp
- filament/backend/src/CommandBufferQueue.cpp
- filament/backend/src/HandleAllocator.cpp
- libs/utils/include/utils/Panic.h
- libs/utils/src/Panic.cpp
- libs/utils/src/sstream.cpp
going forward, instead of using the printf style syntax for panics we use the c++ stream syntax
The new macros that replace ASSERT_*CONDITON are
FILAMENT_CHECK_PRECONDITON
FILAMENT_CHECK_POSTCONDITION
FILAMENT_CHECK_ARITIHMETIC
Example usage:
FILAMENT_CHECK_PRECONDITON(condition) << "Message";
The effect is exactly the same as before, but it'll let clients use Abseil's logging facilities.
> A new stream-based Panic API

- filament/backend/src/metal/MetalState.mm
Currently, if `newRenderPipelineStateWithDescriptor` fails, we log the error message to stderr (which doesn't get captured by most iOS crash reporting systems) and then crash in a postcondition assert. By including the error message in an exception reason and throwing an ObjC exception, we get better discoverability of error causes.
(Building a render pipeline state from shaders is usually what triggers jitting a shader from LLVM IR to GPU-specific code, so if we accidentally used a feature that's not available on the local GPU, we'll find out about it here.)
> Throw an exception when failing to build a Metal render pipeline state.

- libs/gltfio/src/AssetLoader.cpp
Invalid gltf but valid json should not crash but
return null for asset.
Fixes #7868
> gltfio: fix invalid gltf crash

- filament/backend/src/vulkan/platform/VulkanPlatform.cpp
> vk: workaround extension name length = 0 (adreno)

- filament/src/details/Material.cpp
Otherwise, we'd keep swapping between the edited version and the original, causing matdbg to not work.
> Null out pending edits once latched

- libs/gltfio/src/extended/AssetLoaderExtended.cpp
> gltfio: [extended] Fix generated color default

- filament/backend/src/vulkan/VulkanBlitter.cpp
- filament/backend/src/vulkan/VulkanCommands.cpp
- filament/backend/src/vulkan/VulkanConstants.h
- filament/backend/src/vulkan/VulkanContext.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanFboCache.cpp
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanReadPixels.cpp
- filament/backend/src/vulkan/VulkanResourceAllocator.h
- filament/backend/src/vulkan/VulkanStagePool.cpp
- filament/backend/src/vulkan/VulkanTexture.cpp
- filament/backend/src/vulkan/platform/VulkanPlatform.cpp
- filament/backend/src/vulkan/platform/VulkanPlatformSwapChainImpl.cpp
In some debug instances, it's nice to have the logs all go to one output stream so that logs are ordered. We add a FVK_DEBUG flag for this use case.
> vk: single output stream debug logging

- filament/backend/include/backend/platforms/VulkanPlatform.h
- filament/backend/src/vulkan/VulkanSwapChain.cpp
- filament/backend/src/vulkan/VulkanSwapChain.h
- filament/backend/src/vulkan/platform/VulkanPlatform.cpp
- filament/backend/src/vulkan/platform/VulkanPlatformSwapChainImpl.cpp
- filament/backend/src/vulkan/platform/VulkanPlatformSwapChainImpl.h
FIXES=[338303279]
Abstracts the synchronization of the vulkan swapchain so that it is easier to override during the acquisition and presentation of images. A new structure (ImageSyncData) is created to hold swapchain synchronization data.
> Updates vulkan swapchain synchronization

- android/filament-android/src/main/cpp/Material.cpp
- android/filament-android/src/main/java/com/google/android/filament/Material.java
- filament/include/filament/IndirectLight.h
- filament/include/filament/Material.h
- filament/src/details/Material.cpp
- libs/filabridge/include/private/filament/EngineEnums.h
- libs/filamat/src/shaders/CodeGenerator.cpp
- shaders/src/light_indirect.fs
The number of SH bands used for the indirect light irradiance computations can be set to 1, 2 or 3 (default) in Material::Builder.
For e.g. in lower-end devices w/ non HDR content, it might be beneficial to set this value to 2.
BUGS=[341971013]
> Lit Materials can now specify the quality of SH computations

- samples/gltf_viewer.cpp
When a user drags and drops a gltf file to the gltf_viewer window, it loads the new asset.
While this happens, the function `checkAsset` tries parsing the gltf file, but it doesn't free it. Fix this.
> Fix memory leak of asset loading for gltf_viewer

- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
If a user is using `setFrameScheduledCallback()`, managing the provided PresentCallable during engine shutdown is tricky -- we'll likely get a final frame scheduled when we flush the engine's work queue, but the PresentCallable will schedule the final CAMetalDrawable to be released on main thread afterwards, even if we call `present(false)` to skip it. If the swap chain is destroyed before that main queue block gets executed, the mutex presenting that drawable will no longer exist, causing a crash.
To make things easier, store the std::mutex in a shared_ptr, so that a PresentCallable can safely outlive the FSwapChain instance that created it and clean itself up afterwards.
Alternatives considered, all of which seem unfortunate:
* Require users to clear out the callback before shutting …
> Fix use-after-free of a std::mutex in PresentCallable.

- filament/backend/include/private/backend/HandleAllocator.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/opengl/OpenGLProgram.cpp
Texture handles were resolved to pointers when updating a SamplerGroup, as that point the handle was checked for use-after-free. However, the texture could be destroyed later while still active in the SamplerGroup, this would result in using the pointer which now contains garbage.
We now keep the handle and resolve the texture when binding samplers to the program; which will also perform the use-after-free check.
> fix use-after-free dereference risk

- filament/backend/include/backend/Platform.h
- filament/backend/src/metal/MetalBuffer.h
- filament/backend/src/metal/MetalBuffer.mm
- filament/backend/src/metal/MetalBufferPool.h
- filament/backend/src/metal/MetalBufferPool.mm
- filament/backend/src/metal/MetalContext.h
- filament/backend/src/metal/MetalDriver.mm
- filament/include/filament/Engine.h
- filament/src/details/Engine.cpp
This switches staging buffer allocation for vertex and index data to a linear bump allocation scheme instead of using a pool of buffers. The idea is that for certain apps, vertex uploads tend to be smaller and more spiky. Batching the uploads into a larger shared buffer reduces the number and frequency of buffers we need to request from Metal.
> Metal: use a bump allocator for vertex and index uploads

- android/filament-utils-android/src/main/cpp/Manipulator.cpp
- android/filament-utils-android/src/main/java/com/google/android/filament/utils/Manipulator.java
- libs/camutils/include/camutils/Manipulator.h
- libs/camutils/src/Manipulator.cpp
- libs/camutils/src/OrbitManipulator.h
It's useful when you want to have the ability to rotate the camera, but want to limit panning.
> Add ability to disable panning in the OrbitManipulator

- NEW_RELEASE_NOTES.md
- libs/filamentapp/include/filamentapp/FilamentApp.h
- libs/filamentapp/src/FilamentApp.cpp
- samples/gltf_viewer.cpp
Users now can drag and drop IBL files for desktop gltf_viewer.
It attempts to load gltf files first then tries to load IBL files.
> IBL drag & drop support for desktop gltf_viewer

- android/filament-android/src/main/cpp/RenderableManager.cpp
- android/filament-android/src/main/java/com/google/android/filament/MorphTargetBuffer.java
- android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
- filament/include/filament/RenderableManager.h
- filament/src/RenderPass.cpp
- filament/src/RenderPrimitive.h
- filament/src/RenderableManager.cpp
- filament/src/components/RenderableManager.cpp
- filament/src/components/RenderableManager.h
- filament/src/details/MorphTargetBuffer.h
- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/FFilamentAsset.h
- libs/gltfio/src/ResourceLoader.cpp
- libs/gltfio/src/TangentsJob.h
- libs/gltfio/src/extended/AssetLoaderExtended.cpp
- libs/gltfio/src/extended/ResourceLoaderExtended.cpp
- libs/gltfio/test/gltfio_test.cpp
- samples/hellomorphing.cpp
- samples/skinningtest.cpp
- remove deprecated morphing APIs
- repair gltfio, samples and tests
The new API doesn't allow a MorphTargetBuffer per RenderPrimitive, instead the MorphTargetBuffer is specified per Renderable.
gltfio separates RenderPrimitives from Renderables, in particular all RenderPrimitives are created before their Renderable; this was problematic for this change because all primitives must share a single MorphTargetBuffer living in the Renderable.
To fix this, we're no longer initializing the morphing paramters at RenderPrimitive creation, instead we store a reference to the BufferSlot in the Primtive structure, so that later, when the Renderable is created we can finally retrieve the BufferSlot and initialize its morphing paramters, which are not available. The "morphing parameters" are now …
> switch to new morphing API

- filament/backend/src/opengl/ShaderCompilerService.cpp
the failure could happen if the shader didn't have any #extension strings, which was likely to happen on release builds (e.g. on  emulator).
> shader compilation could fail on ES 3.0 devices

- filament/backend/src/CircularBuffer.cpp
- in case of failure we were munmap'ing the wrong size for the guard page (in practice this never happened)
- the post-condition check was incorrect; it checked for nullptr instead of MAP_FAILED. this also never happened in practice.
Also made a couple of small improvements:
- in case the special circular buffer mapping fails, log a message as warning instead of debug.
- immediately memset (i.e. populate) the pages for the circular buffer since they will all be accessed rather quickly.
> fix a couple small bugs when mapping the circular buffer

- filament/src/components/RenderableManager.cpp
These 2 preconditions checks are currently incorrect and cause a crash when trying to create static geometry through `RenderableManager`:
https://github.com/google/filament/blob/ef9bbece2af9730af633f002a58680033b0ab410/filament/src/components/RenderableManager.cpp#L446-L450
Since skinning and morphing is not possible, they should ensure that counts are 0, not higher than 0.
> Fix precondition check when creating static geometry.

- filament/src/details/Renderer.cpp
renderStandaloneView must be called outside of beginFrame() / endFrame(). This extra check ensures this behavior.
> Add an extra check for renderStandaloneView

- filament/include/filament/Renderer.h
- filament/src/FrameInfo.cpp
- filament/src/FrameInfo.h
- filament/src/Renderer.cpp
- filament/src/details/Renderer.h
- filament/src/details/View.cpp
- filament/src/details/View.h
- we use a circular buffer for the frame history so that  we don't have to copy the data when insert a new entry. This also allows us to keep a reference to an entry, which doesn't get invalidated when an entry is added/removed.
- we now store the gpu frame time in the correct slot (instead of always the latest). It didn't matter before because the API wasn't public and we only needed some recent frame time.
- a new public API now returns the frame history, which now contains  more data; in particular the main and backend thread's begin/end frame time.
BUGS=[321110544]
> improve frame timing info

- filament/src/Froxelizer.cpp
- filament/src/RenderPass.h
- filament/src/components/LightManager.cpp
- libs/ibl/src/CubemapSH.cpp
- libs/utils/include/utils/JobSystem.h
- libs/utils/src/JobSystem.cpp
- tools/matc/src/matc/MaterialCompiler.cpp
- reduce the number of calls to notify_one() and notify_all(). notify_one() is not only called when running a new job, and notify_all() only when a job finishes.
- don't hold the condition lock while calling notify_*(), as it is not strictly needed, and because notify_*() can be very slow, there can be a lot of contention on this lock as a result; blocking the whole jobsystem thread pool.
- add a new version of run() that takes an opaque thread id that can be retrieved from a job's execute function; this is especially intended to be used by parallel_for(); it's just a more efficient version of run() that avoids a hashmap lookup.
Overall these change yield a significant performance boost:
- running + waiting a job: +200%
- running many jobs: +150%
- running many jobs in parallel: +50%
> performance improvements to JobSystem

- filament/src/RendererUtils.cpp
FIXES=[354756389]
Only sets the layer count of the color pass target to the stereoscopic eye count if view.hasStereo() and the stereoscopic type is multiview. This aligns RenderUtils.cpp with Renderer.cpp, where the color buffer descriptor's depth is set to the stereoscopic eye count only when view.hasStereo() and the stereoscopic type is multiview.
> Only sets the layercount if the view has stereo and the stereoscopic type is multiview

- libs/gltfio/src/AssetLoader.cpp
> gltfio: enable escaped unicode for node name

- android/filament-android/src/main/cpp/Renderer.cpp
- android/filament-android/src/main/cpp/View.cpp
- android/filament-android/src/main/java/com/google/android/filament/Engine.java
- android/filament-android/src/main/java/com/google/android/filament/Renderer.java
- android/filament-android/src/main/java/com/google/android/filament/View.java
- filament/include/filament/Engine.h
- filament/include/filament/Renderer.h
- filament/include/filament/View.h
- filament/src/FrameHistory.h
- filament/src/Renderer.cpp
- filament/src/ResourceAllocator.cpp
- filament/src/ResourceAllocator.h
- filament/src/View.cpp
- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
- filament/src/details/Renderer.cpp
- filament/src/details/Renderer.h
- filament/src/details/View.cpp
- filament/src/details/View.h
- filament/src/fg/FrameGraph.cpp
- filament/test/filament_framegraph_test.cpp
- web/filament-js/jsbindings.cpp
The ResourceAllocator used to be global and owned by the Engine, this was causing some issues when using several Renderers because each one could cause the eviction of cache data for another.
We now have a ResourceAllocator per Renderer, which makes more sense because most resources are allocated by the FrameGraph.
We also introduce a ResourceAllocatorDisposer class, which is used for checking in and out a texture from the cache, and destroy the texture when it's checked-out. That objet is still global.
> Move the ResourceAllocator from Engine to Renderer

- libs/gltfio/src/AssetLoader.cpp
if it can't find a name for a node, it will revert to the config's defaultNodeName, however, if that is nullptr also, a crash will occur. so we provide a last-resort hardcoded name in that case.
> fix a potential crash is AssetLoader

- filament/backend/src/opengl/OpenGLTimerQuery.cpp
- filament/src/FrameInfo.h
- filament/src/details/Renderer.cpp
This fixes a crash introduced by a8ace2891d2d83e8b9dd7d06a01591d3ff53c764
The refactored FrameInfoManager is now required to be called properly within the renderStandaloneView method, which is mainly being called by IBLPrefilterContext.
Also fix a null pointer reference bug for OpenGLTimer::State, which happenes when the renderer for IBLPrefilterContext is destroyed.
> Fix a crash for IBL resource loading

- libs/gltfio/src/extended/AssetLoaderExtended.h
Value of `mCgltfBuffersLoaded` is sometimes retained across creation of FAssetLoader which skips loading the buffer in AssetLoaderExtended#createPrimitive leading to null pointer crash.
I also tried `(*loader)->mLoaderExtended.reset()` in `AssetLoader::destroy` but that doesn't seem to reset the value of `mCgltfBuffersLoaded`
Fixes the issue, https://github.com/google/filament/issues/7997
> Set mCgltfBuffersLoaded in constructor

- libs/utils/include/utils/WorkStealingDequeue.h
this change shouldn't have any impact on ARM, however, according to cppreference it's not safe to mix seq_cst with other memory orders:
"as soon as atomic operations that are not tagged memory_order_seq_cst  enter the picture, the sequential consistency guarantee for the program  is lost"
> don't mix seq_cst with other memory orders

- NEW_RELEASE_NOTES.md
- filament/backend/src/opengl/OpenGLDriver.cpp
This function attempts to set texture parameters in these two cases, but the texture is not guaranteed to be bound. Perhaps it once was, but the assumption broke at some point.
> Fix ES2/anisotropy bug in updateSamplerGroup

- filament/src/Engine.cpp
- filament/src/Renderer.cpp
This commit 730bc99025a6846dc41764f7f5c7f79f0a192350 introduced a new dependency on ResourceAllocator because of the new field `std::unique_ptr<ResourceAllocator> mResourceAllocator{};` in details/Renderer.h
This requires cpp files including details/Renderer.h to include ResourceAllocator.h as well.
This compile issue only happens on the Windows compiler, Visual Studio.
> Fix ResourceAllocator compile error on Windows

- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
we now have two levels of debug markers. Those that come from the "user" (i.e. filament itself) are now always enabled and generate both  systrace and gl markers. the 2nd level is internal and always disabled by default. Of enabled at compile time it'll emit markers for each driver API method.
> improve GL backend debug markers

- filament/src/FrameInfo.cpp
- filament/src/FrameInfo.h
This reduces the latency of the timer query result; with the previous code the latency could only increase, but there is no reason to wait a whole frame for reading the next available result.
We just loop over them until we find one that has not signaled; instead of doing one per frame.
> read all valid pending timer queries each frame

- NEW_RELEASE_NOTES.md
- filament/src/MaterialParser.cpp
- filament/src/MaterialParser.h
- filament/src/details/Material.cpp
- libs/filabridge/include/filament/MaterialChunkType.h
- libs/filabridge/include/filament/MaterialEnums.h
- libs/filagui/CMakeLists.txt
- libs/filamat/src/MaterialBuilder.cpp
Print a warning in case the stereoscopic type in a compiled package is different than what's in the engine's setting. The application may proceed, but it could end up visual glitches when enabling stereoscopic rendering.
This requires the stereoscopic type to be written into the package, which needs a material version bump.
> Add warning for the incompatibility of stereo type

- filament/src/details/DebugRegistry.cpp
- filament/src/details/DebugRegistry.h
- filament/src/details/View.cpp
- filament/src/details/View.h
- the last View created was always overriding previous View's datasource
- because of lazy registering of the data source it was possible that the registering lambda was called after the view was destroyed, leading to crashes
- all view would share the same PID parameters and these would be initialized to default value instead of the user provided value. so debug build would behave differently.
With this change we improve things:
- now only the first view gets to publish its data source. it's still not ideal, but works for our use case with gltf_Viewer
- the view can now unregister itself when it's destroyed
- only the view that successfully registered uses the debug PID values and publishes its data source.
- the normal parameters are used until we query the datasource (from imgui), so …
> fix several issue with the debug datasource in View

- filament/src/RenderPass.cpp
The push constant call should not be tied to the caching of the pipeline.
> Move morphing buffer offset out of pipeline check

- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanTexture.cpp
- filament/backend/src/vulkan/VulkanTexture.h
We relied on layout transition to emit a barrier, but sometimes
it's skipped. In that case, we explicitly emit a barrier for the
transition from attachment -> sampler.
Without this, we'll hit read-after-write sync validation error
and produce various artifacts (e.g a fade to white effect) on
different platforms.
> vk: fix missing read-after-write barrier

- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
A recent change broken the optional "depth clamp" as well as the  computation of the far plane of the light frustum. There was also a case where DEBUG builds could assert.
- The far plane was no longer being "optimized" (i.e. moved as close as possible), which resulted in less optimal use of the shadow texture. the far plane can be moved as close as the farthest visible shadow  caster.
- After the camera/light frustums intersection we now see of the 2D bounds seen from the light are empty and if so we bail, which prevents an assertion later.
- finally, the "DEPTH_CLAMP" option is also updated for the new code structure.
> fix a few issues with shadowing

- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- filament/src/ShadowMapManager.h
- filament/src/details/Engine.h
- samples/gltf_viewer.cpp
shadow cascades where not calculated properly because part of the  calculation took the cascade near/far into account, while another part didn't. This resulted in cascades being too large. It didn't create wrong shadows, but reduced (and in some case canceled) the usefulness of the cascade.
We fix the problem by always  using the projection matrix only for describing the cascade's frustum, as opposed to just passing the near/far plane distances.
Now the calculation of each cascade is completely self contained and identical.
We also improve the orientation of the light frustum: We can rotate the light frustum around the light direction axis, so it aligns with the view direction, this generally result in smaller light frustums. This cannot be used in stable mode.
> fix shadow cascade computations

- filament/src/ShadowMapManager.cpp
This is because the shadowmap doesn't store depth values so it doesn't  work to "flatten" all casters behind de camera to the near plane. The bulk of shadowing works but the filtering/edges don't always.
Disable depth-clamping when VSM is enabled.
> depth clamp cannot work with VSM

- filament/src/FrameSkipper.cpp
- filament/src/FrameSkipper.h
It is legal for the app to draw a frame even when FrameSkipper  detects that a frame should be skipped. In that case we used to overwrite the most recent fence, but this wasn't ideal. We now proceed as if the fence had signaled, i.e. we destroy it and move all the fences up, creating a new one at the end of the  delayed array.
> improve FrameSkipper when disregarding skipping

- libs/viewer/include/viewer/AutomationEngine.h
- libs/viewer/src/AutomationEngine.cpp
- samples/gltf_viewer.cpp
screenshots are saved in the current directory as  "screenshotXX.ppm" with XX increasing after each
screenshot.
> new screenshot debug option in gltf_viewer

- filament/backend/src/opengl/GLDescriptorSet.h
For some platform, the compilation fails because the size of the struct is not exactly 32 bits (but is always less).
> GLDescriptorSet: less restrictive size assert

- libs/filamat/src/GLSLPostProcessor.cpp
Issues with it were fixed (https://github.com/KhronosGroup/SPIRV-Cross/pull/2163), so it should be safe to reenable. The invalid glsl code seems to be resolved.
> reenable the SimplificationPass in spirv-opt

- filament/src/details/Material.cpp
Verify the compatibility between a compiled material and the engine's setting only when the engine is set up for stereo.
Materials are always compiled with either 'instanced' or 'multiview even if we compile them with 'none'. Therefore Filament will emit warnings unintentionally in this case. This commit fixes it.
> Fix compatibility warning for multiview

- libs/filamat/include/filamat/MaterialBuilder.h
The default values were not provided via default construction. Caused matc to crash on Linux.
> matc: initialize CustomVariable

- libs/gltfio/src/extended/AssetLoaderExtended.cpp
Decoding the mesh optimized gltf in a loop slows down the extended algo drastically & crashes the app with larger primitives
> decoding meshoptimized gltf just once

- filament/src/PostProcessManager.cpp
- filament/src/RendererUtils.cpp
- filament/src/RendererUtils.h
- filament/src/details/Renderer.cpp
The problem was that in that case, SSR was using the colorgraded
color buffer as history.
> fix screen-space reflection when sub-pass colorgrading is used 

- filament/src/details/Renderer.cpp
Coupling subpass on/off with buffer padding has unintended consequences when we need to turn subpass off for tests. We uncouple them in this change.
> Decouple subpass from buffer padding

- filament/src/details/DebugRegistry.cpp
`DebugRegistry::setProperty` is no longer just applicable to debug builds.
This change was previously added in 6c0bd36 but then reverted in a7317e7. We re-enable it and separate it from the shadow changes in this commit.
> Re-enable DebugRegistry::setProperty for release build

- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanTexture.cpp
- Removed the `VK_IMAGE_USAGE_TRANSFER_SRC_BIT` and `VK_IMAGE_USAGE_TRANSFER_DST_BIT` flags that were systematically added to all color and depth attachments.
- Modified the behavior of `TextureUsage::BLIT_SRC`, `TextureUsage::BLIT_DST`, and `TextureUsage::UPLOADABLE`, so that they only raise the corresponding `VkImage` usage flags.
- Note that I shied away from removing `VK_IMAGE_USAGE_SAMPLED_BIT` from depth texture with more than 1 sample, as I am not familiar enough with the custom shader-based resolve. I believe we could move the flag to where the depth sidecar is created (using `TextureUsage::SAMPLEABLE`), but I am not sure 100%.
> Refactored the handling of usage flags in the VulkanTexture constructor

- filament/src/ResourceAllocator.cpp
this is because the "disposer" is now separate from the  ResourceAllocator, so even if we don't use the resource allocator we need to register the handle with the disposer.
> disabling ResourceAllocator led to incorrect assert

- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
This is because we had this assumption on vk and mtl backends already and also because SYSTRACE works this way and we didn't have non-null terminated strings. This makes things more consistant and less bug  prone.
> make pushGroupMarker and insertEventMarker null-terminated strings

- filament/src/details/Renderer.cpp
with a previous change we were too aggressive in falling back to  "no buffer padding", we need to do this only in the case where "as subpass" would have been used if supported by the h/w.
> repair the "no buffer padding case"

- filament/src/PerViewUniforms.cpp
- filament/src/ResourceAllocator.cpp
- filament/src/details/Renderer.cpp
- filament/src/details/Texture.cpp
- filament/src/details/View.cpp
make sure to unset all textures in the per-view sampler group after
they are used, because the resource could be destroyed after the
pass is finished
- unset the fog and ibl_specular after the color pass
- move that cleanup a bit earlier
- in the case of screen-space reflection the structure pass is
set, but might not be used in the color pass, so we also need to
unset it after the SSR pass and before any other passes.
> fix potential framegraph textures use-after free 

- filament/backend/src/CircularBuffer.cpp
Don't remember why this was ever disabled, seems supported on iOS.
BUGS=[362965958]
> Enable mmap on iOS

- filament/include/filament/FilamentAPI.h
This call is used in the BuilderNameMixin template definition, which is a public API.
> Make builderMakeName public

- .github/actions/android-continuous/action.yml
- .github/workflows/android-continuous.yml
- .github/workflows/presubmit.yml
- .github/workflows/release.yml
- README.md
- build/android/build.sh
- Pulled the android continuous workflow into an action
- Split the android continuous build into 3 ABIs armv7, armv8a,
and x86_64 (note that x86 is not present).
- Remove the upload artifacts step from previous workflow.
Unclear why that was present.
- Split the android continous into debug build and a release
build commands, enabling deletion of intermediate output
directory.
> github: Split Android CI to per ABI builds

- filament/backend/src/CommandStream.cpp
- filament/src/fg/FrameGraph.cpp
when debug markers are implemented with systrace, begin/end can is not guaranteed to happen in the same C++ scope, so we can't really use  other scoped systraces.
> fix debug markers when implemented with systrace

- filament/include/filament/View.h
- filament/src/View.cpp
While this method exists on FView, it is missing from View and thus not accessible for filament users. This adds a pass-through method on View.
> Expose getShadowType on View.

- filament/backend/src/vulkan/caching/VulkanPipelineLayoutCache.cpp
- filament/backend/src/vulkan/caching/VulkanPipelineLayoutCache.h
This is to address a weird map.find() miss that only happens on ARM in release mode.
> vk: use std::unordered_map in PipelineLayoutCache

- libs/filamat/src/GLSLPostProcessor.cpp
This reverts commit 30387af61cbd29a9e9f3bdbc6959938222b64c81.
Causes breakage on Pixel 8pro for 1P apps.
> Revert "reenable the SimplificationPass in spirv-opt"

- NEW_RELEASE_NOTES.md
- filament/src/details/RenderTarget.cpp
- samples/CMakeLists.txt
- samples/hellostereo.cpp
- samples/materials/arrayTexture.mat
Clients can create a multi-layered render target that consists of array textures, and use it as a custom render target.
A new sample app "hellostereo" demonstrates how to use this feature.
> Support multi-layered render target

- filament/src/FrameSkipper.cpp
- filament/src/FrameSkipper.h
FrameSkipper was recently broken because of a typo resulting in  the frame latency being always 3 instead of the default of 2.
This change also makes the maximum latency 2 instead of 3, because on ANDROID, 3 can cause CPU throttling at seemingly random places on the GL thread.
> fix FrameSkipper

- libs/utils/include/utils/memalign.h
ptrdiff_t was transiently included by type_traits. However, this is not true for some cpp toolchains. Add the header inclusion explicitly.
> Add missing include

- libs/utils/include/utils/memalign.h
Use stddef.h instead of cstddef for ptrdiff_t
> Prefer using C header

- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
The sizing of each field in Bitmask has changed, and the description was no longer accurate.  This caused msan to fail because the mask is also used as a key to cache.
> vk: Fix descriptor set bitmask padding

- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/VulkanUtility.h
- filament/backend/src/vulkan/caching/VulkanDescriptorSetManager.cpp
- filament/backend/src/vulkan/caching/VulkanDescriptorSetManager.h
Part 1:
Using bitset enables simpler counting of bits and the use of the
handy 'forEachSetBit'.
Also cleaned up various unused code.
Part 2:
DescriptorSetManager's commit() is the inner most of the
rendering loop. We want to avoid any hash map look up here.
We just store a pointer to the history object where appropriate.
> vk: refactor descriptor set bitmask and hash map usage

- filament/src/details/MaterialInstance.cpp
@pixelflinger would you prefer if `FMaterialInstance:` holds on to a `FEngine&` reference instead of passing it each time to `commit`?
> Check for invalid texture inside MaterialInstance

- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/caching/VulkanDescriptorSetManager.cpp
- filament/backend/src/vulkan/caching/VulkanDescriptorSetManager.h
We need to cache descriptor set layouts because Filament creates new layout objects for the same layout content. Adding to this is that descriptor set's lifetime is tied to the layout that it is created from, and we are trying to recycle used descriptor sets wrt layout. This implies that we need to (unfortunately) separate the vk layout lifetime from the filament layout lifetime.
In this commit, we use a cache so that the same layout content will always map to one vk layout.
Also fixed bugs on bit-shifting and counting.
> vk: cache descriptor set layout

- .github/workflows/ios-continuous.yml
- .github/workflows/linux-continuous.yml
- .github/workflows/mac-continuous.yml
- .github/workflows/web-continuous.yml
- .github/workflows/windows-continuous.yml
v1.0.0 has been deprecated and is causing our builds to fail. We update the action to use v4 (the most current and recommended version).
> github: use up-to-date actions/upload-artifact

- libs/filamentapp/src/FilamentApp.cpp
- samples/gltf_viewer.cpp
- Both Scene and IBL are holding on to a skybox reference. We need to make sure the order they are destroyed in right order.
- Reloading IBL should trigger resetting the indrect light in gltf_viewer.
> sample: fix two IBL loading crashes

- filament/src/details/Texture.cpp
- filament/src/details/Texture.h
once we reach the full range of lods, we were resetting the lod range to {0,0}, which means "default, all lods" (which is the initial state of the texture). However this broken the LOD-expanding code.
instead, we now keep the lod range, but we check in in  getHandleForSampling() wether the range is full or default.
> fix a logic bug when updating the lod range of a texture

- filament/src/details/Renderer.cpp
Found through testing that renderStandaloneView+vk+swiftshader seems to cause synchronization issues, which results in incorrect rendering. Here we workaround the issue by forcibly flush and wait per renderStandaloneView call.
BUG=361822355
> vk: workaround a renderStandaloneView issue

- .github/workflows/android-continuous.yml
- .github/workflows/ios-continuous.yml
- .github/workflows/linux-continuous.yml
- .github/workflows/mac-continuous.yml
- .github/workflows/release.yml
- .github/workflows/web-continuous.yml
- Previously we also split Android build into 3, but because we get larger disk with large runners, we combine them again.
> github: upgrade runners on release/continuous

- filament/backend/include/backend/DriverEnums.h
- filament/src/ds/SsrPassDescriptorSet.cpp
- filament/src/ds/SsrPassDescriptorSet.h
- libs/filabridge/include/private/filament/EngineEnums.h
- libs/filabridge/src/DescriptorSets.cpp
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/MaterialVariants.cpp
- libs/filamat/src/shaders/ShaderGenerator.cpp
- libs/filamat/src/shaders/ShaderGenerator.h
The SSR variant uses a custom fragment shader but the generic vertex shader. For this reason their descriptor set layout for the "per view" set end-up being different (the fragment shader one has less descriptors in it and the descriptor itself is create from the SSR variant data).  In the end, we end up with a descriptor set that's too small for the vertex shader and Metal was rightly complaining.
We fix this by:
- removing the descriptors unused in the vertex shader in the generic case
- adding the remaining descriptors in the SSR version of the layout
In practice this only adds one UBO (for shadows). That UBO is actually not even used in the SSR variants, but the (generic) vertex shader  layout has it, so it must be provided. WE do this by providing a dummy UBO, which will never be …
> fix fragment/vertex shader descriptor set layout mismatch

- filament/src/details/Engine.cpp
- filament/src/details/MaterialInstance.cpp
- filament/src/details/MaterialInstance.h
the previous fix prevented "commit" to patch the samplers that use a texture with a volatile handle.
the proper fix is to patch them first, and then see if some are still missing, in which case we use a dummy texture.
> better fix for fixing up missing samplers

- .github/workflows/android-continuous.yml
- .github/workflows/presubmit.yml
- .github/workflows/release.yml
- build/windows/build-github.bat
- Also used a smaller runner as the gains from the 32-core was
not efficient when comparing output times.
- Clean-up:
- Rename the android continuous to a proper name
- set 'echo on' for the Windows release build so we'll know
why the output asset does not get "moved" correclty.
> github: make windows build use all available cores

- filament/src/RenderPass.cpp
this value needs to be updated each time the execute inner loop changes.
> update the max command size

- filament/CMakeLists.txt
- filament/backend/include/backend/DriverEnums.h
- filament/src/Bimap.h
- filament/src/HwDescriptorSetLayoutFactory.cpp
- filament/src/HwDescriptorSetLayoutFactory.h
- filament/src/HwVertexBufferInfoFactory.h
- filament/src/PostProcessManager.cpp
- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
- filament/src/details/Material.cpp
- filament/src/details/View.cpp
- filament/src/ds/ColorPassDescriptorSet.cpp
- filament/src/ds/ColorPassDescriptorSet.h
- filament/src/ds/DescriptorSetLayout.cpp
- filament/src/ds/DescriptorSetLayout.h
- filament/src/ds/PostProcessDescriptorSet.cpp
- filament/src/ds/PostProcessDescriptorSet.h
The cache gets a lot of hits for the "per view" descriptor set layout because it is provided by the  material itself but in practice there is just a set of 8 of them.
The "per material" descriptor set layout also get a fair number of hits. Probably because many materials have similar layouts.
This will help the vk backend who needs to keep some state per  descriptor set layout. This should also save a bit memory and could help with state changes.
> add a cache for DescriptorSetLayout

- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
- filament/src/details/Material.cpp
- filament/src/details/Material.h
- filament/src/details/MaterialInstance.cpp
- filament/src/details/MaterialInstance.h
The default MaterialInstance is not special anymore. It's not even created until getDefaultInstance() is called.
Material just keeps a pointer to it after that and it's tracked by Engine just like any other instance.
> make the default MaterialInstance just a regular one

- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
In the previous logic, if bindPipeline() is called after scissor(), then the scissor is overwritten with the extent of the rendertarget.  We only want to call scissor if it hasn't been called before in the same renderpass.
BUG=677841839
> vk: fix scissor logic

- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
scissor() works like on metal now, that is, it is disabled when a render pass starts.
The GL backend already assumed this in debug mode. We cannot really run into issues at the moment because every time we get a new  MaterialInstance we set the scissor -- we do this both for the color pass and the post-process passes. With this change we will be able to skip setting the scissor altogether in a lot of cases.
> make scissor() work the same way on all backends

- filament/backend/include/backend/TargetBufferInfo.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/ostream.cpp
- filament/backend/src/vulkan/VulkanContext.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/include/filament/RenderTarget.h
- filament/src/details/RenderTarget.cpp
- filament/src/details/RenderTarget.h
- samples/hellostereo.cpp
Currently mLayerCount for RenderTarget is always updated to the number of depth for attachments, which incurs unintended behaviors for some types of textures. i.e., 2d array, cubemap array, and 3d textures.
Fix this by updating mLayerCount only for multiview use case.
BUGS=[369165616]
> Fix broken layerCount for some types of textures

- filament/backend/src/vulkan/VulkanTexture.cpp
There is a bug in the swizzle composition so that given swizzle mapping
A = [I I I I]
B = [R R 0 0]
and compute B(A) (that is, B composed with A) will yield [I I 0 0]. This is incorrect.  We should expect the result to be [I R 0 0].
This change transforms A to [R G B A] and then carry out the original composition code, which will yield the correct result.
> vk: fix texture swizzle

- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanFboCache.cpp
- filament/backend/src/vulkan/VulkanFboCache.h
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanTexture.cpp
- filament/backend/src/vulkan/VulkanTexture.h
We have a WRITE_AFTER_READ validation when enabling Camera->DoF.
- The old renderpass code assumes that we need to set the initialLayout of a color attachment to UNITIALIZED if it's being discarded. This is no longer true. Before attachment, the image should already be in the proper attachment layout.
- The transition to color attachment layout might not actually emit a barrier. We explicitly emit a barrier for the case of going from sampler to attachment.
- Fix some debug code
> vk: fix initial layout logic in renderpass

- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/test/test_Callbacks.cpp
- filament/include/filament/SwapChain.h
- filament/src/SwapChain.cpp
- filament/src/details/SwapChain.cpp
- filament/src/details/SwapChain.h
Two improvements:
1. Call present directly on the metal callback thread.
2. Release the drawable immediately in the callback destructor (don't dispatch to main). We still need the mutex to avoid releasing/requesting drawables at the same time.
BUGS=[367044996]
> Improve setFrameScheduled threading

- .github/actions/ubuntu-apt-add-src/action.yml
- .github/workflows/presubmit.yml
- test/renderdiff/README.md
- test/renderdiff/parse_test_json.py
- test/renderdiff/run.py
- test/renderdiff/tests/presubmit.json
- test/renderdiff/tests/sample.json
- test/renderdiff/utils.py
- test/renderdiff_tests.sh
- test/utils/get_mesa.sh
We use Mesa's gallium swrast to render as the driver with
Filament's backend set to GL. We provide a few scripts to parse
the tests (as jsons) and run gltf_viewer to produce the rendering.
> github: add software rasterizer job for GL

- filament/src/PostProcessManager.cpp
`commit` call is required before `use`, which became a new norm for the
new descriptor set design.
> Fix incomplete use of MI for debugCombineArrayTexture

- filament/backend/src/opengl/GLDescriptorSet.h
- filament/src/ds/DescriptorSet.cpp
- filament/src/ds/DescriptorSet.h
- We change GLDescriptorSet::Buffer default constructor to workaround a client's compiler set up issue.
- We removed the assert_invariant that checks that ubo/samplers are not changed after committed in DescriptorSet. This caused an existing client's build to crash.
> Work around client descriptor set issues

- filament/src/ds/DescriptorSet.h
This class has a ( = default) constructor and hence should have explicit initialization in its definition.
> Initialize bool in DescriptorSet.h

- filament/src/details/Texture.cpp
We need to also account for external image textures that are imported in texture creation.
> Fix imported texture path

- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- filament/backend/src/opengl/OpenGLDriver.cpp
Mesa always clears the generic binding if the buffer deleted is bound to an indexed binding, even if it's not bound to the generic binding.
BUGS=[371324321]
> workaround Mesa glDeleteBuffers() bug

- filament/backend/include/backend/Platform.h
- filament/backend/src/metal/MetalContext.h
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
- filament/include/filament/Engine.h
- filament/src/details/Engine.cpp
Remove `textureUseAfterFreePoolSize`, we'll switch to a more generic use-after-free detection for "heap" handles.
> Remove textureUseAfterFreePoolSize and texture use-after-free

- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/MaterialVariants.cpp
- libs/filamat/src/shaders/ShaderGenerator.cpp
when shadow multiplier was used, the material used the wrong variant (unlit).
> fix shadow multiplier mode

- libs/camutils/src/FreeFlightManipulator.h
This PR addresses an issue in the FreeFlightManipulator class where getCurrentBookmark did not accurately reflect the camera state after calling jumpToBookmark. The fix updates the mTargetEuler values in jumpToBookmark to ensure consistency with getCurrentBookmark.
Changes:
- Modified jumpToBookmark in FreeFlightManipulator to update mTargetEuler.x and mTargetEuler.y
- This ensures that subsequent calls to getCurrentBookmark will return the correct pitch and yaw values
- Resolves the issue of incorrect bookmark state after jumping to a bookmark
> Fix inconsistency between jumpToBookmark and getCurrentBookmark in FreeFlightManipulator

- filament/backend/include/backend/Handle.h
In certain compilers, the assignment operators defined as default
doesn't automatically make a call to the parent's method if it's
user-defined.
Make this behavior explicit to avoid this edge case.
BUGS=[371980551]
> Update hardware Handle

- android/filament-android/src/main/cpp/Engine.cpp
- android/filament-android/src/main/java/com/google/android/filament/Engine.java
- filament/backend/include/backend/Platform.h
- filament/backend/include/backend/platforms/PlatformEGLAndroid.h
- filament/backend/src/opengl/platforms/PlatformEGL.cpp
- filament/backend/src/opengl/platforms/PlatformEGLAndroid.cpp
- filament/include/filament/Engine.h
- filament/src/details/Engine.cpp
We are seeing a cluster of crashes that could be due to using an EGLSurface whose ANativeWindow has become invalid. This could happen if we continued to use (i.e. draw with) an EGLSurface after  SurfaceHolder::onSurfaceDestroyed() has returned.
This new flag enables an assertion that the native window is valid at the time of makeCurrent(), which happens early in the frame.
BUG=[330392256]
> gles: add a flag to enable the validation of the nativewindow

- filament/backend/src/opengl/platforms/PlatformEGLAndroid.cpp
ANGLE features should be set by apps, the system or developers but it's not a good idea to set them in a library as it might conflict with other libs etc.
we did it because it improved performance, but that should be fixed at the angle level instead.
> don't set ANGLE features in filament

- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/caching/VulkanDescriptorSetManager.cpp
- filament/backend/src/vulkan/caching/VulkanDescriptorSetManager.h
"history" is a map from a DescriptorSet pointer to a set of bookkeeping values (we delay "binding" until "commit" so need to keep values until then). Instead of using a map, we can store these values in the DescriptorSet itself so that we save on a map look-up.
> vk: remove history from DescriptorSetManager

- filament/CMakeLists.txt
- libs/gltfio/CMakeLists.txt
The warnings that this change ignores are tricky to fix in the code in a way that is backwards compatible with c++17, but it is possible to do and it would allow these warnings to be reinstated. But for now it seems reasonable to just ignore the warnings if building under c++20, since it compiles and works just fine.
This is useful, for example, if Filament is being used as a CMake submodule inside a project that compiles under c++20.
> Add support for compiling under c++20 on clang-based compilers.

- filament/src/RenderPass.cpp
- filament/src/details/Renderer.cpp
- filament/src/details/View.h
Based on #6633 by @grassydragon, I continue to finish the requirements by @pixelflinger:
> This is what I would like to see:
> 
> * have an option to include or not the transparents. I think there is value to not include the transparents in picking.
> * reuse the structure pass in the case transparents are not included (each extra pass costs about the same as a shadow pass, it's not insignificant). Thanks to the framegraph design this can be done pretty easily: keep the old code, keep the new code and just select which "picking" resource you want to use based on wether transparents should be included -- the framegraph will take care of removing the pass that's not needed.
Here's what I did: 
- Add a boolean in `FView` to select whether to pick transparent entities
- Use structure pass …
> Pick transparent renderables

- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- the main goal of this change was to move some state changes outside of loops, usually with mip generation.
- for instance bindPostProcessDesciptorSet() must now be issued manually (and can be done outside the loop)
- we also don't set the scissor for each pass
- we also move prepareMaterial() outside of getPipelineState(), it's now done in PostProcessMaterial::getMaterial().
- We use PostProcessVariant instead of uint8_t everywhere
In the end we have three drawing helpers:
- commitAndRenderFullScreenQuad() which updates a material instance, binds the corresponding material and draws a full screen quad.
- renderFullScreenQuad() which just renders a full screen quad.
- renderFullScreenQuadWithScissor() which does the same but scisorred
Additionally, we have the following helpers for …
> Cleanup PostPorcessManager rendering

- filament/backend/include/backend/DriverEnums.h
- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
RenderPass is now tracking the scissor state locally so it can avoid re-setting the scissor when it doesn't change.
We also consolidate the scissor override and the scissor-viewport in RenderPass::Execute.
> avoid setting the scissor rect when possible

- filament/backend/include/backend/DriverEnums.h
- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
This reverts commit fc095413b3682b8065bc772ec95083c6926de7d0.
clipping is wrong when post-processing is disabled
> Revert "avoid setting the scissor rect when possible"

- filament/backend/CMakeLists.txt
- filament/backend/src/metal/MetalState.h
When a descriptor set is destroyed, its `id<MTLBuffer>`s are still bound within `vertexDescriptorBindings` and `fragmentDescriptorBindings` using `__unsafe_unretained` pointers . This is a problem because those pointers will be garbage after the descriptor set is destroyed. At the next render pass, if a new descriptor set is not bound, we'll attempt to pass the garbage values to `setVertexBuffer:offset:atIndex`.
Consider the following contrived repro case inside of a backend_test:
Some complications: the destruction of a descriptor set is delayed until the current command buffer completes AND the enclosing `@autoreleasepool` is drained. So, we need to insert a `api.finish(0)` and wrap every command around a `mDriver.execute` [inside …
> Fix potential crash when a descriptor set is destroyed but not unbound

- filament/src/components/RenderableManager.cpp
In some cases, users set materials first without providing render primitives, which has incurred the attribute mismatching warning. This isn't helpful because users don't know what action they should take to remove the warning.
Emit the warning only when the primitive handle is initialized so the AttributeBitset is properly populated.
BUGS=[372755205]
> Add a warning for FRenderableManager

- filament/backend/src/opengl/platforms/PlatformWGL.cpp
As you might imagine, I am submitting this change because I'm debugging a bug in the openGL backend, specifically one that causes PlatformWGL::makeCurrent() to fail if the swap chain is removed and created too many times. I hope that I can figure out the issue there, but if someone more familiar with this code could figure it out, that would be really cool... (If anyone is curious, wglMakeCurrent() is returning win32 error code 6.)
> Fix a bug in the OpenGL backend that causes win32 errors not to be logged #8214

- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
- filament/src/details/Material.cpp
- filament/src/details/MaterialInstance.cpp
- filament/src/details/MaterialInstance.h
This PR is related to [PR #8147](https://github.com/google/filament/pull/8147)
After applying PR #8147, FMaterial::createInstance has an issue where it ignores the name passed as a parameter when mDefaultMaterialInstance is not set.
By applying this PR, a material instance can be assigned a name even if mDefaultMaterialInstance is not set.
> Fix issue where material instance name cannot be set without creating a default instance

- filament/src/details/Renderer.cpp
When multiview is enabled with the combining debug option toggled on, we use an intermediate buffer that requires us to use the entire area of the buffer as the viewport. Use xvp in this case.
> Use xvp for multiview + debug view

- filament/backend/src/vulkan/platform/VulkanPlatformAndroidLinuxWindows.cpp
The NVIDIA Vulkan driver bug causes swap chains to be created with incorrect dimensions for native windows created with thread-specific DPI-awareness context.
This is a pretty subtle issue, and only affects processes where the process-wide DPI-awareness context is different from the thread-specific DPI-awareness context that was used to create a given native window. The [Microsoft docs on this](https://learn.microsoft.com/en-us/windows/win32/hidpi/high-dpi-improvements-for-desktop-applications) are pretty decent, and are super clear that the DPI-awareness of a HWND is whatever the DPI-awareness of the thread that created it was. The NVIDIA driver appears to be ignoring this. I suspect other drivers do as well.
This workaround has to be submitted into Filament itself because client code …
> Add a workaround for a Windows NVIDIA Vulkan driver bug

- filament/src/ResourceAllocator.cpp
- filament/src/ResourceAllocator.h
This is a fix for #8167, and this allows debug builds under MSVC to work again without crashing in the iterator debug stuff.
> Fix bug in ResourceAllocator with erasing iterators inside loops

- tools/beamsplitter/emitters/serializer.template
the generated file was modified, which would be undo'ed next time we run beamsplitter
> update beamsplitter template

- filament/backend/CMakeLists.txt
This is an extension of commit 22db1be -- this one only comes up if you compile the project in debug mode in clang, which I hadn't done before.
> Fix clang c++20 compilation under debug mode as well.

- filament/backend/src/vulkan/VulkanMemory.cpp
Allows Filament to compile cleanly with -Wthread-safety enabled.
> Ignore another warning for vk_mem_alloc.h 

- android/filament-android/src/main/cpp/Engine.cpp
- android/filament-android/src/main/java/com/google/android/filament/Engine.java
- filament/include/filament/Engine.h
- filament/src/Engine.cpp
- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
Feature flags are intended to be used when a new feature is added to  filament and have generally two purposes:
1) during feature development, the feature can be implemented but
disabled which can help developing large features. This way the
feature can be tested by stakeholders while it's being developed
without impacting other clients.
2) once a feature is ready, its flag can be enabled by default, but 
in case the feature breaks something or has unintended consequence,
clients have the option to turn it off.
Feature flags are intended to have a relatively short life span, i.e. once a feature is stable, the flag fill be removed.
There two types of feature flags. Constant feature flags can only be set during Engine initialization via Engine::Builder. Non-constant feature flags can be set …
> a new Feature Flag API

- android/samples/sample-hello-triangle/src/main/java/com/google/android/filament/hellotriangle/MainActivity.kt
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLProgram.cpp
- filament/src/details/Renderer.cpp
On ES2 devices (or in forceES2 mode), we emulate the sRGB swapchain
in the shader if the h/w doesn't support it. In that case, the emulation
is controlled by a uniform that technically lives in the frameUniforms
block. However, the frameUniforms buffer is not updated, instead,
the uniform is manually set. Unfortunately, the UBO emulation
overrides it with the uninitialized variable.
BUGS=[377913730]
> fix uninitialized variable on ES2 devices 

- filament/backend/src/metal/MetalDriver.mm
This can cause issues if we destroy a descriptor set but don't bind a new one.
BUGS=[378374231]
> Metal: unbind descriptor sets upon destruction

- libs/utils/include/utils/ostream.h
- libs/utils/src/ostream.cpp
It only grew by 3/2 of the needed size instead of the needed capacity, which could be extremely slow when growing by a constant amount many times.
> ostream buffer growth was broken

- libs/utils/include/utils/Allocator.h
I do not think there was an actual error with AtomicFreeList, however TSAN detected a data race when concurrent pop() happened. In that case, there is indeed a race, where we can end-up reading data that is already corrupted by the concurrent pop. However, that situation is corrected by the following CAS. Somehow TSAN didn't see that. The fix is strange and consists in replacing:
```
auto pNext = storage[offset].next;
```
with
```
auto s = storage[offset];
auto pNext = s.next;
```
In this PR we also adjust the memory ordering to be less strong. i.e. we do not need `memory_order_seq_cst`, only the appropriate acquire or release semantic.
In addition we also make `Node* next` a non-atomic variable again. It should have been, but was change to placate an older version of TSAN. …
> Fix TSAN warnings with AtomicFreeList

- libs/utils/include/utils/JobSystem.h
The previous fix attempt didn't work on some test. There are no known bugs with AtomicFreeList other than tripping TSAN, and it's unclear that TSAN isn't at fault.
However, switching to using a mutex works fine and doesn't appear to be slower (it's actually faster with synthetic benchmarks on macOS)
BUGS=[377369108]
> Don't use AtomicFreeList to squash TSAN complains

- filament/backend/src/vulkan/VulkanCommands.cpp
- filament/backend/src/vulkan/VulkanCommands.h
The old logic was unnecessarily complex. We simplify it and also properly store the marker stack on the CommandPool instead of VulkanCommands.
> vk: clean up group marker logic

- filament/backend/src/vulkan/VulkanCommands.h
- filament/backend/src/vulkan/VulkanConstants.h
Small number of pre-allocated command buffers can cause unnecessary blocking on the CPU.  We increase this number.
> vk: increase number of command buffers

- filament/src/details/View.h
To fix the [crash](https://github.com/google/filament/issues/8282) for short term, will investigate the root cause of this crash.
> Disable transparent picking by default

- filament/src/details/Engine.cpp
- filament/src/details/Material.cpp
- filament/src/details/Material.h
- libs/filabridge/include/private/filament/Variant.h
- libs/filabridge/src/Variant.cpp
Materials that don't use a custom depth can share the same program for all depth variants. We take advantage of that by pre-caching the depths variants when a program is loaded. The depth variants themselves are owned by the default material which is created first. When a material is destroyed it skips deletion of those variants which will be truly destroyed when the default material is destroyed.
Unfortunately, the default material doesn't contain all depth variants, in particular, it doesn't have the VSM ones (because it's an unlit material).  On top of that, the way it pre-cached depth variant had a bug that made it miss some picking variants.
Because of that, these variants were skipped during material destruction but never actually destroyed, since the default material didn't know …
> fix a HwProgram leak related to depth variant pre-caching

- libs/gltfio/src/Animator.cpp
Without this change, trying to animate to the exact last keyframe wraps back to the first, which only works for animations that loop.
> Bugfix to allow animations to use a keyframe at exactly time=duration

- android/filament-android/src/main/cpp/EntityManager.cpp
- android/filament-android/src/main/cpp/IndirectLight.cpp
When releasing array elements, we need to pass 0 as the last argument if we want to copy local chnages back to the Java array. JNI_ABORT should only be used when we don't want the copy, i.e. when the array is read-only.
Fixes issue #8278.
> Copy back local values to Java array

- filament/backend/src/metal/MetalContext.h
- filament/backend/src/metal/MetalDriver.mm
- depthClamp is only supported from iOS 11.0
- reset the depthClamp state at the beginning of the renderpass
BUGS=[379729888]
> Fix a couple depthClamp issues on metal

- filament/include/filament/Camera.h
As mentioned few lines above:
>  * In Filament, Camera is a component that must be associated with an entity. To do so,
> * use Engine::createCamera(Entity). A Camera component is destroyed using
> * Engine::destroyCameraComponent(Entity).
Entity must be used for creating and destroying `Camera`.
So, this PR propose a fixing typo in code snippet of `Camera` doc comment.
> Fix typo in `Camera` doc comment

- filament/src/details/Material.cpp
This restores the old behavior with depth variant caching. We pay the price at engine init time, instead of when the variant is needed the first time. We can revisit this later.
Note that the default material doesn't have all possible depth variants (e.g. VSM), but that pre-caches the most popular ones.
BUGS=[381946222]
> pre-populate the default material's depth variants

- filament/src/details/Renderer.cpp
- filament/src/details/View.cpp
- filament/src/details/View.h
- filament/src/ds/ColorPassDescriptorSet.cpp
- filament/src/ds/ColorPassDescriptorSet.h
Because ColorPassDescriptorSet is used for both the color pass and the picking/ssr/structure passes, the texture it holds can be stale.
In this CL we fix this by reseting the offending textures when preparing the picking/ssr/structure passes. This has a side effect of recreating the descriptor-set internally. A better fix would be to use separate descriptor-sets for these two cases and rely on the texture cache to avoid recreation from a frame to the next.
BUGS=[376705346]
> fix a use-after-free of texture handles

- filament/backend/src/metal/MetalShaderCompiler.mm
When using async shader compilation, the compiler thread pool is a  standard pthread and not an NSThread. Therefore, it needs a manual @autorelease pool, otherwise ARC objects never get truly released.   BUGS=[383167935]
> Fix ARC objects leak in MetalShaderCompiler thread

- filament/src/details/Engine.cpp
A ResourceList<> object was leaked when destroying a material until the  Engine was shut down. This could however grow unbounded if churning  through Materials.
What was actually leaked was entries in the hashmap linking a material to its material instance list.
BUGS=[383158161]
> fix a ResourceList<> "soft" leak when destroying a material

- libs/filamat/src/shaders/ShaderGenerator.cpp
- shaders/src/common_shading.fs
- shaders/src/getters.fs
When tangents are not supplied in a material, all "normals" related public methods become undefined; remove access to them so we get  compile time errors instead of garbage values in the shader.
> matc: remove access to public functions that should be undefined

- filament/src/components/LightManager.cpp
The `ShadowCascade` functions for computing splits all attempted to clamp `cascades` to [0,4] (evidently to avoid out-of-bounds access), but used `max`, instead giving a range of [4, x].
For applications using less than 4 cascades, this results in incorrect split locations and lower quality (much more obvious seam between cascades).
This change just switches to use `min` to ensure `cascades` is in the range [0,4].
> Fix shadow cascade calculations

- filament/backend/src/vulkan/memory/Resource.h
- filament/backend/src/vulkan/memory/ResourcePointer.h
To allow for use-after-free discovery with ref-counting, we keep a bit to indicate whether the handle is considered destroyed by Filament. We assert against "cast"-ing a destroyed handle.
> vk: Use-after-free coverage

- filament/backend/src/opengl/platforms/PlatformOSMesa.cpp
- libs/bluegl/src/BlueGLLinuxOSMesa.cpp
If the shared osmesa lib is not found, then we assume that the library has been compile-time linked via the linker.  This is to accommodate build frameworks where compile-time linking is preferred.
> renderdiff: allow for explicit (compile-time) linking of osmesa

- libs/matdbg/src/ApiHandler.cpp
- libs/matdbg/src/DebugServer.cpp
- libs/matdbg/src/ShaderReplacer.cpp
We will be running an additional debug server for the `fgviewer`. 
To help users identify which server is generating the logs, this PR specifies the log source for `matdbg`.
> Specify log source for matdbg

- android/filament-android/src/main/cpp/Material.cpp
- android/filament-android/src/main/java/com/google/android/filament/Material.java
- filament/include/filament/Material.h
- filament/src/details/Material.cpp
- libs/filabridge/include/private/filament/EngineEnums.h
- libs/filamat/src/shaders/CodeGenerator.cpp
- shaders/src/shadowing.fs
> Add a way to set the shadow sampling quality

- filament/include/filament/Options.h
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- filament/src/materials/antiAliasing/taa.mat
- use a lanczos filter for sampling the color buffer, instead of a blackman-Harris window. This improves sharpness quite a bit.
- some cleanups of the shader code
- never use YCoCg when rectification is not enabled.
- fix the calculation of the confidence paramter when upscaling is used.
Upscaling works a lot better now, but it is still work in progress.
> TAA fixes and improvements

- NEW_RELEASE_NOTES.md
- libs/gltfio/src/Animator.cpp
the 'target_node' of Animation Channel may be nullpointer.
> Fix : null pointer crash

- libs/matdbg/src/DebugServer.cpp
- libs/matdbg/src/ShaderReplacer.cpp
- murmur3 expects word size not byte size
- should use uint8_t in addressing blob source.
both would crash when asan is enabled.
> matdbg: fix two memory bugs

- libs/matdbg/CMakeLists.txt
- libs/matdbg/src/ApiHandler.cpp
- libs/matdbg/src/ApiHandler.h
- libs/matdbg/src/SourceFormatter.cpp
- libs/matdbg/src/SourceFormatter.h
We use clang-format to format the shader files. Since we assume clang is necessary for compilation, installing clang-format should not be too much of an overhead in terms of adding dependency.
Currently, we only support posix systems (macOS, linux).
> matdbg: enable source formatting

- libs/matdbg/web/app.js
The option will persist beyond user sessions through localStorage.
> matdbg: add option to hide inactive materials and variants

- build/linux/combine-static-libs.sh
I found that only the first archive is passed as an argument to combine_static_libs, when using macos + universal architecture.
As can be seen from line 146, the bash array should be unrolled using "${archives[@]}".
Up to my knowledge, simply using "$archives" will only pass the first element of the array.
> Fix: combine-static-libs.sh in macos universal

- filament/src/AtlasAllocator.cpp
- filament/src/AtlasAllocator.h
- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- filament/src/ShadowMapManager.h
- filament/src/components/LightManager.cpp
- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
- filament/src/details/View.cpp
- filament/test/filament_AtlasAllocator_test.cpp
- libs/filabridge/include/private/filament/EngineEnums.h
- libs/utils/include/utils/QuadTree.h
This feature is controled by a feature flag and is turned off at this point.
This CL shouldn't change the existing behavior of shadowmap allocation as
long as the atlas feature is not enanled.
When enabled, shadowmap allocations are not limited to layers of the
shadowmap texture, instead, an atlas is used meaning a layer can
be shared by multiple shadowmaps. At the very least this can save
a lot of memory as smaller shadowmaps can be packed together.
Currently this feature breaks some VSM features:
- mipmapping
- blurring
> Add support for an Atlas allocator for shadow maps

- test/utils/get_mesa.sh
The public dep for mesa has moved on to beyond llvm-18, but the version we're compiling against is not supported by this change. We workaround by ensuring that the llvm dep is less than 18 but consistent with the clang version.
> renderdiff: fix llvm-18 dep problem

- docs_src/build/install_mdbook.sh
We add a bash script to download and install mdbook. For linux or mac x86_64, we download prebuilts from github. Otherwise, we use `cargo install` to build it with rust.
> docs: add script to download mdbook

- filament/src/details/Engine.cpp
> Fix wrong comment on unlikely directive

- build/linux/ci-common.sh
- test/utils/get_mesa.sh
There are some packages that cannot be installed with
apt-get -y build-dep mesa
We manually add those packages wrt to the expected clang version.
> renderdiff: fix mesa deps

- android/filament-android/src/main/cpp/RenderableManager.cpp
- android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java
- filament/include/filament/RenderableManager.h
- filament/src/RenderPass.cpp
- filament/src/RenderableManager.cpp
- filament/src/components/RenderableManager.cpp
- filament/src/components/RenderableManager.h
- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
- filament/src/details/Material.cpp
- filament/src/details/Skybox.cpp
- libs/filamentapp/src/Cube.cpp
- libs/gltfio/src/FilamentAsset.cpp
- libs/iblprefilter/src/IBLPrefilterContext.cpp
- web/filament-js/jsbindings.cpp
With this change we now enforce two things:
- All MaterialInstance of a Material must be destroyed when destroying said Material. This has always been a documented  requirement of the public API, but wasn't enforced (only a warning was printed). This new assertion is unconditional.
- A MaterialInstance, when destroyed is no longer in use by any Renderable.
So before destroying a MaterialInstance, the user of API needs to  ensure that either all Renderable using that MaterialInstance in one of their Render Primitives are  destroyed, or, that these Renderable using that MaterialInstance are reset to another one or to null.
There is a new RenderableManager::clearMaterialInstanceAt() that can be used to clear a MaterialInstance on a Render Primitive.
Additionally, a Render Primitive with a …
> validate MaterialInstance references when destroyed

- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanTexture.cpp
Because of a recent ref-counting refactor, the swapchains are not being immediately destroyed when destorySwapChain is called. This might cause issue with following calls to createSwapChain.
We make sure the ref-counted resources are cleaned-up before new swapchains are created.
(also cleaned-up a log spam in VulkanTexture)
Fixes #8288
> vk: do not delay old swapchain destruction when creating new swapchain

- filament/backend/include/private/backend/HandleAllocator.h
- filament/backend/src/HandleAllocator.cpp
- uninlined getHandleTag so that the code is not duplicated when multiple backends are supported (e.g. GLES and Vulkan)
- added a lock for mDebugTags because, even if rare, it technically can be accessed from multiple threads. This would happen only on a failure. There should never be any contention on this lock.
> Handle tags now work with heap allocated handles

- filament/backend/include/backend/Handle.h
- filament/backend/include/private/backend/HandleAllocator.h
- filament/backend/src/vulkan/memory/ResourcePointer.h
- libs/utils/include/utils/Allocator.h
- libs/utils/include/utils/BinaryTreeArray.h
- libs/utils/include/utils/BitmaskEnum.h
- libs/utils/include/utils/JobSystem.h
- libs/utils/include/utils/QuadTree.h
- libs/utils/include/utils/StructureOfArrays.h
- libs/utils/include/utils/algorithm.h
- libs/utils/include/utils/bitset.h
e.g. std::enable_if<cond>::type is replaced by std::enable_if_t<cond>
remove some unneeded typename keywords
> use the more modern syntax for std::enable_if and friends

- libs/matdbg/src/SourceFormatter.cpp
- return original source when on an unsupported platform
- check clang-format is available and return original source.
> matdbg: fix two bugs with formatting

- libs/utils/src/Panic.cpp
Without this change, throwing inside the user panic handler calls terminate(). Note that the docs for setPanicHandler() explicitly say that it's okay for the handler to throw, which is not true prior to this change:
```
* Sets a user-defined handler for the Panic. If exceptions are enabled, the concrete Panic
* object will be thrown upon return; moreover it is acceptable to throw from the provided
* callback, but it is unsafe to throw the Panic object itself, since it's just an interface.
* It is also acceptable to abort from the callback. If exceptions are not enabled, std::abort()
* will be automatically called upon return.
```
> Remove noexcept from UserPanicHandler::call() so that panic handlers can throw as documented

- android/filament-android/src/main/cpp/Engine.cpp
- android/filament-android/src/main/java/com/google/android/filament/Engine.java
- filament/include/filament/Engine.h
- filament/src/Engine.cpp
- filament/src/details/Engine.cpp
- filament/src/details/Engine.h
The old version that doesn't take a timeout now always waits forever; before it waited for a few seconds on Android debug builds.
The new version has an explicit timeout that works on all platforms and returns success status.
FIXES=[384043020]
> add a version of Engine::flushAndWait that takes a timeout

- filament/backend/CMakeLists.txt
- filament/backend/include/backend/platforms/PlatformMetal.h
- filament/backend/src/metal/MetalBuffer.h
- filament/backend/src/metal/MetalBuffer.mm
- filament/backend/src/metal/MetalContext.h
- filament/backend/src/metal/MetalDriver.h
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalDriverFactory.h
- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
- filament/backend/src/metal/PlatformMetal.mm
Give clients the option to abandon a frame if we cannot obtain a `CAMetalDrawable` from the swap chain.
BUGS = [387888833]
> Metal: add config to abandon frame if drawable cannot be acquired

- libs/filamat/src/shaders/CodeGenerator.cpp
- shaders/src/common_getters.glsl
- shaders/src/surface_getters.vs
When targeting Vulkan with multiview, the shader
code generator was using the OpenGL extension
and built-in variables, which are not supported on Vulkan.
Changed it to use GL_EXT_multiview instead of
GL_OVR_multiview2 when the target API is Vulkan.
> Update multiview shader code generator for Vulkan

- filament/backend/include/private/backend/VirtualMachineEnv.h
- filament/backend/src/VirtualMachineEnv.cpp
- filament/backend/src/opengl/platforms/ExternalStreamManagerAndroid.cpp
- filament/backend/src/opengl/platforms/ExternalStreamManagerAndroid.h
- clarify precondition for VirtualMachineEnv, in particular,  JNI_OnLoad() must be called from a thread attached to the VM, and should be called once. This is now enforced internally, subsequent calls are ignored.
- sVirtualMachine was written and read from potentially different  threads without synchronization. It is now mutex protected.
- added fatal asserts in all locations that we cannot recover from; previously we would stay in an undefined state.
BUGS=[390724273]
> attempt to fix crashers when initializing the JVM

- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanMemory.cpp
- filament/backend/src/vulkan/VulkanMemory.h
- filament/backend/src/vulkan/VulkanPipelineCache.cpp
- filament/backend/src/vulkan/VulkanPipelineCache.h
- filament/src/Culler.cpp
- filament/src/Froxelizer.cpp
- filament/src/ToneMapper.cpp
- filament/src/details/ColorGrading.cpp
- filament/src/fsr.cpp
'#pragma clang' is unavailable in MSVC. Wrap them with the proper preprocessor to avoid warnings in MSVC.
BUGS=[390207431]
> Fix warnings regarding #pragma clang

- filament/src/details/Renderer.cpp
If FXAA is the last post process effect (i.e. no upscaling), and color grading produced a luma channel, then FXAA needs to reset the alpha channel to 1.
> make sure FXAA resets alpha channel when it's the last postfx

- NEW_RELEASE_NOTES.md
- filament/backend/include/backend/Platform.h
- filament/backend/include/backend/platforms/OpenGLPlatform.h
- filament/backend/include/backend/platforms/PlatformCocoaGL.h
- filament/backend/include/backend/platforms/PlatformCocoaTouchGL.h
- filament/backend/include/backend/platforms/PlatformEGL.h
- filament/backend/include/backend/platforms/PlatformEGLAndroid.h
- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/Platform.cpp
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/GLUtils.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLPlatform.cpp
- filament/backend/src/opengl/platforms/PlatformCocoaGL.mm
- filament/backend/src/opengl/platforms/PlatformCocoaTouchGL.mm
- filament/backend/src/opengl/platforms/PlatformEGL.cpp
- filament/backend/src/opengl/platforms/PlatformEGLAndroid.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/include/filament/Texture.h
- filament/src/Texture.cpp
- filament/src/details/Texture.cpp
- filament/src/details/Texture.h
The current API used a void* in Texture::setExternalImage to pass the platform specific image. This was a problem because on some  platform like Android, there could be several types (EGLImageKHR and  AHardwareBuffer), and with the void* there was no way to distinguish them on the backend / platform side. 
We now have a new Texture API which takes a 
Platform::ExternalImageHandle, which is a reference-counted handle to a Platform::ExternalImage. Platform::ExternalImage is an opaque type only known by the platform.
This type must be created using a concrete Platform specific API, such as:
PlatformEGL::createExternalImage
PlatformEGLAndroid::createExternalImage
PlatformCocoaGL::createExternalImage
PlatformCocoaTouchGL::createExternalImage
New types can easily be added in the future.
There …
> Improve external texture image API

- filament/backend/include/backend/Platform.h
- filament/backend/include/backend/platforms/OpenGLPlatform.h
- filament/backend/include/backend/platforms/PlatformCocoaGL.h
- filament/backend/include/backend/platforms/PlatformEGL.h
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/opengl/OpenGLPlatform.cpp
- filament/backend/src/opengl/platforms/OpenGLDriverBase.h
- filament/backend/src/opengl/platforms/PlatformEGL.cpp
- filament/include/filament/Engine.h
- filament/src/Engine.cpp
- filament/src/details/Engine.h
Add a way to retrieve the GL_RENDERER and GL_VENDOR strings
The API works this way:
```
auto vendor = OpenGLPlatform::getVendorString(engine->getDriver());
```
Obviously the Backend must be `Backend::OPENGL` and the `Driver` must 
have been created with an `OpenGLPlatform` subclass.
FIXES=[385367277]
> Add a way to retrieve the GL_RENDERER and GL_VENDOR strings

- shaders/src/common_getters.glsl
- shaders/src/surface_getters.vs
Now the helper function `getEyeIndex` becomes available for all shader stages including post-processing. It used to be only accessible from surface vertex shaders.
> Promote getEyeIndex() as a common helper

- filament/include/filament/Scene.h
- filament/src/Scene.cpp
- filament/src/details/Scene.cpp
- filament/src/details/Scene.h
The API works for Scene to clear all entities. Sometimes we need clear all entities from Scene.
> Add clearEntities API in Scene.

- libs/filamentapp/src/FilamentApp.cpp
- samples/multiple_windows.cpp
On macOS using Vulkan backend w/ MoltenVK, filament currently passes down an NSView instance from main thread to create the surface on render thread (by calling the vkCreateMacOSSurfaceMVK). Older versions of MVK simply warn you on this kind of usage:
> [mvk-info] vkCreateMacOSSurfaceMVK(): You are not calling this function from the main thread. NSView should only be accessed from the main thread. When using this function outside the main thread, consider passing the CAMetalLayer itself in VkMacOSSurfaceCreateInfoMVK::pView, instead of the NSView.
Newer versions of MVK will try to post it back to its "main thread" utilizing dispatch_sync (see `MVKOSExtensions.mm`). But if there are any pending waits or fences e.g. `flushAndWait()`, `Fence::waitAndDestroy(mEngine->createFence())`, a …
> Use CAMetalLayer to create MVK surfaces to avoid potential deadlocks.

- filament/backend/src/metal/MetalDriver.mm
This should help catch Metal initialization issues earlier on.
BUGS = [362991544]
> Metal: Assert in release builds if Metal fails to initialize

- android/filament-android/src/main/java/com/google/android/filament/Texture.java
Pass enums as int instead of long.
> Fix misprint in Texture.java binding

- CMakeLists.txt
- filament/backend/CMakeLists.txt
- libs/filamat/CMakeLists.txt
We are in the process of updating glslang, which requires
set(IOS_MIN_TARGET "13.0")
This is a problem since we are targeting iOS 11 in general. glslang is a filamat depedency, and we're building filamat for iOS for the iOS version of the backend test.
So one solution is to set set(IOS_MIN_TARGET "13.0") for the backend test. And we might revisit this solution later.
But for now, we simply disable backend tests (and filamat tests) for iOS.
> build: remove ios build dependency on filamat

- shaders/src/common_math.glsl
I think `vmax(const vec4 v)` should compute max value of all components (xyzw).
> fix vmax(const vec4 v)

- libs/filamat/src/eiff/Flattener.h
Enabling UBSan shows the following error:
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior filamat/src/eiff/Flattener.h:102:17 in
filamat/src/eiff/Flattener.h:102:17: runtime error: applying non-zero offset 8 to null pointer
We reference a placeholder byte on the heap when in DryRunner mode to workaround this issue.
> filamat: fix ubsan failure

- filament/src/details/MaterialInstance.cpp
Just like mCulling, mShadowCulling needs to be inherited from the  material.
Fix breakage introduced in #8422 with attempted fix in #8475 and caused by an uninitialized variable (mShadowCulling).
BUGS=[391679058]
> Initialize mShadowCulling properly

- libs/gltfio/src/AssetLoader.cpp
- libs/gltfio/src/GltfEnums.h
We are not correctly handling gltf models with multiple color attributes. Filament doesn't allow for more than one color attribute.  So we just set the additional attributes as VertexAttribute::CUSOM(N).
Also properly clean up dummy buffer.
Fixes #8396
> gltfio: allow for multiple color attributes

- NEW_RELEASE_NOTES.md
- android/filament-utils-android/src/main/cpp/Utils.cpp
- android/filament-utils-android/src/main/java/com/google/android/filament/utils/KTX1Loader.kt
- android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
- android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
We break existing  API by returning both the IndirectLight and the texture. Same thing with Skybox.
Fix one bug where the float array in getSphericalHarmonics wasn't getting written out.
Fixes #6412
> android: prevent leak of cubemap for IndirectLight/Skybox

- filament/backend/src/vulkan/VulkanStagePool.cpp
Updated the `terminate` function to correct resource cleanup. Changed `mUsedStages` to `mUsedImages` and `mFreeStages` to `mFreeImages` to ensure proper memory management during termination.
> Fix cleanup logic in VulkanStagePool::terminate

- libs/matdbg/src/SourceFormatter.h
missing <string>, it occurs error in cross-compile
> fix SourceFormatter.h missing header file

- filament/backend/include/backend/platforms/OpenGLPlatform.h
- filament/backend/include/backend/platforms/PlatformEGLAndroid.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/opengl/OpenGLPlatform.cpp
- filament/backend/src/opengl/platforms/ExternalStreamManagerAndroid.cpp
- filament/backend/src/opengl/platforms/ExternalStreamManagerAndroid.h
- filament/backend/src/opengl/platforms/PlatformEGLAndroid.cpp
From: https://developer.android.com/reference/android/graphics/SurfaceTexture
When sampling from the texture one should first transform the texture coordinates using the matrix queried via getTransformMatrix(float[]). The transform matrix may change each time updateTexImage() is called, so it should be re-queried each time the texture image is updated.
Exposing the matrix to the driver is the first step to being able to apply it to the uniform in the shader.
> Add a way to query the transform matrix of a surface texture from the driver

- NEW_RELEASE_NOTES.md
- docs/Materials.md.html
- filament/src/MaterialParser.cpp
- libs/filabridge/include/private/filament/BufferInterfaceBlock.h
- libs/filabridge/src/BufferInterfaceBlock.cpp
- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/eiff/MaterialInterfaceBlockChunk.cpp
- libs/filamat/src/shaders/UibGenerator.cpp
- tools/matc/src/matc/ParametersProcessor.cpp
Followup to https://github.com/google/filament/pull/8489
From: https://developer.android.com/reference/android/graphics/SurfaceTexture
When sampling from the texture one should first transform the texture coordinates using the matrix queried via getTransformMatrix(float[]). The transform matrix may change each time updateTexImage() is called, so it should be re-queried each time the texture image is updated.
Adding a way to specify the transform name in the material is the second step to being able to apply it to the uniform in the shader.
> Add a way to specify an additional uniform name along with a sampler param for the associated transform matrix

- libs/filamat/CMakeLists.txt
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/GLSLPostProcessor.h
- libs/filamat/src/MaterialBuilder.cpp
- third_party/dawn/tnt/CMakeLists.txt
> Initial tint transpilation support for WebGPU

- filament/src/details/Renderer.cpp
- filament/src/details/View.cpp
- filament/src/details/View.h
Picking is not designed to work with multiview rendering. Disable it when multiview is enabled.
> Disable picking for multiview rendering

- libs/filamat/src/shaders/CodeGenerator.cpp
Restore workaround for CONFIG_MAX_INSTANCES not being a spec constant, because WGSL does not support that being an array length
BUGS = [399880991]
> Restore workaround for CONFIG_MAX_INSTANCES not being a spec constan

- filament/src/details/Material.cpp
When the feature flags assert_destroy_material_before_material_instance is disabled, we emit a log instead of an assert. Unfortunately this log would be emitted even when all material instances were destroyed.
> Fix material instance check log when destroying material

- filament/backend/CMakeLists.txt
- filament/backend/test/Lifetimes.cpp
- filament/backend/test/Lifetimes.h
- filament/backend/test/test_Blit.cpp
Both for cleaning up graphics resources at the end of a test and for starting/stopping render loops.
> Add helpers for backend tests (cleanup+render loops).

- filament/backend/src/vulkan/VulkanDriver.cpp
The level counting was off by one.
FIXES=400710879
> vk: fix generateMipmaps level

- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/GLSLPostProcessor.h
- samples/CMakeLists.txt
We may need to improve the modularity of `matc` invocations as a custom tool, as this logic fully changes how matc works if WebGPU is enabled, even if someone theoretically wants to test other targets. Until we are enabled by default though that is a minor problem
> Adjust matc targets and flags for WebGPU

- libs/filamat/src/MaterialBuilder.cpp
- tools/matinfo/src/main.cpp
in filamat, enable unpacking WGSL code
BUGS = [397672412]
> webgpu: enable unpacking WGSL code in filamat

- filament/backend/src/webgpu/WebGPUDriver.cpp
WebGPU is broken because of 3abddc4584d63ce72bb8e2ccb11d41af490c0cc8 change
> Fix WebGPU compilation error

- NEW_RELEASE_NOTES.md
- android/filament-android/src/main/java/com/google/android/filament/ColorGrading.java
- android/filament-android/src/main/java/com/google/android/filament/ToneMapper.java
- filament/include/filament/ColorGrading.h
- filament/include/filament/ToneMapper.h
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- filament/src/details/ColorGrading.cpp
- filament/src/details/ColorGrading.h
- filament/src/materials/colorGrading/colorGrading.fs
- filament/src/materials/colorGrading/colorGrading.mat
- filament/src/materials/colorGrading/colorGradingAsSubpass.mat
This introduces two new methods to `ToneMapper`: `isOneDimensional()` and `isLDR()`. `ColorGrading` references these values along with other parameters passed to the builder to determine if we can get away with only generating a one-dimensional LUT. Meanwhile, `PostProcessManager` takes care of setting the new spec constants and uniforms for `colorGrading.mat` and `colorGradingAsSubpass.mat`.
FIXES=[372037228]
> Generate 1D LUTs for color grading when possible

- docs/Materials.md.html
- libs/filabridge/include/filament/MaterialEnums.h
- libs/filamat/src/Enums.cpp
- libs/filamat/src/shaders/CodeGenerator.cpp
- libs/filamat/tests/test_filamat.cpp
- shaders/src/surface_light_directional.fs
- shaders/src/surface_light_punctual.fs
- shaders/src/surface_material_inputs.fs
- shaders/src/surface_shading_unlit.fs
- shaders/src/surface_shadowing.fs
Materials have a new property: shadowStrength that can be used to attenuate all shadows received by this material. e.g.:
```
void material(inout MaterialInputs material) {
prepareMaterial(material);
material.shadowStrength = 0.1;
}
```
FIXES=[391663042]
> Materials can now specify a shadow attenuation factor

- filament/backend/CMakeLists.txt
- filament/backend/src/vulkan/VulkanDescriptorSetCache.cpp
- filament/backend/src/vulkan/VulkanDescriptorSetCache.h
- filament/backend/src/vulkan/VulkanDescriptorSetLayoutCache.cpp
- filament/backend/src/vulkan/VulkanDescriptorSetLayoutCache.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
This is just splitting the layout cache into its own class and files.
> vk: split layout cache from descriptorSet cache

- filament/backend/src/noop/PlatformNoop.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/platforms/PlatformCocoaTouchGL.mm
- filament/backend/src/opengl/platforms/PlatformGLX.cpp
- filament/backend/src/opengl/platforms/PlatformOSMesa.cpp
- filament/backend/src/opengl/platforms/PlatformWGL.cpp
- filament/backend/src/opengl/platforms/PlatformWebGL.cpp
- filament/backend/src/webgpu/platform/WebGPUPlatform.cpp
Replace "void* const" with "void*" as const here serves no purpose because of following reasons:
1. void* const in function parameter has a limited and local effect on the code.
2. clang tidy would complain and report error if const is added to the function declaration.
3. const is dropped later in the call stack making the code incosistent.
> Make decl/def of createDriver api consistent

- NEW_RELEASE_NOTES.md
- docs/Materials.md.html
- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/tests/test_filamat.cpp
- shaders/src/post_process_inputs.vs
- shaders/src/post_process_main.vs
- shaders/src/surface_main.vs
- shaders/src/surface_material_inputs.vs
- shaders/src/surface_varyings.glsl
- tools/matc/src/matc/ParametersProcessor.cpp
Five custom variables (varyings) are now available on the condition that the `color` attribute is not requested.
FIXES=[404930099]
> support up to five custom varyings

- filament/backend/include/backend/platforms/PlatformCocoaGL.h
- filament/backend/include/backend/platforms/PlatformCocoaTouchGL.h
- filament/backend/include/backend/platforms/PlatformEGL.h
- filament/backend/include/backend/platforms/PlatformEGLAndroid.h
- filament/backend/include/backend/platforms/VulkanPlatformAndroid.h
createExternalImagedepends on the user calling into this function directly - by adding UTILS_PUBLIC, we future proof setExternalImage functionality for clients who don't have innate awareness of Filament
> make createExternalImage UTILS_PUBLIC across platforms for future proofing

- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/platform/VulkanPlatform.cpp
Set the support for isProtectedTexturesSupported depending if the context supports protected content or not.
- This will allow creating protected textures and importing protected external images in Vulkan.
- Fix checking if the protected feature is supported on the host after retrieving the results from querying the Physical Device otherwise it will always be false.
> Fix Vulkan protected memory support

- filament/backend/include/backend/DriverEnums.h
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- Some tests require textures larger than 2048. Change the minimum to 4096 for now, and file proper bugs for tests.
- The introduction of uint8_t to DescriptorSetLayoutBinding caused unintended padding with using this struct as a hash key. We comment out the relevent code for now.
> Fix test breaking changes with workarounds

- .github/workflows/presubmit.yml
This is a http://go/LSC run by http://go/ghss to upgrade all self-hosted ubuntu-22.04 runners to ubuntu-24.04.
This is a courtesy PR to help you upgrade to the latest release of ubuntu runners, it is not mandatory at this time.
WARNING: We do not know if the updated label is compatiable with your workflow or not.
If you do not want to merge this PR, feel free to close it.
More context and feedback: http://b/406537467
> Upgrade all self-hosted ubuntu-22.04 runners to ubuntu-24.04.

- filament/src/PostProcessManager.cpp
we were not binding the proper descriptor set. on gl this is only an assert, on vulkan it would be a problem if we supported subpasses, on metal there is no assert.
> fix MSAA custom resolve

- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
Mozilla sometimes clears the generic buffer binding when another buffer is destroyed, if that other buffer is bound on an indexed buffer binding.
The fix makes sure the generic buffer binding is unbound from the context when being destroyed.
BUGS=[376125497]
> Fix INVALID_OPERATION error for WebGL

- filament/backend/src/vulkan/VulkanContext.cpp
- filament/backend/src/vulkan/VulkanDescriptorSetCache.cpp
- filament/backend/src/vulkan/VulkanDescriptorSetCache.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanSwapChain.cpp
- filament/backend/src/vulkan/VulkanSwapChain.h
- filament/backend/src/vulkan/VulkanTexture.cpp
- filament/backend/src/vulkan/VulkanTexture.h
- Refactor VulkanTextureState and VulkanTexture so that most state fields are consts.
- Add a field for VkYcbcrConversion.
- Clear the image view cache when YcbcrConversion changes
- Make sure that getAttachmentView and getView are better defined and called.
> vk: add YcbcrConversion to VulkanTexture

- filament/backend/CMakeLists.txt
- filament/backend/src/vulkan/VulkanContext.h
- filament/backend/src/vulkan/VulkanDescriptorSetCache.cpp
- filament/backend/src/vulkan/VulkanDescriptorSetCache.h
- filament/backend/src/vulkan/VulkanDescriptorSetLayoutCache.cpp
- filament/backend/src/vulkan/VulkanDescriptorSetLayoutCache.h
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/VulkanSamplerCache.cpp
- filament/backend/src/vulkan/VulkanYcbcrConversionCache.cpp
- filament/backend/src/vulkan/VulkanYcbcrConversionCache.h
- filament/backend/src/vulkan/platform/VulkanPlatform.cpp
- filament/backend/src/vulkan/utils/Conversion.cpp
- filament/backend/src/vulkan/utils/Conversion.h
- filament/backend/src/vulkan/utils/Definitions.h
- filament/backend/src/vulkan/utils/Image.cpp
- Move utils functions to the right files
- Add conversion from vk formats to filament
- Refactor how to enable multiview and external sampler in VulkanPlatform
- Make VuklanDescriptorSet and VuklanDescriptorSetLayout more general to allow for mutability
- Reorder vulkan files in CMakeLists.txt to be sorted in alphabetical order.
> vk: preparing for Ycbcr conversion

- filament/backend/include/backend/platforms/VulkanPlatform.h
- filament/backend/src/vulkan/VulkanSwapChain.cpp
- filament/backend/src/vulkan/VulkanSwapChain.h
This function was created to make sure the swapchain image was available before submitting the work to the GPU.
This function is currently not in use so its safe to remove it.
So the order of the process looked like
| Acquire | Begin | Record | Wait | Present | End |
After this change the expectation is that when the swapchain acquires a new image it will also wait until is actually available from the platform.
| Acquire | Begin | Record | Present | End |
In the case the image is not available, the expectation is that the acquire will wait until it is and then start processing the frame.
> VK: Remove explicitImageReadyWait callback

- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanFboCache.cpp
- filament/backend/src/vulkan/VulkanFboCache.h
When a swapchain is resized the FBO cache gets resets which includes the framebuffer and renderpass objects. This causes pipelines to be recreated instead of being reused from the previous frames, causing stalls.
In the case of renderpasses there's no need to clear these objects, since the state of the renderpass is the same, only their refcount should be adjusted, fixing the issue mentioned above.
> VK: Reuse renderpasses after swapchain resize

- filament/backend/src/webgpu/WebGPUDriver.cpp
- filament/backend/src/webgpu/WebGPUHandles.cpp
- filament/backend/src/webgpu/WebGPUHandles.h
Adds the ability to create a webgpu descriptor layout when Filament requests it.
BUGS = [403532779]
> webgpu:   Handle WebGPUDescriptorSetLayout creation

- filament/backend/src/webgpu/WebGPUDriver.cpp
Use names like `Handle<HwBufferObject>` consistently in webgpu
> webgpu: Avoid using handle 'using' redefines for consistency

- filament/backend/src/opengl/GLUtils.cpp
- libs/utils/include/utils/Panic.h
- libs/utils/include/utils/compiler.h
- libs/utils/include/utils/debug.h
clang optimizes code differently with very likely or unlikely  conditions, so we add a `VERY` version of these macros, and we make use of it for assertions.
> Add `UTILS_VERY_[UN]LIKELY` macros

- libs/math/include/math/TQuatHelpers.h
Optimize pow and slerp for quaternions by using the identies sin(acos(x)) = sqrt(1-x^2)
> Optimize slerp for quaternions.

- libs/math/include/math/compiler.h
- libs/math/include/math/half.h
The desired at (https://github.com/google/filament/pull/8599) split operation has been applied 
Clang 20 does not allow customization of standard type_traits
Disabled template customization of standard is_floating_point and is_arithmetic for Clang 20.
Fix: (https://github.com/google/filament/issues/8598)
> Fix Clang 20 compile error: invalid std type trait specializations

- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalHandles.h
- filament/backend/src/metal/MetalHandles.mm
Remove the unused functions and varibles from render primitve and target api's.
> metal driver cleanup

- filament/backend/CMakeLists.txt
Add -DSANITIZATION=ASAN as an argument to CMake to enable.
> Optional CMake flag for enabling ASAN for backend and its tests.

- NEW_RELEASE_NOTES.md
- filament/backend/include/backend/Program.h
- filament/src/MaterialParser.cpp
- filament/src/MaterialParser.h
- filament/src/details/Material.cpp
- libs/filabridge/include/private/filament/DescriptorSets.h
- libs/filabridge/include/private/filament/SamplerInterfaceBlock.h
- libs/filabridge/src/DescriptorSets.cpp
- libs/filabridge/src/SamplerInterfaceBlock.cpp
- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/MaterialVariants.cpp
- libs/filamat/src/eiff/MaterialInterfaceBlockChunk.cpp
- libs/filamat/src/eiff/MaterialInterfaceBlockChunk.h
- libs/filamat/src/shaders/ShaderGenerator.cpp
- libs/filamat/src/shaders/ShaderGenerator.h
I've been going back and forth on whether we information about the
per-view descriptor set layout should be written in the material
file.
In this change, we remove that dependency. By definition the 
"per view" descriptor-set layout should only depend on view parameters
and obviously, all materials must be compatible.
In practice, a material does affect the layout so a reconciliation 
needs to happen somewhere. It's easier to maintain to have all this
logic in one place (in Filament) instead of split between material
generation and filament. 
All this change really does is to remove the information about the
per-view layout from the material file, and move it to Material in
filament, where it is hardcoded (before it was hardcoded in filamat),
but because both sides needed to match there …
> remove dependence on per-view descset layout from filamat

- filament/backend/src/vulkan/VulkanContext.h
- filament/backend/src/vulkan/platform/VulkanPlatform.cpp
This heuristic should work on almost all android
devices, can be extended later as needed.
On non android platforms the default is always false.
> VK: Add a new platform method to check UMA

- test/renderdiff/src/golden_manager.py
- test/renderdiff/src/image_diff.py
- test/renderdiff/src/run.py
- test/renderdiff/src/update_golden.py
- test/renderdiff/src/utils.py
- test/renderdiff/src/workflow_presubmit_msg.py
- test/renderdiff/test.sh
- test/utils/get_mesa.sh
Adding a python script to enable updating new goldens into a staging branch in the golden repo (filament-assets).
The same script can be used in github workflow to automatically create a golden staging branch. This will be useful for users without access to a mac (the only platform for generating goldens as of now).
> renderdiff: script for updating golden images

- libs/utils/include/utils/CString.h
- libs/utils/src/CString.cpp
We add rvalue version of append/insert/replace so that calling those on a temporary yields to a temporary.
Also add string literal versions of those so that we can  append/insert/replace a literal without allocation, e.g.:
`CString foo = CString{ bar }.append("baz");`
This will not end-up creating a temporary CString for "baz".
> CString tidy cleanup and rvalue methods

- build.sh
Failed to build android when using CMake >= 4.0.
Remove a no longer required check for the android build. This check should be covered by the cmake_minimum_required() call, which is present in relevant CMakeLists.txts.
> Clean-up build.sh android

- filament/backend/include/backend/platforms/PlatformMetal.h
- filament/backend/src/metal/PlatformMetal.mm
> Add initialize method to PlatformMetal

- test/renderdiff/generate.sh
- test/renderdiff/src/compare.py
- test/renderdiff/src/golden_manager.py
- test/renderdiff/src/preamble.sh
- test/renderdiff/src/render.py
- test/renderdiff/src/results.py
- test/renderdiff/src/test_config.py
- test/renderdiff/src/update_golden.py
- test/renderdiff/src/utils.py
- test/renderdiff/test.sh
- Move the comparison logic into its own script
- Add entry point bash script to generate the renderings
- Separate the preamble bash logic into its own file
> renderdiff: separate comparison from rendering

- filament/backend/include/backend/DriverEnums.h
- filament/include/filament/BufferObject.h
- filament/include/filament/IndexBuffer.h
- filament/include/filament/VertexBuffer.h
- filament/src/details/BufferObject.cpp
- filament/src/details/IndexBuffer.cpp
- filament/src/details/VertexBuffer.cpp
this affects VerteBuffer, BufferObject and IndexBuffer, this restriction already existed in the Metal backend, it is now promoted to all backends.
> enforce offsets to be a multiple of 4 bytes

- filament/backend/src/webgpu/WebGPUDriver.cpp
- filament/backend/src/webgpu/WebGPUDriver.h
- filament/backend/src/webgpu/WebGPUHandles.cpp
- filament/backend/src/webgpu/WebGPUHandles.h
- third_party/dawn/src/dawn/native/CommandValidation.cpp
BUGS=["416091729"]
Revert our Dawn hack, and both handle sizes that are different than Dawn enforces, but also enforce offset rules which don't have a workaround (At least for now).
> webgpu: Ebridgewater/fix dawn hack

- libs/bluegl/include/GL/glext.h
- libs/bluegl/include/bluegl/BlueGL.h
- libs/bluegl/include/bluegl/BlueGLDefines.h
- libs/bluegl/src/BlueGLCoreDarwinAArch64Impl.S
- libs/bluegl/src/BlueGLCoreDarwinImpl.S
- libs/bluegl/src/BlueGLCoreLinuxAArch64Impl.S
- libs/bluegl/src/BlueGLCoreLinuxImpl.S
- libs/bluegl/src/BlueGLCoreWindows32Impl.cpp
- libs/bluegl/src/BlueGLCoreWindowsImpl.S
- libs/bluegl/src/private_BlueGL.h
This commit adds the `glFramebufferTextureMultisampleMultiviewOVR` function, enabling MSAA to work in conjunction with the multiview extension.
The function's declaration is present in the latest main branch of the Khronos GLES2 API headers. While directly pulling these updated headers is the ideal approach, it would necessitate a significant reorganization of Filament's current header file structure and incorporate more files than currently needed.
To minimize immediate changes and limit scope, this change adopts only the necessary function declaration by copying it directly.
BUGS=[417311684]
> Add glFramebufferTextureMultisampleMultiviewOVR for multiview MSAA

- filament/backend/src/webgpu/WGPUProgram.cpp
Current Workaround until #8773 
BUGS=[397432947]
> webgpu: Ignore spec constants greater than 10

- filament/src/details/Engine.cpp
the default cubemap has RGBA pixels (4 bytes per pixel).
> fix a buffer overflow during init

- libs/filamat/src/GLSLPostProcessor.cpp
Dawn complains when consuming these lines with
WebGPU device error: ErrorType::Validation Error while parsing WGSL: :24:4 error: expected attribute Did you mean 'size'?
Possible values: 'align', 'binding', 'blend_src', 'builtin', 'color', 'compute', 'diagnostic', 'fragment', 'group', 'id', 'input_attachment_index', 'interpolate', 'invariant', 'location', 'must_use', 'size', 'vertex', 'workgroup_size'
@stride(16) @internal(disable_validation__ignore_stride)
And we don't see a better workaround at this time.
BUGS=[397432947]
> Manually remove Tint annotations that Dawn complains about when consuming

- filament/backend/src/webgpu/WebGPUDriver.cpp
- filament/backend/src/webgpu/WebGPUDriver.h
- filament/backend/src/webgpu/WebGPUHandles.h
> webgpu: Relocate calling mRenderPassEncoder.SetBindGroup to draw call, deferring it to handle non-default render targets being used.

- filament/backend/src/opengl/GLDescriptorSet.cpp
- filament/backend/src/opengl/GLDescriptorSet.h
- filament/backend/src/opengl/OpenGLDriver.cpp
There was several issues:
1) when we're switching contexts (e.g. between protect and regular) we
needed up reattach all SurfaceView (i.e. streams), because they need
to be attached on currently active context.
2) reattaching, because it's implemented as detach + attach, would 
destroy the current gl texture id and create a new one. However,
because of the way descriptor-sets were implemented, that GL
texture id was kept inside the descriptor, later leading to using
a destroyed texture id.
The fix here is to store texture handles in descriptors, so that
we can update the id independently. 
3) we also needed to invalidate all bound descriptor sets because it's
now possible for descriptor sets to have outdated descriptors
> attempt to fix external streams with protected context

- filament/src/materials/ssao/gtaoImpl.fs
It is possible that `sqSampleDist` becomes very large in a deep scene, and in this case `mediump` might not be enough for storing this value.
> Fix GTAO artifacts on mobile devices

- libs/utils/include/private/utils/Tracing.h
- libs/utils/src/JobSystem.cpp
The addition JobSystem.cpp allows for defining
FILAMENT_TRACING_ENABLED across targets.
Addingin FILAMENT_TRACING_ENABLED to the #if in Tracing.h prevents perfetto from being included.
> utils: add additional guards for Tracing

- filament/backend/src/webgpu/WebGPUDriver.cpp
- filament/backend/src/webgpu/WebGPUHandles.cpp
- filament/backend/src/webgpu/WebGPUHandles.h
This PR addresses an issue where level and layer values were not consistently applied when creating wgpu::TextureViews for render pass attachments.
> webgpu: Use level and layer in textureViews

- filament/backend/src/vulkan/VulkanTexture.cpp
We didn't take into account the top/left/stride parameters of the PixelBufferDescriptor.
> vk: implement proper offset when uploading to texture

- filament/backend/test/test_ReadPixels.cpp
With the new backend testing framework, this isn't needed anymore.
> Remove old screenshot output for readPixels backend test

- filament/backend/src/opengl/ShaderCompilerService.cpp
When a program was created directly from a cached blob in `ShaderCompilerService`, its associated token was not signaled as ready in the THREAD_POOL mode. This oversight caused a deadlock at the `token->wait()` call during program destruction.
This commit resolves the issue by skipping the token's readiness check upon destruction if the program was created from the cache blob.
BUGS=[423221474]
> Fix: Prevent deadlock when loading programs from cache

- filament/backend/src/webgpu/platform/WebGPUPlatform.cpp
- libs/filabridge/src/DescriptorSets.cpp
This will enable webgpu for devices such as pixel 4, which does not support this feature.
> webgpu: remove float filterable requirement

- filament/src/PostProcessManager.cpp
The assert in resolve() will trigger even if the pass is ultimately not needed (culled out). So if a user has
- disabled postprocessing
- uses stencil buffer
They will still hit an assert in debug mode. Here we just delay the assert until when we're actuallly setting up the pass.
> Fix assert in resolve for stencil buffer

- filament/src/RenderPass.cpp
- filament/src/RenderPass.h
- filament/src/RendererUtils.cpp
- filament/src/RendererUtils.h
- filament/src/details/Renderer.cpp
The problem was that we need to know before rendering if we're doing so directly in the swapchain or an intermediate buffer. Unfortunately  this is determined by the framegraph (after culling and such). But at the point we need it the framefraph is not even constructed.
So we need to "guess" this from the parameters of the View. That logic missed the case where SSR (reflection or refraction) was used.
An extra level of complexity is that we need to generate the high level commands before we can determine if refraction will happen.
Fix #8910
> Fix SSR when postfx and msaa are disabled.

- filament/backend/src/webgpu/WebGPUDriver.cpp
- filament/backend/src/webgpu/WebGPUSwapChain.cpp
- filament/backend/src/webgpu/WebGPUSwapChain.h
Provides a separate constructor to create a headless swapchain. 
Provisions textures and textureViews on initialization and reuses them.
> webgpu: Headless Swapchain 

- android/filament-android/src/main/java/com/google/android/filament/View.java
- filament/include/filament/Options.h
- filament/src/details/View.cpp
- web/filament-js/filament.d.ts
normally dynamic resolution is turned off when timerQueries are no available, but we should still allow it if minScale==maxScale.
FIXES=[428767320]
> dynamic resolution can be always be enable if minScale==maxScale

- .github/workflows/presubmit.yml
- test/renderdiff/local_test.sh
Previously, if a comparison fails then the artifacts are not uploaded.  This is defeats the puprpose of having artifacts. We fix that by moving the test logic into presubmit.yml.
local_test.sh is the way to repro a run from local machine.
> renderdiff: upload artifact even when comparison fails

- CMakeLists.txt
- build.sh
- docs_src/src_mdbook/src/notes/coverage.md
Code coverage is helpful when running backend tests to see which parts of the driver API are exercised.
> Add documentation and flags for generating code coverage report

- filament/backend/include/backend/Program.h
- filament/backend/src/Program.cpp
- filament/src/details/Material.cpp
The invocable sent to Program::diagnostic contains a reference to Material, which could be destroyed by the time the invocable is called. We make sure that invocable does not have a reference.
> Fix dangling material reference after destruction

- .github/workflows/presubmit.yml
- test/renderdiff/src/compare.py
- test/renderdiff/src/viewer.py
- Move upload step to later so that comparison result is also
included in the upload
- Fix the wrong relative paths in the comparison_result.json
- Fix viewer logic to pick only the latest run for a PR.
> renderdiff: fix upload issue second try

- filament/backend/src/vulkan/VulkanBufferProxy.cpp
- filament/backend/src/vulkan/VulkanBufferProxy.h
- filament/backend/src/vulkan/VulkanCommands.cpp
- filament/backend/src/vulkan/VulkanCommands.h
- filament/backend/src/vulkan/VulkanDescriptorSetCache.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanHandles.cpp
- filament/backend/src/vulkan/VulkanHandles.h
- filament/backend/src/vulkan/memory/Resource.h
The previous introduction of VulkanBufferProxy uses the refcount of the backing VulkanBuffer as an indication whether there's a write in progress or not. But we also want to make sure there is no read in progress (i.e. not referenced in a descriptor set). This commit fixes the bookkeeping while trying to clean up the relevant structs.
>  vk: VulkanBuffer cannot skip staging buffer after a read

- tools/resgen/src/main.cpp
A test for how Gemini can clean-up code. Changes:
- Configuration Struct: Global variables have been grouped into an  AppConfig struct. This makes the program's configuration explicit and  avoids polluting the global namespace.
- Clearer Argument Parsing: The handleArguments function now returns an  AppConfig object, encapsulating all parsing logic and making the main  function cleaner.
- Helper Functions: Repetitive tasks like string replacement, file I/O,  and writing file entries have been extracted into small, well-defined  helper functions (replaceAll, openOutputFile, readFile, etc.).
- Simplified main Function: The main function is now a high-level  coordinator, delegating work to helper functions. This makes the overall
program flow much easier to follow.
- Modern C++ Idioms: The …
> cleanup resgen code

- filament/CMakeLists.txt
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- filament/src/RenderPass.h
- filament/src/ShadowMap.cpp
- filament/src/ShadowMap.h
- filament/src/ShadowMapManager.cpp
- filament/src/details/Renderer.cpp
- filament/src/details/Renderer.h
- filament/src/details/View.cpp
- filament/src/details/View.h
- filament/src/ds/ColorPassDescriptorSet.cpp
- filament/src/ds/DescriptorSet.cpp
- filament/src/ds/PerViewDescriptorSetUtils.cpp
- filament/src/ds/PerViewDescriptorSetUtils.h
- filament/src/ds/ShadowMapDescriptorSet.cpp
- filament/src/ds/ShadowMapDescriptorSet.h
- filament/src/ds/StructureDescriptorSet.cpp
- filament/src/ds/StructureDescriptorSet.h
- filament/src/ds/TypedUniformBuffer.h
The per-view UBO is used in several different contexts, for instance:
- during the color pass
- during the shadow pass
- during the structure pass
- during app postfx passes
For shadows and other passes, its content is actually different because
the camera is very different. In that case, we use a different buffer.
However, the code that was used to set the values into the UBO was
duplicated and did slightly different things. In addition some
UBO values were (and are still) probably missing (e.g. the per-material
data).
To improve this situation we new use a utility class that does the
UBO set up of those "shared" values.
It turns out that the structure, ssr and ssao passes also need a 
slightly different content (because they run at half res) and currently
are sharing the color pass UBO, …
> use a separate UBO for the postfx user passes

- filament/src/PostProcessManager.cpp
We use it in
- StructureMipMap
- Separable Blur Pass
- Depth Blit (Shader)
These two passes come before the color pass, but the color pass
needs to write the buffer that is referenced by the post-processing
descriptor set. So we set these passes to use the
StructureDescriptorSet (which has its own UBO). This removes a
synchronization dependency between these two passes and the color
pass.
> ppm: Use structure descriptor per-view set where appropriate

- filament/backend/test/ImageExpectations.cpp
- filament/backend/test/ImageExpectations.h
Instead of importing opencv as I had intended with https://github.com/google/filament/pull/8937 this open codes a very simple, almost trivial image comparison that can nevertheless be expanded to provide image diffs and adjustable image comparison thresholds for golden images.
I had not previously appreciated that this could be quite this simple since the captures generated in these tests are so uniform.
This code is mostly inactive as there are no examples of off-by-one-pixel images in the current test corpus. As such image artifacts are encountered, the allowance of number of non-matching bytes (for errant bad pixels) or the threshold for counting a byte as matching (for color selection variation) can be specified to the constructor of a ScreenshotParams struct for a particular test. …
> Add per-byte image comparison to backend tests

- filament/include/filament/InstanceBuffer.h
- filament/src/RenderPass.cpp
- filament/src/components/RenderableManager.cpp
- filament/src/components/RenderableManager.h
- filament/src/details/InstanceBuffer.cpp
- filament/src/details/InstanceBuffer.h
- filament/src/details/Scene.cpp
- filament/src/details/View.cpp
For some reason the UBO was managed by RenderableManager, but it's a
lot cleaner and easier to have this done by InstanceBuffer itself.
> move the management of the InstanceBuffer's UBO into InstanceBuffer

- filament/src/RendererUtils.cpp
- filament/src/details/Renderer.cpp
- filament/src/details/Renderer.h
Filament used to issue command queue flushes (E.g. glFlush()) after large passes like the color pass in order to kick the gpu into action sooner and reduce latency.  This however comes at a high cost on the gpu timeline as command queue flushes are expensive on vulkan and  metal. Moreover GL drivers are allowed to ignore glFlush().
So we just remove all these calls.
> remove the explicit command queue flushes

- filament/src/MaterialInstanceManager.cpp
- filament/src/MaterialInstanceManager.h
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
In the introduction of MaterialInstanceManager, the assumption is that everytime PostprocessManager wants an instance, we can just provide a "new" one since all of the instance's content - UBOS, textures - will not be shared between passes.  But this is not the right assumption. For `colorGradingPrepareSubpass` and `customResolvePrepareSubpass`, they are filling in an instance for later passes to use.
To address this, we add a way to identify a fixed instance in MaterialInstanceManager. This will allow us to refer to specific instances of a material across passes (for the duration of a frame).
This address the following crashes:
- Enabling custom resolve for MSAA for the metal backend
- Resizing the gltf_viewer window
Also move the dof instance into the loop to prevent UBO reuse.
Remove …
> ppm: add fixed material instance references

- filament/backend/src/vulkan/VulkanDescriptorSetCache.h
- filament/backend/src/vulkan/VulkanDriver.cpp
The issue is that we need to reset the bound info in VulkanDescriptorSetCache when the current command buffer completes recording.
> vk: fix broken iblprefilter path

- filament/src/PostProcessManager.cpp
- filament/src/RendererUtils.cpp
- filament/src/ShadowMapManager.cpp
- filament/src/details/View.cpp
- filament/src/details/View.h
- filament/src/ds/ColorPassDescriptorSet.cpp
- filament/src/ds/ColorPassDescriptorSet.h
- filament/src/ds/DescriptorSet.cpp
- filament/src/ds/DescriptorSet.h
this prevents a false dependency with the next pass and keeps us honest about what resources we're using.
> unbind descriptor-sets after renderpasses

- filament/backend/src/webgpu/WebGPUDriver.cpp
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- We just set a dummy set at the renderable bind point for post-processing passes, since its not used.
- We also fix WebgpuDriver::bindDescriptorSet to properly "unbind" when receiving a null handle.
> ppm: ensure a renderable descriptor set is bound

- filament/src/RenderPass.cpp
- filament/src/details/Material.h
- filament/src/details/MaterialInstance.cpp
- filament/src/details/MaterialInstance.h
This avoids binding unnecessary textures to the pipeline when a shared variant (such as the default depth variant) is used.
> Use default descriptor set for shared material variants

- filament/backend/test/Arguments.cpp
- filament/backend/test/mac_runner.mm
- filament/backend/test/test_Callbacks.cpp
- filament/backend/test/test_FeedbackLoops.cpp
- filament/backend/test/test_LoadImage.cpp
Add "Web GPU" as one of the supported backends for the unit tests. At this time this is just the initial implementation as the tests are currently not running
> Backend tests using webgpu

- filament/src/details/Scene.cpp
- libs/utils/include/utils/bitset.h
- Include <limits> in bitset.h
- The type could not be inferred for Scene.cpp's `SharedState` line.  The failure came from clang version 1:14.0-55~exp2
> Fix two compilation errors

- filament/backend/src/opengl/ShaderCompilerService.cpp
The subsequent call
`glGetShaderiv(shader, GL_COMPILE_STATUS, &status);`
will ensure the compilation is complete.
> Correct warning message

- libs/filabridge/include/private/filament/UibStructs.h
- libs/filamat/src/shaders/UibGenerator.cpp
When running the WebGPU Backend we were getting the error
```
WebGPU device error: VALIDATION [Buffer "buffer_object"] bound with size 2048 at group 0, binding 0 is too small. The pipeline ([RenderPipeline "BakedColor"]) requires a buffer binding which is at least 2064 bytes. This binding is a uniform buffer binding. It is padded to a multiple of 16 bytes, and as a result may be larger than the associated data in the shader source.
- While encoding [RenderPassEncoder (unlabeled)].DrawIndexed(3, 1, 0, 0, 0).
- While finishing [CommandEncoder "frame_comman
```
Reason being that the WGSL was treating fogReserved as a 16 byte aligned item. Therefore having the extra 16 bytes.
Alternatively this change can be an array of math::float4 fogReserved[1] and the reserved at the end can be updated to …
> webgpu: fix buffer misalignment

- NEW_RELEASE_NOTES.md
- shaders/src/surface_brdf.fs
it would automatically degrade to the 2-parameters version in  LOW_QUALITY mode, but some other code relied on the proper calculation, in particular when specularFactor was used.
FIXES=[436866605]
> fix the 3-parameters fresnel calculation

- filament/src/RendererUtils.cpp
the framegraph didn't set the Usage::Stencil on textures it created for the color pass if stencil was requested. On the GL backend it didn't matter because that bit is unused.
> correctly set STENCIL Usage on color pass texture

- filament/src/materials/sgsr/sgsr1_shader_mobile.fs
Running one of the samples resulted in an error due to `std` being a reserved word
> Rename shader std var

- android/filament-android/src/main/java/com/google/android/filament/View.java
- filament/include/filament/Options.h
- filament/src/PostProcessManager.cpp
- filament/src/PostProcessManager.h
- filament/src/details/Renderer.cpp
- web/filament-js/filament.d.ts
A few bugs in that area were introduced by #8391. Upscaling is  supposed to perform the final blending if needed, but it didn't. Transparency/blending is only supported by the bilinear upscaler, which is automatically selected in that case.
The upscaling pass itself may include a final `RCAS` pass for sharpening, in that case, blending must be performed then. So we added the logic for that.
Fixes #9061
> Fix dynamic resolution with TRANSLUCENT views

- filament/backend/test/Arguments.cpp
- filament/backend/test/test_LoadImage.cpp
this PR modifies the LoadImage test with the correct GLSL for WebGPU
it temporarily disable integer format uploads since it prevents webGPU tests from running
> webgpu: Modify Load Image

- libs/filabridge/include/filament/MaterialChunkType.h
- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/MaterialBuilder.cpp
- libs/filament-matp/include/filament-matp/Config.h
- libs/matdbg/src/TextWriter.cpp
- tools/matc/src/matc/CommandlineConfig.cpp
- tools/matc/src/matc/CommandlineConfig.h
- tools/matc/src/matc/MaterialCompiler.cpp
This commit enhances the material compilation process by embedding the `matc` command-line parameters directly into the compiled material file. This feature is valuable for debugging, as it allows developers to inspect the exact compilation settings used for a given material.
A key consideration is the potential for personally identifiable information (PII) in the command-line arguments (e.g., file paths). To address this, a `toPIISafeString` method has been implemented to filter out PII-sensitive options before they are stored in the material.
With this change, the matc command below
/path/to/matc -a opengl --api vulkan -p desktop -g -o /path/to/my.filamat /path/to/my.mat
is stored to the package as below. (veryfied by running `matinfo my.filamat`)
Compilation Parameters:         -a …
> mat: Store matc parameters in material packages

- README.md
- docs_src/build/duplicates.json
- docs_src/src_mdbook/src/main/README.md
- Fix broken links in https://google.github.io/filament/main/
- Make /README.md links consistent
- Add additional replacement recipes for /README.md
- Make /index.html redirect to /dup/intro.html because /index.html has the wrong relative links. This is essentially adding a redirect-only index.html to src_raw.
> docs: fix broken links

- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/GLSLPostProcessor.cpp
- libs/filamat/src/GLSLPostProcessor.h
- libs/filamat/src/MaterialBuilder.cpp
- libs/filament-matp/include/filament-matp/Config.h
- libs/filament-matp/src/MaterialParser.cpp
- tools/matc/src/matc/CommandlineConfig.cpp
Currently the only values possible are `none` and `all`. `all` is the default. This option will be used to control code generation workarounds individually. Currently `all` disables the *MergeReturn* and *Simplification* passes, which have caused issues in the past on some older Android devices.
> add a --workarounds option to matc 

- libs/matdbg/web/app.js
matinfo -w doesn't show the variants for any backend other than metal.  The reason is that the code for updating the variant list wasn't being triggered on currentBackend changes.
> matdbg: fix matinfo no variants bug

- filament/include/filament/View.h
- filament/src/Froxelizer.cpp
- filament/src/Froxelizer.h
- filament/src/View.cpp
- filament/src/details/View.cpp
- filament/src/details/View.h
- filament/src/ds/ColorPassDescriptorSet.cpp
- filament/src/ds/ColorPassDescriptorSet.h
- filament/test/filament_test.cpp
- libs/filabridge/include/private/filament/UibStructs.h
- libs/filamat/src/shaders/UibGenerator.cpp
- libs/filamentapp/CMakeLists.txt
- libs/filamentapp/include/filamentapp/FilamentApp.h
- libs/filamentapp/include/filamentapp/Grid.h
- libs/filamentapp/src/FilamentApp.cpp
- libs/filamentapp/src/Grid.cpp
- samples/gltf_viewer.cpp
- shaders/src/surface_light_punctual.fs
FilamentApp now has debugging options to enable or disable the
camera and directional shadow frustums, as well as the new
"froxel grid" visualization.
"froxel grid" is automatically enabled when "froxel debugging" is
enabled in the debug gui in gltf_viewer.
New corresponding debugging APIs were added to View.
> A new froxel grid vizualization for FilamentApp 

- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanExternalImageManager.cpp
- filament/backend/src/vulkan/VulkanExternalImageManager.h
In the case with external samplers, if another descriptor set gets bound between draw2(), then we need to check to see if a rebinding of the pipeline is necessary.
> vk: check rebind flow if bindDescriptorSet called between draw2

- filament/backend/include/backend/Platform.h
- filament/src/details/Engine.h
This is a temporary resolution until we fix an underlying issue.
> Disable amortized shader compile by default

- filament/src/ZstdHelper.cpp
In ZstdHelper::isCompressed call, `src` may not be aligned to 4 bytes, which is violating the alignment requirement of
`UndefinedBehaviorSanitizer: misaligned-pointer-use`, thereby resuling in a runtime failure with UBSan enabled. So reconstruct the 32-bit integer as a workaround.
> fix: Make ZstdHelper compatible with UBSan

- filament/src/PostProcessManager.cpp
- filament/src/details/View.cpp
- libs/filabridge/src/DescriptorSets.cpp
- libs/filamat/src/shaders/SibGenerator.cpp
In some places, this sampler was incorrectly assumed to be sampler2darray, but it should be just a sampler2d.  Additionally, sampling from it should produce unfiltered values - this has been changed accordingly.
> Fix bones indices and weights sampler + descriptor set

- filament/backend/src/opengl/OpenGLDriver.cpp
In EGLAndroid, external textures imported from an AHB that dont use a SAMPLER_EXTERNAL are not properly destroyed, causing a memory leak that eventually leads to an OOM.
> GL: Fix memory leak for external texture with non external sampler

- libs/math/include/math/TVecHelpers.h
On ARM this generates the fmin/fmax instruction, which avoids branches.
> use fmin/fmax for floating-point

- libs/filabridge/include/private/filament/UibStructs.h
- shaders/src/common_getters.glsl
Make the size of PerViewUib 2KiB again.
Add overloading functions for getEyeFromViewMatrix() and getClipFromWorldMatrix().
BUGS=[441127971]
> Improve getEyeFromViewMatrix()

- filament/src/details/Engine.h
- filament/src/details/Texture.cpp
The backend call `isTextureFormatMipmappable` indicates whether a format can be used to generate bitmap through graphics API.
(The issue is that previously there was a check to validate whether a format is mipmappable and levels > 1. These two conditions do not need to imply one another.)
> Remove unecessary assert on texture format + mipmappable

- filament/backend/test/test_MRT.cpp
layercount should be at least 1. This was causing a validation error for the vk backend when running the test.
> backend: fix MRT test's layercount

- filament/backend/test/test_Blit.cpp
multi-sampled textures are only supported at feature level 2, but on macOS OpenGL is only feature level 1.
> fix OpenGL backend tests on macOS

- filament/backend/include/private/backend/DriverAPI.inc
- filament/backend/src/BackendUtils.cpp
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/webgpu/WebGPUDriver.cpp
- filament/backend/src/webgpu/WebGPUDriver.h
- filament/src/details/BufferObject.cpp
- filament/src/details/Material.cpp
- filament/src/details/MaterialInstance.cpp
- filament/src/details/MorphTargetBuffer.cpp
- filament/src/details/RenderTarget.cpp
- filament/src/details/SkinningBuffer.cpp
- filament/src/details/Texture.cpp
- filament/src/details/VertexBuffer.cpp
This saves a CString copy on the backend side and this forces the
frontend to make a copy explicitly.
In theory the CString should now ever be copied just once.
> pass backend tags by && reference

- filament/src/details/Renderer.cpp
The bug might have been addressed by PR #8952. This workaround is no longer needed.
> vk: remove renderstandalone workaround

- filament/backend/src/metal/MetalContext.mm
- filament/backend/src/metal/MetalEnums.h
> Metal: log command buffer errors

- filament/backend/include/backend/platforms/PlatformEGL.h
- filament/backend/src/opengl/platforms/PlatformEGL.cpp
This change introduces a caching mechanism to store the results of MSAA support queries. The results are stored in a vector, indexed by the power-of-two of the sample count.
> Cache isMSAASwapChainSupported() result for EGL

- filament/backend/include/backend/DriverEnums.h
- filament/backend/include/private/backend/Driver.h
- filament/backend/src/metal/MetalDriver.h
- filament/backend/src/metal/MetalDriver.mm
- filament/backend/src/metal/MetalShaderCompiler.mm
- filament/backend/src/noop/NoopDriver.cpp
- filament/backend/src/noop/NoopDriver.h
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/OpenGLDriver.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/src/webgpu/WebGPUDriver.cpp
- filament/backend/src/webgpu/WebGPUDriver.h
- filament/include/filament/Engine.h
- filament/src/MaterialParser.cpp
- filament/src/details/Engine.h
Allow returning a list of supported shader languages instead of only one.
Notify the backend which is the preferred language. In the case of metal, the preferred language will be the first element in the list.
This change will allow a backend to support multiple languages as needed, in the case of the noop driver, it will support a material with any shader languages.
> Refactor backend getShaderLanguage functions.

- filament/backend/CMakeLists.txt
- filament/backend/src/vulkan/VulkanCommands.cpp
- filament/backend/src/vulkan/VulkanCommands.h
- filament/backend/src/vulkan/VulkanDriver.cpp
- filament/backend/src/vulkan/VulkanDriver.h
- filament/backend/src/vulkan/VulkanSemaphore.cpp
- filament/backend/src/vulkan/VulkanSemaphore.h
- filament/backend/src/vulkan/VulkanSemaphoreManager.cpp
- filament/backend/src/vulkan/VulkanSemaphoreManager.h
- filament/backend/src/vulkan/VulkanSwapChain.cpp
- filament/backend/src/vulkan/VulkanSwapChain.h
- filament/backend/src/vulkan/memory/Resource.cpp
- filament/backend/src/vulkan/memory/Resource.h
- filament/backend/src/vulkan/memory/ResourceManager.cpp
- Add a VulkanSemaphore ref-counted class to track the references of a semamphore - i.e. in a command buffer or in a present.
- Add a VulkanSemaphoreManager class to keep a pool of VkSempahores for better re-use.
This fixes a validation error where we were re-using a semaphore that is associated with a command buffer while its being used in a present (as a wait signal).
Error ris VUID-vkQueueSubmit-pSignalSemaphores-00067
> vk: add pool for VkSemaphore for re-use and lifetime tracking

- test/renderdiff/README.md
- test/renderdiff/generate.sh
- test/renderdiff/local_test.sh
- test/renderdiff/src/compare.py
- test/renderdiff/src/render.py
This option will allow for rendering and comparing a single image or files that match a wildcard-style string.
README.md has been updated
> renderdiff: add a filter option for local testing

- filament/backend/src/opengl/OpenGLContext.cpp
- filament/backend/src/opengl/OpenGLContext.h
- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filament-matp/include/filament-matp/Config.h
The corruption seems to be triggered with a combination of using:
- spirv-opt
- RGBA16F (as opposed to e.g. RGBA8)
- framebuffer_fetch
In this CL we disable framebuffer_fetch for drivers we know have the
issue.
We also reenable NONE as the default for matc workarounds
FIXES=[445721121]
Fix https://github.com/google/filament/issues/7794
>  Workaround a rendering corruption on Mali

- filament/backend/src/vulkan/platform/VulkanPlatform.cpp
Since #9259, CString in VulkanPlatform fall into the literal constructor path. But we really want the null-terminated (char const*) path.  So we cast the strings to (char const*) to enforce null-teriminated behavior.
> vk: fix VulkanPlatform CString usage

- test/renderdiff/local_test.sh
- test/renderdiff/src/compare.py
- test/renderdiff/src/image_diff.py
- test/renderdiff/src/preamble.sh
- test/renderdiff/src/test_config.py
- test/renderdiff/tests/presubmit.json
- test/renderdiff/tests/sample.json
We add a way to define a tolerance for comparing the rendered image vs the golden image.  The tolerance is defined as the maximum pixel value difference (per channel) and the number of out-of-tolerance pixels allowed.
The implementation includes parsing the description (in json), do non-exact comparisons (using numpy), returning the difference stats from the comparison, and the output of the difference as part of the test.
Lastly, we add a simple tolderance to the presubmit test.
> renderdiff: add tolerance to comparison

- NEW_RELEASE_NOTES.md
- filament/backend/include/backend/DriverEnums.h
- filament/backend/include/backend/Program.h
- filament/backend/src/metal/MetalShaderCompiler.mm
- filament/backend/src/opengl/OpenGLDriver.cpp
- filament/backend/src/opengl/ShaderCompilerService.cpp
- filament/backend/src/vulkan/utils/Spirv.cpp
- filament/backend/src/vulkan/utils/Spirv.h
- filament/backend/src/webgpu/WebGPUProgram.cpp
- filament/src/MaterialDefinition.cpp
- filament/src/MaterialDefinition.h
- filament/src/MaterialParser.cpp
- filament/src/details/Material.cpp
- filament/src/details/Material.h
- libs/filabridge/include/private/filament/ConstantInfo.h
- libs/filabridge/include/private/filament/EngineEnums.h
- libs/filamat/include/filamat/MaterialBuilder.h
- libs/filamat/src/MaterialBuilder.cpp
- libs/filamat/src/eiff/MaterialInterfaceBlockChunk.cpp
For a shader program cache to be keyed on the set of spec constants that a program has set, we need to know full exact list of constants, including their default values. If we're going to always hold a list of all constants all the time, then we may as well store them as a simple list where each index is the ID number of the spec constant.
As part of this change, we now write the default values of spec constants into the material file metadata.
> engine: change spec constants to simple list

- libs/filamat/src/GLSLPostProcessor.cpp
this option was ignored and treated as -O0.
> fix matc -E (preprocessor) option
